{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"agoraAi"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/segmodeltype\/agoraai"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/segmodeltype\/agoraai"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/SegModelType\/agoraAi","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"agoraAi"}],"title":"SegModelType.agoraAi","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SegModelType@SegModelAgoraAi","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"SegModelAgoraAi"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/SegModelType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/SegModelType":{"role":"symbol","title":"SegModelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegModelType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/SegModelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegModelType"}],"url":"\/documentation\/agorartckit\/segmodeltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/SegModelType/agoraAi":{"role":"symbol","title":"SegModelType.agoraAi","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"agoraAi"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/SegModelType\/agoraAi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegModelAgoraAi"}],"url":"\/documentation\/agorartckit\/segmodeltype\/agoraai"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SegModelAgoraAi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SegModelAgoraAi"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SegModelAgoraAi"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1SegModelType\/title","value":"SegModelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1SegModelType\/fragments","value":[{"kind":"identifier","text":"SegModelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1SegModelType~1agoraAi\/title","value":"SegModelAgoraAi"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1SegModelType~1agoraAi\/fragments","value":[{"kind":"identifier","text":"SegModelAgoraAi"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}