{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramaxmetadatasizetype\/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramaxmetadatasizetype\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/default","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"title":"AgoraMaxMetadataSizeType.default","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMaxMetadataSizeType@AgoraMaxMetadataSizeTypeDefault","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeDefault"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType":{"role":"symbol","title":"AgoraMaxMetadataSizeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/default":{"role":"symbol","title":"AgoraMaxMetadataSizeType.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeDefault"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/default"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMaxMetadataSizeTypeDefault"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeDefault"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeDefault"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType\/title","value":"AgoraMaxMetadataSizeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1default\/title","value":"AgoraMaxMetadataSizeTypeDefault"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1default\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeDefault"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}