{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramaxmetadatasizetype\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramaxmetadatasizetype\/invalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/invalid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"title":"AgoraMaxMetadataSizeType.invalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMaxMetadataSizeType@AgoraMaxMetadataSizeTypeInvalid","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeInvalid"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/invalid":{"role":"symbol","title":"AgoraMaxMetadataSizeType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeInvalid"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/invalid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType":{"role":"symbol","title":"AgoraMaxMetadataSizeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMaxMetadataSizeTypeInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1invalid\/title","value":"AgoraMaxMetadataSizeTypeInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1invalid\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType\/title","value":"AgoraMaxMetadataSizeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}