{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralastmileproberesultstate\/complete"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralastmileproberesultstate\/complete"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState\/complete","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: The last-mile network probe test is complete."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"}],"title":"AgoraLastmileProbeResultState.complete","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLastmileProbeResultState@AgoraLastmileProbeResultComplete","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeResultComplete"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeResultState/complete":{"role":"symbol","title":"AgoraLastmileProbeResultState.complete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"}],"abstract":[{"type":"text","text":"1: The last-mile network probe test is complete."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState\/complete","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeResultComplete"}],"url":"\/documentation\/agorartckit\/agoralastmileproberesultstate\/complete"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeResultState":{"role":"symbol","title":"AgoraLastmileProbeResultState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLastmileProbeResultState"}],"abstract":[{"type":"text","text":"The status of the last-mile probe test."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeResultState"}],"url":"\/documentation\/agorartckit\/agoralastmileproberesultstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLastmileProbeResultComplete"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeResultComplete"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLastmileProbeResultComplete"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState~1complete\/title","value":"AgoraLastmileProbeResultComplete"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState~1complete\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeResultComplete"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState\/title","value":"AgoraLastmileProbeResultState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeResultState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}