{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralastmileproberesultstate\/unavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralastmileproberesultstate\/unavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState\/unavailable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The last-mile network probe test is not carried out. Probably due to poor network conditions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"title":"AgoraLastmileProbeResultState.unavailable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLastmileProbeResultState@AgoraLastmileProbeResultUnavailable","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeResultUnavailable"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeResultState/unavailable":{"role":"symbol","title":"AgoraLastmileProbeResultState.unavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"abstract":[{"type":"text","text":"3: The last-mile network probe test is not carried out. Probably due to poor network conditions."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState\/unavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeResultUnavailable"}],"url":"\/documentation\/agorartckit\/agoralastmileproberesultstate\/unavailable"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeResultState":{"role":"symbol","title":"AgoraLastmileProbeResultState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLastmileProbeResultState"}],"abstract":[{"type":"text","text":"The status of the last-mile probe test."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResultState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeResultState"}],"url":"\/documentation\/agorartckit\/agoralastmileproberesultstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLastmileProbeResultUnavailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeResultUnavailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLastmileProbeResultUnavailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState~1unavailable\/title","value":"AgoraLastmileProbeResultUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState~1unavailable\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeResultUnavailable"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState\/title","value":"AgoraLastmileProbeResultState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResultState\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeResultState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}