{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetOff"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetoff"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetoff"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOff","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetOff"}],"title":"AgoraHeadphoneEQPreset.audioHeadphoneEQPresetOff","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraHeadphoneEQPreset@AgoraAudioHeadphoneEQPresetOff","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOff"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset":{"role":"symbol","title":"AgoraHeadphoneEQPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/audioHeadphoneEQPresetOff":{"role":"symbol","title":"AgoraHeadphoneEQPreset.audioHeadphoneEQPresetOff","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetOff"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOff","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOff"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetoff"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioHeadphoneEQPresetOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOff"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOff"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/title","value":"AgoraHeadphoneEQPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/fragments","value":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetOff\/title","value":"AgoraAudioHeadphoneEQPresetOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetOff\/fragments","value":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}