{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetInear"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetinear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetinear"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetInear","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetInear"}],"title":"AgoraHeadphoneEQPreset.audioHeadphoneEQPresetInear","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraHeadphoneEQPreset@AgoraAudioHeadphoneEQPresetInear","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetInear"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset":{"role":"symbol","title":"AgoraHeadphoneEQPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/audioHeadphoneEQPresetInear":{"role":"symbol","title":"AgoraHeadphoneEQPreset.audioHeadphoneEQPresetInear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetInear"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetInear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetInear"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetinear"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioHeadphoneEQPresetInear"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetInear"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetInear"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/title","value":"AgoraHeadphoneEQPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/fragments","value":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetInear\/title","value":"AgoraAudioHeadphoneEQPresetInear"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetInear\/fragments","value":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetInear"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}