{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gaming"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreenscenariotype\/gaming"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreenscenariotype\/gaming"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenScenarioType\/gaming","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gaming"}],"title":"AgoraScreenScenarioType.gaming","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraScreenScenarioType@AgoraScreenScenarioGaming","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraScreenScenarioGaming"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenScenarioType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenScenarioType/gaming":{"role":"symbol","title":"AgoraScreenScenarioType.gaming","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gaming"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenScenarioType\/gaming","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenScenarioGaming"}],"url":"\/documentation\/agorartckit\/agorascreenscenariotype\/gaming"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenScenarioType":{"role":"symbol","title":"AgoraScreenScenarioType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenScenarioType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenScenarioType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenScenarioType"}],"url":"\/documentation\/agorartckit\/agorascreenscenariotype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraScreenScenarioGaming"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraScreenScenarioGaming"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraScreenScenarioGaming"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenScenarioType~1gaming\/title","value":"AgoraScreenScenarioGaming"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenScenarioType~1gaming\/fragments","value":[{"kind":"identifier","text":"AgoraScreenScenarioGaming"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenScenarioType\/title","value":"AgoraScreenScenarioType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenScenarioType\/fragments","value":[{"kind":"identifier","text":"AgoraScreenScenarioType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}