{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoEncoderTargetBitrateBps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorauplinknetworkinfo\/videoencodertargetbitratebps"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorauplinknetworkinfo\/videoencodertargetbitratebps"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUplinkNetworkInfo\/videoEncoderTargetBitrateBps","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The target video encoder bitrate (bps)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoEncoderTargetBitrateBps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"videoEncoderTargetBitrateBps","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraUplinkNetworkInfo(py)videoEncoderTargetBitrateBps","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"videoEncoderTargetBitrateBps"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUplinkNetworkInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUplinkNetworkInfo":{"role":"symbol","title":"AgoraUplinkNetworkInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUplinkNetworkInfo"}],"abstract":[{"type":"text","text":"The uplink network information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUplinkNetworkInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUplinkNetworkInfo"}],"url":"\/documentation\/agorartckit\/agorauplinknetworkinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUplinkNetworkInfo/videoEncoderTargetBitrateBps":{"role":"symbol","title":"videoEncoderTargetBitrateBps","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoEncoderTargetBitrateBps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The target video encoder bitrate (bps)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUplinkNetworkInfo\/videoEncoderTargetBitrateBps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoEncoderTargetBitrateBps"}],"url":"\/documentation\/agorartckit\/agorauplinknetworkinfo\/videoencodertargetbitratebps"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoEncoderTargetBitrateBps"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoEncoderTargetBitrateBps"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoEncoderTargetBitrateBps"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUplinkNetworkInfo\/title","value":"AgoraUplinkNetworkInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUplinkNetworkInfo\/fragments","value":[{"kind":"identifier","text":"AgoraUplinkNetworkInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUplinkNetworkInfo~1videoEncoderTargetBitrateBps\/title","value":"videoEncoderTargetBitrateBps"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUplinkNetworkInfo~1videoEncoderTargetBitrateBps\/fragments","value":[{"kind":"identifier","text":"videoEncoderTargetBitrateBps"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}