{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"running"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamingstate\/running"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamingstate\/running"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingState\/running","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The RTMP or RTMPS streaming publishes. The SDK successfully publishes"},{"type":"text","text":" "},{"type":"text","text":"the RTMP or RTMPS streaming and returns this state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"running"}],"title":"AgoraRtmpStreamingState.running","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamingState@AgoraRtmpStreamingStateRunning","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingStateRunning"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingState/running":{"role":"symbol","title":"AgoraRtmpStreamingState.running","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"running"}],"abstract":[{"type":"text","text":"2: The RTMP or RTMPS streaming publishes. The SDK successfully publishes"},{"type":"text","text":" "},{"type":"text","text":"the RTMP or RTMPS streaming and returns this state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingState\/running","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingStateRunning"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingstate\/running"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingState":{"role":"symbol","title":"AgoraRtmpStreamingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingState"}],"abstract":[{"type":"text","text":"States of the Media Push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingState"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamingStateRunning"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingStateRunning"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamingStateRunning"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingState~1running\/title","value":"AgoraRtmpStreamingStateRunning"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingState~1running\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingStateRunning"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingState\/title","value":"AgoraRtmpStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingState\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}