{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCache"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterpreloadstatus\/removecache"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterpreloadstatus\/removecache"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterPreloadStatus\/removeCache","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCache"}],"title":"AgoraMusicContentCenterPreloadStatus.removeCache","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMusicContentCenterPreloadStatus@AgoraMusicContentCenterPreloadStatusRemoveCache","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatusRemoveCache"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterPreloadStatus"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterPreloadStatus/removeCache":{"role":"symbol","title":"AgoraMusicContentCenterPreloadStatus.removeCache","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCache"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterPreloadStatus\/removeCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatusRemoveCache"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterpreloadstatus\/removecache"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterPreloadStatus":{"role":"symbol","title":"AgoraMusicContentCenterPreloadStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatus"}],"abstract":[{"type":"text","text":"The loading statuses of music assets."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterPreloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatus"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterpreloadstatus"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicContentCenterPreloadStatusRemoveCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatusRemoveCache"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatusRemoveCache"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterPreloadStatus~1removeCache\/title","value":"AgoraMusicContentCenterPreloadStatusRemoveCache"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterPreloadStatus~1removeCache\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatusRemoveCache"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterPreloadStatus\/title","value":"AgoraMusicContentCenterPreloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterPreloadStatus\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}