{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerKit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol","text":"AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangedTo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerState","preciseIdentifier":"c:@E@AgoraMediaPlayerState","text":"AgoraMediaPlayerState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerError","preciseIdentifier":"c:@E@AgoraMediaPlayerError","text":"AgoraMediaPlayerError"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"playerKit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See AgoraRtcMediaPlayerProtocol ."}]}]},{"name":"state","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The playback state, see AgoraMediaPlayerState ."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error code. See AgoraMediaPlayerError ."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didchangedto:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didchangedto:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reports the playback state change."},{"type":"text","text":" "},{"type":"text","text":"When the state of the media player changes, the SDK triggers this callback to"},{"type":"text","text":" "},{"type":"text","text":"report the current playback state."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToState:error:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didChangedTo:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerState","preciseIdentifier":"c:@E@AgoraMediaPlayerState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerError","preciseIdentifier":"c:@E@AgoraMediaPlayerError"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerDelegate(im)AgoraRtcMediaPlayer:didChangedToState:error:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate":{"role":"symbol","title":"AgoraRtcMediaPlayerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"abstract":[{"type":"text","text":"Provides callbacks for media players."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerError":{"role":"symbol","title":"AgoraMediaPlayerError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerError"}],"abstract":[{"type":"text","text":"Error codes of the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerError"}],"url":"\/documentation\/agorartckit\/agoramediaplayererror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didChangedTo:error:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToState:error:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didChangedTo:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerState","preciseIdentifier":"c:@E@AgoraMediaPlayerState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerError","preciseIdentifier":"c:@E@AgoraMediaPlayerError"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reports the playback state change."},{"type":"text","text":" "},{"type":"text","text":"When the state of the media player changes, the SDK triggers this callback to"},{"type":"text","text":" "},{"type":"text","text":"report the current playback state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didchangedto:error:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerState":{"role":"symbol","title":"AgoraMediaPlayerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerState"}],"abstract":[{"type":"text","text":"The playback state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerState"}],"url":"\/documentation\/agorartckit\/agoramediaplayerstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcMediaPlayer:didChangedToState:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToState:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraRtcMediaPlayerProtocol>","preciseIdentifier":"c:Qoobjc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerKit"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangedToState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerState","preciseIdentifier":"c:@E@AgoraMediaPlayerState","text":"AgoraMediaPlayerState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerError","preciseIdentifier":"c:@E@AgoraMediaPlayerError","text":"AgoraMediaPlayerError"},{"kind":"text","text":") "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/title","value":"AgoraRtcMediaPlayerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerError\/title","value":"AgoraMediaPlayerError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerError\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didChangedTo:error:)\/title","value":"AgoraRtcMediaPlayer:didChangedToState:error:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didChangedTo:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToState:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerState\/title","value":"AgoraMediaPlayerState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerState\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}