{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerKit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol","text":"AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":" "},{"kind":"internalParam","text":"eventCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent","preciseIdentifier":"c:@E@AgoraMediaPlayerEvent","text":"AgoraMediaPlayerEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsedTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didoccur:elapsedtime:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didoccur:elapsedtime:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerEvent","preciseIdentifier":"c:@E@AgoraMediaPlayerEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsedTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerDelegate(im)AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerEvent","preciseIdentifier":"c:@E@AgoraMediaPlayerEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsedTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didoccur:elapsedtime:message:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent":{"role":"symbol","title":"AgoraMediaPlayerEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"abstract":[{"type":"text","text":"Media player events."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate":{"role":"symbol","title":"AgoraRtcMediaPlayerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"abstract":[{"type":"text","text":"Provides callbacks for media players."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraRtcMediaPlayerProtocol>","preciseIdentifier":"c:Qoobjc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"playerKit"},{"kind":"text","text":" "},{"kind":"identifier","text":"didOccurEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent","preciseIdentifier":"c:@E@AgoraMediaPlayerEvent","text":"AgoraMediaPlayerEvent"},{"kind":"text","text":")"},{"kind":"internalParam","text":"eventCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"elapsedTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"elapsedTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)\/title","value":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/title","value":"AgoraMediaPlayerEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/title","value":"AgoraRtcMediaPlayerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}