{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"join2JoinSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/join2joinsuccess"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/join2joinsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/join2JoinSuccess","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Time interval from calling joinChannelByToken [2\/4] to successfully joining the channel. The unit is milliseconds."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"join2JoinSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"join2JoinSuccess","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoRenderingTracingInfo(py)join2JoinSuccess","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"join2JoinSuccess"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo":{"role":"symbol","title":"AgoraVideoRenderingTracingInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"abstract":[{"type":"text","text":"Indicators during video frame rendering progress."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/join2JoinSuccess":{"role":"symbol","title":"join2JoinSuccess","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"join2JoinSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Time interval from calling joinChannelByToken [2\/4] to successfully joining the channel. The unit is milliseconds."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/join2JoinSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"join2JoinSuccess"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/join2joinsuccess"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"join2JoinSuccess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"join2JoinSuccess"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"join2JoinSuccess"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/title","value":"AgoraVideoRenderingTracingInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1join2JoinSuccess\/title","value":"join2JoinSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1join2JoinSuccess\/fragments","value":[{"kind":"identifier","text":"join2JoinSuccess"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}