{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoined2UnmuteVideo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/remotejoined2unmutevideo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/remotejoined2unmutevideo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2UnmuteVideo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If the local user calls startMediaRenderingTracing before the remote user"},{"type":"text","text":" "},{"type":"text","text":"joins the channel, this value is the time interval from the remote user"},{"type":"text","text":" "},{"type":"text","text":"joining the channel to subscribing to the remote video stream. The unit is"},{"type":"text","text":" "},{"type":"text","text":"milliseconds.If the local user calls startMediaRenderingTracing after the"},{"type":"text","text":" "},{"type":"text","text":"remote user joins the channel, this value is the time interval from calling"},{"type":"text","text":" "},{"type":"text","text":"startMediaRenderingTracing to subscribing to the remote video stream. The"},{"type":"text","text":" "},{"type":"text","text":"unit is milliseconds.If the local user calls startMediaRenderingTracing after"},{"type":"text","text":" "},{"type":"text","text":"subscribing to the remote video stream, the value is 0 and meaningless.In"},{"type":"text","text":" "},{"type":"text","text":"order to reduce the time of rendering the first frame for remote users, Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends that after the remote user joins the channel, the local user"},{"type":"text","text":" "},{"type":"text","text":"immediately subscribes to the remote video stream to reduce this value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoined2UnmuteVideo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"remoteJoined2UnmuteVideo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoRenderingTracingInfo(py)remoteJoined2UnmuteVideo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"remoteJoined2UnmuteVideo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/remoteJoined2UnmuteVideo":{"role":"symbol","title":"remoteJoined2UnmuteVideo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoined2UnmuteVideo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"If the local user calls startMediaRenderingTracing before the remote user"},{"type":"text","text":" "},{"type":"text","text":"joins the channel, this value is the time interval from the remote user"},{"type":"text","text":" "},{"type":"text","text":"joining the channel to subscribing to the remote video stream. The unit is"},{"type":"text","text":" "},{"type":"text","text":"milliseconds.If the local user calls startMediaRenderingTracing after the"},{"type":"text","text":" "},{"type":"text","text":"remote user joins the channel, this value is the time interval from calling"},{"type":"text","text":" "},{"type":"text","text":"startMediaRenderingTracing to subscribing to the remote video stream. The"},{"type":"text","text":" "},{"type":"text","text":"unit is milliseconds.If the local user calls startMediaRenderingTracing after"},{"type":"text","text":" "},{"type":"text","text":"subscribing to the remote video stream, the value is 0 and meaningless.In"},{"type":"text","text":" "},{"type":"text","text":"order to reduce the time of rendering the first frame for remote users, Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends that after the remote user joins the channel, the local user"},{"type":"text","text":" "},{"type":"text","text":"immediately subscribes to the remote video stream to reduce this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2UnmuteVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteJoined2UnmuteVideo"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/remotejoined2unmutevideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo":{"role":"symbol","title":"AgoraVideoRenderingTracingInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"abstract":[{"type":"text","text":"Indicators during video frame rendering progress."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"remoteJoined2UnmuteVideo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"remoteJoined2UnmuteVideo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoined2UnmuteVideo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2UnmuteVideo\/title","value":"remoteJoined2UnmuteVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2UnmuteVideo\/fragments","value":[{"kind":"identifier","text":"remoteJoined2UnmuteVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/title","value":"AgoraVideoRenderingTracingInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}