{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rtmpStreamingChangedToState"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingState","preciseIdentifier":"c:@E@AgoraRtmpStreamingState","text":"AgoraRtmpStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode","preciseIdentifier":"c:@E@AgoraRtmpStreamingErrorCode","text":"AgoraRtmpStreamingErrorCode"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:rtmpstreamingchangedtostate:state:errcode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:rtmpstreamingchangedtostate:state:errcode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"}],"role":"symbol","title":"rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rtmpStreamingChangedToState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamingState","preciseIdentifier":"c:@E@AgoraRtmpStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamingErrorCode","preciseIdentifier":"c:@E@AgoraRtmpStreamingErrorCode"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraBaseDelegate(im)rtcEngine:rtmpStreamingChangedToState:state:errCode:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingState":{"role":"symbol","title":"AgoraRtmpStreamingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingState"}],"abstract":[{"type":"text","text":"States of the Media Push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingState"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingErrorCode":{"role":"symbol","title":"AgoraRtmpStreamingErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"abstract":[{"type":"text","text":"Error codes of the RTMP or RTMPS streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"}],"role":"symbol","title":"rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rtmpStreamingChangedToState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamingState","preciseIdentifier":"c:@E@AgoraRtmpStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamingErrorCode","preciseIdentifier":"c:@E@AgoraRtmpStreamingErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:rtmpstreamingchangedtostate:state:errcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate":{"role":"symbol","title":"AgoraBaseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseDelegate"}],"url":"\/documentation\/agorartckit\/agorabasedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmpStreamingChangedToState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"state:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingState","preciseIdentifier":"c:@E@AgoraRtmpStreamingState","text":"AgoraRtmpStreamingState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"state"},{"kind":"text","text":" "},{"kind":"identifier","text":"errCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode","preciseIdentifier":"c:@E@AgoraRtmpStreamingErrorCode","text":"AgoraRtmpStreamingErrorCode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"errCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingState\/title","value":"AgoraRtmpStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingState\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/title","value":"AgoraRtmpStreamingErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)\/title","value":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/title","value":"AgoraBaseDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraBaseDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}