{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType","preciseIdentifier":"c:@E@AgoraEncryptionErrorType","text":"AgoraEncryptionErrorType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didoccur:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didoccur:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccur:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncryptionErrorType","preciseIdentifier":"c:@E@AgoraEncryptionErrorType"},{"kind":"text","text":")"}],"title":"rtcEngine(_:didOccur:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraBaseDelegate(im)rtcEngine:didOccurEncryptionError:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didOccurEncryptionError:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType":{"role":"symbol","title":"AgoraEncryptionErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"abstract":[{"type":"text","text":"Encryption error type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"url":"\/documentation\/agorartckit\/agoraencryptionerrortype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate":{"role":"symbol","title":"AgoraBaseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseDelegate"}],"url":"\/documentation\/agorartckit\/agorabasedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didOccur:)":{"role":"symbol","title":"rtcEngine(_:didOccur:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncryptionErrorType","preciseIdentifier":"c:@E@AgoraEncryptionErrorType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccur:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didOccurEncryptionError:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didoccur:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:didOccurEncryptionError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didOccurEncryptionError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"didOccurEncryptionError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType","preciseIdentifier":"c:@E@AgoraEncryptionErrorType","text":"AgoraEncryptionErrorType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"errorType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType\/title","value":"AgoraEncryptionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/title","value":"AgoraBaseDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraBaseDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didOccur:)\/title","value":"rtcEngine:didOccurEncryptionError:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didOccur:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didOccurEncryptionError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}