{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClientRoleChanged"},{"kind":"text","text":" "},{"kind":"internalParam","text":"oldRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRoleOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions","text":"AgoraClientRoleOptions"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didclientrolechanged:newrole:newroleoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didclientrolechanged:newrole:newroleoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClientRoleChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRoleOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions"},{"kind":"text","text":"?)"}],"title":"rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraBaseDelegate(im)rtcEngine:didClientRoleChanged:newRole:newRoleOptions:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate":{"role":"symbol","title":"AgoraBaseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseDelegate"}],"url":"\/documentation\/agorartckit\/agorabasedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)":{"role":"symbol","title":"rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClientRoleChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRoleOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didclientrolechanged:newrole:newroleoptions:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleOptions":{"role":"symbol","title":"AgoraClientRoleOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleOptions"}],"abstract":[{"type":"text","text":"Setting of user role properties."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleOptions"}],"url":"\/documentation\/agorartckit\/agoraclientroleoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRole":{"role":"symbol","title":"AgoraClientRole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRole"}],"abstract":[{"type":"text","text":"The user role in the interactive live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRole"}],"url":"\/documentation\/agorartckit\/agoraclientrole"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClientRoleChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":")"},{"kind":"internalParam","text":"oldRole"},{"kind":"text","text":" "},{"kind":"identifier","text":"newRole:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":")"},{"kind":"internalParam","text":"newRole"},{"kind":"text","text":" "},{"kind":"identifier","text":"newRoleOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions","text":"AgoraClientRoleOptions"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"newRoleOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/title","value":"AgoraBaseDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraBaseDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)\/title","value":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions\/title","value":"AgoraClientRoleOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRole\/title","value":"AgoraClientRole"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRole\/fragments","value":[{"kind":"identifier","text":"AgoraClientRole"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}