{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"observerPositionPlayback"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition\/observerpositionplayback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition\/observerpositionplayback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition\/observerPositionPlayback","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Only records the audio of all remote users."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"observerPositionPlayback"}],"title":"AgoraAudioEncodedFrameDelegatePosition.observerPositionPlayback","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioEncodedFrameDelegatePosition@AgoraAudioEncodedFrameObserverPositionPlayback","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionPlayback"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegatePosition/observerPositionPlayback":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegatePosition.observerPositionPlayback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"observerPositionPlayback"}],"abstract":[{"type":"text","text":"2: Only records the audio of all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition\/observerPositionPlayback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionPlayback"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition\/observerpositionplayback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegatePosition":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegatePosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegatePosition"}],"abstract":[{"type":"text","text":"Audio profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegatePosition"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEncodedFrameObserverPositionPlayback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionPlayback"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionPlayback"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition~1observerPositionPlayback\/title","value":"AgoraAudioEncodedFrameObserverPositionPlayback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition~1observerPositionPlayback\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionPlayback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition\/title","value":"AgoraAudioEncodedFrameDelegatePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegatePosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}