{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"observerPositionMixed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition\/observerpositionmixed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition\/observerpositionmixed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition\/observerPositionMixed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: Records the mixed audio of the local and all remote users."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"observerPositionMixed"}],"title":"AgoraAudioEncodedFrameDelegatePosition.observerPositionMixed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioEncodedFrameDelegatePosition@AgoraAudioEncodedFrameObserverPositionMixed","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionMixed"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegatePosition/observerPositionMixed":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegatePosition.observerPositionMixed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"observerPositionMixed"}],"abstract":[{"type":"text","text":"3: Records the mixed audio of the local and all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition\/observerPositionMixed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionMixed"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition\/observerpositionmixed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegatePosition":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegatePosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegatePosition"}],"abstract":[{"type":"text","text":"Audio profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegatePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegatePosition"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateposition"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEncodedFrameObserverPositionMixed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionMixed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionMixed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition~1observerPositionMixed\/title","value":"AgoraAudioEncodedFrameObserverPositionMixed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition~1observerPositionMixed\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameObserverPositionMixed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition\/title","value":"AgoraAudioEncodedFrameDelegatePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegatePosition\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegatePosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}