{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpProxyType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraproxytype\/tcpproxytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraproxytype\/tcpproxytype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpProxyType"}],"title":"AgoraProxyType.tcpProxyType","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraProxyType@AgoraTcpProxyType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraTcpProxyType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType":{"role":"symbol","title":"AgoraProxyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/tcpProxyType":{"role":"symbol","title":"AgoraProxyType.tcpProxyType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraTcpProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/tcpproxytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraTcpProxyType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraTcpProxyType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraTcpProxyType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType\/title","value":"AgoraProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraProxyType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1tcpProxyType\/title","value":"AgoraTcpProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1tcpProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraTcpProxyType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}