{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenAudioParameters","preciseIdentifier":"c:objc(cs)AgoraScreenAudioParameters","text":"AgoraScreenAudioParameters"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreencaptureparameters2\/audioparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreencaptureparameters2\/audioparams"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2\/audioParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The audio configuration for the shared screen stream. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraScreenAudioParameters .This parameter only takes effect when"},{"type":"text","text":" "},{"type":"text","text":"captureAudio is YES."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraScreenAudioParameters","preciseIdentifier":"c:objc(cs)AgoraScreenAudioParameters"}],"title":"audioParams","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraScreenCaptureParameters2(py)audioParams","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"audioParams"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureParameters2/audioParams":{"role":"symbol","title":"audioParams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraScreenAudioParameters","preciseIdentifier":"c:objc(cs)AgoraScreenAudioParameters"}],"abstract":[{"type":"text","text":"The audio configuration for the shared screen stream. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraScreenAudioParameters .This parameter only takes effect when"},{"type":"text","text":" "},{"type":"text","text":"captureAudio is YES."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2\/audioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioParams"}],"url":"\/documentation\/agorartckit\/agorascreencaptureparameters2\/audioparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureParameters2":{"role":"symbol","title":"AgoraScreenCaptureParameters2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"abstract":[{"type":"text","text":"Screen sharing configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"url":"\/documentation\/agorartckit\/agorascreencaptureparameters2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenAudioParameters":{"role":"symbol","title":"AgoraScreenAudioParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenAudioParameters"}],"abstract":[{"type":"text","text":"The audio configuration for the shared screen stream."},{"type":"text","text":" "},{"type":"text","text":"Only available where captureAudio is YES."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenAudioParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenAudioParameters"}],"url":"\/documentation\/agorartckit\/agorascreenaudioparameters"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audioParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioParams"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenAudioParameters","preciseIdentifier":"c:objc(cs)AgoraScreenAudioParameters","text":"AgoraScreenAudioParameters"},{"kind":"text","text":" * "},{"kind":"identifier","text":"audioParams"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2~1audioParams\/title","value":"audioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2~1audioParams\/fragments","value":[{"kind":"identifier","text":"audioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/title","value":"AgoraScreenCaptureParameters2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenAudioParameters\/title","value":"AgoraScreenAudioParameters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenAudioParameters\/fragments","value":[{"kind":"identifier","text":"AgoraScreenAudioParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}