{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters","preciseIdentifier":"c:objc(cs)AgoraScreenVideoParameters","text":"AgoraScreenVideoParameters"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreencaptureparameters2\/videoparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreencaptureparameters2\/videoparams"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2\/videoParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The video configuration for the shared screen stream. See AgoraScreenVideoParameters.This parameter only takes effect when captureVideo is YES."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraScreenVideoParameters","preciseIdentifier":"c:objc(cs)AgoraScreenVideoParameters"}],"title":"videoParams","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraScreenCaptureParameters2(py)videoParams","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"videoParams"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureParameters2/videoParams":{"role":"symbol","title":"videoParams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraScreenVideoParameters","preciseIdentifier":"c:objc(cs)AgoraScreenVideoParameters"}],"abstract":[{"type":"text","text":"The video configuration for the shared screen stream. See AgoraScreenVideoParameters.This parameter only takes effect when captureVideo is YES."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2\/videoParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoParams"}],"url":"\/documentation\/agorartckit\/agorascreencaptureparameters2\/videoparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureParameters2":{"role":"symbol","title":"AgoraScreenCaptureParameters2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"abstract":[{"type":"text","text":"Screen sharing configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"url":"\/documentation\/agorartckit\/agorascreencaptureparameters2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters":{"role":"symbol","title":"AgoraScreenVideoParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"abstract":[{"type":"text","text":"The video configuration for the shared screen stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoParams"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters","preciseIdentifier":"c:objc(cs)AgoraScreenVideoParameters","text":"AgoraScreenVideoParameters"},{"kind":"text","text":" * "},{"kind":"identifier","text":"videoParams"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2~1videoParams\/title","value":"videoParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2~1videoParams\/fragments","value":[{"kind":"identifier","text":"videoParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/title","value":"AgoraScreenCaptureParameters2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters\/title","value":"AgoraScreenVideoParameters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters\/fragments","value":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}