{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRecovery"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioremotereason\/networkrecovery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioremotereason\/networkrecovery"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkRecovery","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Network recovery."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRecovery"}],"title":"AgoraAudioRemoteReason.networkRecovery","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioRemoteReason@AgoraAudioRemoteReasonNetworkRecovery","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkRecovery"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/networkRecovery":{"role":"symbol","title":"AgoraAudioRemoteReason.networkRecovery","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRecovery"}],"abstract":[{"type":"text","text":"2: Network recovery."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkRecovery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkRecovery"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/networkrecovery"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason":{"role":"symbol","title":"AgoraAudioRemoteReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteReason"}],"abstract":[{"type":"text","text":"The reason for the remote audio state change."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReason"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioRemoteReasonNetworkRecovery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkRecovery"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkRecovery"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1networkRecovery\/title","value":"AgoraAudioRemoteReasonNetworkRecovery"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1networkRecovery\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkRecovery"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason\/title","value":"AgoraAudioRemoteReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}