{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardware"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/hardware"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/hardware"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/hardware","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Hardware encoding is applied for acceleration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardware"}],"title":"AgoraVideoHwEncoderAccelerating.hardware","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoHwEncoderAccelerating@AgoraVideoHwEncoderHardware","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderHardware"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating/hardware":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating.hardware","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardware"}],"abstract":[{"type":"text","text":"1: Hardware encoding is applied for acceleration."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/hardware","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderHardware"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/hardware"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"abstract":[{"type":"text","text":"The local video encoding acceleration type."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoHwEncoderHardware"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderHardware"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoHwEncoderHardware"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1hardware\/title","value":"AgoraVideoHwEncoderHardware"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1hardware\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderHardware"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/title","value":"AgoraVideoHwEncoderAccelerating"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}