{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"software"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/software"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/software"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/software","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: Software encoding is applied without acceleration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"software"}],"title":"AgoraVideoHwEncoderAccelerating.software","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoHwEncoderAccelerating@AgoraVideoHwEncoderSoftware","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderSoftware"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating/software":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating.software","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"software"}],"abstract":[{"type":"text","text":"0: Software encoding is applied without acceleration."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/software","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderSoftware"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/software"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"abstract":[{"type":"text","text":"The local video encoding acceleration type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoHwEncoderSoftware"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderSoftware"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoHwEncoderSoftware"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1software\/title","value":"AgoraVideoHwEncoderSoftware"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1software\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderSoftware"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/title","value":"AgoraVideoHwEncoderAccelerating"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}