{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dark"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/dark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/dark"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/dark","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The brightness level of the video image is too dark."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dark"}],"title":"AgoraCaptureBrightnessLevelType.dark","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCaptureBrightnessLevelType@AgoraCaptureBrightnessLevelDark","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelDark"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"abstract":[{"type":"text","text":"The brightness level of the video image captured by the local camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/dark":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType.dark","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dark"}],"abstract":[{"type":"text","text":"2: The brightness level of the video image is too dark."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/dark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelDark"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/dark"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCaptureBrightnessLevelDark"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelDark"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelDark"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/title","value":"AgoraCaptureBrightnessLevelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1dark\/title","value":"AgoraCaptureBrightnessLevelDark"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1dark\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelDark"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}