{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/invalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/invalid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"-1: The SDK does not detect the brightness level of the video image. Wait a"},{"type":"text","text":" "},{"type":"text","text":"few seconds to get the brightness level from captureBrightnessLevel in the"},{"type":"text","text":" "},{"type":"text","text":"next callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"title":"AgoraCaptureBrightnessLevelType.invalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCaptureBrightnessLevelType@AgoraCaptureBrightnessLevelInvalid","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelInvalid"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/invalid":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"-1: The SDK does not detect the brightness level of the video image. Wait a"},{"type":"text","text":" "},{"type":"text","text":"few seconds to get the brightness level from captureBrightnessLevel in the"},{"type":"text","text":" "},{"type":"text","text":"next callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelInvalid"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/invalid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"abstract":[{"type":"text","text":"The brightness level of the video image captured by the local camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCaptureBrightnessLevelInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1invalid\/title","value":"AgoraCaptureBrightnessLevelInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1invalid\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/title","value":"AgoraCaptureBrightnessLevelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}