{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracontentinspectmodule\/interval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracontentinspectmodule\/interval"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectModule\/interval","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The frequency (s) of video screenshot and upload. The value should be set as"},{"type":"text","text":" "},{"type":"text","text":"larger than 0. The default value is 0, the SDK does not take screenshots."},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you set the value as 10; you can also adjust it"},{"type":"text","text":" "},{"type":"text","text":"according to your business needs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"interval","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraContentInspectModule(py)interval","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"interval"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectModule"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectModule":{"role":"symbol","title":"AgoraContentInspectModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectModule"}],"abstract":[{"type":"text","text":"A structure used to configure the frequency of video screenshot and"},{"type":"text","text":" "},{"type":"text","text":"upload.AgoraContentInspectModule"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectModule"}],"url":"\/documentation\/agorartckit\/agoracontentinspectmodule"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectModule/interval":{"role":"symbol","title":"interval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The frequency (s) of video screenshot and upload. The value should be set as"},{"type":"text","text":" "},{"type":"text","text":"larger than 0. The default value is 0, the SDK does not take screenshots."},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you set the value as 10; you can also adjust it"},{"type":"text","text":" "},{"type":"text","text":"according to your business needs."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectModule\/interval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"interval"}],"url":"\/documentation\/agorartckit\/agoracontentinspectmodule\/interval"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"interval"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"interval"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"interval"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectModule\/title","value":"AgoraContentInspectModule"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectModule\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectModule"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectModule~1interval\/title","value":"interval"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectModule~1interval\/fragments","value":[{"kind":"identifier","text":"interval"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}