{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraremotevoicepositioninfo\/forward"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraremotevoicepositioninfo\/forward"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRemoteVoicePositionInfo\/forward","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The unit vector of the x axis in the coordinate system. This parameter is an"},{"type":"text","text":" "},{"type":"text","text":"array of length 3, and the three values represent the front, right, and top"},{"type":"text","text":" "},{"type":"text","text":"coordinates in turn."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?"}],"title":"forward","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRemoteVoicePositionInfo(py)forward","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"forward"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRemoteVoicePositionInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRemoteVoicePositionInfo/forward":{"role":"symbol","title":"forward","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The unit vector of the x axis in the coordinate system. This parameter is an"},{"type":"text","text":" "},{"type":"text","text":"array of length 3, and the three values represent the front, right, and top"},{"type":"text","text":" "},{"type":"text","text":"coordinates in turn."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRemoteVoicePositionInfo\/forward","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"forward"}],"url":"\/documentation\/agorartckit\/agoraremotevoicepositioninfo\/forward"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRemoteVoicePositionInfo":{"role":"symbol","title":"AgoraRemoteVoicePositionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRemoteVoicePositionInfo"}],"abstract":[{"type":"text","text":"The spatial position of the remote user or the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRemoteVoicePositionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRemoteVoicePositionInfo"}],"url":"\/documentation\/agorartckit\/agoraremotevoicepositioninfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"forward"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"forward"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"forward"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRemoteVoicePositionInfo~1forward\/title","value":"forward"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRemoteVoicePositionInfo~1forward\/fragments","value":[{"kind":"identifier","text":"forward"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRemoteVoicePositionInfo\/title","value":"AgoraRemoteVoicePositionInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRemoteVoicePositionInfo\/fragments","value":[{"kind":"identifier","text":"AgoraRemoteVoicePositionInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}