{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEncodedVideoFrameReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoFrameInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoFrameInfo","text":"AgoraEncodedVideoFrameInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Reserved for future use."}]}]},{"kind":"parameters","parameters":[{"name":"videoData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encoded video image data."}]}]},{"name":"length","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The data length of the video image."}]}]},{"name":"videoFrameInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For the information of the encoded video frame, see AgoraEncodedVideoFrameInfo."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you call the setRemoteVideoSubscriptionOptions method and set encodedFrameOnly to YES , the SDK triggers this callback locally to report the received encoded video frame information."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodedvideoframedelegate\/onencodedvideoframereceived(_:length:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodedvideoframedelegate\/onencodedvideoframereceived(_:length:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameDelegate\/onEncodedVideoFrameReceived(_:length:info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reports that the receiver has received the to-be-decoded video frame sent by the remote end."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onEncodedVideoFrameReceived:length:info:"}],"role":"symbol","title":"onEncodedVideoFrameReceived(_:length:info:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEncodedVideoFrameReceived"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedVideoFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoFrameInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraEncodedVideoFrameDelegate(im)onEncodedVideoFrameReceived:length:info:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameDelegate":{"role":"symbol","title":"AgoraEncodedVideoFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoFrameDelegate"}],"abstract":[{"type":"text","text":"Receives encoded video images."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo":{"role":"symbol","title":"AgoraEncodedVideoFrameInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameDelegate/onEncodedVideoFrameReceived(_:length:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onEncodedVideoFrameReceived:length:info:"}],"role":"symbol","title":"onEncodedVideoFrameReceived(_:length:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEncodedVideoFrameReceived"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedVideoFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoFrameInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Reports that the receiver has received the to-be-decoded video frame sent by the remote end."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameDelegate\/onEncodedVideoFrameReceived(_:length:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraencodedvideoframedelegate\/onencodedvideoframereceived(_:length:info:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onEncodedVideoFrameReceived:length:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEncodedVideoFrameReceived:length:info:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onEncodedVideoFrameReceived:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"videoData"},{"kind":"text","text":" "},{"kind":"identifier","text":"length:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"size_t","preciseIdentifier":"c:@T@size_t"},{"kind":"text","text":")"},{"kind":"internalParam","text":"length"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoFrameInfo","text":"AgoraEncodedVideoFrameInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"videoFrameInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameDelegate\/title","value":"AgoraEncodedVideoFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo\/title","value":"AgoraEncodedVideoFrameInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameDelegate~1onEncodedVideoFrameReceived(_:length:info:)\/title","value":"onEncodedVideoFrameReceived:length:info:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameDelegate~1onEncodedVideoFrameReceived(_:length:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEncodedVideoFrameReceived:length:info:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}