{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode","text":"AgoraVideoRenderMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcvideocanvas\/rendermode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcvideocanvas\/rendermode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas\/renderMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The rendering mode of the video. See AgoraVideoRenderMode ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"}],"title":"renderMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcVideoCanvas(py)renderMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"renderMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode":{"role":"symbol","title":"AgoraVideoRenderMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderMode"}],"url":"\/documentation\/agorartckit\/agoravideorendermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCanvas":{"role":"symbol","title":"AgoraRtcVideoCanvas","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"abstract":[{"type":"text","text":"Attributes of video canvas object."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"url":"\/documentation\/agorartckit\/agorartcvideocanvas"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCanvas/renderMode":{"role":"symbol","title":"renderMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"}],"abstract":[{"type":"text","text":"The rendering mode of the video. See AgoraVideoRenderMode ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas\/renderMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renderMode"}],"url":"\/documentation\/agorartckit\/agorartcvideocanvas\/rendermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"renderMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"renderMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode","text":"AgoraVideoRenderMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/title","value":"AgoraVideoRenderMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/title","value":"AgoraRtcVideoCanvas"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/fragments","value":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas~1renderMode\/title","value":"renderMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas~1renderMode\/fragments","value":[{"kind":"identifier","text":"renderMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}