{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoViewSetupMode","preciseIdentifier":"c:@E@AgoraVideoViewSetupMode","text":"AgoraVideoViewSetupMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcvideocanvas\/setupmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcvideocanvas\/setupmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas\/setupMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Setting mode of the view. See AgoraVideoViewSetupMode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoViewSetupMode","preciseIdentifier":"c:@E@AgoraVideoViewSetupMode"}],"title":"setupMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcVideoCanvas(py)setupMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setupMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCanvas/setupMode":{"role":"symbol","title":"setupMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoViewSetupMode","preciseIdentifier":"c:@E@AgoraVideoViewSetupMode"}],"abstract":[{"type":"text","text":"Setting mode of the view. See AgoraVideoViewSetupMode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas\/setupMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupMode"}],"url":"\/documentation\/agorartckit\/agorartcvideocanvas\/setupmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoViewSetupMode":{"role":"symbol","title":"AgoraVideoViewSetupMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoViewSetupMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoViewSetupMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoViewSetupMode"}],"url":"\/documentation\/agorartckit\/agoravideoviewsetupmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCanvas":{"role":"symbol","title":"AgoraRtcVideoCanvas","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"abstract":[{"type":"text","text":"Attributes of the video canvas object."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"url":"\/documentation\/agorartckit\/agorartcvideocanvas"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"setupMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"setupMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoViewSetupMode","preciseIdentifier":"c:@E@AgoraVideoViewSetupMode","text":"AgoraVideoViewSetupMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas~1setupMode\/title","value":"setupMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas~1setupMode\/fragments","value":[{"kind":"identifier","text":"setupMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoViewSetupMode\/title","value":"AgoraVideoViewSetupMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoViewSetupMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoViewSetupMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/title","value":"AgoraRtcVideoCanvas"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/fragments","value":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}