{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localNetworkQualityPoor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/localnetworkqualitypoor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/localnetworkqualitypoor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/localNetworkQualityPoor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The local user’s network quality is poor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localNetworkQualityPoor"}],"title":"AgoraExperiencePoorReason.localNetworkQualityPoor","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraExperiencePoorReason@AgoraExperiencePoorReasonLocalNetworkQualityPoor","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonLocalNetworkQualityPoor"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason/localNetworkQualityPoor":{"role":"symbol","title":"AgoraExperiencePoorReason.localNetworkQualityPoor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localNetworkQualityPoor"}],"abstract":[{"type":"text","text":"2: The local user’s network quality is poor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/localNetworkQualityPoor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonLocalNetworkQualityPoor"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason\/localnetworkqualitypoor"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason":{"role":"symbol","title":"AgoraExperiencePoorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is poor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraExperiencePoorReasonLocalNetworkQualityPoor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonLocalNetworkQualityPoor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraExperiencePoorReasonLocalNetworkQualityPoor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1localNetworkQualityPoor\/title","value":"AgoraExperiencePoorReasonLocalNetworkQualityPoor"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1localNetworkQualityPoor\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonLocalNetworkQualityPoor"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/title","value":"AgoraExperiencePoorReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}