{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/none","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: No reason, indicating a good QoE of the local user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"AgoraExperiencePoorReason.none","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraExperiencePoorReason@AgoraExperiencePoorReasonNone","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonNone"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason/none":{"role":"symbol","title":"AgoraExperiencePoorReason.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"0: No reason, indicating a good QoE of the local user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonNone"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason\/none"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason":{"role":"symbol","title":"AgoraExperiencePoorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is"},{"type":"text","text":" "},{"type":"text","text":"poor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraExperiencePoorReasonNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonNone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraExperiencePoorReasonNone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1none\/title","value":"AgoraExperiencePoorReasonNone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1none\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonNone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/title","value":"AgoraExperiencePoorReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}