{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiBluetoothCoexist"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/wifibluetoothcoexist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/wifibluetoothcoexist"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/wifiBluetoothCoexist","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"8: The local user enables both Wi-Fi and bluetooth, and their signals"},{"type":"text","text":" "},{"type":"text","text":"interfere with each other. As a result, audio transmission quality is"},{"type":"text","text":" "},{"type":"text","text":"undermined."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiBluetoothCoexist"}],"title":"AgoraExperiencePoorReason.wifiBluetoothCoexist","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraExperiencePoorReason@AgoraExperiencePoorReasonWifiBluetoothCoexist","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWifiBluetoothCoexist"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason/wifiBluetoothCoexist":{"role":"symbol","title":"AgoraExperiencePoorReason.wifiBluetoothCoexist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifiBluetoothCoexist"}],"abstract":[{"type":"text","text":"8: The local user enables both Wi-Fi and bluetooth, and their signals"},{"type":"text","text":" "},{"type":"text","text":"interfere with each other. As a result, audio transmission quality is"},{"type":"text","text":" "},{"type":"text","text":"undermined."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/wifiBluetoothCoexist","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWifiBluetoothCoexist"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason\/wifibluetoothcoexist"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason":{"role":"symbol","title":"AgoraExperiencePoorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is"},{"type":"text","text":" "},{"type":"text","text":"poor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraExperiencePoorReasonWifiBluetoothCoexist"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWifiBluetoothCoexist"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWifiBluetoothCoexist"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1wifiBluetoothCoexist\/title","value":"AgoraExperiencePoorReasonWifiBluetoothCoexist"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1wifiBluetoothCoexist\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWifiBluetoothCoexist"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/title","value":"AgoraExperiencePoorReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}