{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wirelessSignalPoor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/wirelesssignalpoor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraexperiencepoorreason\/wirelesssignalpoor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/wirelessSignalPoor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: The local user’s Wi-Fi or mobile network signal is weak."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wirelessSignalPoor"}],"title":"AgoraExperiencePoorReason.wirelessSignalPoor","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraExperiencePoorReason@AgoraExperiencePoorReasonWirelessSignalPoor","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWirelessSignalPoor"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason/wirelessSignalPoor":{"role":"symbol","title":"AgoraExperiencePoorReason.wirelessSignalPoor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wirelessSignalPoor"}],"abstract":[{"type":"text","text":"4: The local user’s Wi-Fi or mobile network signal is weak."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason\/wirelessSignalPoor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWirelessSignalPoor"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason\/wirelesssignalpoor"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason":{"role":"symbol","title":"AgoraExperiencePoorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is"},{"type":"text","text":" "},{"type":"text","text":"poor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraExperiencePoorReasonWirelessSignalPoor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWirelessSignalPoor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWirelessSignalPoor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1wirelessSignalPoor\/title","value":"AgoraExperiencePoorReasonWirelessSignalPoor"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason~1wirelessSignalPoor\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReasonWirelessSignalPoor"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/title","value":"AgoraExperiencePoorReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}