{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/lowlatency"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/lowlatency"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/lowLatency","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Low latency."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"}],"title":"AgoraAudienceLatencyLevelType.lowLatency","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudienceLatencyLevelType@AgoraAudienceLatencyLevelLowLatency","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelLowLatency"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType":{"role":"symbol","title":"AgoraAudienceLatencyLevelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"abstract":[{"type":"text","text":"The latency level of an audience member in interactive live streaming. This enum takes effect only when the user role is set to AgoraClientRoleAudience ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType/lowLatency":{"role":"symbol","title":"AgoraAudienceLatencyLevelType.lowLatency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"}],"abstract":[{"type":"text","text":"1: Low latency."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/lowLatency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelLowLatency"}],"url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/lowlatency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudienceLatencyLevelLowLatency"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelLowLatency"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelLowLatency"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType\/title","value":"AgoraAudienceLatencyLevelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType~1lowLatency\/title","value":"AgoraAudienceLatencyLevelLowLatency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType~1lowLatency\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelLowLatency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}