{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerKit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol","text":"AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveAudioFrame"},{"kind":"text","text":" "},{"kind":"internalParam","text":"audioFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"playerKit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See AgoraRtcMediaPlayerProtocol ."}]}]},{"name":"audioFrame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Audio frame information (CMSampleBufferRef)."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate\/agorartcmediaplayer(_:didreceiveaudioframe:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate\/agorartcmediaplayer(_:didreceiveaudioframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate\/AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs each time the player receives an audio frame."},{"type":"text","text":" "},{"type":"text","text":"After registering the audio frame observer, the callback occurs every time"},{"type":"text","text":" "},{"type":"text","text":"the player receives an audio frame, reporting the detailed information of the"},{"type":"text","text":" "},{"type":"text","text":"audio frame."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveAudioFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerAudioFrameDelegate(im)AgoraRtcMediaPlayer:didReceiveAudioFrame:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerAudioFrameDelegate/AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveAudioFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs each time the player receives an audio frame."},{"type":"text","text":" "},{"type":"text","text":"After registering the audio frame observer, the callback occurs every time"},{"type":"text","text":" "},{"type":"text","text":"the player receives an audio frame, reporting the detailed information of the"},{"type":"text","text":" "},{"type":"text","text":"audio frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate\/AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate\/agorartcmediaplayer(_:didreceiveaudioframe:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrame":{"role":"symbol","title":"AgoraAudioFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrame"}],"abstract":[{"type":"text","text":"Raw audio data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrame"}],"url":"\/documentation\/agorartckit\/agoraaudioframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerAudioFrameDelegate":{"role":"symbol","title":"AgoraRtcMediaPlayerAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraRtcMediaPlayerProtocol>","preciseIdentifier":"c:Qoobjc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"playerKit"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveAudioFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"audioFrame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate~1AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)\/title","value":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate~1AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/title","value":"AgoraAudioFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate\/title","value":"AgoraRtcMediaPlayerAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}