{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTooOften"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamingevent\/requesttoooften"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamingevent\/requesttoooften"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/requestTooOften","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: Reserved."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTooOften"}],"title":"AgoraRtmpStreamingEvent.requestTooOften","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamingEvent@AgoraRtmpStreamingEventRequestTooOften","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventRequestTooOften"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/requestTooOften":{"role":"symbol","title":"AgoraRtmpStreamingEvent.requestTooOften","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTooOften"}],"abstract":[{"type":"text","text":"4: Reserved."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/requestTooOften","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventRequestTooOften"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/requesttoooften"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent":{"role":"symbol","title":"AgoraRtmpStreamingEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"abstract":[{"type":"text","text":"Events during the media push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamingEventRequestTooOften"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventRequestTooOften"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamingEventRequestTooOften"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1requestTooOften\/title","value":"AgoraRtmpStreamingEventRequestTooOften"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1requestTooOften\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventRequestTooOften"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent\/title","value":"AgoraRtmpStreamingEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}