{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlAlreadyInUse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamingevent\/urlalreadyinuse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamingevent\/urlalreadyinuse"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/urlAlreadyInUse","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The streaming URL is already being used for Media Push. If you want to start new streaming, use a new streaming URL."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlAlreadyInUse"}],"title":"AgoraRtmpStreamingEvent.urlAlreadyInUse","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamingEvent@AgoraRtmpStreamingEventUrlAlreadyInUse","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventUrlAlreadyInUse"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/urlAlreadyInUse":{"role":"symbol","title":"AgoraRtmpStreamingEvent.urlAlreadyInUse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlAlreadyInUse"}],"abstract":[{"type":"text","text":"2: The streaming URL is already being used for Media Push. If you want to start new streaming, use a new streaming URL."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/urlAlreadyInUse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventUrlAlreadyInUse"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/urlalreadyinuse"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent":{"role":"symbol","title":"AgoraRtmpStreamingEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"abstract":[{"type":"text","text":"Events during the Media Push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamingEventUrlAlreadyInUse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventUrlAlreadyInUse"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamingEventUrlAlreadyInUse"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1urlAlreadyInUse\/title","value":"AgoraRtmpStreamingEventUrlAlreadyInUse"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1urlAlreadyInUse\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventUrlAlreadyInUse"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent\/title","value":"AgoraRtmpStreamingEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}