{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/as"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/as"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/AS","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asia, excluding Mainland China."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AS"}],"title":"AgoraAreaCodeType.AS","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAreaCodeType@AgoraAreaCodeTypeAS","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeAS"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType/AS":{"role":"symbol","title":"AgoraAreaCodeType.AS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AS"}],"abstract":[{"type":"text","text":"Asia, excluding Mainland China."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/AS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeAS"}],"url":"\/documentation\/agorartckit\/agoraareacodetype\/as"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType":{"role":"symbol","title":"AgoraAreaCodeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAreaCodeType"}],"abstract":[{"type":"text","text":"The region for connection, which is the region where the server the SDK"},{"type":"text","text":" "},{"type":"text","text":"connects to is located."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeType"}],"url":"\/documentation\/agorartckit\/agoraareacodetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAreaCodeTypeAS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeAS"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAreaCodeTypeAS"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1AS\/title","value":"AgoraAreaCodeTypeAS"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1AS\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeAS"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/title","value":"AgoraAreaCodeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}