{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EUR"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/eur"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/eur"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/EUR","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Europe."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EUR"}],"title":"AgoraAreaCodeType.EUR","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAreaCodeType@AgoraAreaCodeTypeEUR","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeEUR"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType":{"role":"symbol","title":"AgoraAreaCodeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAreaCodeType"}],"abstract":[{"type":"text","text":"The region for connection, which is the region where the server the SDK"},{"type":"text","text":" "},{"type":"text","text":"connects to is located."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeType"}],"url":"\/documentation\/agorartckit\/agoraareacodetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType/EUR":{"role":"symbol","title":"AgoraAreaCodeType.EUR","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EUR"}],"abstract":[{"type":"text","text":"Europe."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/EUR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeEUR"}],"url":"\/documentation\/agorartckit\/agoraareacodetype\/eur"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAreaCodeTypeEUR"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeEUR"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAreaCodeTypeEUR"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/title","value":"AgoraAreaCodeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1EUR\/title","value":"AgoraAreaCodeTypeEUR"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1EUR\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeEUR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}