{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/jp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/jp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/JP","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Japan."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JP"}],"title":"AgoraAreaCodeType.JP","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAreaCodeType@AgoraAreaCodeTypeJP","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeJP"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType":{"role":"symbol","title":"AgoraAreaCodeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAreaCodeType"}],"abstract":[{"type":"text","text":"The region for connection, which is the region where the server the SDK"},{"type":"text","text":" "},{"type":"text","text":"connects to is located."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeType"}],"url":"\/documentation\/agorartckit\/agoraareacodetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType/JP":{"role":"symbol","title":"AgoraAreaCodeType.JP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"JP"}],"abstract":[{"type":"text","text":"Japan."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/JP","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeJP"}],"url":"\/documentation\/agorartckit\/agoraareacodetype\/jp"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAreaCodeTypeJP"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeJP"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAreaCodeTypeJP"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/title","value":"AgoraAreaCodeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1JP\/title","value":"AgoraAreaCodeTypeJP"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1JP\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeJP"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}