{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NA"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/na"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraareacodetype\/na"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/NA","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"North America."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NA"}],"title":"AgoraAreaCodeType.NA","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAreaCodeType@AgoraAreaCodeTypeNA","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeNA"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType/NA":{"role":"symbol","title":"AgoraAreaCodeType.NA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NA"}],"abstract":[{"type":"text","text":"North America."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType\/NA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeTypeNA"}],"url":"\/documentation\/agorartckit\/agoraareacodetype\/na"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType":{"role":"symbol","title":"AgoraAreaCodeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAreaCodeType"}],"abstract":[{"type":"text","text":"The region for connection, which is the region where the server the SDK connects to is located."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeType"}],"url":"\/documentation\/agorartckit\/agoraareacodetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAreaCodeTypeNA"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeNA"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAreaCodeTypeNA"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1NA\/title","value":"AgoraAreaCodeTypeNA"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType~1NA\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeTypeNA"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/title","value":"AgoraAreaCodeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}