{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","preciseIdentifier":"c:@E@AgoraEncryptionMode","text":"AgoraEncryptionMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionconfig\/encryptionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionconfig\/encryptionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig\/encryptionMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The built-in encryption mode. See AgoraEncryptionMode . Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"using AgoraEncryptionModeAES128GCM2 or AgoraEncryptionModeAES256GCM2"},{"type":"text","text":" "},{"type":"text","text":"encrypted mode. These two modes support the use of salt for higher security."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncryptionMode","preciseIdentifier":"c:@E@AgoraEncryptionMode"}],"title":"encryptionMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraEncryptionConfig(py)encryptionMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"encryptionMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig":{"role":"symbol","title":"AgoraEncryptionConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionConfig"}],"abstract":[{"type":"text","text":"Built-in encryption configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionConfig"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig/encryptionMode":{"role":"symbol","title":"encryptionMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncryptionMode","preciseIdentifier":"c:@E@AgoraEncryptionMode"}],"abstract":[{"type":"text","text":"The built-in encryption mode. See AgoraEncryptionMode . Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"using AgoraEncryptionModeAES128GCM2 or AgoraEncryptionModeAES256GCM2"},{"type":"text","text":" "},{"type":"text","text":"encrypted mode. These two modes support the use of salt for higher security."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig\/encryptionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encryptionMode"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig\/encryptionmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode":{"role":"symbol","title":"AgoraEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"}],"abstract":[{"type":"text","text":"The built-in encryption mode."},{"type":"text","text":" "},{"type":"text","text":"Agora recommends using AgoraEncryptionModeAES128GCM2 or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncryptionModeAES256GCM2 encrypted mode. These two modes support the use"},{"type":"text","text":" "},{"type":"text","text":"of salt for higher security."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionMode"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"encryptionMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"encryptionMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","preciseIdentifier":"c:@E@AgoraEncryptionMode","text":"AgoraEncryptionMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/title","value":"AgoraEncryptionConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig~1encryptionMode\/title","value":"encryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig~1encryptionMode\/fragments","value":[{"kind":"identifier","text":"encryptionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/title","value":"AgoraEncryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}