{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionconfig\/encryptionkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionconfig\/encryptionkey"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig\/encryptionKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Encryption key in string type with unlimited length. Agora recommends using a 32-byte key.If you do not set an encryption key or set it as nil, you cannot use the built-in encryption, and the SDK returns -2."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"encryptionKey","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraEncryptionConfig(py)encryptionKey","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"encryptionKey"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig/encryptionKey":{"role":"symbol","title":"encryptionKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Encryption key in string type with unlimited length. Agora recommends using a 32-byte key.If you do not set an encryption key or set it as nil, you cannot use the built-in encryption, and the SDK returns -2."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig\/encryptionKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encryptionKey"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig\/encryptionkey"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig":{"role":"symbol","title":"AgoraEncryptionConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionConfig"}],"abstract":[{"type":"text","text":"Built-in encryption configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionConfig"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"encryptionKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"encryptionKey"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"encryptionKey"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig~1encryptionKey\/title","value":"encryptionKey"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig~1encryptionKey\/fragments","value":[{"kind":"identifier","text":"encryptionKey"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/title","value":"AgoraEncryptionConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}