{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiodualmonomode\/mix"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiodualmonomode\/mix"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/mix","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"title":"AgoraAudioDualMonoMode.mix","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioDualMonoMode@AgoraAudioDualMonoMix","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMix"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/mix":{"role":"symbol","title":"AgoraAudioDualMonoMode.mix","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/mix","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMix"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/mix"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode":{"role":"symbol","title":"AgoraAudioDualMonoMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"abstract":[{"type":"text","text":"The channel mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioDualMonoMix"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMix"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioDualMonoMix"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1mix\/title","value":"AgoraAudioDualMonoMix"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1mix\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMix"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/title","value":"AgoraAudioDualMonoMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}