{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stereo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiodualmonomode\/stereo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiodualmonomode\/stereo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/stereo","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stereo"}],"title":"AgoraAudioDualMonoMode.stereo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioDualMonoMode@AgoraAudioDualMonoStereo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoStereo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode":{"role":"symbol","title":"AgoraAudioDualMonoMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"abstract":[{"type":"text","text":"The channel mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/stereo":{"role":"symbol","title":"AgoraAudioDualMonoMode.stereo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stereo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/stereo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoStereo"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/stereo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioDualMonoStereo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoStereo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioDualMonoStereo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/title","value":"AgoraAudioDualMonoMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1stereo\/title","value":"AgoraAudioDualMonoStereo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1stereo\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoStereo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}