{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"porn"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracontentinspectresult\/porn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracontentinspectresult\/porn"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectResult\/porn","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"porn"}],"title":"AgoraContentInspectResult.porn","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraContentInspectResult@AgoraContentInspectPorn","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectPorn"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectResult"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectResult/porn":{"role":"symbol","title":"AgoraContentInspectResult.porn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"porn"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectResult\/porn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectPorn"}],"url":"\/documentation\/agorartckit\/agoracontentinspectresult\/porn"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectResult":{"role":"symbol","title":"AgoraContentInspectResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectResult"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectResult"}],"url":"\/documentation\/agorartckit\/agoracontentinspectresult"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraContentInspectPorn"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectPorn"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraContentInspectPorn"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectResult~1porn\/title","value":"AgoraContentInspectPorn"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectResult~1porn\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectPorn"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectResult\/title","value":"AgoraContentInspectResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectResult\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}