{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPermissionAndResource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/errorpermissionandresource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/errorpermissionandresource"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode\/errorPermissionAndResource","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPermissionAndResource"}],"title":"AgoraMusicContentCenterStatusCode.errorPermissionAndResource","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMusicContentCenterStatusCode@AgoraMusicContentCenterStatusCodeErrorPermissionAndResource","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorPermissionAndResource"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterStatusCode/errorPermissionAndResource":{"role":"symbol","title":"AgoraMusicContentCenterStatusCode.errorPermissionAndResource","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPermissionAndResource"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode\/errorPermissionAndResource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorPermissionAndResource"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/errorpermissionandresource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterStatusCode":{"role":"symbol","title":"AgoraMusicContentCenterStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicContentCenterStatusCodeErrorPermissionAndResource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorPermissionAndResource"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorPermissionAndResource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode~1errorPermissionAndResource\/title","value":"AgoraMusicContentCenterStatusCodeErrorPermissionAndResource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode~1errorPermissionAndResource\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorPermissionAndResource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/title","value":"AgoraMusicContentCenterStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}