{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMusicDecryption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/errormusicdecryption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/errormusicdecryption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode\/errorMusicDecryption","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMusicDecryption"}],"title":"AgoraMusicContentCenterStatusCode.errorMusicDecryption","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMusicContentCenterStatusCode@AgoraMusicContentCenterStatusCodeErrorMusicDecryption","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorMusicDecryption"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterStatusCode":{"role":"symbol","title":"AgoraMusicContentCenterStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterStatusCode/errorMusicDecryption":{"role":"symbol","title":"AgoraMusicContentCenterStatusCode.errorMusicDecryption","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMusicDecryption"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode\/errorMusicDecryption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorMusicDecryption"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/errormusicdecryption"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicContentCenterStatusCodeErrorMusicDecryption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorMusicDecryption"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorMusicDecryption"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/title","value":"AgoraMusicContentCenterStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode~1errorMusicDecryption\/title","value":"AgoraMusicContentCenterStatusCodeErrorMusicDecryption"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode~1errorMusicDecryption\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeErrorMusicDecryption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}