{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/ok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode\/OK","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"title":"AgoraMusicContentCenterStatusCode.OK","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMusicContentCenterStatusCode@AgoraMusicContentCenterStatusCodeOK","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeOK"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterStatusCode/OK":{"role":"symbol","title":"AgoraMusicContentCenterStatusCode.OK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode\/OK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeOK"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode\/ok"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterStatusCode":{"role":"symbol","title":"AgoraMusicContentCenterStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicContentCenterStatusCodeOK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeOK"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeOK"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode~1OK\/title","value":"AgoraMusicContentCenterStatusCodeOK"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode~1OK\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCodeOK"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/title","value":"AgoraMusicContentCenterStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}