{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type32000"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiosampleratetype\/type32000"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiosampleratetype\/type32000"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSampleRateType\/type32000","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"32000: 32 kHz"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type32000"}],"title":"AgoraAudioSampleRateType.type32000","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioSampleRateType@AgoraAudioSampleRateType32000","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSampleRateType32000"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSampleRateType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSampleRateType/type32000":{"role":"symbol","title":"AgoraAudioSampleRateType.type32000","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type32000"}],"abstract":[{"type":"text","text":"32000: 32 kHz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSampleRateType\/type32000","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSampleRateType32000"}],"url":"\/documentation\/agorartckit\/agoraaudiosampleratetype\/type32000"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSampleRateType":{"role":"symbol","title":"AgoraAudioSampleRateType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSampleRateType"}],"abstract":[{"type":"text","text":"The audio sampling rate of the stream to be pushed to the CDN."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSampleRateType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSampleRateType"}],"url":"\/documentation\/agorartckit\/agoraaudiosampleratetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioSampleRateType32000"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSampleRateType32000"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioSampleRateType32000"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSampleRateType~1type32000\/title","value":"AgoraAudioSampleRateType32000"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSampleRateType~1type32000\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSampleRateType32000"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSampleRateType\/title","value":"AgoraAudioSampleRateType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSampleRateType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSampleRateType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}