{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"begin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediaplayerpreloadevent\/begin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediaplayerpreloadevent\/begin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerPreloadEvent\/begin","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: Starts preloading media resources."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"begin"}],"title":"AgoraMediaPlayerPreloadEvent.begin","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaPlayerPreloadEvent@AgoraMediaPlayerPreloadEventBegin","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerPreloadEventBegin"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerPreloadEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerPreloadEvent/begin":{"role":"symbol","title":"AgoraMediaPlayerPreloadEvent.begin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"begin"}],"abstract":[{"type":"text","text":"0: Starts preloading media resources."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerPreloadEvent\/begin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerPreloadEventBegin"}],"url":"\/documentation\/agorartckit\/agoramediaplayerpreloadevent\/begin"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerPreloadEvent":{"role":"symbol","title":"AgoraMediaPlayerPreloadEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerPreloadEvent"}],"abstract":[{"type":"text","text":"Events that occur when media resources are preloaded."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerPreloadEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerPreloadEvent"}],"url":"\/documentation\/agorartckit\/agoramediaplayerpreloadevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaPlayerPreloadEventBegin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerPreloadEventBegin"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaPlayerPreloadEventBegin"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerPreloadEvent~1begin\/title","value":"AgoraMediaPlayerPreloadEventBegin"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerPreloadEvent~1begin\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerPreloadEventBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerPreloadEvent\/title","value":"AgoraMediaPlayerPreloadEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerPreloadEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerPreloadEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}