{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/mix"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/mix"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/mix","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: Mixed channel mode. This mode mixes the audio of the left channel and"},{"type":"text","text":" "},{"type":"text","text":"the right channel, which means the user can hear the audio of the left"},{"type":"text","text":" "},{"type":"text","text":"channel and the right channel at the same time."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"title":"AgoraAudioMixingDualMonoMode.mix","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioMixingDualMonoMode@AgoraAudioMixingDualMonoMix","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMix"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/mix":{"role":"symbol","title":"AgoraAudioMixingDualMonoMode.mix","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"abstract":[{"type":"text","text":"3: Mixed channel mode. This mode mixes the audio of the left channel and"},{"type":"text","text":" "},{"type":"text","text":"the right channel, which means the user can hear the audio of the left"},{"type":"text","text":" "},{"type":"text","text":"channel and the right channel at the same time."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/mix","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMix"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/mix"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode":{"role":"symbol","title":"AgoraAudioMixingDualMonoMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}],"abstract":[{"type":"text","text":"The channel mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioMixingDualMonoMix"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMix"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMix"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1mix\/title","value":"AgoraAudioMixingDualMonoMix"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1mix\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMix"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode\/title","value":"AgoraAudioMixingDualMonoMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}