{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelstereo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioprocesschannels\/channelstereo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioprocesschannels\/channelstereo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelstereo","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelstereo"}],"title":"AgoraAudioProcessChannels.channelstereo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioProcessChannels@AgoraAudioProcessChannelstereo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannelstereo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels":{"role":"symbol","title":"AgoraAudioProcessChannels","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"abstract":[{"type":"text","text":"The number of channels for audio preprocessing."},{"type":"text","text":" "},{"type":"text","text":"In scenarios that require enhanced realism, such as concerts, local users"},{"type":"text","text":" "},{"type":"text","text":"might need to capture stereo audio and send stereo signals to remote users."},{"type":"text","text":" "},{"type":"text","text":"For example, the singer, guitarist, and drummer are standing in different"},{"type":"text","text":" "},{"type":"text","text":"positions on the stage. The audio capture device captures their stereo audio"},{"type":"text","text":" "},{"type":"text","text":"and sends stereo signals to remote users. Remote users can hear the song,"},{"type":"text","text":" "},{"type":"text","text":"guitar, and drum from different directions as if they were at the"},{"type":"text","text":" "},{"type":"text","text":"auditorium.You can set the dual-channel processing to implement stereo audio"},{"type":"text","text":" "},{"type":"text","text":"in this class. Agora recommends the following settings:Preprocessing: call"},{"type":"text","text":" "},{"type":"text","text":"setAdvancedAudioOptions and set audioProcessingChannels to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAdvancedAudioOptions (2) in"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProcessChannelsStereo.Post-processing: call setAudioProfile [2\/2]"},{"type":"text","text":" "},{"type":"text","text":"profile to AgoraAudioProfileMusicStandardStereo (3) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo (5).The stereo setting only takes"},{"type":"text","text":" "},{"type":"text","text":"effect when the SDK uses the media volume.  On iOS, stereo audio requires"},{"type":"text","text":" "},{"type":"text","text":"high device performance. Stereo audio is only supported on the following"},{"type":"text","text":" "},{"type":"text","text":"devices using iOS 14.0 and later:iPhone XSiPhone XS MaxiPhone XRiPhone"},{"type":"text","text":" "},{"type":"text","text":"11iPhone 11 ProiPhone 11 Pro MaxiPhone SE (2020)iPad Pro 11” and 12.9” (3rd"},{"type":"text","text":" "},{"type":"text","text":"generation)iPad Pro 11” and 12.9” (4th generation)"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"url":"\/documentation\/agorartckit\/agoraaudioprocesschannels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels/channelstereo":{"role":"symbol","title":"AgoraAudioProcessChannels.channelstereo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelstereo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelstereo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannelstereo"}],"url":"\/documentation\/agorartckit\/agoraaudioprocesschannels\/channelstereo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioProcessChannelstereo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannelstereo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioProcessChannelstereo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels\/title","value":"AgoraAudioProcessChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels~1channelstereo\/title","value":"AgoraAudioProcessChannelstereo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels~1channelstereo\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannelstereo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}