{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addVideoWatermarkEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions","preciseIdentifier":"c:objc(cs)WatermarkOptions","text":"WatermarkOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The local file path of the watermark image to be added. This"},{"type":"text","text":" "},{"type":"text","text":"method supports adding a watermark image from the local absolute or relative"},{"type":"text","text":" "},{"type":"text","text":"file path."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options of the watermark image to be added. See"},{"type":"text","text":" "},{"type":"text","text":"WatermarkOptions ."}]}]},{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/addvideowatermarkex(_:options:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/addvideowatermarkex(_:options:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/addVideoWatermarkEx(_:options:connection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a watermark image to the local video."},{"type":"text","text":" "},{"type":"text","text":"This method adds a PNG watermark image to the local video in the live"},{"type":"text","text":" "},{"type":"text","text":"streaming. Once the watermark image is added, all the audience in the channel"},{"type":"text","text":" "},{"type":"text","text":"(CDN audience included), and the capturing device can see and capture it. The"},{"type":"text","text":" "},{"type":"text","text":"Agora SDK supports adding only one watermark image onto a local video or CDN"},{"type":"text","text":" "},{"type":"text","text":"live stream. The newly added watermark image replaces the previous one.The"},{"type":"text","text":" "},{"type":"text","text":"watermark coordinates are dependent on the settings in the"},{"type":"text","text":" "},{"type":"text","text":"setVideoEncoderConfigurationEx method:If the orientation mode of the encoding"},{"type":"text","text":" "},{"type":"text","text":"video ( AgoraVideoOutputOrientationMode ) is fixed landscape mode or the"},{"type":"text","text":" "},{"type":"text","text":"adaptive landscape mode, the watermark uses the landscape orientation.If the"},{"type":"text","text":" "},{"type":"text","text":"orientation mode of the encoding video (AgoraVideoOutputOrientationMode) is"},{"type":"text","text":" "},{"type":"text","text":"fixed portrait mode or the adaptive portrait mode, the watermark uses the"},{"type":"text","text":" "},{"type":"text","text":"portrait orientation.When setting the watermark position, the region must be"},{"type":"text","text":" "},{"type":"text","text":"less than the dimensions set in the setVideoEncoderConfigurationEx method;"},{"type":"text","text":" "},{"type":"text","text":"otherwise, the watermark image will be cropped.Ensure that you have called"},{"type":"text","text":" "},{"type":"text","text":"enableVideo before calling this method.This method supports adding a"},{"type":"text","text":" "},{"type":"text","text":"watermark image in the PNG file format only. Supported pixel formats of the"},{"type":"text","text":" "},{"type":"text","text":"PNG image are RGBA, RGB, Palette, Gray, and Alpha_gray.If the dimensions of"},{"type":"text","text":" "},{"type":"text","text":"the PNG image differ from your settings in this method, the image will be"},{"type":"text","text":" "},{"type":"text","text":"cropped or zoomed to conform to your settings.If you have enabled the local"},{"type":"text","text":" "},{"type":"text","text":"video preview by calling the startPreview visibleInPreview member to set"},{"type":"text","text":" "},{"type":"text","text":"whether or not the watermark is visible in the preview.If you have enabled"},{"type":"text","text":" "},{"type":"text","text":"the mirror mode for the local video, the watermark on the local video is also"},{"type":"text","text":" "},{"type":"text","text":"mirrored. To avoid mirroring the watermark, Agora recommends that you do not"},{"type":"text","text":" "},{"type":"text","text":"use the mirror and watermark functions for the local video at the same time."},{"type":"text","text":" "},{"type":"text","text":"You can implement the watermark function in your application layer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addVideoWatermarkEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WatermarkOptions","preciseIdentifier":"c:objc(cs)WatermarkOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"addVideoWatermarkEx(_:options:connection:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)addVideoWatermarkEx:options:connection:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"addVideoWatermarkEx:options:connection:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/WatermarkOptions":{"role":"symbol","title":"WatermarkOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatermarkOptions"}],"abstract":[{"type":"text","text":"Configurations of the watermark image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatermarkOptions"}],"url":"\/documentation\/agorartckit\/watermarkoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/addVideoWatermarkEx(_:options:connection:)":{"role":"symbol","title":"addVideoWatermarkEx(_:options:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addVideoWatermarkEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WatermarkOptions","preciseIdentifier":"c:objc(cs)WatermarkOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adds a watermark image to the local video."},{"type":"text","text":" "},{"type":"text","text":"This method adds a PNG watermark image to the local video in the live"},{"type":"text","text":" "},{"type":"text","text":"streaming. Once the watermark image is added, all the audience in the channel"},{"type":"text","text":" "},{"type":"text","text":"(CDN audience included), and the capturing device can see and capture it. The"},{"type":"text","text":" "},{"type":"text","text":"Agora SDK supports adding only one watermark image onto a local video or CDN"},{"type":"text","text":" "},{"type":"text","text":"live stream. The newly added watermark image replaces the previous one.The"},{"type":"text","text":" "},{"type":"text","text":"watermark coordinates are dependent on the settings in the"},{"type":"text","text":" "},{"type":"text","text":"setVideoEncoderConfigurationEx method:If the orientation mode of the encoding"},{"type":"text","text":" "},{"type":"text","text":"video ( AgoraVideoOutputOrientationMode ) is fixed landscape mode or the"},{"type":"text","text":" "},{"type":"text","text":"adaptive landscape mode, the watermark uses the landscape orientation.If the"},{"type":"text","text":" "},{"type":"text","text":"orientation mode of the encoding video (AgoraVideoOutputOrientationMode) is"},{"type":"text","text":" "},{"type":"text","text":"fixed portrait mode or the adaptive portrait mode, the watermark uses the"},{"type":"text","text":" "},{"type":"text","text":"portrait orientation.When setting the watermark position, the region must be"},{"type":"text","text":" "},{"type":"text","text":"less than the dimensions set in the setVideoEncoderConfigurationEx method;"},{"type":"text","text":" "},{"type":"text","text":"otherwise, the watermark image will be cropped.Ensure that you have called"},{"type":"text","text":" "},{"type":"text","text":"enableVideo before calling this method.This method supports adding a"},{"type":"text","text":" "},{"type":"text","text":"watermark image in the PNG file format only. Supported pixel formats of the"},{"type":"text","text":" "},{"type":"text","text":"PNG image are RGBA, RGB, Palette, Gray, and Alpha_gray.If the dimensions of"},{"type":"text","text":" "},{"type":"text","text":"the PNG image differ from your settings in this method, the image will be"},{"type":"text","text":" "},{"type":"text","text":"cropped or zoomed to conform to your settings.If you have enabled the local"},{"type":"text","text":" "},{"type":"text","text":"video preview by calling the startPreview visibleInPreview member to set"},{"type":"text","text":" "},{"type":"text","text":"whether or not the watermark is visible in the preview.If you have enabled"},{"type":"text","text":" "},{"type":"text","text":"the mirror mode for the local video, the watermark on the local video is also"},{"type":"text","text":" "},{"type":"text","text":"mirrored. To avoid mirroring the watermark, Agora recommends that you do not"},{"type":"text","text":" "},{"type":"text","text":"use the mirror and watermark functions for the local video at the same time."},{"type":"text","text":" "},{"type":"text","text":"You can implement the watermark function in your application layer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/addVideoWatermarkEx(_:options:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addVideoWatermarkEx:options:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/addvideowatermarkex(_:options:connection:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addVideoWatermarkEx:options:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addVideoWatermarkEx:options:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"addVideoWatermarkEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions","preciseIdentifier":"c:objc(cs)WatermarkOptions","text":"WatermarkOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions\/title","value":"WatermarkOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions\/fragments","value":[{"kind":"identifier","text":"WatermarkOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1addVideoWatermarkEx(_:options:connection:)\/title","value":"addVideoWatermarkEx:options:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1addVideoWatermarkEx(_:options:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addVideoWatermarkEx:options:connection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}