{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio track ID. Set this parameter to the custom audio track ID returned in createCustomAudioTrack."}]}]},{"name":"volume","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The volume of the audio source. The value can range from 0 to 100. 0 means mute; 100 means the original volume."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Ensure you have called the createCustomAudioTrack method to create an external audio track before calling this method. If you want to change the volume of the audio to be published, you need to call this method again."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/adjustcustomaudiopublishvolume(_:volume:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/adjustcustomaudiopublishvolume(_:volume:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustCustomAudioPublishVolume(_:volume:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adjusts the volume of the custom external audio source when it is published in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"adjustCustomAudioPublishVolume(_:volume:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)adjustCustomAudioPublishVolume:volume:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"adjustCustomAudioPublishVolume:volume:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"seeAlsoSections":[{"title":"Audio Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalAudio(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:scenario:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioScenario(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalAudioStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteAudioStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteAudioStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioSessionOperationRestriction(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustRecordingSignalVolume(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustUserPlaybackSignalVolume(_:volume:)"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioProfile(_:)":{"role":"symbol","title":"setAudioProfile(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioProfile","preciseIdentifier":"c:@E@AgoraAudioProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the audio parameters and application scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioProfile:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioprofile(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteLocalAudioStream(_:)":{"role":"symbol","title":"muteLocalAudioStream(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteLocalAudioStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes publishing the local audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalAudioStream(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteLocalAudioStream:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/mutelocalaudiostream(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableLocalAudio(_:)":{"role":"symbol","title":"enableLocalAudio(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLocalAudio"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables or disables the local audio capture."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalAudio(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableLocalAudio:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablelocalaudio(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteRemoteAudioStream(_:mute:)":{"role":"symbol","title":"muteRemoteAudioStream(_:mute:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteRemoteAudioStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio stream of a specified user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteAudioStream(_:mute:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteRemoteAudioStream:mute:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteremoteaudiostream(_:mute:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/adjustUserPlaybackSignalVolume(_:volume:)":{"role":"symbol","title":"adjustUserPlaybackSignalVolume(_:volume:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustUserPlaybackSignalVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adjusts the playback signal volume of a specified remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustUserPlaybackSignalVolume(_:volume:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustUserPlaybackSignalVolume:volume:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/adjustuserplaybacksignalvolume(_:volume:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioSessionOperationRestriction(_:)":{"role":"symbol","title":"setAudioSessionOperationRestriction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioSessionOperationRestriction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the operational permission of the SDK on the audio session."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioSessionOperationRestriction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioSessionOperationRestriction:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudiosessionoperationrestriction(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioProfile(_:scenario:)":{"deprecated":true,"role":"symbol","title":"setAudioProfile(_:scenario:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioProfile","preciseIdentifier":"c:@E@AgoraAudioProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scenario"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioScenario","preciseIdentifier":"c:@E@AgoraAudioScenario"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the audio profile and audio scenario."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:scenario:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioProfile:scenario:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioprofile(_:scenario:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/adjustCustomAudioPublishVolume(_:volume:)":{"role":"symbol","title":"adjustCustomAudioPublishVolume(_:volume:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adjusts the volume of the custom external audio source when it is published in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustCustomAudioPublishVolume(_:volume:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustCustomAudioPublishVolume:volume:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/adjustcustomaudiopublishvolume(_:volume:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/disableAudio()":{"role":"symbol","title":"disableAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAudio"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Disables the audio module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableAudio"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/disableaudio()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteAllRemoteAudioStreams(_:)":{"role":"symbol","title":"muteAllRemoteAudioStreams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteAudioStreams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio streams of all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteAudioStreams(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteallremoteaudiostreams(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioScenario(_:)":{"role":"symbol","title":"setAudioScenario(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioScenario"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioScenario","preciseIdentifier":"c:@E@AgoraAudioScenario"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets audio scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioScenario(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioScenario:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioscenario(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableAudio()":{"role":"symbol","title":"enableAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableAudio"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the audio module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableAudio"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enableaudio()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/adjustRecordingSignalVolume(_:)":{"role":"symbol","title":"adjustRecordingSignalVolume(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustRecordingSignalVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adjusts the capturing signal volume."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustRecordingSignalVolume(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustRecordingSignalVolume:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/adjustrecordingsignalvolume(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adjustCustomAudioPublishVolume:volume:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume:volume:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Audio Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalAudio(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:scenario:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioScenario(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalAudioStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteAudioStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteAudioStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioSessionOperationRestriction(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustRecordingSignalVolume(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustUserPlaybackSignalVolume(_:volume:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"trackId"},{"kind":"text","text":" "},{"kind":"identifier","text":"volume:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"volume"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:)\/title","value":"setAudioProfile:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalAudioStream(_:)\/title","value":"muteLocalAudioStream:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalAudioStream(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteLocalAudioStream:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalAudio(_:)\/title","value":"enableLocalAudio:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalAudio(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableLocalAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteAudioStream(_:mute:)\/title","value":"muteRemoteAudioStream:mute:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteAudioStream(_:mute:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteRemoteAudioStream:mute:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustUserPlaybackSignalVolume(_:volume:)\/title","value":"adjustUserPlaybackSignalVolume:volume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustUserPlaybackSignalVolume(_:volume:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustUserPlaybackSignalVolume:volume:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioSessionOperationRestriction(_:)\/title","value":"setAudioSessionOperationRestriction:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioSessionOperationRestriction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioSessionOperationRestriction:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:scenario:)\/title","value":"setAudioProfile:scenario:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:scenario:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioProfile:scenario:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustCustomAudioPublishVolume(_:volume:)\/title","value":"adjustCustomAudioPublishVolume:volume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustCustomAudioPublishVolume(_:volume:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume:volume:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableAudio()\/title","value":"disableAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteAudioStreams(_:)\/title","value":"muteAllRemoteAudioStreams:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteAudioStreams(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioScenario(_:)\/title","value":"setAudioScenario:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioScenario(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioScenario:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableAudio()\/title","value":"enableAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustRecordingSignalVolume(_:)\/title","value":"adjustRecordingSignalVolume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustRecordingSignalVolume(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustRecordingSignalVolume:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}