{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createLocalMediaRecorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder","text":"AgoraMediaRecorder"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createlocalmediarecorder(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createlocalmediarecorder(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createLocalMediaRecorder(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the blocklist of subscriptions for video streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the video streams of a user that you do"},{"type":"text","text":" "},{"type":"text","text":"not want to subscribe to.If a user is added in the allowlist and blocklist at"},{"type":"text","text":" "},{"type":"text","text":"the same time, only the blocklist takes effect.Once the blocklist of"},{"type":"text","text":" "},{"type":"text","text":"subscriptions is set, it is effective even if you leave the current channel"},{"type":"text","text":" "},{"type":"text","text":"and rejoin the channel.You can call this method either before or after"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.The blocklist is not affected by the setting in"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteVideoStream , muteAllRemoteVideoStreams and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createLocalMediaRecorder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder"},{"kind":"text","text":"?"}],"title":"createLocalMediaRecorder(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)createLocalMediaRecorder:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"createLocalMediaRecorder:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder":{"role":"symbol","title":"AgoraMediaRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorder"}],"abstract":[{"type":"text","text":"Used for recording audio and video on the client."},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaRecorder can record the following:"},{"type":"text","text":" "},{"type":"text","text":"The audio captured by the local microphone and encoded in AAC format.The"},{"type":"text","text":" "},{"type":"text","text":"video captured by the local camera and encoded by the SDK.In the"},{"type":"text","text":" "},{"type":"text","text":"COMMUNICATION channel profile, this feature is unavailable when there are"},{"type":"text","text":" "},{"type":"text","text":"users using SDK versions earlier than v3.0.0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorder"}],"url":"\/documentation\/agorartckit\/agoramediarecorder"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/createLocalMediaRecorder(_:)":{"role":"symbol","title":"createLocalMediaRecorder(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createLocalMediaRecorder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the blocklist of subscriptions for video streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the video streams of a user that you do"},{"type":"text","text":" "},{"type":"text","text":"not want to subscribe to.If a user is added in the allowlist and blocklist at"},{"type":"text","text":" "},{"type":"text","text":"the same time, only the blocklist takes effect.Once the blocklist of"},{"type":"text","text":" "},{"type":"text","text":"subscriptions is set, it is effective even if you leave the current channel"},{"type":"text","text":" "},{"type":"text","text":"and rejoin the channel.You can call this method either before or after"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.The blocklist is not affected by the setting in"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteVideoStream , muteAllRemoteVideoStreams and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createLocalMediaRecorder(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createLocalMediaRecorder:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/createlocalmediarecorder(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createLocalMediaRecorder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createLocalMediaRecorder:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder","text":"AgoraMediaRecorder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createLocalMediaRecorder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/title","value":"AgoraMediaRecorder"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorder"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createLocalMediaRecorder(_:)\/title","value":"createLocalMediaRecorder:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createLocalMediaRecorder(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createLocalMediaRecorder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}