{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMediaPlayerCacheManager"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCacheManagerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerCacheManagerProtocol","text":"AgoraRtcMediaPlayerCacheManagerProtocol"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createmediaplayercachemanager()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createmediaplayercachemanager()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createMediaPlayerCacheManager()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMediaPlayerCacheManager"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerCacheManagerProtocol"},{"kind":"text","text":"?"}],"title":"createMediaPlayerCacheManager()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)createMediaPlayerCacheManager","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"createMediaPlayerCacheManager"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/createMediaPlayerCacheManager()":{"role":"symbol","title":"createMediaPlayerCacheManager()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMediaPlayerCacheManager"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerCacheManagerProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createMediaPlayerCacheManager()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMediaPlayerCacheManager"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/createmediaplayercachemanager()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerCacheManagerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerCacheManagerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol"}],"abstract":[{"type":"text","text":"This class provides methods to manage cached media files."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCacheManagerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayercachemanagerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createMediaPlayerCacheManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMediaPlayerCacheManager"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<AgoraRtcMediaPlayerCacheManagerProtocol>","preciseIdentifier":"c:Qoobjc(pl)AgoraRtcMediaPlayerCacheManagerProtocol"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createMediaPlayerCacheManager"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createMediaPlayerCacheManager()\/title","value":"createMediaPlayerCacheManager"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createMediaPlayerCacheManager()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMediaPlayerCacheManager"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCacheManagerProtocol\/title","value":"AgoraRtcMediaPlayerCacheManagerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCacheManagerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}