{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDataStreamEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDataStreamConfig","preciseIdentifier":"c:objc(cs)AgoraDataStreamConfig","text":"AgoraDataStreamConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createdatastreamex(_:config:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createdatastreamex(_:config:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createDataStreamEx(_:config:connection:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createDataStreamEx:config:connection:"}],"role":"symbol","title":"createDataStreamEx(_:config:connection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDataStreamEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDataStreamConfig","preciseIdentifier":"c:objc(cs)AgoraDataStreamConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)createDataStreamEx:config:connection:","extendedModule":"AgoraRtcKit","modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/createDataStreamEx(_:config:connection:)":{"role":"symbol","title":"createDataStreamEx(_:config:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDataStreamEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDataStreamConfig","preciseIdentifier":"c:objc(cs)AgoraDataStreamConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createDataStreamEx(_:config:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createDataStreamEx:config:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/createdatastreamex(_:config:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDataStreamConfig":{"role":"symbol","title":"AgoraDataStreamConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDataStreamConfig"}],"abstract":[{"type":"text","text":"The configurations for the data stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDataStreamConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDataStreamConfig"}],"url":"\/documentation\/agorartckit\/agoradatastreamconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createDataStreamEx:config:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createDataStreamEx:config:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"createDataStreamEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"streamId"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDataStreamConfig","preciseIdentifier":"c:objc(cs)AgoraDataStreamConfig","text":"AgoraDataStreamConfig"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createDataStreamEx(_:config:connection:)\/title","value":"createDataStreamEx:config:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createDataStreamEx(_:config:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createDataStreamEx:config:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDataStreamConfig\/title","value":"AgoraDataStreamConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDataStreamConfig\/fragments","value":[{"kind":"identifier","text":"AgoraDataStreamConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}