{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCustomAudioTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"trackType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioTrackType","preciseIdentifier":"c:@E@AgoraAudioTrackType","text":"AgoraAudioTrackType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioTrackConfig","preciseIdentifier":"c:objc(cs)AgoraAudioTrackConfig","text":"AgoraAudioTrackConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createcustomaudiotrack(_:config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createcustomaudiotrack(_:config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createCustomAudioTrack(_:config:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCustomAudioTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioTrackType","preciseIdentifier":"c:@E@AgoraAudioTrackType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioTrackConfig","preciseIdentifier":"c:objc(cs)AgoraAudioTrackConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"createCustomAudioTrack(_:config:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)createCustomAudioTrack:config:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"createCustomAudioTrack:config:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/createCustomAudioTrack(_:config:)":{"role":"symbol","title":"createCustomAudioTrack(_:config:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCustomAudioTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioTrackType","preciseIdentifier":"c:@E@AgoraAudioTrackType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioTrackConfig","preciseIdentifier":"c:objc(cs)AgoraAudioTrackConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createCustomAudioTrack(_:config:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createCustomAudioTrack:config:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/createcustomaudiotrack(_:config:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioTrackType":{"role":"symbol","title":"AgoraAudioTrackType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioTrackType"}],"abstract":[{"type":"text","text":"The type of the audio track."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioTrackType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioTrackType"}],"url":"\/documentation\/agorartckit\/agoraaudiotracktype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioTrackConfig":{"role":"symbol","title":"AgoraAudioTrackConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioTrackConfig"}],"abstract":[{"type":"text","text":"The configuration of custom audio tracks."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioTrackConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioTrackConfig"}],"url":"\/documentation\/agorartckit\/agoraaudiotrackconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createCustomAudioTrack:config:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createCustomAudioTrack:config:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"createCustomAudioTrack:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioTrackType","preciseIdentifier":"c:@E@AgoraAudioTrackType","text":"AgoraAudioTrackType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"trackType"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioTrackConfig","preciseIdentifier":"c:objc(cs)AgoraAudioTrackConfig","text":"AgoraAudioTrackConfig"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createCustomAudioTrack(_:config:)\/title","value":"createCustomAudioTrack:config:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createCustomAudioTrack(_:config:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createCustomAudioTrack:config:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioTrackType\/title","value":"AgoraAudioTrackType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioTrackType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioTrackType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioTrackConfig\/title","value":"AgoraAudioTrackConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioTrackConfig\/fragments","value":[{"kind":"identifier","text":"AgoraAudioTrackConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}