{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMediaPlayer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerDelegate","text":"AgoraRtcMediaPlayerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol","text":"AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The AgoraRtcMediaPlayerProtocol instance, if the method call succeeds. An empty pointer, if the method call fails."}]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The event handler for AgoraRtcEngineKit. See AgoraRtcEngineDelegate."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createmediaplayer(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createmediaplayer(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createMediaPlayer(with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMediaPlayer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":"?"}],"title":"createMediaPlayer(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)createMediaPlayerWithDelegate:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"createMediaPlayerWithDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate":{"role":"symbol","title":"AgoraRtcMediaPlayerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"abstract":[{"type":"text","text":"Provides callbacks for media players."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/createMediaPlayer(with:)":{"role":"symbol","title":"createMediaPlayer(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMediaPlayer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createMediaPlayer(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMediaPlayerWithDelegate:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/createmediaplayer(with:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createMediaPlayerWithDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMediaPlayerWithDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<AgoraRtcMediaPlayerProtocol>","preciseIdentifier":"c:Qoobjc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createMediaPlayerWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraRtcMediaPlayerDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraRtcMediaPlayerDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/title","value":"AgoraRtcMediaPlayerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createMediaPlayer(with:)\/title","value":"createMediaPlayerWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createMediaPlayer(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMediaPlayerWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}