{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDataStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"reliable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ordered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"streamId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An output parameter; the ID of the data stream created."}]}]},{"name":"reliable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether or not the data stream is reliable:YES: The"},{"type":"text","text":" "},{"type":"text","text":"recipients receive the data from the sender within five seconds. If the"},{"type":"text","text":" "},{"type":"text","text":"recipient does not receive the data within five seconds, the SDK triggers the"},{"type":"text","text":" "},{"type":"text","text":"didOccurStreamMessageErrorFromUid callback and returns an error code.NO:"},{"type":"text","text":" "},{"type":"text","text":"There is no guarantee that the recipients receive the data stream within five"},{"type":"text","text":" "},{"type":"text","text":"seconds and no error message is reported for any delay or missing data"},{"type":"text","text":" "},{"type":"text","text":"stream."}]}]},{"name":"ordered","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether or not the recipients receive the data stream in"},{"type":"text","text":" "},{"type":"text","text":"the sent order: YES: The recipients receive the data in the sent order.NO:"},{"type":"text","text":" "},{"type":"text","text":"The recipients do not receive the data in the sent order."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createdatastream(_:reliable:ordered:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createdatastream(_:reliable:ordered:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createDataStream(_:reliable:ordered:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a data stream."},{"type":"text","text":" "},{"type":"text","text":"Each user can create up to five data streams during the lifecycle of"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineKit . The data stream will be destroyed when leaving the"},{"type":"text","text":" "},{"type":"text","text":"channel, and the data stream needs to be recreated if needed.Call this method"},{"type":"text","text":" "},{"type":"text","text":"after joining a channel.Agora does not support setting reliable as YES and"},{"type":"text","text":" "},{"type":"text","text":"ordered as YES."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDataStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"reliable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ordered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"createDataStream(_:reliable:ordered:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)createDataStream:reliable:ordered:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"createDataStream:reliable:ordered:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/createDataStream(_:reliable:ordered:)":{"role":"symbol","title":"createDataStream(_:reliable:ordered:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDataStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"reliable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ordered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Creates a data stream."},{"type":"text","text":" "},{"type":"text","text":"Each user can create up to five data streams during the lifecycle of"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineKit . The data stream will be destroyed when leaving the"},{"type":"text","text":" "},{"type":"text","text":"channel, and the data stream needs to be recreated if needed.Call this method"},{"type":"text","text":" "},{"type":"text","text":"after joining a channel.Agora does not support setting reliable as YES and"},{"type":"text","text":" "},{"type":"text","text":"ordered as YES."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createDataStream(_:reliable:ordered:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createDataStream:reliable:ordered:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/createdatastream(_:reliable:ordered:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createDataStream:reliable:ordered:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createDataStream:reliable:ordered:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"createDataStream:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"streamId"},{"kind":"text","text":" "},{"kind":"identifier","text":"reliable:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reliable"},{"kind":"text","text":" "},{"kind":"identifier","text":"ordered:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"ordered"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createDataStream(_:reliable:ordered:)\/title","value":"createDataStream:reliable:ordered:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createDataStream(_:reliable:ordered:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createDataStream:reliable:ordered:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}