{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCustomVideoTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the method call is successful, the video track ID is returned"},{"type":"text","text":" "},{"type":"text","text":"as the unique identifier of the video track. If the method call fails, a"},{"type":"text","text":" "},{"type":"text","text":"negative value is returned."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createcustomvideotrack()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/createcustomvideotrack()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createCustomVideoTrack()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a customized video track."},{"type":"text","text":" "},{"type":"text","text":"When you need to publish multiple custom captured videos in the channel, you"},{"type":"text","text":" "},{"type":"text","text":"can refer to the following steps:Call this method to create a video track and"},{"type":"text","text":" "},{"type":"text","text":"get the video track ID.In each channel’s AgoraRtcChannelMediaOptions , set"},{"type":"text","text":" "},{"type":"text","text":"the customVideoTrackId parameter to the ID of the video track you want to"},{"type":"text","text":" "},{"type":"text","text":"publish, and set publishCustomVideoTrack to YES.If you call"},{"type":"text","text":" "},{"type":"text","text":"pushExternalVideoFrame customVideoTrackId as the videoTrackId set in step 2,"},{"type":"text","text":" "},{"type":"text","text":"you can publish the corresponding custom video source in multiple channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCustomVideoTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"title":"createCustomVideoTrack()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)createCustomVideoTrack","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"createCustomVideoTrack"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/createCustomVideoTrack()":{"role":"symbol","title":"createCustomVideoTrack()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCustomVideoTrack"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"abstract":[{"type":"text","text":"Creates a customized video track."},{"type":"text","text":" "},{"type":"text","text":"When you need to publish multiple custom captured videos in the channel, you"},{"type":"text","text":" "},{"type":"text","text":"can refer to the following steps:Call this method to create a video track and"},{"type":"text","text":" "},{"type":"text","text":"get the video track ID.In each channel’s AgoraRtcChannelMediaOptions , set"},{"type":"text","text":" "},{"type":"text","text":"the customVideoTrackId parameter to the ID of the video track you want to"},{"type":"text","text":" "},{"type":"text","text":"publish, and set publishCustomVideoTrack to YES.If you call"},{"type":"text","text":" "},{"type":"text","text":"pushExternalVideoFrame customVideoTrackId as the videoTrackId set in step 2,"},{"type":"text","text":" "},{"type":"text","text":"you can publish the corresponding custom video source in multiple channels."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/createCustomVideoTrack()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createCustomVideoTrack"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/createcustomvideotrack()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createCustomVideoTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createCustomVideoTrack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"unsigned int","preciseIdentifier":"c:i"},{"kind":"text","text":") "},{"kind":"identifier","text":"createCustomVideoTrack"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createCustomVideoTrack()\/title","value":"createCustomVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1createCustomVideoTrack()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createCustomVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}