{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableContentInspect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig","preciseIdentifier":"c:objc(cs)AgoraContentInspectConfig","text":"AgoraContentInspectConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable video screenshot and uploadYES:"},{"type":"text","text":" "},{"type":"text","text":"Enables video screenshot and upload. NO: Disables video screenshot and"},{"type":"text","text":" "},{"type":"text","text":"upload."}]}]},{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configuration of video screenshot and upload. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraContentInspectConfig ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablecontentinspect(_:config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablecontentinspect(_:config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableContentInspect(_:config:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables or disables video screenshot and upload."},{"type":"text","text":" "},{"type":"text","text":"When video screenshot and upload function is enabled, the SDK takes"},{"type":"text","text":" "},{"type":"text","text":"screenshots and upload videos sent by local users based on the type and"},{"type":"text","text":" "},{"type":"text","text":"frequency of the module you set in AgoraContentInspectConfig . After video"},{"type":"text","text":" "},{"type":"text","text":"screenshot and upload, the Agora server sends the callback notification to"},{"type":"text","text":" "},{"type":"text","text":"your app server in HTTPS requests and sends all screenshots to the"},{"type":"text","text":" "},{"type":"text","text":"third-party cloud storage service.Before calling this method, ensure that the"},{"type":"text","text":" "},{"type":"text","text":"video screenshot upload service has been activated. This method relies on the"},{"type":"text","text":" "},{"type":"text","text":"video screenshot and upload dynamic library"},{"type":"text","text":" "},{"type":"text","text":"AgoraContentInspectExtension.xcframework. If the dynamic library is deleted,"},{"type":"text","text":" "},{"type":"text","text":"the function cannot be enabled normally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableContentInspect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraContentInspectConfig","preciseIdentifier":"c:objc(cs)AgoraContentInspectConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enableContentInspect(_:config:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableContentInspect:config:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableContentInspect:config:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableContentInspect(_:config:)":{"role":"symbol","title":"enableContentInspect(_:config:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableContentInspect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraContentInspectConfig","preciseIdentifier":"c:objc(cs)AgoraContentInspectConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables or disables video screenshot and upload."},{"type":"text","text":" "},{"type":"text","text":"When video screenshot and upload function is enabled, the SDK takes"},{"type":"text","text":" "},{"type":"text","text":"screenshots and upload videos sent by local users based on the type and"},{"type":"text","text":" "},{"type":"text","text":"frequency of the module you set in AgoraContentInspectConfig . After video"},{"type":"text","text":" "},{"type":"text","text":"screenshot and upload, the Agora server sends the callback notification to"},{"type":"text","text":" "},{"type":"text","text":"your app server in HTTPS requests and sends all screenshots to the"},{"type":"text","text":" "},{"type":"text","text":"third-party cloud storage service.Before calling this method, ensure that the"},{"type":"text","text":" "},{"type":"text","text":"video screenshot upload service has been activated. This method relies on the"},{"type":"text","text":" "},{"type":"text","text":"video screenshot and upload dynamic library"},{"type":"text","text":" "},{"type":"text","text":"AgoraContentInspectExtension.xcframework. If the dynamic library is deleted,"},{"type":"text","text":" "},{"type":"text","text":"the function cannot be enabled normally."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableContentInspect(_:config:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableContentInspect:config:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablecontentinspect(_:config:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectConfig":{"role":"symbol","title":"AgoraContentInspectConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectConfig"}],"abstract":[{"type":"text","text":"Configuration of video screenshot and upload."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectConfig"}],"url":"\/documentation\/agorartckit\/agoracontentinspectconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableContentInspect:config:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableContentInspect:config:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableContentInspect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig","preciseIdentifier":"c:objc(cs)AgoraContentInspectConfig","text":"AgoraContentInspectConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableContentInspect(_:config:)\/title","value":"enableContentInspect:config:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableContentInspect(_:config:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableContentInspect:config:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig\/title","value":"AgoraContentInspectConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}