{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inEarMonitoring"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeAudioFilters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType","text":"AgoraEarMonitoringFilterType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. - 8: Make sure the current audio routing is Bluetooth or headset."}]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Enables or disables in-ear monitoring.YES: Enables in-ear monitoring.NO: (Default) Disables in-ear monitoring."}]}]},{"name":"includeAudioFilters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio filter of in-ear monitoring: See AgoraEarMonitoringFilterType."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method enables or disables in-ear monitoring. Users must use earphones (wired or Bluetooth) to hear the in-ear monitoring effect. You can call this method either before or after joining a channel."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enable(inearmonitoring:includeaudiofilters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enable(inearmonitoring:includeaudiofilters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enable(inEarMonitoring:includeAudioFilters:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables in-ear monitoring."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inEarMonitoring"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeAudioFilters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enable(inEarMonitoring:includeAudioFilters:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableInEarMonitoring:includeAudioFilters:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableInEarMonitoring:includeAudioFilters:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType":{"role":"symbol","title":"AgoraEarMonitoringFilterType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enable(inEarMonitoring:includeAudioFilters:)":{"role":"symbol","title":"enable(inEarMonitoring:includeAudioFilters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inEarMonitoring"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeAudioFilters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables in-ear monitoring."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enable(inEarMonitoring:includeAudioFilters:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableInEarMonitoring:includeAudioFilters:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enable(inearmonitoring:includeaudiofilters:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableInEarMonitoring:includeAudioFilters:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableInEarMonitoring:includeAudioFilters:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableInEarMonitoring:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeAudioFilters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType","text":"AgoraEarMonitoringFilterType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includeAudioFilters"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType\/title","value":"AgoraEarMonitoringFilterType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enable(inEarMonitoring:includeAudioFilters:)\/title","value":"enableInEarMonitoring:includeAudioFilters:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enable(inEarMonitoring:includeAudioFilters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableInEarMonitoring:includeAudioFilters:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}