{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableWebSdkInteroperability"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable interoperability:YES: Enable"},{"type":"text","text":" "},{"type":"text","text":"interoperability.NO: (Default) Disable interoperability."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablewebsdkinteroperability(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablewebsdkinteroperability(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableWebSdkInteroperability(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables interoperability with the Agora Web SDK (applicable only in the live"},{"type":"text","text":" "},{"type":"text","text":"streaming scenarios). Deprecated:The SDK automatically enables"},{"type":"text","text":" "},{"type":"text","text":"interoperability with the Web SDK, so you no longer need to call this"},{"type":"text","text":" "},{"type":"text","text":"method.You can call this method to enable or disable interoperability with"},{"type":"text","text":" "},{"type":"text","text":"the Agora Web SDK. If a channel has Web SDK users, ensure that you call this"},{"type":"text","text":" "},{"type":"text","text":"method, or the video of the Native user will be a black screen for the Web"},{"type":"text","text":" "},{"type":"text","text":"user.This method is only applicable in live streaming scenarios, and"},{"type":"text","text":" "},{"type":"text","text":"interoperability is enabled by default in communication scenarios."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"enableWebSdkInteroperability:"}],"role":"symbol","title":"enableWebSdkInteroperability(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableWebSdkInteroperability"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableWebSdkInteroperability:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableWebSdkInteroperability(_:)":{"deprecated":true,"role":"symbol","title":"enableWebSdkInteroperability(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableWebSdkInteroperability"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables interoperability with the Agora Web SDK (applicable only in the live"},{"type":"text","text":" "},{"type":"text","text":"streaming scenarios). Deprecated:The SDK automatically enables"},{"type":"text","text":" "},{"type":"text","text":"interoperability with the Web SDK, so you no longer need to call this"},{"type":"text","text":" "},{"type":"text","text":"method.You can call this method to enable or disable interoperability with"},{"type":"text","text":" "},{"type":"text","text":"the Agora Web SDK. If a channel has Web SDK users, ensure that you call this"},{"type":"text","text":" "},{"type":"text","text":"method, or the video of the Native user will be a black screen for the Web"},{"type":"text","text":" "},{"type":"text","text":"user.This method is only applicable in live streaming scenarios, and"},{"type":"text","text":" "},{"type":"text","text":"interoperability is enabled by default in communication scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableWebSdkInteroperability(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableWebSdkInteroperability:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablewebsdkinteroperability(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableWebSdkInteroperability:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWebSdkInteroperability:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableWebSdkInteroperability:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableWebSdkInteroperability(_:)\/title","value":"enableWebSdkInteroperability:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableWebSdkInteroperability(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWebSdkInteroperability:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}