{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablevideo()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablevideo()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables the video module."},{"type":"text","text":" "},{"type":"text","text":"Call this method either before joining a channel or during a call. If this"},{"type":"text","text":" "},{"type":"text","text":"method is called before joining a channel, the call starts in the video mode;"},{"type":"text","text":" "},{"type":"text","text":"if called during a call, the audio call switches to a video call. Call"},{"type":"text","text":" "},{"type":"text","text":"disableVideo to disable the video mode.A successful call of this method"},{"type":"text","text":" "},{"type":"text","text":"triggers the remoteVideoStateChangedOfUid callback on the remote client.This"},{"type":"text","text":" "},{"type":"text","text":"method enables the internal engine and is valid after leaving the"},{"type":"text","text":" "},{"type":"text","text":"channel.This method resets the internal engine and thus might takes some time"},{"type":"text","text":" "},{"type":"text","text":"to take effect. Agora recommends using the following APIs to control the"},{"type":"text","text":" "},{"type":"text","text":"video modules separately: enableLocalVideo : Whether to enable the camera to"},{"type":"text","text":" "},{"type":"text","text":"create the local video stream. muteLocalVideoStream : Whether to publish the"},{"type":"text","text":" "},{"type":"text","text":"local video stream. muteRemoteVideoStream : Whether to subscribe to and play"},{"type":"text","text":" "},{"type":"text","text":"the remote video stream. muteAllRemoteVideoStreams : Whether to subscribe to"},{"type":"text","text":" "},{"type":"text","text":"and play all remote video streams."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enableVideo()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableVideo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableVideo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"seeAlsoSections":[{"title":"Video Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableVideo()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfiguration(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/stopPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalRenderMode(_:mirror:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteRenderMode(_:mode:mirror:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStream(_:type:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalVideoStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteVideoStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteVideoStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableInstantMediaRendering()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startMediaRenderingTracing()"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableLocalVideo(_:)":{"role":"symbol","title":"enableLocalVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLocalVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables\/Disables the local video capture."},{"type":"text","text":" "},{"type":"text","text":"This method disables or re-enables the local video capture, and does not"},{"type":"text","text":" "},{"type":"text","text":"affect receiving the remote video stream.After calling enableVideo , the"},{"type":"text","text":" "},{"type":"text","text":"local video capture is enabled by default. You can call enableLocalVideo (NO)"},{"type":"text","text":" "},{"type":"text","text":"to disable the local video capture. If you want to re-enable the local video"},{"type":"text","text":" "},{"type":"text","text":"capture, call enableLocalVideo(YES).After the local video capturer is"},{"type":"text","text":" "},{"type":"text","text":"successfully disabled or re-enabled, the SDK triggers the"},{"type":"text","text":" "},{"type":"text","text":"remoteVideoStateChangedOfUid callback on the remote client.You can call this"},{"type":"text","text":" "},{"type":"text","text":"method either before or after joining a channel.This method enables the"},{"type":"text","text":" "},{"type":"text","text":"internal engine and is valid after leaving the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableLocalVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablelocalvideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/disableVideo()":{"role":"symbol","title":"disableVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Disables the video module."},{"type":"text","text":" "},{"type":"text","text":"This method can be called before joining a channel or during a call to"},{"type":"text","text":" "},{"type":"text","text":"disable the video module. If it is called before joining a channel, an audio"},{"type":"text","text":" "},{"type":"text","text":"call starts when you join the channel; if called during a call, a video call"},{"type":"text","text":" "},{"type":"text","text":"switches to an audio call. Call enableVideo to enable the video module.A"},{"type":"text","text":" "},{"type":"text","text":"successful call of this method triggers the didVideoEnabled (NO) callback on"},{"type":"text","text":" "},{"type":"text","text":"the remote client.This method affects the internal engine and can be called"},{"type":"text","text":" "},{"type":"text","text":"after leaving the channel.This method resets the internal engine and thus"},{"type":"text","text":" "},{"type":"text","text":"might takes some time to take effect. Agora recommends using the following"},{"type":"text","text":" "},{"type":"text","text":"APIs to control the video modules separately: enableLocalVideo : Whether to"},{"type":"text","text":" "},{"type":"text","text":"enable the camera to create the local video stream. muteLocalVideoStream :"},{"type":"text","text":" "},{"type":"text","text":"Whether to publish the local video stream. muteRemoteVideoStream : Whether to"},{"type":"text","text":" "},{"type":"text","text":"subscribe to and play the remote video stream. muteAllRemoteVideoStreams :"},{"type":"text","text":" "},{"type":"text","text":"Whether to subscribe to and play all remote video streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableVideo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableVideo"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/disablevideo()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteRenderMode(_:mode:mirror:)":{"role":"symbol","title":"setRemoteRenderMode(_:mode:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteRenderMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the display mode of the video view of a remote user."},{"type":"text","text":" "},{"type":"text","text":"After initializing the video view of a remote user, you can call this method"},{"type":"text","text":" "},{"type":"text","text":"to update its rendering and mirror modes. This method affects only the video"},{"type":"text","text":" "},{"type":"text","text":"view that the local user sees.Please call this method after initializing the"},{"type":"text","text":" "},{"type":"text","text":"remote view by calling the setupRemoteVideo method.During a call, you can"},{"type":"text","text":" "},{"type":"text","text":"call this method as many times as necessary to update the display mode of the"},{"type":"text","text":" "},{"type":"text","text":"video view of a remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteRenderMode(_:mode:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteRenderMode:mode:mirror:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremoterendermode(_:mode:mirror:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteLocalVideoStream(_:)":{"role":"symbol","title":"muteLocalVideoStream(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteLocalVideoStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes publishing the local video stream."},{"type":"text","text":" "},{"type":"text","text":"A successful call of this method triggers the didVideoMuted callback on the"},{"type":"text","text":" "},{"type":"text","text":"remote client.This method executes faster than the enableLocalVideo (NO)"},{"type":"text","text":" "},{"type":"text","text":"method, which controls the sending of the local video stream.This method does"},{"type":"text","text":" "},{"type":"text","text":"not affect any ongoing video recording, because it does not disable the"},{"type":"text","text":" "},{"type":"text","text":"camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalVideoStream(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteLocalVideoStream:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/mutelocalvideostream(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVideoEncoderConfiguration(_:)":{"role":"symbol","title":"setVideoEncoderConfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoEncoderConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoEncoderConfiguration","preciseIdentifier":"c:objc(cs)AgoraVideoEncoderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the video encoder configuration."},{"type":"text","text":" "},{"type":"text","text":"Sets the encoder configuration for the local video.You can call this method"},{"type":"text","text":" "},{"type":"text","text":"either before or after joining a channel. If the user does not need to reset"},{"type":"text","text":" "},{"type":"text","text":"the video encoding properties after joining the channel, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"calling this method before enableVideo to reduce the time to render the first"},{"type":"text","text":" "},{"type":"text","text":"video frame.Both this method and the getMirrorApplied method support setting"},{"type":"text","text":" "},{"type":"text","text":"the mirroring effect. Agora recommends that you only choose one method to set"},{"type":"text","text":" "},{"type":"text","text":"it up. Using both methods at the same time causes the mirroring effect to"},{"type":"text","text":" "},{"type":"text","text":"overlap, which causes the mirroring settings to fail."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfiguration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoEncoderConfiguration:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvideoencoderconfiguration(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteAllRemoteVideoStreams(_:)":{"role":"symbol","title":"muteAllRemoteVideoStreams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteVideoStreams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the video streams of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the local user stops or resumes"},{"type":"text","text":" "},{"type":"text","text":"subscribing to the audio streams of all remote users, including all"},{"type":"text","text":" "},{"type":"text","text":"subsequent users.Call this method after joining a channel.If you do not want"},{"type":"text","text":" "},{"type":"text","text":"to subscribe the video streams of remote users before joining a channel, you"},{"type":"text","text":" "},{"type":"text","text":"can call joinChannelByToken [2\/4] and set autoSubscribeVideo as NO."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteVideoStreams(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteAllRemoteVideoStreams:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteallremotevideostreams(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startPreview()":{"role":"symbol","title":"startPreview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPreview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the local video preview."},{"type":"text","text":" "},{"type":"text","text":"This method starts the local video preview before joining the channel. Before"},{"type":"text","text":" "},{"type":"text","text":"calling this method, ensure that you do the following:Call setupLocalVideo to"},{"type":"text","text":" "},{"type":"text","text":"set the local preview window.Call enableVideo to enable the video.The local"},{"type":"text","text":" "},{"type":"text","text":"preview enables the mirror mode by default.After the local video preview is"},{"type":"text","text":" "},{"type":"text","text":"enabled, if you call leaveChannel [1\/2] to exit the channel, the local"},{"type":"text","text":" "},{"type":"text","text":"preview remains until you call stopPreview to disable it."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startPreview"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startpreview()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setupRemoteVideo(_:)":{"role":"symbol","title":"setupRemoteVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupRemoteVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Initializes the video view of a remote user."},{"type":"text","text":" "},{"type":"text","text":"This method initializes the video view of a remote stream on the local"},{"type":"text","text":" "},{"type":"text","text":"device. It affects only the video view that the local user sees. Call this"},{"type":"text","text":" "},{"type":"text","text":"method to bind the remote video stream to a video view and to set the"},{"type":"text","text":" "},{"type":"text","text":"rendering and mirror modes of the video view.You need to specify the ID of"},{"type":"text","text":" "},{"type":"text","text":"the remote user in this method. If the remote user ID is unknown to the"},{"type":"text","text":" "},{"type":"text","text":"application, set it after the app receives the didJoinedOfUid callback.To"},{"type":"text","text":" "},{"type":"text","text":"unbind the remote user from the view, set the view parameter to NULL.Once the"},{"type":"text","text":" "},{"type":"text","text":"remote user leaves the channel, the SDK unbinds the remote user.To update the"},{"type":"text","text":" "},{"type":"text","text":"rendering or mirror mode of the remote video view during a call, use the"},{"type":"text","text":" "},{"type":"text","text":"setRemoteRenderMode [2\/2] method.If you use the Agora recording function, the"},{"type":"text","text":" "},{"type":"text","text":"recording client joins the channel as a placeholder client, triggering the"},{"type":"text","text":" "},{"type":"text","text":"didJoinedOfUid callback. Do not bind the placeholder client to the app view"},{"type":"text","text":" "},{"type":"text","text":"because the placeholder client does not send any video streams. If your app"},{"type":"text","text":" "},{"type":"text","text":"does not recognize the placeholder client, bind the remote user to the view"},{"type":"text","text":" "},{"type":"text","text":"when the SDK triggers the firstRemoteVideoDecodedOfUid callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupRemoteVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setupremotevideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startMediaRenderingTracing()":{"role":"symbol","title":"startMediaRenderingTracing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startMediaRenderingTracing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables tracing the video frame rendering process."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1The SDK starts tracing the rendering status of the video frames in"},{"type":"text","text":" "},{"type":"text","text":"the channel from the moment this method is successfully called and reports"},{"type":"text","text":" "},{"type":"text","text":"information about the event through the videoRenderingTracingResultOfUid"},{"type":"text","text":" "},{"type":"text","text":"callback.By default, the SDK starts tracing the video rendering event"},{"type":"text","text":" "},{"type":"text","text":"automatically when the local user successfully joins the channel. You can"},{"type":"text","text":" "},{"type":"text","text":"call this method at an appropriate time according to the actual application"},{"type":"text","text":" "},{"type":"text","text":"scenario to customize the tracing process.After the local user leaves the"},{"type":"text","text":" "},{"type":"text","text":"current channel, the SDK automatically resets the time point to the next time"},{"type":"text","text":" "},{"type":"text","text":"when the user successfully joins the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startMediaRenderingTracing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startMediaRenderingTracing"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startmediarenderingtracing()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteVideoStream(_:type:)":{"role":"symbol","title":"setRemoteVideoStream(_:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the stream type of the remote video."},{"type":"text","text":" "},{"type":"text","text":"Under limited network conditions, if the publisher has not disabled the"},{"type":"text","text":" "},{"type":"text","text":"dual-stream mode using enableDualStreamMode [2\/2] (NO), the receiver can"},{"type":"text","text":" "},{"type":"text","text":"choose to receive either the high-quality video stream or the low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream. The high-quality video stream has a higher resolution and"},{"type":"text","text":" "},{"type":"text","text":"bitrate, and the low-quality video stream has a lower resolution and"},{"type":"text","text":" "},{"type":"text","text":"bitrate.By default, users receive the high-quality video stream. Call this"},{"type":"text","text":" "},{"type":"text","text":"method if you want to switch to the low-quality video stream. This method"},{"type":"text","text":" "},{"type":"text","text":"allows the app to adjust the corresponding video stream type based on the"},{"type":"text","text":" "},{"type":"text","text":"size of the video window to reduce the bandwidth and resources. The aspect"},{"type":"text","text":" "},{"type":"text","text":"ratio of the low-quality video stream is the same as the high-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream. Once the resolution of the high-quality video stream is set, the"},{"type":"text","text":" "},{"type":"text","text":"system automatically sets the resolution, frame rate, and bitrate of the"},{"type":"text","text":" "},{"type":"text","text":"low-quality video stream.The SDK enables the low-quality video stream auto"},{"type":"text","text":" "},{"type":"text","text":"mode on the sender by default (not actively sending low-quality video"},{"type":"text","text":" "},{"type":"text","text":"streams). The host at the receiving end can call this method to initiate a"},{"type":"text","text":" "},{"type":"text","text":"low-quality video stream stream request on the receiving end, and the sender"},{"type":"text","text":" "},{"type":"text","text":"automatically switches to the low-quality video stream mode after receiving"},{"type":"text","text":" "},{"type":"text","text":"the request.The result of this method returns in the didApiCallExecute"},{"type":"text","text":" "},{"type":"text","text":"callback.You can call this method either before or after joining a channel."},{"type":"text","text":" "},{"type":"text","text":"If you call both setRemoteVideoStream and setRemoteDefaultVideoStreamType ,"},{"type":"text","text":" "},{"type":"text","text":"the setting of setRemoteVideoStream takes effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStream(_:type:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoStream:type:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremotevideostream(_:type:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setLocalRenderMode(_:mirror:)":{"role":"symbol","title":"setLocalRenderMode(_:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalRenderMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the display mode of the local video view."},{"type":"text","text":" "},{"type":"text","text":"After initializing the local video view, you can call this method to update"},{"type":"text","text":" "},{"type":"text","text":"its rendering and mirror modes. It affects only the video view that the local"},{"type":"text","text":" "},{"type":"text","text":"user sees, not the published local video stream.Ensure that you have called"},{"type":"text","text":" "},{"type":"text","text":"the setupLocalVideo method to initialize the local video view before calling"},{"type":"text","text":" "},{"type":"text","text":"this method.During a call, you can call this method as many times as"},{"type":"text","text":" "},{"type":"text","text":"necessary to update the display mode of the local video view."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalRenderMode(_:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLocalRenderMode:mirror:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setlocalrendermode(_:mirror:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteRemoteVideoStream(_:mute:)":{"role":"symbol","title":"muteRemoteVideoStream(_:mute:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteRemoteVideoStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the video stream of a specified user."},{"type":"text","text":" "},{"type":"text","text":"Call this method after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteVideoStream(_:mute:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteRemoteVideoStream:mute:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteremotevideostream(_:mute:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableInstantMediaRendering()":{"role":"symbol","title":"enableInstantMediaRendering()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableInstantMediaRendering"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables audio and video frame instant rendering."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1After successfully calling this method, the SDK enables the"},{"type":"text","text":" "},{"type":"text","text":"instant frame rendering mode, which can speed up the first frame rendering"},{"type":"text","text":" "},{"type":"text","text":"speed after the user joins the channel.Once the instant rendering function is"},{"type":"text","text":" "},{"type":"text","text":"enabled, it can only be canceled by calling the destroy method to destroy the"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineKit object.In this mode, the SDK uses Agora’s custom encryption"},{"type":"text","text":" "},{"type":"text","text":"algorithm to shorten the time required to establish transmission links, and"},{"type":"text","text":" "},{"type":"text","text":"the security is reduced compared to the standard DTLS (Datagram Transport"},{"type":"text","text":" "},{"type":"text","text":"Layer Security). If the application scenario requires higher security"},{"type":"text","text":" "},{"type":"text","text":"standards, Agora recommends that you do not use this method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableInstantMediaRendering()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableInstantMediaRendering"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enableinstantmediarendering()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/stopPreview()":{"role":"symbol","title":"stopPreview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopPreview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops the local video preview."},{"type":"text","text":" "},{"type":"text","text":"After calling startPreview to start the preview, if you want to close the"},{"type":"text","text":" "},{"type":"text","text":"local video preview, please call this method.Please call this method before"},{"type":"text","text":" "},{"type":"text","text":"joining a channel or after leaving a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/stopPreview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopPreview"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/stoppreview()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setupLocalVideo(_:)":{"role":"symbol","title":"setupLocalVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLocalVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Initializes the local video view."},{"type":"text","text":" "},{"type":"text","text":"This method initializes the video view of a local stream on the local device."},{"type":"text","text":" "},{"type":"text","text":"It affects only the video view that the local user sees, not the published"},{"type":"text","text":" "},{"type":"text","text":"local video stream. Call this method to bind the local video stream to a"},{"type":"text","text":" "},{"type":"text","text":"video view and to set the rendering and mirror modes of the video view.After"},{"type":"text","text":" "},{"type":"text","text":"initialization, call this method to set the local video and then join the"},{"type":"text","text":" "},{"type":"text","text":"channel. The local video still binds to the view after you leave the channel."},{"type":"text","text":" "},{"type":"text","text":"To unbind the local video from the view, set the view parameter as nil.You"},{"type":"text","text":" "},{"type":"text","text":"can call this method either before or after joining a channel.To update the"},{"type":"text","text":" "},{"type":"text","text":"rendering or mirror mode of the local video view during a call, use the"},{"type":"text","text":" "},{"type":"text","text":"setLocalRenderMode [2\/2] method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLocalVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setuplocalvideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableVideo()":{"role":"symbol","title":"enableVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the video module."},{"type":"text","text":" "},{"type":"text","text":"Call this method either before joining a channel or during a call. If this"},{"type":"text","text":" "},{"type":"text","text":"method is called before joining a channel, the call starts in the video mode;"},{"type":"text","text":" "},{"type":"text","text":"if called during a call, the audio call switches to a video call. Call"},{"type":"text","text":" "},{"type":"text","text":"disableVideo to disable the video mode.A successful call of this method"},{"type":"text","text":" "},{"type":"text","text":"triggers the remoteVideoStateChangedOfUid callback on the remote client.This"},{"type":"text","text":" "},{"type":"text","text":"method enables the internal engine and is valid after leaving the"},{"type":"text","text":" "},{"type":"text","text":"channel.This method resets the internal engine and thus might takes some time"},{"type":"text","text":" "},{"type":"text","text":"to take effect. Agora recommends using the following APIs to control the"},{"type":"text","text":" "},{"type":"text","text":"video modules separately: enableLocalVideo : Whether to enable the camera to"},{"type":"text","text":" "},{"type":"text","text":"create the local video stream. muteLocalVideoStream : Whether to publish the"},{"type":"text","text":" "},{"type":"text","text":"local video stream. muteRemoteVideoStream : Whether to subscribe to and play"},{"type":"text","text":" "},{"type":"text","text":"the remote video stream. muteAllRemoteVideoStreams : Whether to subscribe to"},{"type":"text","text":" "},{"type":"text","text":"and play all remote video streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableVideo"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablevideo()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableVideo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVideo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Video Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableVideo()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfiguration(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/stopPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalRenderMode(_:mirror:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteRenderMode(_:mode:mirror:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStream(_:type:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalVideoStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteVideoStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteVideoStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableInstantMediaRendering()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startMediaRenderingTracing()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableVideo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalVideo(_:)\/title","value":"enableLocalVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableLocalVideo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableVideo()\/title","value":"disableVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteRenderMode(_:mode:mirror:)\/title","value":"setRemoteRenderMode:mode:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteRenderMode(_:mode:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteRenderMode:mode:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalVideoStream(_:)\/title","value":"muteLocalVideoStream:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalVideoStream(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteLocalVideoStream:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoEncoderConfiguration(_:)\/title","value":"setVideoEncoderConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoEncoderConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoEncoderConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteVideoStreams(_:)\/title","value":"muteAllRemoteVideoStreams:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteVideoStreams(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteAllRemoteVideoStreams:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startPreview()\/title","value":"startPreview"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startPreview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideo(_:)\/title","value":"setupRemoteVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupRemoteVideo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startMediaRenderingTracing()\/title","value":"startMediaRenderingTracing"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startMediaRenderingTracing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startMediaRenderingTracing"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoStream(_:type:)\/title","value":"setRemoteVideoStream:type:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoStream(_:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoStream:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalRenderMode(_:mirror:)\/title","value":"setLocalRenderMode:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalRenderMode(_:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalRenderMode:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteVideoStream(_:mute:)\/title","value":"muteRemoteVideoStream:mute:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteVideoStream(_:mute:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteRemoteVideoStream:mute:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableInstantMediaRendering()\/title","value":"enableInstantMediaRendering"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableInstantMediaRendering()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableInstantMediaRendering"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1stopPreview()\/title","value":"stopPreview"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1stopPreview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupLocalVideo(_:)\/title","value":"setupLocalVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupLocalVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLocalVideo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideo()\/title","value":"enableVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}