{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDualStreamMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig","text":"AgoraSimulcastStreamConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable dual-stream mode:YES: Enable"},{"type":"text","text":" "},{"type":"text","text":"dual-stream mode.NO: (Default) Disable dual-stream mode."}]}]},{"name":"streamConfig","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the low-quality video stream."},{"type":"text","text":" "},{"type":"text","text":"See AgoraSimulcastStreamConfig ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enabledualstreammode(_:streamconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enabledualstreammode(_:streamconfig:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableDualStreamMode(_:streamConfig:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables or disables the dual-stream mode on the sender and sets the"},{"type":"text","text":" "},{"type":"text","text":"low-quality video stream. You can call this method to enable or disable the"},{"type":"text","text":" "},{"type":"text","text":"dual-stream mode on the publisher side. Dual streams are a pairing of a"},{"type":"text","text":" "},{"type":"text","text":"high-quality video stream and a low-quality video stream:High-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream: High bitrate, high resolution.Low-quality video stream: Low bitrate,"},{"type":"text","text":" "},{"type":"text","text":"low resolution.After you enable dual-stream mode, you can call"},{"type":"text","text":" "},{"type":"text","text":"setRemoteVideoStream to choose to receive either the high-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream or the low-quality video stream on the subscriber side.This method is"},{"type":"text","text":" "},{"type":"text","text":"applicable to all types of streams from the sender, including but not limited"},{"type":"text","text":" "},{"type":"text","text":"to video streams collected from cameras, screen sharing streams, and"},{"type":"text","text":" "},{"type":"text","text":"custom-collected video streams.If you need to enable dual video streams in a"},{"type":"text","text":" "},{"type":"text","text":"multi-channel scenario, you can call the enableDualStreamModeEx method.You"},{"type":"text","text":" "},{"type":"text","text":"can call this method either before or after joining a channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDualStreamMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enableDualStreamMode(_:streamConfig:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableDualStreamMode:streamConfig:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableDualStreamMode:streamConfig:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamConfig":{"role":"symbol","title":"AgoraSimulcastStreamConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}],"abstract":[{"type":"text","text":"The configuration of the low-quality video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreamconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableDualStreamMode(_:streamConfig:)":{"role":"symbol","title":"enableDualStreamMode(_:streamConfig:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDualStreamMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables or disables the dual-stream mode on the sender and sets the"},{"type":"text","text":" "},{"type":"text","text":"low-quality video stream. You can call this method to enable or disable the"},{"type":"text","text":" "},{"type":"text","text":"dual-stream mode on the publisher side. Dual streams are a pairing of a"},{"type":"text","text":" "},{"type":"text","text":"high-quality video stream and a low-quality video stream:High-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream: High bitrate, high resolution.Low-quality video stream: Low bitrate,"},{"type":"text","text":" "},{"type":"text","text":"low resolution.After you enable dual-stream mode, you can call"},{"type":"text","text":" "},{"type":"text","text":"setRemoteVideoStream to choose to receive either the high-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream or the low-quality video stream on the subscriber side.This method is"},{"type":"text","text":" "},{"type":"text","text":"applicable to all types of streams from the sender, including but not limited"},{"type":"text","text":" "},{"type":"text","text":"to video streams collected from cameras, screen sharing streams, and"},{"type":"text","text":" "},{"type":"text","text":"custom-collected video streams.If you need to enable dual video streams in a"},{"type":"text","text":" "},{"type":"text","text":"multi-channel scenario, you can call the enableDualStreamModeEx method.You"},{"type":"text","text":" "},{"type":"text","text":"can call this method either before or after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableDualStreamMode(_:streamConfig:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableDualStreamMode:streamConfig:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enabledualstreammode(_:streamconfig:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableDualStreamMode:streamConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableDualStreamMode:streamConfig:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableDualStreamMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig","text":"AgoraSimulcastStreamConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"streamConfig"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamConfig\/title","value":"AgoraSimulcastStreamConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamConfig\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableDualStreamMode(_:streamConfig:)\/title","value":"enableDualStreamMode:streamConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableDualStreamMode(_:streamConfig:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableDualStreamMode:streamConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}