{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVirtualBackground"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","preciseIdentifier":"c:objc(cs)AgoraVirtualBackgroundSource","text":"AgoraVirtualBackgroundSource"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"segData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty","preciseIdentifier":"c:objc(cs)AgoraSegmentationProperty","text":"AgoraSegmentationProperty"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable virtual background:YES: Enable virtual"},{"type":"text","text":" "},{"type":"text","text":"background.NO: Disable virtual background."}]}]},{"name":"backData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The custom background image. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVirtualBackgroundSource . To adapt the resolution of the custom"},{"type":"text","text":" "},{"type":"text","text":"background image to that of the video captured by the SDK, the SDK scales and"},{"type":"text","text":" "},{"type":"text","text":"crops the custom background image while ensuring that the content of the"},{"type":"text","text":" "},{"type":"text","text":"custom background image is not distorted."}]}]},{"name":"segData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Processing properties for background images. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraSegmentationProperty ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -1: The custom background image does not"},{"type":"text","text":" "},{"type":"text","text":"exist. Check the value of source in AgoraVirtualBackgroundSource . -2: The"},{"type":"text","text":" "},{"type":"text","text":"color format of the custom background image is invalid. Check the value of"},{"type":"text","text":" "},{"type":"text","text":"color in AgoraVirtualBackgroundSource . -3: The device does not support"},{"type":"text","text":" "},{"type":"text","text":"virtual background."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablevirtualbackground(_:backdata:segdata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablevirtualbackground(_:backdata:segdata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVirtualBackground(_:backData:segData:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables\/Disables the virtual background."},{"type":"text","text":" "},{"type":"text","text":"The virtual background function allows you to replace the original background"},{"type":"text","text":" "},{"type":"text","text":"image of the local user or to blur the background. After successfully"},{"type":"text","text":" "},{"type":"text","text":"enabling the virtual background function, all users in the channel can see"},{"type":"text","text":" "},{"type":"text","text":"the customized background.Call this method before calling enableVideo or"},{"type":"text","text":" "},{"type":"text","text":"startPreview .This feature requires high performance devices. Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends that you implement it on devices equipped with the following"},{"type":"text","text":" "},{"type":"text","text":"chips:Devices with an A9 chip and better, as follows:iPhone 6S and lateriPad"},{"type":"text","text":" "},{"type":"text","text":"Air 3rd generation and lateriPad 5th generation and lateriPad Pro 1st"},{"type":"text","text":" "},{"type":"text","text":"generation and lateriPad mini 5th generation and laterAgora recommends that"},{"type":"text","text":" "},{"type":"text","text":"you use this feature in scenarios that meet the following conditions:A"},{"type":"text","text":" "},{"type":"text","text":"high-definition camera device is used, and the environment is uniformly"},{"type":"text","text":" "},{"type":"text","text":"lit.There are few objects in the captured video. Portraits are half-length"},{"type":"text","text":" "},{"type":"text","text":"and unobstructed. Ensure that the background is a solid color that is"},{"type":"text","text":" "},{"type":"text","text":"different from the color of the user’s clothing.This method relies on the"},{"type":"text","text":" "},{"type":"text","text":"virtual background dynamic library"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoSegmentationExtension.xcframework. If the dynamic library is"},{"type":"text","text":" "},{"type":"text","text":"deleted, the function cannot be enabled normally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVirtualBackground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVirtualBackgroundSource","preciseIdentifier":"c:objc(cs)AgoraVirtualBackgroundSource"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"segData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSegmentationProperty","preciseIdentifier":"c:objc(cs)AgoraSegmentationProperty"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enableVirtualBackground(_:backData:segData:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableVirtualBackground:backData:segData:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableVirtualBackground:backData:segData:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableVirtualBackground(_:backData:segData:)":{"role":"symbol","title":"enableVirtualBackground(_:backData:segData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVirtualBackground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVirtualBackgroundSource","preciseIdentifier":"c:objc(cs)AgoraVirtualBackgroundSource"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"segData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSegmentationProperty","preciseIdentifier":"c:objc(cs)AgoraSegmentationProperty"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables\/Disables the virtual background."},{"type":"text","text":" "},{"type":"text","text":"The virtual background function allows you to replace the original background"},{"type":"text","text":" "},{"type":"text","text":"image of the local user or to blur the background. After successfully"},{"type":"text","text":" "},{"type":"text","text":"enabling the virtual background function, all users in the channel can see"},{"type":"text","text":" "},{"type":"text","text":"the customized background.Call this method before calling enableVideo or"},{"type":"text","text":" "},{"type":"text","text":"startPreview .This feature requires high performance devices. Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends that you implement it on devices equipped with the following"},{"type":"text","text":" "},{"type":"text","text":"chips:Devices with an A9 chip and better, as follows:iPhone 6S and lateriPad"},{"type":"text","text":" "},{"type":"text","text":"Air 3rd generation and lateriPad 5th generation and lateriPad Pro 1st"},{"type":"text","text":" "},{"type":"text","text":"generation and lateriPad mini 5th generation and laterAgora recommends that"},{"type":"text","text":" "},{"type":"text","text":"you use this feature in scenarios that meet the following conditions:A"},{"type":"text","text":" "},{"type":"text","text":"high-definition camera device is used, and the environment is uniformly"},{"type":"text","text":" "},{"type":"text","text":"lit.There are few objects in the captured video. Portraits are half-length"},{"type":"text","text":" "},{"type":"text","text":"and unobstructed. Ensure that the background is a solid color that is"},{"type":"text","text":" "},{"type":"text","text":"different from the color of the user’s clothing.This method relies on the"},{"type":"text","text":" "},{"type":"text","text":"virtual background dynamic library"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoSegmentationExtension.xcframework. If the dynamic library is"},{"type":"text","text":" "},{"type":"text","text":"deleted, the function cannot be enabled normally."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVirtualBackground(_:backData:segData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableVirtualBackground:backData:segData:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablevirtualbackground(_:backdata:segdata:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource":{"role":"symbol","title":"AgoraVirtualBackgroundSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"abstract":[{"type":"text","text":"The custom background image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSegmentationProperty":{"role":"symbol","title":"AgoraSegmentationProperty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSegmentationProperty"}],"abstract":[{"type":"text","text":"Processing properties for background images."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSegmentationProperty"}],"url":"\/documentation\/agorartckit\/agorasegmentationproperty"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableVirtualBackground:backData:segData:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVirtualBackground:backData:segData:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableVirtualBackground:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":" "},{"kind":"identifier","text":"backData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","preciseIdentifier":"c:objc(cs)AgoraVirtualBackgroundSource","text":"AgoraVirtualBackgroundSource"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backData"},{"kind":"text","text":" "},{"kind":"identifier","text":"segData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty","preciseIdentifier":"c:objc(cs)AgoraSegmentationProperty","text":"AgoraSegmentationProperty"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"segData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVirtualBackground(_:backData:segData:)\/title","value":"enableVirtualBackground:backData:segData:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVirtualBackground(_:backData:segData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVirtualBackground:backData:segData:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/title","value":"AgoraVirtualBackgroundSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty\/title","value":"AgoraSegmentationProperty"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty\/fragments","value":[{"kind":"identifier","text":"AgoraSegmentationProperty"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}