{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDualStreamModeEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig","text":"AgoraSimulcastStreamConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable dual-stream mode:YES: Enable"},{"type":"text","text":" "},{"type":"text","text":"dual-stream mode.NO: (Default) Disable dual-stream mode."}]}]},{"name":"streamConfig","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the low-quality video stream."},{"type":"text","text":" "},{"type":"text","text":"See AgoraSimulcastStreamConfig ."}]}]},{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enabledualstreammodeex(_:streamconfig:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enabledualstreammodeex(_:streamconfig:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableDualStreamModeEx(_:streamConfig:connection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables or disables dual-stream mode on the sender side."},{"type":"text","text":" "},{"type":"text","text":"After you enable dual-stream mode, you can call setRemoteVideoStream to"},{"type":"text","text":" "},{"type":"text","text":"choose to receive either the high-quality video stream or the low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream on the subscriber side.You can call this method to enable or"},{"type":"text","text":" "},{"type":"text","text":"disable the dual-stream mode on the publisher side. Dual streams are a"},{"type":"text","text":" "},{"type":"text","text":"pairing of a high-quality video stream and a low-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream:High-quality video stream: High bitrate, high resolution.Low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream: Low bitrate, low resolution.Sincev4.0.1This method is"},{"type":"text","text":" "},{"type":"text","text":"applicable to all types of streams from the sender, including but not limited"},{"type":"text","text":" "},{"type":"text","text":"to video streams collected from cameras, screen sharing streams, and"},{"type":"text","text":" "},{"type":"text","text":"custom-collected video streams."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"enableDualStreamModeEx:streamConfig:connection:"}],"role":"symbol","title":"enableDualStreamModeEx(_:streamConfig:connection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDualStreamModeEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableDualStreamModeEx:streamConfig:connection:","extendedModule":"AgoraRtcKit","modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamConfig":{"role":"symbol","title":"AgoraSimulcastStreamConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}],"abstract":[{"type":"text","text":"The configuration of the low-quality video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreamconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableDualStreamModeEx(_:streamConfig:connection:)":{"role":"symbol","title":"enableDualStreamModeEx(_:streamConfig:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDualStreamModeEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables or disables dual-stream mode on the sender side."},{"type":"text","text":" "},{"type":"text","text":"After you enable dual-stream mode, you can call setRemoteVideoStream to"},{"type":"text","text":" "},{"type":"text","text":"choose to receive either the high-quality video stream or the low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream on the subscriber side.You can call this method to enable or"},{"type":"text","text":" "},{"type":"text","text":"disable the dual-stream mode on the publisher side. Dual streams are a"},{"type":"text","text":" "},{"type":"text","text":"pairing of a high-quality video stream and a low-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream:High-quality video stream: High bitrate, high resolution.Low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream: Low bitrate, low resolution.Sincev4.0.1This method is"},{"type":"text","text":" "},{"type":"text","text":"applicable to all types of streams from the sender, including but not limited"},{"type":"text","text":" "},{"type":"text","text":"to video streams collected from cameras, screen sharing streams, and"},{"type":"text","text":" "},{"type":"text","text":"custom-collected video streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableDualStreamModeEx(_:streamConfig:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableDualStreamModeEx:streamConfig:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enabledualstreammodeex(_:streamconfig:connection:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableDualStreamModeEx:streamConfig:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableDualStreamModeEx:streamConfig:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableDualStreamModeEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig","text":"AgoraSimulcastStreamConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"streamConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamConfig\/title","value":"AgoraSimulcastStreamConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamConfig\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableDualStreamModeEx(_:streamConfig:connection:)\/title","value":"enableDualStreamModeEx:streamConfig:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableDualStreamModeEx(_:streamConfig:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableDualStreamModeEx:streamConfig:connection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}