{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideoImageSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraImageTrackOptions","preciseIdentifier":"c:objc(cs)AgoraImageTrackOptions","text":"AgoraImageTrackOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to replace the current video feeds with custom"},{"type":"text","text":" "},{"type":"text","text":"images:YES: Replace the current video feeds with custom images.NO: (Default)"},{"type":"text","text":" "},{"type":"text","text":"Do not replace the current video feeds with custom images."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Image configurations. See AgoraImageTrackOptions ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablevideoimagesource(_:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablevideoimagesource(_:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideoImageSource(_:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets whether to replace the current video feeds with images when publishing"},{"type":"text","text":" "},{"type":"text","text":"video streams. Agora recommends that you call this method after joining a"},{"type":"text","text":" "},{"type":"text","text":"channel.When publishing video streams, you can call this method to replace"},{"type":"text","text":" "},{"type":"text","text":"the current video feeds with custom images.Once you enable this function, you"},{"type":"text","text":" "},{"type":"text","text":"can select images to replace the video feeds through the"},{"type":"text","text":" "},{"type":"text","text":"AgoraImageTrackOptions parameter. If you disable this function, the remote"},{"type":"text","text":" "},{"type":"text","text":"users see the video feeds that you publish."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideoImageSource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraImageTrackOptions","preciseIdentifier":"c:objc(cs)AgoraImageTrackOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enableVideoImageSource(_:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableVideoImageSource:options:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableVideoImageSource:options:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraImageTrackOptions":{"role":"symbol","title":"AgoraImageTrackOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraImageTrackOptions"}],"abstract":[{"type":"text","text":"Image configurations"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraImageTrackOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraImageTrackOptions"}],"url":"\/documentation\/agorartckit\/agoraimagetrackoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableVideoImageSource(_:options:)":{"role":"symbol","title":"enableVideoImageSource(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideoImageSource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraImageTrackOptions","preciseIdentifier":"c:objc(cs)AgoraImageTrackOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets whether to replace the current video feeds with images when publishing"},{"type":"text","text":" "},{"type":"text","text":"video streams. Agora recommends that you call this method after joining a"},{"type":"text","text":" "},{"type":"text","text":"channel.When publishing video streams, you can call this method to replace"},{"type":"text","text":" "},{"type":"text","text":"the current video feeds with custom images.Once you enable this function, you"},{"type":"text","text":" "},{"type":"text","text":"can select images to replace the video feeds through the"},{"type":"text","text":" "},{"type":"text","text":"AgoraImageTrackOptions parameter. If you disable this function, the remote"},{"type":"text","text":" "},{"type":"text","text":"users see the video feeds that you publish."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideoImageSource(_:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableVideoImageSource:options:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablevideoimagesource(_:options:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableVideoImageSource:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVideoImageSource:options:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableVideoImageSource:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraImageTrackOptions","preciseIdentifier":"c:objc(cs)AgoraImageTrackOptions","text":"AgoraImageTrackOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraImageTrackOptions\/title","value":"AgoraImageTrackOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraImageTrackOptions\/fragments","value":[{"kind":"identifier","text":"AgoraImageTrackOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideoImageSource(_:options:)\/title","value":"enableVideoImageSource:options:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideoImageSource(_:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVideoImageSource:options:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}