{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableMultiCamera"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration","text":"AgoraCameraCapturerConfiguration"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable multi-camera video capture mode:YES:"},{"type":"text","text":" "},{"type":"text","text":"Enable multi-camera capture mode; the SDK uses multiple cameras to capture"},{"type":"text","text":" "},{"type":"text","text":"video.NO: Disable multi-camera capture mode; the SDK uses a single camera to"},{"type":"text","text":" "},{"type":"text","text":"capture video."}]}]},{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Capture configuration for the second camera. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraCameraCapturerConfiguration ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"< 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablemulticamera(_:config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enablemulticamera(_:config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableMultiCamera(_:config:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables or disables multi-camera capture."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0In scenarios where there are existing cameras to capture video,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you use the following steps to capture and publish"},{"type":"text","text":" "},{"type":"text","text":"video with multiple cameras:Call this method to enable multi-channel camera"},{"type":"text","text":" "},{"type":"text","text":"capture.Call startPreview to start the local video preview.Call"},{"type":"text","text":" "},{"type":"text","text":"startSecondaryCameraCapture to start video capture with the second"},{"type":"text","text":" "},{"type":"text","text":"camera.Call joinChannelExByToken [1\/2] , and set publishSecondaryCameraTrack"},{"type":"text","text":" "},{"type":"text","text":"to YES to publish the video stream captured by the second camera in the"},{"type":"text","text":" "},{"type":"text","text":"channel.If you want to disable multi-channel camera capture, use the"},{"type":"text","text":" "},{"type":"text","text":"following steps:Call stopSecondaryCameraCapture .Call this method with"},{"type":"text","text":" "},{"type":"text","text":"enabled set to NO.You can call this method before and after startPreview to"},{"type":"text","text":" "},{"type":"text","text":"enable multi-camera capture:If it is enabled before startPreview, the local"},{"type":"text","text":" "},{"type":"text","text":"video preview shows the image captured by the two cameras at the same time.If"},{"type":"text","text":" "},{"type":"text","text":"it is enabled after startPreview, the SDK stops the current camera capture"},{"type":"text","text":" "},{"type":"text","text":"first, and then enables the primary camera and the second camera. The local"},{"type":"text","text":" "},{"type":"text","text":"video preview appears black for a short time, and then automatically returns"},{"type":"text","text":" "},{"type":"text","text":"to normal.When using this function, ensure that the system version is 13.0 or"},{"type":"text","text":" "},{"type":"text","text":"later.The minimum iOS device types that support multi-camera capture are as"},{"type":"text","text":" "},{"type":"text","text":"follows:iPhone XRiPhone XSiPhone XS MaxiPad Pro 3rd generation and later"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableMultiCamera"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enableMultiCamera(_:config:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableMultiCamera:config:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableMultiCamera:config:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableMultiCamera(_:config:)":{"role":"symbol","title":"enableMultiCamera(_:config:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableMultiCamera"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables or disables multi-camera capture."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0In scenarios where there are existing cameras to capture video,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you use the following steps to capture and publish"},{"type":"text","text":" "},{"type":"text","text":"video with multiple cameras:Call this method to enable multi-channel camera"},{"type":"text","text":" "},{"type":"text","text":"capture.Call startPreview to start the local video preview.Call"},{"type":"text","text":" "},{"type":"text","text":"startSecondaryCameraCapture to start video capture with the second"},{"type":"text","text":" "},{"type":"text","text":"camera.Call joinChannelExByToken [1\/2] , and set publishSecondaryCameraTrack"},{"type":"text","text":" "},{"type":"text","text":"to YES to publish the video stream captured by the second camera in the"},{"type":"text","text":" "},{"type":"text","text":"channel.If you want to disable multi-channel camera capture, use the"},{"type":"text","text":" "},{"type":"text","text":"following steps:Call stopSecondaryCameraCapture .Call this method with"},{"type":"text","text":" "},{"type":"text","text":"enabled set to NO.You can call this method before and after startPreview to"},{"type":"text","text":" "},{"type":"text","text":"enable multi-camera capture:If it is enabled before startPreview, the local"},{"type":"text","text":" "},{"type":"text","text":"video preview shows the image captured by the two cameras at the same time.If"},{"type":"text","text":" "},{"type":"text","text":"it is enabled after startPreview, the SDK stops the current camera capture"},{"type":"text","text":" "},{"type":"text","text":"first, and then enables the primary camera and the second camera. The local"},{"type":"text","text":" "},{"type":"text","text":"video preview appears black for a short time, and then automatically returns"},{"type":"text","text":" "},{"type":"text","text":"to normal.When using this function, ensure that the system version is 13.0 or"},{"type":"text","text":" "},{"type":"text","text":"later.The minimum iOS device types that support multi-camera capture are as"},{"type":"text","text":" "},{"type":"text","text":"follows:iPhone XRiPhone XSiPhone XS MaxiPad Pro 3rd generation and later"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableMultiCamera(_:config:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableMultiCamera:config:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablemulticamera(_:config:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraCapturerConfiguration":{"role":"symbol","title":"AgoraCameraCapturerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"abstract":[{"type":"text","text":"The camera capturer preference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"url":"\/documentation\/agorartckit\/agoracameracapturerconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableMultiCamera:config:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableMultiCamera:config:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableMultiCamera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration","text":"AgoraCameraCapturerConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableMultiCamera(_:config:)\/title","value":"enableMultiCamera:config:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableMultiCamera(_:config:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableMultiCamera:config:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/title","value":"AgoraCameraCapturerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}