{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableEncryption"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encryptionConfig"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","preciseIdentifier":"c:objc(cs)AgoraEncryptionConfig","text":"AgoraEncryptionConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable built-in encryption:YES: Enable the"},{"type":"text","text":" "},{"type":"text","text":"built-in encryption.NO: Disable the built-in encryption."}]}]},{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Built-in encryption configurations. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncryptionConfig ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -2: An invalid parameter is used. Set"},{"type":"text","text":" "},{"type":"text","text":"the parameter with a valid value. -4: The built-in encryption mode is"},{"type":"text","text":" "},{"type":"text","text":"incorrect or the SDK fails to load the external encryption library. Check the"},{"type":"text","text":" "},{"type":"text","text":"enumeration or reload the external encryption library. -7: The SDK is not"},{"type":"text","text":" "},{"type":"text","text":"initialized. Initialize the AgoraRtcEngineKit instance before calling this"},{"type":"text","text":" "},{"type":"text","text":"method."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enableencryption(_:encryptionconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/enableencryption(_:encryptionconfig:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableEncryption(_:encryptionConfig:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables or disables the built-in encryption."},{"type":"text","text":" "},{"type":"text","text":"In scenarios requiring high security, Agora recommends calling this method to"},{"type":"text","text":" "},{"type":"text","text":"enable the built-in encryption before joining a channel.All users in the same"},{"type":"text","text":" "},{"type":"text","text":"channel must use the same encryption mode and encryption key. After the user"},{"type":"text","text":" "},{"type":"text","text":"leaves the channel, the SDK automatically disables the built-in encryption."},{"type":"text","text":" "},{"type":"text","text":"To enable the built-in encryption, call this method before the user joins the"},{"type":"text","text":" "},{"type":"text","text":"channel again.If you enable the built-in encryption, you cannot use the Media"},{"type":"text","text":" "},{"type":"text","text":"Push function."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableEncryption"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encryptionConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncryptionConfig","preciseIdentifier":"c:objc(cs)AgoraEncryptionConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"enableEncryption(_:encryptionConfig:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)enableEncryption:encryptionConfig:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"enableEncryption:encryptionConfig:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableEncryption(_:encryptionConfig:)":{"role":"symbol","title":"enableEncryption(_:encryptionConfig:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableEncryption"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encryptionConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncryptionConfig","preciseIdentifier":"c:objc(cs)AgoraEncryptionConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables or disables the built-in encryption."},{"type":"text","text":" "},{"type":"text","text":"In scenarios requiring high security, Agora recommends calling this method to"},{"type":"text","text":" "},{"type":"text","text":"enable the built-in encryption before joining a channel.All users in the same"},{"type":"text","text":" "},{"type":"text","text":"channel must use the same encryption mode and encryption key. After the user"},{"type":"text","text":" "},{"type":"text","text":"leaves the channel, the SDK automatically disables the built-in encryption."},{"type":"text","text":" "},{"type":"text","text":"To enable the built-in encryption, call this method before the user joins the"},{"type":"text","text":" "},{"type":"text","text":"channel again.If you enable the built-in encryption, you cannot use the Media"},{"type":"text","text":" "},{"type":"text","text":"Push function."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableEncryption(_:encryptionConfig:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableEncryption:encryptionConfig:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enableencryption(_:encryptionconfig:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig":{"role":"symbol","title":"AgoraEncryptionConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionConfig"}],"abstract":[{"type":"text","text":"Built-in encryption configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionConfig"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableEncryption:encryptionConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableEncryption:encryptionConfig:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableEncryption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","preciseIdentifier":"c:objc(cs)AgoraEncryptionConfig","text":"AgoraEncryptionConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableEncryption(_:encryptionConfig:)\/title","value":"enableEncryption:encryptionConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableEncryption(_:encryptionConfig:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableEncryption:encryptionConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/title","value":"AgoraEncryptionConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}