{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioMixingCurrentPosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"≥ 0: The current playback position (ms) of the audio mixing, if"},{"type":"text","text":" "},{"type":"text","text":"this method call succeeds. 0 represents that the current music file does not"},{"type":"text","text":" "},{"type":"text","text":"start playing. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/getaudiomixingcurrentposition()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/getaudiomixingcurrentposition()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/getAudioMixingCurrentPosition()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Retrieves the playback position (ms) of the music file."},{"type":"text","text":" "},{"type":"text","text":"Retrieves the playback position (ms) of the audio.You need to call this"},{"type":"text","text":" "},{"type":"text","text":"method after calling startAudioMixing [2\/2] and receiving the"},{"type":"text","text":" "},{"type":"text","text":"audioMixingStateChanged(AgoraAudioMixingStateTypePlaying) callback.If you"},{"type":"text","text":" "},{"type":"text","text":"need to call getAudioMixingCurrentPosition multiple times, ensure that the"},{"type":"text","text":" "},{"type":"text","text":"time interval between calling this method is more than 500 ms."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioMixingCurrentPosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"getAudioMixingCurrentPosition()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)getAudioMixingCurrentPosition","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"getAudioMixingCurrentPosition"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/getAudioMixingCurrentPosition()":{"role":"symbol","title":"getAudioMixingCurrentPosition()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioMixingCurrentPosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Retrieves the playback position (ms) of the music file."},{"type":"text","text":" "},{"type":"text","text":"Retrieves the playback position (ms) of the audio.You need to call this"},{"type":"text","text":" "},{"type":"text","text":"method after calling startAudioMixing [2\/2] and receiving the"},{"type":"text","text":" "},{"type":"text","text":"audioMixingStateChanged(AgoraAudioMixingStateTypePlaying) callback.If you"},{"type":"text","text":" "},{"type":"text","text":"need to call getAudioMixingCurrentPosition multiple times, ensure that the"},{"type":"text","text":" "},{"type":"text","text":"time interval between calling this method is more than 500 ms."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/getAudioMixingCurrentPosition()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAudioMixingCurrentPosition"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/getaudiomixingcurrentposition()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAudioMixingCurrentPosition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAudioMixingCurrentPosition"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAudioMixingCurrentPosition"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1getAudioMixingCurrentPosition()\/title","value":"getAudioMixingCurrentPosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1getAudioMixingCurrentPosition()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAudioMixingCurrentPosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}