{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCameraTorchSupported"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES : The device supports enabling the flash. NO : The device does"},{"type":"text","text":" "},{"type":"text","text":"not support enabling the flash."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/iscameratorchsupported()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/iscameratorchsupported()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/isCameraTorchSupported()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checks whether the device supports camera flash."},{"type":"text","text":" "},{"type":"text","text":"Call this method after enabling the local camera, for example, by calling"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [2\/4] , enableVideo , or enableLocalVideo ,depending on"},{"type":"text","text":" "},{"type":"text","text":"which method you use to turn on your local camera.The app enables the front"},{"type":"text","text":" "},{"type":"text","text":"camera by default. If your front camera does not support enabling the flash,"},{"type":"text","text":" "},{"type":"text","text":"this method returns NO. If you want to check whether the rear camera supports"},{"type":"text","text":" "},{"type":"text","text":"the flash function, call switchCamera before this method.On iPads with system"},{"type":"text","text":" "},{"type":"text","text":"version 15, even if isCameraTorchSupported returns YES, you might fail to"},{"type":"text","text":" "},{"type":"text","text":"successfully enable the flash by calling setCameraTorchOn due to system"},{"type":"text","text":" "},{"type":"text","text":"issues."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCameraTorchSupported"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isCameraTorchSupported()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)isCameraTorchSupported","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"isCameraTorchSupported"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/isCameraTorchSupported()":{"role":"symbol","title":"isCameraTorchSupported()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCameraTorchSupported"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks whether the device supports camera flash."},{"type":"text","text":" "},{"type":"text","text":"Call this method after enabling the local camera, for example, by calling"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [2\/4] , enableVideo , or enableLocalVideo ,depending on"},{"type":"text","text":" "},{"type":"text","text":"which method you use to turn on your local camera.The app enables the front"},{"type":"text","text":" "},{"type":"text","text":"camera by default. If your front camera does not support enabling the flash,"},{"type":"text","text":" "},{"type":"text","text":"this method returns NO. If you want to check whether the rear camera supports"},{"type":"text","text":" "},{"type":"text","text":"the flash function, call switchCamera before this method.On iPads with system"},{"type":"text","text":" "},{"type":"text","text":"version 15, even if isCameraTorchSupported returns YES, you might fail to"},{"type":"text","text":" "},{"type":"text","text":"successfully enable the flash by calling setCameraTorchOn due to system"},{"type":"text","text":" "},{"type":"text","text":"issues."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/isCameraTorchSupported()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCameraTorchSupported"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/iscameratorchsupported()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isCameraTorchSupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isCameraTorchSupported"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isCameraTorchSupported"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1isCameraTorchSupported()\/title","value":"isCameraTorchSupported"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1isCameraTorchSupported()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isCameraTorchSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}