{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions","preciseIdentifier":"c:objc(cs)AgoraLeaveChannelOptions","text":"AgoraLeaveChannelOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leaveChannelBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats","text":"AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection ."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sincev4.1.0The options for leaving the channel. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLeaveChannelOptions .This parameter only supports the"},{"type":"text","text":" "},{"type":"text","text":"stopMicrophoneRecording member in the AgoraLeaveChannelOptions settings;"},{"type":"text","text":" "},{"type":"text","text":"setting other members does not take effect."}]}]},{"name":"leaveChannelBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This callback indicates that a user leaves a"},{"type":"text","text":" "},{"type":"text","text":"channel, and provides the statistics of the call in AgoraChannelStats ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/leavechannelex(_:options:leavechannelblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/leavechannelex(_:options:leavechannelblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannelEx(_:options:leaveChannelBlock:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets channel options and leaves the channel."},{"type":"text","text":" "},{"type":"text","text":"This method lets the user leave the channel, for example, by hanging up or"},{"type":"text","text":" "},{"type":"text","text":"exiting the call.After calling joinChannelExByToken [1\/2] to join the"},{"type":"text","text":" "},{"type":"text","text":"channel, this method must be called to end the call before starting the next"},{"type":"text","text":" "},{"type":"text","text":"call.This method can be called whether or not a call is currently in"},{"type":"text","text":" "},{"type":"text","text":"progress. This method releases all resources related to the session.This"},{"type":"text","text":" "},{"type":"text","text":"method call is asynchronous. When this method returns, it does not"},{"type":"text","text":" "},{"type":"text","text":"necessarily mean that the user has left the channel. After you leave the"},{"type":"text","text":" "},{"type":"text","text":"channel, the SDK triggers the didLeaveChannelWithStats callback.After"},{"type":"text","text":" "},{"type":"text","text":"actually leaving the channel, the local user triggers the"},{"type":"text","text":" "},{"type":"text","text":"didLeaveChannelWithStats callback; after the user in the communication"},{"type":"text","text":" "},{"type":"text","text":"scenario and the host in the live streaming scenario leave the channel, the"},{"type":"text","text":" "},{"type":"text","text":"remote user triggers the didOfflineOfUid callback.If you call destroy"},{"type":"text","text":" "},{"type":"text","text":"immediately after calling this method, the SDK does not trigger the"},{"type":"text","text":" "},{"type":"text","text":"didLeaveChannelWithStats callback.Calling leaveChannel [1\/2] will leave the"},{"type":"text","text":" "},{"type":"text","text":"channels when calling joinChannelByToken [2\/4] and joinChannelExByToken [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"at the same time."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLeaveChannelOptions","preciseIdentifier":"c:objc(cs)AgoraLeaveChannelOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leaveChannelBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"leaveChannelEx(_:options:leaveChannelBlock:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)leaveChannelEx:options:leaveChannelBlock:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"leaveChannelEx:options:leaveChannelBlock:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats":{"role":"symbol","title":"AgoraChannelStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelStats"}],"abstract":[{"type":"text","text":"Statistics of the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelStats"}],"url":"\/documentation\/agorartckit\/agorachannelstats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/leaveChannelEx(_:options:leaveChannelBlock:)":{"role":"symbol","title":"leaveChannelEx(_:options:leaveChannelBlock:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLeaveChannelOptions","preciseIdentifier":"c:objc(cs)AgoraLeaveChannelOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leaveChannelBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets channel options and leaves the channel."},{"type":"text","text":" "},{"type":"text","text":"This method lets the user leave the channel, for example, by hanging up or"},{"type":"text","text":" "},{"type":"text","text":"exiting the call.After calling joinChannelExByToken [1\/2] to join the"},{"type":"text","text":" "},{"type":"text","text":"channel, this method must be called to end the call before starting the next"},{"type":"text","text":" "},{"type":"text","text":"call.This method can be called whether or not a call is currently in"},{"type":"text","text":" "},{"type":"text","text":"progress. This method releases all resources related to the session.This"},{"type":"text","text":" "},{"type":"text","text":"method call is asynchronous. When this method returns, it does not"},{"type":"text","text":" "},{"type":"text","text":"necessarily mean that the user has left the channel. After you leave the"},{"type":"text","text":" "},{"type":"text","text":"channel, the SDK triggers the didLeaveChannelWithStats callback.After"},{"type":"text","text":" "},{"type":"text","text":"actually leaving the channel, the local user triggers the"},{"type":"text","text":" "},{"type":"text","text":"didLeaveChannelWithStats callback; after the user in the communication"},{"type":"text","text":" "},{"type":"text","text":"scenario and the host in the live streaming scenario leave the channel, the"},{"type":"text","text":" "},{"type":"text","text":"remote user triggers the didOfflineOfUid callback.If you call destroy"},{"type":"text","text":" "},{"type":"text","text":"immediately after calling this method, the SDK does not trigger the"},{"type":"text","text":" "},{"type":"text","text":"didLeaveChannelWithStats callback.Calling leaveChannel [1\/2] will leave the"},{"type":"text","text":" "},{"type":"text","text":"channels when calling joinChannelByToken [2\/4] and joinChannelExByToken [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"at the same time."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannelEx(_:options:leaveChannelBlock:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leaveChannelEx:options:leaveChannelBlock:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/leavechannelex(_:options:leavechannelblock:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLeaveChannelOptions":{"role":"symbol","title":"AgoraLeaveChannelOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"abstract":[{"type":"text","text":"The options for leaving a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"url":"\/documentation\/agorartckit\/agoraleavechanneloptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"leaveChannelEx:options:leaveChannelBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChannelEx:options:leaveChannelBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"leaveChannelEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions","preciseIdentifier":"c:objc(cs)AgoraLeaveChannelOptions","text":"AgoraLeaveChannelOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(AgoraChannelStats *)","preciseIdentifier":"c:BFv(#*$objc(cs)AgoraChannelStats)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"leaveChannelBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/title","value":"AgoraChannelStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/fragments","value":[{"kind":"identifier","text":"AgoraChannelStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannelEx(_:options:leaveChannelBlock:)\/title","value":"leaveChannelEx:options:leaveChannelBlock:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannelEx(_:options:leaveChannelBlock:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChannelEx:options:leaveChannelBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions\/title","value":"AgoraLeaveChannelOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions\/fragments","value":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}