{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelBlock"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"leaveChannelBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats","text":"AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"leaveChannelBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This callback indicates that a user leaves a"},{"type":"text","text":" "},{"type":"text","text":"channel, and provides the statistics of the call in AgoraChannelStats ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -1: A general error occurs (no specified"},{"type":"text","text":" "},{"type":"text","text":"reason). -2: The parameter is invalid. -7: The SDK is not initialized."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/leavechannelblock(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/leavechannelblock(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannelBlock(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Leaves a channel."},{"type":"text","text":" "},{"type":"text","text":"This method releases all resources related to the session.This method call is"},{"type":"text","text":" "},{"type":"text","text":"asynchronous. When this method returns, it does not necessarily mean that the"},{"type":"text","text":" "},{"type":"text","text":"user has left the channel.After joining the channel, you must call this"},{"type":"text","text":" "},{"type":"text","text":"method or leaveChannel [2\/2] to end the call, otherwise, the next call cannot"},{"type":"text","text":" "},{"type":"text","text":"be started.If you successfully call this method and leave the channel, the"},{"type":"text","text":" "},{"type":"text","text":"following callbacks are triggered:The local client: didLeaveChannelWithStats"},{"type":"text","text":" "},{"type":"text","text":".The remote client: didOfflineOfUid , if the user joining the channel is in"},{"type":"text","text":" "},{"type":"text","text":"the Communication profile, or is a host in the Live-broadcasting profile.If"},{"type":"text","text":" "},{"type":"text","text":"you call destroy immediately after calling this method, the SDK does not"},{"type":"text","text":" "},{"type":"text","text":"trigger the didLeaveChannelWithStats callback.If you have called"},{"type":"text","text":" "},{"type":"text","text":"joinChannelExByToken [1\/2] to join multiple channels, calling this method"},{"type":"text","text":" "},{"type":"text","text":"will leave the channels when calling joinChannelByToken [2\/4] and"},{"type":"text","text":" "},{"type":"text","text":"joinChannelExByToken [1\/2] at the same time."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"leaveChannelBlock:"}],"role":"symbol","title":"leaveChannelBlock(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelBlock"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)leaveChannelBlock:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use delegate instead."}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats":{"role":"symbol","title":"AgoraChannelStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelStats"}],"abstract":[{"type":"text","text":"Statistics of the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelStats"}],"url":"\/documentation\/agorartckit\/agorachannelstats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/leaveChannelBlock(_:)":{"deprecated":true,"role":"symbol","title":"leaveChannelBlock(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelBlock"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Leaves a channel."},{"type":"text","text":" "},{"type":"text","text":"This method releases all resources related to the session.This method call is"},{"type":"text","text":" "},{"type":"text","text":"asynchronous. When this method returns, it does not necessarily mean that the"},{"type":"text","text":" "},{"type":"text","text":"user has left the channel.After joining the channel, you must call this"},{"type":"text","text":" "},{"type":"text","text":"method or leaveChannel [2\/2] to end the call, otherwise, the next call cannot"},{"type":"text","text":" "},{"type":"text","text":"be started.If you successfully call this method and leave the channel, the"},{"type":"text","text":" "},{"type":"text","text":"following callbacks are triggered:The local client: didLeaveChannelWithStats"},{"type":"text","text":" "},{"type":"text","text":".The remote client: didOfflineOfUid , if the user joining the channel is in"},{"type":"text","text":" "},{"type":"text","text":"the Communication profile, or is a host in the Live-broadcasting profile.If"},{"type":"text","text":" "},{"type":"text","text":"you call destroy immediately after calling this method, the SDK does not"},{"type":"text","text":" "},{"type":"text","text":"trigger the didLeaveChannelWithStats callback.If you have called"},{"type":"text","text":" "},{"type":"text","text":"joinChannelExByToken [1\/2] to join multiple channels, calling this method"},{"type":"text","text":" "},{"type":"text","text":"will leave the channels when calling joinChannelByToken [2\/4] and"},{"type":"text","text":" "},{"type":"text","text":"joinChannelExByToken [1\/2] at the same time."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannelBlock(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leaveChannelBlock:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/leavechannelblock(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"leaveChannelBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChannelBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"leaveChannelBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(AgoraChannelStats *)","preciseIdentifier":"c:BFv(#*$objc(cs)AgoraChannelStats)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"leaveChannelBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/title","value":"AgoraChannelStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/fragments","value":[{"kind":"identifier","text":"AgoraChannelStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannelBlock(_:)\/title","value":"leaveChannelBlock:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannelBlock(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChannelBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}