{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playEffect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"soundId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loopCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"startPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"soundId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio effect ID. The ID of each audio effect file is"},{"type":"text","text":" "},{"type":"text","text":"unique.If you have preloaded an audio effect into memory by calling"},{"type":"text","text":" "},{"type":"text","text":"preloadEffect , ensure that the value of this parameter is the same as that"},{"type":"text","text":" "},{"type":"text","text":"of soundId in preloadEffect."}]}]},{"name":"filePath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The absolute path or URL address (including the"},{"type":"text","text":" "},{"type":"text","text":"suffixes of the filename) of the audio effect file. For example,"},{"type":"text","text":" "},{"type":"text","text":"\/var\/mobile\/Containers\/Data\/audio.mp4. Supported audio formats include MP3,"},{"type":"text","text":" "},{"type":"text","text":"AAC, M4A, MP4, WAV, and 3GP. See supported audio formats.If you have"},{"type":"text","text":" "},{"type":"text","text":"preloaded an audio effect into memory by calling preloadEffect , ensure that"},{"type":"text","text":" "},{"type":"text","text":"the value of this parameter is the same as that of filePath in preloadEffect."}]}]},{"name":"loopCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of times the audio effect loops.≥ 0: The"},{"type":"text","text":" "},{"type":"text","text":"number of playback times. For example, 1 means looping one time, which means"},{"type":"text","text":" "},{"type":"text","text":"playing the audio effect two times in total.-1: Play the audio file in an"},{"type":"text","text":" "},{"type":"text","text":"infinite loop."}]}]},{"name":"pitch","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The pitch of the audio effect. The value range is 0.5"},{"type":"text","text":" "},{"type":"text","text":"to 2.0. The default value is 1.0, which means the original pitch. The lower"},{"type":"text","text":" "},{"type":"text","text":"the value, the lower the pitch."}]}]},{"name":"pan","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The spatial position of the audio effect. The value ranges"},{"type":"text","text":" "},{"type":"text","text":"between -1.0 and 1.0:-1.0: The audio effect is heard on the left of the"},{"type":"text","text":" "},{"type":"text","text":"user.0.0: The audio effect is heard in front of the user.1.0: The audio"},{"type":"text","text":" "},{"type":"text","text":"effect is heard on the right of the user."}]}]},{"name":"gain","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The volume of the audio effect. The value range is 0.0 to"},{"type":"text","text":" "},{"type":"text","text":"100.0. The default value is 100.0, which means the original volume. The"},{"type":"text","text":" "},{"type":"text","text":"smaller the value, the lower the volume."}]}]},{"name":"publish","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to publish the audio effect to the remote"},{"type":"text","text":" "},{"type":"text","text":"users:YES: Publish the audio effect to the remote users. Both the local user"},{"type":"text","text":" "},{"type":"text","text":"and remote users can hear the audio effect.NO: Do not publish the audio"},{"type":"text","text":" "},{"type":"text","text":"effect to the remote users. Only the local user can hear the audio effect."}]}]},{"name":"startPos","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The playback position (ms) of the audio effect file."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/playeffect(_:filepath:loopcount:pitch:pan:gain:publish:startpos:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/playeffect(_:filepath:loopcount:pitch:pan:gain:publish:startpos:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/playEffect(_:filePath:loopCount:pitch:pan:gain:publish:startPos:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Plays the specified local or online audio effect file."},{"type":"text","text":" "},{"type":"text","text":"If you use this method to play an online audio effect file, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"that you cache the online audio effect file to your local device, call"},{"type":"text","text":" "},{"type":"text","text":"preloadEffect to preload the cached audio effect file into memory, and then"},{"type":"text","text":" "},{"type":"text","text":"call this method to play the audio effect. Otherwise, you might encounter"},{"type":"text","text":" "},{"type":"text","text":"playback failures or no sound during playback due to loading timeouts or"},{"type":"text","text":" "},{"type":"text","text":"failures.To play multiple audio effect files at the same time, call this"},{"type":"text","text":" "},{"type":"text","text":"method multiple times with different soundId and filePath. To achieve the"},{"type":"text","text":" "},{"type":"text","text":"optimal user experience, Agora recommends that do not playing more than three"},{"type":"text","text":" "},{"type":"text","text":"audio files at the same time. After the playback of an audio effect file"},{"type":"text","text":" "},{"type":"text","text":"completes, the SDK triggers the rtcEngineDidAudioEffectFinish callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playEffect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loopCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"startPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"playEffect(_:filePath:loopCount:pitch:pan:gain:publish:startPos:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)playEffect:filePath:loopCount:pitch:pan:gain:publish:startPos:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"playEffect:filePath:loopCount:pitch:pan:gain:publish:startPos:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/playEffect(_:filePath:loopCount:pitch:pan:gain:publish:startPos:)":{"role":"symbol","title":"playEffect(_:filePath:loopCount:pitch:pan:gain:publish:startPos:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playEffect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loopCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"startPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Plays the specified local or online audio effect file."},{"type":"text","text":" "},{"type":"text","text":"If you use this method to play an online audio effect file, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"that you cache the online audio effect file to your local device, call"},{"type":"text","text":" "},{"type":"text","text":"preloadEffect to preload the cached audio effect file into memory, and then"},{"type":"text","text":" "},{"type":"text","text":"call this method to play the audio effect. Otherwise, you might encounter"},{"type":"text","text":" "},{"type":"text","text":"playback failures or no sound during playback due to loading timeouts or"},{"type":"text","text":" "},{"type":"text","text":"failures.To play multiple audio effect files at the same time, call this"},{"type":"text","text":" "},{"type":"text","text":"method multiple times with different soundId and filePath. To achieve the"},{"type":"text","text":" "},{"type":"text","text":"optimal user experience, Agora recommends that do not playing more than three"},{"type":"text","text":" "},{"type":"text","text":"audio files at the same time. After the playback of an audio effect file"},{"type":"text","text":" "},{"type":"text","text":"completes, the SDK triggers the rtcEngineDidAudioEffectFinish callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/playEffect(_:filePath:loopCount:pitch:pan:gain:publish:startPos:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playEffect:filePath:loopCount:pitch:pan:gain:publish:startPos:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/playeffect(_:filepath:loopcount:pitch:pan:gain:publish:startpos:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playEffect:filePath:loopCount:pitch:pan:gain:publish:startPos:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playEffect:filePath:loopCount:pitch:pan:gain:publish:startPos:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"playEffect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"soundId"},{"kind":"text","text":" "},{"kind":"identifier","text":"filePath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"filePath"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"loopCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pitch"},{"kind":"text","text":" "},{"kind":"identifier","text":"pan:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pan"},{"kind":"text","text":" "},{"kind":"identifier","text":"gain:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gain"},{"kind":"text","text":" "},{"kind":"identifier","text":"publish:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"publish"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPos:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"startPos"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1playEffect(_:filePath:loopCount:pitch:pan:gain:publish:startPos:)\/title","value":"playEffect:filePath:loopCount:pitch:pan:gain:publish:startPos:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1playEffect(_:filePath:loopCount:pitch:pan:gain:publish:startPos:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playEffect:filePath:loopCount:pitch:pan:gain:publish:startPos:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}