{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferBy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengthInByte"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":">?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"lengthInByte","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The data length (byte). The value of this parameter"},{"type":"text","text":" "},{"type":"text","text":"is related to the audio duration, and the values of the sampleRate and"},{"type":"text","text":" "},{"type":"text","text":"channels parameters that you set in enableExternalAudioSink. lengthInByte ="},{"type":"text","text":" "},{"type":"text","text":"sampleRate\/1000 × 2 × channels × audio duration (ms)."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES : Success. NO : Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/pullplaybackaudioframesamplebufferby(lengthinbyte:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/pullplaybackaudioframesamplebufferby(lengthinbyte:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/pullPlaybackAudioFrameSampleBufferBy(lengthInByte:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Pulls remote audio data in the SampleBuffer format."},{"type":"text","text":" "},{"type":"text","text":"Before calling this method, you need to call enableExternalAudioSink to"},{"type":"text","text":" "},{"type":"text","text":"notify the app to enable and set the external rendering.After a successful"},{"type":"text","text":" "},{"type":"text","text":"method call, the app pulls the decoded and mixed audio data for playback.This"},{"type":"text","text":" "},{"type":"text","text":"method only supports pulling data from custom audio source. If you need to"},{"type":"text","text":" "},{"type":"text","text":"pull the data captured by the SDK, do not call this method.Call this method"},{"type":"text","text":" "},{"type":"text","text":"after joining a channel.Once you enable the external audio sink, the app will"},{"type":"text","text":" "},{"type":"text","text":"not retrieve any audio data from the onPlaybackAudioFrame callback.The"},{"type":"text","text":" "},{"type":"text","text":"difference between this method and the onPlaybackAudioFrame callback is as"},{"type":"text","text":" "},{"type":"text","text":"follows:The SDK sends the audio data to the app through the"},{"type":"text","text":" "},{"type":"text","text":"onPlaybackAudioFrame callback. Any delay in processing the audio frames may"},{"type":"text","text":" "},{"type":"text","text":"result in audio jitter.After a successful method call, the app automatically"},{"type":"text","text":" "},{"type":"text","text":"pulls the audio data from the SDK. After setting the audio data parameters,"},{"type":"text","text":" "},{"type":"text","text":"the SDK adjusts the frame buffer and avoids problems caused by jitter in the"},{"type":"text","text":" "},{"type":"text","text":"external audio playback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferBy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengthInByte"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":">?"}],"title":"pullPlaybackAudioFrameSampleBufferBy(lengthInByte:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)pullPlaybackAudioFrameSampleBufferByLengthInByte:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferByLengthInByte:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/pullPlaybackAudioFrameSampleBufferBy(lengthInByte:)":{"role":"symbol","title":"pullPlaybackAudioFrameSampleBufferBy(lengthInByte:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferBy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lengthInByte"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":">?"}],"abstract":[{"type":"text","text":"Pulls remote audio data in the SampleBuffer format."},{"type":"text","text":" "},{"type":"text","text":"Before calling this method, you need to call enableExternalAudioSink to"},{"type":"text","text":" "},{"type":"text","text":"notify the app to enable and set the external rendering.After a successful"},{"type":"text","text":" "},{"type":"text","text":"method call, the app pulls the decoded and mixed audio data for playback.This"},{"type":"text","text":" "},{"type":"text","text":"method only supports pulling data from custom audio source. If you need to"},{"type":"text","text":" "},{"type":"text","text":"pull the data captured by the SDK, do not call this method.Call this method"},{"type":"text","text":" "},{"type":"text","text":"after joining a channel.Once you enable the external audio sink, the app will"},{"type":"text","text":" "},{"type":"text","text":"not retrieve any audio data from the onPlaybackAudioFrame callback.The"},{"type":"text","text":" "},{"type":"text","text":"difference between this method and the onPlaybackAudioFrame callback is as"},{"type":"text","text":" "},{"type":"text","text":"follows:The SDK sends the audio data to the app through the"},{"type":"text","text":" "},{"type":"text","text":"onPlaybackAudioFrame callback. Any delay in processing the audio frames may"},{"type":"text","text":" "},{"type":"text","text":"result in audio jitter.After a successful method call, the app automatically"},{"type":"text","text":" "},{"type":"text","text":"pulls the audio data from the SDK. After setting the audio data parameters,"},{"type":"text","text":" "},{"type":"text","text":"the SDK adjusts the frame buffer and avoids problems caused by jitter in the"},{"type":"text","text":" "},{"type":"text","text":"external audio playback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/pullPlaybackAudioFrameSampleBufferBy(lengthInByte:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferByLengthInByte:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/pullplaybackaudioframesamplebufferby(lengthinbyte:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pullPlaybackAudioFrameSampleBufferByLengthInByte:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferByLengthInByte:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferByLengthInByte:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"lengthInByte"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1pullPlaybackAudioFrameSampleBufferBy(lengthInByte:)\/title","value":"pullPlaybackAudioFrameSampleBufferByLengthInByte:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1pullPlaybackAudioFrameSampleBufferBy(lengthInByte:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pullPlaybackAudioFrameSampleBufferByLengthInByte:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}