{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushExternalVideoFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame","preciseIdentifier":"c:objc(cs)AgoraVideoFrame","text":"AgoraVideoFrame"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The raw audio data. See AgoraAudioFrame ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Reserved for future use."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/pushexternalvideoframe(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/pushexternalvideoframe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/pushExternalVideoFrame(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the captured audio frame."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the format of the cpatured audio frame is as expected, you can"},{"type":"text","text":" "},{"type":"text","text":"choose one of the following two methods to set the audio data format:Method"},{"type":"text","text":" "},{"type":"text","text":"1: After calling setRecordingAudioFrameParametersWithSampleRate to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format and setAudioFrameDelegate to register the audio frame"},{"type":"text","text":" "},{"type":"text","text":"observer object, the SDK calculates the sampling interval according to the"},{"type":"text","text":" "},{"type":"text","text":"parameters set in the methods, and triggers the onRecordAudioFrame callback"},{"type":"text","text":" "},{"type":"text","text":"according to the sampling interval.Method 2: After calling"},{"type":"text","text":" "},{"type":"text","text":"setAudioFrameDelegate to register the audio frame observer object, set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format in the return value of the getObservedAudioFramePosition"},{"type":"text","text":" "},{"type":"text","text":"callback. The SDK then calculates the sampling interval according to the"},{"type":"text","text":" "},{"type":"text","text":"return value of the getRecordAudioParams callback, and triggers the"},{"type":"text","text":" "},{"type":"text","text":"onRecordAudioFrame callback according to the sampling interval.The priority"},{"type":"text","text":" "},{"type":"text","text":"of method 1 is higher than that of method 2. If method 1 is used to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format, the setting of method 2 is invalid."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushExternalVideoFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoFrame","preciseIdentifier":"c:objc(cs)AgoraVideoFrame"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"pushExternalVideoFrame(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)pushExternalVideoFrame:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"pushExternalVideoFrame:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/pushExternalVideoFrame(_:)":{"role":"symbol","title":"pushExternalVideoFrame(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushExternalVideoFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoFrame","preciseIdentifier":"c:objc(cs)AgoraVideoFrame"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the captured audio frame."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the format of the cpatured audio frame is as expected, you can"},{"type":"text","text":" "},{"type":"text","text":"choose one of the following two methods to set the audio data format:Method"},{"type":"text","text":" "},{"type":"text","text":"1: After calling setRecordingAudioFrameParametersWithSampleRate to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format and setAudioFrameDelegate to register the audio frame"},{"type":"text","text":" "},{"type":"text","text":"observer object, the SDK calculates the sampling interval according to the"},{"type":"text","text":" "},{"type":"text","text":"parameters set in the methods, and triggers the onRecordAudioFrame callback"},{"type":"text","text":" "},{"type":"text","text":"according to the sampling interval.Method 2: After calling"},{"type":"text","text":" "},{"type":"text","text":"setAudioFrameDelegate to register the audio frame observer object, set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format in the return value of the getObservedAudioFramePosition"},{"type":"text","text":" "},{"type":"text","text":"callback. The SDK then calculates the sampling interval according to the"},{"type":"text","text":" "},{"type":"text","text":"return value of the getRecordAudioParams callback, and triggers the"},{"type":"text","text":" "},{"type":"text","text":"onRecordAudioFrame callback according to the sampling interval.The priority"},{"type":"text","text":" "},{"type":"text","text":"of method 1 is higher than that of method 2. If method 1 is used to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format, the setting of method 2 is invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/pushExternalVideoFrame(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushExternalVideoFrame:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/pushexternalvideoframe(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame":{"role":"symbol","title":"AgoraVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrame"}],"abstract":[{"type":"text","text":"The external video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrame"}],"url":"\/documentation\/agorartckit\/agoravideoframe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pushExternalVideoFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushExternalVideoFrame:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"pushExternalVideoFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame","preciseIdentifier":"c:objc(cs)AgoraVideoFrame","text":"AgoraVideoFrame"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1pushExternalVideoFrame(_:)\/title","value":"pushExternalVideoFrame:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1pushExternalVideoFrame(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushExternalVideoFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/title","value":"AgoraVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrame"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}