{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryScreenCaptureCapability"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability","preciseIdentifier":"c:@E@AgoraScreenCaptureFrameRateCapability","text":"AgoraScreenCaptureFrameRateCapability"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since v4.2.0"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/queryscreencapturecapability()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/queryscreencapturecapability()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/queryScreenCaptureCapability()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Queries the highest frame rate supported by the device during screen sharing."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryScreenCaptureCapability"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraScreenCaptureFrameRateCapability","preciseIdentifier":"c:@E@AgoraScreenCaptureFrameRateCapability"}],"title":"queryScreenCaptureCapability()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)queryScreenCaptureCapability","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"queryScreenCaptureCapability"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureFrameRateCapability":{"role":"symbol","title":"AgoraScreenCaptureFrameRateCapability","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}],"abstract":[{"type":"text","text":"The highest frame rate supported by the screen sharing device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}],"url":"\/documentation\/agorartckit\/agorascreencaptureframeratecapability"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/queryScreenCaptureCapability()":{"role":"symbol","title":"queryScreenCaptureCapability()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryScreenCaptureCapability"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraScreenCaptureFrameRateCapability","preciseIdentifier":"c:@E@AgoraScreenCaptureFrameRateCapability"}],"abstract":[{"type":"text","text":"Queries the highest frame rate supported by the device during screen sharing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/queryScreenCaptureCapability()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"queryScreenCaptureCapability"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/queryscreencapturecapability()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"queryScreenCaptureCapability"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryScreenCaptureCapability"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability","preciseIdentifier":"c:@E@AgoraScreenCaptureFrameRateCapability","text":"AgoraScreenCaptureFrameRateCapability"},{"kind":"text","text":") "},{"kind":"identifier","text":"queryScreenCaptureCapability"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability\/title","value":"AgoraScreenCaptureFrameRateCapability"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1queryScreenCaptureCapability()\/title","value":"queryScreenCaptureCapability"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1queryScreenCaptureCapability()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryScreenCaptureCapability"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}