{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerAudioSpectrumDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioSpectrumDelegate","text":"AgoraAudioSpectrumDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio spectrum observer. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioSpectrumDelegate ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/registeraudiospectrumdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/registeraudiospectrumdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/registerAudioSpectrumDelegate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Register an audio spectrum observer."},{"type":"text","text":" "},{"type":"text","text":"After successfully registering the audio spectrum observer and calling"},{"type":"text","text":" "},{"type":"text","text":"enableAudioSpectrumMonitor to enable the audio spectrum monitoring, the SDK"},{"type":"text","text":" "},{"type":"text","text":"reports the callback that you implement in the AgoraAudioSpectrumDelegate"},{"type":"text","text":" "},{"type":"text","text":"class according to the time interval you set.You can call this method either"},{"type":"text","text":" "},{"type":"text","text":"before or after joining a channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerAudioSpectrumDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioSpectrumDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioSpectrumDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"registerAudioSpectrumDelegate(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)registerAudioSpectrumDelegate:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerAudioSpectrumDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/registerAudioSpectrumDelegate(_:)":{"role":"symbol","title":"registerAudioSpectrumDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerAudioSpectrumDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioSpectrumDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioSpectrumDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Register an audio spectrum observer."},{"type":"text","text":" "},{"type":"text","text":"After successfully registering the audio spectrum observer and calling"},{"type":"text","text":" "},{"type":"text","text":"enableAudioSpectrumMonitor to enable the audio spectrum monitoring, the SDK"},{"type":"text","text":" "},{"type":"text","text":"reports the callback that you implement in the AgoraAudioSpectrumDelegate"},{"type":"text","text":" "},{"type":"text","text":"class according to the time interval you set.You can call this method either"},{"type":"text","text":" "},{"type":"text","text":"before or after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/registerAudioSpectrumDelegate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerAudioSpectrumDelegate:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/registeraudiospectrumdelegate(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumDelegate":{"role":"symbol","title":"AgoraAudioSpectrumDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}],"abstract":[{"type":"text","text":"The audio spectrum observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudiospectrumdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerAudioSpectrumDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerAudioSpectrumDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerAudioSpectrumDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraAudioSpectrumDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraAudioSpectrumDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1registerAudioSpectrumDelegate(_:)\/title","value":"registerAudioSpectrumDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1registerAudioSpectrumDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerAudioSpectrumDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate\/title","value":"AgoraAudioSpectrumDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}