{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerLocalUserAccount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"userAccount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user account. This parameter is used to identify"},{"type":"text","text":" "},{"type":"text","text":"the user in the channel for real-time audio and video engagement. You need to"},{"type":"text","text":" "},{"type":"text","text":"set and manage user accounts yourself and ensure that each user account in"},{"type":"text","text":" "},{"type":"text","text":"the same channel is unique. The maximum length of this parameter is 255"},{"type":"text","text":" "},{"type":"text","text":"bytes. Ensure that you set this parameter and do not set it as nil. Supported"},{"type":"text","text":" "},{"type":"text","text":"characters are as follow(89 in total):The 26 lowercase English letters: a to"},{"type":"text","text":" "},{"type":"text","text":"z.The 26 uppercase English letters: A to Z.All numeric characters: 0"},{"type":"text","text":" "},{"type":"text","text":"to 9.Space”!”, “#”, “$”, “%”, “&”, “(”, “)”, “+”, “-”, “:”, “;”, “<”, “= “,"},{"type":"text","text":" "},{"type":"text","text":"“.”, “>”, “?”, “@”, “[”, “]”, “^”, “_”, “{”, “}”, “|”, “~”, “,”"}]}]},{"name":"appID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The App ID of your project on Agora Console."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/registerlocaluseraccount(_:appid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/registerlocaluseraccount(_:appid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/registerLocalUserAccount(_:appId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Registers a user account."},{"type":"text","text":" "},{"type":"text","text":"Once registered, the user account can be used to identify the local user when"},{"type":"text","text":" "},{"type":"text","text":"the user joins the channel. After the registration is successful, the user"},{"type":"text","text":" "},{"type":"text","text":"account can identify the identity of the local user, and the user can use it"},{"type":"text","text":" "},{"type":"text","text":"to join the channel.After the user successfully registers a user account, the"},{"type":"text","text":" "},{"type":"text","text":"SDK triggers the didLocalUserRegisteredWithUserId callback on the local"},{"type":"text","text":" "},{"type":"text","text":"client, reporting the user ID and account of the local user.This method is"},{"type":"text","text":" "},{"type":"text","text":"optional. To join a channel with a user account, you can choose either of the"},{"type":"text","text":" "},{"type":"text","text":"following ways:Call registerLocalUserAccountWithAppID to create a user"},{"type":"text","text":" "},{"type":"text","text":"account, and then call joinChannelByToken [4\/4] to join the channel.Call the"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [4\/4] method to join the channel.The difference between"},{"type":"text","text":" "},{"type":"text","text":"the two ways is that the time elapsed between calling the"},{"type":"text","text":" "},{"type":"text","text":"registerLocalUserAccountWithAppID method and joining the channel is shorter"},{"type":"text","text":" "},{"type":"text","text":"than directly calling joinChannelByToken [4\/4].Ensure that you set the"},{"type":"text","text":" "},{"type":"text","text":"userAccount parameter; otherwise, this method does not take effect.Ensure"},{"type":"text","text":" "},{"type":"text","text":"that the userAccount is unique in the channel.To ensure smooth communication,"},{"type":"text","text":" "},{"type":"text","text":"use the same parameter type to identify the user. For example, if a user"},{"type":"text","text":" "},{"type":"text","text":"joins the channel with a user ID, then ensure all the other users use the"},{"type":"text","text":" "},{"type":"text","text":"user ID too. The same applies to the user account. If a user joins the"},{"type":"text","text":" "},{"type":"text","text":"channel with the Agora Web SDK, ensure that the ID of the user is set to the"},{"type":"text","text":" "},{"type":"text","text":"same parameter type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerLocalUserAccount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"registerLocalUserAccount(_:appId:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)registerLocalUserAccount:appId:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerLocalUserAccount:appId:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/registerLocalUserAccount(_:appId:)":{"role":"symbol","title":"registerLocalUserAccount(_:appId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerLocalUserAccount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Registers a user account."},{"type":"text","text":" "},{"type":"text","text":"Once registered, the user account can be used to identify the local user when"},{"type":"text","text":" "},{"type":"text","text":"the user joins the channel. After the registration is successful, the user"},{"type":"text","text":" "},{"type":"text","text":"account can identify the identity of the local user, and the user can use it"},{"type":"text","text":" "},{"type":"text","text":"to join the channel.After the user successfully registers a user account, the"},{"type":"text","text":" "},{"type":"text","text":"SDK triggers the didLocalUserRegisteredWithUserId callback on the local"},{"type":"text","text":" "},{"type":"text","text":"client, reporting the user ID and account of the local user.This method is"},{"type":"text","text":" "},{"type":"text","text":"optional. To join a channel with a user account, you can choose either of the"},{"type":"text","text":" "},{"type":"text","text":"following ways:Call registerLocalUserAccountWithAppID to create a user"},{"type":"text","text":" "},{"type":"text","text":"account, and then call joinChannelByToken [4\/4] to join the channel.Call the"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [4\/4] method to join the channel.The difference between"},{"type":"text","text":" "},{"type":"text","text":"the two ways is that the time elapsed between calling the"},{"type":"text","text":" "},{"type":"text","text":"registerLocalUserAccountWithAppID method and joining the channel is shorter"},{"type":"text","text":" "},{"type":"text","text":"than directly calling joinChannelByToken [4\/4].Ensure that you set the"},{"type":"text","text":" "},{"type":"text","text":"userAccount parameter; otherwise, this method does not take effect.Ensure"},{"type":"text","text":" "},{"type":"text","text":"that the userAccount is unique in the channel.To ensure smooth communication,"},{"type":"text","text":" "},{"type":"text","text":"use the same parameter type to identify the user. For example, if a user"},{"type":"text","text":" "},{"type":"text","text":"joins the channel with a user ID, then ensure all the other users use the"},{"type":"text","text":" "},{"type":"text","text":"user ID too. The same applies to the user account. If a user joins the"},{"type":"text","text":" "},{"type":"text","text":"channel with the Agora Web SDK, ensure that the ID of the user is set to the"},{"type":"text","text":" "},{"type":"text","text":"same parameter type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/registerLocalUserAccount(_:appId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerLocalUserAccount:appId:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/registerlocaluseraccount(_:appid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerLocalUserAccount:appId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerLocalUserAccount:appId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerLocalUserAccount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userAccount"},{"kind":"text","text":" "},{"kind":"identifier","text":"appId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"appId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1registerLocalUserAccount(_:appId:)\/title","value":"registerLocalUserAccount:appId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1registerLocalUserAccount(_:appId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerLocalUserAccount:appId:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}