{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioSessionOperationRestriction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"restriction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction","text":"AgoraAudioSessionOperationRestriction"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"restriction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The operational permission of the SDK on the audio"},{"type":"text","text":" "},{"type":"text","text":"session. See AgoraAudioSessionOperationRestriction . This parameter is in bit"},{"type":"text","text":" "},{"type":"text","text":"mask format, and each bit corresponds to a permission."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"< 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setaudiosessionoperationrestriction(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setaudiosessionoperationrestriction(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioSessionOperationRestriction(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the operational permission of the SDK on the audio session."},{"type":"text","text":" "},{"type":"text","text":"The SDK and the app can both configure the audio session by default. If you"},{"type":"text","text":" "},{"type":"text","text":"need to only use the app to configure the audio session, this method"},{"type":"text","text":" "},{"type":"text","text":"restricts the operational permission of the SDK on the audio session.You can"},{"type":"text","text":" "},{"type":"text","text":"call this method either before or after joining a channel. Once you call this"},{"type":"text","text":" "},{"type":"text","text":"method to restrict the operational permission of the SDK on the audio"},{"type":"text","text":" "},{"type":"text","text":"session, the restriction takes effect when the SDK needs to change the audio"},{"type":"text","text":" "},{"type":"text","text":"session.This method does not restrict the operational permission of the app"},{"type":"text","text":" "},{"type":"text","text":"on the audio session."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioSessionOperationRestriction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"},{"kind":"text","text":")"}],"title":"setAudioSessionOperationRestriction(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setAudioSessionOperationRestriction:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setAudioSessionOperationRestriction:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"seeAlsoSections":[{"title":"Audio Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalAudio(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:scenario:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioScenario(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalAudioStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteAudioStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteAudioStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustRecordingSignalVolume(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustUserPlaybackSignalVolume(_:volume:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustCustomAudioPublishVolume(_:volume:)"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioSessionOperationRestriction(_:)":{"role":"symbol","title":"setAudioSessionOperationRestriction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioSessionOperationRestriction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the operational permission of the SDK on the audio session."},{"type":"text","text":" "},{"type":"text","text":"The SDK and the app can both configure the audio session by default. If you"},{"type":"text","text":" "},{"type":"text","text":"need to only use the app to configure the audio session, this method"},{"type":"text","text":" "},{"type":"text","text":"restricts the operational permission of the SDK on the audio session.You can"},{"type":"text","text":" "},{"type":"text","text":"call this method either before or after joining a channel. Once you call this"},{"type":"text","text":" "},{"type":"text","text":"method to restrict the operational permission of the SDK on the audio"},{"type":"text","text":" "},{"type":"text","text":"session, the restriction takes effect when the SDK needs to change the audio"},{"type":"text","text":" "},{"type":"text","text":"session.This method does not restrict the operational permission of the app"},{"type":"text","text":" "},{"type":"text","text":"on the audio session."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioSessionOperationRestriction(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioSessionOperationRestriction:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudiosessionoperationrestriction(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableLocalAudio(_:)":{"role":"symbol","title":"enableLocalAudio(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLocalAudio"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables or disables the local audio capture."},{"type":"text","text":" "},{"type":"text","text":"The audio function is enabled by default when users joining a channel. This"},{"type":"text","text":" "},{"type":"text","text":"method disables or re-enables the local audio function to stop or restart"},{"type":"text","text":" "},{"type":"text","text":"local audio capturing.This method does not affect receiving or playing the"},{"type":"text","text":" "},{"type":"text","text":"remote audio streams, and enableLocalAudio (NO) is applicable to scenarios"},{"type":"text","text":" "},{"type":"text","text":"where the user wants to receive remote audio streams without sending any"},{"type":"text","text":" "},{"type":"text","text":"audio stream to other users in the channel.Once the local audio function is"},{"type":"text","text":" "},{"type":"text","text":"disabled or re-enabled, the SDK triggers the localAudioStateChanged callback,"},{"type":"text","text":" "},{"type":"text","text":"which reports AgoraAudioLocalStateStopped(0) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioLocalStateRecording(1).The difference between this method and"},{"type":"text","text":" "},{"type":"text","text":"muteLocalAudioStream are as follow:enableLocalAudio: Disables or re-enables"},{"type":"text","text":" "},{"type":"text","text":"the local audio capturing and processing. If you disable or re-enable local"},{"type":"text","text":" "},{"type":"text","text":"audio capturing using the enableLocalAudio method, the local user might hear"},{"type":"text","text":" "},{"type":"text","text":"a pause in the remote audio playback.muteLocalAudioStream: Sends or stops"},{"type":"text","text":" "},{"type":"text","text":"sending the local audio streams.You can call this method either before or"},{"type":"text","text":" "},{"type":"text","text":"after joining a channel. Calling it before joining a channel only sets the"},{"type":"text","text":" "},{"type":"text","text":"device state, and it takes effect immediately after you join the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalAudio(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableLocalAudio:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablelocalaudio(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteLocalAudioStream(_:)":{"role":"symbol","title":"muteLocalAudioStream(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteLocalAudioStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes publishing the local audio stream."},{"type":"text","text":" "},{"type":"text","text":"This method does not affect any ongoing audio recording, because it does not"},{"type":"text","text":" "},{"type":"text","text":"disable the audio capture device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalAudioStream(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteLocalAudioStream:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/mutelocalaudiostream(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteRemoteAudioStream(_:mute:)":{"role":"symbol","title":"muteRemoteAudioStream(_:mute:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteRemoteAudioStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio stream of a specified user."},{"type":"text","text":" "},{"type":"text","text":"Call this method after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteAudioStream(_:mute:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteRemoteAudioStream:mute:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteremoteaudiostream(_:mute:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteAllRemoteAudioStreams(_:)":{"role":"symbol","title":"muteAllRemoteAudioStreams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteAudioStreams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio streams of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the local user stops or resumes"},{"type":"text","text":" "},{"type":"text","text":"subscribing to the audio streams of all remote users, including all"},{"type":"text","text":" "},{"type":"text","text":"subsequent users.Call this method after joining a channel.If you do not want"},{"type":"text","text":" "},{"type":"text","text":"to subscribe the audio streams of remote users before joining a channel, you"},{"type":"text","text":" "},{"type":"text","text":"can set autoSubscribeAudio as NO when calling joinChannelByToken [2\/4] .See"},{"type":"text","text":" "},{"type":"text","text":"recommended settings in Set the Subscribing State."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteAudioStreams(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteallremoteaudiostreams(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction":{"role":"symbol","title":"AgoraAudioSessionOperationRestriction","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/disableAudio()":{"role":"symbol","title":"disableAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableAudio"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Disables the audio module."},{"type":"text","text":" "},{"type":"text","text":"This method disables the internal engine and can be called anytime after"},{"type":"text","text":" "},{"type":"text","text":"initialization. It is still valid after one leaves channel.This method resets"},{"type":"text","text":" "},{"type":"text","text":"the internal engine and takes some time to take effect. Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"using the following API methods to control the audio modules separately:"},{"type":"text","text":" "},{"type":"text","text":"enableLocalAudio : Whether to enable the microphone to create the local audio"},{"type":"text","text":" "},{"type":"text","text":"stream. muteLocalAudioStream : Whether to publish the local audio stream."},{"type":"text","text":" "},{"type":"text","text":"muteRemoteAudioStream : Whether to subscribe and play the remote audio"},{"type":"text","text":" "},{"type":"text","text":"stream. muteAllRemoteAudioStreams : Whether to subscribe to and play all"},{"type":"text","text":" "},{"type":"text","text":"remote audio streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableAudio"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/disableaudio()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioScenario(_:)":{"role":"symbol","title":"setAudioScenario(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioScenario"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioScenario","preciseIdentifier":"c:@E@AgoraAudioScenario"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets audio scenarios."},{"type":"text","text":" "},{"type":"text","text":"You can call this method either before or after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioScenario(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioScenario:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioscenario(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/adjustCustomAudioPublishVolume(_:volume:)":{"role":"symbol","title":"adjustCustomAudioPublishVolume(_:volume:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adjusts the volume of the custom external audio source when it is published"},{"type":"text","text":" "},{"type":"text","text":"in the channel. Ensure you have called the setExternalAudioSource [2\/2]"},{"type":"text","text":" "},{"type":"text","text":"method to create an external audio track before calling this method.If you"},{"type":"text","text":" "},{"type":"text","text":"want to change the volume of the audio to be published, you need to call this"},{"type":"text","text":" "},{"type":"text","text":"method again."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustCustomAudioPublishVolume(_:volume:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustCustomAudioPublishVolume:volume:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/adjustcustomaudiopublishvolume(_:volume:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/adjustUserPlaybackSignalVolume(_:volume:)":{"role":"symbol","title":"adjustUserPlaybackSignalVolume(_:volume:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustUserPlaybackSignalVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"volume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adjusts the playback signal volume of a specified remote user."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to adjust the playback volume of a specified remote"},{"type":"text","text":" "},{"type":"text","text":"user. To adjust the playback volume of different remote users, call the"},{"type":"text","text":" "},{"type":"text","text":"method as many times, once for each remote user.Call this method after"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.The playback volume here refers to the mixed volume of a"},{"type":"text","text":" "},{"type":"text","text":"specified remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustUserPlaybackSignalVolume(_:volume:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustUserPlaybackSignalVolume:volume:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/adjustuserplaybacksignalvolume(_:volume:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioProfile(_:)":{"role":"symbol","title":"setAudioProfile(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioProfile","preciseIdentifier":"c:@E@AgoraAudioProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the audio parameters and application scenarios."},{"type":"text","text":" "},{"type":"text","text":"You can call this method either before or after joining a channel.In"},{"type":"text","text":" "},{"type":"text","text":"scenarios requiring high-quality audio, such as online music tutoring, Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends you set profile asAgoraAudioProfileMusicHighQuality (4).If you"},{"type":"text","text":" "},{"type":"text","text":"want to set the audio scenario, call sharedEngineWithConfig and set"},{"type":"text","text":" "},{"type":"text","text":"audioScenario in the AgoraRtcEngineConfig struct."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioProfile:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioprofile(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableAudio()":{"role":"symbol","title":"enableAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableAudio"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the audio module."},{"type":"text","text":" "},{"type":"text","text":"The audio mode is enabled by default.This method enables the internal engine"},{"type":"text","text":" "},{"type":"text","text":"and can be called anytime after initialization. It is still valid after one"},{"type":"text","text":" "},{"type":"text","text":"leaves channel.This method enables the whole audio module and thus might take"},{"type":"text","text":" "},{"type":"text","text":"a while to take effect. Agora recommends using the following APIs to control"},{"type":"text","text":" "},{"type":"text","text":"the audio module separately: enableLocalAudio : Whether to enable the"},{"type":"text","text":" "},{"type":"text","text":"microphone to create the local audio stream. muteLocalAudioStream : Whether"},{"type":"text","text":" "},{"type":"text","text":"to publish the local audio stream. muteRemoteAudioStream : Whether to"},{"type":"text","text":" "},{"type":"text","text":"subscribe and play the remote audio stream. muteAllRemoteAudioStreams :"},{"type":"text","text":" "},{"type":"text","text":"Whether to subscribe to and play all remote audio streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableAudio()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableAudio"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enableaudio()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioProfile(_:scenario:)":{"deprecated":true,"role":"symbol","title":"setAudioProfile(_:scenario:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioProfile","preciseIdentifier":"c:@E@AgoraAudioProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scenario"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioScenario","preciseIdentifier":"c:@E@AgoraAudioScenario"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the audio profile and audio scenario."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated. If you need to set the audio profile,"},{"type":"text","text":" "},{"type":"text","text":"use setAudioProfile [2\/2] ; if you need to set the audio scenario, use"},{"type":"text","text":" "},{"type":"text","text":"setAudioScenario .You can call this method either before or after joining a"},{"type":"text","text":" "},{"type":"text","text":"channel.In scenarios requiring high-quality audio, such as online music"},{"type":"text","text":" "},{"type":"text","text":"tutoring, Agora recommends you set profile as"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQuality(4)and scenario as"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioScenarioGameStreaming(3)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:scenario:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioProfile:scenario:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioprofile(_:scenario:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/adjustRecordingSignalVolume(_:)":{"role":"symbol","title":"adjustRecordingSignalVolume(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adjustRecordingSignalVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adjusts the capturing signal volume."},{"type":"text","text":" "},{"type":"text","text":"You can call this method either before or after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustRecordingSignalVolume(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustRecordingSignalVolume:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/adjustrecordingsignalvolume(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setAudioSessionOperationRestriction:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioSessionOperationRestriction:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Audio Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableAudio()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalAudio(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioProfile(_:scenario:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioScenario(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalAudioStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteAudioStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteAudioStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustRecordingSignalVolume(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustUserPlaybackSignalVolume(_:volume:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/adjustCustomAudioPublishVolume(_:volume:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setAudioSessionOperationRestriction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction","text":"AgoraAudioSessionOperationRestriction"},{"kind":"text","text":") "},{"kind":"internalParam","text":"restriction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioSessionOperationRestriction(_:)\/title","value":"setAudioSessionOperationRestriction:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioSessionOperationRestriction(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioSessionOperationRestriction:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalAudio(_:)\/title","value":"enableLocalAudio:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalAudio(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableLocalAudio:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalAudioStream(_:)\/title","value":"muteLocalAudioStream:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalAudioStream(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteLocalAudioStream:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteAudioStream(_:mute:)\/title","value":"muteRemoteAudioStream:mute:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteAudioStream(_:mute:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteRemoteAudioStream:mute:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteAudioStreams(_:)\/title","value":"muteAllRemoteAudioStreams:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteAudioStreams(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction\/title","value":"AgoraAudioSessionOperationRestriction"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableAudio()\/title","value":"disableAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioScenario(_:)\/title","value":"setAudioScenario:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioScenario(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioScenario:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustCustomAudioPublishVolume(_:volume:)\/title","value":"adjustCustomAudioPublishVolume:volume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustCustomAudioPublishVolume(_:volume:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustCustomAudioPublishVolume:volume:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustUserPlaybackSignalVolume(_:volume:)\/title","value":"adjustUserPlaybackSignalVolume:volume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustUserPlaybackSignalVolume(_:volume:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustUserPlaybackSignalVolume:volume:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:)\/title","value":"setAudioProfile:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableAudio()\/title","value":"enableAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:scenario:)\/title","value":"setAudioProfile:scenario:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioProfile(_:scenario:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioProfile:scenario:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustRecordingSignalVolume(_:)\/title","value":"adjustRecordingSignalVolume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1adjustRecordingSignalVolume(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adjustRecordingSignalVolume:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}