{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioEncodedFrameDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioEncodedFrameDelegate","text":"AgoraAudioEncodedFrameDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig","preciseIdentifier":"c:objc(cs)AgoraAudioEncodedFrameDelegateConfig","text":"AgoraAudioEncodedFrameDelegateConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encoded audio observer. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioEncodedFrameDelegate ."}]}]},{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Observer settings for the encoded audio. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioEncodedFrameDelegateConfig ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setaudioencodedframedelegate(_:config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setaudioencodedframedelegate(_:config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioEncodedFrameDelegate(_:config:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Registers an encoded audio observer."},{"type":"text","text":" "},{"type":"text","text":"Call this method after joining a channel.You can call this method or"},{"type":"text","text":" "},{"type":"text","text":"startAudioRecording [2\/2] to set the recording type and quality of audio"},{"type":"text","text":" "},{"type":"text","text":"files, but Agora does not recommend using this method and startAudioRecording"},{"type":"text","text":" "},{"type":"text","text":"[2\/2] at the same time. Only the method called later will take effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioEncodedFrameDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioEncodedFrameDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioEncodedFrameDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioEncodedFrameDelegateConfig","preciseIdentifier":"c:objc(cs)AgoraAudioEncodedFrameDelegateConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setAudioEncodedFrameDelegate(_:config:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setAudioEncodedFrameDelegate:config:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setAudioEncodedFrameDelegate:config:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegateConfig":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegateConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"abstract":[{"type":"text","text":"Observer settings for encoded audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioEncodedFrameDelegate(_:config:)":{"role":"symbol","title":"setAudioEncodedFrameDelegate(_:config:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioEncodedFrameDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioEncodedFrameDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioEncodedFrameDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioEncodedFrameDelegateConfig","preciseIdentifier":"c:objc(cs)AgoraAudioEncodedFrameDelegateConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Registers an encoded audio observer."},{"type":"text","text":" "},{"type":"text","text":"Call this method after joining a channel.You can call this method or"},{"type":"text","text":" "},{"type":"text","text":"startAudioRecording [2\/2] to set the recording type and quality of audio"},{"type":"text","text":" "},{"type":"text","text":"files, but Agora does not recommend using this method and startAudioRecording"},{"type":"text","text":" "},{"type":"text","text":"[2\/2] at the same time. Only the method called later will take effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioEncodedFrameDelegate(_:config:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioEncodedFrameDelegate:config:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioencodedframedelegate(_:config:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegate":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}],"abstract":[{"type":"text","text":"The encoded audio observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setAudioEncodedFrameDelegate:config:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioEncodedFrameDelegate:config:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setAudioEncodedFrameDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraAudioEncodedFrameDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraAudioEncodedFrameDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig","preciseIdentifier":"c:objc(cs)AgoraAudioEncodedFrameDelegateConfig","text":"AgoraAudioEncodedFrameDelegateConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig\/title","value":"AgoraAudioEncodedFrameDelegateConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioEncodedFrameDelegate(_:config:)\/title","value":"setAudioEncodedFrameDelegate:config:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioEncodedFrameDelegate(_:config:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioEncodedFrameDelegate:config:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate\/title","value":"AgoraAudioEncodedFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}