{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioEffectParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","preciseIdentifier":"c:@E@AgoraAudioEffectPreset","text":"AgoraAudioEffectPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options for SDK preset audio"},{"type":"text","text":" "},{"type":"text","text":"effects:AgoraAudioEffectPresetRoomAcous3DVoice, 3D voice effect:Call"},{"type":"text","text":" "},{"type":"text","text":"setAudioProfile [1\/2] and set the profile parameter in to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicStandardStereo(3) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo(5) before setting this enumerator;"},{"type":"text","text":" "},{"type":"text","text":"otherwise, the enumerator setting does not take effect.If the 3D voice effect"},{"type":"text","text":" "},{"type":"text","text":"is enabled, users need to use stereo audio playback devices to hear the"},{"type":"text","text":" "},{"type":"text","text":"anticipated voice effect.AgoraAudioEffectPresetPitchCorrection, Pitch"},{"type":"text","text":" "},{"type":"text","text":"correction effect: To achieve better audio effect quality, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"setting the profile parameter in setAudioProfile [1\/2] to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQuality(4) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo(5) before setting this enumerator."}]}]},{"name":"param1","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you set preset to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioEffectPresetRoomAcous3DVoice, param1 sets the cycle period of the"},{"type":"text","text":" "},{"type":"text","text":"3D voice effect. The value range is [1,60] and the unit is seconds. The"},{"type":"text","text":" "},{"type":"text","text":"default value is 10, indicating that the voice moves around you every 10"},{"type":"text","text":" "},{"type":"text","text":"seconds.If you set preset to AgoraAudioEffectPresetPitchCorrection, param1"},{"type":"text","text":" "},{"type":"text","text":"indicates the basic mode of the pitch correction effect:1: (Default) Natural"},{"type":"text","text":" "},{"type":"text","text":"major scale.2: Natural minor scale.3: Japanese pentatonic scale."}]}]},{"name":"param2","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you set preset to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioEffectPresetRoomAcous3DVoice , you need to set param2 to 0.If you"},{"type":"text","text":" "},{"type":"text","text":"set preset to AgoraAudioEffectPresetPitchCorrection, param2 indicates the"},{"type":"text","text":" "},{"type":"text","text":"tonic pitch of the pitch correction effect:1: A2: A#3: B4: (Default) C5: C#6:"},{"type":"text","text":" "},{"type":"text","text":"D7: D#8: E9: F10: F#11: G12: G#"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setaudioeffectparameters(_:param1:param2:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setaudioeffectparameters(_:param1:param2:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioEffectParameters(_:param1:param2:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets parameters for SDK preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"Call this method to set the following parameters for the local user who sends"},{"type":"text","text":" "},{"type":"text","text":"an audio stream:3D voice effect: Sets the cycle period of the 3D voice"},{"type":"text","text":" "},{"type":"text","text":"effect.Pitch correction effect: Sets the basic mode and tonic pitch of the"},{"type":"text","text":" "},{"type":"text","text":"pitch correction effect. Different songs have different modes and tonic"},{"type":"text","text":" "},{"type":"text","text":"pitches. Agora recommends bounding this method with interface elements to"},{"type":"text","text":" "},{"type":"text","text":"enable users to adjust the pitch correction interactively.After setting the"},{"type":"text","text":" "},{"type":"text","text":"audio parameters, all users in the channel can hear the effect.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel.To get better audio"},{"type":"text","text":" "},{"type":"text","text":"effect quality, Agora recommends setting the scenario parameter of"},{"type":"text","text":" "},{"type":"text","text":"setAudioProfile [1\/2] as AgoraAudioScenarioGameStreaming(3) before calling"},{"type":"text","text":" "},{"type":"text","text":"this method.Do not set the profile parameter in setAudioProfile [1\/2] to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileSpeechStandard(1), or the method does not take effect.This"},{"type":"text","text":" "},{"type":"text","text":"method has the best effect on human voice processing, and Agora does not"},{"type":"text","text":" "},{"type":"text","text":"recommend calling this method to process audio data containing music.After"},{"type":"text","text":" "},{"type":"text","text":"calling setAudioEffectParameters, Agora does not recommend you to call the"},{"type":"text","text":" "},{"type":"text","text":"following methods, otherwise the effect set by setAudioEffectParameters will"},{"type":"text","text":" "},{"type":"text","text":"be overwritten: setAudioEffectPreset setVoiceBeautifierPreset"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoicePitch setLocalVoiceEqualizationOfBandFrequency"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoiceReverbOfType setVoiceBeautifierParameters"},{"type":"text","text":" "},{"type":"text","text":"setVoiceConversionPreset"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioEffectParameters"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioEffectPreset","preciseIdentifier":"c:@E@AgoraAudioEffectPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setAudioEffectParameters(_:param1:param2:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setAudioEffectParameters:param1:param2:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setAudioEffectParameters:param1:param2:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setAudioEffectParameters(_:param1:param2:)":{"role":"symbol","title":"setAudioEffectParameters(_:param1:param2:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioEffectParameters"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioEffectPreset","preciseIdentifier":"c:@E@AgoraAudioEffectPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets parameters for SDK preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"Call this method to set the following parameters for the local user who sends"},{"type":"text","text":" "},{"type":"text","text":"an audio stream:3D voice effect: Sets the cycle period of the 3D voice"},{"type":"text","text":" "},{"type":"text","text":"effect.Pitch correction effect: Sets the basic mode and tonic pitch of the"},{"type":"text","text":" "},{"type":"text","text":"pitch correction effect. Different songs have different modes and tonic"},{"type":"text","text":" "},{"type":"text","text":"pitches. Agora recommends bounding this method with interface elements to"},{"type":"text","text":" "},{"type":"text","text":"enable users to adjust the pitch correction interactively.After setting the"},{"type":"text","text":" "},{"type":"text","text":"audio parameters, all users in the channel can hear the effect.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel.To get better audio"},{"type":"text","text":" "},{"type":"text","text":"effect quality, Agora recommends setting the scenario parameter of"},{"type":"text","text":" "},{"type":"text","text":"setAudioProfile [1\/2] as AgoraAudioScenarioGameStreaming(3) before calling"},{"type":"text","text":" "},{"type":"text","text":"this method.Do not set the profile parameter in setAudioProfile [1\/2] to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileSpeechStandard(1), or the method does not take effect.This"},{"type":"text","text":" "},{"type":"text","text":"method has the best effect on human voice processing, and Agora does not"},{"type":"text","text":" "},{"type":"text","text":"recommend calling this method to process audio data containing music.After"},{"type":"text","text":" "},{"type":"text","text":"calling setAudioEffectParameters, Agora does not recommend you to call the"},{"type":"text","text":" "},{"type":"text","text":"following methods, otherwise the effect set by setAudioEffectParameters will"},{"type":"text","text":" "},{"type":"text","text":"be overwritten: setAudioEffectPreset setVoiceBeautifierPreset"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoicePitch setLocalVoiceEqualizationOfBandFrequency"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoiceReverbOfType setVoiceBeautifierParameters"},{"type":"text","text":" "},{"type":"text","text":"setVoiceConversionPreset"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setAudioEffectParameters(_:param1:param2:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioEffectParameters:param1:param2:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setaudioeffectparameters(_:param1:param2:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset":{"role":"symbol","title":"AgoraAudioEffectPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"abstract":[{"type":"text","text":"Preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"To get better audio effects, Agora recommends calling setAudioProfile [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"and setting the profile parameter as recommended below before using the"},{"type":"text","text":" "},{"type":"text","text":"preset audio effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setAudioEffectParameters:param1:param2:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioEffectParameters:param1:param2:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setAudioEffectParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","preciseIdentifier":"c:@E@AgoraAudioEffectPreset","text":"AgoraAudioEffectPreset"},{"kind":"text","text":") "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":" "},{"kind":"identifier","text":"param1:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"param1"},{"kind":"text","text":" "},{"kind":"identifier","text":"param2:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"param2"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioEffectParameters(_:param1:param2:)\/title","value":"setAudioEffectParameters:param1:param2:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setAudioEffectParameters(_:param1:param2:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioEffectParameters:param1:param2:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}