{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraCapturerConfiguration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration","text":"AgoraCameraCapturerConfiguration"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The camera capture configuration. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraCameraCapturerConfiguration ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setcameracapturerconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setcameracapturerconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setCameraCapturerConfiguration(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the camera capture configuration."},{"type":"text","text":" "},{"type":"text","text":"Call this method before calling joinChannelByToken [2\/4] , enableVideo , or"},{"type":"text","text":" "},{"type":"text","text":"enableLocalVideo , depending on which method you use to turn on your local"},{"type":"text","text":" "},{"type":"text","text":"camera."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraCapturerConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setCameraCapturerConfiguration(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setCameraCapturerConfiguration:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setCameraCapturerConfiguration:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraCapturerConfiguration":{"role":"symbol","title":"AgoraCameraCapturerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"abstract":[{"type":"text","text":"The camera capturer preference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"url":"\/documentation\/agorartckit\/agoracameracapturerconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setCameraCapturerConfiguration(_:)":{"role":"symbol","title":"setCameraCapturerConfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraCapturerConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the camera capture configuration."},{"type":"text","text":" "},{"type":"text","text":"Call this method before calling joinChannelByToken [2\/4] , enableVideo , or"},{"type":"text","text":" "},{"type":"text","text":"enableLocalVideo , depending on which method you use to turn on your local"},{"type":"text","text":" "},{"type":"text","text":"camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setCameraCapturerConfiguration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCameraCapturerConfiguration:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setcameracapturerconfiguration(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setCameraCapturerConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCameraCapturerConfiguration:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCameraCapturerConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","preciseIdentifier":"c:objc(cs)AgoraCameraCapturerConfiguration","text":"AgoraCameraCapturerConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/title","value":"AgoraCameraCapturerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setCameraCapturerConfiguration(_:)\/title","value":"setCameraCapturerConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setCameraCapturerConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCameraCapturerConfiguration:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}