{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRole"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions","text":"AgoraClientRoleOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -1: A general error occurs (no specified reason). -2: The parameter is invalid. -5: The request is rejected. -7: The SDK is not initialized."}]}]},{"kind":"parameters","parameters":[{"name":"role","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user role in the interactive live streaming. See AgoraClientRole."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The detailed options of a user, including the user level. See AgoraClientRoleOptions."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the interactive live streaming profile, the SDK sets the user role as audience by default. You can call this method to set the user role as host. You can call this method either before or after joining a channel. If you call this method to set the user’s role as the host before joining the channel and set the local video property through the setupLocalVideo method, the local video preview is automatically enabled when the user joins the channel. If you call this method to switch the user role after joining a channel, the SDK automatically does the following: Calls muteLocalAudioStream and muteLocalVideoStream to change the publishing state. Triggers didClientRoleChanged on the local client. Triggers didJoinedOfUid or didOfflineOfUid on the remote client. The difference between this method and setClientRole [1\/2] is that this method can set the user level in addition to the user role. The user role ( role ) determines the permissions that the SDK grants to a user, such as permission to send local streams, receive remote streams, and push streams to a CDN address. The user level ( level ) determines the level of services that a user can enjoy within the permissions of the user’s role. For example, an audience member can choose to receive remote streams with low latency or ultra-low latency. User level affects the pricing of services. This method applies to the interactive live streaming profile (the profile parameter of setChannelProfile is AgoraChannelProfileLiveBroadcasting ) only."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setclientrole(_:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setclientrole(_:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setClientRole(_:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the user role and level in an interactive live streaming channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRole"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setClientRole(_:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setClientRole:options:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setClientRole:options:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"seeAlsoSections":[{"title":"Channel Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:info:uid:joinSuccess:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateChannel(with:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:leaveChannelBlock:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/renewToken(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setClientRole(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/getConnectionState()"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/getConnectionState()":{"role":"symbol","title":"getConnectionState()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConnectionState"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraConnectionState","preciseIdentifier":"c:@E@AgoraConnectionState"}],"abstract":[{"type":"text","text":"Gets the current connection state of the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/getConnectionState()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getConnectionState"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/getconnectionstate()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/joinChannel(byToken:channelId:info:uid:joinSuccess:)":{"role":"symbol","title":"joinChannel(byToken:channelId:info:uid:joinSuccess:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinSuccess"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Joins a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:info:uid:joinSuccess:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinChannelByToken:channelId:info:uid:joinSuccess:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/joinchannel(bytoken:channelid:info:uid:joinsuccess:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleOptions":{"role":"symbol","title":"AgoraClientRoleOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleOptions"}],"abstract":[{"type":"text","text":"Setting of user role properties."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleOptions"}],"url":"\/documentation\/agorartckit\/agoraclientroleoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/leaveChannel(_:leaveChannelBlock:)":{"role":"symbol","title":"leaveChannel(_:leaveChannelBlock:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraLeaveChannelOptions","preciseIdentifier":"c:objc(cs)AgoraLeaveChannelOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leaveChannelBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets channel options and leaves the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:leaveChannelBlock:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leaveChannel:leaveChannelBlock:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/leavechannel(_:leavechannelblock:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/leaveChannel(_:)":{"role":"symbol","title":"leaveChannel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannel"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Leaves a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leaveChannel:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/leavechannel(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/updateChannel(with:)":{"role":"symbol","title":"updateChannel(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcChannelMediaOptions","preciseIdentifier":"c:objc(cs)AgoraRtcChannelMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the channel media options after joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateChannel(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelWithMediaOptions:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/updatechannel(with:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)":{"role":"symbol","title":"joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcChannelMediaOptions","preciseIdentifier":"c:objc(cs)AgoraRtcChannelMediaOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinSuccess"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Joins a channel with media options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinChannelByToken:channelId:uid:mediaOptions:joinSuccess:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/joinchannel(bytoken:channelid:uid:mediaoptions:joinsuccess:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setClientRole(_:)":{"role":"symbol","title":"setClientRole(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRole"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the client role."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setClientRole(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setClientRole:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setclientrole(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRole":{"role":"symbol","title":"AgoraClientRole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRole"}],"abstract":[{"type":"text","text":"The user role in the interactive live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRole"}],"url":"\/documentation\/agorartckit\/agoraclientrole"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setClientRole(_:options:)":{"role":"symbol","title":"setClientRole(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRole"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the user role and level in an interactive live streaming channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setClientRole(_:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setClientRole:options:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setclientrole(_:options:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/renewToken(_:)":{"role":"symbol","title":"renewToken(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renewToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Renews the token."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/renewToken(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renewToken:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/renewtoken(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setClientRole:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClientRole:options:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Channel Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:info:uid:joinSuccess:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateChannel(with:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:leaveChannelBlock:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/renewToken(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setClientRole(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/getConnectionState()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setClientRole:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":")"},{"kind":"internalParam","text":"role"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions","text":"AgoraClientRoleOptions"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1getConnectionState()\/title","value":"getConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1getConnectionState()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannel(byToken:channelId:info:uid:joinSuccess:)\/title","value":"joinChannelByToken:channelId:info:uid:joinSuccess:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannel(byToken:channelId:info:uid:joinSuccess:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinChannelByToken:channelId:info:uid:joinSuccess:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions\/title","value":"AgoraClientRoleOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannel(_:leaveChannelBlock:)\/title","value":"leaveChannel:leaveChannelBlock:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannel(_:leaveChannelBlock:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChannel:leaveChannelBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannel(_:)\/title","value":"leaveChannel:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateChannel(with:)\/title","value":"updateChannelWithMediaOptions:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateChannel(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithMediaOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)\/title","value":"joinChannelByToken:channelId:uid:mediaOptions:joinSuccess:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinChannelByToken:channelId:uid:mediaOptions:joinSuccess:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setClientRole(_:)\/title","value":"setClientRole:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setClientRole(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClientRole:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRole\/title","value":"AgoraClientRole"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRole\/fragments","value":[{"kind":"identifier","text":"AgoraClientRole"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setClientRole(_:options:)\/title","value":"setClientRole:options:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setClientRole(_:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClientRole:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1renewToken(_:)\/title","value":"renewToken:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1renewToken(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renewToken:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}