{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCloudProxy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"proxyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCloudProxyType","preciseIdentifier":"c:@E@AgoraCloudProxyType","text":"AgoraCloudProxyType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"proxyType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the cloud proxy. See AgoraCloudProxyType"},{"type":"text","text":" "},{"type":"text","text":".This parameter is mandatory. The SDK reports an error if you do not pass in"},{"type":"text","text":" "},{"type":"text","text":"a value."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -2: The parameter is invalid. -7: The"},{"type":"text","text":" "},{"type":"text","text":"SDK is not initialized."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setcloudproxy(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setcloudproxy(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setCloudProxy(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets up cloud proxy service."},{"type":"text","text":" "},{"type":"text","text":"When users’ network access is restricted by a firewall, configure the"},{"type":"text","text":" "},{"type":"text","text":"firewall to allow specific IP addresses and ports provided by Agora; then,"},{"type":"text","text":" "},{"type":"text","text":"call this method to enable the cloud proxyType and set the cloud proxy type"},{"type":"text","text":" "},{"type":"text","text":"with the proxyType parameter.After successfully connecting to the cloud"},{"type":"text","text":" "},{"type":"text","text":"proxy, the SDK triggers the connectionChangedToState"},{"type":"text","text":" "},{"type":"text","text":"(AgoraConnectionStateConnecting,"},{"type":"text","text":" "},{"type":"text","text":"AgoraConnectionChangedReasonSettingProxyServer) callback.To disable the cloud"},{"type":"text","text":" "},{"type":"text","text":"proxy that has been set, call the setCloudProxy (AgoraNoneProxyType).To"},{"type":"text","text":" "},{"type":"text","text":"change the cloud proxy type that has been set, call the setCloudProxy"},{"type":"text","text":" "},{"type":"text","text":"(AgoraNoneProxyType) first, and then call the setCloudProxy to set the"},{"type":"text","text":" "},{"type":"text","text":"proxyType you want.Agora recommends that you call this method after joining a"},{"type":"text","text":" "},{"type":"text","text":"channel.When a user is behind a firewall and uses the Force UDP cloud proxy,"},{"type":"text","text":" "},{"type":"text","text":"the services for Media Push and cohosting across channels are not"},{"type":"text","text":" "},{"type":"text","text":"available.When you use the Force TCP cloud proxy, note that an error would"},{"type":"text","text":" "},{"type":"text","text":"occur when calling the startAudioMixing [2\/2] method to play online music"},{"type":"text","text":" "},{"type":"text","text":"files in the HTTP protocol. The services for Media Push and cohosting across"},{"type":"text","text":" "},{"type":"text","text":"channels use the cloud proxy with the TCP protocol."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCloudProxy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraCloudProxyType","preciseIdentifier":"c:@E@AgoraCloudProxyType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setCloudProxy(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setCloudProxy:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setCloudProxy:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setCloudProxy(_:)":{"role":"symbol","title":"setCloudProxy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCloudProxy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraCloudProxyType","preciseIdentifier":"c:@E@AgoraCloudProxyType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets up cloud proxy service."},{"type":"text","text":" "},{"type":"text","text":"When users’ network access is restricted by a firewall, configure the"},{"type":"text","text":" "},{"type":"text","text":"firewall to allow specific IP addresses and ports provided by Agora; then,"},{"type":"text","text":" "},{"type":"text","text":"call this method to enable the cloud proxyType and set the cloud proxy type"},{"type":"text","text":" "},{"type":"text","text":"with the proxyType parameter.After successfully connecting to the cloud"},{"type":"text","text":" "},{"type":"text","text":"proxy, the SDK triggers the connectionChangedToState"},{"type":"text","text":" "},{"type":"text","text":"(AgoraConnectionStateConnecting,"},{"type":"text","text":" "},{"type":"text","text":"AgoraConnectionChangedReasonSettingProxyServer) callback.To disable the cloud"},{"type":"text","text":" "},{"type":"text","text":"proxy that has been set, call the setCloudProxy (AgoraNoneProxyType).To"},{"type":"text","text":" "},{"type":"text","text":"change the cloud proxy type that has been set, call the setCloudProxy"},{"type":"text","text":" "},{"type":"text","text":"(AgoraNoneProxyType) first, and then call the setCloudProxy to set the"},{"type":"text","text":" "},{"type":"text","text":"proxyType you want.Agora recommends that you call this method after joining a"},{"type":"text","text":" "},{"type":"text","text":"channel.When a user is behind a firewall and uses the Force UDP cloud proxy,"},{"type":"text","text":" "},{"type":"text","text":"the services for Media Push and cohosting across channels are not"},{"type":"text","text":" "},{"type":"text","text":"available.When you use the Force TCP cloud proxy, note that an error would"},{"type":"text","text":" "},{"type":"text","text":"occur when calling the startAudioMixing [2\/2] method to play online music"},{"type":"text","text":" "},{"type":"text","text":"files in the HTTP protocol. The services for Media Push and cohosting across"},{"type":"text","text":" "},{"type":"text","text":"channels use the cloud proxy with the TCP protocol."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setCloudProxy(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCloudProxy:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setcloudproxy(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCloudProxyType":{"role":"symbol","title":"AgoraCloudProxyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCloudProxyType"}],"abstract":[{"type":"text","text":"The cloud proxy type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCloudProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCloudProxyType"}],"url":"\/documentation\/agorartckit\/agoracloudproxytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setCloudProxy:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCloudProxy:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCloudProxy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCloudProxyType","preciseIdentifier":"c:@E@AgoraCloudProxyType","text":"AgoraCloudProxyType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"proxyType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setCloudProxy(_:)\/title","value":"setCloudProxy:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setCloudProxy(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCloudProxy:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCloudProxyType\/title","value":"AgoraCloudProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCloudProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraCloudProxyType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}