{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable face detection for the local user:YES:"},{"type":"text","text":" "},{"type":"text","text":"Enable face detection.NO: (Default) Disable face detection."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setcameraautoexposurefacemodeenabled(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setcameraautoexposurefacemodeenabled(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setCameraAutoExposureFaceModeEnabled(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables or disables face detection for the local user."},{"type":"text","text":" "},{"type":"text","text":"You can call this method either before or after joining a channel.Once face"},{"type":"text","text":" "},{"type":"text","text":"detection is enabled, the SDK triggers the facePositionDidChangeWidth"},{"type":"text","text":" "},{"type":"text","text":"callback to report the face information of the local user, which includes the"},{"type":"text","text":" "},{"type":"text","text":"following:The width and height of the local video.The position of the human"},{"type":"text","text":" "},{"type":"text","text":"face in the local view.The distance between the human face and the"},{"type":"text","text":" "},{"type":"text","text":"screen.This method needs to be called after the camera is started (for"},{"type":"text","text":" "},{"type":"text","text":"example, by calling startPreviewjoinChannelByToken [2\/4])."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"setCameraAutoExposureFaceModeEnabled(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setCameraAutoExposureFaceModeEnabled:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setCameraAutoExposureFaceModeEnabled(_:)":{"role":"symbol","title":"setCameraAutoExposureFaceModeEnabled(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Enables or disables face detection for the local user."},{"type":"text","text":" "},{"type":"text","text":"You can call this method either before or after joining a channel.Once face"},{"type":"text","text":" "},{"type":"text","text":"detection is enabled, the SDK triggers the facePositionDidChangeWidth"},{"type":"text","text":" "},{"type":"text","text":"callback to report the face information of the local user, which includes the"},{"type":"text","text":" "},{"type":"text","text":"following:The width and height of the local video.The position of the human"},{"type":"text","text":" "},{"type":"text","text":"face in the local view.The distance between the human face and the"},{"type":"text","text":" "},{"type":"text","text":"screen.This method needs to be called after the camera is started (for"},{"type":"text","text":" "},{"type":"text","text":"example, by calling startPreviewjoinChannelByToken [2\/4])."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setCameraAutoExposureFaceModeEnabled(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setcameraautoexposurefacemodeenabled(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setCameraAutoExposureFaceModeEnabled:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setCameraAutoExposureFaceModeEnabled(_:)\/title","value":"setCameraAutoExposureFaceModeEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setCameraAutoExposureFaceModeEnabled(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCameraAutoExposureFaceModeEnabled:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}