{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDualStreamMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode","text":"AgoraSimulcastStreamMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mode in which the video stream is sent. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraSimulcastStreamMode ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setdualstreammode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setdualstreammode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setDualStreamMode(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets dual-stream mode on the sender side."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1The SDK enables the low-quality video stream auto mode on the"},{"type":"text","text":" "},{"type":"text","text":"sender by default, which is equivalent to calling this method and setting the"},{"type":"text","text":" "},{"type":"text","text":"mode to AgoraAutoSimulcastStream. If you want to modify this behavior, you"},{"type":"text","text":" "},{"type":"text","text":"can call this method and modify the mode to AgoraDisableSimulcastStream(never"},{"type":"text","text":" "},{"type":"text","text":"send low-quality video streams) or AgoraEnableSimulcastStream (always send"},{"type":"text","text":" "},{"type":"text","text":"low-quality video streams).The difference and connection between this method"},{"type":"text","text":" "},{"type":"text","text":"and enableDualStreamMode [1\/2] is as follows:When calling this method and"},{"type":"text","text":" "},{"type":"text","text":"setting mode to AgoraDisableSimulcastStream, it has the same effect as"},{"type":"text","text":" "},{"type":"text","text":"enableDualStreamMode "},{"type":"reference","isActive":true,"identifier":"NO"},{"type":"text","text":".When calling this method and setting mode to"},{"type":"text","text":" "},{"type":"text","text":"AgoraEnableSimulcastStream, it has the same effect as enableDualStreamMode"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"YES"},{"type":"text","text":".Both methods can be called before and after joining a channel. If"},{"type":"text","text":" "},{"type":"text","text":"they are used at the same time, the settings in the method called later shall"},{"type":"text","text":" "},{"type":"text","text":"prevail."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDualStreamMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setDualStreamMode(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setDualStreamMode:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setDualStreamMode:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setDualStreamMode(_:)":{"role":"symbol","title":"setDualStreamMode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDualStreamMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets dual-stream mode on the sender side."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1The SDK enables the low-quality video stream auto mode on the"},{"type":"text","text":" "},{"type":"text","text":"sender by default, which is equivalent to calling this method and setting the"},{"type":"text","text":" "},{"type":"text","text":"mode to AgoraAutoSimulcastStream. If you want to modify this behavior, you"},{"type":"text","text":" "},{"type":"text","text":"can call this method and modify the mode to AgoraDisableSimulcastStream(never"},{"type":"text","text":" "},{"type":"text","text":"send low-quality video streams) or AgoraEnableSimulcastStream (always send"},{"type":"text","text":" "},{"type":"text","text":"low-quality video streams).The difference and connection between this method"},{"type":"text","text":" "},{"type":"text","text":"and enableDualStreamMode [1\/2] is as follows:When calling this method and"},{"type":"text","text":" "},{"type":"text","text":"setting mode to AgoraDisableSimulcastStream, it has the same effect as"},{"type":"text","text":" "},{"type":"text","text":"enableDualStreamMode "},{"type":"reference","isActive":true,"identifier":"NO"},{"type":"text","text":".When calling this method and setting mode to"},{"type":"text","text":" "},{"type":"text","text":"AgoraEnableSimulcastStream, it has the same effect as enableDualStreamMode"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"YES"},{"type":"text","text":".Both methods can be called before and after joining a channel. If"},{"type":"text","text":" "},{"type":"text","text":"they are used at the same time, the settings in the method called later shall"},{"type":"text","text":" "},{"type":"text","text":"prevail."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setDualStreamMode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDualStreamMode:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setdualstreammode(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode":{"role":"symbol","title":"AgoraSimulcastStreamMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"abstract":[{"type":"text","text":"The mode in which the video stream is sent."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode"},"YES":{"title":"1\/2","titleInlineContent":[{"type":"text","text":"1\/2"}],"type":"link","identifier":"YES","url":"YES"},"NO":{"title":"1\/2","titleInlineContent":[{"type":"text","text":"1\/2"}],"type":"link","identifier":"NO","url":"NO"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setDualStreamMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDualStreamMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDualStreamMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode","text":"AgoraSimulcastStreamMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setDualStreamMode(_:)\/title","value":"setDualStreamMode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setDualStreamMode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDualStreamMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/title","value":"AgoraSimulcastStreamMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}