{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDualStreamMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode","text":"AgoraSimulcastStreamMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig","text":"AgoraSimulcastStreamConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mode in which the video stream is sent. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraSimulcastStreamMode ."}]}]},{"name":"streamConfig","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the low-quality video stream."},{"type":"text","text":" "},{"type":"text","text":"See AgoraSimulcastStreamConfig .When setting mode to"},{"type":"text","text":" "},{"type":"text","text":"AgoraDisableSimulcastStream, setting streamConfig will not take effect."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setdualstreammode(_:streamconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setdualstreammode(_:streamconfig:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setDualStreamMode(_:streamConfig:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets dual-stream mode configuration on the sender, and sets the low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream. The difference and connection between this method and"},{"type":"text","text":" "},{"type":"text","text":"enableDualStreamMode [1\/2] is as follows:When calling this method and setting"},{"type":"text","text":" "},{"type":"text","text":"mode to AgoraDisableSimulcastStream, it has the same effect as"},{"type":"text","text":" "},{"type":"text","text":"enableDualStreamMode "},{"type":"reference","isActive":true,"identifier":"NO"},{"type":"text","text":".When calling this method and setting mode to"},{"type":"text","text":" "},{"type":"text","text":"AgoraEnableSimulcastStream, it has the same effect as enableDualStreamMode"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"YES"},{"type":"text","text":".Both methods can be called before and after joining a channel. If"},{"type":"text","text":" "},{"type":"text","text":"they are used at the same time, the settings in the method called later shall"},{"type":"text","text":" "},{"type":"text","text":"prevail.Sincev4.0.1The SDK enables the low-quality video stream auto mode on"},{"type":"text","text":" "},{"type":"text","text":"the sender by default, which is equivalent to calling this method and setting"},{"type":"text","text":" "},{"type":"text","text":"the mode to AgoraAutoSimulcastStream. If you want to modify this behavior,"},{"type":"text","text":" "},{"type":"text","text":"you can call this method and modify the mode to"},{"type":"text","text":" "},{"type":"text","text":"AgoraDisableSimulcastStream(never send low-quality video streams) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEnableSimulcastStream (always send low-quality video streams).The"},{"type":"text","text":" "},{"type":"text","text":"difference between this method and setDualStreamMode [1\/2] is that this"},{"type":"text","text":" "},{"type":"text","text":"method can also configure the low-quality video stream, and the SDK sends the"},{"type":"text","text":" "},{"type":"text","text":"stream according to the configuration in streamConfig."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDualStreamMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setDualStreamMode(_:streamConfig:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setDualStreamMode:streamConfig:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setDualStreamMode:streamConfig:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"NO":{"title":"1\/2","titleInlineContent":[{"type":"text","text":"1\/2"}],"type":"link","identifier":"NO","url":"NO"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setDualStreamMode(_:streamConfig:)":{"role":"symbol","title":"setDualStreamMode(_:streamConfig:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDualStreamMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets dual-stream mode configuration on the sender, and sets the low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream. The difference and connection between this method and"},{"type":"text","text":" "},{"type":"text","text":"enableDualStreamMode [1\/2] is as follows:When calling this method and setting"},{"type":"text","text":" "},{"type":"text","text":"mode to AgoraDisableSimulcastStream, it has the same effect as"},{"type":"text","text":" "},{"type":"text","text":"enableDualStreamMode "},{"type":"reference","isActive":true,"identifier":"NO"},{"type":"text","text":".When calling this method and setting mode to"},{"type":"text","text":" "},{"type":"text","text":"AgoraEnableSimulcastStream, it has the same effect as enableDualStreamMode"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"YES"},{"type":"text","text":".Both methods can be called before and after joining a channel. If"},{"type":"text","text":" "},{"type":"text","text":"they are used at the same time, the settings in the method called later shall"},{"type":"text","text":" "},{"type":"text","text":"prevail.Sincev4.0.1The SDK enables the low-quality video stream auto mode on"},{"type":"text","text":" "},{"type":"text","text":"the sender by default, which is equivalent to calling this method and setting"},{"type":"text","text":" "},{"type":"text","text":"the mode to AgoraAutoSimulcastStream. If you want to modify this behavior,"},{"type":"text","text":" "},{"type":"text","text":"you can call this method and modify the mode to"},{"type":"text","text":" "},{"type":"text","text":"AgoraDisableSimulcastStream(never send low-quality video streams) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEnableSimulcastStream (always send low-quality video streams).The"},{"type":"text","text":" "},{"type":"text","text":"difference between this method and setDualStreamMode [1\/2] is that this"},{"type":"text","text":" "},{"type":"text","text":"method can also configure the low-quality video stream, and the SDK sends the"},{"type":"text","text":" "},{"type":"text","text":"stream according to the configuration in streamConfig."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setDualStreamMode(_:streamConfig:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDualStreamMode:streamConfig:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setdualstreammode(_:streamconfig:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode":{"role":"symbol","title":"AgoraSimulcastStreamMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"abstract":[{"type":"text","text":"The mode in which the video stream is sent."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"YES":{"title":"1\/2","titleInlineContent":[{"type":"text","text":"1\/2"}],"type":"link","identifier":"YES","url":"YES"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamConfig":{"role":"symbol","title":"AgoraSimulcastStreamConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}],"abstract":[{"type":"text","text":"The configuration of the low-quality video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreamconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setDualStreamMode:streamConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDualStreamMode:streamConfig:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDualStreamMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","preciseIdentifier":"c:@E@AgoraSimulcastStreamMode","text":"AgoraSimulcastStreamMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamConfig","preciseIdentifier":"c:objc(cs)AgoraSimulcastStreamConfig","text":"AgoraSimulcastStreamConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"streamConfig"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setDualStreamMode(_:streamConfig:)\/title","value":"setDualStreamMode:streamConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setDualStreamMode(_:streamConfig:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDualStreamMode:streamConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/title","value":"AgoraSimulcastStreamMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamConfig\/title","value":"AgoraSimulcastStreamConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamConfig\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}