{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExternalVideoSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useTexture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExternalVideoSourceType","preciseIdentifier":"c:@E@AgoraExternalVideoSourceType","text":"AgoraExternalVideoSourceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedVideoTrackOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoTrackOptions","text":"AgoraEncodedVideoTrackOptions"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setexternalvideosource(_:usetexture:sourcetype:encodedvideotrackoption:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setexternalvideosource(_:usetexture:sourcetype:encodedvideotrackoption:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setExternalVideoSource(_:useTexture:sourceType:encodedVideoTrackOption:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExternalVideoSource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useTexture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraExternalVideoSourceType","preciseIdentifier":"c:@E@AgoraExternalVideoSourceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedVideoTrackOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedVideoTrackOptions","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoTrackOptions"},{"kind":"text","text":")"}],"title":"setExternalVideoSource(_:useTexture:sourceType:encodedVideoTrackOption:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setExternalVideoSource:useTexture:sourceType:encodedVideoTrackOption:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setExternalVideoSource:useTexture:sourceType:encodedVideoTrackOption:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExternalVideoSourceType":{"role":"symbol","title":"AgoraExternalVideoSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExternalVideoSourceType"}],"abstract":[{"type":"text","text":"The external video frame encoding type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExternalVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExternalVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoraexternalvideosourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoTrackOptions":{"role":"symbol","title":"AgoraEncodedVideoTrackOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}],"url":"\/documentation\/agorartckit\/agoraencodedvideotrackoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setExternalVideoSource(_:useTexture:sourceType:encodedVideoTrackOption:)":{"role":"symbol","title":"setExternalVideoSource(_:useTexture:sourceType:encodedVideoTrackOption:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setExternalVideoSource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useTexture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraExternalVideoSourceType","preciseIdentifier":"c:@E@AgoraExternalVideoSourceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encodedVideoTrackOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedVideoTrackOptions","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoTrackOptions"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setExternalVideoSource(_:useTexture:sourceType:encodedVideoTrackOption:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setExternalVideoSource:useTexture:sourceType:encodedVideoTrackOption:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setexternalvideosource(_:usetexture:sourcetype:encodedvideotrackoption:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setExternalVideoSource:useTexture:sourceType:encodedVideoTrackOption:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setExternalVideoSource:useTexture:sourceType:encodedVideoTrackOption:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setExternalVideoSource:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":" "},{"kind":"identifier","text":"useTexture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useTexture"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExternalVideoSourceType","preciseIdentifier":"c:@E@AgoraExternalVideoSourceType","text":"AgoraExternalVideoSourceType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sourceType"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedVideoTrackOption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions","preciseIdentifier":"c:objc(cs)AgoraEncodedVideoTrackOptions","text":"AgoraEncodedVideoTrackOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"encodedVideoTrackOption"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExternalVideoSourceType\/title","value":"AgoraExternalVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExternalVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraExternalVideoSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions\/title","value":"AgoraEncodedVideoTrackOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setExternalVideoSource(_:useTexture:sourceType:encodedVideoTrackOption:)\/title","value":"setExternalVideoSource:useTexture:sourceType:encodedVideoTrackOption:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setExternalVideoSource(_:useTexture:sourceType:encodedVideoTrackOption:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setExternalVideoSource:useTexture:sourceType:encodedVideoTrackOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}