{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEncryptionSecret"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"secret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"secret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encryption password."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setencryptionsecret(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setencryptionsecret(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setEncryptionSecret(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables built-in encryption with an encryption password before users join a"},{"type":"text","text":" "},{"type":"text","text":"channel. Deprecated:Use enableEncryption instead.Before joining the channel,"},{"type":"text","text":" "},{"type":"text","text":"you need to call this method to set the secret parameter to enable the"},{"type":"text","text":" "},{"type":"text","text":"built-in encryption. All users in the same channel should use the same"},{"type":"text","text":" "},{"type":"text","text":"secret. The secret is automatically cleared once a user leaves the channel."},{"type":"text","text":" "},{"type":"text","text":"If you do not specify the secret or secret is set as null, the built-in"},{"type":"text","text":" "},{"type":"text","text":"encryption is disabled.Do not use this method for Media Push.For optimal"},{"type":"text","text":" "},{"type":"text","text":"transmission, ensure that the encrypted data size does not exceed the"},{"type":"text","text":" "},{"type":"text","text":"original data size + 16 bytes. 16 bytes is the maximum padding size for AES"},{"type":"text","text":" "},{"type":"text","text":"encryption."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setEncryptionSecret:"}],"role":"symbol","title":"setEncryptionSecret(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEncryptionSecret"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setEncryptionSecret:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use enableEncryption: instead."}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setEncryptionSecret(_:)":{"deprecated":true,"role":"symbol","title":"setEncryptionSecret(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEncryptionSecret"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables built-in encryption with an encryption password before users join a"},{"type":"text","text":" "},{"type":"text","text":"channel. Deprecated:Use enableEncryption instead.Before joining the channel,"},{"type":"text","text":" "},{"type":"text","text":"you need to call this method to set the secret parameter to enable the"},{"type":"text","text":" "},{"type":"text","text":"built-in encryption. All users in the same channel should use the same"},{"type":"text","text":" "},{"type":"text","text":"secret. The secret is automatically cleared once a user leaves the channel."},{"type":"text","text":" "},{"type":"text","text":"If you do not specify the secret or secret is set as null, the built-in"},{"type":"text","text":" "},{"type":"text","text":"encryption is disabled.Do not use this method for Media Push.For optimal"},{"type":"text","text":" "},{"type":"text","text":"transmission, ensure that the encrypted data size does not exceed the"},{"type":"text","text":" "},{"type":"text","text":"original data size + 16 bytes. 16 bytes is the maximum padding size for AES"},{"type":"text","text":" "},{"type":"text","text":"encryption."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setEncryptionSecret(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setEncryptionSecret:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setencryptionsecret(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setEncryptionSecret:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEncryptionSecret:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setEncryptionSecret:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"secret"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setEncryptionSecret(_:)\/title","value":"setEncryptionSecret:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setEncryptionSecret(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEncryptionSecret:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}