{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEncryptionMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"encryptionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"encryptionMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The following encryption modes:“aes-128-xts”:"},{"type":"text","text":" "},{"type":"text","text":"128-bit AES encryption, XTS mode.“aes-128-ecb”: 128-bit AES encryption, ECB"},{"type":"text","text":" "},{"type":"text","text":"mode.“aes-256-xts”: 256-bit AES encryption, XTS mode.“sm4-128-ecb”: 128-bit"},{"type":"text","text":" "},{"type":"text","text":"SM4 encryption, ECB mode.“aes-128-gcm”: 128-bit AES encryption, GCM"},{"type":"text","text":" "},{"type":"text","text":"mode.“aes-256-gcm”: 256-bit AES encryption, GCM mode.””: When this parameter"},{"type":"text","text":" "},{"type":"text","text":"is set as null, the encryption mode is set as “aes-128-gcm” by default."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setencryptionmode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setencryptionmode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setEncryptionMode(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the built-in encryption mode."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Use enableEncryption instead.The SDK supports built-in encryption"},{"type":"text","text":" "},{"type":"text","text":"schemes, AES-128-GCM is supported by default. Call this method to use other"},{"type":"text","text":" "},{"type":"text","text":"encryption modes. All users in the same channel must use the same encryption"},{"type":"text","text":" "},{"type":"text","text":"mode and secret. Refer to the information related to the AES encryption"},{"type":"text","text":" "},{"type":"text","text":"algorithm on the differences between the encryption modes.Before calling this"},{"type":"text","text":" "},{"type":"text","text":"method, please call setEncryptionSecret to enable the built-in encryption"},{"type":"text","text":" "},{"type":"text","text":"function."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setEncryptionMode:"}],"role":"symbol","title":"setEncryptionMode(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEncryptionMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setEncryptionMode:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use enableEncryption: instead."}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setEncryptionMode(_:)":{"deprecated":true,"role":"symbol","title":"setEncryptionMode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEncryptionMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the built-in encryption mode."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Use enableEncryption instead.The SDK supports built-in encryption"},{"type":"text","text":" "},{"type":"text","text":"schemes, AES-128-GCM is supported by default. Call this method to use other"},{"type":"text","text":" "},{"type":"text","text":"encryption modes. All users in the same channel must use the same encryption"},{"type":"text","text":" "},{"type":"text","text":"mode and secret. Refer to the information related to the AES encryption"},{"type":"text","text":" "},{"type":"text","text":"algorithm on the differences between the encryption modes.Before calling this"},{"type":"text","text":" "},{"type":"text","text":"method, please call setEncryptionSecret to enable the built-in encryption"},{"type":"text","text":" "},{"type":"text","text":"function."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setEncryptionMode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setEncryptionMode:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setencryptionmode(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setEncryptionMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEncryptionMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setEncryptionMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"encryptionMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setEncryptionMode(_:)\/title","value":"setEncryptionMode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setEncryptionMode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEncryptionMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}