{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEnableSpeakerphone"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enableSpeaker"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enableSpeaker","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sets whether to enable the speakerphone or"},{"type":"text","text":" "},{"type":"text","text":"earpiece:YES: Enable the speakerphone or earpiece. The audio route is the"},{"type":"text","text":" "},{"type":"text","text":"speakerphone.NO: Disable the speakerphone or earpiece. The audio route is the"},{"type":"text","text":" "},{"type":"text","text":"earpiece."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setenablespeakerphone(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setenablespeakerphone(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setEnableSpeakerphone(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables\/Disables the audio route to the speakerphone."},{"type":"text","text":" "},{"type":"text","text":"If the default audio route of the SDK (see Set the Audio Route) or the"},{"type":"text","text":" "},{"type":"text","text":"setting in setDefaultAudioRouteToSpeakerphone cannot meet your requirements,"},{"type":"text","text":" "},{"type":"text","text":"you can call setEnableSpeakerphone to switch the current audio route. After a"},{"type":"text","text":" "},{"type":"text","text":"successful method call, the SDK triggers the didAudioRouteChanged"},{"type":"text","text":" "},{"type":"text","text":"callback.This method only sets the audio route in the current channel and"},{"type":"text","text":" "},{"type":"text","text":"does not influence the default audio route. If the user leaves the current"},{"type":"text","text":" "},{"type":"text","text":"channel and joins another channel, the default audio route is used.Call this"},{"type":"text","text":" "},{"type":"text","text":"method after joining a channel.If the user uses an external audio playback"},{"type":"text","text":" "},{"type":"text","text":"device such as a Bluetooth or wired headset, this method does not take"},{"type":"text","text":" "},{"type":"text","text":"effect, and the SDK plays audio through the external device. When the user"},{"type":"text","text":" "},{"type":"text","text":"uses multiple external devices, the SDK plays audio through the last"},{"type":"text","text":" "},{"type":"text","text":"connected device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEnableSpeakerphone"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setEnableSpeakerphone(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setEnableSpeakerphone:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setEnableSpeakerphone:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setEnableSpeakerphone(_:)":{"role":"symbol","title":"setEnableSpeakerphone(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEnableSpeakerphone"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables\/Disables the audio route to the speakerphone."},{"type":"text","text":" "},{"type":"text","text":"If the default audio route of the SDK (see Set the Audio Route) or the"},{"type":"text","text":" "},{"type":"text","text":"setting in setDefaultAudioRouteToSpeakerphone cannot meet your requirements,"},{"type":"text","text":" "},{"type":"text","text":"you can call setEnableSpeakerphone to switch the current audio route. After a"},{"type":"text","text":" "},{"type":"text","text":"successful method call, the SDK triggers the didAudioRouteChanged"},{"type":"text","text":" "},{"type":"text","text":"callback.This method only sets the audio route in the current channel and"},{"type":"text","text":" "},{"type":"text","text":"does not influence the default audio route. If the user leaves the current"},{"type":"text","text":" "},{"type":"text","text":"channel and joins another channel, the default audio route is used.Call this"},{"type":"text","text":" "},{"type":"text","text":"method after joining a channel.If the user uses an external audio playback"},{"type":"text","text":" "},{"type":"text","text":"device such as a Bluetooth or wired headset, this method does not take"},{"type":"text","text":" "},{"type":"text","text":"effect, and the SDK plays audio through the external device. When the user"},{"type":"text","text":" "},{"type":"text","text":"uses multiple external devices, the SDK plays audio through the last"},{"type":"text","text":" "},{"type":"text","text":"connected device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setEnableSpeakerphone(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setEnableSpeakerphone:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setenablespeakerphone(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setEnableSpeakerphone:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEnableSpeakerphone:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setEnableSpeakerphone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enableSpeaker"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setEnableSpeakerphone(_:)\/title","value":"setEnableSpeakerphone:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setEnableSpeakerphone(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEnableSpeakerphone:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}