{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHeadphoneEQPreset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset","preciseIdentifier":"c:@E@AgoraHeadphoneEQPreset","text":"AgoraHeadphoneEQPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The preset headphone equalization effect. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraHeadphoneEQPreset ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -1: A general error occurs (no specified"},{"type":"text","text":" "},{"type":"text","text":"reason)."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setheadphoneeqpreset(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setheadphoneeqpreset(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setHeadphoneEQPreset(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the preset headphone equalization effect."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1This method is mainly used in spatial audio effect scenarios. You"},{"type":"text","text":" "},{"type":"text","text":"can select the preset headphone equalizer to listen to the audio to achieve"},{"type":"text","text":" "},{"type":"text","text":"the expected audio experience.If the headphones you use already have a good"},{"type":"text","text":" "},{"type":"text","text":"equalization effect, you may not get a significant improvement when you call"},{"type":"text","text":" "},{"type":"text","text":"this method, and could even diminish the experience."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHeadphoneEQPreset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraHeadphoneEQPreset","preciseIdentifier":"c:@E@AgoraHeadphoneEQPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setHeadphoneEQPreset(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setHeadphoneEQPreset:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setHeadphoneEQPreset:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset":{"role":"symbol","title":"AgoraHeadphoneEQPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setHeadphoneEQPreset(_:)":{"role":"symbol","title":"setHeadphoneEQPreset(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHeadphoneEQPreset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraHeadphoneEQPreset","preciseIdentifier":"c:@E@AgoraHeadphoneEQPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the preset headphone equalization effect."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1This method is mainly used in spatial audio effect scenarios. You"},{"type":"text","text":" "},{"type":"text","text":"can select the preset headphone equalizer to listen to the audio to achieve"},{"type":"text","text":" "},{"type":"text","text":"the expected audio experience.If the headphones you use already have a good"},{"type":"text","text":" "},{"type":"text","text":"equalization effect, you may not get a significant improvement when you call"},{"type":"text","text":" "},{"type":"text","text":"this method, and could even diminish the experience."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setHeadphoneEQPreset(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setHeadphoneEQPreset:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setheadphoneeqpreset(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setHeadphoneEQPreset:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setHeadphoneEQPreset:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setHeadphoneEQPreset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset","preciseIdentifier":"c:@E@AgoraHeadphoneEQPreset","text":"AgoraHeadphoneEQPreset"},{"kind":"text","text":") "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/title","value":"AgoraHeadphoneEQPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/fragments","value":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setHeadphoneEQPreset(_:)\/title","value":"setHeadphoneEQPreset:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setHeadphoneEQPreset(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setHeadphoneEQPreset:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}