{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVoiceReverbOf"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"reverbType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType","preciseIdentifier":"c:@E@AgoraAudioReverbType","text":"AgoraAudioReverbType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withValue"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"reverbType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The reverberation key. Agora provides five"},{"type":"text","text":" "},{"type":"text","text":"reverberation keys, see AgoraAudioReverbType ."}]}]},{"name":"value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The value of the reverberation key."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalvoicereverbof(_:withvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalvoicereverbof(_:withvalue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalVoiceReverbOf(_:withValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the local voice reverberation."},{"type":"text","text":" "},{"type":"text","text":"The SDK provides an easier-to-use method, setAudioEffectPreset , to directly"},{"type":"text","text":" "},{"type":"text","text":"implement preset reverb effects for such as pop, R&B, and KTV.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVoiceReverbOf"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioReverbType","preciseIdentifier":"c:@E@AgoraAudioReverbType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setLocalVoiceReverbOf(_:withValue:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setLocalVoiceReverbOfType:withValue:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setLocalVoiceReverbOfType:withValue:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setLocalVoiceReverbOf(_:withValue:)":{"role":"symbol","title":"setLocalVoiceReverbOf(_:withValue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVoiceReverbOf"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioReverbType","preciseIdentifier":"c:@E@AgoraAudioReverbType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the local voice reverberation."},{"type":"text","text":" "},{"type":"text","text":"The SDK provides an easier-to-use method, setAudioEffectPreset , to directly"},{"type":"text","text":" "},{"type":"text","text":"implement preset reverb effects for such as pop, R&B, and KTV.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalVoiceReverbOf(_:withValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLocalVoiceReverbOfType:withValue:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setlocalvoicereverbof(_:withvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType":{"role":"symbol","title":"AgoraAudioReverbType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbType"}],"abstract":[{"type":"text","text":"Audio reverberation types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbType"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLocalVoiceReverbOfType:withValue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalVoiceReverbOfType:withValue:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLocalVoiceReverbOfType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType","preciseIdentifier":"c:@E@AgoraAudioReverbType","text":"AgoraAudioReverbType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reverbType"},{"kind":"text","text":" "},{"kind":"identifier","text":"withValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalVoiceReverbOf(_:withValue:)\/title","value":"setLocalVoiceReverbOfType:withValue:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalVoiceReverbOf(_:withValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalVoiceReverbOfType:withValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/title","value":"AgoraAudioReverbType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}