{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLowlightEnhanceOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions","preciseIdentifier":"c:objc(cs)AgoraLowlightEnhanceOptions","text":"AgoraLowlightEnhanceOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable low-light enhancement function:YES:"},{"type":"text","text":" "},{"type":"text","text":"Enable low-light enhancement function.NO: (Default) Disable low-light"},{"type":"text","text":" "},{"type":"text","text":"enhancement function."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The low-light enhancement options. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLowlightEnhanceOptions ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlowlightenhanceoptions(_:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlowlightenhanceoptions(_:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLowlightEnhanceOptions(_:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets low-light enhancement."},{"type":"text","text":" "},{"type":"text","text":"The low-light enhancement feature can adaptively adjust the brightness value"},{"type":"text","text":" "},{"type":"text","text":"of the video captured in situations with low or uneven lighting, such as"},{"type":"text","text":" "},{"type":"text","text":"backlit, cloudy, or dark scenes. It restores or highlights the image details"},{"type":"text","text":" "},{"type":"text","text":"and improves the overall visual effect of the video.You can call this method"},{"type":"text","text":" "},{"type":"text","text":"to enable the color enhancement feature and set the options of the color"},{"type":"text","text":" "},{"type":"text","text":"enhancement effect.Call this method after calling enableVideo .Dark light"},{"type":"text","text":" "},{"type":"text","text":"enhancement has certain requirements for equipment performance. The low-light"},{"type":"text","text":" "},{"type":"text","text":"enhancement feature has certain performance requirements on devices. If your"},{"type":"text","text":" "},{"type":"text","text":"device overheats after you enable low-light enhancement, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"modifying the low-light enhancement options to a less performance-consuming"},{"type":"text","text":" "},{"type":"text","text":"level or disabling low-light enhancement entirely.Both this method and"},{"type":"text","text":" "},{"type":"text","text":"setExtensionPropertyWithVendor can turn on low-light enhancement:When you use"},{"type":"text","text":" "},{"type":"text","text":"the SDK to capture video, Agora recommends this method (this method only"},{"type":"text","text":" "},{"type":"text","text":"works for video captured by the SDK).When you use an external video source to"},{"type":"text","text":" "},{"type":"text","text":"implement custom video capture, or send an external video source to the SDK,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends using setExtensionPropertyWithVendor.This method relies on"},{"type":"text","text":" "},{"type":"text","text":"the video enhancement dynamic library AgoraClearVisionExtension.xcframework."},{"type":"text","text":" "},{"type":"text","text":"If the dynamic library is deleted, the function cannot be enabled normally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLowlightEnhanceOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLowlightEnhanceOptions","preciseIdentifier":"c:objc(cs)AgoraLowlightEnhanceOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setLowlightEnhanceOptions(_:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setLowlightEnhanceOptions:options:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setLowlightEnhanceOptions:options:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setLowlightEnhanceOptions(_:options:)":{"role":"symbol","title":"setLowlightEnhanceOptions(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLowlightEnhanceOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLowlightEnhanceOptions","preciseIdentifier":"c:objc(cs)AgoraLowlightEnhanceOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets low-light enhancement."},{"type":"text","text":" "},{"type":"text","text":"The low-light enhancement feature can adaptively adjust the brightness value"},{"type":"text","text":" "},{"type":"text","text":"of the video captured in situations with low or uneven lighting, such as"},{"type":"text","text":" "},{"type":"text","text":"backlit, cloudy, or dark scenes. It restores or highlights the image details"},{"type":"text","text":" "},{"type":"text","text":"and improves the overall visual effect of the video.You can call this method"},{"type":"text","text":" "},{"type":"text","text":"to enable the color enhancement feature and set the options of the color"},{"type":"text","text":" "},{"type":"text","text":"enhancement effect.Call this method after calling enableVideo .Dark light"},{"type":"text","text":" "},{"type":"text","text":"enhancement has certain requirements for equipment performance. The low-light"},{"type":"text","text":" "},{"type":"text","text":"enhancement feature has certain performance requirements on devices. If your"},{"type":"text","text":" "},{"type":"text","text":"device overheats after you enable low-light enhancement, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"modifying the low-light enhancement options to a less performance-consuming"},{"type":"text","text":" "},{"type":"text","text":"level or disabling low-light enhancement entirely.Both this method and"},{"type":"text","text":" "},{"type":"text","text":"setExtensionPropertyWithVendor can turn on low-light enhancement:When you use"},{"type":"text","text":" "},{"type":"text","text":"the SDK to capture video, Agora recommends this method (this method only"},{"type":"text","text":" "},{"type":"text","text":"works for video captured by the SDK).When you use an external video source to"},{"type":"text","text":" "},{"type":"text","text":"implement custom video capture, or send an external video source to the SDK,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends using setExtensionPropertyWithVendor.This method relies on"},{"type":"text","text":" "},{"type":"text","text":"the video enhancement dynamic library AgoraClearVisionExtension.xcframework."},{"type":"text","text":" "},{"type":"text","text":"If the dynamic library is deleted, the function cannot be enabled normally."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLowlightEnhanceOptions(_:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLowlightEnhanceOptions:options:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setlowlightenhanceoptions(_:options:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceOptions":{"role":"symbol","title":"AgoraLowlightEnhanceOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}],"abstract":[{"type":"text","text":"The low-light enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}],"url":"\/documentation\/agorartckit\/agoralowlightenhanceoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLowlightEnhanceOptions:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLowlightEnhanceOptions:options:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLowlightEnhanceOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions","preciseIdentifier":"c:objc(cs)AgoraLowlightEnhanceOptions","text":"AgoraLowlightEnhanceOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLowlightEnhanceOptions(_:options:)\/title","value":"setLowlightEnhanceOptions:options:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLowlightEnhanceOptions(_:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLowlightEnhanceOptions:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions\/title","value":"AgoraLowlightEnhanceOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}