{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVoiceEqualizationOf"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bandFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency","preciseIdentifier":"c:@E@AgoraAudioEqualizationBandFrequency","text":"AgoraAudioEqualizationBandFrequency"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withGain"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"bandFrequency","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The band frequency. The value ranges between 0 and 9; representing the respective 10-band center frequencies of the voice effects, including 31, 62, 125, 250, 500, 1k, 2k, 4k, 8k, and 16k Hz. See AgoraAudioEqualizationBandFrequency."}]}]},{"name":"gain","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The gain of each band in dB. The value ranges between -15 and 15. The default value is 0."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can call this method either before or after joining a channel."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalvoiceequalizationof(_:withgain:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalvoiceequalizationof(_:withgain:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalVoiceEqualizationOf(_:withGain:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the local voice equalization effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVoiceEqualizationOf"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioEqualizationBandFrequency","preciseIdentifier":"c:@E@AgoraAudioEqualizationBandFrequency"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withGain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setLocalVoiceEqualizationOf(_:withGain:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setLocalVoiceEqualizationOfBandFrequency:withGain:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setLocalVoiceEqualizationOfBandFrequency:withGain:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"abstract":[{"type":"text","text":"The midrange frequency for audio equalization."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setLocalVoiceEqualizationOf(_:withGain:)":{"role":"symbol","title":"setLocalVoiceEqualizationOf(_:withGain:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVoiceEqualizationOf"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioEqualizationBandFrequency","preciseIdentifier":"c:@E@AgoraAudioEqualizationBandFrequency"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withGain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the local voice equalization effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalVoiceEqualizationOf(_:withGain:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLocalVoiceEqualizationOfBandFrequency:withGain:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setlocalvoiceequalizationof(_:withgain:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLocalVoiceEqualizationOfBandFrequency:withGain:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalVoiceEqualizationOfBandFrequency:withGain:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLocalVoiceEqualizationOfBandFrequency:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency","preciseIdentifier":"c:@E@AgoraAudioEqualizationBandFrequency","text":"AgoraAudioEqualizationBandFrequency"},{"kind":"text","text":")"},{"kind":"internalParam","text":"bandFrequency"},{"kind":"text","text":" "},{"kind":"identifier","text":"withGain:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"gain"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency\/title","value":"AgoraAudioEqualizationBandFrequency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalVoiceEqualizationOf(_:withGain:)\/title","value":"setLocalVoiceEqualizationOfBandFrequency:withGain:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalVoiceEqualizationOf(_:withGain:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalVoiceEqualizationOfBandFrequency:withGain:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}