{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogFileSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileSizeInKBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fileSizeInKBytes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size (KB) of an agorasdk.log file. The"},{"type":"text","text":" "},{"type":"text","text":"value range is [128,20480]. The default value is 1,024 KB. If you set"},{"type":"text","text":" "},{"type":"text","text":"fileSizeInKByte smaller than 128 KB, the SDK automatically adjusts it to 128"},{"type":"text","text":" "},{"type":"text","text":"KB; if you set fileSizeInKByte greater than 20,480 KB, the SDK automatically"},{"type":"text","text":" "},{"type":"text","text":"adjusts it to 20,480 KB."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlogfilesize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlogfilesize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLogFileSize(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the log file size."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Use the logConfig parameter in sharedEngineWithConfig instead.By"},{"type":"text","text":" "},{"type":"text","text":"default, the SDK generates five SDK log files and five API call log files"},{"type":"text","text":" "},{"type":"text","text":"with the following rules:The SDK log files are: agorasdk.log, agorasdk.1.log,"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.2.log, agorasdk.3.log, and agorasdk.4.log.The API call log files"},{"type":"text","text":" "},{"type":"text","text":"are: agoraapi.log, agoraapi.1.log, agoraapi.2.log, agoraapi.3.log, and"},{"type":"text","text":" "},{"type":"text","text":"agoraapi.4.log.The default size for each SDK log file is 1,024 KB; the"},{"type":"text","text":" "},{"type":"text","text":"default size for each API call log file is 2,048 KB. These log files are"},{"type":"text","text":" "},{"type":"text","text":"encoded in UTF-8.The SDK writes the latest logs in agorasdk.log or"},{"type":"text","text":" "},{"type":"text","text":"agoraapi.log.When agorasdk.log is full, the SDK processes the log files in"},{"type":"text","text":" "},{"type":"text","text":"the following order:Delete the agorasdk.4.log file (if any).Rename"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.3.log to agorasdk.4.log.Rename agorasdk.2.log to"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.3.log.Rename agorasdk.1.log to agorasdk.2.log.Create a new"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.log file.The overwrite rules for the agoraapi.log file are the same"},{"type":"text","text":" "},{"type":"text","text":"as for agorasdk.log.This method is used to set the size of the agorasdk.log"},{"type":"text","text":" "},{"type":"text","text":"file only and does not effect the agoraapi.log file."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogFileSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setLogFileSize(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setLogFileSize:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setLogFileSize:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setLogFileSize(_:)":{"role":"symbol","title":"setLogFileSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogFileSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the log file size."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Use the logConfig parameter in sharedEngineWithConfig instead.By"},{"type":"text","text":" "},{"type":"text","text":"default, the SDK generates five SDK log files and five API call log files"},{"type":"text","text":" "},{"type":"text","text":"with the following rules:The SDK log files are: agorasdk.log, agorasdk.1.log,"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.2.log, agorasdk.3.log, and agorasdk.4.log.The API call log files"},{"type":"text","text":" "},{"type":"text","text":"are: agoraapi.log, agoraapi.1.log, agoraapi.2.log, agoraapi.3.log, and"},{"type":"text","text":" "},{"type":"text","text":"agoraapi.4.log.The default size for each SDK log file is 1,024 KB; the"},{"type":"text","text":" "},{"type":"text","text":"default size for each API call log file is 2,048 KB. These log files are"},{"type":"text","text":" "},{"type":"text","text":"encoded in UTF-8.The SDK writes the latest logs in agorasdk.log or"},{"type":"text","text":" "},{"type":"text","text":"agoraapi.log.When agorasdk.log is full, the SDK processes the log files in"},{"type":"text","text":" "},{"type":"text","text":"the following order:Delete the agorasdk.4.log file (if any).Rename"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.3.log to agorasdk.4.log.Rename agorasdk.2.log to"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.3.log.Rename agorasdk.1.log to agorasdk.2.log.Create a new"},{"type":"text","text":" "},{"type":"text","text":"agorasdk.log file.The overwrite rules for the agoraapi.log file are the same"},{"type":"text","text":" "},{"type":"text","text":"as for agorasdk.log.This method is used to set the size of the agorasdk.log"},{"type":"text","text":" "},{"type":"text","text":"file only and does not effect the agoraapi.log file."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLogFileSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLogFileSize:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setlogfilesize(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLogFileSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLogFileSize:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLogFileSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fileSizeInKBytes"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLogFileSize(_:)\/title","value":"setLogFileSize:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLogFileSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLogFileSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}