{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalRenderMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode","text":"AgoraVideoRenderMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The local video display mode. See AgoraVideoRenderMode."}]}]},{"name":"mirror","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mirror mode of the local video view. See AgoraVideoMirrorMode.If you use a front camera, the SDK enables the mirror mode by default; if you use a rear camera, the SDK disables the mirror mode by default."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After initializing the local video view, you can call this method to update its rendering and mirror modes. It affects only the video view that the local user sees, not the published local video stream. Ensure that you have called the setupLocalVideo method to initialize the local video view before calling this method. During a call, you can call this method as many times as necessary to update the display mode of the local video view."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalrendermode(_:mirror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalrendermode(_:mirror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalRenderMode(_:mirror:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates the display mode of the local video view."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalRenderMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setLocalRenderMode(_:mirror:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setLocalRenderMode:mirror:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setLocalRenderMode:mirror:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"seeAlsoSections":[{"title":"Video Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableVideo()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfiguration(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/stopPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteRenderMode(_:mode:mirror:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStream(_:type:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalVideoStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteVideoStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteVideoStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableInstantMediaRendering()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startMediaRenderingTracing()"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/disableVideo()":{"role":"symbol","title":"disableVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Disables the video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableVideo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableVideo"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/disablevideo()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startPreview()":{"role":"symbol","title":"startPreview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPreview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the local video preview."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startPreview"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startpreview()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableVideo()":{"role":"symbol","title":"enableVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableVideo"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablevideo()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVideoEncoderConfiguration(_:)":{"role":"symbol","title":"setVideoEncoderConfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoEncoderConfiguration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoEncoderConfiguration","preciseIdentifier":"c:objc(cs)AgoraVideoEncoderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the video encoder configuration."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfiguration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoEncoderConfiguration:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvideoencoderconfiguration(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableInstantMediaRendering()":{"role":"symbol","title":"enableInstantMediaRendering()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableInstantMediaRendering"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables audio and video frame instant rendering."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableInstantMediaRendering()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableInstantMediaRendering"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enableinstantmediarendering()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setLocalRenderMode(_:mirror:)":{"role":"symbol","title":"setLocalRenderMode(_:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalRenderMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the display mode of the local video view."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalRenderMode(_:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLocalRenderMode:mirror:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setlocalrendermode(_:mirror:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteVideoStream(_:type:)":{"role":"symbol","title":"setRemoteVideoStream(_:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the stream type of the remote video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStream(_:type:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoStream:type:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremotevideostream(_:type:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoMirrorMode":{"role":"symbol","title":"AgoraVideoMirrorMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"abstract":[{"type":"text","text":"Video mirror mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"url":"\/documentation\/agorartckit\/agoravideomirrormode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setupLocalVideo(_:)":{"role":"symbol","title":"setupLocalVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLocalVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Initializes the local video view."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLocalVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setuplocalvideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/stopPreview()":{"role":"symbol","title":"stopPreview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopPreview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops the local video preview."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/stopPreview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopPreview"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/stoppreview()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteLocalVideoStream(_:)":{"role":"symbol","title":"muteLocalVideoStream(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteLocalVideoStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes publishing the local video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalVideoStream(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteLocalVideoStream:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/mutelocalvideostream(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteAllRemoteVideoStreams(_:)":{"role":"symbol","title":"muteAllRemoteVideoStreams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteVideoStreams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the video streams of all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteVideoStreams(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteAllRemoteVideoStreams:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteallremotevideostreams(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startMediaRenderingTracing()":{"role":"symbol","title":"startMediaRenderingTracing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startMediaRenderingTracing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables tracing the video frame rendering process."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startMediaRenderingTracing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startMediaRenderingTracing"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startmediarenderingtracing()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteRenderMode(_:mode:mirror:)":{"role":"symbol","title":"setRemoteRenderMode(_:mode:mirror:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteRenderMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the display mode of the video view of a remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteRenderMode(_:mode:mirror:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteRenderMode:mode:mirror:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremoterendermode(_:mode:mirror:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode":{"role":"symbol","title":"AgoraVideoRenderMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderMode"}],"url":"\/documentation\/agorartckit\/agoravideorendermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableLocalVideo(_:)":{"role":"symbol","title":"enableLocalVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableLocalVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables\/Disables the local video capture."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableLocalVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablelocalvideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setupRemoteVideo(_:)":{"role":"symbol","title":"setupRemoteVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupRemoteVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Initializes the video view of a remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupRemoteVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setupremotevideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/muteRemoteVideoStream(_:mute:)":{"role":"symbol","title":"muteRemoteVideoStream(_:mute:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteRemoteVideoStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the video stream of a specified user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteVideoStream(_:mute:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteRemoteVideoStream:mute:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/muteremotevideostream(_:mute:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLocalRenderMode:mirror:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalRenderMode:mirror:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Video Management","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/disableVideo()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfiguration(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/stopPreview()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteRenderMode(_:mode:mirror:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStream(_:type:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteLocalVideoStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteRemoteVideoStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/muteAllRemoteVideoStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableInstantMediaRendering()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startMediaRenderingTracing()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLocalRenderMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode","text":"AgoraVideoRenderMode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirror:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"mirror"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableVideo()\/title","value":"disableVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1disableVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disableVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startPreview()\/title","value":"startPreview"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startPreview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideo()\/title","value":"enableVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoEncoderConfiguration(_:)\/title","value":"setVideoEncoderConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoEncoderConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoEncoderConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableInstantMediaRendering()\/title","value":"enableInstantMediaRendering"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableInstantMediaRendering()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableInstantMediaRendering"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalRenderMode(_:mirror:)\/title","value":"setLocalRenderMode:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalRenderMode(_:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalRenderMode:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoStream(_:type:)\/title","value":"setRemoteVideoStream:type:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoStream(_:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoStream:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/title","value":"AgoraVideoMirrorMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupLocalVideo(_:)\/title","value":"setupLocalVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupLocalVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLocalVideo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1stopPreview()\/title","value":"stopPreview"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1stopPreview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalVideoStream(_:)\/title","value":"muteLocalVideoStream:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteLocalVideoStream(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteLocalVideoStream:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteVideoStreams(_:)\/title","value":"muteAllRemoteVideoStreams:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteAllRemoteVideoStreams(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteAllRemoteVideoStreams:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startMediaRenderingTracing()\/title","value":"startMediaRenderingTracing"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startMediaRenderingTracing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startMediaRenderingTracing"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteRenderMode(_:mode:mirror:)\/title","value":"setRemoteRenderMode:mode:mirror:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteRenderMode(_:mode:mirror:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteRenderMode:mode:mirror:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/title","value":"AgoraVideoRenderMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalVideo(_:)\/title","value":"enableLocalVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableLocalVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableLocalVideo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideo(_:)\/title","value":"setupRemoteVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupRemoteVideo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteVideoStream(_:mute:)\/title","value":"muteRemoteVideoStream:mute:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1muteRemoteVideoStream(_:mute:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteRemoteVideoStream:mute:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}