{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVideoMirrorMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The local video mirror mode. See AgoraVideoMirrorMode ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalvideomirrormode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setlocalvideomirrormode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalVideoMirrorMode(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the local video mirror mode."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated.Use setupLocalVideo or"},{"type":"text","text":" "},{"type":"text","text":"setLocalRenderMode [2\/2] instead."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setLocalVideoMirrorMode:"}],"role":"symbol","title":"setLocalVideoMirrorMode(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVideoMirrorMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setLocalVideoMirrorMode:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setLocalVideoMirrorMode(_:)":{"deprecated":true,"role":"symbol","title":"setLocalVideoMirrorMode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLocalVideoMirrorMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the local video mirror mode."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated.Use setupLocalVideo or"},{"type":"text","text":" "},{"type":"text","text":"setLocalRenderMode [2\/2] instead."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setLocalVideoMirrorMode(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLocalVideoMirrorMode:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setlocalvideomirrormode(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoMirrorMode":{"role":"symbol","title":"AgoraVideoMirrorMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"abstract":[{"type":"text","text":"Video mirror mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"url":"\/documentation\/agorartckit\/agoravideomirrormode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLocalVideoMirrorMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalVideoMirrorMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setLocalVideoMirrorMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalVideoMirrorMode(_:)\/title","value":"setLocalVideoMirrorMode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setLocalVideoMirrorMode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setLocalVideoMirrorMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/title","value":"AgoraVideoMirrorMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}