{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaMetadataDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"metadataDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDelegate","preciseIdentifier":"c:objc(pl)AgoraMediaMetadataDelegate","text":"AgoraMediaMetadataDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType","text":"AgoraMetadataType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The metadata observer. See AgoraMediaMetadataDelegate."}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The metadata type. The SDK currently only supports AgoraMetadataTypeVideo. See AgoraMetadataType."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to implement the AgoraMediaMetadataDelegate class and specify the metadata type in this method. This method enables you to add synchronized metadata in the video stream for more diversified"},{"type":"text","text":" "},{"type":"text","text":"live interactive streaming, such as sending shopping links, digital coupons, and online quizzes. A successful call of this method triggers the metadataMaxSize callback. Call this method before joinChannelByToken [2\/4] ."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setmediametadatadelegate(_:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setmediametadatadelegate(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setMediaMetadataDelegate(_:with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Registers the metadata observer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaMetadataDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaMetadataDelegate","preciseIdentifier":"c:objc(pl)AgoraMediaMetadataDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"setMediaMetadataDelegate(_:with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setMediaMetadataDelegate:withType:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setMediaMetadataDelegate:withType:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMetadataType":{"role":"symbol","title":"AgoraMetadataType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMetadataType"}],"abstract":[{"type":"text","text":"Metadata type of the observer. We only support video metadata for now."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMetadataType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMetadataType"}],"url":"\/documentation\/agorartckit\/agorametadatatype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaMetadataDelegate":{"role":"symbol","title":"AgoraMediaMetadataDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaMetadataDelegate"}],"abstract":[{"type":"text","text":"The metadata observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaMetadataDelegate"}],"url":"\/documentation\/agorartckit\/agoramediametadatadelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setMediaMetadataDelegate(_:with:)":{"role":"symbol","title":"setMediaMetadataDelegate(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaMetadataDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaMetadataDelegate","preciseIdentifier":"c:objc(pl)AgoraMediaMetadataDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Registers the metadata observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setMediaMetadataDelegate(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMediaMetadataDelegate:withType:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setmediametadatadelegate(_:with:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setMediaMetadataDelegate:withType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMediaMetadataDelegate:withType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMediaMetadataDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraMediaMetadataDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraMediaMetadataDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"metadataDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"withType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType","text":"AgoraMetadataType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMetadataType\/title","value":"AgoraMetadataType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMetadataType\/fragments","value":[{"kind":"identifier","text":"AgoraMetadataType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDelegate\/title","value":"AgoraMediaMetadataDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraMediaMetadataDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setMediaMetadataDelegate(_:with:)\/title","value":"setMediaMetadataDelegate:withType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setMediaMetadataDelegate(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMediaMetadataDelegate:withType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}