{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaMetadataDataSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"metadataDataSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource","preciseIdentifier":"c:objc(pl)AgoraMediaMetadataDataSource","text":"AgoraMediaMetadataDataSource"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType","text":"AgoraMetadataType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES : Success. NO : Failure."}]}]},{"kind":"parameters","parameters":[{"name":"metadataDataSource","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AgoraMediaMetadataDataSource protocol."}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The metadata type. The SDK currently only supports AgoraMetadataTypeVideo. See AgoraMetadataType."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to implement the AgoraMediaMetadataDataSource protocol in this method and specify the data format of the metadata. After a successful method call, the SDK triggers the metadataMaxSize callback. This method can be used with setMediaMetadataDelegate to add synchronized metadata in the video stream for more diversified live interactions, such as sending shopping links, digital coupons, and online quizzes. Call this method before joining a channel."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setmediametadatadatasource(_:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setmediametadatadatasource(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setMediaMetadataDataSource(_:with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the data source of the metadata."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaMetadataDataSource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaMetadataDataSource","preciseIdentifier":"c:objc(pl)AgoraMediaMetadataDataSource"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"setMediaMetadataDataSource(_:with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setMediaMetadataDataSource:withType:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setMediaMetadataDataSource:withType:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setMediaMetadataDataSource(_:with:)":{"role":"symbol","title":"setMediaMetadataDataSource(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaMetadataDataSource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaMetadataDataSource","preciseIdentifier":"c:objc(pl)AgoraMediaMetadataDataSource"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets the data source of the metadata."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setMediaMetadataDataSource(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMediaMetadataDataSource:withType:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setmediametadatadatasource(_:with:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMetadataType":{"role":"symbol","title":"AgoraMetadataType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMetadataType"}],"abstract":[{"type":"text","text":"Metadata type of the observer. We only support video metadata for now."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMetadataType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMetadataType"}],"url":"\/documentation\/agorartckit\/agorametadatatype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaMetadataDataSource":{"role":"symbol","title":"AgoraMediaMetadataDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}],"abstract":[{"type":"text","text":"AgoraMediaMetadataDataSource protocol."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}],"url":"\/documentation\/agorartckit\/agoramediametadatadatasource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setMediaMetadataDataSource:withType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMediaMetadataDataSource:withType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMediaMetadataDataSource:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraMediaMetadataDataSource>","preciseIdentifier":"c:Qoobjc(pl)AgoraMediaMetadataDataSource"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"metadataDataSource"},{"kind":"text","text":" "},{"kind":"identifier","text":"withType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMetadataType","preciseIdentifier":"c:@E@AgoraMetadataType","text":"AgoraMetadataType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setMediaMetadataDataSource(_:with:)\/title","value":"setMediaMetadataDataSource:withType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setMediaMetadataDataSource(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMediaMetadataDataSource:withType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMetadataType\/title","value":"AgoraMetadataType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMetadataType\/fragments","value":[{"kind":"identifier","text":"AgoraMetadataType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource\/title","value":"AgoraMediaMetadataDataSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource\/fragments","value":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}