{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode","text":"AgoraAudioRawFrameOperationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"samplesPerCall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"sampleRate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sample rate returned in the onPlaybackAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callback, which can be set as 8000, 16000, 32000, 44100, or 48000 Hz."}]}]},{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of channels returned in the"},{"type":"text","text":" "},{"type":"text","text":"onPlaybackAudioFrame callback:1: Mono.2: Stereo."}]}]},{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The use mode of the audio frame. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioRawFrameOperationMode ."}]}]},{"name":"samplesPerCall","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of data samples returned in the"},{"type":"text","text":" "},{"type":"text","text":"onPlaybackAudioFrame callback, such as 1024 for the Media Push."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setplaybackaudioframeparameterswithsamplerate(_:channel:mode:samplespercall:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setplaybackaudioframeparameterswithsamplerate(_:channel:mode:samplespercall:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setPlaybackAudioFrameParametersWithSampleRate(_:channel:mode:samplesPerCall:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the audio data format for playback."},{"type":"text","text":" "},{"type":"text","text":"Sets the data format for the onPlaybackAudioFrame callback.Ensure that you"},{"type":"text","text":" "},{"type":"text","text":"call this method before joining a channel.The SDK calculates the sampling"},{"type":"text","text":" "},{"type":"text","text":"interval based on the samplesPerCall, sampleRate and channel parameters set"},{"type":"text","text":" "},{"type":"text","text":"in this method.Sample interval (sec) = samplePerCall\/(sampleRate × channel)."},{"type":"text","text":" "},{"type":"text","text":"Ensure that the sample interval ≥ 0.01 (s). The SDK triggers the callback"},{"type":"text","text":" "},{"type":"text","text":"according to the sampling interval.onPlaybackAudioFrame"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"samplesPerCall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setPlaybackAudioFrameParametersWithSampleRate(_:channel:mode:samplesPerCall:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setPlaybackAudioFrameParametersWithSampleRate:channel:mode:samplesPerCall:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate:channel:mode:samplesPerCall:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRawFrameOperationMode":{"role":"symbol","title":"AgoraAudioRawFrameOperationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRawFrameOperationMode"}],"abstract":[{"type":"text","text":"The use mode of the audio data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRawFrameOperationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRawFrameOperationMode"}],"url":"\/documentation\/agorartckit\/agoraaudiorawframeoperationmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setPlaybackAudioFrameParametersWithSampleRate(_:channel:mode:samplesPerCall:)":{"role":"symbol","title":"setPlaybackAudioFrameParametersWithSampleRate(_:channel:mode:samplesPerCall:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"samplesPerCall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the audio data format for playback."},{"type":"text","text":" "},{"type":"text","text":"Sets the data format for the onPlaybackAudioFrame callback.Ensure that you"},{"type":"text","text":" "},{"type":"text","text":"call this method before joining a channel.The SDK calculates the sampling"},{"type":"text","text":" "},{"type":"text","text":"interval based on the samplesPerCall, sampleRate and channel parameters set"},{"type":"text","text":" "},{"type":"text","text":"in this method.Sample interval (sec) = samplePerCall\/(sampleRate × channel)."},{"type":"text","text":" "},{"type":"text","text":"Ensure that the sample interval ≥ 0.01 (s). The SDK triggers the callback"},{"type":"text","text":" "},{"type":"text","text":"according to the sampling interval.onPlaybackAudioFrame"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setPlaybackAudioFrameParametersWithSampleRate(_:channel:mode:samplesPerCall:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate:channel:mode:samplesPerCall:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setplaybackaudioframeparameterswithsamplerate(_:channel:mode:samplespercall:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setPlaybackAudioFrameParametersWithSampleRate:channel:mode:samplesPerCall:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate:channel:mode:samplesPerCall:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sampleRate"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode","text":"AgoraAudioRawFrameOperationMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":"samplesPerCall:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"samplesPerCall"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRawFrameOperationMode\/title","value":"AgoraAudioRawFrameOperationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRawFrameOperationMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRawFrameOperationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setPlaybackAudioFrameParametersWithSampleRate(_:channel:mode:samplesPerCall:)\/title","value":"setPlaybackAudioFrameParametersWithSampleRate:channel:mode:samplesPerCall:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setPlaybackAudioFrameParametersWithSampleRate(_:channel:mode:samplesPerCall:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPlaybackAudioFrameParametersWithSampleRate:channel:mode:samplesPerCall:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}