{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoStreamEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":" "},{"kind":"internalParam","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType","text":"AgoraVideoStreamType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID."}]}]},{"name":"streamType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video stream type: AgoraVideoStreamType ."}]}]},{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevideostreamex(_:type:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevideostreamex(_:type:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStreamEx(_:type:connection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the stream type of the remote video."},{"type":"text","text":" "},{"type":"text","text":"Under limited network conditions, if the publisher has not disabled the"},{"type":"text","text":" "},{"type":"text","text":"dual-stream mode using enableDualStreamModeEx (NO), the receiver can choose"},{"type":"text","text":" "},{"type":"text","text":"to receive either the high-quality video stream or the low-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream. The high-quality video stream has a higher resolution and bitrate,"},{"type":"text","text":" "},{"type":"text","text":"and the low-quality video stream has a lower resolution and bitrate.By"},{"type":"text","text":" "},{"type":"text","text":"default, users receive the high-quality video stream. Call this method if you"},{"type":"text","text":" "},{"type":"text","text":"want to switch to the low-quality video stream. This method allows the app to"},{"type":"text","text":" "},{"type":"text","text":"adjust the corresponding video stream type based on the size of the video"},{"type":"text","text":" "},{"type":"text","text":"window to reduce the bandwidth and resources. The aspect ratio of the"},{"type":"text","text":" "},{"type":"text","text":"low-quality video stream is the same as the high-quality video stream. Once"},{"type":"text","text":" "},{"type":"text","text":"the resolution of the high-quality video stream is set, the system"},{"type":"text","text":" "},{"type":"text","text":"automatically sets the resolution, frame rate, and bitrate of the low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream.The SDK enables the low-quality video stream auto mode on the"},{"type":"text","text":" "},{"type":"text","text":"sender by default (not actively sending low-quality video streams). The host"},{"type":"text","text":" "},{"type":"text","text":"at the receiving end can call this method to initiate a low-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream stream request on the receiving end, and the sender automatically"},{"type":"text","text":" "},{"type":"text","text":"switches to the low-quality video stream mode after receiving the request.The"},{"type":"text","text":" "},{"type":"text","text":"result of this method returns in the didApiCallExecute callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoStreamEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setRemoteVideoStreamEx(_:type:connection:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setRemoteVideoStreamEx:type:connection:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoStreamEx:type:connection:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoStreamType":{"role":"symbol","title":"AgoraVideoStreamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoStreamType"}],"abstract":[{"type":"text","text":"The type of video streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoStreamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoStreamType"}],"url":"\/documentation\/agorartckit\/agoravideostreamtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteVideoStreamEx(_:type:connection:)":{"role":"symbol","title":"setRemoteVideoStreamEx(_:type:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoStreamEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the stream type of the remote video."},{"type":"text","text":" "},{"type":"text","text":"Under limited network conditions, if the publisher has not disabled the"},{"type":"text","text":" "},{"type":"text","text":"dual-stream mode using enableDualStreamModeEx (NO), the receiver can choose"},{"type":"text","text":" "},{"type":"text","text":"to receive either the high-quality video stream or the low-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream. The high-quality video stream has a higher resolution and bitrate,"},{"type":"text","text":" "},{"type":"text","text":"and the low-quality video stream has a lower resolution and bitrate.By"},{"type":"text","text":" "},{"type":"text","text":"default, users receive the high-quality video stream. Call this method if you"},{"type":"text","text":" "},{"type":"text","text":"want to switch to the low-quality video stream. This method allows the app to"},{"type":"text","text":" "},{"type":"text","text":"adjust the corresponding video stream type based on the size of the video"},{"type":"text","text":" "},{"type":"text","text":"window to reduce the bandwidth and resources. The aspect ratio of the"},{"type":"text","text":" "},{"type":"text","text":"low-quality video stream is the same as the high-quality video stream. Once"},{"type":"text","text":" "},{"type":"text","text":"the resolution of the high-quality video stream is set, the system"},{"type":"text","text":" "},{"type":"text","text":"automatically sets the resolution, frame rate, and bitrate of the low-quality"},{"type":"text","text":" "},{"type":"text","text":"video stream.The SDK enables the low-quality video stream auto mode on the"},{"type":"text","text":" "},{"type":"text","text":"sender by default (not actively sending low-quality video streams). The host"},{"type":"text","text":" "},{"type":"text","text":"at the receiving end can call this method to initiate a low-quality video"},{"type":"text","text":" "},{"type":"text","text":"stream stream request on the receiving end, and the sender automatically"},{"type":"text","text":" "},{"type":"text","text":"switches to the low-quality video stream mode after receiving the request.The"},{"type":"text","text":" "},{"type":"text","text":"result of this method returns in the didApiCallExecute callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoStreamEx(_:type:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoStreamEx:type:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremotevideostreamex(_:type:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setRemoteVideoStreamEx:type:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoStreamEx:type:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRemoteVideoStreamEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType","text":"AgoraVideoStreamType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"streamType"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoStreamType\/title","value":"AgoraVideoStreamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoStreamType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoStreamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoStreamEx(_:type:connection:)\/title","value":"setRemoteVideoStreamEx:type:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoStreamEx(_:type:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoStreamEx:type:connection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}