{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions","text":"AgoraVideoSubscriptionOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID of the remote user."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video subscription options. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoSubscriptionOptions ."}]}]},{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevideosubscriptionoptionsex(_:options:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevideosubscriptionoptionsex(_:options:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoSubscriptionOptionsEx(_:options:connection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Options for subscribing to remote video streams."},{"type":"text","text":" "},{"type":"text","text":"When a remote user has enabled dual-stream mode, you can call this method to"},{"type":"text","text":" "},{"type":"text","text":"choose the option for subscribing to the video streams sent by the remote"},{"type":"text","text":" "},{"type":"text","text":"user."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx:options:connection:"}],"role":"symbol","title":"setRemoteVideoSubscriptionOptionsEx(_:options:connection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setRemoteVideoSubscriptionOptionsEx:options:connection:","extendedModule":"AgoraRtcKit","modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSubscriptionOptions":{"role":"symbol","title":"AgoraVideoSubscriptionOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}],"url":"\/documentation\/agorartckit\/agoravideosubscriptionoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteVideoSubscriptionOptionsEx(_:options:connection:)":{"role":"symbol","title":"setRemoteVideoSubscriptionOptionsEx(_:options:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Options for subscribing to remote video streams."},{"type":"text","text":" "},{"type":"text","text":"When a remote user has enabled dual-stream mode, you can call this method to"},{"type":"text","text":" "},{"type":"text","text":"choose the option for subscribing to the video streams sent by the remote"},{"type":"text","text":" "},{"type":"text","text":"user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoSubscriptionOptionsEx(_:options:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx:options:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremotevideosubscriptionoptionsex(_:options:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setRemoteVideoSubscriptionOptionsEx:options:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx:options:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions","text":"AgoraVideoSubscriptionOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions\/title","value":"AgoraVideoSubscriptionOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoSubscriptionOptionsEx(_:options:connection:)\/title","value":"setRemoteVideoSubscriptionOptionsEx:options:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoSubscriptionOptionsEx(_:options:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptionsEx:options:connection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}