{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVoicePosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID of the remote user."}]}]},{"name":"pan","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The voice position of the remote user. The value ranges from"},{"type":"text","text":" "},{"type":"text","text":"-1.0 to 1.0:0.0: (Default) The remote voice comes from the front.-1.0: The"},{"type":"text","text":" "},{"type":"text","text":"remote voice comes from the left.1.0: The remote voice comes from the right."}]}]},{"name":"gain","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The volume of the remote user. The value ranges from 0.0 to"},{"type":"text","text":" "},{"type":"text","text":"100.0. The default value is 100.0 (the original volume of the remote user)."},{"type":"text","text":" "},{"type":"text","text":"The smaller the value, the lower the volume."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevoiceposition(_:pan:gain:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevoiceposition(_:pan:gain:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVoicePosition(_:pan:gain:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the 2D position (the position on the horizontal plane) of the remote"},{"type":"text","text":" "},{"type":"text","text":"user’s voice. This method sets the 2D position and volume of a remote user,"},{"type":"text","text":" "},{"type":"text","text":"so that the local user can easily hear and identify the remote user’s"},{"type":"text","text":" "},{"type":"text","text":"position.When the local user calls this method to set the voice position of a"},{"type":"text","text":" "},{"type":"text","text":"remote user, the voice difference between the left and right channels allows"},{"type":"text","text":" "},{"type":"text","text":"the local user to track the real-time position of the remote user, creating a"},{"type":"text","text":" "},{"type":"text","text":"sense of space. This method applies to massive multiplayer online games, such"},{"type":"text","text":" "},{"type":"text","text":"as Battle Royale games.For this method to work, enable stereo panning for"},{"type":"text","text":" "},{"type":"text","text":"remote users by calling the enableSoundPositionIndication method before"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.For the best voice positioning, Agora recommends using a"},{"type":"text","text":" "},{"type":"text","text":"wired headset.Call this method after joining a channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVoicePosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setRemoteVoicePosition(_:pan:gain:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setRemoteVoicePosition:pan:gain:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setRemoteVoicePosition:pan:gain:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteVoicePosition(_:pan:gain:)":{"role":"symbol","title":"setRemoteVoicePosition(_:pan:gain:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVoicePosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the 2D position (the position on the horizontal plane) of the remote"},{"type":"text","text":" "},{"type":"text","text":"user’s voice. This method sets the 2D position and volume of a remote user,"},{"type":"text","text":" "},{"type":"text","text":"so that the local user can easily hear and identify the remote user’s"},{"type":"text","text":" "},{"type":"text","text":"position.When the local user calls this method to set the voice position of a"},{"type":"text","text":" "},{"type":"text","text":"remote user, the voice difference between the left and right channels allows"},{"type":"text","text":" "},{"type":"text","text":"the local user to track the real-time position of the remote user, creating a"},{"type":"text","text":" "},{"type":"text","text":"sense of space. This method applies to massive multiplayer online games, such"},{"type":"text","text":" "},{"type":"text","text":"as Battle Royale games.For this method to work, enable stereo panning for"},{"type":"text","text":" "},{"type":"text","text":"remote users by calling the enableSoundPositionIndication method before"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.For the best voice positioning, Agora recommends using a"},{"type":"text","text":" "},{"type":"text","text":"wired headset.Call this method after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVoicePosition(_:pan:gain:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteVoicePosition:pan:gain:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremotevoiceposition(_:pan:gain:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setRemoteVoicePosition:pan:gain:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVoicePosition:pan:gain:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRemoteVoicePosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"pan:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pan"},{"kind":"text","text":" "},{"kind":"identifier","text":"gain:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gain"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVoicePosition(_:pan:gain:)\/title","value":"setRemoteVoicePosition:pan:gain:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVoicePosition(_:pan:gain:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVoicePosition:pan:gain:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}