{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteUserSpatialAudioParams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioParams","text":"AgoraSpatialAudioParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID. This parameter must be the same as the user ID"},{"type":"text","text":" "},{"type":"text","text":"passed in when the user joined the channel."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The spatial audio parameters. See AgoraSpatialAudioParams"},{"type":"text","text":" "},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremoteuserspatialaudioparams(_:params:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremoteuserspatialaudioparams(_:params:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteUserSpatialAudioParams(_:params:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the spatial audio effect parameters of the remote user."},{"type":"text","text":" "},{"type":"text","text":"Call this method after enableSpatialAudio . After successfully setting the"},{"type":"text","text":" "},{"type":"text","text":"spatial audio effect parameters of the remote user, the local user can hear"},{"type":"text","text":" "},{"type":"text","text":"the remote user with a sense of space."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteUserSpatialAudioParams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSpatialAudioParams","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setRemoteUserSpatialAudioParams(_:params:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setRemoteUserSpatialAudioParams:params:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setRemoteUserSpatialAudioParams:params:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteUserSpatialAudioParams(_:params:)":{"role":"symbol","title":"setRemoteUserSpatialAudioParams(_:params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteUserSpatialAudioParams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraSpatialAudioParams","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioParams"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the spatial audio effect parameters of the remote user."},{"type":"text","text":" "},{"type":"text","text":"Call this method after enableSpatialAudio . After successfully setting the"},{"type":"text","text":" "},{"type":"text","text":"spatial audio effect parameters of the remote user, the local user can hear"},{"type":"text","text":" "},{"type":"text","text":"the remote user with a sense of space."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteUserSpatialAudioParams(_:params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteUserSpatialAudioParams:params:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremoteuserspatialaudioparams(_:params:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams":{"role":"symbol","title":"AgoraSpatialAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"abstract":[{"type":"text","text":"The spatial audio parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setRemoteUserSpatialAudioParams:params:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteUserSpatialAudioParams:params:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRemoteUserSpatialAudioParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioParams","text":"AgoraSpatialAudioParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"params"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteUserSpatialAudioParams(_:params:)\/title","value":"setRemoteUserSpatialAudioParams:params:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteUserSpatialAudioParams(_:params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteUserSpatialAudioParams:params:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/title","value":"AgoraSpatialAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}