{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions","text":"AgoraVideoSubscriptionOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID of the remote user."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video subscription options. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoSubscriptionOptions ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevideosubscriptionoptions(_:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setremotevideosubscriptionoptions(_:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoSubscriptionOptions(_:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Options for subscribing to remote video streams."},{"type":"text","text":" "},{"type":"text","text":"When a remote user has enabled dual-stream mode, you can call this method to"},{"type":"text","text":" "},{"type":"text","text":"choose the option for subscribing to the video streams sent by the remote"},{"type":"text","text":" "},{"type":"text","text":"user.If you only register one AgoraVideoFrameDelegate object, the SDK"},{"type":"text","text":" "},{"type":"text","text":"subscribes to the raw video data and encoded video data by default (the"},{"type":"text","text":" "},{"type":"text","text":"effect is equivalent to setting encodedFrameOnly to NO).If you only register"},{"type":"text","text":" "},{"type":"text","text":"one AgoraEncodedVideoFrameDelegate object, the SDK only subscribes to the"},{"type":"text","text":" "},{"type":"text","text":"encoded video data by default (the effect is equivalent to setting"},{"type":"text","text":" "},{"type":"text","text":"encodedFrameOnly to YES).If you register one AgoraVideoFrameDelegate object"},{"type":"text","text":" "},{"type":"text","text":"and one AgoraEncodedVideoFrameDelegate object successively, the SDK"},{"type":"text","text":" "},{"type":"text","text":"subscribes to the encoded video data by default (the effect is equivalent to"},{"type":"text","text":" "},{"type":"text","text":"setting encodedFrameOnly to NO).If you call this method first with the"},{"type":"text","text":" "},{"type":"text","text":"options parameter set, and then register one AgoraVideoFrameDelegate or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncodedVideoFrameDelegate object, you need to call this method again and"},{"type":"text","text":" "},{"type":"text","text":"set the options parameter as described in the above two items to get the"},{"type":"text","text":" "},{"type":"text","text":"desired results.Agora recommends the following steps:Set autoSubscribeVideo"},{"type":"text","text":" "},{"type":"text","text":"to NO when calling joinChannelByToken [2\/4] to join a channel.Call this"},{"type":"text","text":" "},{"type":"text","text":"method after receiving the didJoinedOfUid callback to set the subscription"},{"type":"text","text":" "},{"type":"text","text":"options for the specified remote user’s video stream.Call the"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteVideoStream method to resume subscribing to the video stream of the"},{"type":"text","text":" "},{"type":"text","text":"specified remote user. If you set encodedFrameOnly to YES in the previous"},{"type":"text","text":" "},{"type":"text","text":"step, the SDK triggers the onEncodedVideoFrameReceived callback locally to"},{"type":"text","text":" "},{"type":"text","text":"report the received encoded video frame information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setRemoteVideoSubscriptionOptions(_:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setRemoteVideoSubscriptionOptions:options:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions:options:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setRemoteVideoSubscriptionOptions(_:options:)":{"role":"symbol","title":"setRemoteVideoSubscriptionOptions(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Options for subscribing to remote video streams."},{"type":"text","text":" "},{"type":"text","text":"When a remote user has enabled dual-stream mode, you can call this method to"},{"type":"text","text":" "},{"type":"text","text":"choose the option for subscribing to the video streams sent by the remote"},{"type":"text","text":" "},{"type":"text","text":"user.If you only register one AgoraVideoFrameDelegate object, the SDK"},{"type":"text","text":" "},{"type":"text","text":"subscribes to the raw video data and encoded video data by default (the"},{"type":"text","text":" "},{"type":"text","text":"effect is equivalent to setting encodedFrameOnly to NO).If you only register"},{"type":"text","text":" "},{"type":"text","text":"one AgoraEncodedVideoFrameDelegate object, the SDK only subscribes to the"},{"type":"text","text":" "},{"type":"text","text":"encoded video data by default (the effect is equivalent to setting"},{"type":"text","text":" "},{"type":"text","text":"encodedFrameOnly to YES).If you register one AgoraVideoFrameDelegate object"},{"type":"text","text":" "},{"type":"text","text":"and one AgoraEncodedVideoFrameDelegate object successively, the SDK"},{"type":"text","text":" "},{"type":"text","text":"subscribes to the encoded video data by default (the effect is equivalent to"},{"type":"text","text":" "},{"type":"text","text":"setting encodedFrameOnly to NO).If you call this method first with the"},{"type":"text","text":" "},{"type":"text","text":"options parameter set, and then register one AgoraVideoFrameDelegate or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncodedVideoFrameDelegate object, you need to call this method again and"},{"type":"text","text":" "},{"type":"text","text":"set the options parameter as described in the above two items to get the"},{"type":"text","text":" "},{"type":"text","text":"desired results.Agora recommends the following steps:Set autoSubscribeVideo"},{"type":"text","text":" "},{"type":"text","text":"to NO when calling joinChannelByToken [2\/4] to join a channel.Call this"},{"type":"text","text":" "},{"type":"text","text":"method after receiving the didJoinedOfUid callback to set the subscription"},{"type":"text","text":" "},{"type":"text","text":"options for the specified remote user’s video stream.Call the"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteVideoStream method to resume subscribing to the video stream of the"},{"type":"text","text":" "},{"type":"text","text":"specified remote user. If you set encodedFrameOnly to YES in the previous"},{"type":"text","text":" "},{"type":"text","text":"step, the SDK triggers the onEncodedVideoFrameReceived callback locally to"},{"type":"text","text":" "},{"type":"text","text":"report the received encoded video frame information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setRemoteVideoSubscriptionOptions(_:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions:options:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setremotevideosubscriptionoptions(_:options:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSubscriptionOptions":{"role":"symbol","title":"AgoraVideoSubscriptionOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}],"url":"\/documentation\/agorartckit\/agoravideosubscriptionoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setRemoteVideoSubscriptionOptions:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions:options:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions","preciseIdentifier":"c:objc(cs)AgoraVideoSubscriptionOptions","text":"AgoraVideoSubscriptionOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoSubscriptionOptions(_:options:)\/title","value":"setRemoteVideoSubscriptionOptions:options:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setRemoteVideoSubscriptionOptions(_:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteVideoSubscriptionOptions:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions\/title","value":"AgoraVideoSubscriptionOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}