{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubscribeAudioAllowlist"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"allowlist"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setsubscribeaudioallowlist(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setsubscribeaudioallowlist(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeAudioAllowlist(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the allowlist of subscriptions for audio streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the audio streams of a user that you want"},{"type":"text","text":" "},{"type":"text","text":"to subscribe to.If a user is added in the allowlist and blocklist at the same"},{"type":"text","text":" "},{"type":"text","text":"time, only the blocklist takes effect.You can call this method either before"},{"type":"text","text":" "},{"type":"text","text":"or after joining a channel.The allowlist is not affected by the setting in"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteAudioStream , muteAllRemoteAudioStreams and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions .Once the allowlist of subscriptions is set, it"},{"type":"text","text":" "},{"type":"text","text":"is effective even if you leave the current channel and rejoin the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubscribeAudioAllowlist"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setSubscribeAudioAllowlist(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setSubscribeAudioAllowlist:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setSubscribeAudioAllowlist:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"seeAlsoSections":[{"title":"Subscribing to and publishing audio and video streams","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeAudioBlocklist(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeVideoBlocklist(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeVideoAllowlist(_:)"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setSubscribeAudioBlocklist(_:)":{"role":"symbol","title":"setSubscribeAudioBlocklist(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubscribeAudioBlocklist"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Set the blocklist of subscriptions for audio streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the audio streams of a user that you do"},{"type":"text","text":" "},{"type":"text","text":"not want to subscribe to.You can call this method either before or after"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.The blocklist is not affected by the setting in"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteAudioStream , muteAllRemoteAudioStreams , and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions .Once the blocklist of subscriptions is set, it"},{"type":"text","text":" "},{"type":"text","text":"is effective even if you leave the current channel and rejoin the channel.If"},{"type":"text","text":" "},{"type":"text","text":"a user is added in the allowlist and blocklist at the same time, only the"},{"type":"text","text":" "},{"type":"text","text":"blocklist takes effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeAudioBlocklist(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSubscribeAudioBlocklist:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setsubscribeaudioblocklist(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setSubscribeVideoBlocklist(_:)":{"role":"symbol","title":"setSubscribeVideoBlocklist(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubscribeVideoBlocklist"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Set the blocklist of subscriptions for video streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the video streams of a user that you do"},{"type":"text","text":" "},{"type":"text","text":"not want to subscribe to.If a user is added in the allowlist and blocklist at"},{"type":"text","text":" "},{"type":"text","text":"the same time, only the blocklist takes effect.Once the blocklist of"},{"type":"text","text":" "},{"type":"text","text":"subscriptions is set, it is effective even if you leave the current channel"},{"type":"text","text":" "},{"type":"text","text":"and rejoin the channel.You can call this method either before or after"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.The blocklist is not affected by the setting in"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteVideoStream , muteAllRemoteVideoStreams and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeVideoBlocklist(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSubscribeVideoBlocklist:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setsubscribevideoblocklist(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setSubscribeAudioAllowlist(_:)":{"role":"symbol","title":"setSubscribeAudioAllowlist(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubscribeAudioAllowlist"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the allowlist of subscriptions for audio streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the audio streams of a user that you want"},{"type":"text","text":" "},{"type":"text","text":"to subscribe to.If a user is added in the allowlist and blocklist at the same"},{"type":"text","text":" "},{"type":"text","text":"time, only the blocklist takes effect.You can call this method either before"},{"type":"text","text":" "},{"type":"text","text":"or after joining a channel.The allowlist is not affected by the setting in"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteAudioStream , muteAllRemoteAudioStreams and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions .Once the allowlist of subscriptions is set, it"},{"type":"text","text":" "},{"type":"text","text":"is effective even if you leave the current channel and rejoin the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeAudioAllowlist(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSubscribeAudioAllowlist:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setsubscribeaudioallowlist(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setSubscribeVideoAllowlist(_:)":{"role":"symbol","title":"setSubscribeVideoAllowlist(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSubscribeVideoAllowlist"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Set the allowlist of subscriptions for video streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the video streams of a user that you want"},{"type":"text","text":" "},{"type":"text","text":"to subscribe to.If a user is added in the allowlist and blocklist at the same"},{"type":"text","text":" "},{"type":"text","text":"time, only the blocklist takes effect.Once the allowlist of subscriptions is"},{"type":"text","text":" "},{"type":"text","text":"set, it is effective even if you leave the current channel and rejoin the"},{"type":"text","text":" "},{"type":"text","text":"channel.You can call this method either before or after joining a channel.The"},{"type":"text","text":" "},{"type":"text","text":"allowlist is not affected by the setting in muteRemoteVideoStream ,"},{"type":"text","text":" "},{"type":"text","text":"muteAllRemoteVideoStreams and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeVideoAllowlist(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSubscribeVideoAllowlist:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setsubscribevideoallowlist(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setSubscribeAudioAllowlist:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSubscribeAudioAllowlist:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Subscribing to and publishing audio and video streams","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeAudioBlocklist(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeVideoBlocklist(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setSubscribeVideoAllowlist(_:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSubscribeAudioAllowlist:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"allowlist"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeAudioBlocklist(_:)\/title","value":"setSubscribeAudioBlocklist:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeAudioBlocklist(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSubscribeAudioBlocklist:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeVideoBlocklist(_:)\/title","value":"setSubscribeVideoBlocklist:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeVideoBlocklist(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSubscribeVideoBlocklist:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeAudioAllowlist(_:)\/title","value":"setSubscribeAudioAllowlist:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeAudioAllowlist(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSubscribeAudioAllowlist:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeVideoAllowlist(_:)\/title","value":"setSubscribeVideoAllowlist:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setSubscribeVideoAllowlist(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSubscribeVideoAllowlist:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}