{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupRemoteVideoEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"remote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas","text":"AgoraRtcVideoCanvas"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"remote","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The remote video view settings. See AgoraRtcVideoCanvas ."}]}]},{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setupremotevideoex(_:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setupremotevideoex(_:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideoEx(_:connection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes the video view of a remote user."},{"type":"text","text":" "},{"type":"text","text":"This method initializes the video view of a remote stream on the local"},{"type":"text","text":" "},{"type":"text","text":"device. It affects only the video view that the local user sees. Call this"},{"type":"text","text":" "},{"type":"text","text":"method to bind the remote video stream to a video view and to set the"},{"type":"text","text":" "},{"type":"text","text":"rendering and mirror modes of the video view.The application specifies the"},{"type":"text","text":" "},{"type":"text","text":"uid of the remote video in the AgoraRtcVideoCanvas method before the remote"},{"type":"text","text":" "},{"type":"text","text":"user joins the channel.If the remote uid is unknown to the application, set"},{"type":"text","text":" "},{"type":"text","text":"it after the application receives the didJoinedOfUid callback. If the Video"},{"type":"text","text":" "},{"type":"text","text":"Recording function is enabled, the Video Recording Service joins the channel"},{"type":"text","text":" "},{"type":"text","text":"as a dummy client, causing other clients to also receive the onUserJoined"},{"type":"text","text":" "},{"type":"text","text":"callback. Do not bind the dummy client to the application view because the"},{"type":"text","text":" "},{"type":"text","text":"dummy client does not send any video streams.To unbind the remote user from"},{"type":"text","text":" "},{"type":"text","text":"the view, set the view parameter to NULL.Once the remote user leaves the"},{"type":"text","text":" "},{"type":"text","text":"channel, the SDK unbinds the remote user.To update the rendering or mirror"},{"type":"text","text":" "},{"type":"text","text":"mode of the remote video view during a call, use the setRemoteRenderModeEx"},{"type":"text","text":" "},{"type":"text","text":"method."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setupRemoteVideoEx:connection:"}],"role":"symbol","title":"setupRemoteVideoEx(_:connection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupRemoteVideoEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setupRemoteVideoEx:connection:","extendedModule":"AgoraRtcKit","modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setupRemoteVideoEx(_:connection:)":{"role":"symbol","title":"setupRemoteVideoEx(_:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupRemoteVideoEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Initializes the video view of a remote user."},{"type":"text","text":" "},{"type":"text","text":"This method initializes the video view of a remote stream on the local"},{"type":"text","text":" "},{"type":"text","text":"device. It affects only the video view that the local user sees. Call this"},{"type":"text","text":" "},{"type":"text","text":"method to bind the remote video stream to a video view and to set the"},{"type":"text","text":" "},{"type":"text","text":"rendering and mirror modes of the video view.The application specifies the"},{"type":"text","text":" "},{"type":"text","text":"uid of the remote video in the AgoraRtcVideoCanvas method before the remote"},{"type":"text","text":" "},{"type":"text","text":"user joins the channel.If the remote uid is unknown to the application, set"},{"type":"text","text":" "},{"type":"text","text":"it after the application receives the didJoinedOfUid callback. If the Video"},{"type":"text","text":" "},{"type":"text","text":"Recording function is enabled, the Video Recording Service joins the channel"},{"type":"text","text":" "},{"type":"text","text":"as a dummy client, causing other clients to also receive the onUserJoined"},{"type":"text","text":" "},{"type":"text","text":"callback. Do not bind the dummy client to the application view because the"},{"type":"text","text":" "},{"type":"text","text":"dummy client does not send any video streams.To unbind the remote user from"},{"type":"text","text":" "},{"type":"text","text":"the view, set the view parameter to NULL.Once the remote user leaves the"},{"type":"text","text":" "},{"type":"text","text":"channel, the SDK unbinds the remote user.To update the rendering or mirror"},{"type":"text","text":" "},{"type":"text","text":"mode of the remote video view during a call, use the setRemoteRenderModeEx"},{"type":"text","text":" "},{"type":"text","text":"method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideoEx(_:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupRemoteVideoEx:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setupremotevideoex(_:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCanvas":{"role":"symbol","title":"AgoraRtcVideoCanvas","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"abstract":[{"type":"text","text":"Attributes of video canvas object."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"url":"\/documentation\/agorartckit\/agorartcvideocanvas"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setupRemoteVideoEx:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupRemoteVideoEx:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setupRemoteVideoEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas","text":"AgoraRtcVideoCanvas"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"remote"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideoEx(_:connection:)\/title","value":"setupRemoteVideoEx:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideoEx(_:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupRemoteVideoEx:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/title","value":"AgoraRtcVideoCanvas"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/fragments","value":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}