{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoEncoderConfigurationEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","preciseIdentifier":"c:objc(cs)AgoraVideoEncoderConfiguration","text":"AgoraVideoEncoderConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The recording configuration. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaRecorderConfiguration ."}]}]},{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -2: The parameter is invalid. Ensure the"},{"type":"text","text":" "},{"type":"text","text":"following: The specified path of the recording file exists and is writable."},{"type":"text","text":" "},{"type":"text","text":"The specified format of the recording file is supported. The maximum"},{"type":"text","text":" "},{"type":"text","text":"recording duration is correctly set. -4: AgoraRtcEngineKit does not support"},{"type":"text","text":" "},{"type":"text","text":"the request. The recording is ongoing or the recording stops because an error"},{"type":"text","text":" "},{"type":"text","text":"occurs. -7: The method is called before AgoraRtcEngineKit is initialized."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvideoencoderconfigurationex(_:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvideoencoderconfigurationex(_:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfigurationEx(_:connection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts recording the local audio and video."},{"type":"text","text":" "},{"type":"text","text":"This method can record the audio captured by the local microphone and encoded"},{"type":"text","text":" "},{"type":"text","text":"in AAC format, and the video captured by the local camera and encoded in"},{"type":"text","text":" "},{"type":"text","text":"H.264 format. The SDK can generate a recording file only when it detects"},{"type":"text","text":" "},{"type":"text","text":"audio and video streams; when there are no audio and video streams to be"},{"type":"text","text":" "},{"type":"text","text":"recorded or the audio and video streams are interrupted for more than five"},{"type":"text","text":" "},{"type":"text","text":"seconds, the SDK stops the recording and triggers the"},{"type":"text","text":" "},{"type":"text","text":"stateDidChanged(AgoraMediaRecorderStateError,"},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaRecorderErrorCodeNoStream) callback.Once the recording is started,"},{"type":"text","text":" "},{"type":"text","text":"if the video resolution is changed, the SDK stops the recording; if the"},{"type":"text","text":" "},{"type":"text","text":"sampling rate and audio channel changes, the SDK continues recording and"},{"type":"text","text":" "},{"type":"text","text":"generates audio files respectively.Call this method after joining a channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setVideoEncoderConfigurationEx:connection:"}],"role":"symbol","title":"setVideoEncoderConfigurationEx(_:connection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoEncoderConfigurationEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoEncoderConfiguration","preciseIdentifier":"c:objc(cs)AgoraVideoEncoderConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setVideoEncoderConfigurationEx:connection:","extendedModule":"AgoraRtcKit","modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration":{"role":"symbol","title":"AgoraVideoEncoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVideoEncoderConfigurationEx(_:connection:)":{"role":"symbol","title":"setVideoEncoderConfigurationEx(_:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoEncoderConfigurationEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoEncoderConfiguration","preciseIdentifier":"c:objc(cs)AgoraVideoEncoderConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts recording the local audio and video."},{"type":"text","text":" "},{"type":"text","text":"This method can record the audio captured by the local microphone and encoded"},{"type":"text","text":" "},{"type":"text","text":"in AAC format, and the video captured by the local camera and encoded in"},{"type":"text","text":" "},{"type":"text","text":"H.264 format. The SDK can generate a recording file only when it detects"},{"type":"text","text":" "},{"type":"text","text":"audio and video streams; when there are no audio and video streams to be"},{"type":"text","text":" "},{"type":"text","text":"recorded or the audio and video streams are interrupted for more than five"},{"type":"text","text":" "},{"type":"text","text":"seconds, the SDK stops the recording and triggers the"},{"type":"text","text":" "},{"type":"text","text":"stateDidChanged(AgoraMediaRecorderStateError,"},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaRecorderErrorCodeNoStream) callback.Once the recording is started,"},{"type":"text","text":" "},{"type":"text","text":"if the video resolution is changed, the SDK stops the recording; if the"},{"type":"text","text":" "},{"type":"text","text":"sampling rate and audio channel changes, the SDK continues recording and"},{"type":"text","text":" "},{"type":"text","text":"generates audio files respectively.Call this method after joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoEncoderConfigurationEx(_:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoEncoderConfigurationEx:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvideoencoderconfigurationex(_:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setVideoEncoderConfigurationEx:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoEncoderConfigurationEx:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVideoEncoderConfigurationEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","preciseIdentifier":"c:objc(cs)AgoraVideoEncoderConfiguration","text":"AgoraVideoEncoderConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/title","value":"AgoraVideoEncoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoEncoderConfigurationEx(_:connection:)\/title","value":"setVideoEncoderConfigurationEx:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoEncoderConfigurationEx(_:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoEncoderConfigurationEx:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}