{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoDenoiserOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions","preciseIdentifier":"c:objc(cs)AgoraVideoDenoiserOptions","text":"AgoraVideoDenoiserOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable video noise reduction:YES: Enable video"},{"type":"text","text":" "},{"type":"text","text":"noise reduction.NO: (Default) Disable video noise reduction."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video noise reduction options. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoDenoiserOptions ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvideodenoiseroptions(_:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvideodenoiseroptions(_:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoDenoiserOptions(_:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets video noise reduction."},{"type":"text","text":" "},{"type":"text","text":"Underlit environments and low-end video capture devices can cause video"},{"type":"text","text":" "},{"type":"text","text":"images to contain significant noise, which affects video quality. In"},{"type":"text","text":" "},{"type":"text","text":"real-time interactive scenarios, video noise also consumes bitstream"},{"type":"text","text":" "},{"type":"text","text":"resources and reduces encoding efficiency during encoding.You can call this"},{"type":"text","text":" "},{"type":"text","text":"method to enable the video noise reduction feature and set the options of the"},{"type":"text","text":" "},{"type":"text","text":"video noise reduction effect.Call this method after calling enableVideo"},{"type":"text","text":" "},{"type":"text","text":".Video noise reduction has certain requirements for equipment performance. If"},{"type":"text","text":" "},{"type":"text","text":"your device overheats after you enable video noise reduction, Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends modifying the video noise reduction options to a less"},{"type":"text","text":" "},{"type":"text","text":"performance-consuming level or disabling video noise reduction entirely.Both"},{"type":"text","text":" "},{"type":"text","text":"this method and setExtensionPropertyWithVendor can turn on video noise"},{"type":"text","text":" "},{"type":"text","text":"reduction function:When you use the SDK to capture video, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"this method (this method only works for video captured by the SDK).When you"},{"type":"text","text":" "},{"type":"text","text":"use an external video source to implement custom video capture, or send an"},{"type":"text","text":" "},{"type":"text","text":"external video source to the SDK, Agora recommends using"},{"type":"text","text":" "},{"type":"text","text":"setExtensionPropertyWithVendor.This method relies on the video enhancement"},{"type":"text","text":" "},{"type":"text","text":"dynamic library AgoraClearVisionExtension.xcframework. If the dynamic library"},{"type":"text","text":" "},{"type":"text","text":"is deleted, the function cannot be enabled normally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoDenoiserOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoDenoiserOptions","preciseIdentifier":"c:objc(cs)AgoraVideoDenoiserOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setVideoDenoiserOptions(_:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setVideoDenoiserOptions:options:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setVideoDenoiserOptions:options:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVideoDenoiserOptions(_:options:)":{"role":"symbol","title":"setVideoDenoiserOptions(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoDenoiserOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoDenoiserOptions","preciseIdentifier":"c:objc(cs)AgoraVideoDenoiserOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets video noise reduction."},{"type":"text","text":" "},{"type":"text","text":"Underlit environments and low-end video capture devices can cause video"},{"type":"text","text":" "},{"type":"text","text":"images to contain significant noise, which affects video quality. In"},{"type":"text","text":" "},{"type":"text","text":"real-time interactive scenarios, video noise also consumes bitstream"},{"type":"text","text":" "},{"type":"text","text":"resources and reduces encoding efficiency during encoding.You can call this"},{"type":"text","text":" "},{"type":"text","text":"method to enable the video noise reduction feature and set the options of the"},{"type":"text","text":" "},{"type":"text","text":"video noise reduction effect.Call this method after calling enableVideo"},{"type":"text","text":" "},{"type":"text","text":".Video noise reduction has certain requirements for equipment performance. If"},{"type":"text","text":" "},{"type":"text","text":"your device overheats after you enable video noise reduction, Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends modifying the video noise reduction options to a less"},{"type":"text","text":" "},{"type":"text","text":"performance-consuming level or disabling video noise reduction entirely.Both"},{"type":"text","text":" "},{"type":"text","text":"this method and setExtensionPropertyWithVendor can turn on video noise"},{"type":"text","text":" "},{"type":"text","text":"reduction function:When you use the SDK to capture video, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"this method (this method only works for video captured by the SDK).When you"},{"type":"text","text":" "},{"type":"text","text":"use an external video source to implement custom video capture, or send an"},{"type":"text","text":" "},{"type":"text","text":"external video source to the SDK, Agora recommends using"},{"type":"text","text":" "},{"type":"text","text":"setExtensionPropertyWithVendor.This method relies on the video enhancement"},{"type":"text","text":" "},{"type":"text","text":"dynamic library AgoraClearVisionExtension.xcframework. If the dynamic library"},{"type":"text","text":" "},{"type":"text","text":"is deleted, the function cannot be enabled normally."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoDenoiserOptions(_:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoDenoiserOptions:options:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvideodenoiseroptions(_:options:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserOptions":{"role":"symbol","title":"AgoraVideoDenoiserOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}],"abstract":[{"type":"text","text":"Video noise reduction options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}],"url":"\/documentation\/agorartckit\/agoravideodenoiseroptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setVideoDenoiserOptions:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoDenoiserOptions:options:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVideoDenoiserOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions","preciseIdentifier":"c:objc(cs)AgoraVideoDenoiserOptions","text":"AgoraVideoDenoiserOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoDenoiserOptions(_:options:)\/title","value":"setVideoDenoiserOptions:options:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoDenoiserOptions(_:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoDenoiserOptions:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions\/title","value":"AgoraVideoDenoiserOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}