{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","preciseIdentifier":"c:@E@AgoraVideoProfile","text":"AgoraVideoProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swapWidthAndHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"profile","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video profile. See AgoraVideoProfile ."}]}]},{"name":"swapWidthAndHeight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK outputs video with a fixed width and"},{"type":"text","text":" "},{"type":"text","text":"height according to the video profile (profile) you selected. This parameter"},{"type":"text","text":" "},{"type":"text","text":"sets whether to swap width and height of the video:YES: Swap the width and"},{"type":"text","text":" "},{"type":"text","text":"height.NO: (Default) Do not swap the width and height."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvideoprofile(_:swapwidthandheight:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvideoprofile(_:swapwidthandheight:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoProfile(_:swapWidthAndHeight:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the video encoder configuration."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated. Use setVideoEncoderConfiguration"},{"type":"text","text":" "},{"type":"text","text":"instead.This method sets the video encoder configuration. You can call this"},{"type":"text","text":" "},{"type":"text","text":"method either before or after joining a channel. If the user does not need to"},{"type":"text","text":" "},{"type":"text","text":"reset the video encoding properties after joining the channel, Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends calling this method before enableVideo to reduce the time to"},{"type":"text","text":" "},{"type":"text","text":"render the first video frame."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setVideoProfile:swapWidthAndHeight:"}],"role":"symbol","title":"setVideoProfile(_:swapWidthAndHeight:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoProfile","preciseIdentifier":"c:@E@AgoraVideoProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swapWidthAndHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setVideoProfile:swapWidthAndHeight:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use setVideoEncoderConfiguration: instead."}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVideoProfile(_:swapWidthAndHeight:)":{"deprecated":true,"role":"symbol","title":"setVideoProfile(_:swapWidthAndHeight:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVideoProfile","preciseIdentifier":"c:@E@AgoraVideoProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swapWidthAndHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the video encoder configuration."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated. Use setVideoEncoderConfiguration"},{"type":"text","text":" "},{"type":"text","text":"instead.This method sets the video encoder configuration. You can call this"},{"type":"text","text":" "},{"type":"text","text":"method either before or after joining a channel. If the user does not need to"},{"type":"text","text":" "},{"type":"text","text":"reset the video encoding properties after joining the channel, Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends calling this method before enableVideo to reduce the time to"},{"type":"text","text":" "},{"type":"text","text":"render the first video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVideoProfile(_:swapWidthAndHeight:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoProfile:swapWidthAndHeight:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvideoprofile(_:swapwidthandheight:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile":{"role":"symbol","title":"AgoraVideoProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"abstract":[{"type":"text","text":"Video profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfile"}],"url":"\/documentation\/agorartckit\/agoravideoprofile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setVideoProfile:swapWidthAndHeight:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoProfile:swapWidthAndHeight:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVideoProfile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","preciseIdentifier":"c:@E@AgoraVideoProfile","text":"AgoraVideoProfile"},{"kind":"text","text":") "},{"kind":"internalParam","text":"profile"},{"kind":"text","text":" "},{"kind":"identifier","text":"swapWidthAndHeight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"swapWidthAndHeight"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoProfile(_:swapWidthAndHeight:)\/title","value":"setVideoProfile:swapWidthAndHeight:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVideoProfile(_:swapWidthAndHeight:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoProfile:swapWidthAndHeight:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/title","value":"AgoraVideoProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}