{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceBeautifierPreset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset","text":"AgoraVoiceBeautifierPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The preset voice beautifier effect options:"},{"type":"text","text":" "},{"type":"text","text":"AgoraVoiceBeautifierPreset ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvoicebeautifierpreset(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvoicebeautifierpreset(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVoiceBeautifierPreset(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets a preset voice beautifier effect."},{"type":"text","text":" "},{"type":"text","text":"Call this method to set a preset voice beautifier effect for the local user"},{"type":"text","text":" "},{"type":"text","text":"who sends an audio stream. After setting a voice beautifier effect, all users"},{"type":"text","text":" "},{"type":"text","text":"in the channel can hear the effect. You can set different voice beautifier"},{"type":"text","text":" "},{"type":"text","text":"effects for different scenarios. For the applicable scenarios of each voice"},{"type":"text","text":" "},{"type":"text","text":"beautifier effect, refer to Set the Voice Effect.For better voice effects,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you call setAudioProfile [1\/2] and set scenario to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioScenarioGameStreaming(3) and profile to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQuality(4) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo(5) before calling this method.You can"},{"type":"text","text":" "},{"type":"text","text":"call this method either before or after joining a channel.Do not set the"},{"type":"text","text":" "},{"type":"text","text":"profile parameter in setAudioProfile [1\/2] to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileSpeechStandard(1)This method has the best effect on human"},{"type":"text","text":" "},{"type":"text","text":"voice processing, and Agora does not recommend calling this method to process"},{"type":"text","text":" "},{"type":"text","text":"audio data containing music.After calling setVoiceBeautifierPreset, Agora"},{"type":"text","text":" "},{"type":"text","text":"does not recommend calling the following methods, otherwise the effect set by"},{"type":"text","text":" "},{"type":"text","text":"setVoiceBeautifierPreset will be overwritten: setAudioEffectPreset"},{"type":"text","text":" "},{"type":"text","text":"setAudioEffectParameters setLocalVoicePitch"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoiceEqualizationOfBandFrequency setLocalVoiceReverbOfType"},{"type":"text","text":" "},{"type":"text","text":"setVoiceBeautifierParameters setVoiceConversionPreset This method relies on"},{"type":"text","text":" "},{"type":"text","text":"the voice beautifier dynamic library AgoraAudioBeautyExtension.xcframework."},{"type":"text","text":" "},{"type":"text","text":"If the dynamic library is deleted, the function cannot be enabled normally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceBeautifierPreset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setVoiceBeautifierPreset(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setVoiceBeautifierPreset:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setVoiceBeautifierPreset:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVoiceBeautifierPreset(_:)":{"role":"symbol","title":"setVoiceBeautifierPreset(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceBeautifierPreset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets a preset voice beautifier effect."},{"type":"text","text":" "},{"type":"text","text":"Call this method to set a preset voice beautifier effect for the local user"},{"type":"text","text":" "},{"type":"text","text":"who sends an audio stream. After setting a voice beautifier effect, all users"},{"type":"text","text":" "},{"type":"text","text":"in the channel can hear the effect. You can set different voice beautifier"},{"type":"text","text":" "},{"type":"text","text":"effects for different scenarios. For the applicable scenarios of each voice"},{"type":"text","text":" "},{"type":"text","text":"beautifier effect, refer to Set the Voice Effect.For better voice effects,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you call setAudioProfile [1\/2] and set scenario to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioScenarioGameStreaming(3) and profile to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQuality(4) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo(5) before calling this method.You can"},{"type":"text","text":" "},{"type":"text","text":"call this method either before or after joining a channel.Do not set the"},{"type":"text","text":" "},{"type":"text","text":"profile parameter in setAudioProfile [1\/2] to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileSpeechStandard(1)This method has the best effect on human"},{"type":"text","text":" "},{"type":"text","text":"voice processing, and Agora does not recommend calling this method to process"},{"type":"text","text":" "},{"type":"text","text":"audio data containing music.After calling setVoiceBeautifierPreset, Agora"},{"type":"text","text":" "},{"type":"text","text":"does not recommend calling the following methods, otherwise the effect set by"},{"type":"text","text":" "},{"type":"text","text":"setVoiceBeautifierPreset will be overwritten: setAudioEffectPreset"},{"type":"text","text":" "},{"type":"text","text":"setAudioEffectParameters setLocalVoicePitch"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoiceEqualizationOfBandFrequency setLocalVoiceReverbOfType"},{"type":"text","text":" "},{"type":"text","text":"setVoiceBeautifierParameters setVoiceConversionPreset This method relies on"},{"type":"text","text":" "},{"type":"text","text":"the voice beautifier dynamic library AgoraAudioBeautyExtension.xcframework."},{"type":"text","text":" "},{"type":"text","text":"If the dynamic library is deleted, the function cannot be enabled normally."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVoiceBeautifierPreset(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVoiceBeautifierPreset:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvoicebeautifierpreset(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset":{"role":"symbol","title":"AgoraVoiceBeautifierPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setVoiceBeautifierPreset:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVoiceBeautifierPreset:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVoiceBeautifierPreset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset","text":"AgoraVoiceBeautifierPreset"},{"kind":"text","text":") "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVoiceBeautifierPreset(_:)\/title","value":"setVoiceBeautifierPreset:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVoiceBeautifierPreset(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVoiceBeautifierPreset:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}