{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceBeautifierParameters"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset","text":"AgoraVoiceBeautifierPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The option for the preset audio effect:SINGING_BEAUTIFIER: The singing beautifier effect."}]}]},{"name":"param1","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The gender characteristics options for the singing voice:1: A male-sounding voice.2: A female-sounding voice."}]}]},{"name":"param2","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The reverberation effect options for the singing voice:1: The reverberation effect sounds like singing in a small room.2: The reverberation effect sounds like singing in a large room.3: The reverberation effect sounds like singing in a hall."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method to set a gender characteristic and a reverberation effect for the singing beautifier effect. This method sets parameters for the local user who sends an audio stream. After setting the audio parameters, all users in the channel can hear the effect. For better voice effects, Agora recommends that you call setAudioProfile [1\/2] and set scenario to AgoraAudioScenarioGameStreaming (3) and profile to AgoraAudioProfileMusicHighQuality (4) or AgoraAudioProfileMusicHighQualityStereo (5) before calling this method. You can call this method either before or after joining a channel. Do not set the profile parameter in setAudioProfile [1\/2] to AgoraAudioProfileSpeechStandard (1) This method has the best effect on human voice processing, and Agora does not recommend calling this method to process audio data containing music. After calling setVoiceBeautifierParameters , Agora does not recommend calling the following methods, otherwise the effect set by setVoiceBeautifierParameters will be overwritten: setAudioEffectPreset setAudioEffectParameters setVoiceBeautifierPreset setLocalVoicePitch setLocalVoiceEqualizationOfBandFrequency setLocalVoiceReverbOfType setVoiceConversionPreset"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvoicebeautifierparameters(_:param1:param2:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvoicebeautifierparameters(_:param1:param2:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVoiceBeautifierParameters(_:param1:param2:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets parameters for the preset voice beautifier effects."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceBeautifierParameters"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setVoiceBeautifierParameters(_:param1:param2:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setVoiceBeautifierParameters:param1:param2:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setVoiceBeautifierParameters:param1:param2:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVoiceBeautifierParameters(_:param1:param2:)":{"role":"symbol","title":"setVoiceBeautifierParameters(_:param1:param2:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceBeautifierParameters"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"param2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets parameters for the preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVoiceBeautifierParameters(_:param1:param2:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVoiceBeautifierParameters:param1:param2:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvoicebeautifierparameters(_:param1:param2:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset":{"role":"symbol","title":"AgoraVoiceBeautifierPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setVoiceBeautifierParameters:param1:param2:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVoiceBeautifierParameters:param1:param2:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVoiceBeautifierParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","preciseIdentifier":"c:@E@AgoraVoiceBeautifierPreset","text":"AgoraVoiceBeautifierPreset"},{"kind":"text","text":")"},{"kind":"internalParam","text":"preset"},{"kind":"text","text":" "},{"kind":"identifier","text":"param1:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"param1"},{"kind":"text","text":" "},{"kind":"identifier","text":"param2:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"param2"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVoiceBeautifierParameters(_:param1:param2:)\/title","value":"setVoiceBeautifierParameters:param1:param2:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVoiceBeautifierParameters(_:param1:param2:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVoiceBeautifierParameters:param1:param2:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}