{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceConversionPreset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset","preciseIdentifier":"c:@E@AgoraVoiceConversionPreset","text":"AgoraVoiceConversionPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"preset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options for the preset voice beautifier effects:"},{"type":"text","text":" "},{"type":"text","text":"AgoraVoiceConversionPreset ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvoiceconversionpreset(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/setvoiceconversionpreset(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVoiceConversionPreset(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets a preset voice beautifier effect."},{"type":"text","text":" "},{"type":"text","text":"Call this method to set a preset voice beautifier effect for the local user"},{"type":"text","text":" "},{"type":"text","text":"who sends an audio stream. After setting an audio effect, all users in the"},{"type":"text","text":" "},{"type":"text","text":"channel can hear the effect. You can set different voice beautifier effects"},{"type":"text","text":" "},{"type":"text","text":"for different scenarios. For the applicable scenarios of each voice"},{"type":"text","text":" "},{"type":"text","text":"beautifier effect, refer to Set the Voice Effect.To achieve better audio"},{"type":"text","text":" "},{"type":"text","text":"effect quality, Agora recommends that you call setAudioProfile [1\/2] and set"},{"type":"text","text":" "},{"type":"text","text":"the profile to AgoraAudioProfileMusicHighQuality(4) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo(5) and scenario to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioScenarioGameStreaming(3) before calling this method.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel.Do not set the profile"},{"type":"text","text":" "},{"type":"text","text":"parameter in setAudioProfile [1\/2] to AgoraAudioProfileSpeechStandard(1)This"},{"type":"text","text":" "},{"type":"text","text":"method has the best effect on human voice processing, and Agora does not"},{"type":"text","text":" "},{"type":"text","text":"recommend calling this method to process audio data containing music.After"},{"type":"text","text":" "},{"type":"text","text":"calling setVoiceConversionPreset, Agora does not recommend you to call the"},{"type":"text","text":" "},{"type":"text","text":"following methods, otherwise the effect set by setVoiceConversionPreset will"},{"type":"text","text":" "},{"type":"text","text":"be overwritten: setAudioEffectPreset setAudioEffectParameters"},{"type":"text","text":" "},{"type":"text","text":"setVoiceBeautifierPreset setVoiceBeautifierParameters setLocalVoicePitch"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoiceEqualizationOfBandFrequency setLocalVoiceReverbOfType This"},{"type":"text","text":" "},{"type":"text","text":"method relies on the voice beautifier dynamic library"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioBeautyExtension.xcframework. If the dynamic library is deleted, the"},{"type":"text","text":" "},{"type":"text","text":"function cannot be enabled normally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceConversionPreset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVoiceConversionPreset","preciseIdentifier":"c:@E@AgoraVoiceConversionPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setVoiceConversionPreset(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)setVoiceConversionPreset:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setVoiceConversionPreset:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset":{"role":"symbol","title":"AgoraVoiceConversionPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceConversionPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice conversion effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPreset"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setVoiceConversionPreset(_:)":{"role":"symbol","title":"setVoiceConversionPreset(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoiceConversionPreset"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraVoiceConversionPreset","preciseIdentifier":"c:@E@AgoraVoiceConversionPreset"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets a preset voice beautifier effect."},{"type":"text","text":" "},{"type":"text","text":"Call this method to set a preset voice beautifier effect for the local user"},{"type":"text","text":" "},{"type":"text","text":"who sends an audio stream. After setting an audio effect, all users in the"},{"type":"text","text":" "},{"type":"text","text":"channel can hear the effect. You can set different voice beautifier effects"},{"type":"text","text":" "},{"type":"text","text":"for different scenarios. For the applicable scenarios of each voice"},{"type":"text","text":" "},{"type":"text","text":"beautifier effect, refer to Set the Voice Effect.To achieve better audio"},{"type":"text","text":" "},{"type":"text","text":"effect quality, Agora recommends that you call setAudioProfile [1\/2] and set"},{"type":"text","text":" "},{"type":"text","text":"the profile to AgoraAudioProfileMusicHighQuality(4) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo(5) and scenario to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioScenarioGameStreaming(3) before calling this method.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel.Do not set the profile"},{"type":"text","text":" "},{"type":"text","text":"parameter in setAudioProfile [1\/2] to AgoraAudioProfileSpeechStandard(1)This"},{"type":"text","text":" "},{"type":"text","text":"method has the best effect on human voice processing, and Agora does not"},{"type":"text","text":" "},{"type":"text","text":"recommend calling this method to process audio data containing music.After"},{"type":"text","text":" "},{"type":"text","text":"calling setVoiceConversionPreset, Agora does not recommend you to call the"},{"type":"text","text":" "},{"type":"text","text":"following methods, otherwise the effect set by setVoiceConversionPreset will"},{"type":"text","text":" "},{"type":"text","text":"be overwritten: setAudioEffectPreset setAudioEffectParameters"},{"type":"text","text":" "},{"type":"text","text":"setVoiceBeautifierPreset setVoiceBeautifierParameters setLocalVoicePitch"},{"type":"text","text":" "},{"type":"text","text":"setLocalVoiceEqualizationOfBandFrequency setLocalVoiceReverbOfType This"},{"type":"text","text":" "},{"type":"text","text":"method relies on the voice beautifier dynamic library"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioBeautyExtension.xcframework. If the dynamic library is deleted, the"},{"type":"text","text":" "},{"type":"text","text":"function cannot be enabled normally."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setVoiceConversionPreset(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVoiceConversionPreset:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setvoiceconversionpreset(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setVoiceConversionPreset:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVoiceConversionPreset:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setVoiceConversionPreset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset","preciseIdentifier":"c:@E@AgoraVoiceConversionPreset","text":"AgoraVoiceConversionPreset"},{"kind":"text","text":") "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset\/title","value":"AgoraVoiceConversionPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVoiceConversionPreset(_:)\/title","value":"setVoiceConversionPreset:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setVoiceConversionPreset(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVoiceConversionPreset:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}