{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","preciseIdentifier":"c:objc(cs)AgoraRtcEngineConfig","text":"AgoraRtcEngineConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcEngineDelegate","text":"AgoraRtcEngineDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configurations for the AgoraRtcEngineKit instance. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineConfig ."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The event handler for AgoraRtcEngineKit . See"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineDelegate ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"< 0: Failure. -1: A general error occurs (no specified reason)."},{"type":"text","text":" "},{"type":"text","text":"-2: The parameter is invalid. -7: The SDK is not initialized. -22: The"},{"type":"text","text":" "},{"type":"text","text":"resource request failed. The SDK fails to allocate resources because your app"},{"type":"text","text":" "},{"type":"text","text":"consumes too much system resource or the system resources are insufficient."},{"type":"text","text":" "},{"type":"text","text":"-101: The App ID is invalid."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/sharedengine(with:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/sharedengine(with:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/sharedEngine(with:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates and initializes AgoraRtcEngineKit ."},{"type":"text","text":" "},{"type":"text","text":"All called methods provided by the AgoraRtcEngineKit class are executed"},{"type":"text","text":" "},{"type":"text","text":"asynchronously. Agora recommends calling these methods in the same"},{"type":"text","text":" "},{"type":"text","text":"thread.Before calling other APIs, you must call this method to create the"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineKit object.You can create the AgoraRtcEngineKit instance either"},{"type":"text","text":" "},{"type":"text","text":"by calling this method or by calling sharedEngineWithAppId . The difference"},{"type":"text","text":" "},{"type":"text","text":"between sharedEngineWithAppId and this method is that this method supports"},{"type":"text","text":" "},{"type":"text","text":"more configurations when creating the AgoraRtcEngineKit instance, for"},{"type":"text","text":" "},{"type":"text","text":"example, specifying the region for connection and setting the log files.The"},{"type":"text","text":" "},{"type":"text","text":"SDK supports creating only one AgoraRtcEngineKit instance for an app."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineConfig","preciseIdentifier":"c:objc(cs)AgoraRtcEngineConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcEngineDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"sharedEngine(with:delegate:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(cm)sharedEngineWithConfig:delegate:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"sharedEngineWithConfig:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"seeAlsoSections":[{"title":"Initialise and Destruct","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/sharedEngine(withAppId:delegate:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/destroy()"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/sharedEngine(withAppId:delegate:)":{"role":"symbol","title":"sharedEngine(withAppId:delegate:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcEngineDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Creates and initializes AgoraRtcEngineKit ."},{"type":"text","text":" "},{"type":"text","text":"All called methods provided by the AgoraRtcEngineKit class are executed"},{"type":"text","text":" "},{"type":"text","text":"asynchronously. Agora recommends calling these methods in the same"},{"type":"text","text":" "},{"type":"text","text":"thread.Before calling other APIs, you must call this method to create the"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineKit object.You can create the AgoraRtcEngineKit instance either"},{"type":"text","text":" "},{"type":"text","text":"by calling this method or by calling sharedEngineWithConfig . The difference"},{"type":"text","text":" "},{"type":"text","text":"between sharedEngineWithConfig and this method is that sharedEngineWithConfig"},{"type":"text","text":" "},{"type":"text","text":"supports more configurations when creating the AgoraRtcEngineKit instance,"},{"type":"text","text":" "},{"type":"text","text":"for example, specifying the region for connection and setting the log"},{"type":"text","text":" "},{"type":"text","text":"files.The SDK supports creating only one AgoraRtcEngineKit instance for an"},{"type":"text","text":" "},{"type":"text","text":"app."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/sharedEngine(withAppId:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedEngineWithAppId:delegate:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/sharedengine(withappid:delegate:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications"},{"type":"text","text":" "},{"type":"text","text":"to your app. Your app can get those notifications through methods that"},{"type":"text","text":" "},{"type":"text","text":"inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig":{"role":"symbol","title":"AgoraRtcEngineConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"abstract":[{"type":"text","text":"Configurations for the AgoraRtcEngineConfig instance."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/destroy()":{"role":"symbol","title":"destroy()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroy"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Releases the AgoraRtcEngineKit instance."},{"type":"text","text":" "},{"type":"text","text":"This method releases all resources used by the Agora SDK. Use this method for"},{"type":"text","text":" "},{"type":"text","text":"apps in which users occasionally make voice or video calls. When users do not"},{"type":"text","text":" "},{"type":"text","text":"make calls, you can free up resources for other operations.After a successful"},{"type":"text","text":" "},{"type":"text","text":"method call, you can no longer use any method or callback in the SDK anymore."},{"type":"text","text":" "},{"type":"text","text":"If you want to use the real-time communication functions again, you must call"},{"type":"text","text":" "},{"type":"text","text":"sharedEngineWithConfig to create a new AgoraRtcEngineKit instance.If you want"},{"type":"text","text":" "},{"type":"text","text":"to create a new AgoraRtcEngineKit instance after destroyingthe current one,"},{"type":"text","text":" "},{"type":"text","text":"ensure that you wait till the destroy method execution to complete."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/destroy()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"destroy"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/destroy()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/sharedEngine(with:delegate:)":{"role":"symbol","title":"sharedEngine(with:delegate:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineConfig","preciseIdentifier":"c:objc(cs)AgoraRtcEngineConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcEngineDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Creates and initializes AgoraRtcEngineKit ."},{"type":"text","text":" "},{"type":"text","text":"All called methods provided by the AgoraRtcEngineKit class are executed"},{"type":"text","text":" "},{"type":"text","text":"asynchronously. Agora recommends calling these methods in the same"},{"type":"text","text":" "},{"type":"text","text":"thread.Before calling other APIs, you must call this method to create the"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineKit object.You can create the AgoraRtcEngineKit instance either"},{"type":"text","text":" "},{"type":"text","text":"by calling this method or by calling sharedEngineWithAppId . The difference"},{"type":"text","text":" "},{"type":"text","text":"between sharedEngineWithAppId and this method is that this method supports"},{"type":"text","text":" "},{"type":"text","text":"more configurations when creating the AgoraRtcEngineKit instance, for"},{"type":"text","text":" "},{"type":"text","text":"example, specifying the region for connection and setting the log files.The"},{"type":"text","text":" "},{"type":"text","text":"SDK supports creating only one AgoraRtcEngineKit instance for an app."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/sharedEngine(with:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedEngineWithConfig:delegate:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/sharedengine(with:delegate:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"sharedEngineWithConfig:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedEngineWithConfig:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Initialise and Destruct","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/sharedEngine(withAppId:delegate:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/destroy()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"sharedEngineWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","preciseIdentifier":"c:objc(cs)AgoraRtcEngineConfig","text":"AgoraRtcEngineConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraRtcEngineDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraRtcEngineDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1sharedEngine(withAppId:delegate:)\/title","value":"sharedEngineWithAppId:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1sharedEngine(withAppId:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedEngineWithAppId:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/title","value":"AgoraRtcEngineConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1destroy()\/title","value":"destroy"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1destroy()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"destroy"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1sharedEngine(with:delegate:)\/title","value":"sharedEngineWithConfig:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1sharedEngine(with:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedEngineWithConfig:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}