{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startScreenCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2","text":"AgoraScreenCaptureParameters2"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"parameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The screen sharing encoding parameters. The default"},{"type":"text","text":" "},{"type":"text","text":"video dimension is 1920 x 1080, that is, 2,073,600 pixels. Agora uses the"},{"type":"text","text":" "},{"type":"text","text":"value of this parameter to calculate the charges. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraScreenCaptureParameters2 ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -2: The parameter is null."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startscreencapture(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startscreencapture(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startScreenCapture(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts screen sharing."},{"type":"text","text":" "},{"type":"text","text":"There are two ways to start screen sharing, you can choose one according to"},{"type":"text","text":" "},{"type":"text","text":"your needs:Call this method before joining a channel, then call"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [2\/4] to join channel and set publishScreenCaptureVideo to"},{"type":"text","text":" "},{"type":"text","text":"YES to start screen sharing.Call this method after joining a channel, then"},{"type":"text","text":" "},{"type":"text","text":"call updateChannelWithMediaOptions and set publishScreenCaptureVideo to YES"},{"type":"text","text":" "},{"type":"text","text":"to start screen sharing.When the state of the screen sharing extension"},{"type":"text","text":" "},{"type":"text","text":"process changes, the SDK triggers the localVideoStateChangedOfState callback"},{"type":"text","text":" "},{"type":"text","text":"accordingly. When the type of sourceType is AgoraVideoSourceTypeScreen, the"},{"type":"text","text":" "},{"type":"text","text":"state parameter indicates the state of the screen sharing.On the iOS"},{"type":"text","text":" "},{"type":"text","text":"platform, screen sharing is only available on iOS 12.0 and later.The billing"},{"type":"text","text":" "},{"type":"text","text":"for the screen sharing stream is based on the dimensions in"},{"type":"text","text":" "},{"type":"text","text":"AgoraScreenVideoParameters. When you do not pass in a value, Agora bills you"},{"type":"text","text":" "},{"type":"text","text":"at 1280 × 720; when you pass a value in, Agora bills you at that value. If"},{"type":"text","text":" "},{"type":"text","text":"you are using the custom audio source instead of the SDK to capture audio,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends you add the keep-alive processing logic to your application"},{"type":"text","text":" "},{"type":"text","text":"to avoid screen sharing stopping when the application goes to the"},{"type":"text","text":" "},{"type":"text","text":"background.This feature requires high-performance device, and Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends that you use it on iPhone X and later models.This method relies on"},{"type":"text","text":" "},{"type":"text","text":"the iOS screen sharing dynamic library AgoraReplayKitExtension.xcframework."},{"type":"text","text":" "},{"type":"text","text":"If the dynamic library is deleted, screen sharing cannot be enabled normally."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startScreenCapture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startScreenCapture(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startScreenCapture:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startScreenCapture:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startScreenCapture(_:)":{"role":"symbol","title":"startScreenCapture(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startScreenCapture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts screen sharing."},{"type":"text","text":" "},{"type":"text","text":"There are two ways to start screen sharing, you can choose one according to"},{"type":"text","text":" "},{"type":"text","text":"your needs:Call this method before joining a channel, then call"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [2\/4] to join channel and set publishScreenCaptureVideo to"},{"type":"text","text":" "},{"type":"text","text":"YES to start screen sharing.Call this method after joining a channel, then"},{"type":"text","text":" "},{"type":"text","text":"call updateChannelWithMediaOptions and set publishScreenCaptureVideo to YES"},{"type":"text","text":" "},{"type":"text","text":"to start screen sharing.When the state of the screen sharing extension"},{"type":"text","text":" "},{"type":"text","text":"process changes, the SDK triggers the localVideoStateChangedOfState callback"},{"type":"text","text":" "},{"type":"text","text":"accordingly. When the type of sourceType is AgoraVideoSourceTypeScreen, the"},{"type":"text","text":" "},{"type":"text","text":"state parameter indicates the state of the screen sharing.On the iOS"},{"type":"text","text":" "},{"type":"text","text":"platform, screen sharing is only available on iOS 12.0 and later.The billing"},{"type":"text","text":" "},{"type":"text","text":"for the screen sharing stream is based on the dimensions in"},{"type":"text","text":" "},{"type":"text","text":"AgoraScreenVideoParameters. When you do not pass in a value, Agora bills you"},{"type":"text","text":" "},{"type":"text","text":"at 1280 × 720; when you pass a value in, Agora bills you at that value. If"},{"type":"text","text":" "},{"type":"text","text":"you are using the custom audio source instead of the SDK to capture audio,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends you add the keep-alive processing logic to your application"},{"type":"text","text":" "},{"type":"text","text":"to avoid screen sharing stopping when the application goes to the"},{"type":"text","text":" "},{"type":"text","text":"background.This feature requires high-performance device, and Agora"},{"type":"text","text":" "},{"type":"text","text":"recommends that you use it on iPhone X and later models.This method relies on"},{"type":"text","text":" "},{"type":"text","text":"the iOS screen sharing dynamic library AgoraReplayKitExtension.xcframework."},{"type":"text","text":" "},{"type":"text","text":"If the dynamic library is deleted, screen sharing cannot be enabled normally."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startScreenCapture(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startScreenCapture:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startscreencapture(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureParameters2":{"role":"symbol","title":"AgoraScreenCaptureParameters2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"abstract":[{"type":"text","text":"Screen sharing configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"url":"\/documentation\/agorartckit\/agorascreencaptureparameters2"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startScreenCapture:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startScreenCapture:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startScreenCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2","text":"AgoraScreenCaptureParameters2"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startScreenCapture(_:)\/title","value":"startScreenCapture:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startScreenCapture(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startScreenCapture:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/title","value":"AgoraScreenCaptureParameters2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}