{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAudioMixing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loopback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"filePath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The absolute path or URL address (including the"},{"type":"text","text":" "},{"type":"text","text":"suffixes of the filename) of the audio effect file. For example,"},{"type":"text","text":" "},{"type":"text","text":"\/var\/mobile\/Containers\/Data\/audio.mp4. Supported audio formats include MP3,"},{"type":"text","text":" "},{"type":"text","text":"AAC, M4A, MP4, WAV, and 3GP. See supported audio formats."}]}]},{"name":"loopback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to play music files only on the local"},{"type":"text","text":" "},{"type":"text","text":"client:YES: Only play music files on the local client so that only the local"},{"type":"text","text":" "},{"type":"text","text":"user can hear the music.NO: Publish music files to remote clients so that"},{"type":"text","text":" "},{"type":"text","text":"both the local user and remote users can hear the music."}]}]},{"name":"cycle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of times the music file plays.≥ 0: The number"},{"type":"text","text":" "},{"type":"text","text":"of playback times. For example, 0 means that the SDK does not play the music"},{"type":"text","text":" "},{"type":"text","text":"file while 1 means that the SDK plays once.-1: Play the audio file in an"},{"type":"text","text":" "},{"type":"text","text":"infinite loop."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startaudiomixing(_:loopback:cycle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startaudiomixing(_:loopback:cycle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startAudioMixing(_:loopback:cycle:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts playing the music file."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Use startAudioMixing [2\/2] instead.This method mixes the specified"},{"type":"text","text":" "},{"type":"text","text":"local or online audio file with the audio from the microphone, or replaces"},{"type":"text","text":" "},{"type":"text","text":"the microphone’s audio with the specified local or remote audio file. A"},{"type":"text","text":" "},{"type":"text","text":"successful method call triggers the audioMixingStateChanged"},{"type":"text","text":" "},{"type":"text","text":"(AgoraAudioMixingStateTypePlaying) callback. When the audio mixing file"},{"type":"text","text":" "},{"type":"text","text":"playback finishes, the SDK triggers the audioMixingStateChanged"},{"type":"text","text":" "},{"type":"text","text":"(AgoraAudioMixingStateTypeStopped) callback on the local client.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel. If you need to call"},{"type":"text","text":" "},{"type":"text","text":"startAudioMixing [1\/2] multiple times, ensure that the time interval between"},{"type":"text","text":" "},{"type":"text","text":"calling this method is more than 500 ms.If the local music file does not"},{"type":"text","text":" "},{"type":"text","text":"exist, the SDK does not support the file format, or the the SDK cannot access"},{"type":"text","text":" "},{"type":"text","text":"the music file URL, the SDK reports the warn code 701."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAudioMixing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loopback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startAudioMixing(_:loopback:cycle:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startAudioMixing:loopback:cycle:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startAudioMixing:loopback:cycle:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startAudioMixing(_:loopback:cycle:)":{"role":"symbol","title":"startAudioMixing(_:loopback:cycle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAudioMixing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loopback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts playing the music file."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Use startAudioMixing [2\/2] instead.This method mixes the specified"},{"type":"text","text":" "},{"type":"text","text":"local or online audio file with the audio from the microphone, or replaces"},{"type":"text","text":" "},{"type":"text","text":"the microphone’s audio with the specified local or remote audio file. A"},{"type":"text","text":" "},{"type":"text","text":"successful method call triggers the audioMixingStateChanged"},{"type":"text","text":" "},{"type":"text","text":"(AgoraAudioMixingStateTypePlaying) callback. When the audio mixing file"},{"type":"text","text":" "},{"type":"text","text":"playback finishes, the SDK triggers the audioMixingStateChanged"},{"type":"text","text":" "},{"type":"text","text":"(AgoraAudioMixingStateTypeStopped) callback on the local client.You can call"},{"type":"text","text":" "},{"type":"text","text":"this method either before or after joining a channel. If you need to call"},{"type":"text","text":" "},{"type":"text","text":"startAudioMixing [1\/2] multiple times, ensure that the time interval between"},{"type":"text","text":" "},{"type":"text","text":"calling this method is more than 500 ms.If the local music file does not"},{"type":"text","text":" "},{"type":"text","text":"exist, the SDK does not support the file format, or the the SDK cannot access"},{"type":"text","text":" "},{"type":"text","text":"the music file URL, the SDK reports the warn code 701."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startAudioMixing(_:loopback:cycle:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startAudioMixing:loopback:cycle:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startaudiomixing(_:loopback:cycle:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startAudioMixing:loopback:cycle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAudioMixing:loopback:cycle:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startAudioMixing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"filePath"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"loopback"},{"kind":"text","text":" "},{"kind":"identifier","text":"cycle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cycle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startAudioMixing(_:loopback:cycle:)\/title","value":"startAudioMixing:loopback:cycle:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startAudioMixing(_:loopback:cycle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAudioMixing:loopback:cycle:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}