{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"successBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"successBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK triggers the successBlock callback if this"},{"type":"text","text":" "},{"type":"text","text":"method call is successful."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startechotest(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startechotest(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startEchoTest(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts an audio call test."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated, use startEchoTestWithInterval"},{"type":"text","text":" "},{"type":"text","text":"instead.This method starts an audio call test to determine whether the audio"},{"type":"text","text":" "},{"type":"text","text":"devices (for example, headset and speaker) and the network connection are"},{"type":"text","text":" "},{"type":"text","text":"working properly. To conduct the test, the user speaks, and the recording is"},{"type":"text","text":" "},{"type":"text","text":"played back within 10 seconds. If the user can hear the recording within the"},{"type":"text","text":" "},{"type":"text","text":"interval, the audio devices and network connection are working properly.Call"},{"type":"text","text":" "},{"type":"text","text":"this method before joining a channel.After calling startEchoTest, you must"},{"type":"text","text":" "},{"type":"text","text":"call stopEchoTest to end the test. Otherwise, the app cannot perform the next"},{"type":"text","text":" "},{"type":"text","text":"echo test, and you cannot join the channel.In the live streaming channels,"},{"type":"text","text":" "},{"type":"text","text":"only a host can call this method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startEchoTest(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startEchoTest:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startEchoTest:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startEchoTest(_:)":{"role":"symbol","title":"startEchoTest(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts an audio call test."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated, use startEchoTestWithInterval"},{"type":"text","text":" "},{"type":"text","text":"instead.This method starts an audio call test to determine whether the audio"},{"type":"text","text":" "},{"type":"text","text":"devices (for example, headset and speaker) and the network connection are"},{"type":"text","text":" "},{"type":"text","text":"working properly. To conduct the test, the user speaks, and the recording is"},{"type":"text","text":" "},{"type":"text","text":"played back within 10 seconds. If the user can hear the recording within the"},{"type":"text","text":" "},{"type":"text","text":"interval, the audio devices and network connection are working properly.Call"},{"type":"text","text":" "},{"type":"text","text":"this method before joining a channel.After calling startEchoTest, you must"},{"type":"text","text":" "},{"type":"text","text":"call stopEchoTest to end the test. Otherwise, the app cannot perform the next"},{"type":"text","text":" "},{"type":"text","text":"echo test, and you cannot join the channel.In the live streaming channels,"},{"type":"text","text":" "},{"type":"text","text":"only a host can call this method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startEchoTest(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startEchoTest:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startechotest(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startEchoTest:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startEchoTest:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startEchoTest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSString *, unsigned long, long)","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#l#L)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"successBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startEchoTest(_:)\/title","value":"startEchoTest:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startEchoTest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startEchoTest:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}