{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDirectCdnStreaming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate","preciseIdentifier":"c:objc(pl)AgoraDirectCdnStreamingEventDelegate","text":"AgoraDirectCdnStreamingEventDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publishUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaOptions"},{"kind":"text","text":" "},{"kind":"internalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions","text":"AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"publishUrl","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CDN live streaming URL."}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The media setting options for the host. See AgoraDirectCdnStreamingMediaOptions."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Aogra does not support pushing media streams to one URL repeatedly. Media options Agora does not support setting the value of publishCameraTrack and publishCustomVideoTrack as YES , or the value of publishMicrophoneTrack and publishCustomAudioTrack as YES at the same time. When choosing media setting options ( AgoraDirectCdnStreamingMediaOptions ), you can refer to the following examples: If you want to push audio and video streams published by the host to the CDN, the media setting options should be set as follows: publishCustomAudioTrack is set as YES and call the pushExternalAudioFrameSampleBuffer or pushExternalAudioFrameNSData method publishCustomVideoTrack is set as YES and call the pushExternalVideoFrame method publishCameraTrack is set as NO (the default value) publishMicrophoneTrack is set as NO (the default value) Agora only supports pushing one audio and video streams or one audio streams to CDN."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startdirectcdnstreaming(_:publishurl:mediaoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startdirectcdnstreaming(_:publishurl:mediaoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startDirectCdnStreaming(_:publishUrl:mediaOptions:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts pushing media streams to the CDN directly."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDirectCdnStreaming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingEventDelegate","preciseIdentifier":"c:objc(pl)AgoraDirectCdnStreamingEventDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publishUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startDirectCdnStreaming(_:publishUrl:mediaOptions:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startDirectCdnStreaming:publishUrl:mediaOptions:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startDirectCdnStreaming:publishUrl:mediaOptions:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions":{"role":"symbol","title":"AgoraDirectCdnStreamingMediaOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"abstract":[{"type":"text","text":"The media setting options for the host."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startDirectCdnStreaming(_:publishUrl:mediaOptions:)":{"role":"symbol","title":"startDirectCdnStreaming(_:publishUrl:mediaOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startDirectCdnStreaming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingEventDelegate","preciseIdentifier":"c:objc(pl)AgoraDirectCdnStreamingEventDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publishUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts pushing media streams to the CDN directly."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startDirectCdnStreaming(_:publishUrl:mediaOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startDirectCdnStreaming:publishUrl:mediaOptions:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startdirectcdnstreaming(_:publishurl:mediaoptions:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate":{"role":"symbol","title":"AgoraDirectCdnStreamingEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"abstract":[{"type":"text","text":"The AgoraDirectCdnStreamingEventDelegate interface class is used by the SDK to send event notifications of CDN streaming to your app. Your app can get those notifications through methods that inherit this interface class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startDirectCdnStreaming:publishUrl:mediaOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startDirectCdnStreaming:publishUrl:mediaOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startDirectCdnStreaming:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraDirectCdnStreamingEventDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraDirectCdnStreamingEventDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"publishUrl"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions","text":"AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/title","value":"AgoraDirectCdnStreamingMediaOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startDirectCdnStreaming(_:publishUrl:mediaOptions:)\/title","value":"startDirectCdnStreaming:publishUrl:mediaOptions:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startDirectCdnStreaming(_:publishUrl:mediaOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startDirectCdnStreaming:publishUrl:mediaOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/title","value":"AgoraDirectCdnStreamingEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}