{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withInterval"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"interval","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The time interval (s) between when you speak and when"},{"type":"text","text":" "},{"type":"text","text":"the recording plays back. The value range is [2, 10], and the default value"},{"type":"text","text":" "},{"type":"text","text":"is 10."}]}]},{"name":"successBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK triggers the successBlock callback if this"},{"type":"text","text":" "},{"type":"text","text":"method call is successful."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startechotest(withinterval:successblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startechotest(withinterval:successblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startEchoTest(withInterval:successBlock:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts an audio call test."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated as of v4.0.1. Use"},{"type":"text","text":" "},{"type":"text","text":"startEchoTestWithConfig instead.This method starts an audio call test to"},{"type":"text","text":" "},{"type":"text","text":"determine whether the audio devices (for example, headset and speaker) and"},{"type":"text","text":" "},{"type":"text","text":"the network connection are working properly. To conduct the test, let the"},{"type":"text","text":" "},{"type":"text","text":"user speak for a while, and the recording is played back within the set"},{"type":"text","text":" "},{"type":"text","text":"interval. If the user can hear the recording within the interval, the audio"},{"type":"text","text":" "},{"type":"text","text":"devices and network connection are working properly.Call this method before"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.After calling startEchoTestWithInterval, you must call"},{"type":"text","text":" "},{"type":"text","text":"stopEchoTest to end the test. Otherwise, the app cannot perform the next echo"},{"type":"text","text":" "},{"type":"text","text":"test, and you cannot join the channel.In the live streaming channels, only a"},{"type":"text","text":" "},{"type":"text","text":"host can call this method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startEchoTest(withInterval:successBlock:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startEchoTestWithInterval:successBlock:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startEchoTestWithInterval:successBlock:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startEchoTest(withInterval:successBlock:)":{"role":"symbol","title":"startEchoTest(withInterval:successBlock:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts an audio call test."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:This method is deprecated as of v4.0.1. Use"},{"type":"text","text":" "},{"type":"text","text":"startEchoTestWithConfig instead.This method starts an audio call test to"},{"type":"text","text":" "},{"type":"text","text":"determine whether the audio devices (for example, headset and speaker) and"},{"type":"text","text":" "},{"type":"text","text":"the network connection are working properly. To conduct the test, let the"},{"type":"text","text":" "},{"type":"text","text":"user speak for a while, and the recording is played back within the set"},{"type":"text","text":" "},{"type":"text","text":"interval. If the user can hear the recording within the interval, the audio"},{"type":"text","text":" "},{"type":"text","text":"devices and network connection are working properly.Call this method before"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.After calling startEchoTestWithInterval, you must call"},{"type":"text","text":" "},{"type":"text","text":"stopEchoTest to end the test. Otherwise, the app cannot perform the next echo"},{"type":"text","text":" "},{"type":"text","text":"test, and you cannot join the channel.In the live streaming channels, only a"},{"type":"text","text":" "},{"type":"text","text":"host can call this method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startEchoTest(withInterval:successBlock:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startEchoTestWithInterval:successBlock:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startechotest(withinterval:successblock:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startEchoTestWithInterval:successBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startEchoTestWithInterval:successBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startEchoTestWithInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"interval"},{"kind":"text","text":" "},{"kind":"identifier","text":"successBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSString *, unsigned long, long)","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#l#L)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"successBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startEchoTest(withInterval:successBlock:)\/title","value":"startEchoTestWithInterval:successBlock:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startEchoTest(withInterval:successBlock:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startEchoTestWithInterval:successBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}