{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLastmileProbeTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeConfig","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeConfig","text":"AgoraLastmileProbeConfig"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configurations of the last-mile network probe test."},{"type":"text","text":" "},{"type":"text","text":"See AgoraLastmileProbeConfig ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startlastmileprobetest(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startlastmileprobetest(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startLastmileProbeTest(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts the last mile network probe test."},{"type":"text","text":" "},{"type":"text","text":"This method starts the last-mile network probe test before joining a channel"},{"type":"text","text":" "},{"type":"text","text":"to get the uplink and downlink last mile network statistics, including the"},{"type":"text","text":" "},{"type":"text","text":"bandwidth, packet loss, jitter, and round-trip time (RTT).Once this method is"},{"type":"text","text":" "},{"type":"text","text":"enabled, the SDK returns the following callbacks: lastmileQuality : The SDK"},{"type":"text","text":" "},{"type":"text","text":"triggers this callback within two seconds depending on the network"},{"type":"text","text":" "},{"type":"text","text":"conditions. This callback rates the network conditions and is more closely"},{"type":"text","text":" "},{"type":"text","text":"linked to the user experience. lastmileProbeTestResult : The SDK triggers"},{"type":"text","text":" "},{"type":"text","text":"this callback within 30 seconds depending on the network conditions. This"},{"type":"text","text":" "},{"type":"text","text":"callback returns the real-time statistics of the network conditions and is"},{"type":"text","text":" "},{"type":"text","text":"more objective.This method applies to the following scenarios:Before a user"},{"type":"text","text":" "},{"type":"text","text":"joins a channel, call this method to check the uplink network quality.In a"},{"type":"text","text":" "},{"type":"text","text":"live streaming channel, call this method to check the uplink network quality"},{"type":"text","text":" "},{"type":"text","text":"before an audience member switches to a host.Do not call other methods before"},{"type":"text","text":" "},{"type":"text","text":"receiving the lastmileQuality and lastmileProbeTestResult callbacks."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the callbacks may be interrupted.A host should not call this"},{"type":"text","text":" "},{"type":"text","text":"method after joining a channel (when in a call)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLastmileProbeTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraLastmileProbeConfig","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeConfig"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startLastmileProbeTest(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startLastmileProbeTest:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startLastmileProbeTest:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startLastmileProbeTest(_:)":{"role":"symbol","title":"startLastmileProbeTest(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLastmileProbeTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraLastmileProbeConfig","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeConfig"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts the last mile network probe test."},{"type":"text","text":" "},{"type":"text","text":"This method starts the last-mile network probe test before joining a channel"},{"type":"text","text":" "},{"type":"text","text":"to get the uplink and downlink last mile network statistics, including the"},{"type":"text","text":" "},{"type":"text","text":"bandwidth, packet loss, jitter, and round-trip time (RTT).Once this method is"},{"type":"text","text":" "},{"type":"text","text":"enabled, the SDK returns the following callbacks: lastmileQuality : The SDK"},{"type":"text","text":" "},{"type":"text","text":"triggers this callback within two seconds depending on the network"},{"type":"text","text":" "},{"type":"text","text":"conditions. This callback rates the network conditions and is more closely"},{"type":"text","text":" "},{"type":"text","text":"linked to the user experience. lastmileProbeTestResult : The SDK triggers"},{"type":"text","text":" "},{"type":"text","text":"this callback within 30 seconds depending on the network conditions. This"},{"type":"text","text":" "},{"type":"text","text":"callback returns the real-time statistics of the network conditions and is"},{"type":"text","text":" "},{"type":"text","text":"more objective.This method applies to the following scenarios:Before a user"},{"type":"text","text":" "},{"type":"text","text":"joins a channel, call this method to check the uplink network quality.In a"},{"type":"text","text":" "},{"type":"text","text":"live streaming channel, call this method to check the uplink network quality"},{"type":"text","text":" "},{"type":"text","text":"before an audience member switches to a host.Do not call other methods before"},{"type":"text","text":" "},{"type":"text","text":"receiving the lastmileQuality and lastmileProbeTestResult callbacks."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the callbacks may be interrupted.A host should not call this"},{"type":"text","text":" "},{"type":"text","text":"method after joining a channel (when in a call)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startLastmileProbeTest(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLastmileProbeTest:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startlastmileprobetest(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeConfig":{"role":"symbol","title":"AgoraLastmileProbeConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLastmileProbeConfig"}],"abstract":[{"type":"text","text":"Configurations of the last-mile network test."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeConfig"}],"url":"\/documentation\/agorartckit\/agoralastmileprobeconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startLastmileProbeTest:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLastmileProbeTest:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startLastmileProbeTest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeConfig","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeConfig","text":"AgoraLastmileProbeConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startLastmileProbeTest(_:)\/title","value":"startLastmileProbeTest:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startLastmileProbeTest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLastmileProbeTest:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeConfig\/title","value":"AgoraLastmileProbeConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}