{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startChannelMediaRelay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration","text":"AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the media stream relay. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraChannelMediaRelayConfiguration ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -1: A general error occurs (no specified"},{"type":"text","text":" "},{"type":"text","text":"reason). -2: The parameter is invalid. -7: The method call was rejected. It"},{"type":"text","text":" "},{"type":"text","text":"may be because the SDK has not been initialized successfully, or the user"},{"type":"text","text":" "},{"type":"text","text":"role is not an host. -8: Internal state error. Probably because the user is"},{"type":"text","text":" "},{"type":"text","text":"not an audience member."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startchannelmediarelay(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startchannelmediarelay(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startChannelMediaRelay(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts relaying media streams across channels. This method can be used to"},{"type":"text","text":" "},{"type":"text","text":"implement scenarios such as co-host across channels. After a successful"},{"type":"text","text":" "},{"type":"text","text":"method call, the SDK triggers the channelMediaRelayStateDidChange and"},{"type":"text","text":" "},{"type":"text","text":"didReceiveChannelMediaRelayEvent callbacks, and these callbacks return the"},{"type":"text","text":" "},{"type":"text","text":"state and events of the media stream relay.If the"},{"type":"text","text":" "},{"type":"text","text":"channelMediaRelayStateDidChange callback returns"},{"type":"text","text":" "},{"type":"text","text":"AgoraChannelMediaRelayStateRunning (2) and AgoraChannelMediaRelayErrorNone"},{"type":"text","text":" "},{"type":"text","text":"(0), and the didReceiveChannelMediaRelayEvent callback returns"},{"type":"text","text":" "},{"type":"text","text":"AgoraChannelMediaRelayEventSentToDestinationChannel (4), it means that the"},{"type":"text","text":" "},{"type":"text","text":"SDK starts relaying media streams between the source channel and the target"},{"type":"text","text":" "},{"type":"text","text":"channel.If the channelMediaRelayStateDidChange callback"},{"type":"text","text":" "},{"type":"text","text":"returnsAgoraChannelMediaRelayStateFailure (3), an exception occurs during the"},{"type":"text","text":" "},{"type":"text","text":"media stream relay.Call this method after joining the channel.This method"},{"type":"text","text":" "},{"type":"text","text":"takes effect only when you are a host in a live streaming channel.After a"},{"type":"text","text":" "},{"type":"text","text":"successful method call, if you want to call this method again, ensure that"},{"type":"text","text":" "},{"type":"text","text":"you call the stopChannelMediaRelay method to quit the current relay.The"},{"type":"text","text":" "},{"type":"text","text":"relaying media streams across channels function needs to be enabled by"},{"type":"text","text":" "},{"type":"text","text":"contacting .We do not support string user accounts in this API."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"startChannelMediaRelay:"}],"role":"symbol","title":"startChannelMediaRelay(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startChannelMediaRelay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startChannelMediaRelay:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use startOrUpdateChannelMediaRelay instead."}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startChannelMediaRelay(_:)":{"deprecated":true,"role":"symbol","title":"startChannelMediaRelay(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startChannelMediaRelay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts relaying media streams across channels. This method can be used to"},{"type":"text","text":" "},{"type":"text","text":"implement scenarios such as co-host across channels. After a successful"},{"type":"text","text":" "},{"type":"text","text":"method call, the SDK triggers the channelMediaRelayStateDidChange and"},{"type":"text","text":" "},{"type":"text","text":"didReceiveChannelMediaRelayEvent callbacks, and these callbacks return the"},{"type":"text","text":" "},{"type":"text","text":"state and events of the media stream relay.If the"},{"type":"text","text":" "},{"type":"text","text":"channelMediaRelayStateDidChange callback returns"},{"type":"text","text":" "},{"type":"text","text":"AgoraChannelMediaRelayStateRunning (2) and AgoraChannelMediaRelayErrorNone"},{"type":"text","text":" "},{"type":"text","text":"(0), and the didReceiveChannelMediaRelayEvent callback returns"},{"type":"text","text":" "},{"type":"text","text":"AgoraChannelMediaRelayEventSentToDestinationChannel (4), it means that the"},{"type":"text","text":" "},{"type":"text","text":"SDK starts relaying media streams between the source channel and the target"},{"type":"text","text":" "},{"type":"text","text":"channel.If the channelMediaRelayStateDidChange callback"},{"type":"text","text":" "},{"type":"text","text":"returnsAgoraChannelMediaRelayStateFailure (3), an exception occurs during the"},{"type":"text","text":" "},{"type":"text","text":"media stream relay.Call this method after joining the channel.This method"},{"type":"text","text":" "},{"type":"text","text":"takes effect only when you are a host in a live streaming channel.After a"},{"type":"text","text":" "},{"type":"text","text":"successful method call, if you want to call this method again, ensure that"},{"type":"text","text":" "},{"type":"text","text":"you call the stopChannelMediaRelay method to quit the current relay.The"},{"type":"text","text":" "},{"type":"text","text":"relaying media streams across channels function needs to be enabled by"},{"type":"text","text":" "},{"type":"text","text":"contacting .We do not support string user accounts in this API."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startChannelMediaRelay(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startChannelMediaRelay:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startchannelmediarelay(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration":{"role":"symbol","title":"AgoraChannelMediaRelayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"abstract":[{"type":"text","text":"Configuration of cross channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startChannelMediaRelay:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startChannelMediaRelay:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startChannelMediaRelay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration","text":"AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startChannelMediaRelay(_:)\/title","value":"startChannelMediaRelay:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startChannelMediaRelay(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startChannelMediaRelay:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/title","value":"AgoraChannelMediaRelayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}