{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfig"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration","preciseIdentifier":"c:objc(cs)AgoraEchoTestConfiguration","text":"AgoraEchoTestConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the audio and video call loop test."},{"type":"text","text":" "},{"type":"text","text":"See AgoraEchoTestConfiguration ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startechotest(withconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/startechotest(withconfig:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startEchoTest(withConfig:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts an audio and video call loop test."},{"type":"text","text":" "},{"type":"text","text":"Before joining a channel, to test whether the user’s local sending and"},{"type":"text","text":" "},{"type":"text","text":"receiving streams are normal, you can call this method to perform an audio"},{"type":"text","text":" "},{"type":"text","text":"and video call loop test, which tests whether the audio and video devices and"},{"type":"text","text":" "},{"type":"text","text":"the user’s upstream and downstream networks are working properly.After"},{"type":"text","text":" "},{"type":"text","text":"starting the test, the user needs to make a sound or face the camera. The"},{"type":"text","text":" "},{"type":"text","text":"audio or video is output after about two seconds. If the audio playback is"},{"type":"text","text":" "},{"type":"text","text":"normal, the audio device and the user’s upstream and downstream networks are"},{"type":"text","text":" "},{"type":"text","text":"working properly; if the video playback is normal, the video device and the"},{"type":"text","text":" "},{"type":"text","text":"user’s upstream and downstream networks are working properly.Call this method"},{"type":"text","text":" "},{"type":"text","text":"before joining a channel.After calling this method, call stopEchoTest to end"},{"type":"text","text":" "},{"type":"text","text":"the test; otherwise, the user cannot perform the next audio and video call"},{"type":"text","text":" "},{"type":"text","text":"loop test and cannot join the channel.In live streaming scenarios, this"},{"type":"text","text":" "},{"type":"text","text":"method only applies to hosts."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEchoTestConfiguration","preciseIdentifier":"c:objc(cs)AgoraEchoTestConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startEchoTest(withConfig:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)startEchoTestWithConfig:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startEchoTestWithConfig:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startEchoTest(withConfig:)":{"role":"symbol","title":"startEchoTest(withConfig:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startEchoTest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEchoTestConfiguration","preciseIdentifier":"c:objc(cs)AgoraEchoTestConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Starts an audio and video call loop test."},{"type":"text","text":" "},{"type":"text","text":"Before joining a channel, to test whether the user’s local sending and"},{"type":"text","text":" "},{"type":"text","text":"receiving streams are normal, you can call this method to perform an audio"},{"type":"text","text":" "},{"type":"text","text":"and video call loop test, which tests whether the audio and video devices and"},{"type":"text","text":" "},{"type":"text","text":"the user’s upstream and downstream networks are working properly.After"},{"type":"text","text":" "},{"type":"text","text":"starting the test, the user needs to make a sound or face the camera. The"},{"type":"text","text":" "},{"type":"text","text":"audio or video is output after about two seconds. If the audio playback is"},{"type":"text","text":" "},{"type":"text","text":"normal, the audio device and the user’s upstream and downstream networks are"},{"type":"text","text":" "},{"type":"text","text":"working properly; if the video playback is normal, the video device and the"},{"type":"text","text":" "},{"type":"text","text":"user’s upstream and downstream networks are working properly.Call this method"},{"type":"text","text":" "},{"type":"text","text":"before joining a channel.After calling this method, call stopEchoTest to end"},{"type":"text","text":" "},{"type":"text","text":"the test; otherwise, the user cannot perform the next audio and video call"},{"type":"text","text":" "},{"type":"text","text":"loop test and cannot join the channel.In live streaming scenarios, this"},{"type":"text","text":" "},{"type":"text","text":"method only applies to hosts."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startEchoTest(withConfig:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startEchoTestWithConfig:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startechotest(withconfig:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration":{"role":"symbol","title":"AgoraEchoTestConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEchoTestConfiguration"}],"abstract":[{"type":"text","text":"The configuration of the audio and video call loop test."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEchoTestConfiguration"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startEchoTestWithConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startEchoTestWithConfig:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startEchoTestWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration","preciseIdentifier":"c:objc(cs)AgoraEchoTestConfiguration","text":"AgoraEchoTestConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startEchoTest(withConfig:)\/title","value":"startEchoTestWithConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startEchoTest(withConfig:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startEchoTestWithConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration\/title","value":"AgoraEchoTestConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraEchoTestConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}