{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeSnapshot"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID. Set uid as 0 if you want to take a snapshot of"},{"type":"text","text":" "},{"type":"text","text":"the local user’s video."}]}]},{"name":"filePath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The local path (including filename extensions) of the"},{"type":"text","text":" "},{"type":"text","text":"snapshot. For example:iOS: \/App Sandbox\/Library\/Caches\/example.jpgEnsure that"},{"type":"text","text":" "},{"type":"text","text":"the path you specify exists and is writable."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/takesnapshot(_:filepath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/takesnapshot(_:filepath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/takeSnapshot(_:filePath:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Takes a snapshot of a video stream."},{"type":"text","text":" "},{"type":"text","text":"This method takes a snapshot of a video stream from the specified user,"},{"type":"text","text":" "},{"type":"text","text":"generates a JPG image, and saves it to the specified path.The method is"},{"type":"text","text":" "},{"type":"text","text":"asynchronous, and the SDK has not taken the snapshot when the method call"},{"type":"text","text":" "},{"type":"text","text":"returns. After a successful method call, the SDK triggers the snapshotTaken"},{"type":"text","text":" "},{"type":"text","text":"callback to report whether the snapshot is successfully taken, as well as the"},{"type":"text","text":" "},{"type":"text","text":"details for that snapshot.Call this method after joining a channel.This"},{"type":"text","text":" "},{"type":"text","text":"method takes a snapshot of the published video stream specified in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions .If the user’s video has been preprocessed, for"},{"type":"text","text":" "},{"type":"text","text":"example, watermarked or beautified, the resulting snapshot includes the"},{"type":"text","text":" "},{"type":"text","text":"pre-processing effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeSnapshot"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"takeSnapshot(_:filePath:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)takeSnapshot:filePath:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"takeSnapshot:filePath:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/takeSnapshot(_:filePath:)":{"role":"symbol","title":"takeSnapshot(_:filePath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeSnapshot"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Takes a snapshot of a video stream."},{"type":"text","text":" "},{"type":"text","text":"This method takes a snapshot of a video stream from the specified user,"},{"type":"text","text":" "},{"type":"text","text":"generates a JPG image, and saves it to the specified path.The method is"},{"type":"text","text":" "},{"type":"text","text":"asynchronous, and the SDK has not taken the snapshot when the method call"},{"type":"text","text":" "},{"type":"text","text":"returns. After a successful method call, the SDK triggers the snapshotTaken"},{"type":"text","text":" "},{"type":"text","text":"callback to report whether the snapshot is successfully taken, as well as the"},{"type":"text","text":" "},{"type":"text","text":"details for that snapshot.Call this method after joining a channel.This"},{"type":"text","text":" "},{"type":"text","text":"method takes a snapshot of the published video stream specified in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions .If the user’s video has been preprocessed, for"},{"type":"text","text":" "},{"type":"text","text":"example, watermarked or beautified, the resulting snapshot includes the"},{"type":"text","text":" "},{"type":"text","text":"pre-processing effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/takeSnapshot(_:filePath:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"takeSnapshot:filePath:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/takesnapshot(_:filepath:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"takeSnapshot:filePath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"takeSnapshot:filePath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"takeSnapshot:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"filePath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"filePath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1takeSnapshot(_:filePath:)\/title","value":"takeSnapshot:filePath:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1takeSnapshot(_:filePath:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"takeSnapshot:filePath:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}