{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions","text":"AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/updatedirectcdnstreamingmediaoptions(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/updatedirectcdnstreamingmediaoptions(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateDirectCdnStreamingMediaOptions(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"updateDirectCdnStreamingMediaOptions(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)updateDirectCdnStreamingMediaOptions:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/updateDirectCdnStreamingMediaOptions(_:)":{"role":"symbol","title":"updateDirectCdnStreamingMediaOptions(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateDirectCdnStreamingMediaOptions(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/updatedirectcdnstreamingmediaoptions(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions":{"role":"symbol","title":"AgoraDirectCdnStreamingMediaOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"abstract":[{"type":"text","text":"The media setting options for the host."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateDirectCdnStreamingMediaOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions","text":"AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateDirectCdnStreamingMediaOptions(_:)\/title","value":"updateDirectCdnStreamingMediaOptions:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateDirectCdnStreamingMediaOptions(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDirectCdnStreamingMediaOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/title","value":"AgoraDirectCdnStreamingMediaOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}