{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannelMediaRelayEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration","text":"AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the media stream relay. See AgoraChannelMediaRelayConfiguration."}]}]},{"name":"connection","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The connection information. See AgoraRtcConnection."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated: This method is deprecated. Use startOrUpdateChannelMediaRelayEx instead. After the media relay starts, if you want to relay the media stream to more channels, or leave the current relay channel, you can call this method. After a successful method call, the SDK triggers the didReceiveChannelMediaRelayEvent callback with the AgoraChannelMediaRelayEventUpdateDestinationChannel (7) state code. Call the method after successfully calling the startChannelMediaRelayEx method and receiving channelMediaRelayStateDidChange ( AgoraChannelMediaRelayStateRunning , AgoraChannelMediaRelayErrorNone ) ; otherwise, the method call fails."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/updatechannelmediarelayex(_:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/updatechannelmediarelayex(_:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateChannelMediaRelayEx(_:connection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates the channels for media stream relay."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateChannelMediaRelayEx:connection:"}],"role":"symbol","title":"updateChannelMediaRelayEx(_:connection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannelMediaRelayEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)updateChannelMediaRelayEx:connection:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use startOrUpdateChannelMediaRelayEx instead."}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/updateChannelMediaRelayEx(_:connection:)":{"deprecated":true,"role":"symbol","title":"updateChannelMediaRelayEx(_:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannelMediaRelayEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the channels for media stream relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateChannelMediaRelayEx(_:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelMediaRelayEx:connection:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/updatechannelmediarelayex(_:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration":{"role":"symbol","title":"AgoraChannelMediaRelayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"abstract":[{"type":"text","text":"Configuration of cross channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateChannelMediaRelayEx:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelMediaRelayEx:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateChannelMediaRelayEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayConfiguration","text":"AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateChannelMediaRelayEx(_:connection:)\/title","value":"updateChannelMediaRelayEx:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateChannelMediaRelayEx(_:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelMediaRelayEx:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/title","value":"AgoraChannelMediaRelayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}