{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateScreenCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2","text":"AgoraScreenCaptureParameters2"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"parameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The screen sharing encoding parameters. The default"},{"type":"text","text":" "},{"type":"text","text":"video resolution is 1920 × 1080, that is, 2,073,600 pixels. Agora uses the"},{"type":"text","text":" "},{"type":"text","text":"value of this parameter to calculate the charges. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraScreenCaptureParameters2 ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure. -2: The parameter is invalid. -8: The"},{"type":"text","text":" "},{"type":"text","text":"screen sharing state is invalid. Probably because you have shared other"},{"type":"text","text":" "},{"type":"text","text":"screens or windows. Try calling stopScreenCapture to stop the current sharing"},{"type":"text","text":" "},{"type":"text","text":"and start sharing the screen again."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/updatescreencapture(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginekit\/updatescreencapture(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateScreenCapture(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates the screen sharing parameters."},{"type":"text","text":" "},{"type":"text","text":"If the system audio is not captured when screen sharing is enabled, and then"},{"type":"text","text":" "},{"type":"text","text":"you want to update the parameter configuration and publish the system audio,"},{"type":"text","text":" "},{"type":"text","text":"you can refer to the following steps:Call this method, and set captureAudio"},{"type":"text","text":" "},{"type":"text","text":"to YES.Call updateChannelWithMediaOptions , and set publishScreenCaptureAudio"},{"type":"text","text":" "},{"type":"text","text":"to YES to publish the audio captured by the screen.On the iOS platform,"},{"type":"text","text":" "},{"type":"text","text":"screen sharing is only available on iOS 12.0 and later."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateScreenCapture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"updateScreenCapture(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtcEngineKit(im)updateScreenCapture:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateScreenCapture:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureParameters2":{"role":"symbol","title":"AgoraScreenCaptureParameters2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"abstract":[{"type":"text","text":"Screen sharing configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}],"url":"\/documentation\/agorartckit\/agorascreencaptureparameters2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/updateScreenCapture(_:)":{"role":"symbol","title":"updateScreenCapture(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateScreenCapture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the screen sharing parameters."},{"type":"text","text":" "},{"type":"text","text":"If the system audio is not captured when screen sharing is enabled, and then"},{"type":"text","text":" "},{"type":"text","text":"you want to update the parameter configuration and publish the system audio,"},{"type":"text","text":" "},{"type":"text","text":"you can refer to the following steps:Call this method, and set captureAudio"},{"type":"text","text":" "},{"type":"text","text":"to YES.Call updateChannelWithMediaOptions , and set publishScreenCaptureAudio"},{"type":"text","text":" "},{"type":"text","text":"to YES to publish the audio captured by the screen.On the iOS platform,"},{"type":"text","text":" "},{"type":"text","text":"screen sharing is only available on iOS 12.0 and later."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateScreenCapture(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateScreenCapture:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/updatescreencapture(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateScreenCapture:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateScreenCapture:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateScreenCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureParameters2","preciseIdentifier":"c:objc(cs)AgoraScreenCaptureParameters2","text":"AgoraScreenCaptureParameters2"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/title","value":"AgoraScreenCaptureParameters2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureParameters2\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureParameters2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateScreenCapture(_:)\/title","value":"updateScreenCapture:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateScreenCapture(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateScreenCapture:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}