{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expire"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralicenseverifycode\/expire"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralicenseverifycode\/expire"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/expire","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expire"}],"title":"AgoraLicenseVerifyCode.expire","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLicenseVerifyCode@AgoraLicenseVerifyExpire","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyExpire"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/expire":{"role":"symbol","title":"AgoraLicenseVerifyCode.expire","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expire"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/expire","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyExpire"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/expire"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode":{"role":"symbol","title":"AgoraLicenseVerifyCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLicenseVerifyExpire"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyExpire"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLicenseVerifyExpire"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1expire\/title","value":"AgoraLicenseVerifyExpire"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1expire\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyExpire"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode\/title","value":"AgoraLicenseVerifyCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}