{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedPeriod"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralicenseverifycode\/limitedperiod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralicenseverifycode\/limitedperiod"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/limitedPeriod","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedPeriod"}],"title":"AgoraLicenseVerifyCode.limitedPeriod","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLicenseVerifyCode@AgoraLicenseVerifyLimitedPeriod","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyLimitedPeriod"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/limitedPeriod":{"role":"symbol","title":"AgoraLicenseVerifyCode.limitedPeriod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedPeriod"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/limitedPeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyLimitedPeriod"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/limitedperiod"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode":{"role":"symbol","title":"AgoraLicenseVerifyCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLicenseVerifyLimitedPeriod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyLimitedPeriod"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLicenseVerifyLimitedPeriod"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1limitedPeriod\/title","value":"AgoraLicenseVerifyLimitedPeriod"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1limitedPeriod\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyLimitedPeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode\/title","value":"AgoraLicenseVerifyCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}