{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterTranscoderDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate","preciseIdentifier":"c:objc(pl)AgoraH265TranscoderDelegate","text":"AgoraH265TranscoderDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The event handler for AgoraRtcEngineKit . See"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineDelegate ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The AgoraRtcMediaPlayerProtocol instance, if the method call"},{"type":"text","text":" "},{"type":"text","text":"succeeds. An empty pointer , if the method call fails."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderprotocol\/unregistertranscoderdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderprotocol\/unregistertranscoderdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/unregisterTranscoderDelegate(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"unregisterTranscoderDelegate:"}],"role":"symbol","title":"unregisterTranscoderDelegate(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterTranscoderDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscoderDelegate","preciseIdentifier":"c:objc(pl)AgoraH265TranscoderDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraH265TranscoderProtocol(im)unregisterTranscoderDelegate:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderDelegate":{"role":"symbol","title":"AgoraH265TranscoderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}],"url":"\/documentation\/agorartckit\/agorah265transcoderdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol":{"role":"symbol","title":"AgoraH265TranscoderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}],"url":"\/documentation\/agorartckit\/agorah265transcoderprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol/unregisterTranscoderDelegate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"unregisterTranscoderDelegate:"}],"role":"symbol","title":"unregisterTranscoderDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterTranscoderDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscoderDelegate","preciseIdentifier":"c:objc(pl)AgoraH265TranscoderDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/unregisterTranscoderDelegate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderprotocol\/unregistertranscoderdelegate(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unregisterTranscoderDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterTranscoderDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"unregisterTranscoderDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraH265TranscoderDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraH265TranscoderDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate\/title","value":"AgoraH265TranscoderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol\/title","value":"AgoraH265TranscoderProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1unregisterTranscoderDelegate(_:)\/title","value":"unregisterTranscoderDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1unregisterTranscoderDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterTranscoderDelegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}