{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noStream"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecordererrorcode\/nostream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecordererrorcode\/nostream"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderErrorCode\/noStream","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The SDK does not detect any audio and video streams, or audio and video streams are interrupted for more than five seconds during recording."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noStream"}],"title":"AgoraMediaRecorderErrorCode.noStream","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaRecorderErrorCode@AgoraMediaRecorderErrorCodeNoStream","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderErrorCodeNoStream"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderErrorCode/noStream":{"role":"symbol","title":"AgoraMediaRecorderErrorCode.noStream","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noStream"}],"abstract":[{"type":"text","text":"2: The SDK does not detect any audio and video streams, or audio and video streams are interrupted for more than five seconds during recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderErrorCode\/noStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderErrorCodeNoStream"}],"url":"\/documentation\/agorartckit\/agoramediarecordererrorcode\/nostream"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderErrorCode":{"role":"symbol","title":"AgoraMediaRecorderErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderErrorCode"}],"abstract":[{"type":"text","text":"The reason for the state change."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderErrorCode"}],"url":"\/documentation\/agorartckit\/agoramediarecordererrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaRecorderErrorCodeNoStream"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderErrorCodeNoStream"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaRecorderErrorCodeNoStream"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderErrorCode~1noStream\/title","value":"AgoraMediaRecorderErrorCodeNoStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderErrorCode~1noStream\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderErrorCodeNoStream"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderErrorCode\/title","value":"AgoraMediaRecorderErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}