{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opus48000High"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodingtype\/opus48000high"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodingtype\/opus48000high"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000High","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"OPUS encoding format, 48000 Hz sampling rate, high sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 3.5 MB after"},{"type":"text","text":" "},{"type":"text","text":"encoding."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opus48000High"}],"title":"AgoraAudioEncodingType.opus48000High","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioEncodingType@AgoraAudioEncodingTypeOPUS48000High","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000High"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType":{"role":"symbol","title":"AgoraAudioEncodingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodingType"}],"abstract":[{"type":"text","text":"Audio encoding type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingType"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/opus48000High":{"role":"symbol","title":"AgoraAudioEncodingType.opus48000High","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opus48000High"}],"abstract":[{"type":"text","text":"OPUS encoding format, 48000 Hz sampling rate, high sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 3.5 MB after"},{"type":"text","text":" "},{"type":"text","text":"encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000High","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000High"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/opus48000high"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEncodingTypeOPUS48000High"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000High"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000High"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType\/title","value":"AgoraAudioEncodingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus48000High\/title","value":"AgoraAudioEncodingTypeOPUS48000High"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus48000High\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000High"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}