{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRendered"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediatraceevent\/videorendered"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediatraceevent\/videorendered"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoRendered","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The video frame has been rendered."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRendered"}],"title":"AgoraMediaTraceEvent.videoRendered","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaTraceEvent@AgoraMediaTraceEventVideoRendered","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoRendered"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent/videoRendered":{"role":"symbol","title":"AgoraMediaTraceEvent.videoRendered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRendered"}],"abstract":[{"type":"text","text":"0: The video frame has been rendered."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoRendered","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoRendered"}],"url":"\/documentation\/agorartckit\/agoramediatraceevent\/videorendered"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent":{"role":"symbol","title":"AgoraMediaTraceEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"abstract":[{"type":"text","text":"The rendering state of the media frame.`"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"url":"\/documentation\/agorartckit\/agoramediatraceevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaTraceEventVideoRendered"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoRendered"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoRendered"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent~1videoRendered\/title","value":"AgoraMediaTraceEventVideoRendered"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent~1videoRendered\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoRendered"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent\/title","value":"AgoraMediaTraceEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}