{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"netError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorauploaderrorreason\/neterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorauploaderrorreason\/neterror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason\/netError","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"netError"}],"title":"AgoraUploadErrorReason.netError","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraUploadErrorReason@AgoraUploadErrorReasonNetError","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraUploadErrorReasonNetError"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUploadErrorReason/netError":{"role":"symbol","title":"AgoraUploadErrorReason.netError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"netError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason\/netError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUploadErrorReasonNetError"}],"url":"\/documentation\/agorartckit\/agorauploaderrorreason\/neterror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUploadErrorReason":{"role":"symbol","title":"AgoraUploadErrorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUploadErrorReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUploadErrorReason"}],"url":"\/documentation\/agorartckit\/agorauploaderrorreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraUploadErrorReasonNetError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraUploadErrorReasonNetError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraUploadErrorReasonNetError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason~1netError\/title","value":"AgoraUploadErrorReasonNetError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason~1netError\/fragments","value":[{"kind":"identifier","text":"AgoraUploadErrorReasonNetError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason\/title","value":"AgoraUploadErrorReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason\/fragments","value":[{"kind":"identifier","text":"AgoraUploadErrorReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}