{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorauploaderrorreason\/servererror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorauploaderrorreason\/servererror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason\/serverError","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"title":"AgoraUploadErrorReason.serverError","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraUploadErrorReason@AgoraUploadErrorReasonServerError","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraUploadErrorReasonServerError"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUploadErrorReason":{"role":"symbol","title":"AgoraUploadErrorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUploadErrorReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUploadErrorReason"}],"url":"\/documentation\/agorartckit\/agorauploaderrorreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUploadErrorReason/serverError":{"role":"symbol","title":"AgoraUploadErrorReason.serverError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUploadErrorReason\/serverError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUploadErrorReasonServerError"}],"url":"\/documentation\/agorartckit\/agorauploaderrorreason\/servererror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraUploadErrorReasonServerError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraUploadErrorReasonServerError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraUploadErrorReasonServerError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason\/title","value":"AgoraUploadErrorReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason\/fragments","value":[{"kind":"identifier","text":"AgoraUploadErrorReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason~1serverError\/title","value":"AgoraUploadErrorReasonServerError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUploadErrorReason~1serverError\/fragments","value":[{"kind":"identifier","text":"AgoraUploadErrorReasonServerError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}