{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voicePitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcaudiovolumeinfo\/voicepitch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcaudiovolumeinfo\/voicepitch"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcAudioVolumeInfo\/voicePitch","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The voice pitch of the local user. The value ranges between 0.0 and"},{"type":"text","text":" "},{"type":"text","text":"4000.0.The voicePitch parameter does not report the voice pitch of remote"},{"type":"text","text":" "},{"type":"text","text":"users. In the remote users’ callback, the value of voicePitch is always 0.0."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voicePitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"voicePitch","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcAudioVolumeInfo(py)voicePitch","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"voicePitch"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcAudioVolumeInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcAudioVolumeInfo":{"role":"symbol","title":"AgoraRtcAudioVolumeInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcAudioVolumeInfo"}],"abstract":[{"type":"text","text":"The volume information of users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcAudioVolumeInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcAudioVolumeInfo"}],"url":"\/documentation\/agorartckit\/agorartcaudiovolumeinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcAudioVolumeInfo/voicePitch":{"role":"symbol","title":"voicePitch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voicePitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The voice pitch of the local user. The value ranges between 0.0 and"},{"type":"text","text":" "},{"type":"text","text":"4000.0.The voicePitch parameter does not report the voice pitch of remote"},{"type":"text","text":" "},{"type":"text","text":"users. In the remote users’ callback, the value of voicePitch is always 0.0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcAudioVolumeInfo\/voicePitch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"voicePitch"}],"url":"\/documentation\/agorartckit\/agorartcaudiovolumeinfo\/voicepitch"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"voicePitch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"voicePitch"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"voicePitch"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcAudioVolumeInfo\/title","value":"AgoraRtcAudioVolumeInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcAudioVolumeInfo\/fragments","value":[{"kind":"identifier","text":"AgoraRtcAudioVolumeInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcAudioVolumeInfo~1voicePitch\/title","value":"voicePitch"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcAudioVolumeInfo~1voicePitch\/fragments","value":[{"kind":"identifier","text":"voicePitch"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}