{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"generalScenario"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraapplicationscenariotype\/generalscenario"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraapplicationscenariotype\/generalscenario"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType\/generalScenario","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: (Default) The general scenario."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"generalScenario"}],"title":"AgoraApplicationScenarioType.generalScenario","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraApplicationScenarioType@AgoraApplicationGeneralScenario","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraApplicationGeneralScenario"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraApplicationScenarioType":{"role":"symbol","title":"AgoraApplicationScenarioType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraApplicationScenarioType"}],"abstract":[{"type":"text","text":"The video application scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraApplicationScenarioType"}],"url":"\/documentation\/agorartckit\/agoraapplicationscenariotype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraApplicationScenarioType/generalScenario":{"role":"symbol","title":"AgoraApplicationScenarioType.generalScenario","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"generalScenario"}],"abstract":[{"type":"text","text":"0: (Default) The general scenario."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType\/generalScenario","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraApplicationGeneralScenario"}],"url":"\/documentation\/agorartckit\/agoraapplicationscenariotype\/generalscenario"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraApplicationGeneralScenario"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraApplicationGeneralScenario"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraApplicationGeneralScenario"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType\/title","value":"AgoraApplicationScenarioType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType\/fragments","value":[{"kind":"identifier","text":"AgoraApplicationScenarioType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType~1generalScenario\/title","value":"AgoraApplicationGeneralScenario"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType~1generalScenario\/fragments","value":[{"kind":"identifier","text":"AgoraApplicationGeneralScenario"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}