{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"meetingScenario"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraapplicationscenariotype\/meetingscenario"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraapplicationscenariotype\/meetingscenario"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType\/meetingScenario","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"meetingScenario"}],"title":"AgoraApplicationScenarioType.meetingScenario","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraApplicationScenarioType@AgoraApplicationMeetingScenario","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraApplicationMeetingScenario"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraApplicationScenarioType/meetingScenario":{"role":"symbol","title":"AgoraApplicationScenarioType.meetingScenario","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"meetingScenario"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType\/meetingScenario","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraApplicationMeetingScenario"}],"url":"\/documentation\/agorartckit\/agoraapplicationscenariotype\/meetingscenario"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraApplicationScenarioType":{"role":"symbol","title":"AgoraApplicationScenarioType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraApplicationScenarioType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraApplicationScenarioType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraApplicationScenarioType"}],"url":"\/documentation\/agorartckit\/agoraapplicationscenariotype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraApplicationMeetingScenario"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraApplicationMeetingScenario"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraApplicationMeetingScenario"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType~1meetingScenario\/title","value":"AgoraApplicationMeetingScenario"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType~1meetingScenario\/fragments","value":[{"kind":"identifier","text":"AgoraApplicationMeetingScenario"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType\/title","value":"AgoraApplicationScenarioType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraApplicationScenarioType\/fragments","value":[{"kind":"identifier","text":"AgoraApplicationScenarioType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}