{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderContainerFormat","preciseIdentifier":"c:@E@AgoraMediaRecorderContainerFormat","text":"AgoraMediaRecorderContainerFormat"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration\/containerformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration\/containerformat"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/containerFormat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The format of the recording file. See AgoraMediaRecorderContainerFormat ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderContainerFormat","preciseIdentifier":"c:@E@AgoraMediaRecorderContainerFormat"}],"title":"containerFormat","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraMediaRecorderConfiguration(py)containerFormat","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"containerFormat"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/containerFormat":{"role":"symbol","title":"containerFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderContainerFormat","preciseIdentifier":"c:@E@AgoraMediaRecorderContainerFormat"}],"abstract":[{"type":"text","text":"The format of the recording file. See AgoraMediaRecorderContainerFormat ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/containerFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"containerFormat"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/containerformat"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderContainerFormat":{"role":"symbol","title":"AgoraMediaRecorderContainerFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderContainerFormat"}],"abstract":[{"type":"text","text":"The format of the recording file."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderContainerFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderContainerFormat"}],"url":"\/documentation\/agorartckit\/agoramediarecordercontainerformat"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration":{"role":"symbol","title":"AgoraMediaRecorderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"abstract":[{"type":"text","text":"Configurations for the local audio and video recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"containerFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"containerFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderContainerFormat","preciseIdentifier":"c:@E@AgoraMediaRecorderContainerFormat","text":"AgoraMediaRecorderContainerFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerFormat"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1containerFormat\/title","value":"containerFormat"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1containerFormat\/fragments","value":[{"kind":"identifier","text":"containerFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderContainerFormat\/title","value":"AgoraMediaRecorderContainerFormat"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderContainerFormat\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderContainerFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/title","value":"AgoraMediaRecorderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}