{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recorderInfoUpdateInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration\/recorderinfoupdateinterval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration\/recorderinfoupdateinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/recorderInfoUpdateInterval","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The interval (ms) of updating the recording information. The value range is"},{"type":"text","text":" "},{"type":"text","text":"[1000,10000]. Based on the value you set in this parameter, the SDK triggers"},{"type":"text","text":" "},{"type":"text","text":"the informationDidUpdated callback to report the updated recording"},{"type":"text","text":" "},{"type":"text","text":"information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recorderInfoUpdateInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"recorderInfoUpdateInterval","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraMediaRecorderConfiguration(py)recorderInfoUpdateInterval","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"recorderInfoUpdateInterval"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration":{"role":"symbol","title":"AgoraMediaRecorderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"abstract":[{"type":"text","text":"Configurations for the local audio and video recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/recorderInfoUpdateInterval":{"role":"symbol","title":"recorderInfoUpdateInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recorderInfoUpdateInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The interval (ms) of updating the recording information. The value range is"},{"type":"text","text":" "},{"type":"text","text":"[1000,10000]. Based on the value you set in this parameter, the SDK triggers"},{"type":"text","text":" "},{"type":"text","text":"the informationDidUpdated callback to report the updated recording"},{"type":"text","text":" "},{"type":"text","text":"information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/recorderInfoUpdateInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recorderInfoUpdateInterval"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/recorderinfoupdateinterval"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recorderInfoUpdateInterval"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recorderInfoUpdateInterval"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"recorderInfoUpdateInterval"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/title","value":"AgoraMediaRecorderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1recorderInfoUpdateInterval\/title","value":"recorderInfoUpdateInterval"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1recorderInfoUpdateInterval\/fragments","value":[{"kind":"identifier","text":"recorderInfoUpdateInterval"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}