{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderStreamType","preciseIdentifier":"c:@E@AgoraMediaRecorderStreamType","text":"AgoraMediaRecorderStreamType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration\/streamtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration\/streamtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/streamType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The recording content. See AgoraMediaRecorderStreamType ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderStreamType","preciseIdentifier":"c:@E@AgoraMediaRecorderStreamType"}],"title":"streamType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraMediaRecorderConfiguration(py)streamType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"streamType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration":{"role":"symbol","title":"AgoraMediaRecorderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"abstract":[{"type":"text","text":"Configurations for the local audio and video recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderStreamType":{"role":"symbol","title":"AgoraMediaRecorderStreamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderStreamType"}],"abstract":[{"type":"text","text":"The recording content."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderStreamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderStreamType"}],"url":"\/documentation\/agorartckit\/agoramediarecorderstreamtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/streamType":{"role":"symbol","title":"streamType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderStreamType","preciseIdentifier":"c:@E@AgoraMediaRecorderStreamType"}],"abstract":[{"type":"text","text":"The recording content. See AgoraMediaRecorderStreamType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/streamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"streamType"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/streamtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"streamType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"streamType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderStreamType","preciseIdentifier":"c:@E@AgoraMediaRecorderStreamType","text":"AgoraMediaRecorderStreamType"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/title","value":"AgoraMediaRecorderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderStreamType\/title","value":"AgoraMediaRecorderStreamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderStreamType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderStreamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1streamType\/title","value":"streamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1streamType\/fragments","value":[{"kind":"identifier","text":"streamType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}