{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dryLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioreverbtype\/drylevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioreverbtype\/drylevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/dryLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The level of the dry signal (dB). The value is between -20 and 10."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dryLevel"}],"title":"AgoraAudioReverbType.dryLevel","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioReverbType@AgoraAudioReverbDryLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbDryLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/dryLevel":{"role":"symbol","title":"AgoraAudioReverbType.dryLevel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dryLevel"}],"abstract":[{"type":"text","text":"0: The level of the dry signal (dB). The value is between -20 and 10."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/dryLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbDryLevel"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/drylevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType":{"role":"symbol","title":"AgoraAudioReverbType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbType"}],"abstract":[{"type":"text","text":"Audio reverberation types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbType"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioReverbDryLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbDryLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioReverbDryLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1dryLevel\/title","value":"AgoraAudioReverbDryLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1dryLevel\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbDryLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/title","value":"AgoraAudioReverbType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}