{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wetDelay"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioreverbtype\/wetdelay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioreverbtype\/wetdelay"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetDelay","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The length of the initial delay of the wet signal (ms). The value is between 0 and 200."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wetDelay"}],"title":"AgoraAudioReverbType.wetDelay","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioReverbType@AgoraAudioReverbWetDelay","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbWetDelay"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType":{"role":"symbol","title":"AgoraAudioReverbType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbType"}],"abstract":[{"type":"text","text":"Audio reverberation types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbType"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/wetDelay":{"role":"symbol","title":"AgoraAudioReverbType.wetDelay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wetDelay"}],"abstract":[{"type":"text","text":"3: The length of the initial delay of the wet signal (ms). The value is between 0 and 200."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbWetDelay"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/wetdelay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioReverbWetDelay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbWetDelay"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioReverbWetDelay"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/title","value":"AgoraAudioReverbType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1wetDelay\/title","value":"AgoraAudioReverbWetDelay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1wetDelay\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbWetDelay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}