{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel","preciseIdentifier":"c:@E@AgoraLowlightEnhanceLevel","text":"AgoraLowlightEnhanceLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralowlightenhanceoptions\/level"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralowlightenhanceoptions\/level"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions\/level","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The low-light enhancement level."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLowlightEnhanceLevel","preciseIdentifier":"c:@E@AgoraLowlightEnhanceLevel"}],"title":"level","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLowlightEnhanceOptions(py)level","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"level"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceOptions/level":{"role":"symbol","title":"level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLowlightEnhanceLevel","preciseIdentifier":"c:@E@AgoraLowlightEnhanceLevel"}],"abstract":[{"type":"text","text":"The low-light enhancement level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions\/level","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"level"}],"url":"\/documentation\/agorartckit\/agoralowlightenhanceoptions\/level"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceOptions":{"role":"symbol","title":"AgoraLowlightEnhanceOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}],"abstract":[{"type":"text","text":"The low-light enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}],"url":"\/documentation\/agorartckit\/agoralowlightenhanceoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceLevel":{"role":"symbol","title":"AgoraLowlightEnhanceLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}],"abstract":[{"type":"text","text":"The low-light enhancement level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}],"url":"\/documentation\/agorartckit\/agoralowlightenhancelevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"level"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"level"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel","preciseIdentifier":"c:@E@AgoraLowlightEnhanceLevel","text":"AgoraLowlightEnhanceLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions~1level\/title","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions~1level\/fragments","value":[{"kind":"identifier","text":"level"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions\/title","value":"AgoraLowlightEnhanceOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel\/title","value":"AgoraLowlightEnhanceLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}