{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceMode","preciseIdentifier":"c:@E@AgoraLowlightEnhanceMode","text":"AgoraLowlightEnhanceMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralowlightenhanceoptions\/mode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralowlightenhanceoptions\/mode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions\/mode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The low-light enhancement mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLowlightEnhanceMode","preciseIdentifier":"c:@E@AgoraLowlightEnhanceMode"}],"title":"mode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLowlightEnhanceOptions(py)mode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"mode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceOptions":{"role":"symbol","title":"AgoraLowlightEnhanceOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}],"abstract":[{"type":"text","text":"The low-light enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}],"url":"\/documentation\/agorartckit\/agoralowlightenhanceoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceOptions/mode":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLowlightEnhanceMode","preciseIdentifier":"c:@E@AgoraLowlightEnhanceMode"}],"abstract":[{"type":"text","text":"The low-light enhancement mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceOptions\/mode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mode"}],"url":"\/documentation\/agorartckit\/agoralowlightenhanceoptions\/mode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceMode":{"role":"symbol","title":"AgoraLowlightEnhanceMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLowlightEnhanceMode"}],"abstract":[{"type":"text","text":"The low-light enhancement mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceMode"}],"url":"\/documentation\/agorartckit\/agoralowlightenhancemode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceMode","preciseIdentifier":"c:@E@AgoraLowlightEnhanceMode","text":"AgoraLowlightEnhanceMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions\/title","value":"AgoraLowlightEnhanceOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions~1mode\/title","value":"mode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceOptions~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceMode\/title","value":"AgoraLowlightEnhanceMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceMode\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}