{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPreLoadEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"songCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"percent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lyricUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterPreloadStatus","preciseIdentifier":"c:@E@AgoraMusicContentCenterPreloadStatus","text":"AgoraMusicContentCenterPreloadStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode","text":"AgoraMusicContentCenterStatusCode"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate\/onpreloadevent(_:percent:lyricurl:status:errorcode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate\/onpreloadevent(_:percent:lyricurl:status:errorcode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"}],"role":"symbol","title":"onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPreLoadEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"percent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lyricUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterPreloadStatus","preciseIdentifier":"c:@E@AgoraMusicContentCenterPreloadStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraMusicContentCenterEventDelegate(im)onPreLoadEvent:percent:lyricUrl:status:errorCode:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterEventDelegate/onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)":{"navigatorTitle":[{"kind":"identifier","text":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"}],"role":"symbol","title":"onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPreLoadEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"percent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lyricUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterPreloadStatus","preciseIdentifier":"c:@E@AgoraMusicContentCenterPreloadStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate\/onpreloadevent(_:percent:lyricurl:status:errorcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterEventDelegate":{"role":"symbol","title":"AgoraMusicContentCenterEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterPreloadStatus":{"role":"symbol","title":"AgoraMusicContentCenterPreloadStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatus"}],"abstract":[{"type":"text","text":"The loading statuses of music assets."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterPreloadStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatus"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterpreloadstatus"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterStatusCode":{"role":"symbol","title":"AgoraMusicContentCenterStatusCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterstatuscode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPreLoadEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"songCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"percent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"percent"},{"kind":"text","text":" "},{"kind":"identifier","text":"lyricUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lyricUrl"},{"kind":"text","text":" "},{"kind":"identifier","text":"status:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterPreloadStatus","preciseIdentifier":"c:@E@AgoraMusicContentCenterPreloadStatus","text":"AgoraMusicContentCenterPreloadStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode","text":"AgoraMusicContentCenterStatusCode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"errorCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)\/title","value":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate\/title","value":"AgoraMusicContentCenterEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterPreloadStatus\/title","value":"AgoraMusicContentCenterPreloadStatus"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterPreloadStatus\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterPreloadStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/title","value":"AgoraMusicContentCenterStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterStatusCode\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterStatusCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}