{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"climaxSegmentList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClimaxSegment","preciseIdentifier":"c:objc(cs)AgoraClimaxSegment","text":"AgoraClimaxSegment"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusic\/climaxsegmentlist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusic\/climaxsegmentlist"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/climaxSegmentList","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"climaxSegmentList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraClimaxSegment","preciseIdentifier":"c:objc(cs)AgoraClimaxSegment"},{"kind":"text","text":"]"}],"title":"climaxSegmentList","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraMusic(py)climaxSegmentList","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"climaxSegmentList"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClimaxSegment":{"role":"symbol","title":"AgoraClimaxSegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClimaxSegment"}],"abstract":[{"type":"text","text":"The climax parts of the music."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClimaxSegment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClimaxSegment"}],"url":"\/documentation\/agorartckit\/agoraclimaxsegment"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic":{"role":"symbol","title":"AgoraMusic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusic"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusic"}],"url":"\/documentation\/agorartckit\/agoramusic"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/climaxSegmentList":{"role":"symbol","title":"climaxSegmentList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"climaxSegmentList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraClimaxSegment","preciseIdentifier":"c:objc(cs)AgoraClimaxSegment"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/climaxSegmentList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"climaxSegmentList"}],"url":"\/documentation\/agorartckit\/agoramusic\/climaxsegmentlist"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"climaxSegmentList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"climaxSegmentList"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<AgoraClimaxSegment *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"climaxSegmentList"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClimaxSegment\/title","value":"AgoraClimaxSegment"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClimaxSegment\/fragments","value":[{"kind":"identifier","text":"AgoraClimaxSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic\/title","value":"AgoraMusic"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic\/fragments","value":[{"kind":"identifier","text":"AgoraMusic"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1climaxSegmentList\/title","value":"climaxSegmentList"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1climaxSegmentList\/fragments","value":[{"kind":"identifier","text":"climaxSegmentList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}