{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedFrameOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideosubscriptionoptions\/encodedframeonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideosubscriptionoptions\/encodedframeonly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions\/encodedFrameOnly","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether to subscribe to encoded video frames only:YES: Subscribe to the"},{"type":"text","text":" "},{"type":"text","text":"encoded video data (structured data) only; the SDK does not decode or render"},{"type":"text","text":" "},{"type":"text","text":"raw video data.NO: (Default) Subscribe to both raw video data and encoded"},{"type":"text","text":" "},{"type":"text","text":"video data."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedFrameOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"encodedFrameOnly","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoSubscriptionOptions(py)encodedFrameOnly","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"encodedFrameOnly"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSubscriptionOptions":{"role":"symbol","title":"AgoraVideoSubscriptionOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}],"url":"\/documentation\/agorartckit\/agoravideosubscriptionoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSubscriptionOptions/encodedFrameOnly":{"role":"symbol","title":"encodedFrameOnly","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedFrameOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to subscribe to encoded video frames only:YES: Subscribe to the"},{"type":"text","text":" "},{"type":"text","text":"encoded video data (structured data) only; the SDK does not decode or render"},{"type":"text","text":" "},{"type":"text","text":"raw video data.NO: (Default) Subscribe to both raw video data and encoded"},{"type":"text","text":" "},{"type":"text","text":"video data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSubscriptionOptions\/encodedFrameOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodedFrameOnly"}],"url":"\/documentation\/agorartckit\/agoravideosubscriptionoptions\/encodedframeonly"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"encodedFrameOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"encodedFrameOnly"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedFrameOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions\/title","value":"AgoraVideoSubscriptionOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSubscriptionOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions~1encodedFrameOnly\/title","value":"encodedFrameOnly"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSubscriptionOptions~1encodedFrameOnly\/fragments","value":[{"kind":"identifier","text":"encodedFrameOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}