{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedVideoFrame"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraexternalvideosourcetype\/encodedvideoframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraexternalvideosourcetype\/encodedvideoframe"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExternalVideoSourceType\/encodedVideoFrame","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedVideoFrame"}],"title":"AgoraExternalVideoSourceType.encodedVideoFrame","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraExternalVideoSourceType@AgoraExternalVideoSourceTypeEncodedVideoFrame","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraExternalVideoSourceTypeEncodedVideoFrame"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExternalVideoSourceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExternalVideoSourceType/encodedVideoFrame":{"role":"symbol","title":"AgoraExternalVideoSourceType.encodedVideoFrame","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedVideoFrame"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExternalVideoSourceType\/encodedVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExternalVideoSourceTypeEncodedVideoFrame"}],"url":"\/documentation\/agorartckit\/agoraexternalvideosourcetype\/encodedvideoframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExternalVideoSourceType":{"role":"symbol","title":"AgoraExternalVideoSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExternalVideoSourceType"}],"abstract":[{"type":"text","text":"The external video frame encoding type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExternalVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExternalVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoraexternalvideosourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraExternalVideoSourceTypeEncodedVideoFrame"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraExternalVideoSourceTypeEncodedVideoFrame"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraExternalVideoSourceTypeEncodedVideoFrame"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExternalVideoSourceType~1encodedVideoFrame\/title","value":"AgoraExternalVideoSourceTypeEncodedVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExternalVideoSourceType~1encodedVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraExternalVideoSourceTypeEncodedVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExternalVideoSourceType\/title","value":"AgoraExternalVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExternalVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraExternalVideoSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}