{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedContentCenter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig","preciseIdentifier":"c:objc(cs)AgoraMusicContentCenterConfig","text":"AgoraMusicContentCenterConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenter\/sharedcontentcenter(config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenter\/sharedcontentcenter(config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/sharedContentCenter(config:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedContentCenter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterConfig","preciseIdentifier":"c:objc(cs)AgoraMusicContentCenterConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"?"}],"title":"sharedContentCenter(config:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraMusicContentCenter(cm)sharedContentCenterWithConfig:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"sharedContentCenterWithConfig:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/sharedContentCenter(config:)":{"role":"symbol","title":"sharedContentCenter(config:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedContentCenter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterConfig","preciseIdentifier":"c:objc(cs)AgoraMusicContentCenterConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/sharedContentCenter(config:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedContentCenterWithConfig:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/sharedcontentcenter(config:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter":{"role":"symbol","title":"AgoraMusicContentCenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenter"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenter"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterConfig":{"role":"symbol","title":"AgoraMusicContentCenterConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"sharedContentCenterWithConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedContentCenterWithConfig:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"sharedContentCenterWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig","preciseIdentifier":"c:objc(cs)AgoraMusicContentCenterConfig","text":"AgoraMusicContentCenterConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1sharedContentCenter(config:)\/title","value":"sharedContentCenterWithConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1sharedContentCenter(config:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedContentCenterWithConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter\/title","value":"AgoraMusicContentCenter"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig\/title","value":"AgoraMusicContentCenterConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}