{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction","text":"AgoraAudioSessionOperationRestriction"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/configuresession"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/configuresession"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/configureSession","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"}],"title":"configureSession","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@AgoraAudioSessionOperationRestriction@AgoraAudioSessionOperationRestrictionConfigureSession","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionConfigureSession"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction":{"role":"symbol","title":"AgoraAudioSessionOperationRestriction","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/configureSession":{"role":"symbol","title":"configureSession","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/configureSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionConfigureSession"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/configuresession"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioSessionOperationRestrictionConfigureSession"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionConfigureSession"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionConfigureSession"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction\/title","value":"AgoraAudioSessionOperationRestriction"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1configureSession\/title","value":"AgoraAudioSessionOperationRestrictionConfigureSession"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1configureSession\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionConfigureSession"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}