{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playback"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/playback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/playback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/playback","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Only records the audio of all remote users."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playback"}],"title":"AgoraAudioFileRecordingType.playback","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioFileRecordingType@AgoraAudioFileRecordingTypePlayback","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypePlayback"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType":{"role":"symbol","title":"AgoraAudioFileRecordingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"abstract":[{"type":"text","text":"Recording content. Set in startAudioRecording [2\/2] ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType/playback":{"role":"symbol","title":"AgoraAudioFileRecordingType.playback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playback"}],"abstract":[{"type":"text","text":"2: Only records the audio of all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/playback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypePlayback"}],"url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/playback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioFileRecordingTypePlayback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypePlayback"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypePlayback"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType\/title","value":"AgoraAudioFileRecordingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1playback\/title","value":"AgoraAudioFileRecordingTypePlayback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1playback\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypePlayback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}