{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientRoleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcchannelmediaoptions\/clientroletype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcchannelmediaoptions\/clientroletype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/clientRoleType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user role. See AgoraClientRole."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientRoleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"}],"title":"clientRoleType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcChannelMediaOptions(py)clientRoleType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"clientRoleType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions":{"role":"symbol","title":"AgoraRtcChannelMediaOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}],"abstract":[{"type":"text","text":"The channel media options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRole":{"role":"symbol","title":"AgoraClientRole","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRole"}],"abstract":[{"type":"text","text":"The user role in the interactive live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRole"}],"url":"\/documentation\/agorartckit\/agoraclientrole"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/clientRoleType":{"role":"symbol","title":"clientRoleType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientRoleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"}],"abstract":[{"type":"text","text":"The user role. See AgoraClientRole."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/clientRoleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientRoleType"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/clientroletype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clientRoleType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientRoleType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole","text":"AgoraClientRole"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientRoleType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions\/title","value":"AgoraRtcChannelMediaOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions\/fragments","value":[{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRole\/title","value":"AgoraClientRole"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRole\/fragments","value":[{"kind":"identifier","text":"AgoraClientRole"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1clientRoleType\/title","value":"clientRoleType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1clientRoleType\/fragments","value":[{"kind":"identifier","text":"clientRoleType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}