{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band4K"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band4k"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band4k"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band4K","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"7: 4 kHz"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band4K"}],"title":"AgoraAudioEqualizationBandFrequency.band4K","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioEqualizationBandFrequency@AgoraAudioEqualizationBand4K","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand4K"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band4K":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band4K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band4K"}],"abstract":[{"type":"text","text":"7: 4 kHz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band4K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand4K"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band4k"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"abstract":[{"type":"text","text":"The midrange frequency for audio equalization."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEqualizationBand4K"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand4K"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioEqualizationBand4K"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band4K\/title","value":"AgoraAudioEqualizationBand4K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band4K\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand4K"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency\/title","value":"AgoraAudioEqualizationBandFrequency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}