{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoInputStreams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream","preciseIdentifier":"c:objc(cs)AgoraTranscodingVideoStream","text":"AgoraTranscodingVideoStream"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocaltranscoderconfiguration\/videoinputstreams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocaltranscoderconfiguration\/videoinputstreams"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoInputStreams","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoInputStreams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraTranscodingVideoStream","preciseIdentifier":"c:objc(cs)AgoraTranscodingVideoStream"},{"kind":"text","text":"]?"}],"title":"videoInputStreams","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLocalTranscoderConfiguration(py)videoInputStreams","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"videoInputStreams"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalTranscoderConfiguration/videoInputStreams":{"role":"symbol","title":"videoInputStreams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoInputStreams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraTranscodingVideoStream","preciseIdentifier":"c:objc(cs)AgoraTranscodingVideoStream"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoInputStreams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoInputStreams"}],"url":"\/documentation\/agorartckit\/agoralocaltranscoderconfiguration\/videoinputstreams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalTranscoderConfiguration":{"role":"symbol","title":"AgoraLocalTranscoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoralocaltranscoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream":{"role":"symbol","title":"AgoraTranscodingVideoStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraTranscodingVideoStream"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraTranscodingVideoStream"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoInputStreams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoInputStreams"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<AgoraTranscodingVideoStream *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"videoInputStreams"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1videoInputStreams\/title","value":"videoInputStreams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1videoInputStreams\/fragments","value":[{"kind":"identifier","text":"videoInputStreams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration\/title","value":"AgoraLocalTranscoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream\/title","value":"AgoraTranscodingVideoStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream\/fragments","value":[{"kind":"identifier","text":"AgoraTranscodingVideoStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}