{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES256XTS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionmode\/aes256xts"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionmode\/aes256xts"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256XTS","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: 256-bit AES encryption, XTS mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES256XTS"}],"title":"AgoraEncryptionMode.AES256XTS","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraEncryptionMode@AgoraEncryptionModeAES256XTS","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES256XTS"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES256XTS":{"role":"symbol","title":"AgoraEncryptionMode.AES256XTS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES256XTS"}],"abstract":[{"type":"text","text":"3: 256-bit AES encryption, XTS mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256XTS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES256XTS"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes256xts"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode":{"role":"symbol","title":"AgoraEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"}],"abstract":[{"type":"text","text":"The built-in encryption mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionMode"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncryptionModeAES256XTS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES256XTS"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraEncryptionModeAES256XTS"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256XTS\/title","value":"AgoraEncryptionModeAES256XTS"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256XTS\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES256XTS"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/title","value":"AgoraEncryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}