{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionmode\/end"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionmode\/end"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/end","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"8: 256-bit AES encryption, GCM mode. This encryption mode requires the"},{"type":"text","text":" "},{"type":"text","text":"setting of salt (encryptionKdfSalt)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"}],"title":"AgoraEncryptionMode.end","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraEncryptionMode@AgoraEncryptionModeEnd","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeEnd"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode":{"role":"symbol","title":"AgoraEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"}],"abstract":[{"type":"text","text":"The built-in encryption mode."},{"type":"text","text":" "},{"type":"text","text":"Agora recommends using AgoraEncryptionModeAES128GCM2 or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncryptionModeAES256GCM2 encrypted mode. These two modes support the use"},{"type":"text","text":" "},{"type":"text","text":"of salt for higher security."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionMode"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/end":{"role":"symbol","title":"AgoraEncryptionMode.end","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"}],"abstract":[{"type":"text","text":"8: 256-bit AES encryption, GCM mode. This encryption mode requires the"},{"type":"text","text":" "},{"type":"text","text":"setting of salt (encryptionKdfSalt)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/end","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeEnd"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/end"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncryptionModeEnd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeEnd"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraEncryptionModeEnd"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/title","value":"AgoraEncryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1end\/title","value":"AgoraEncryptionModeEnd"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1end\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeEnd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}