{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SM4128ECB"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionmode\/sm4128ecb"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionmode\/sm4128ecb"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/SM4128ECB","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: 128-bit SM4 encryption, ECB mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SM4128ECB"}],"title":"AgoraEncryptionMode.SM4128ECB","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraEncryptionMode@AgoraEncryptionModeSM4128ECB","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeSM4128ECB"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/SM4128ECB":{"role":"symbol","title":"AgoraEncryptionMode.SM4128ECB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SM4128ECB"}],"abstract":[{"type":"text","text":"4: 128-bit SM4 encryption, ECB mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/SM4128ECB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeSM4128ECB"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/sm4128ecb"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode":{"role":"symbol","title":"AgoraEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"}],"abstract":[{"type":"text","text":"The built-in encryption mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionMode"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncryptionModeSM4128ECB"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeSM4128ECB"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraEncryptionModeSM4128ECB"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1SM4128ECB\/title","value":"AgoraEncryptionModeSM4128ECB"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1SM4128ECB\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeSM4128ECB"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/title","value":"AgoraEncryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}