{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"unowned(unsafe)"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pixelBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraoutputvideoframe\/pixelbuffer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraoutputvideoframe\/pixelbuffer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame\/pixelBuffer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fills the data to CVPixelBuffer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pixelBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"?"}],"title":"pixelBuffer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraOutputVideoFrame(py)pixelBuffer","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"pixelBuffer"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraOutputVideoFrame":{"role":"symbol","title":"AgoraOutputVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"abstract":[{"type":"text","text":"Configurations of the video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"url":"\/documentation\/agorartckit\/agoraoutputvideoframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraOutputVideoFrame/pixelBuffer":{"role":"symbol","title":"pixelBuffer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pixelBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Fills the data to CVPixelBuffer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame\/pixelBuffer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pixelBuffer"}],"url":"\/documentation\/agorartckit\/agoraoutputvideoframe\/pixelbuffer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"pixelBuffer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pixelBuffer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__CVBuffer","preciseIdentifier":"c:@S@__CVBuffer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"pixelBuffer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/title","value":"AgoraOutputVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame~1pixelBuffer\/title","value":"pixelBuffer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame~1pixelBuffer\/fragments","value":[{"kind":"identifier","text":"pixelBuffer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}