{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canNotOpen"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/cannotopen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/cannotopen"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/canNotOpen","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canNotOpen"}],"title":"AgoraAudioMixingReasonCode.canNotOpen","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioMixingReasonCode@AgoraAudioMixingReasonCanNotOpen","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCanNotOpen"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode":{"role":"symbol","title":"AgoraAudioMixingReasonCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"abstract":[{"type":"text","text":"The reason why the playback state of the music file changes. Reported in the"},{"type":"text","text":" "},{"type":"text","text":"audioMixingStateChanged callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/canNotOpen":{"role":"symbol","title":"AgoraAudioMixingReasonCode.canNotOpen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canNotOpen"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/canNotOpen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCanNotOpen"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/cannotopen"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioMixingReasonCanNotOpen"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCanNotOpen"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioMixingReasonCanNotOpen"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/title","value":"AgoraAudioMixingReasonCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1canNotOpen\/title","value":"AgoraAudioMixingReasonCanNotOpen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1canNotOpen\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCanNotOpen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}