{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneLoopCompleted"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/oneloopcompleted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/oneloopcompleted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/oneLoopCompleted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"721: The music file completes a loop playback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneLoopCompleted"}],"title":"AgoraAudioMixingReasonCode.oneLoopCompleted","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioMixingReasonCode@AgoraAudioMixingReasonOneLoopCompleted","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonOneLoopCompleted"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode":{"role":"symbol","title":"AgoraAudioMixingReasonCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"abstract":[{"type":"text","text":"The reason why the playback state of the music file changes. Reported in the audioMixingStateChanged callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/oneLoopCompleted":{"role":"symbol","title":"AgoraAudioMixingReasonCode.oneLoopCompleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneLoopCompleted"}],"abstract":[{"type":"text","text":"721: The music file completes a loop playback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/oneLoopCompleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonOneLoopCompleted"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/oneloopcompleted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioMixingReasonOneLoopCompleted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonOneLoopCompleted"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioMixingReasonOneLoopCompleted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/title","value":"AgoraAudioMixingReasonCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1oneLoopCompleted\/title","value":"AgoraAudioMixingReasonOneLoopCompleted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1oneLoopCompleted\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonOneLoopCompleted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}