{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooFrequentlyCall"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/toofrequentlycall"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/toofrequentlycall"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/tooFrequentlyCall","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooFrequentlyCall"}],"title":"AgoraAudioMixingReasonCode.tooFrequentlyCall","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioMixingReasonCode@AgoraAudioMixingReasonTooFrequentlyCall","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonTooFrequentlyCall"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode":{"role":"symbol","title":"AgoraAudioMixingReasonCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"abstract":[{"type":"text","text":"The reason why the playback state of the music file changes. Reported in the audioMixingStateChanged callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/tooFrequentlyCall":{"role":"symbol","title":"AgoraAudioMixingReasonCode.tooFrequentlyCall","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooFrequentlyCall"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/tooFrequentlyCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonTooFrequentlyCall"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/toofrequentlycall"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioMixingReasonTooFrequentlyCall"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonTooFrequentlyCall"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioMixingReasonTooFrequentlyCall"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/title","value":"AgoraAudioMixingReasonCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1tooFrequentlyCall\/title","value":"AgoraAudioMixingReasonTooFrequentlyCall"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1tooFrequentlyCall\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonTooFrequentlyCall"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}