{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate\/idle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate\/idle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/idle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The initial publishing state after joining the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"title":"AgoraStreamSubscribeState.idle","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraStreamSubscribeState@AgoraStreamSubscribeStateIdle","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateIdle"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState":{"role":"symbol","title":"AgoraStreamSubscribeState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"abstract":[{"type":"text","text":"The subscribing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/idle":{"role":"symbol","title":"AgoraStreamSubscribeState.idle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"abstract":[{"type":"text","text":"0: The initial publishing state after joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/idle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateIdle"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/idle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamSubscribeStateIdle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateIdle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraStreamSubscribeStateIdle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/title","value":"AgoraStreamSubscribeState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1idle\/title","value":"AgoraStreamSubscribeStateIdle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1idle\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateIdle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}