{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noSubscribed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate\/nosubscribed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate\/nosubscribed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/noSubscribed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Fails to subscribe to the remote stream. Possible reasons:The remote"},{"type":"text","text":" "},{"type":"text","text":"user:Calls muteLocalAudioStream (YES) or muteLocalVideoStream (YES) to stop"},{"type":"text","text":" "},{"type":"text","text":"sending local media stream.Calls disableAudio or disableVideo to disable"},{"type":"text","text":" "},{"type":"text","text":"the local audio or video module.Calls enableLocalAudio (NO) or"},{"type":"text","text":" "},{"type":"text","text":"enableLocalVideo (NO) to disable local audio or video capture.The role of"},{"type":"text","text":" "},{"type":"text","text":"the remote user is audience.The local user calls the following methods to"},{"type":"text","text":" "},{"type":"text","text":"stop receiving remote streams:Call muteRemoteAudioStream (YES) or"},{"type":"text","text":" "},{"type":"text","text":"muteAllRemoteAudioStreams (YES) to stop receiving the remote audio"},{"type":"text","text":" "},{"type":"text","text":"stream.Call muteRemoteVideoStream (YES) or muteAllRemoteVideoStreams (YES)"},{"type":"text","text":" "},{"type":"text","text":"to stop receiving the remote video stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noSubscribed"}],"title":"AgoraStreamSubscribeState.noSubscribed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraStreamSubscribeState@AgoraStreamSubscribeStateNoSubscribed","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateNoSubscribed"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState":{"role":"symbol","title":"AgoraStreamSubscribeState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"abstract":[{"type":"text","text":"The subscribing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/noSubscribed":{"role":"symbol","title":"AgoraStreamSubscribeState.noSubscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noSubscribed"}],"abstract":[{"type":"text","text":"1: Fails to subscribe to the remote stream. Possible reasons:The remote"},{"type":"text","text":" "},{"type":"text","text":"user:Calls muteLocalAudioStream (YES) or muteLocalVideoStream (YES) to stop"},{"type":"text","text":" "},{"type":"text","text":"sending local media stream.Calls disableAudio or disableVideo to disable"},{"type":"text","text":" "},{"type":"text","text":"the local audio or video module.Calls enableLocalAudio (NO) or"},{"type":"text","text":" "},{"type":"text","text":"enableLocalVideo (NO) to disable local audio or video capture.The role of"},{"type":"text","text":" "},{"type":"text","text":"the remote user is audience.The local user calls the following methods to"},{"type":"text","text":" "},{"type":"text","text":"stop receiving remote streams:Call muteRemoteAudioStream (YES) or"},{"type":"text","text":" "},{"type":"text","text":"muteAllRemoteAudioStreams (YES) to stop receiving the remote audio"},{"type":"text","text":" "},{"type":"text","text":"stream.Call muteRemoteVideoStream (YES) or muteAllRemoteVideoStreams (YES)"},{"type":"text","text":" "},{"type":"text","text":"to stop receiving the remote video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/noSubscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateNoSubscribed"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/nosubscribed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamSubscribeStateNoSubscribed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateNoSubscribed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraStreamSubscribeStateNoSubscribed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/title","value":"AgoraStreamSubscribeState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1noSubscribed\/title","value":"AgoraStreamSubscribeStateNoSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1noSubscribed\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateNoSubscribed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}