{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate\/subscribed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate\/subscribed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The remote stream is received, and the subscription is successful."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"title":"AgoraStreamSubscribeState.subscribed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraStreamSubscribeState@AgoraStreamSubscribeStateSubscribed","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribed"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState":{"role":"symbol","title":"AgoraStreamSubscribeState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"abstract":[{"type":"text","text":"The subscribing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/subscribed":{"role":"symbol","title":"AgoraStreamSubscribeState.subscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"abstract":[{"type":"text","text":"3: The remote stream is received, and the subscription is successful."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribed"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/subscribed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamSubscribeStateSubscribed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/title","value":"AgoraStreamSubscribeState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1subscribed\/title","value":"AgoraStreamSubscribeStateSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1subscribed\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}