{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraconnectionstate\/connecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraconnectionstate\/connecting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connecting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The SDK is connecting to the Agora edge server. This state indicates"},{"type":"text","text":" "},{"type":"text","text":"that the SDK is establishing a connection with the specified channel after"},{"type":"text","text":" "},{"type":"text","text":"the app calls joinChannelByToken [2\/4].If the SDK successfully joins the"},{"type":"text","text":" "},{"type":"text","text":"channel, it triggers the connectionChangedToState callback and the"},{"type":"text","text":" "},{"type":"text","text":"connection state switches to AgoraConnectionStateConnected.After the"},{"type":"text","text":" "},{"type":"text","text":"connection is established, the SDK also initializes the media and triggers"},{"type":"text","text":" "},{"type":"text","text":"didJoinChannel when everything is ready."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"title":"AgoraConnectionState.connecting","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraConnectionState@AgoraConnectionStateConnecting","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateConnecting"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/connecting":{"role":"symbol","title":"AgoraConnectionState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"2: The SDK is connecting to the Agora edge server. This state indicates"},{"type":"text","text":" "},{"type":"text","text":"that the SDK is establishing a connection with the specified channel after"},{"type":"text","text":" "},{"type":"text","text":"the app calls joinChannelByToken [2\/4].If the SDK successfully joins the"},{"type":"text","text":" "},{"type":"text","text":"channel, it triggers the connectionChangedToState callback and the"},{"type":"text","text":" "},{"type":"text","text":"connection state switches to AgoraConnectionStateConnected.After the"},{"type":"text","text":" "},{"type":"text","text":"connection is established, the SDK also initializes the media and triggers"},{"type":"text","text":" "},{"type":"text","text":"didJoinChannel when everything is ready."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateConnecting"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate\/connecting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState":{"role":"symbol","title":"AgoraConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionState"}],"abstract":[{"type":"text","text":"Connection states."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionState"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraConnectionStateConnecting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateConnecting"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraConnectionStateConnecting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1connecting\/title","value":"AgoraConnectionStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1connecting\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState\/title","value":"AgoraConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}