{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraconnectionstate\/reconnecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraconnectionstate\/reconnecting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/reconnecting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: The SDK keeps reconnecting to the Agora edge server. The SDK keeps"},{"type":"text","text":" "},{"type":"text","text":"rejoining the channel after being disconnected from a joined channel"},{"type":"text","text":" "},{"type":"text","text":"because of network issues.If the SDK cannot rejoin the channel within 10"},{"type":"text","text":" "},{"type":"text","text":"seconds, it triggers rtcEngineConnectionDidLost , stays in the"},{"type":"text","text":" "},{"type":"text","text":"AgoraConnectionStateReconnecting state, and keeps rejoining the channel.If"},{"type":"text","text":" "},{"type":"text","text":"the SDK fails to rejoin the channel 20 minutes after being disconnected"},{"type":"text","text":" "},{"type":"text","text":"from the Agora edge server, the SDK triggers the connectionChangedToState"},{"type":"text","text":" "},{"type":"text","text":"callback, switches to the AgoraConnectionStateFailed state, and stops"},{"type":"text","text":" "},{"type":"text","text":"rejoining the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"title":"AgoraConnectionState.reconnecting","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraConnectionState@AgoraConnectionStateReconnecting","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateReconnecting"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/reconnecting":{"role":"symbol","title":"AgoraConnectionState.reconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"abstract":[{"type":"text","text":"4: The SDK keeps reconnecting to the Agora edge server. The SDK keeps"},{"type":"text","text":" "},{"type":"text","text":"rejoining the channel after being disconnected from a joined channel"},{"type":"text","text":" "},{"type":"text","text":"because of network issues.If the SDK cannot rejoin the channel within 10"},{"type":"text","text":" "},{"type":"text","text":"seconds, it triggers rtcEngineConnectionDidLost , stays in the"},{"type":"text","text":" "},{"type":"text","text":"AgoraConnectionStateReconnecting state, and keeps rejoining the channel.If"},{"type":"text","text":" "},{"type":"text","text":"the SDK fails to rejoin the channel 20 minutes after being disconnected"},{"type":"text","text":" "},{"type":"text","text":"from the Agora edge server, the SDK triggers the connectionChangedToState"},{"type":"text","text":" "},{"type":"text","text":"callback, switches to the AgoraConnectionStateFailed state, and stops"},{"type":"text","text":" "},{"type":"text","text":"rejoining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/reconnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateReconnecting"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate\/reconnecting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState":{"role":"symbol","title":"AgoraConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionState"}],"abstract":[{"type":"text","text":"Connection states."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionState"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraConnectionStateReconnecting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateReconnecting"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraConnectionStateReconnecting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1reconnecting\/title","value":"AgoraConnectionStateReconnecting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1reconnecting\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateReconnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState\/title","value":"AgoraConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}