{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmJoinChannelOption","preciseIdentifier":"c:objc(cs)AgoraRtmJoinChannelOption","text":"AgoraRtmJoinChannelOption"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmstreamchannel\/join(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmstreamchannel\/join(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannel\/join(with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmJoinChannelOption","preciseIdentifier":"c:objc(cs)AgoraRtmJoinChannelOption"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"join(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraRtmStreamChannel(im)joinWithOption:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"joinWithOption:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannel"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmJoinChannelOption":{"role":"symbol","title":"AgoraRtmJoinChannelOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmJoinChannelOption"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmJoinChannelOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmJoinChannelOption"}],"url":"\/documentation\/agorartckit\/agorartmjoinchanneloption"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannel/join(with:)":{"role":"symbol","title":"join(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmJoinChannelOption","preciseIdentifier":"c:objc(cs)AgoraRtmJoinChannelOption"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannel\/join(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinWithOption:"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannel\/join(with:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannel":{"role":"symbol","title":"AgoraRtmStreamChannel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmStreamChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannel"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"joinWithOption:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinWithOption:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"joinWithOption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmJoinChannelOption","preciseIdentifier":"c:objc(cs)AgoraRtmJoinChannelOption","text":"AgoraRtmJoinChannelOption"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"option"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmJoinChannelOption\/title","value":"AgoraRtmJoinChannelOption"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmJoinChannelOption\/fragments","value":[{"kind":"identifier","text":"AgoraRtmJoinChannelOption"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannel~1join(with:)\/title","value":"joinWithOption:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannel~1join(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinWithOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannel\/title","value":"AgoraRtmStreamChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannel\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}