{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerCacheStatistics","preciseIdentifier":"c:objc(cs)AgoraMediaPlayerCacheStatistics","text":"AgoraMediaPlayerCacheStatistics"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediaplayerupdatedinfo\/cachestatistics"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediaplayerupdatedinfo\/cachestatistics"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerUpdatedInfo\/cacheStatistics","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The statistics about the media file being cached.If you call the"},{"type":"text","text":" "},{"type":"text","text":"openWithMediaSource method and set enableCache as YES, the statistics about"},{"type":"text","text":" "},{"type":"text","text":"the media file being cached is updated every second after the media file is"},{"type":"text","text":" "},{"type":"text","text":"played. See AgoraMediaPlayerCacheStatistics ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerCacheStatistics","preciseIdentifier":"c:objc(cs)AgoraMediaPlayerCacheStatistics"},{"kind":"text","text":"?"}],"title":"cacheStatistics","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraMediaPlayerUpdatedInfo(py)cacheStatistics","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"cacheStatistics"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerUpdatedInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerUpdatedInfo/cacheStatistics":{"role":"symbol","title":"cacheStatistics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheStatistics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerCacheStatistics","preciseIdentifier":"c:objc(cs)AgoraMediaPlayerCacheStatistics"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The statistics about the media file being cached.If you call the"},{"type":"text","text":" "},{"type":"text","text":"openWithMediaSource method and set enableCache as YES, the statistics about"},{"type":"text","text":" "},{"type":"text","text":"the media file being cached is updated every second after the media file is"},{"type":"text","text":" "},{"type":"text","text":"played. See AgoraMediaPlayerCacheStatistics ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerUpdatedInfo\/cacheStatistics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cacheStatistics"}],"url":"\/documentation\/agorartckit\/agoramediaplayerupdatedinfo\/cachestatistics"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerUpdatedInfo":{"role":"symbol","title":"AgoraMediaPlayerUpdatedInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerUpdatedInfo"}],"abstract":[{"type":"text","text":"Information related to the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerUpdatedInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerUpdatedInfo"}],"url":"\/documentation\/agorartckit\/agoramediaplayerupdatedinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerCacheStatistics":{"role":"symbol","title":"AgoraMediaPlayerCacheStatistics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerCacheStatistics"}],"abstract":[{"type":"text","text":"Statistics about the media files being cached."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerCacheStatistics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerCacheStatistics"}],"url":"\/documentation\/agorartckit\/agoramediaplayercachestatistics"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cacheStatistics"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cacheStatistics"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerCacheStatistics","preciseIdentifier":"c:objc(cs)AgoraMediaPlayerCacheStatistics","text":"AgoraMediaPlayerCacheStatistics"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cacheStatistics"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerUpdatedInfo~1cacheStatistics\/title","value":"cacheStatistics"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerUpdatedInfo~1cacheStatistics\/fragments","value":[{"kind":"identifier","text":"cacheStatistics"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerUpdatedInfo\/title","value":"AgoraMediaPlayerUpdatedInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerUpdatedInfo\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerUpdatedInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerCacheStatistics\/title","value":"AgoraMediaPlayerCacheStatistics"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerCacheStatistics\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerCacheStatistics"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}