{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionerrortype\/encryption_error_decryption_failure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionerrortype\/encryption_error_decryption_failure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_DECRYPTION_FAILURE","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Decryption errors. Ensure that the receiver and the sender use the same"},{"type":"text","text":" "},{"type":"text","text":"encryption mode and key."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}],"title":"AgoraEncryptionErrorType.ENCRYPTION_ERROR_DECRYPTION_FAILURE","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraEncryptionErrorType@ENCRYPTION_ERROR_DECRYPTION_FAILURE","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType/ENCRYPTION_ERROR_DECRYPTION_FAILURE":{"role":"symbol","title":"AgoraEncryptionErrorType.ENCRYPTION_ERROR_DECRYPTION_FAILURE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}],"abstract":[{"type":"text","text":"1: Decryption errors. Ensure that the receiver and the sender use the same"},{"type":"text","text":" "},{"type":"text","text":"encryption mode and key."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_DECRYPTION_FAILURE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}],"url":"\/documentation\/agorartckit\/agoraencryptionerrortype\/encryption_error_decryption_failure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType":{"role":"symbol","title":"AgoraEncryptionErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"abstract":[{"type":"text","text":"Encryption error type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"url":"\/documentation\/agorartckit\/agoraencryptionerrortype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_DECRYPTION_FAILURE\/title","value":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_DECRYPTION_FAILURE\/fragments","value":[{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType\/title","value":"AgoraEncryptionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}