{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fast"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideodenoiserlevel\/fast"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideodenoiserlevel\/fast"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel\/fast","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Promotes reducing performance consumption during video noise reduction. prioritizes reducing performance consumption over video noise reduction quality. The performance consumption is lower, and the video noise reduction speed is faster. To avoid a noticeable shadowing effect (shadows trailing behind moving objects) in the processed video, Agora recommends that you use this settinging when the camera is fixed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fast"}],"title":"AgoraVideoDenoiserLevel.fast","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoDenoiserLevel@AgoraVideoDenoiserLevelFast","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelFast"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserLevel/fast":{"role":"symbol","title":"AgoraVideoDenoiserLevel.fast","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fast"}],"abstract":[{"type":"text","text":"1: Promotes reducing performance consumption during video noise reduction. prioritizes reducing performance consumption over video noise reduction quality. The performance consumption is lower, and the video noise reduction speed is faster. To avoid a noticeable shadowing effect (shadows trailing behind moving objects) in the processed video, Agora recommends that you use this settinging when the camera is fixed."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel\/fast","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelFast"}],"url":"\/documentation\/agorartckit\/agoravideodenoiserlevel\/fast"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserLevel":{"role":"symbol","title":"AgoraVideoDenoiserLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserLevel"}],"abstract":[{"type":"text","text":"The video noise reduction level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserLevel"}],"url":"\/documentation\/agorartckit\/agoravideodenoiserlevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoDenoiserLevelFast"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelFast"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelFast"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel~1fast\/title","value":"AgoraVideoDenoiserLevelFast"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel~1fast\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelFast"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel\/title","value":"AgoraVideoDenoiserLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}