{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"strength"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideodenoiserlevel\/strength"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideodenoiserlevel\/strength"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel\/strength","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Enhanced video noise reduction. prioritizes video noise reduction"},{"type":"text","text":" "},{"type":"text","text":"quality over reducing performance consumption. The performance consumption"},{"type":"text","text":" "},{"type":"text","text":"is higher, the video noise reduction speed is slower, and the video noise"},{"type":"text","text":" "},{"type":"text","text":"reduction quality is better. If AgoraVideoDenoiserLevelHighQuality is not"},{"type":"text","text":" "},{"type":"text","text":"enough for your video noise reduction needs, you can use this enumerator."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"strength"}],"title":"AgoraVideoDenoiserLevel.strength","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoDenoiserLevel@AgoraVideoDenoiserLevelStrength","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelStrength"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserLevel":{"role":"symbol","title":"AgoraVideoDenoiserLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserLevel"}],"abstract":[{"type":"text","text":"The video noise reduction level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserLevel"}],"url":"\/documentation\/agorartckit\/agoravideodenoiserlevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserLevel/strength":{"role":"symbol","title":"AgoraVideoDenoiserLevel.strength","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"strength"}],"abstract":[{"type":"text","text":"2: Enhanced video noise reduction. prioritizes video noise reduction"},{"type":"text","text":" "},{"type":"text","text":"quality over reducing performance consumption. The performance consumption"},{"type":"text","text":" "},{"type":"text","text":"is higher, the video noise reduction speed is slower, and the video noise"},{"type":"text","text":" "},{"type":"text","text":"reduction quality is better. If AgoraVideoDenoiserLevelHighQuality is not"},{"type":"text","text":" "},{"type":"text","text":"enough for your video noise reduction needs, you can use this enumerator."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserLevel\/strength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelStrength"}],"url":"\/documentation\/agorartckit\/agoravideodenoiserlevel\/strength"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoDenoiserLevelStrength"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelStrength"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelStrength"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel\/title","value":"AgoraVideoDenoiserLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel~1strength\/title","value":"AgoraVideoDenoiserLevelStrength"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserLevel~1strength\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserLevelStrength"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}