{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStartLoopback"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/admstartloopback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/admstartloopback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartLoopback","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStartLoopback"}],"title":"AgoraErrorCode.admStartLoopback","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraErrorCode@AgoraErrorCodeAdmStartLoopback","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartLoopback"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admStartLoopback":{"role":"symbol","title":"AgoraErrorCode.admStartLoopback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStartLoopback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartLoopback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartLoopback"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admstartloopback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode":{"role":"symbol","title":"AgoraErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"abstract":[{"type":"text","text":"Error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}],"url":"\/documentation\/agorartckit\/agoraerrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraErrorCodeAdmStartLoopback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartLoopback"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartLoopback"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartLoopback\/title","value":"AgoraErrorCodeAdmStartLoopback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartLoopback\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartLoopback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}