{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionInterrupted"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/connectioninterrupted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/connectioninterrupted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionInterrupted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"111: The network connection is interrupted. The SDK triggers this callback when it loses connection with the server for more than four seconds after the connection is established."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionInterrupted"}],"title":"AgoraErrorCode.connectionInterrupted","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraErrorCode@AgoraErrorCodeConnectionInterrupted","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeConnectionInterrupted"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode":{"role":"symbol","title":"AgoraErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"abstract":[{"type":"text","text":"Error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}],"url":"\/documentation\/agorartckit\/agoraerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/connectionInterrupted":{"role":"symbol","title":"AgoraErrorCode.connectionInterrupted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionInterrupted"}],"abstract":[{"type":"text","text":"111: The network connection is interrupted. The SDK triggers this callback when it loses connection with the server for more than four seconds after the connection is established."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionInterrupted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeConnectionInterrupted"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/connectioninterrupted"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraErrorCodeConnectionInterrupted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeConnectionInterrupted"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraErrorCodeConnectionInterrupted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1connectionInterrupted\/title","value":"AgoraErrorCodeConnectionInterrupted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1connectionInterrupted\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeConnectionInterrupted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}