{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannelRejected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/joinchannelrejected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/joinchannelrejected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/joinChannelRejected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"17: The request to join the channel is rejected. Possible reasons include the following:The user is already in the channel. Agora recommends that you use the connectionChangedToState callback to determine whether the user exists in the channel. Do not call this method to join the channel unless you receive the AgoraConnectionStateDisconnected(1) state.After calling startEchoTestWithConfig for the call test, the user tries to join the channel without calling stopEchoTest to end the current test. To join a channel, the call test must be ended by calling stopEchoTest."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannelRejected"}],"title":"AgoraErrorCode.joinChannelRejected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraErrorCode@AgoraErrorCodeJoinChannelRejected","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeJoinChannelRejected"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/joinChannelRejected":{"role":"symbol","title":"AgoraErrorCode.joinChannelRejected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannelRejected"}],"abstract":[{"type":"text","text":"17: The request to join the channel is rejected. Possible reasons include the following:The user is already in the channel. Agora recommends that you use the connectionChangedToState callback to determine whether the user exists in the channel. Do not call this method to join the channel unless you receive the AgoraConnectionStateDisconnected(1) state.After calling startEchoTestWithConfig for the call test, the user tries to join the channel without calling stopEchoTest to end the current test. To join a channel, the call test must be ended by calling stopEchoTest."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/joinChannelRejected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeJoinChannelRejected"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/joinchannelrejected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode":{"role":"symbol","title":"AgoraErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"abstract":[{"type":"text","text":"Error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}],"url":"\/documentation\/agorartckit\/agoraerrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraErrorCodeJoinChannelRejected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeJoinChannelRejected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraErrorCodeJoinChannelRejected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1joinChannelRejected\/title","value":"AgoraErrorCodeJoinChannelRejected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1joinChannelRejected\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeJoinChannelRejected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}