{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelRejected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/leavechannelrejected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/leavechannelrejected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/leaveChannelRejected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"18: Fails to leave the channel. Possible reasons include the following:The"},{"type":"text","text":" "},{"type":"text","text":"user has left the channel before calling the leaveChannel [1\/2] method."},{"type":"text","text":" "},{"type":"text","text":"Stop calling this method to clear this error.The user calls the"},{"type":"text","text":" "},{"type":"text","text":"leaveChannel [1\/2] method to leave the channel before joining the channel."},{"type":"text","text":" "},{"type":"text","text":"In this case, no extra operation is needed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelRejected"}],"title":"AgoraErrorCode.leaveChannelRejected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraErrorCode@AgoraErrorCodeLeaveChannelRejected","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeLeaveChannelRejected"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/leaveChannelRejected":{"role":"symbol","title":"AgoraErrorCode.leaveChannelRejected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelRejected"}],"abstract":[{"type":"text","text":"18: Fails to leave the channel. Possible reasons include the following:The"},{"type":"text","text":" "},{"type":"text","text":"user has left the channel before calling the leaveChannel [1\/2] method."},{"type":"text","text":" "},{"type":"text","text":"Stop calling this method to clear this error.The user calls the"},{"type":"text","text":" "},{"type":"text","text":"leaveChannel [1\/2] method to leave the channel before joining the channel."},{"type":"text","text":" "},{"type":"text","text":"In this case, no extra operation is needed."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/leaveChannelRejected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeLeaveChannelRejected"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/leavechannelrejected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode":{"role":"symbol","title":"AgoraErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"abstract":[{"type":"text","text":"Error codes."},{"type":"text","text":" "},{"type":"text","text":"An error code indicates that the SDK encountered an unrecoverable error that"},{"type":"text","text":" "},{"type":"text","text":"requires application intervention. For example, an error is returned when the"},{"type":"text","text":" "},{"type":"text","text":"camera fails to open, and the app needs to inform the user that the camera"},{"type":"text","text":" "},{"type":"text","text":"cannot be used."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}],"url":"\/documentation\/agorartckit\/agoraerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraErrorCodeLeaveChannelRejected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeLeaveChannelRejected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraErrorCodeLeaveChannelRejected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1leaveChannelRejected\/title","value":"AgoraErrorCodeLeaveChannelRejected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1leaveChannelRejected\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeLeaveChannelRejected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}