{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noBufs"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/nobufs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/nobufs"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noBufs","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noBufs"}],"title":"AgoraErrorCode.noBufs","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraErrorCode@AgoraErrorCodeNoBufs","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNoBufs"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode":{"role":"symbol","title":"AgoraErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"abstract":[{"type":"text","text":"Error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}],"url":"\/documentation\/agorartckit\/agoraerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/noBufs":{"role":"symbol","title":"AgoraErrorCode.noBufs","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noBufs"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noBufs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNoBufs"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/nobufs"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraErrorCodeNoBufs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNoBufs"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraErrorCodeNoBufs"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noBufs\/title","value":"AgoraErrorCodeNoBufs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noBufs\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNoBufs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}