{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReady"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/notready"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraerrorcode\/notready"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notReady","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The SDK is not ready. Possible reasons include the following:The initialization of AgoraRtcEngineKit fails. Reinitialize the AgoraRtcEngineKit.No user has joined the channel when the method is called. Check the code logic.The user has not left the channel when the rate or complain method is called. Check the code logic.The audio module is disabled.The program is not complete."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReady"}],"title":"AgoraErrorCode.notReady","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraErrorCode@AgoraErrorCodeNotReady","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNotReady"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode":{"role":"symbol","title":"AgoraErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"abstract":[{"type":"text","text":"Error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}],"url":"\/documentation\/agorartckit\/agoraerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/notReady":{"role":"symbol","title":"AgoraErrorCode.notReady","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReady"}],"abstract":[{"type":"text","text":"3: The SDK is not ready. Possible reasons include the following:The initialization of AgoraRtcEngineKit fails. Reinitialize the AgoraRtcEngineKit.No user has joined the channel when the method is called. Check the code logic.The user has not left the channel when the rate or complain method is called. Check the code logic.The audio module is disabled.The program is not complete."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notReady","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNotReady"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/notready"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraErrorCodeNotReady"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNotReady"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraErrorCodeNotReady"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notReady\/title","value":"AgoraErrorCodeNotReady"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notReady\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNotReady"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}