{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverConnectionLost"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayerror\/serverconnectionlost"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayerror\/serverconnectionlost"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverConnectionLost","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"8: The SDK disconnects from the server due to poor network connections. You can call leaveChannel [1\/2]"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverConnectionLost"}],"title":"AgoraChannelMediaRelayError.serverConnectionLost","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChannelMediaRelayError@AgoraChannelMediaRelayErrorServerConnectionLost","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerConnectionLost"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError":{"role":"symbol","title":"AgoraChannelMediaRelayError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayError"}],"abstract":[{"type":"text","text":"The error code of the channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayError"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/serverConnectionLost":{"role":"symbol","title":"AgoraChannelMediaRelayError.serverConnectionLost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverConnectionLost"}],"abstract":[{"type":"text","text":"8: The SDK disconnects from the server due to poor network connections. You can call leaveChannel [1\/2]"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverConnectionLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerConnectionLost"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/serverconnectionlost"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelMediaRelayErrorServerConnectionLost"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerConnectionLost"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerConnectionLost"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError\/title","value":"AgoraChannelMediaRelayError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverConnectionLost\/title","value":"AgoraChannelMediaRelayErrorServerConnectionLost"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverConnectionLost\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerConnectionLost"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}