{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfig"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig","preciseIdentifier":"c:objc(cs)AgoraLiveInjectStreamConfig","text":"AgoraLiveInjectStreamConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/defaultconfig()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/defaultconfig()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/defaultConfig()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfig"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraLiveInjectStreamConfig","preciseIdentifier":"c:objc(cs)AgoraLiveInjectStreamConfig"}],"title":"defaultConfig()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraLiveInjectStreamConfig(cm)defaultConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"defaultConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig":{"role":"symbol","title":"AgoraLiveInjectStreamConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/defaultConfig()":{"role":"symbol","title":"defaultConfig()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfig"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraLiveInjectStreamConfig","preciseIdentifier":"c:objc(cs)AgoraLiveInjectStreamConfig"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/defaultConfig()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultConfig"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/defaultconfig()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"defaultConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultConfig"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig","preciseIdentifier":"c:objc(cs)AgoraLiveInjectStreamConfig","text":"AgoraLiveInjectStreamConfig"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"defaultConfig"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig\/title","value":"AgoraLiveInjectStreamConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1defaultConfig()\/title","value":"defaultConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1defaultConfig()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}