{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedSourceChannel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent\/joinedsourcechannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent\/joinedsourcechannel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedSourceChannel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The user joins the source channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedSourceChannel"}],"title":"AgoraChannelMediaRelayEvent.joinedSourceChannel","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChannelMediaRelayEvent@AgoraChannelMediaRelayEventJoinedSourceChannel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedSourceChannel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/joinedSourceChannel":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.joinedSourceChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedSourceChannel"}],"abstract":[{"type":"text","text":"2: The user joins the source channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedSourceChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedSourceChannel"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/joinedsourcechannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent":{"role":"symbol","title":"AgoraChannelMediaRelayEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"abstract":[{"type":"text","text":"The event code of channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelMediaRelayEventJoinedSourceChannel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedSourceChannel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedSourceChannel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1joinedSourceChannel\/title","value":"AgoraChannelMediaRelayEventJoinedSourceChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1joinedSourceChannel\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedSourceChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/title","value":"AgoraChannelMediaRelayEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}