{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelIsNil"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelisnil"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelisnil"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelIsNil","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"10: The target channel name is nil."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelIsNil"}],"title":"AgoraChannelMediaRelayEvent.updateDestinationChannelIsNil","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChannelMediaRelayEvent@AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent":{"role":"symbol","title":"AgoraChannelMediaRelayEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"abstract":[{"type":"text","text":"The event code of channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/updateDestinationChannelIsNil":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.updateDestinationChannelIsNil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelIsNil"}],"abstract":[{"type":"text","text":"10: The target channel name is nil."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelIsNil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelisnil"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/title","value":"AgoraChannelMediaRelayEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelIsNil\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelIsNil\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}