{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelNotChange"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelnotchange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelnotchange"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelNotChange","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"9: The target channel does not change, which means that the target channel"},{"type":"text","text":" "},{"type":"text","text":"fails to be updated."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelNotChange"}],"title":"AgoraChannelMediaRelayEvent.updateDestinationChannelNotChange","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChannelMediaRelayEvent@AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/updateDestinationChannelNotChange":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.updateDestinationChannelNotChange","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelNotChange"}],"abstract":[{"type":"text","text":"9: The target channel does not change, which means that the target channel"},{"type":"text","text":" "},{"type":"text","text":"fails to be updated."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelNotChange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelnotchange"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent":{"role":"symbol","title":"AgoraChannelMediaRelayEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"abstract":[{"type":"text","text":"The event code of channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelNotChange\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelNotChange\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/title","value":"AgoraChannelMediaRelayEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}