{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unordered"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmmessageqos\/unordered"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmmessageqos\/unordered"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageQos\/unordered","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unordered"}],"title":"AgoraRtmMessageQos.unordered","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmMessageQos@AgoraRtmMessageQosUnordered","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmMessageQosUnordered"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageQos"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageQos":{"role":"symbol","title":"AgoraRtmMessageQos","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmMessageQos"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageQos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmMessageQos"}],"url":"\/documentation\/agorartckit\/agorartmmessageqos"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageQos/unordered":{"role":"symbol","title":"AgoraRtmMessageQos.unordered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unordered"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageQos\/unordered","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmMessageQosUnordered"}],"url":"\/documentation\/agorartckit\/agorartmmessageqos\/unordered"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmMessageQosUnordered"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmMessageQosUnordered"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmMessageQosUnordered"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageQos\/title","value":"AgoraRtmMessageQos"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageQos\/fragments","value":[{"kind":"identifier","text":"AgoraRtmMessageQos"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageQos~1unordered\/title","value":"AgoraRtmMessageQosUnordered"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageQos~1unordered\/fragments","value":[{"kind":"identifier","text":"AgoraRtmMessageQosUnordered"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}