{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType","preciseIdentifier":"c:@E@AgoraAudioEncodingType","text":"AgoraAudioEncodingType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig\/encodingtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig\/encodingtype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/encodingType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio encoding type. See AgoraAudioEncodingType."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioEncodingType","preciseIdentifier":"c:@E@AgoraAudioEncodingType"}],"title":"encodingType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraAudioEncodedFrameDelegateConfig(py)encodingType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"encodingType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegateConfig/encodingType":{"role":"symbol","title":"encodingType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioEncodingType","preciseIdentifier":"c:@E@AgoraAudioEncodingType"}],"abstract":[{"type":"text","text":"Audio encoding type. See AgoraAudioEncodingType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/encodingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodingType"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig\/encodingtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType":{"role":"symbol","title":"AgoraAudioEncodingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodingType"}],"abstract":[{"type":"text","text":"Audio encoding type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingType"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegateConfig":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegateConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"abstract":[{"type":"text","text":"Observer settings for the encoded audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"encodingType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"encodingType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType","preciseIdentifier":"c:@E@AgoraAudioEncodingType","text":"AgoraAudioEncodingType"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig~1encodingType\/title","value":"encodingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig~1encodingType\/fragments","value":[{"kind":"identifier","text":"encodingType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType\/title","value":"AgoraAudioEncodingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig\/title","value":"AgoraAudioEncodedFrameDelegateConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}