{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beatsPerMinute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorarhythmplayerconfig\/beatsperminute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorarhythmplayerconfig\/beatsperminute"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMinute","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The beat speed (beats\/minute), which ranges from 60 to 360. The default value"},{"type":"text","text":" "},{"type":"text","text":"is 60, which means that the metronome plays 60 beats in one minute."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beatsPerMinute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"beatsPerMinute","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRhythmPlayerConfig(py)beatsPerMinute","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"beatsPerMinute"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerConfig/beatsPerMinute":{"role":"symbol","title":"beatsPerMinute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beatsPerMinute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The beat speed (beats\/minute), which ranges from 60 to 360. The default value"},{"type":"text","text":" "},{"type":"text","text":"is 60, which means that the metronome plays 60 beats in one minute."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMinute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"beatsPerMinute"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerconfig\/beatsperminute"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerConfig":{"role":"symbol","title":"AgoraRhythmPlayerConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}],"abstract":[{"type":"text","text":"The metronome configuration."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"beatsPerMinute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"beatsPerMinute"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"kind":"identifier","text":"beatsPerMinute"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig~1beatsPerMinute\/title","value":"beatsPerMinute"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig~1beatsPerMinute\/fragments","value":[{"kind":"identifier","text":"beatsPerMinute"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig\/title","value":"AgoraRhythmPlayerConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}