{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousVirtualSurroundSound"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousvirtualsurroundsound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousvirtualsurroundsound"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualSurroundSound","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Virtual surround sound, that is, the SDK generates a simulated surround"},{"type":"text","text":" "},{"type":"text","text":"sound field on the basis of stereo channels, thereby creating a surround"},{"type":"text","text":" "},{"type":"text","text":"sound effect.If the virtual surround sound is enabled, users need to use"},{"type":"text","text":" "},{"type":"text","text":"stereo audio playback devices to hear the anticipated audio effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousVirtualSurroundSound"}],"title":"AgoraAudioEffectPreset.roomAcousVirtualSurroundSound","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioEffectPreset@AgoraAudioEffectPresetRoomAcousVirtualSurroundSound","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousVirtualSurroundSound":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousVirtualSurroundSound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousVirtualSurroundSound"}],"abstract":[{"type":"text","text":"Virtual surround sound, that is, the SDK generates a simulated surround"},{"type":"text","text":" "},{"type":"text","text":"sound field on the basis of stereo channels, thereby creating a surround"},{"type":"text","text":" "},{"type":"text","text":"sound effect.If the virtual surround sound is enabled, users need to use"},{"type":"text","text":" "},{"type":"text","text":"stereo audio playback devices to hear the anticipated audio effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualSurroundSound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousvirtualsurroundsound"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset":{"role":"symbol","title":"AgoraAudioEffectPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"abstract":[{"type":"text","text":"Preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"To get better audio effects, Agora recommends calling setAudioProfile [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"and setting the profile parameter as recommended below before using the"},{"type":"text","text":" "},{"type":"text","text":"preset audio effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVirtualSurroundSound\/title","value":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVirtualSurroundSound\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}