{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcous3DVoice"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacous3dvoice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacous3dvoice"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcous3DVoice","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A 3D voice effect that makes the voice appear to be moving around the user. The default cycle period is 10 seconds. After setting this effect, you can call setAudioEffectParameters to modify the movement period.If the 3D voice effect is enabled, users need to use stereo audio playback devices to hear the anticipated voice effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcous3DVoice"}],"title":"AgoraAudioEffectPreset.roomAcous3DVoice","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioEffectPreset@AgoraAudioEffectPresetRoomAcous3DVoice","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcous3DVoice"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset":{"role":"symbol","title":"AgoraAudioEffectPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"abstract":[{"type":"text","text":"Preset audio effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcous3DVoice":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcous3DVoice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcous3DVoice"}],"abstract":[{"type":"text","text":"A 3D voice effect that makes the voice appear to be moving around the user. The default cycle period is 10 seconds. After setting this effect, you can call setAudioEffectParameters to modify the movement period.If the 3D voice effect is enabled, users need to use stereo audio playback devices to hear the anticipated voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcous3DVoice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcous3DVoice"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacous3dvoice"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEffectPresetRoomAcous3DVoice"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcous3DVoice"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcous3DVoice"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcous3DVoice\/title","value":"AgoraAudioEffectPresetRoomAcous3DVoice"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcous3DVoice\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcous3DVoice"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}