{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectBoy"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectboy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectboy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectBoy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A boy’s voice.Agora recommends using this preset to process a male-sounding"},{"type":"text","text":" "},{"type":"text","text":"voice; otherwise, you may not hear the anticipated voice effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectBoy"}],"title":"AgoraAudioEffectPreset.voiceChangerEffectBoy","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioEffectPreset@AgoraAudioEffectPresetVoiceChangerEffectBoy","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectBoy"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectBoy":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectBoy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectBoy"}],"abstract":[{"type":"text","text":"A boy’s voice.Agora recommends using this preset to process a male-sounding"},{"type":"text","text":" "},{"type":"text","text":"voice; otherwise, you may not hear the anticipated voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectBoy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectBoy"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectboy"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset":{"role":"symbol","title":"AgoraAudioEffectPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"abstract":[{"type":"text","text":"Preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"To get better audio effects, Agora recommends calling setAudioProfile [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"and setting the profile parameter as recommended below before using the"},{"type":"text","text":" "},{"type":"text","text":"preset audio effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectBoy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectBoy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectBoy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectBoy\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectBoy"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectBoy\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectBoy"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}