{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorauserofflinereason\/quit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorauserofflinereason\/quit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/quit","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quit"}],"title":"AgoraUserOfflineReason.quit","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraUserOfflineReason@AgoraUserOfflineReasonQuit","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReasonQuit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason":{"role":"symbol","title":"AgoraUserOfflineReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUserOfflineReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReason"}],"url":"\/documentation\/agorartckit\/agorauserofflinereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason/quit":{"role":"symbol","title":"AgoraUserOfflineReason.quit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/quit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReasonQuit"}],"url":"\/documentation\/agorartckit\/agorauserofflinereason\/quit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraUserOfflineReasonQuit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReasonQuit"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraUserOfflineReasonQuit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason\/title","value":"AgoraUserOfflineReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1quit\/title","value":"AgoraUserOfflineReasonQuit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1quit\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReasonQuit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}