{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectModule","preciseIdentifier":"c:objc(cs)AgoraContentInspectModule","text":"AgoraContentInspectModule"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracontentinspectconfig\/modules"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracontentinspectconfig\/modules"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/modules","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Functional module. See AgoraContentInspectModule.A maximum of 32 AgoraContentInspectModule instances can be configured, and the value range of MAX_CONTENT_INSPECT_MODULE_COUNT is an integer in [1,32].A function module can only be configured with one instance at most. Currently only the video screenshot and upload function is supported."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraContentInspectModule","preciseIdentifier":"c:objc(cs)AgoraContentInspectModule"},{"kind":"text","text":"]?"}],"title":"modules","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraContentInspectConfig(py)modules","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"modules"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectModule":{"role":"symbol","title":"AgoraContentInspectModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectModule"}],"abstract":[{"type":"text","text":"A structure used to configure the frequency of video screenshot and upload.AgoraContentInspectModule"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectModule"}],"url":"\/documentation\/agorartckit\/agoracontentinspectmodule"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectConfig/modules":{"role":"symbol","title":"modules","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraContentInspectModule","preciseIdentifier":"c:objc(cs)AgoraContentInspectModule"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Functional module. See AgoraContentInspectModule.A maximum of 32 AgoraContentInspectModule instances can be configured, and the value range of MAX_CONTENT_INSPECT_MODULE_COUNT is an integer in [1,32].A function module can only be configured with one instance at most. Currently only the video screenshot and upload function is supported."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/modules","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modules"}],"url":"\/documentation\/agorartckit\/agoracontentinspectconfig\/modules"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectConfig":{"role":"symbol","title":"AgoraContentInspectConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectConfig"}],"abstract":[{"type":"text","text":"Configuration of video screenshot and upload."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectConfig"}],"url":"\/documentation\/agorartckit\/agoracontentinspectconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"modules"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<AgoraContentInspectModule *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modules"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectModule\/title","value":"AgoraContentInspectModule"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectModule\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectModule"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig~1modules\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig~1modules\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig\/title","value":"AgoraContentInspectConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}