{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedVideoOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions","preciseIdentifier":"c:objc(cs)AgoraAdvancedVideoOptions","text":"AgoraAdvancedVideoOptions"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/advancedvideooptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/advancedvideooptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/advancedVideoOptions","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedVideoOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAdvancedVideoOptions","preciseIdentifier":"c:objc(cs)AgoraAdvancedVideoOptions"},{"kind":"text","text":"?"}],"title":"advancedVideoOptions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoEncoderConfiguration(py)advancedVideoOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"advancedVideoOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration/advancedVideoOptions":{"role":"symbol","title":"advancedVideoOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedVideoOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAdvancedVideoOptions","preciseIdentifier":"c:objc(cs)AgoraAdvancedVideoOptions"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/advancedVideoOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"advancedVideoOptions"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration\/advancedvideooptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAdvancedVideoOptions":{"role":"symbol","title":"AgoraAdvancedVideoOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}],"url":"\/documentation\/agorartckit\/agoraadvancedvideooptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration":{"role":"symbol","title":"AgoraVideoEncoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"advancedVideoOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"advancedVideoOptions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions","preciseIdentifier":"c:objc(cs)AgoraAdvancedVideoOptions","text":"AgoraAdvancedVideoOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"advancedVideoOptions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1advancedVideoOptions\/title","value":"advancedVideoOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1advancedVideoOptions\/fragments","value":[{"kind":"identifier","text":"advancedVideoOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions\/title","value":"AgoraAdvancedVideoOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions\/fragments","value":[{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/title","value":"AgoraVideoEncoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}