{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"degradationPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","preciseIdentifier":"c:@E@AgoraDegradationPreference","text":"AgoraDegradationPreference"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/degradationpreference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/degradationpreference"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/degradationPreference","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video degradation preference under limited bandwidth. See AgoraDegradationPreference."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"degradationPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDegradationPreference","preciseIdentifier":"c:@E@AgoraDegradationPreference"}],"title":"degradationPreference","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoEncoderConfiguration(py)degradationPreference","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"degradationPreference"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration":{"role":"symbol","title":"AgoraVideoEncoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference":{"role":"symbol","title":"AgoraDegradationPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"}],"abstract":[{"type":"text","text":"Video degradation preferences when the bandwidth is a constraint."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationPreference"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration/degradationPreference":{"role":"symbol","title":"degradationPreference","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"degradationPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDegradationPreference","preciseIdentifier":"c:@E@AgoraDegradationPreference"}],"abstract":[{"type":"text","text":"Video degradation preference under limited bandwidth. See AgoraDegradationPreference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/degradationPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"degradationPreference"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration\/degradationpreference"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"degradationPreference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"degradationPreference"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","preciseIdentifier":"c:@E@AgoraDegradationPreference","text":"AgoraDegradationPreference"},{"kind":"text","text":" "},{"kind":"identifier","text":"degradationPreference"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/title","value":"AgoraVideoEncoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/title","value":"AgoraDegradationPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1degradationPreference\/title","value":"degradationPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1degradationPreference\/fragments","value":[{"kind":"identifier","text":"degradationPreference"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}