{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/dimensions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/dimensions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/dimensions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Users can set the resolution by themselves, or directly select the desired resolution from the following list:AgoraVideoDimension120x120: The video resolution is 120 × 120.AgoraVideoDimension160x120: The video resolution is 160 × 120.AgoraVideoDimension180x180: The video resolution is 180 × 180.AgoraVideoDimension240x180: The video resolution is 240 × 180.AgoraVideoDimension320x180: The video resolution is 320 × 180.AgoraVideoDimension240x240: The video resolution is 240 × 240.AgoraVideoDimension320x240: The video resolution is 320 × 240.AgoraVideoDimension424x240: The video resolution is 424 × 240.AgoraVideoDimension360x360: The video resolution is 360 × 360.AgoraVideoDimension480x360: The video resolution is 480 × 360.AgoraVideoDimension640x360: The video resolution is 640 × 360.AgoraVideoDimension480x480: The video resolution is 480 × 480.AgoraVideoDimension640x480: The video resolution is 640 × 480.AgoraVideoDimension840x480: The video resolution is 840 × 480.AgoraVideoDimension960x540: The video resolution is 960 × 540.AgoraVideoDimension960x720: The video resolution is 960 × 720.AgoraVideoDimension1280x720: The video resolution is 1280 × 720.AgoraVideoDimension1920x1080: The video resolution is 1920 × 1080.AgoraVideoDimension2540x1440: The video resolution is 2540 × 1440.AgoraVideoDimension3840x2160: The video resolution is 3840 × 2160.Whether the 720p resolution or above can be supported depends on the device. If the device cannot support 720p, the frame rate will be lower than the set value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"dimensions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoEncoderConfiguration(py)dimensions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"dimensions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration/dimensions":{"role":"symbol","title":"dimensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"Users can set the resolution by themselves, or directly select the desired resolution from the following list:AgoraVideoDimension120x120: The video resolution is 120 × 120.AgoraVideoDimension160x120: The video resolution is 160 × 120.AgoraVideoDimension180x180: The video resolution is 180 × 180.AgoraVideoDimension240x180: The video resolution is 240 × 180.AgoraVideoDimension320x180: The video resolution is 320 × 180.AgoraVideoDimension240x240: The video resolution is 240 × 240.AgoraVideoDimension320x240: The video resolution is 320 × 240.AgoraVideoDimension424x240: The video resolution is 424 × 240.AgoraVideoDimension360x360: The video resolution is 360 × 360.AgoraVideoDimension480x360: The video resolution is 480 × 360.AgoraVideoDimension640x360: The video resolution is 640 × 360.AgoraVideoDimension480x480: The video resolution is 480 × 480.AgoraVideoDimension640x480: The video resolution is 640 × 480.AgoraVideoDimension840x480: The video resolution is 840 × 480.AgoraVideoDimension960x540: The video resolution is 960 × 540.AgoraVideoDimension960x720: The video resolution is 960 × 720.AgoraVideoDimension1280x720: The video resolution is 1280 × 720.AgoraVideoDimension1920x1080: The video resolution is 1920 × 1080.AgoraVideoDimension2540x1440: The video resolution is 2540 × 1440.AgoraVideoDimension3840x2160: The video resolution is 3840 × 2160.Whether the 720p resolution or above can be supported depends on the device. If the device cannot support 720p, the frame rate will be lower than the set value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/dimensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dimensions"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration\/dimensions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration":{"role":"symbol","title":"AgoraVideoEncoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dimensions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dimensions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimensions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1dimensions\/title","value":"dimensions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1dimensions\/fragments","value":[{"kind":"identifier","text":"dimensions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/title","value":"AgoraVideoEncoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}