{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameRate","preciseIdentifier":"c:@E@AgoraVideoFrameRate","text":"AgoraVideoFrameRate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode","text":"AgoraVideoOutputOrientationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirrorMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"size","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video resolution."}]}]},{"name":"frameRate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Video frame rate. See AgoraVideoFrameRate ."}]}]},{"name":"bitrate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bitrate of the encoding video."}]}]},{"name":"orientationMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The orientation of the encoding video. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoOutputOrientationMode ."}]}]},{"name":"mirrorMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to enable mirroring mode when sending encoded"},{"type":"text","text":" "},{"type":"text","text":"video, only affects the video images seen by remote users. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoMirrorMode ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The initialized AgoraVideoEncoderConfiguration object."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/init(size:framerate:bitrate:orientationmode:mirrormode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/init(size:framerate:bitrate:orientationmode:mirrormode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/init(size:frameRate:bitrate:orientationMode:mirrorMode:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specifies the video resolution and initializes the"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoEncoderConfiguration object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFrameRate","preciseIdentifier":"c:@E@AgoraVideoFrameRate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirrorMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":")"}],"title":"init(size:frameRate:bitrate:orientationMode:mirrorMode:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)AgoraVideoEncoderConfiguration(im)initWithSize:frameRate:bitrate:orientationMode:mirrorMode:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSize:frameRate:bitrate:orientationMode:mirrorMode:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration/init(size:frameRate:bitrate:orientationMode:mirrorMode:)":{"role":"symbol","title":"init(size:frameRate:bitrate:orientationMode:mirrorMode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFrameRate","preciseIdentifier":"c:@E@AgoraVideoFrameRate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirrorMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Specifies the video resolution and initializes the"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoEncoderConfiguration object."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/init(size:frameRate:bitrate:orientationMode:mirrorMode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSize:frameRate:bitrate:orientationMode:mirrorMode:"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration\/init(size:framerate:bitrate:orientationmode:mirrormode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode":{"role":"symbol","title":"AgoraVideoOutputOrientationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"abstract":[{"type":"text","text":"Video output orientation mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration":{"role":"symbol","title":"AgoraVideoEncoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameRate":{"role":"symbol","title":"AgoraVideoFrameRate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameRate"}],"abstract":[{"type":"text","text":"Video frame rate."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameRate"}],"url":"\/documentation\/agorartckit\/agoravideoframerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoMirrorMode":{"role":"symbol","title":"AgoraVideoMirrorMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"abstract":[{"type":"text","text":"Video mirror mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"url":"\/documentation\/agorartckit\/agoravideomirrormode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSize:frameRate:bitrate:orientationMode:mirrorMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSize:frameRate:bitrate:orientationMode:mirrorMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameRate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameRate","preciseIdentifier":"c:@E@AgoraVideoFrameRate","text":"AgoraVideoFrameRate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frameRate"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bitrate"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode","text":"AgoraVideoOutputOrientationMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrorMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mirrorMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1init(size:frameRate:bitrate:orientationMode:mirrorMode:)\/title","value":"initWithSize:frameRate:bitrate:orientationMode:mirrorMode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1init(size:frameRate:bitrate:orientationMode:mirrorMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSize:frameRate:bitrate:orientationMode:mirrorMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/title","value":"AgoraVideoOutputOrientationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/title","value":"AgoraVideoEncoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameRate\/title","value":"AgoraVideoFrameRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameRate\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/title","value":"AgoraVideoMirrorMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}