{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrorMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/mirrormode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/mirrormode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/mirrorMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the mirror mode of the published local video stream. It only affects the video that the remote user sees. See AgoraVideoMirrorMode.By default, the video is not mirrored."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrorMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"}],"title":"mirrorMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoEncoderConfiguration(py)mirrorMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"mirrorMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoMirrorMode":{"role":"symbol","title":"AgoraVideoMirrorMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"abstract":[{"type":"text","text":"Video mirror mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"url":"\/documentation\/agorartckit\/agoravideomirrormode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration/mirrorMode":{"role":"symbol","title":"mirrorMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrorMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode"}],"abstract":[{"type":"text","text":"Sets the mirror mode of the published local video stream. It only affects the video that the remote user sees. See AgoraVideoMirrorMode.By default, the video is not mirrored."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/mirrorMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mirrorMode"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration\/mirrormode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration":{"role":"symbol","title":"AgoraVideoEncoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mirrorMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mirrorMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","preciseIdentifier":"c:@E@AgoraVideoMirrorMode","text":"AgoraVideoMirrorMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrorMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/title","value":"AgoraVideoMirrorMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1mirrorMode\/title","value":"mirrorMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1mirrorMode\/fragments","value":[{"kind":"identifier","text":"mirrorMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/title","value":"AgoraVideoEncoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}