{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode","text":"AgoraVideoOutputOrientationMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/orientationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoencoderconfiguration\/orientationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/orientationMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The orientation mode of the encoded video. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoOutputOrientationMode ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode"}],"title":"orientationMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVideoEncoderConfiguration(py)orientationMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"orientationMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration":{"role":"symbol","title":"AgoraVideoEncoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode":{"role":"symbol","title":"AgoraVideoOutputOrientationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"abstract":[{"type":"text","text":"Video output orientation mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoEncoderConfiguration/orientationMode":{"role":"symbol","title":"orientationMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode"}],"abstract":[{"type":"text","text":"The orientation mode of the encoded video. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoOutputOrientationMode ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoEncoderConfiguration\/orientationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"orientationMode"}],"url":"\/documentation\/agorartckit\/agoravideoencoderconfiguration\/orientationmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"orientationMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"orientationMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","preciseIdentifier":"c:@E@AgoraVideoOutputOrientationMode","text":"AgoraVideoOutputOrientationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/title","value":"AgoraVideoEncoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraVideoEncoderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/title","value":"AgoraVideoOutputOrientationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1orientationMode\/title","value":"orientationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoEncoderConfiguration~1orientationMode\/fragments","value":[{"kind":"identifier","text":"orientationMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}