{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameType","preciseIdentifier":"c:@E@AgoraVideoFrameType","text":"AgoraVideoFrameType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/frametype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/frametype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/frameType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The video frame type. See AgoraVideoFrameType ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFrameType","preciseIdentifier":"c:@E@AgoraVideoFrameType"}],"title":"frameType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraEncodedVideoFrameInfo(py)frameType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"frameType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/frameType":{"role":"symbol","title":"frameType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFrameType","preciseIdentifier":"c:@E@AgoraVideoFrameType"}],"abstract":[{"type":"text","text":"The video frame type. See AgoraVideoFrameType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/frameType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameType"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/frametype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo":{"role":"symbol","title":"AgoraEncodedVideoFrameInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameType":{"role":"symbol","title":"AgoraVideoFrameType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameType"}],"abstract":[{"type":"text","text":"The video frame type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameType"}],"url":"\/documentation\/agorartckit\/agoravideoframetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"frameType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frameType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameType","preciseIdentifier":"c:@E@AgoraVideoFrameType","text":"AgoraVideoFrameType"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1frameType\/title","value":"frameType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1frameType\/fragments","value":[{"kind":"identifier","text":"frameType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo\/title","value":"AgoraEncodedVideoFrameInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameType\/title","value":"AgoraVideoFrameType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}