{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"srcBufferUnderflow"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediaplayererror\/srcbufferunderflow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediaplayererror\/srcbufferunderflow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerError\/srcBufferUnderflow","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"-12: The playback buffer is insufficient."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"srcBufferUnderflow"}],"title":"AgoraMediaPlayerError.srcBufferUnderflow","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaPlayerError@AgoraMediaPlayerErrorSrcBufferUnderflow","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerErrorSrcBufferUnderflow"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerError/srcBufferUnderflow":{"role":"symbol","title":"AgoraMediaPlayerError.srcBufferUnderflow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"srcBufferUnderflow"}],"abstract":[{"type":"text","text":"-12: The playback buffer is insufficient."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerError\/srcBufferUnderflow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerErrorSrcBufferUnderflow"}],"url":"\/documentation\/agorartckit\/agoramediaplayererror\/srcbufferunderflow"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerError":{"role":"symbol","title":"AgoraMediaPlayerError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerError"}],"abstract":[{"type":"text","text":"Error codes of the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerError"}],"url":"\/documentation\/agorartckit\/agoramediaplayererror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaPlayerErrorSrcBufferUnderflow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerErrorSrcBufferUnderflow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaPlayerErrorSrcBufferUnderflow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerError~1srcBufferUnderflow\/title","value":"AgoraMediaPlayerErrorSrcBufferUnderflow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerError~1srcBufferUnderflow\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerErrorSrcBufferUnderflow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerError\/title","value":"AgoraMediaPlayerError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerError\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}