{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualRecording"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualrecording"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualrecording"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualRecording","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualRecording"}],"title":"AgoraMediaDeviceType.audioVirtualRecording","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaDeviceType@AgoraMediaDeviceTypeAudioVirtualRecording","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualRecording"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioVirtualRecording":{"role":"symbol","title":"AgoraMediaDeviceType.audioVirtualRecording","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualRecording"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualRecording"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualrecording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType":{"role":"symbol","title":"AgoraMediaDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaDeviceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceType"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaDeviceTypeAudioVirtualRecording"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualRecording"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualRecording"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualRecording\/title","value":"AgoraMediaDeviceTypeAudioVirtualRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualRecording\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType\/title","value":"AgoraMediaDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}