{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualPlayout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualplayout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualplayout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualPlayout","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualPlayout"}],"title":"AgoraMediaDeviceType.audioVirtualPlayout","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaDeviceType@AgoraMediaDeviceTypeAudioVirtualPlayout","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualPlayout"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType":{"role":"symbol","title":"AgoraMediaDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaDeviceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceType"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioVirtualPlayout":{"role":"symbol","title":"AgoraMediaDeviceType.audioVirtualPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualPlayout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualPlayout"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualplayout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaDeviceTypeAudioVirtualPlayout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualPlayout"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualPlayout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType\/title","value":"AgoraMediaDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualPlayout\/title","value":"AgoraMediaDeviceTypeAudioVirtualPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualPlayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}