{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audienceLatencyLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType","preciseIdentifier":"c:@E@AgoraAudienceLatencyLevelType","text":"AgoraAudienceLatencyLevelType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraclientroleoptions\/audiencelatencylevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraclientroleoptions\/audiencelatencylevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions\/audienceLatencyLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The latency level of an audience member in interactive live streaming. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudienceLatencyLevelType ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audienceLatencyLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudienceLatencyLevelType","preciseIdentifier":"c:@E@AgoraAudienceLatencyLevelType"}],"title":"audienceLatencyLevel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraClientRoleOptions(py)audienceLatencyLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"audienceLatencyLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType":{"role":"symbol","title":"AgoraAudienceLatencyLevelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"abstract":[{"type":"text","text":"The latency level of an audience member in interactive live streaming. This"},{"type":"text","text":" "},{"type":"text","text":"enum takes effect only when the user role is set to AgoraClientRoleAudience ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleOptions":{"role":"symbol","title":"AgoraClientRoleOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleOptions"}],"abstract":[{"type":"text","text":"The detailed options of a user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleOptions"}],"url":"\/documentation\/agorartckit\/agoraclientroleoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleOptions/audienceLatencyLevel":{"role":"symbol","title":"audienceLatencyLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audienceLatencyLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudienceLatencyLevelType","preciseIdentifier":"c:@E@AgoraAudienceLatencyLevelType"}],"abstract":[{"type":"text","text":"The latency level of an audience member in interactive live streaming. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudienceLatencyLevelType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleOptions\/audienceLatencyLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audienceLatencyLevel"}],"url":"\/documentation\/agorartckit\/agoraclientroleoptions\/audiencelatencylevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audienceLatencyLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audienceLatencyLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType","preciseIdentifier":"c:@E@AgoraAudienceLatencyLevelType","text":"AgoraAudienceLatencyLevelType"},{"kind":"text","text":" "},{"kind":"identifier","text":"audienceLatencyLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType\/title","value":"AgoraAudienceLatencyLevelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions\/title","value":"AgoraClientRoleOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions~1audienceLatencyLevel\/title","value":"audienceLatencyLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleOptions~1audienceLatencyLevel\/fragments","value":[{"kind":"identifier","text":"audienceLatencyLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}