{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expectedDownlinkBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralastmileprobeconfig\/expecteddownlinkbitrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralastmileprobeconfig\/expecteddownlinkbitrate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeConfig\/expectedDownlinkBitrate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The expected maximum downlink bitrate (bps) of the local user. The value"},{"type":"text","text":" "},{"type":"text","text":"range is [100000,5000000]."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expectedDownlinkBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"expectedDownlinkBitrate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLastmileProbeConfig(py)expectedDownlinkBitrate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"expectedDownlinkBitrate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeConfig/expectedDownlinkBitrate":{"role":"symbol","title":"expectedDownlinkBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expectedDownlinkBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The expected maximum downlink bitrate (bps) of the local user. The value"},{"type":"text","text":" "},{"type":"text","text":"range is [100000,5000000]."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeConfig\/expectedDownlinkBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expectedDownlinkBitrate"}],"url":"\/documentation\/agorartckit\/agoralastmileprobeconfig\/expecteddownlinkbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeConfig":{"role":"symbol","title":"AgoraLastmileProbeConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLastmileProbeConfig"}],"abstract":[{"type":"text","text":"Configurations of the last-mile network test."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeConfig"}],"url":"\/documentation\/agorartckit\/agoralastmileprobeconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"expectedDownlinkBitrate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"expectedDownlinkBitrate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"expectedDownlinkBitrate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeConfig~1expectedDownlinkBitrate\/title","value":"expectedDownlinkBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeConfig~1expectedDownlinkBitrate\/fragments","value":[{"kind":"identifier","text":"expectedDownlinkBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeConfig\/title","value":"AgoraLastmileProbeConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}