{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralivestreamadvancedfeature\/featurename"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralivestreamadvancedfeature\/featurename"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/featureName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The feature names, including LBHQ (high-quality video with a lower bitrate)"},{"type":"text","text":" "},{"type":"text","text":"and VEO (optimized video encoder)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"featureName","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLiveStreamAdvancedFeature(py)featureName","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"featureName"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveStreamAdvancedFeature/featureName":{"role":"symbol","title":"featureName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The feature names, including LBHQ (high-quality video with a lower bitrate)"},{"type":"text","text":" "},{"type":"text","text":"and VEO (optimized video encoder)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/featureName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"featureName"}],"url":"\/documentation\/agorartckit\/agoralivestreamadvancedfeature\/featurename"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveStreamAdvancedFeature":{"role":"symbol","title":"AgoraLiveStreamAdvancedFeature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"abstract":[{"type":"text","text":"The configuration for advanced features of the RTMP or RTMPS streaming with"},{"type":"text","text":" "},{"type":"text","text":"transcoding. If you want to enable the advanced features of streaming with"},{"type":"text","text":" "},{"type":"text","text":"transcoding, contact ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"url":"\/documentation\/agorartckit\/agoralivestreamadvancedfeature"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"featureName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"featureName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"featureName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature~1featureName\/title","value":"featureName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature~1featureName\/fragments","value":[{"kind":"identifier","text":"featureName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature\/title","value":"AgoraLiveStreamAdvancedFeature"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature\/fragments","value":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}