{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReasonChannelCongestion"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorawlaccreason\/messagereasonchannelcongestion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorawlaccreason\/messagereasonchannelcongestion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccReason\/messageReasonChannelCongestion","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReasonChannelCongestion"}],"title":"AgoraWlAccReason.messageReasonChannelCongestion","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraWlAccReason@AgoraWlAccMessageReasonChannelCongestion","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccMessageReasonChannelCongestion"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccReason/messageReasonChannelCongestion":{"role":"symbol","title":"AgoraWlAccReason.messageReasonChannelCongestion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReasonChannelCongestion"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccReason\/messageReasonChannelCongestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccMessageReasonChannelCongestion"}],"url":"\/documentation\/agorartckit\/agorawlaccreason\/messagereasonchannelcongestion"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccReason":{"role":"symbol","title":"AgoraWlAccReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWlAccReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccReason"}],"url":"\/documentation\/agorartckit\/agorawlaccreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraWlAccMessageReasonChannelCongestion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccMessageReasonChannelCongestion"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraWlAccMessageReasonChannelCongestion"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccReason~1messageReasonChannelCongestion\/title","value":"AgoraWlAccMessageReasonChannelCongestion"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccReason~1messageReasonChannelCongestion\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccMessageReasonChannelCongestion"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccReason\/title","value":"AgoraWlAccReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccReason\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}