{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode","text":"AgoraAudioRawFrameOperationMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioparams\/mode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioparams\/mode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams\/mode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The use mode of the audio data. See AgoraAudioRawFrameOperationMode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode"}],"title":"mode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraAudioParams(py)mode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"mode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioParams":{"role":"symbol","title":"AgoraAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioParams"}],"abstract":[{"type":"text","text":"Audio data format."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioParams"}],"url":"\/documentation\/agorartckit\/agoraaudioparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRawFrameOperationMode":{"role":"symbol","title":"AgoraAudioRawFrameOperationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRawFrameOperationMode"}],"abstract":[{"type":"text","text":"The use mode of the audio data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRawFrameOperationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRawFrameOperationMode"}],"url":"\/documentation\/agorartckit\/agoraaudiorawframeoperationmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioParams/mode":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode"}],"abstract":[{"type":"text","text":"The use mode of the audio data. See AgoraAudioRawFrameOperationMode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams\/mode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mode"}],"url":"\/documentation\/agorartckit\/agoraaudioparams\/mode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRawFrameOperationMode","preciseIdentifier":"c:@E@AgoraAudioRawFrameOperationMode","text":"AgoraAudioRawFrameOperationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams\/title","value":"AgoraAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRawFrameOperationMode\/title","value":"AgoraAudioRawFrameOperationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRawFrameOperationMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRawFrameOperationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams~1mode\/title","value":"mode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}