{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediastreamtype\/subtitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediastreamtype\/subtitle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/subtitle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The subtitle stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"}],"title":"AgoraMediaStreamType.subtitle","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaStreamType@AgoraMediaStreamTypeSubtitle","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamTypeSubtitle"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/subtitle":{"role":"symbol","title":"AgoraMediaStreamType.subtitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"}],"abstract":[{"type":"text","text":"3: The subtitle stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/subtitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamTypeSubtitle"}],"url":"\/documentation\/agorartckit\/agoramediastreamtype\/subtitle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType":{"role":"symbol","title":"AgoraMediaStreamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaStreamType"}],"abstract":[{"type":"text","text":"The type of the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamType"}],"url":"\/documentation\/agorartckit\/agoramediastreamtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaStreamTypeSubtitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamTypeSubtitle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaStreamTypeSubtitle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1subtitle\/title","value":"AgoraMediaStreamTypeSubtitle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1subtitle\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamTypeSubtitle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType\/title","value":"AgoraMediaStreamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}