{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/invalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/invalid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Invalid video attribute."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"title":"AgoraVideoProfile.invalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoProfile@AgoraVideoProfileInvalid","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileInvalid"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/invalid":{"role":"symbol","title":"AgoraVideoProfile.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Invalid video attribute."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileInvalid"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/invalid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile":{"role":"symbol","title":"AgoraVideoProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"abstract":[{"type":"text","text":"Video profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfile"}],"url":"\/documentation\/agorartckit\/agoravideoprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoProfileInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoProfileInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1invalid\/title","value":"AgoraVideoProfileInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1invalid\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/title","value":"AgoraVideoProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}