{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1080P_3"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/landscape1080p_3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/landscape1080p_3"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_3","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"60: 1920 × 1080, frame rate 30 fps, bitrate 3150 Kbps."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1080P_3"}],"title":"AgoraVideoProfile.landscape1080P_3","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoProfile@AgoraVideoProfileLandscape1080P_3","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_3"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape1080P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape1080P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1080P_3"}],"abstract":[{"type":"text","text":"60: 1920 × 1080, frame rate 30 fps, bitrate 3150 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape1080p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile":{"role":"symbol","title":"AgoraVideoProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"abstract":[{"type":"text","text":"Video profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfile"}],"url":"\/documentation\/agorartckit\/agoravideoprofile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoProfileLandscape1080P_3"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_3"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_3"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P_3\/title","value":"AgoraVideoProfileLandscape1080P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/title","value":"AgoraVideoProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}