{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1080P_5"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/portrait1080p_5"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/portrait1080p_5"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_5","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1064: 1080 × 1920, frame rate 60 fps, bitrate 4780 Kbps."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1080P_5"}],"title":"AgoraVideoProfile.portrait1080P_5","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoProfile@AgoraVideoProfilePortrait1080P_5","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_5"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait1080P_5":{"role":"symbol","title":"AgoraVideoProfile.portrait1080P_5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1080P_5"}],"abstract":[{"type":"text","text":"1064: 1080 × 1920, frame rate 60 fps, bitrate 4780 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_5"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait1080p_5"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile":{"role":"symbol","title":"AgoraVideoProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"abstract":[{"type":"text","text":"Video profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfile"}],"url":"\/documentation\/agorartckit\/agoravideoprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoProfilePortrait1080P_5"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_5"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_5"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P_5\/title","value":"AgoraVideoProfilePortrait1080P_5"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P_5\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_5"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/title","value":"AgoraVideoProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}