{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait120P"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/portrait120p"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoprofile\/portrait120p"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1000: 120 × 160, frame rate 15 fps, bitrate 65 Kbps."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait120P"}],"title":"AgoraVideoProfile.portrait120P","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoProfile@AgoraVideoProfilePortrait120P","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile":{"role":"symbol","title":"AgoraVideoProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"abstract":[{"type":"text","text":"Video profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfile"}],"url":"\/documentation\/agorartckit\/agoravideoprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait120P":{"role":"symbol","title":"AgoraVideoProfile.portrait120P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait120P"}],"abstract":[{"type":"text","text":"1000: 120 × 160, frame rate 15 fps, bitrate 65 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait120p"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoProfilePortrait120P"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/title","value":"AgoraVideoProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait120P\/title","value":"AgoraVideoProfilePortrait120P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait120P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}