{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/forbidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/forbidden"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/forbidden","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}],"title":"AgoraH265TranscodeResult.forbidden","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraH265TranscodeResult@AgoraH265TranscodeResultForbidden","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultForbidden"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult":{"role":"symbol","title":"AgoraH265TranscodeResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult/forbidden":{"role":"symbol","title":"AgoraH265TranscodeResult.forbidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/forbidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultForbidden"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult\/forbidden"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraH265TranscodeResultForbidden"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultForbidden"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraH265TranscodeResultForbidden"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/title","value":"AgoraH265TranscodeResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1forbidden\/title","value":"AgoraH265TranscodeResultForbidden"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1forbidden\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultForbidden"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}