{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestInvalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/requestinvalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/requestinvalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/requestInvalid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestInvalid"}],"title":"AgoraH265TranscodeResult.requestInvalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraH265TranscodeResult@AgoraH265TranscodeResultRequestInvalid","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultRequestInvalid"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult/requestInvalid":{"role":"symbol","title":"AgoraH265TranscodeResult.requestInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestInvalid"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/requestInvalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultRequestInvalid"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult\/requestinvalid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult":{"role":"symbol","title":"AgoraH265TranscodeResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraH265TranscodeResultRequestInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultRequestInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraH265TranscodeResultRequestInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1requestInvalid\/title","value":"AgoraH265TranscodeResultRequestInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1requestInvalid\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultRequestInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/title","value":"AgoraH265TranscodeResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}