{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceUnavailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/serviceunavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/serviceunavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/serviceUnavailable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceUnavailable"}],"title":"AgoraH265TranscodeResult.serviceUnavailable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraH265TranscodeResult@AgoraH265TranscodeResultServiceUnavailable","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultServiceUnavailable"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult/serviceUnavailable":{"role":"symbol","title":"AgoraH265TranscodeResult.serviceUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceUnavailable"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/serviceUnavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultServiceUnavailable"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult\/serviceunavailable"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult":{"role":"symbol","title":"AgoraH265TranscodeResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraH265TranscodeResultServiceUnavailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultServiceUnavailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraH265TranscodeResultServiceUnavailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1serviceUnavailable\/title","value":"AgoraH265TranscodeResultServiceUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1serviceUnavailable\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultServiceUnavailable"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/title","value":"AgoraH265TranscodeResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}