{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/tokenexpired"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderesult\/tokenexpired"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/tokenExpired","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"title":"AgoraH265TranscodeResult.tokenExpired","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraH265TranscodeResult@AgoraH265TranscodeResultTokenExpired","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultTokenExpired"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult/tokenExpired":{"role":"symbol","title":"AgoraH265TranscodeResult.tokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult\/tokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResultTokenExpired"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult\/tokenexpired"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult":{"role":"symbol","title":"AgoraH265TranscodeResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraH265TranscodeResultTokenExpired"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultTokenExpired"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraH265TranscodeResultTokenExpired"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1tokenExpired\/title","value":"AgoraH265TranscodeResultTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult~1tokenExpired\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResultTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/title","value":"AgoraH265TranscodeResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}