{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionstate\/connected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionstate\/connected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionState\/connected","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"title":"AgoraRtmClientConnectionState.connected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmClientConnectionState@AgoraRtmClientConnectionStateConnected","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionStateConnected"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionState/connected":{"role":"symbol","title":"AgoraRtmClientConnectionState.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionState\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionStateConnected"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionstate\/connected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionState":{"role":"symbol","title":"AgoraRtmClientConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionState"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionState"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmClientConnectionStateConnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionStateConnected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmClientConnectionStateConnected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionState~1connected\/title","value":"AgoraRtmClientConnectionStateConnected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionState~1connected\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionStateConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionState\/title","value":"AgoraRtmClientConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionState\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}