{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkQuality"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"txQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality","text":"AgoraNetworkQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rxQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality","text":"AgoraNetworkQuality"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"engine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AgoraRtcEngineKit object."}]}]},{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID. The network quality of the user with this user"},{"type":"text","text":" "},{"type":"text","text":"ID is reported."}]}]},{"name":"txQuality","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Uplink network quality rating of the user in terms of"},{"type":"text","text":" "},{"type":"text","text":"the transmission bit rate, packet loss rate, average RTT (Round-Trip Time)"},{"type":"text","text":" "},{"type":"text","text":"and jitter of the uplink network. This parameter is a quality rating helping"},{"type":"text","text":" "},{"type":"text","text":"you understand how well the current uplink network conditions can support the"},{"type":"text","text":" "},{"type":"text","text":"selected video encoder configuration. For example, a 1000 Kbps uplink network"},{"type":"text","text":" "},{"type":"text","text":"may be adequate for video frames with a resolution of 640 × 480 and a frame"},{"type":"text","text":" "},{"type":"text","text":"rate of 15 fps in the LIVE_BROADCASTING profile, but may be inadequate for"},{"type":"text","text":" "},{"type":"text","text":"resolutions higher than 1280 × 720. AgoraNetworkQualityUnknown(0): The"},{"type":"text","text":" "},{"type":"text","text":"quality is unknown.AgoraNetworkQualityExcellent(1): The quality is"},{"type":"text","text":" "},{"type":"text","text":"excellent.AgoraNetworkQualityGood(2): The network quality seems excellent,"},{"type":"text","text":" "},{"type":"text","text":"but the bitrate can be slightly lower than"},{"type":"text","text":" "},{"type":"text","text":"excellent.AgoraNetworkQualityPoor(3): Users can feel the communication is"},{"type":"text","text":" "},{"type":"text","text":"slightly impaired.AgoraNetworkQualityBad(4): Users cannot communicate"},{"type":"text","text":" "},{"type":"text","text":"smoothly.AgoraNetworkQualityVBad(5): The quality is so bad that users can"},{"type":"text","text":" "},{"type":"text","text":"barely communicate.AgoraNetworkQualityDown(6): The network is down, and users"},{"type":"text","text":" "},{"type":"text","text":"cannot communicate at all.See AgoraNetworkQuality ."}]}]},{"name":"rxQuality","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Downlink network quality rating of the user in terms"},{"type":"text","text":" "},{"type":"text","text":"of packet loss rate, average RTT, and jitter of the downlink network."},{"type":"text","text":" "},{"type":"text","text":"AgoraNetworkQualityUnknown(0): The quality is"},{"type":"text","text":" "},{"type":"text","text":"unknown.AgoraNetworkQualityExcellent(1): The quality is"},{"type":"text","text":" "},{"type":"text","text":"excellent.AgoraNetworkQualityGood(2): The network quality seems excellent,"},{"type":"text","text":" "},{"type":"text","text":"but the bitrate can be slightly lower than"},{"type":"text","text":" "},{"type":"text","text":"excellent.AgoraNetworkQualityPoor(3): Users can feel the communication is"},{"type":"text","text":" "},{"type":"text","text":"slightly impaired.AgoraNetworkQualityBad(4): Users cannot communicate"},{"type":"text","text":" "},{"type":"text","text":"smoothly.AgoraNetworkQualityVBad(5): The quality is so bad that users can"},{"type":"text","text":" "},{"type":"text","text":"barely communicate.AgoraNetworkQualityDown(6): The network is down, and users"},{"type":"text","text":" "},{"type":"text","text":"cannot communicate at all.See AgoraNetworkQuality ."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:networkquality:txquality:rxquality:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:networkquality:txquality:rxquality:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:networkQuality:txQuality:rxQuality:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reports the last mile network quality of each user in the channel."},{"type":"text","text":" "},{"type":"text","text":"This callback reports the last mile network conditions of each user in the"},{"type":"text","text":" "},{"type":"text","text":"channel. Last mile refers to the connection between the local device and"},{"type":"text","text":" "},{"type":"text","text":"Agora’s edge server.The SDK triggers this callback once every two seconds. If"},{"type":"text","text":" "},{"type":"text","text":"a channel includes multiple users, the SDK triggers this callback as many"},{"type":"text","text":" "},{"type":"text","text":"times.txQuality is Unknown when the user is not sending a stream; rxQuality"},{"type":"text","text":" "},{"type":"text","text":"is Unknown when the user is not receiving a stream."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}],"role":"symbol","title":"rtcEngine(_:networkQuality:txQuality:rxQuality:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"txQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rxQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate(im)rtcEngine:networkQuality:txQuality:rxQuality:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications"},{"type":"text","text":" "},{"type":"text","text":"to your app. Your app can get those notifications through methods that"},{"type":"text","text":" "},{"type":"text","text":"inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:networkQuality:txQuality:rxQuality:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}],"role":"symbol","title":"rtcEngine(_:networkQuality:txQuality:rxQuality:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"txQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rxQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reports the last mile network quality of each user in the channel."},{"type":"text","text":" "},{"type":"text","text":"This callback reports the last mile network conditions of each user in the"},{"type":"text","text":" "},{"type":"text","text":"channel. Last mile refers to the connection between the local device and"},{"type":"text","text":" "},{"type":"text","text":"Agora’s edge server.The SDK triggers this callback once every two seconds. If"},{"type":"text","text":" "},{"type":"text","text":"a channel includes multiple users, the SDK triggers this callback as many"},{"type":"text","text":" "},{"type":"text","text":"times.txQuality is Unknown when the user is not sending a stream; rxQuality"},{"type":"text","text":" "},{"type":"text","text":"is Unknown when the user is not receiving a stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:networkQuality:txQuality:rxQuality:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:networkquality:txquality:rxquality:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality":{"role":"symbol","title":"AgoraNetworkQuality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkQuality"}],"abstract":[{"type":"text","text":"Network quality types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQuality"}],"url":"\/documentation\/agorartckit\/agoranetworkquality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:networkQuality:txQuality:rxQuality:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkQuality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"txQuality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality","text":"AgoraNetworkQuality"},{"kind":"text","text":") "},{"kind":"internalParam","text":"txQuality"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxQuality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality","text":"AgoraNetworkQuality"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rxQuality"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:networkQuality:txQuality:rxQuality:)\/title","value":"rtcEngine:networkQuality:txQuality:rxQuality:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:networkQuality:txQuality:rxQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality\/title","value":"AgoraNetworkQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}