{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoRenderingTracingResultOfUid"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent","preciseIdentifier":"c:@E@AgoraMediaTraceEvent","text":"AgoraMediaTraceEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracingInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo","preciseIdentifier":"c:objc(cs)AgoraVideoRenderingTracingInfo","text":"AgoraVideoRenderingTracingInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID."}]}]},{"name":"currentEvent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current video frame rendering event. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaTraceEvent ."}]}]},{"name":"tracingInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The indicators during the video frame rendering"},{"type":"text","text":" "},{"type":"text","text":"process. Developers need to reduce the value of indicators as much as"},{"type":"text","text":" "},{"type":"text","text":"possible in order to improve the efficiency of the first video frame"},{"type":"text","text":" "},{"type":"text","text":"rendering. See AgoraVideoRenderingTracingInfo ."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:videorenderingtracingresultofuid:currentevent:tracinginfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:videorenderingtracingresultofuid:currentevent:tracinginfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video frame rendering event callback."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1After calling the startMediaRenderingTracing method or joining the"},{"type":"text","text":" "},{"type":"text","text":"channel, the SDK triggers this callback to report the events of video frame"},{"type":"text","text":" "},{"type":"text","text":"rendering and the indicators during the rendering process. Developers can"},{"type":"text","text":" "},{"type":"text","text":"optimize the indicators to improve the efficiency of the first video frame"},{"type":"text","text":" "},{"type":"text","text":"rendering."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:"}],"role":"symbol","title":"rtcEngine(_:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoRenderingTracingResultOfUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaTraceEvent","preciseIdentifier":"c:@E@AgoraMediaTraceEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracingInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderingTracingInfo","preciseIdentifier":"c:objc(cs)AgoraVideoRenderingTracingInfo"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate(im)rtcEngine:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo":{"role":"symbol","title":"AgoraVideoRenderingTracingInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"abstract":[{"type":"text","text":"Indicators during video frame rendering progress."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent":{"role":"symbol","title":"AgoraMediaTraceEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"abstract":[{"type":"text","text":"The rendering state of the media frame."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"url":"\/documentation\/agorartckit\/agoramediatraceevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:"}],"role":"symbol","title":"rtcEngine(_:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoRenderingTracingResultOfUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaTraceEvent","preciseIdentifier":"c:@E@AgoraMediaTraceEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracingInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderingTracingInfo","preciseIdentifier":"c:objc(cs)AgoraVideoRenderingTracingInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Video frame rendering event callback."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1After calling the startMediaRenderingTracing method or joining the"},{"type":"text","text":" "},{"type":"text","text":"channel, the SDK triggers this callback to report the events of video frame"},{"type":"text","text":" "},{"type":"text","text":"rendering and the indicators during the rendering process. Developers can"},{"type":"text","text":" "},{"type":"text","text":"optimize the indicators to improve the efficiency of the first video frame"},{"type":"text","text":" "},{"type":"text","text":"rendering."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:videorenderingtracingresultofuid:currentevent:tracinginfo:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications"},{"type":"text","text":" "},{"type":"text","text":"to your app. Your app can get those notifications through methods that"},{"type":"text","text":" "},{"type":"text","text":"inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRenderingTracingResultOfUid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent","preciseIdentifier":"c:@E@AgoraMediaTraceEvent","text":"AgoraMediaTraceEvent"},{"kind":"text","text":") "},{"kind":"internalParam","text":"currentEvent"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracingInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo","preciseIdentifier":"c:objc(cs)AgoraVideoRenderingTracingInfo","text":"AgoraVideoRenderingTracingInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tracingInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/title","value":"AgoraVideoRenderingTracingInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent\/title","value":"AgoraMediaTraceEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:)\/title","value":"rtcEngine:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:videoRenderingTracingResultOfUid:currentEvent:tracingInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}