{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localAudioStats"},{"kind":"text","text":" "},{"kind":"internalParam","text":"stats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","preciseIdentifier":"c:objc(cs)AgoraRtcLocalAudioStats","text":"AgoraRtcLocalAudioStats"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"engine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"One AgoraRtcEngineKit object."}]}]},{"name":"stats","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Local audio statistics. See AgoraRtcLocalAudioStats."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK triggers this callback once every two seconds."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:localaudiostats:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:localaudiostats:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:localAudioStats:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reports the statistics of the local audio stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localAudioStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcLocalAudioStats","preciseIdentifier":"c:objc(cs)AgoraRtcLocalAudioStats"},{"kind":"text","text":")"}],"title":"rtcEngine(_:localAudioStats:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate(im)rtcEngine:localAudioStats:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:localAudioStats:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:localAudioStats:)":{"role":"symbol","title":"rtcEngine(_:localAudioStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localAudioStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcLocalAudioStats","preciseIdentifier":"c:objc(cs)AgoraRtcLocalAudioStats"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reports the statistics of the local audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:localAudioStats:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:localAudioStats:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:localaudiostats:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications to your app. Your app can get those notifications through methods that inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats":{"role":"symbol","title":"AgoraRtcLocalAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"abstract":[{"type":"text","text":"Local audio statistics."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:localAudioStats:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:localAudioStats:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"localAudioStats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","preciseIdentifier":"c:objc(cs)AgoraRtcLocalAudioStats","text":"AgoraRtcLocalAudioStats"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"stats"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:localAudioStats:)\/title","value":"rtcEngine:localAudioStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:localAudioStats:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:localAudioStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/title","value":"AgoraRtcLocalAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}