{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"firstRemoteAudioFrameOfUid"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"engine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AgoraRtcEngineKit object."}]}]},{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the user or host who joins the channel."}]}]},{"name":"elapsed","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Time delay (ms) from the local user calling"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [2\/4] until this callback is triggered."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:firstremoteaudioframeofuid:elapsed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:firstremoteaudioframeofuid:elapsed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:firstRemoteAudioFrameOfUid:elapsed:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when a remote user (COMMUNICATION)\/ host (LIVE_BROADCASTING) joins the"},{"type":"text","text":" "},{"type":"text","text":"channel. In a communication channel, this callback indicates that a remote"},{"type":"text","text":" "},{"type":"text","text":"user joins the channel. The SDK also triggers this callback to report the"},{"type":"text","text":" "},{"type":"text","text":"existing users in the channel when a user joins the channel.In a"},{"type":"text","text":" "},{"type":"text","text":"live-broadcast channel, this callback indicates that a host joins the"},{"type":"text","text":" "},{"type":"text","text":"channel. The SDK also triggers this callback to report the existing hosts in"},{"type":"text","text":" "},{"type":"text","text":"the channel when a host joins the channel. Agora recommends limiting the"},{"type":"text","text":" "},{"type":"text","text":"number of hosts to 17.The SDK triggers this callback under one of the"},{"type":"text","text":" "},{"type":"text","text":"following circumstances:A remote user\/host joins the channel by calling the"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [2\/4] method.A remote user switches the user role to the"},{"type":"text","text":" "},{"type":"text","text":"host after joining the channel.A remote user\/host rejoins the channel after a"},{"type":"text","text":" "},{"type":"text","text":"network interruption."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:firstRemoteAudioFrameOfUid:elapsed:"}],"role":"symbol","title":"rtcEngine(_:firstRemoteAudioFrameOfUid:elapsed:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"firstRemoteAudioFrameOfUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate(im)rtcEngine:firstRemoteAudioFrameOfUid:elapsed:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications"},{"type":"text","text":" "},{"type":"text","text":"to your app. Your app can get those notifications through methods that"},{"type":"text","text":" "},{"type":"text","text":"inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:firstRemoteAudioFrameOfUid:elapsed:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:firstRemoteAudioFrameOfUid:elapsed:"}],"role":"symbol","title":"rtcEngine(_:firstRemoteAudioFrameOfUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"firstRemoteAudioFrameOfUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a remote user (COMMUNICATION)\/ host (LIVE_BROADCASTING) joins the"},{"type":"text","text":" "},{"type":"text","text":"channel. In a communication channel, this callback indicates that a remote"},{"type":"text","text":" "},{"type":"text","text":"user joins the channel. The SDK also triggers this callback to report the"},{"type":"text","text":" "},{"type":"text","text":"existing users in the channel when a user joins the channel.In a"},{"type":"text","text":" "},{"type":"text","text":"live-broadcast channel, this callback indicates that a host joins the"},{"type":"text","text":" "},{"type":"text","text":"channel. The SDK also triggers this callback to report the existing hosts in"},{"type":"text","text":" "},{"type":"text","text":"the channel when a host joins the channel. Agora recommends limiting the"},{"type":"text","text":" "},{"type":"text","text":"number of hosts to 17.The SDK triggers this callback under one of the"},{"type":"text","text":" "},{"type":"text","text":"following circumstances:A remote user\/host joins the channel by calling the"},{"type":"text","text":" "},{"type":"text","text":"joinChannelByToken [2\/4] method.A remote user switches the user role to the"},{"type":"text","text":" "},{"type":"text","text":"host after joining the channel.A remote user\/host rejoins the channel after a"},{"type":"text","text":" "},{"type":"text","text":"network interruption."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:firstRemoteAudioFrameOfUid:elapsed:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:firstremoteaudioframeofuid:elapsed:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:firstRemoteAudioFrameOfUid:elapsed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:firstRemoteAudioFrameOfUid:elapsed:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstRemoteAudioFrameOfUid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"elapsed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"elapsed"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:firstRemoteAudioFrameOfUid:elapsed:)\/title","value":"rtcEngine:firstRemoteAudioFrameOfUid:elapsed:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:firstRemoteAudioFrameOfUid:elapsed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:firstRemoteAudioFrameOfUid:elapsed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}