{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"facePositionDidChangeWidth"},{"kind":"text","text":" "},{"kind":"internalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewHeight"},{"kind":"text","text":" "},{"kind":"internalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faces"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraFacePositionInfo","preciseIdentifier":"c:objc(cs)AgoraFacePositionInfo","text":"AgoraFacePositionInfo"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"engine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AgoraRtcEngineKit object."}]}]},{"name":"width","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The width (px) of the video image captured by the local"},{"type":"text","text":" "},{"type":"text","text":"camera."}]}]},{"name":"hight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The height (px) of the video image captured by the local"},{"type":"text","text":" "},{"type":"text","text":"camera."}]}]},{"name":"faces","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For the information of the detected face. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraFacePositionInfo for details. If several faces are detected, this"},{"type":"text","text":" "},{"type":"text","text":"callback reports several AgoraFacePositionInfo arrays. The length of the"},{"type":"text","text":" "},{"type":"text","text":"array can be 0, which means that no human face is detected in front of the"},{"type":"text","text":" "},{"type":"text","text":"camera."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:facepositiondidchangewidth:previewheight:faces:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:facepositiondidchangewidth:previewheight:faces:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reports the face detection result of the local user."},{"type":"text","text":" "},{"type":"text","text":"Once you enable face detection by calling enableFaceDetection (YES), you can"},{"type":"text","text":" "},{"type":"text","text":"get the following information on the local user in real-time:The width and"},{"type":"text","text":" "},{"type":"text","text":"height of the local video.The position of the human face in the local"},{"type":"text","text":" "},{"type":"text","text":"view.The distance between the human face and the screen.This value is based"},{"type":"text","text":" "},{"type":"text","text":"on the fitting calculation of the local video size and the position of the"},{"type":"text","text":" "},{"type":"text","text":"human face.When it is detected that the face in front of the camera"},{"type":"text","text":" "},{"type":"text","text":"disappears, the callback will be triggered immediately. When no human face is"},{"type":"text","text":" "},{"type":"text","text":"detected, the frequency of this callback to be rtriggered wil be decreased to"},{"type":"text","text":" "},{"type":"text","text":"reduce power consumption on the local device.The SDK stops triggering this"},{"type":"text","text":" "},{"type":"text","text":"callback when a human face is in close proximity to the screen."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"facePositionDidChangeWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faces"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraFacePositionInfo","preciseIdentifier":"c:objc(cs)AgoraFacePositionInfo"},{"kind":"text","text":"]?)"}],"title":"rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate(im)rtcEngine:facePositionDidChangeWidth:previewHeight:faces:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraFacePositionInfo":{"role":"symbol","title":"AgoraFacePositionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraFacePositionInfo"}],"abstract":[{"type":"text","text":"The information of the detected human face."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraFacePositionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraFacePositionInfo"}],"url":"\/documentation\/agorartckit\/agorafacepositioninfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)":{"role":"symbol","title":"rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"facePositionDidChangeWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faces"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraFacePositionInfo","preciseIdentifier":"c:objc(cs)AgoraFacePositionInfo"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Reports the face detection result of the local user."},{"type":"text","text":" "},{"type":"text","text":"Once you enable face detection by calling enableFaceDetection (YES), you can"},{"type":"text","text":" "},{"type":"text","text":"get the following information on the local user in real-time:The width and"},{"type":"text","text":" "},{"type":"text","text":"height of the local video.The position of the human face in the local"},{"type":"text","text":" "},{"type":"text","text":"view.The distance between the human face and the screen.This value is based"},{"type":"text","text":" "},{"type":"text","text":"on the fitting calculation of the local video size and the position of the"},{"type":"text","text":" "},{"type":"text","text":"human face.When it is detected that the face in front of the camera"},{"type":"text","text":" "},{"type":"text","text":"disappears, the callback will be triggered immediately. When no human face is"},{"type":"text","text":" "},{"type":"text","text":"detected, the frequency of this callback to be rtriggered wil be decreased to"},{"type":"text","text":" "},{"type":"text","text":"reduce power consumption on the local device.The SDK stops triggering this"},{"type":"text","text":" "},{"type":"text","text":"callback when a human face is in close proximity to the screen."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:facepositiondidchangewidth:previewheight:faces:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications"},{"type":"text","text":" "},{"type":"text","text":"to your app. Your app can get those notifications through methods that"},{"type":"text","text":" "},{"type":"text","text":"inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"facePositionDidChangeWidth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewHeight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"height"},{"kind":"text","text":" "},{"kind":"identifier","text":"faces:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<AgoraFacePositionInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faces"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraFacePositionInfo\/title","value":"AgoraFacePositionInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraFacePositionInfo\/fragments","value":[{"kind":"identifier","text":"AgoraFacePositionInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)\/title","value":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}