{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reportAudioVolumeIndicationOfSpeakers"},{"kind":"text","text":" "},{"kind":"internalParam","text":"speakers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcAudioVolumeInfo","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo","text":"AgoraRtcAudioVolumeInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"totalVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"engine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AgoraRtcEngineKit object."}]}]},{"name":"speakers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The volume information of the users, see"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcAudioVolumeInfo . An empty speakers array in the callback indicates"},{"type":"text","text":" "},{"type":"text","text":"that no remote user is in the channel or is sending a stream."}]}]},{"name":"totalVolume","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The volume of the speaker. The value range is"},{"type":"text","text":" "},{"type":"text","text":"[0,255].In the callback for the local user, totalVolume is the volume of the"},{"type":"text","text":" "},{"type":"text","text":"local user who sends a stream.In the callback for remote users, totalVolume"},{"type":"text","text":" "},{"type":"text","text":"is the sum of the volume of all remote users (up to three) whose"},{"type":"text","text":" "},{"type":"text","text":"instantaneous volume is the highest. If the user calls startAudioMixing [2\/2]"},{"type":"text","text":" "},{"type":"text","text":", then totalVolume is the volume after audio mixing."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reports the volume information of users."},{"type":"text","text":" "},{"type":"text","text":"By default, this callback is disabled. You can enable it by calling"},{"type":"text","text":" "},{"type":"text","text":"enableAudioVolumeIndication . Once this callback is enabled and users send"},{"type":"text","text":" "},{"type":"text","text":"streams in the channel, the SDK triggers the"},{"type":"text","text":" "},{"type":"text","text":"reportAudioVolumeIndicationOfSpeakers callback according to the time interval"},{"type":"text","text":" "},{"type":"text","text":"set in enableAudioVolumeIndication. The SDK triggers two independent"},{"type":"text","text":" "},{"type":"text","text":"reportAudioVolumeIndicationOfSpeakers callbacks simultaneously, which"},{"type":"text","text":" "},{"type":"text","text":"separately report the volume information of the local user who sends a stream"},{"type":"text","text":" "},{"type":"text","text":"and the remote users (up to three) whose instantaneous volume is the"},{"type":"text","text":" "},{"type":"text","text":"highest.Once this callback is enabled, if the local user calls the"},{"type":"text","text":" "},{"type":"text","text":"muteLocalAudioStream method for muting, the SDK continues to report the"},{"type":"text","text":" "},{"type":"text","text":"volume indication of the local user. In the callbacks triggered, the volume"},{"type":"text","text":" "},{"type":"text","text":"information about the local user is 0 If a remote user whose volume is one of"},{"type":"text","text":" "},{"type":"text","text":"the three highest in the channel stops publishing the audio stream for 20"},{"type":"text","text":" "},{"type":"text","text":"seconds, the callback excludes this user’s information; if all remote users"},{"type":"text","text":" "},{"type":"text","text":"stop publishing audio streams for 20 seconds, the SDK stops triggering the"},{"type":"text","text":" "},{"type":"text","text":"callback for remote users."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reportAudioVolumeIndicationOfSpeakers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraRtcAudioVolumeInfo","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"totalVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate(im)rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications"},{"type":"text","text":" "},{"type":"text","text":"to your app. Your app can get those notifications through methods that"},{"type":"text","text":" "},{"type":"text","text":"inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)":{"role":"symbol","title":"rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reportAudioVolumeIndicationOfSpeakers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraRtcAudioVolumeInfo","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"totalVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reports the volume information of users."},{"type":"text","text":" "},{"type":"text","text":"By default, this callback is disabled. You can enable it by calling"},{"type":"text","text":" "},{"type":"text","text":"enableAudioVolumeIndication . Once this callback is enabled and users send"},{"type":"text","text":" "},{"type":"text","text":"streams in the channel, the SDK triggers the"},{"type":"text","text":" "},{"type":"text","text":"reportAudioVolumeIndicationOfSpeakers callback according to the time interval"},{"type":"text","text":" "},{"type":"text","text":"set in enableAudioVolumeIndication. The SDK triggers two independent"},{"type":"text","text":" "},{"type":"text","text":"reportAudioVolumeIndicationOfSpeakers callbacks simultaneously, which"},{"type":"text","text":" "},{"type":"text","text":"separately report the volume information of the local user who sends a stream"},{"type":"text","text":" "},{"type":"text","text":"and the remote users (up to three) whose instantaneous volume is the"},{"type":"text","text":" "},{"type":"text","text":"highest.Once this callback is enabled, if the local user calls the"},{"type":"text","text":" "},{"type":"text","text":"muteLocalAudioStream method for muting, the SDK continues to report the"},{"type":"text","text":" "},{"type":"text","text":"volume indication of the local user. In the callbacks triggered, the volume"},{"type":"text","text":" "},{"type":"text","text":"information about the local user is 0 If a remote user whose volume is one of"},{"type":"text","text":" "},{"type":"text","text":"the three highest in the channel stops publishing the audio stream for 20"},{"type":"text","text":" "},{"type":"text","text":"seconds, the callback excludes this user’s information; if all remote users"},{"type":"text","text":" "},{"type":"text","text":"stop publishing audio streams for 20 seconds, the SDK stops triggering the"},{"type":"text","text":" "},{"type":"text","text":"callback for remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcAudioVolumeInfo":{"role":"symbol","title":"AgoraRtcAudioVolumeInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcAudioVolumeInfo"}],"abstract":[{"type":"text","text":"The volume information of users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcAudioVolumeInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcAudioVolumeInfo"}],"url":"\/documentation\/agorartckit\/agorartcaudiovolumeinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportAudioVolumeIndicationOfSpeakers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<AgoraRtcAudioVolumeInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"speakers"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalVolume:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"totalVolume"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/title","value":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcAudioVolumeInfo\/title","value":"AgoraRtcAudioVolumeInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcAudioVolumeInfo\/fragments","value":[{"kind":"identifier","text":"AgoraRtcAudioVolumeInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}