{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communication"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelprofile\/communication"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelprofile\/communication"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: Communication. Use this profile when there are only two users in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communication"}],"title":"AgoraChannelProfile.communication","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChannelProfile@AgoraChannelProfileCommunication","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileCommunication"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile":{"role":"symbol","title":"AgoraChannelProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelProfile"}],"abstract":[{"type":"text","text":"The channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfile"}],"url":"\/documentation\/agorartckit\/agorachannelprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/communication":{"role":"symbol","title":"AgoraChannelProfile.communication","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communication"}],"abstract":[{"type":"text","text":"0: Communication. Use this profile when there are only two users in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileCommunication"}],"url":"\/documentation\/agorartckit\/agorachannelprofile\/communication"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelProfileCommunication"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileCommunication"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChannelProfileCommunication"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile\/title","value":"AgoraChannelProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1communication\/title","value":"AgoraChannelProfileCommunication"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1communication\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileCommunication"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}