{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveBroadcasting"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelprofile\/livebroadcasting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelprofile\/livebroadcasting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/liveBroadcasting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Live streaming. Live streaming. Use this profile when there are more"},{"type":"text","text":" "},{"type":"text","text":"than two users in the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveBroadcasting"}],"title":"AgoraChannelProfile.liveBroadcasting","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraChannelProfile@AgoraChannelProfileLiveBroadcasting","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileLiveBroadcasting"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/liveBroadcasting":{"role":"symbol","title":"AgoraChannelProfile.liveBroadcasting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveBroadcasting"}],"abstract":[{"type":"text","text":"1: Live streaming. Live streaming. Use this profile when there are more"},{"type":"text","text":" "},{"type":"text","text":"than two users in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/liveBroadcasting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileLiveBroadcasting"}],"url":"\/documentation\/agorartckit\/agorachannelprofile\/livebroadcasting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile":{"role":"symbol","title":"AgoraChannelProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelProfile"}],"abstract":[{"type":"text","text":"The channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfile"}],"url":"\/documentation\/agorartckit\/agorachannelprofile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelProfileLiveBroadcasting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileLiveBroadcasting"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraChannelProfileLiveBroadcasting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1liveBroadcasting\/title","value":"AgoraChannelProfileLiveBroadcasting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1liveBroadcasting\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileLiveBroadcasting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile\/title","value":"AgoraChannelProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}