{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerOnSeekCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCustomSourceOnSeekCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnSeekCallback","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediasource\/playeronseekcallback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediasource\/playeronseekcallback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSource\/playerOnSeekCallback","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerOnSeekCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}],"title":"playerOnSeekCallback","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraMediaSource(py)playerOnSeekCallback","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"playerOnSeekCallback"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSource"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSource":{"role":"symbol","title":"AgoraMediaSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaSource"}],"abstract":[{"type":"text","text":"Information related to the media file to be played and the playback scenario configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSource"}],"url":"\/documentation\/agorartckit\/agoramediasource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerCustomSourceOnSeekCallback":{"role":"symbol","title":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCustomSourceOnSeekCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayercustomsourceonseekcallback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSource/playerOnSeekCallback":{"role":"symbol","title":"playerOnSeekCallback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerOnSeekCallback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSource\/playerOnSeekCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerOnSeekCallback"}],"url":"\/documentation\/agorartckit\/agoramediasource\/playeronseekcallback"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"playerOnSeekCallback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"playerOnSeekCallback"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"long long (^)(id<AgoraRtcMediaPlayerProtocol>, long long, int)","preciseIdentifier":"c:BFK(#*Qoobjc(pl)AgoraRtcMediaPlayerProtocol#K#I)"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerOnSeekCallback"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSource\/title","value":"AgoraMediaSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSource\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCustomSourceOnSeekCallback\/title","value":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCustomSourceOnSeekCallback\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSource~1playerOnSeekCallback\/title","value":"playerOnSeekCallback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSource~1playerOnSeekCallback\/fragments","value":[{"kind":"identifier","text":"playerOnSeekCallback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}