{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracameradirection\/front"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracameradirection\/front"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection\/front","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The front camera."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"title":"AgoraCameraDirection.front","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCameraDirection@AgoraCameraDirectionFront","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCameraDirectionFront"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraDirection":{"role":"symbol","title":"AgoraCameraDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCameraDirection"}],"abstract":[{"type":"text","text":"The camera direction."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraDirection"}],"url":"\/documentation\/agorartckit\/agoracameradirection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraDirection/front":{"role":"symbol","title":"AgoraCameraDirection.front","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"abstract":[{"type":"text","text":"The front camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection\/front","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraDirectionFront"}],"url":"\/documentation\/agorartckit\/agoracameradirection\/front"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCameraDirectionFront"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCameraDirectionFront"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCameraDirectionFront"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection\/title","value":"AgoraCameraDirection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection\/fragments","value":[{"kind":"identifier","text":"AgoraCameraDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection~1front\/title","value":"AgoraCameraDirectionFront"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection~1front\/fragments","value":[{"kind":"identifier","text":"AgoraCameraDirectionFront"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}