{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rear"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracameradirection\/rear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracameradirection\/rear"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection\/rear","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The rear camera."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rear"}],"title":"AgoraCameraDirection.rear","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCameraDirection@AgoraCameraDirectionRear","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCameraDirectionRear"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraDirection":{"role":"symbol","title":"AgoraCameraDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCameraDirection"}],"abstract":[{"type":"text","text":"The camera direction."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraDirection"}],"url":"\/documentation\/agorartckit\/agoracameradirection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraDirection/rear":{"role":"symbol","title":"AgoraCameraDirection.rear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rear"}],"abstract":[{"type":"text","text":"The rear camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection\/rear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraDirectionRear"}],"url":"\/documentation\/agorartckit\/agoracameradirection\/rear"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCameraDirectionRear"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCameraDirectionRear"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCameraDirectionRear"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection\/title","value":"AgoraCameraDirection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection\/fragments","value":[{"kind":"identifier","text":"AgoraCameraDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection~1rear\/title","value":"AgoraCameraDirectionRear"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection~1rear\/fragments","value":[{"kind":"identifier","text":"AgoraCameraDirectionRear"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}