{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_aggressive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_aggressive"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_AGGRESSIVE","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Aggressive mode. In scenarios where high performance on noise suppression is required, such as live streaming outdoor events, this mode reduces nosie more dramatically, but may sometimes affect the original character of the audio."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}],"title":"AUDIO_AINS_MODE.AINS_MODE_AGGRESSIVE","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AUDIO_AINS_MODE@AINS_MODE_AGGRESSIVE","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/AINS_MODE_AGGRESSIVE":{"role":"symbol","title":"AUDIO_AINS_MODE.AINS_MODE_AGGRESSIVE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}],"abstract":[{"type":"text","text":"1: Aggressive mode. In scenarios where high performance on noise suppression is required, such as live streaming outdoor events, this mode reduces nosie more dramatically, but may sometimes affect the original character of the audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_AGGRESSIVE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}],"url":"\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_aggressive"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE":{"role":"symbol","title":"AUDIO_AINS_MODE","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"abstract":[{"type":"text","text":"AI noise suppression modes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"url":"\/documentation\/agorartckit\/audio_ains_mode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AINS_MODE_AGGRESSIVE"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_AGGRESSIVE\/title","value":"AINS_MODE_AGGRESSIVE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_AGGRESSIVE\/fragments","value":[{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE\/title","value":"AUDIO_AINS_MODE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE\/fragments","value":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}