{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_ultralowlatency"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_ultralowlatency"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_ULTRALOWLATENCY","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}],"title":"AUDIO_AINS_MODE.AINS_MODE_ULTRALOWLATENCY","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AUDIO_AINS_MODE@AINS_MODE_ULTRALOWLATENCY","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/AINS_MODE_ULTRALOWLATENCY":{"role":"symbol","title":"AUDIO_AINS_MODE.AINS_MODE_ULTRALOWLATENCY","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_ULTRALOWLATENCY","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}],"url":"\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_ultralowlatency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE":{"role":"symbol","title":"AUDIO_AINS_MODE","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"url":"\/documentation\/agorartckit\/audio_ains_mode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AINS_MODE_ULTRALOWLATENCY"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_ULTRALOWLATENCY\/title","value":"AINS_MODE_ULTRALOWLATENCY"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_ULTRALOWLATENCY\/fragments","value":[{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE\/title","value":"AUDIO_AINS_MODE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE\/fragments","value":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}