{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxVocalConcert"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxvocalconcert"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxvocalconcert"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxVocalConcert","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The reverb style typical of a concert hall (enhanced)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxVocalConcert"}],"title":"AgoraAudioReverbPreset.fxVocalConcert","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioReverbPreset@AgoraAudioReverbPresetFxVocalConcert","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxVocalConcert"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset":{"role":"symbol","title":"AgoraAudioReverbPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"abstract":[{"type":"text","text":"Voice reverb presets."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Deprecated as of v3.2.0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxVocalConcert":{"role":"symbol","title":"AgoraAudioReverbPreset.fxVocalConcert","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxVocalConcert"}],"abstract":[{"type":"text","text":"The reverb style typical of a concert hall (enhanced)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxVocalConcert","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxVocalConcert"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxvocalconcert"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioReverbPresetFxVocalConcert"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxVocalConcert"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxVocalConcert"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset\/title","value":"AgoraAudioReverbPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxVocalConcert\/title","value":"AgoraAudioReverbPresetFxVocalConcert"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxVocalConcert\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxVocalConcert"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}