{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioreverbpreset\/off"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioreverbpreset\/off"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/off","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Turn off voice reverb, that is, to use the original voice."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"title":"AgoraAudioReverbPreset.off","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioReverbPreset@AgoraAudioReverbPresetOff","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetOff"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset":{"role":"symbol","title":"AgoraAudioReverbPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"abstract":[{"type":"text","text":"Voice reverb presets."},{"type":"text","text":" "},{"type":"text","text":"Deprecated:Deprecated as of v3.2.0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/off":{"role":"symbol","title":"AgoraAudioReverbPreset.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"Turn off voice reverb, that is, to use the original voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetOff"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/off"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioReverbPresetOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetOff"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioReverbPresetOff"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset\/title","value":"AgoraAudioReverbPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1off\/title","value":"AgoraAudioReverbPresetOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1off\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}