{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderConfiguration","text":"AgoraMediaRecorderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorder\/startrecording(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorder\/startrecording(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/startRecording(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorderConfiguration","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"startRecording(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraMediaRecorder(im)startRecording:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"startRecording:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder":{"role":"symbol","title":"AgoraMediaRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorder"}],"abstract":[{"type":"text","text":"Used for recording audio and video on the client."},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaRecorder can record the following:"},{"type":"text","text":" "},{"type":"text","text":"The audio captured by the local microphone and encoded in AAC format.The"},{"type":"text","text":" "},{"type":"text","text":"video captured by the local camera and encoded by the SDK.In the"},{"type":"text","text":" "},{"type":"text","text":"COMMUNICATION channel profile, this feature is unavailable when there are"},{"type":"text","text":" "},{"type":"text","text":"users using SDK versions earlier than v3.0.0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorder"}],"url":"\/documentation\/agorartckit\/agoramediarecorder"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder/startRecording(_:)":{"role":"symbol","title":"startRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorderConfiguration","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/startRecording(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startRecording:"}],"url":"\/documentation\/agorartckit\/agoramediarecorder\/startrecording(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration":{"role":"symbol","title":"AgoraMediaRecorderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"abstract":[{"type":"text","text":"Configurations for the local audio and video recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startRecording:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRecording:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"startRecording:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderConfiguration","text":"AgoraMediaRecorderConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/title","value":"AgoraMediaRecorder"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorder"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1startRecording(_:)\/title","value":"startRecording:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1startRecording(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRecording:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/title","value":"AgoraMediaRecorderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}