{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityChangedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason","preciseIdentifier":"c:@E@AgoraExperiencePoorReason","text":"AgoraExperiencePoorReason"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcremoteaudiostats\/qualitychangedreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcremoteaudiostats\/qualitychangedreason"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qualityChangedReason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is"},{"type":"text","text":" "},{"type":"text","text":"poor. See AgoraExperiencePoorReason ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityChangedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraExperiencePoorReason","preciseIdentifier":"c:@E@AgoraExperiencePoorReason"}],"title":"qualityChangedReason","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcRemoteAudioStats(py)qualityChangedReason","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"qualityChangedReason"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats":{"role":"symbol","title":"AgoraRtcRemoteAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}],"abstract":[{"type":"text","text":"Audio statistics of the remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperiencePoorReason":{"role":"symbol","title":"AgoraExperiencePoorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is"},{"type":"text","text":" "},{"type":"text","text":"poor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}],"url":"\/documentation\/agorartckit\/agoraexperiencepoorreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/qualityChangedReason":{"role":"symbol","title":"qualityChangedReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityChangedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraExperiencePoorReason","preciseIdentifier":"c:@E@AgoraExperiencePoorReason"}],"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is"},{"type":"text","text":" "},{"type":"text","text":"poor. See AgoraExperiencePoorReason ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qualityChangedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityChangedReason"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/qualitychangedreason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"qualityChangedReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"qualityChangedReason"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperiencePoorReason","preciseIdentifier":"c:@E@AgoraExperiencePoorReason","text":"AgoraExperiencePoorReason"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityChangedReason"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats\/title","value":"AgoraRtcRemoteAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/title","value":"AgoraExperiencePoorReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperiencePoorReason\/fragments","value":[{"kind":"identifier","text":"AgoraExperiencePoorReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1qualityChangedReason\/title","value":"qualityChangedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1qualityChangedReason\/fragments","value":[{"kind":"identifier","text":"qualityChangedReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}