{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracompressionpreference\/lowlatency"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracompressionpreference\/lowlatency"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCompressionPreference\/lowLatency","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: Low latency preference. The SDK compresses video frames to reduce latency. This preference is suitable for scenarios where smoothness is prioritized and reduced video quality is acceptable."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"}],"title":"AgoraCompressionPreference.lowLatency","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCompressionPreference@AgoraCompressionLowLatency","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCompressionLowLatency"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCompressionPreference"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCompressionPreference":{"role":"symbol","title":"AgoraCompressionPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCompressionPreference"}],"abstract":[{"type":"text","text":"Compression preference for video encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCompressionPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCompressionPreference"}],"url":"\/documentation\/agorartckit\/agoracompressionpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCompressionPreference/lowLatency":{"role":"symbol","title":"AgoraCompressionPreference.lowLatency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"}],"abstract":[{"type":"text","text":"0: Low latency preference. The SDK compresses video frames to reduce latency. This preference is suitable for scenarios where smoothness is prioritized and reduced video quality is acceptable."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCompressionPreference\/lowLatency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCompressionLowLatency"}],"url":"\/documentation\/agorartckit\/agoracompressionpreference\/lowlatency"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCompressionLowLatency"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCompressionLowLatency"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCompressionLowLatency"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCompressionPreference\/title","value":"AgoraCompressionPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCompressionPreference\/fragments","value":[{"kind":"identifier","text":"AgoraCompressionPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCompressionPreference~1lowLatency\/title","value":"AgoraCompressionLowLatency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCompressionPreference~1lowLatency\/fragments","value":[{"kind":"identifier","text":"AgoraCompressionLowLatency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}