{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSuccess"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorainjectstreamstatus\/startsuccess"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorainjectstreamstatus\/startsuccess"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startSuccess","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSuccess"}],"title":"AgoraInjectStreamStatus.startSuccess","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraInjectStreamStatus@AgoraInjectStreamStatusStartSuccess","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartSuccess"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/startSuccess":{"role":"symbol","title":"AgoraInjectStreamStatus.startSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSuccess"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartSuccess"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/startsuccess"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus":{"role":"symbol","title":"AgoraInjectStreamStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraInjectStreamStatusStartSuccess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartSuccess"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartSuccess"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startSuccess\/title","value":"AgoraInjectStreamStatusStartSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus\/title","value":"AgoraInjectStreamStatus"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}