{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTimedout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorainjectstreamstatus\/stoptimedout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorainjectstreamstatus\/stoptimedout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopTimedout","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTimedout"}],"title":"AgoraInjectStreamStatus.stopTimedout","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraInjectStreamStatus@AgoraInjectStreamStatusStopTimedout","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopTimedout"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus":{"role":"symbol","title":"AgoraInjectStreamStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/stopTimedout":{"role":"symbol","title":"AgoraInjectStreamStatus.stopTimedout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTimedout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopTimedout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopTimedout"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/stoptimedout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraInjectStreamStatusStopTimedout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopTimedout"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopTimedout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus\/title","value":"AgoraInjectStreamStatus"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopTimedout\/title","value":"AgoraInjectStreamStatusStopTimedout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopTimedout\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopTimedout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}