{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HEAAC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiocodecprofiletype\/heaac"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiocodecprofiletype\/heaac"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecProfileType\/HEAAC","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: HE-AAC."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HEAAC"}],"title":"AgoraAudioCodecProfileType.HEAAC","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioCodecProfileType@AgoraAudioCodecProfileHEAAC","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecProfileHEAAC"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecProfileType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecProfileType/HEAAC":{"role":"symbol","title":"AgoraAudioCodecProfileType.HEAAC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HEAAC"}],"abstract":[{"type":"text","text":"1: HE-AAC."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecProfileType\/HEAAC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecProfileHEAAC"}],"url":"\/documentation\/agorartckit\/agoraaudiocodecprofiletype\/heaac"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecProfileType":{"role":"symbol","title":"AgoraAudioCodecProfileType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioCodecProfileType"}],"abstract":[{"type":"text","text":"Self-defined audio codec profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecProfileType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecProfileType"}],"url":"\/documentation\/agorartckit\/agoraaudiocodecprofiletype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioCodecProfileHEAAC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecProfileHEAAC"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioCodecProfileHEAAC"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecProfileType~1HEAAC\/title","value":"AgoraAudioCodecProfileHEAAC"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecProfileType~1HEAAC\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecProfileHEAAC"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecProfileType\/title","value":"AgoraAudioCodecProfileType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecProfileType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecProfileType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}