{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundSourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSourceType","preciseIdentifier":"c:@E@AgoraVirtualBackgroundSourceType","text":"AgoraVirtualBackgroundSourceType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource\/backgroundsourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource\/backgroundsourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/backgroundSourceType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of the custom background image. See AgoraVirtualBackgroundSourceType"},{"type":"text","text":" "},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundSourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVirtualBackgroundSourceType","preciseIdentifier":"c:@E@AgoraVirtualBackgroundSourceType"}],"title":"backgroundSourceType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVirtualBackgroundSource(py)backgroundSourceType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"backgroundSourceType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource":{"role":"symbol","title":"AgoraVirtualBackgroundSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"abstract":[{"type":"text","text":"The custom background image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource/backgroundSourceType":{"role":"symbol","title":"backgroundSourceType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundSourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVirtualBackgroundSourceType","preciseIdentifier":"c:@E@AgoraVirtualBackgroundSourceType"}],"abstract":[{"type":"text","text":"The type of the custom background image. See AgoraVirtualBackgroundSourceType"},{"type":"text","text":" "},{"type":"text","text":"."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/backgroundSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundSourceType"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource\/backgroundsourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSourceType":{"role":"symbol","title":"AgoraVirtualBackgroundSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSourceType"}],"abstract":[{"type":"text","text":"The type of the custom background image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSourceType"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsourcetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"backgroundSourceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"backgroundSourceType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSourceType","preciseIdentifier":"c:@E@AgoraVirtualBackgroundSourceType","text":"AgoraVirtualBackgroundSourceType"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundSourceType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/title","value":"AgoraVirtualBackgroundSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1backgroundSourceType\/title","value":"backgroundSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1backgroundSourceType\/fragments","value":[{"kind":"identifier","text":"backgroundSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSourceType\/title","value":"AgoraVirtualBackgroundSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}