{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource\/color"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource\/color"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/color","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of the custom background image. The color of the custom background"},{"type":"text","text":" "},{"type":"text","text":"image. The format is a hexadecimal integer defined by RGB, without the #"},{"type":"text","text":" "},{"type":"text","text":"sign, such as 0xFFB6C1 for light pink. The default value is 0xFFFFFF, which"},{"type":"text","text":" "},{"type":"text","text":"signifies white. The value range is [0x000000, 0xffffff]. If the value is"},{"type":"text","text":" "},{"type":"text","text":"invalid, the SDK replaces the original background image with a white"},{"type":"text","text":" "},{"type":"text","text":"background image.This parameter takes effect only when the type of the custom"},{"type":"text","text":" "},{"type":"text","text":"background image is AgoraVirtualBackgroundColor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"color","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVirtualBackgroundSource(py)color","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"color"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource/color":{"role":"symbol","title":"color","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The type of the custom background image. The color of the custom background"},{"type":"text","text":" "},{"type":"text","text":"image. The format is a hexadecimal integer defined by RGB, without the #"},{"type":"text","text":" "},{"type":"text","text":"sign, such as 0xFFB6C1 for light pink. The default value is 0xFFFFFF, which"},{"type":"text","text":" "},{"type":"text","text":"signifies white. The value range is [0x000000, 0xffffff]. If the value is"},{"type":"text","text":" "},{"type":"text","text":"invalid, the SDK replaces the original background image with a white"},{"type":"text","text":" "},{"type":"text","text":"background image.This parameter takes effect only when the type of the custom"},{"type":"text","text":" "},{"type":"text","text":"background image is AgoraVirtualBackgroundColor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/color","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"color"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource\/color"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource":{"role":"symbol","title":"AgoraVirtualBackgroundSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"abstract":[{"type":"text","text":"The custom background image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"color"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"color"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1color\/title","value":"color"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1color\/fragments","value":[{"kind":"identifier","text":"color"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/title","value":"AgoraVirtualBackgroundSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}