{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource\/source"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource\/source"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/source","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The local absolute path of the custom background image. PNG and JPG formats"},{"type":"text","text":" "},{"type":"text","text":"are supported. If the path is invalid, the SDK replaces the original"},{"type":"text","text":" "},{"type":"text","text":"background image with a white background image.This parameter takes effect"},{"type":"text","text":" "},{"type":"text","text":"only when the type of the custom background image is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVirtualBackgroundImg."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"source","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraVirtualBackgroundSource(py)source","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"source"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource":{"role":"symbol","title":"AgoraVirtualBackgroundSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"abstract":[{"type":"text","text":"The custom background image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The local absolute path of the custom background image. PNG and JPG formats"},{"type":"text","text":" "},{"type":"text","text":"are supported. If the path is invalid, the SDK replaces the original"},{"type":"text","text":" "},{"type":"text","text":"background image with a white background image.This parameter takes effect"},{"type":"text","text":" "},{"type":"text","text":"only when the type of the custom background image is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVirtualBackgroundImg."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/source","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"source"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource\/source"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"source"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"source"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"source"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/title","value":"AgoraVirtualBackgroundSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1source\/title","value":"source"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1source\/fragments","value":[{"kind":"identifier","text":"source"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}