{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheDir"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"< 0: Failure. See AgoraMediaPlayerError ."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayercachemanagerprotocol\/cachedir()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayercachemanagerprotocol\/cachedir()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCacheManagerProtocol\/cacheDir()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the storage path of the cached media files."},{"type":"text","text":" "},{"type":"text","text":"If you have not called the setCacheDir method to set the storage path for the"},{"type":"text","text":" "},{"type":"text","text":"media files to be cached before calling this method, you get the default"},{"type":"text","text":" "},{"type":"text","text":"storage path used by the SDK."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cacheDir"}],"role":"symbol","title":"cacheDir()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheDir"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerCacheManagerProtocol(im)cacheDir","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCacheManagerProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerCacheManagerProtocol/cacheDir()":{"navigatorTitle":[{"kind":"identifier","text":"cacheDir"}],"role":"symbol","title":"cacheDir()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheDir"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Gets the storage path of the cached media files."},{"type":"text","text":" "},{"type":"text","text":"If you have not called the setCacheDir method to set the storage path for the"},{"type":"text","text":" "},{"type":"text","text":"media files to be cached before calling this method, you get the default"},{"type":"text","text":" "},{"type":"text","text":"storage path used by the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCacheManagerProtocol\/cacheDir()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayercachemanagerprotocol\/cachedir()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerCacheManagerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerCacheManagerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol"}],"abstract":[{"type":"text","text":"This class provides methods to manage cached media files."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCacheManagerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayercachemanagerprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cacheDir"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheDir"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"cacheDir"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCacheManagerProtocol~1cacheDir()\/title","value":"cacheDir"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCacheManagerProtocol~1cacheDir()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheDir"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCacheManagerProtocol\/title","value":"AgoraRtcMediaPlayerCacheManagerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCacheManagerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCacheManagerProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}