{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionFailed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/connectionfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/connectionfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/connectionFailed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: The SDK connection fails. You can use reason reported in the connectionChangedToState callback to troubleshoot the failure."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionFailed"}],"title":"AgoraClientRoleChangeFailedReason.connectionFailed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraClientRoleChangeFailedReason@AgoraClientRoleChangeFailedConnectionFailed","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedConnectionFailed"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/connectionFailed":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason.connectionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionFailed"}],"abstract":[{"type":"text","text":"4: The SDK connection fails. You can use reason reported in the connectionChangedToState callback to troubleshoot the failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/connectionFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedConnectionFailed"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/connectionfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"abstract":[{"type":"text","text":"The reason for a user role switch failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraClientRoleChangeFailedConnectionFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedConnectionFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedConnectionFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1connectionFailed\/title","value":"AgoraClientRoleChangeFailedConnectionFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1connectionFailed\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedConnectionFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/title","value":"AgoraClientRoleChangeFailedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}