{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/notauthorized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/notauthorized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/notAuthorized","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The request is rejected by the Agora server. Agora recommends you prompt"},{"type":"text","text":" "},{"type":"text","text":"the user to try to switch their user role again."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"title":"AgoraClientRoleChangeFailedReason.notAuthorized","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraClientRoleChangeFailedReason@AgoraClientRoleChangeFailedNotAuthorized","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedNotAuthorized"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/notAuthorized":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason.notAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"abstract":[{"type":"text","text":"2: The request is rejected by the Agora server. Agora recommends you prompt"},{"type":"text","text":" "},{"type":"text","text":"the user to try to switch their user role again."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/notAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedNotAuthorized"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/notauthorized"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"abstract":[{"type":"text","text":"The reason for a user role switch failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraClientRoleChangeFailedNotAuthorized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedNotAuthorized"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedNotAuthorized"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1notAuthorized\/title","value":"AgoraClientRoleChangeFailedNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1notAuthorized\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/title","value":"AgoraClientRoleChangeFailedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}