{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooManyBroadcasters"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/toomanybroadcasters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/toomanybroadcasters"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/tooManyBroadcasters","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: The number of hosts in the channel is already at the upper limit.This enumerator is reported only when the support for 128 users is enabled. The maximum number of hosts is based on the actual number of hosts configured when you enable the 128-user feature."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooManyBroadcasters"}],"title":"AgoraClientRoleChangeFailedReason.tooManyBroadcasters","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraClientRoleChangeFailedReason@AgoraClientRoleChangeFailedTooManyBroadcasters","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedTooManyBroadcasters"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/tooManyBroadcasters":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason.tooManyBroadcasters","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooManyBroadcasters"}],"abstract":[{"type":"text","text":"1: The number of hosts in the channel is already at the upper limit.This enumerator is reported only when the support for 128 users is enabled. The maximum number of hosts is based on the actual number of hosts configured when you enable the 128-user feature."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/tooManyBroadcasters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedTooManyBroadcasters"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/toomanybroadcasters"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"abstract":[{"type":"text","text":"The reason for a user role switch failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraClientRoleChangeFailedTooManyBroadcasters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedTooManyBroadcasters"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedTooManyBroadcasters"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1tooManyBroadcasters\/title","value":"AgoraClientRoleChangeFailedTooManyBroadcasters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1tooManyBroadcasters\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedTooManyBroadcasters"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/title","value":"AgoraClientRoleChangeFailedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}