{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strengthLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracolorenhanceoptions\/strengthlevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracolorenhanceoptions\/strengthlevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/strengthLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The level of color enhancement. The value range is [0.0, 1.0]. 0.0 is the"},{"type":"text","text":" "},{"type":"text","text":"default value, which means no color enhancement is applied to the video. The"},{"type":"text","text":" "},{"type":"text","text":"higher the value, the higher the level of color enhancement. The default"},{"type":"text","text":" "},{"type":"text","text":"value is 0.5."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strengthLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"strengthLevel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraColorEnhanceOptions(py)strengthLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"strengthLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraColorEnhanceOptions":{"role":"symbol","title":"AgoraColorEnhanceOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraColorEnhanceOptions"}],"abstract":[{"type":"text","text":"The color enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraColorEnhanceOptions"}],"url":"\/documentation\/agorartckit\/agoracolorenhanceoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraColorEnhanceOptions/strengthLevel":{"role":"symbol","title":"strengthLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strengthLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The level of color enhancement. The value range is [0.0, 1.0]. 0.0 is the"},{"type":"text","text":" "},{"type":"text","text":"default value, which means no color enhancement is applied to the video. The"},{"type":"text","text":" "},{"type":"text","text":"higher the value, the higher the level of color enhancement. The default"},{"type":"text","text":" "},{"type":"text","text":"value is 0.5."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/strengthLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"strengthLevel"}],"url":"\/documentation\/agorartckit\/agoracolorenhanceoptions\/strengthlevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"strengthLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"strengthLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"strengthLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions\/title","value":"AgoraColorEnhanceOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions\/fragments","value":[{"kind":"identifier","text":"AgoraColorEnhanceOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions~1strengthLevel\/title","value":"strengthLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions~1strengthLevel\/fragments","value":[{"kind":"identifier","text":"strengthLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}