{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToSendMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atTimestamp"},{"kind":"text","text":" "},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The timestamp."}]}]},{"name":"sourceType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Video data type. See AgoraVideoSourceType ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The metadata that you want to send in the format of NSData, which"},{"type":"text","text":" "},{"type":"text","text":"includes the following parameters: uid : The ID of the remote user who sends"},{"type":"text","text":" "},{"type":"text","text":"the metadata. size : The size of the metadata. buffer : The metadata data."},{"type":"text","text":" "},{"type":"text","text":"timeStampMs : The NTP timestamp (ms) when the metadata is sent."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediametadatadatasource\/readytosendmetadata(attimestamp:sourcetype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediametadatadatasource\/readytosendmetadata(attimestamp:sourcetype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/readyToSendMetadata(atTimestamp:sourceType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the SDK is ready to send metadata."},{"type":"text","text":" "},{"type":"text","text":"This callback is triggered when the SDK is ready to send metadata.Ensure that"},{"type":"text","text":" "},{"type":"text","text":"the size of the metadata does not exceed the value set in the metadataMaxSize"},{"type":"text","text":" "},{"type":"text","text":"callback."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"readyToSendMetadataAtTimestamp:sourceType:"}],"role":"symbol","title":"readyToSendMetadata(atTimestamp:sourceType:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToSendMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraMediaMetadataDataSource(im)readyToSendMetadataAtTimestamp:sourceType:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType":{"role":"symbol","title":"AgoraVideoSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSourceType"}],"abstract":[{"type":"text","text":"The capture type of the custom video source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaMetadataDataSource/readyToSendMetadata(atTimestamp:sourceType:)":{"navigatorTitle":[{"kind":"identifier","text":"readyToSendMetadataAtTimestamp:sourceType:"}],"role":"symbol","title":"readyToSendMetadata(atTimestamp:sourceType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToSendMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Occurs when the SDK is ready to send metadata."},{"type":"text","text":" "},{"type":"text","text":"This callback is triggered when the SDK is ready to send metadata.Ensure that"},{"type":"text","text":" "},{"type":"text","text":"the size of the metadata does not exceed the value set in the metadataMaxSize"},{"type":"text","text":" "},{"type":"text","text":"callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/readyToSendMetadata(atTimestamp:sourceType:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramediametadatadatasource\/readytosendmetadata(attimestamp:sourcetype:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaMetadataDataSource":{"role":"symbol","title":"AgoraMediaMetadataDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}],"abstract":[{"type":"text","text":"AgoraMediaMetadataDataSource protocol."},{"type":"text","text":" "},{"type":"text","text":"Implement all the callbacks in this class in the critical thread. We"},{"type":"text","text":" "},{"type":"text","text":"recommend avoiding any time-consuming operation in the critical thread."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}],"url":"\/documentation\/agorartckit\/agoramediametadatadatasource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"readyToSendMetadataAtTimestamp:sourceType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readyToSendMetadataAtTimestamp:sourceType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"readyToSendMetadataAtTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sourceType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/title","value":"AgoraVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource~1readyToSendMetadata(atTimestamp:sourceType:)\/title","value":"readyToSendMetadataAtTimestamp:sourceType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource~1readyToSendMetadata(atTimestamp:sourceType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readyToSendMetadataAtTimestamp:sourceType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource\/title","value":"AgoraMediaMetadataDataSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource\/fragments","value":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}