{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/idle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/idle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/idle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The initial state before the CDN streaming starts."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"title":"AgoraDirectCdnStreamingState.idle","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraDirectCdnStreamingState@AgoraDirectCdnStreamingStateIdle","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateIdle"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/idle":{"role":"symbol","title":"AgoraDirectCdnStreamingState.idle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"abstract":[{"type":"text","text":"0: The initial state before the CDN streaming starts."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/idle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateIdle"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/idle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState":{"role":"symbol","title":"AgoraDirectCdnStreamingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"abstract":[{"type":"text","text":"The current CDN streaming state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDirectCdnStreamingStateIdle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateIdle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateIdle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1idle\/title","value":"AgoraDirectCdnStreamingStateIdle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1idle\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateIdle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState\/title","value":"AgoraDirectCdnStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}