{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralighteningcontrastlevel\/normal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralighteningcontrastlevel\/normal"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/normal","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: (Default) Normal contrast level."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"title":"AgoraLighteningContrastLevel.normal","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLighteningContrastLevel@AgoraLighteningContrastNormal","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastNormal"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel":{"role":"symbol","title":"AgoraLighteningContrastLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"abstract":[{"type":"text","text":"The contrast level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel/normal":{"role":"symbol","title":"AgoraLighteningContrastLevel.normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"abstract":[{"type":"text","text":"1: (Default) Normal contrast level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/normal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastNormal"}],"url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel\/normal"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLighteningContrastNormal"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastNormal"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLighteningContrastNormal"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel\/title","value":"AgoraLighteningContrastLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1normal\/title","value":"AgoraLighteningContrastNormal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1normal\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastNormal"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}