{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideodenoisermode\/auto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideodenoisermode\/auto"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/auto","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: (Default) Automatic mode. The SDK automatically enables or disables the video noise reduction feature according to the ambient light."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"title":"AgoraVideoDenoiserMode.auto","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoDenoiserMode@AgoraVideoDenoiserModeAuto","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserModeAuto"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode":{"role":"symbol","title":"AgoraVideoDenoiserMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"abstract":[{"type":"text","text":"Video noise reduction mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"url":"\/documentation\/agorartckit\/agoravideodenoisermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode/auto":{"role":"symbol","title":"AgoraVideoDenoiserMode.auto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"abstract":[{"type":"text","text":"0: (Default) Automatic mode. The SDK automatically enables or disables the video noise reduction feature according to the ambient light."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/auto","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserModeAuto"}],"url":"\/documentation\/agorartckit\/agoravideodenoisermode\/auto"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoDenoiserModeAuto"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserModeAuto"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoDenoiserModeAuto"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode\/title","value":"AgoraVideoDenoiserMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1auto\/title","value":"AgoraVideoDenoiserModeAuto"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1auto\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserModeAuto"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}