{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideodenoisermode\/manual"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideodenoisermode\/manual"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/manual","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Manual mode. Users need to enable or disable the video noise reduction"},{"type":"text","text":" "},{"type":"text","text":"feature manually."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}],"title":"AgoraVideoDenoiserMode.manual","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoDenoiserMode@AgoraVideoDenoiserModeManual","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserModeManual"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode/manual":{"role":"symbol","title":"AgoraVideoDenoiserMode.manual","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}],"abstract":[{"type":"text","text":"1: Manual mode. Users need to enable or disable the video noise reduction"},{"type":"text","text":" "},{"type":"text","text":"feature manually."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/manual","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserModeManual"}],"url":"\/documentation\/agorartckit\/agoravideodenoisermode\/manual"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode":{"role":"symbol","title":"AgoraVideoDenoiserMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"abstract":[{"type":"text","text":"Video noise reduction mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"url":"\/documentation\/agorartckit\/agoravideodenoisermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoDenoiserModeManual"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserModeManual"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoDenoiserModeManual"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1manual\/title","value":"AgoraVideoDenoiserModeManual"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1manual\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserModeManual"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode\/title","value":"AgoraVideoDenoiserMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}