{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downBandwidth"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoqualityadaptindication\/downbandwidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoqualityadaptindication\/downbandwidth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/downBandwidth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The local video quality deteriorates because the network bandwidth"},{"type":"text","text":" "},{"type":"text","text":"decreases."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downBandwidth"}],"title":"AgoraVideoQualityAdaptIndication.downBandwidth","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoQualityAdaptIndication@AgoraVideoQualityAdaptDownBandwidth","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptDownBandwidth"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"abstract":[{"type":"text","text":"Quality change of the local video in terms of target frame rate and target"},{"type":"text","text":" "},{"type":"text","text":"bit rate since last count."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/downBandwidth":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication.downBandwidth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downBandwidth"}],"abstract":[{"type":"text","text":"2: The local video quality deteriorates because the network bandwidth"},{"type":"text","text":" "},{"type":"text","text":"decreases."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/downBandwidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptDownBandwidth"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/downbandwidth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoQualityAdaptDownBandwidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptDownBandwidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoQualityAdaptDownBandwidth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/title","value":"AgoraVideoQualityAdaptIndication"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1downBandwidth\/title","value":"AgoraVideoQualityAdaptDownBandwidth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1downBandwidth\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptDownBandwidth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}