{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upBandwidth"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoqualityadaptindication\/upbandwidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoqualityadaptindication\/upbandwidth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/upBandwidth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: The local video quality improves because the network bandwidth increases."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upBandwidth"}],"title":"AgoraVideoQualityAdaptIndication.upBandwidth","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoQualityAdaptIndication@AgoraVideoQualityAdaptUpBandwidth","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptUpBandwidth"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"abstract":[{"type":"text","text":"Quality change of the local video in terms of target frame rate and target bit rate since last count."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/upBandwidth":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication.upBandwidth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upBandwidth"}],"abstract":[{"type":"text","text":"1: The local video quality improves because the network bandwidth increases."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/upBandwidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptUpBandwidth"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/upbandwidth"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoQualityAdaptUpBandwidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptUpBandwidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoQualityAdaptUpBandwidth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/title","value":"AgoraVideoQualityAdaptIndication"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1upBandwidth\/title","value":"AgoraVideoQualityAdaptUpBandwidth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1upBandwidth\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptUpBandwidth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}