{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestActionModifySSID"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorawlaccaction\/suggestactionmodifyssid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorawlaccaction\/suggestactionmodifyssid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionModifySSID","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestActionModifySSID"}],"title":"AgoraWlAccAction.suggestActionModifySSID","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraWlAccAction@AgoraWlAccSuggestActionModifySSID","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccSuggestActionModifySSID"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction":{"role":"symbol","title":"AgoraWlAccAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWlAccAction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccAction"}],"url":"\/documentation\/agorartckit\/agorawlaccaction"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/suggestActionModifySSID":{"role":"symbol","title":"AgoraWlAccAction.suggestActionModifySSID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestActionModifySSID"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionModifySSID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccSuggestActionModifySSID"}],"url":"\/documentation\/agorartckit\/agorawlaccaction\/suggestactionmodifyssid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraWlAccSuggestActionModifySSID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccSuggestActionModifySSID"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraWlAccSuggestActionModifySSID"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction\/title","value":"AgoraWlAccAction"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccAction"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionModifySSID\/title","value":"AgoraWlAccSuggestActionModifySSID"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionModifySSID\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccSuggestActionModifySSID"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}