{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureBrightnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType","preciseIdentifier":"c:@E@AgoraCaptureBrightnessLevelType","text":"AgoraCaptureBrightnessLevelType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartclocalvideostats\/capturebrightnesslevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartclocalvideostats\/capturebrightnesslevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats\/captureBrightnessLevel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureBrightnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCaptureBrightnessLevelType","preciseIdentifier":"c:@E@AgoraCaptureBrightnessLevelType"}],"title":"captureBrightnessLevel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcLocalVideoStats(py)captureBrightnessLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"captureBrightnessLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"abstract":[{"type":"text","text":"The brightness level of the video image captured by the local camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalVideoStats":{"role":"symbol","title":"AgoraRtcLocalVideoStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}],"abstract":[{"type":"text","text":"The statistics of the local video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}],"url":"\/documentation\/agorartckit\/agorartclocalvideostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalVideoStats/captureBrightnessLevel":{"role":"symbol","title":"captureBrightnessLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureBrightnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCaptureBrightnessLevelType","preciseIdentifier":"c:@E@AgoraCaptureBrightnessLevelType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats\/captureBrightnessLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureBrightnessLevel"}],"url":"\/documentation\/agorartckit\/agorartclocalvideostats\/capturebrightnesslevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"captureBrightnessLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"captureBrightnessLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType","preciseIdentifier":"c:@E@AgoraCaptureBrightnessLevelType","text":"AgoraCaptureBrightnessLevelType"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureBrightnessLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/title","value":"AgoraCaptureBrightnessLevelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats\/title","value":"AgoraRtcLocalVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats~1captureBrightnessLevel\/title","value":"captureBrightnessLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats~1captureBrightnessLevel\/fragments","value":[{"kind":"identifier","text":"captureBrightnessLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}