{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hwEncoderAccelerating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating","preciseIdentifier":"c:@E@AgoraVideoHwEncoderAccelerating","text":"AgoraVideoHwEncoderAccelerating"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartclocalvideostats\/hwencoderaccelerating"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartclocalvideostats\/hwencoderaccelerating"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats\/hwEncoderAccelerating","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The local video encoding acceleration type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hwEncoderAccelerating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoHwEncoderAccelerating","preciseIdentifier":"c:@E@AgoraVideoHwEncoderAccelerating"}],"title":"hwEncoderAccelerating","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcLocalVideoStats(py)hwEncoderAccelerating","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"hwEncoderAccelerating"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalVideoStats":{"role":"symbol","title":"AgoraRtcLocalVideoStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}],"abstract":[{"type":"text","text":"The statistics of the local video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}],"url":"\/documentation\/agorartckit\/agorartclocalvideostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalVideoStats/hwEncoderAccelerating":{"role":"symbol","title":"hwEncoderAccelerating","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hwEncoderAccelerating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoHwEncoderAccelerating","preciseIdentifier":"c:@E@AgoraVideoHwEncoderAccelerating"}],"abstract":[{"type":"text","text":"The local video encoding acceleration type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats\/hwEncoderAccelerating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hwEncoderAccelerating"}],"url":"\/documentation\/agorartckit\/agorartclocalvideostats\/hwencoderaccelerating"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"abstract":[{"type":"text","text":"The local video encoding acceleration type."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hwEncoderAccelerating"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hwEncoderAccelerating"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating","preciseIdentifier":"c:@E@AgoraVideoHwEncoderAccelerating","text":"AgoraVideoHwEncoderAccelerating"},{"kind":"text","text":" "},{"kind":"identifier","text":"hwEncoderAccelerating"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats\/title","value":"AgoraRtcLocalVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats~1hwEncoderAccelerating\/title","value":"hwEncoderAccelerating"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats~1hwEncoderAccelerating\/fragments","value":[{"kind":"identifier","text":"hwEncoderAccelerating"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/title","value":"AgoraVideoHwEncoderAccelerating"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}