{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAdaptIndication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication","preciseIdentifier":"c:@E@AgoraVideoQualityAdaptIndication","text":"AgoraVideoQualityAdaptIndication"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartclocalvideostats\/qualityadaptindication"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartclocalvideostats\/qualityadaptindication"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats\/qualityAdaptIndication","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The quality adaptation of the local video stream in the reported interval (based on the target frame rate and target bitrate). See AgoraVideoQualityAdaptIndication."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAdaptIndication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoQualityAdaptIndication","preciseIdentifier":"c:@E@AgoraVideoQualityAdaptIndication"}],"title":"qualityAdaptIndication","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcLocalVideoStats(py)qualityAdaptIndication","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"qualityAdaptIndication"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalVideoStats/qualityAdaptIndication":{"role":"symbol","title":"qualityAdaptIndication","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAdaptIndication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoQualityAdaptIndication","preciseIdentifier":"c:@E@AgoraVideoQualityAdaptIndication"}],"abstract":[{"type":"text","text":"The quality adaptation of the local video stream in the reported interval (based on the target frame rate and target bitrate). See AgoraVideoQualityAdaptIndication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats\/qualityAdaptIndication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityAdaptIndication"}],"url":"\/documentation\/agorartckit\/agorartclocalvideostats\/qualityadaptindication"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"abstract":[{"type":"text","text":"Quality change of the local video in terms of target frame rate and target bit rate since last count."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalVideoStats":{"role":"symbol","title":"AgoraRtcLocalVideoStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}],"abstract":[{"type":"text","text":"The statistics of the local video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}],"url":"\/documentation\/agorartckit\/agorartclocalvideostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"qualityAdaptIndication"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"qualityAdaptIndication"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication","preciseIdentifier":"c:@E@AgoraVideoQualityAdaptIndication","text":"AgoraVideoQualityAdaptIndication"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAdaptIndication"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats~1qualityAdaptIndication\/title","value":"qualityAdaptIndication"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats~1qualityAdaptIndication\/fragments","value":[{"kind":"identifier","text":"qualityAdaptIndication"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/title","value":"AgoraVideoQualityAdaptIndication"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats\/title","value":"AgoraRtcLocalVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalVideoStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalVideoStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}