{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateUnKonw"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreencaptureframeratecapability\/rateunkonw"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreencaptureframeratecapability\/rateunkonw"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability\/rateUnKonw","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateUnKonw"}],"title":"AgoraScreenCaptureFrameRateCapability.rateUnKonw","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraScreenCaptureFrameRateCapability@AgoraScreenCaptureFrameRateUnKonw","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateUnKonw"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureFrameRateCapability/rateUnKonw":{"role":"symbol","title":"AgoraScreenCaptureFrameRateCapability.rateUnKonw","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateUnKonw"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability\/rateUnKonw","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateUnKonw"}],"url":"\/documentation\/agorartckit\/agorascreencaptureframeratecapability\/rateunkonw"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureFrameRateCapability":{"role":"symbol","title":"AgoraScreenCaptureFrameRateCapability","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}],"url":"\/documentation\/agorartckit\/agorascreencaptureframeratecapability"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraScreenCaptureFrameRateUnKonw"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateUnKonw"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateUnKonw"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability~1rateUnKonw\/title","value":"AgoraScreenCaptureFrameRateUnKonw"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability~1rateUnKonw\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateUnKonw"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability\/title","value":"AgoraScreenCaptureFrameRateCapability"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}