{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rate60FPS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreencaptureframeratecapability\/rate60fps"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreencaptureframeratecapability\/rate60fps"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability\/rate60FPS","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The device supports the frame rate of up to 60 fps."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rate60FPS"}],"title":"AgoraScreenCaptureFrameRateCapability.rate60FPS","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraScreenCaptureFrameRateCapability@AgoraScreenCaptureFrameRate60FPS","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRate60FPS"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureFrameRateCapability":{"role":"symbol","title":"AgoraScreenCaptureFrameRateCapability","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}],"abstract":[{"type":"text","text":"The highest frame rate supported by the screen sharing device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}],"url":"\/documentation\/agorartckit\/agorascreencaptureframeratecapability"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureFrameRateCapability/rate60FPS":{"role":"symbol","title":"AgoraScreenCaptureFrameRateCapability.rate60FPS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rate60FPS"}],"abstract":[{"type":"text","text":"2: The device supports the frame rate of up to 60 fps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureFrameRateCapability\/rate60FPS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRate60FPS"}],"url":"\/documentation\/agorartckit\/agorascreencaptureframeratecapability\/rate60fps"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraScreenCaptureFrameRate60FPS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRate60FPS"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRate60FPS"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability\/title","value":"AgoraScreenCaptureFrameRateCapability"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRateCapability"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability~1rate60FPS\/title","value":"AgoraScreenCaptureFrameRate60FPS"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureFrameRateCapability~1rate60FPS\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureFrameRate60FPS"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}