{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraHigh"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingquality\/ultrahigh"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingquality\/ultrahigh"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingQuality\/ultraHigh","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: Ultra high quality. The sample rate is 32 kHz, and the file size is around 7.5 MB after 10 minutes of recording."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraHigh"}],"title":"AgoraAudioRecordingQuality.ultraHigh","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioRecordingQuality@AgoraAudioRecordingQualityUltraHigh","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingQualityUltraHigh"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingQuality"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingQuality/ultraHigh":{"role":"symbol","title":"AgoraAudioRecordingQuality.ultraHigh","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraHigh"}],"abstract":[{"type":"text","text":"3: Ultra high quality. The sample rate is 32 kHz, and the file size is around 7.5 MB after 10 minutes of recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingQuality\/ultraHigh","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingQualityUltraHigh"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingquality\/ultrahigh"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingQuality":{"role":"symbol","title":"AgoraAudioRecordingQuality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingQuality"}],"abstract":[{"type":"text","text":"Recording quality."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingQuality"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingquality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioRecordingQualityUltraHigh"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingQualityUltraHigh"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioRecordingQualityUltraHigh"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingQuality~1ultraHigh\/title","value":"AgoraAudioRecordingQualityUltraHigh"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingQuality~1ultraHigh\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingQualityUltraHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingQuality\/title","value":"AgoraAudioRecordingQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingQuality\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}