{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"highest"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorathreadprioritytype\/highest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorathreadprioritytype\/highest"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/highest","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"highest"}],"title":"AgoraThreadPriorityType.highest","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraThreadPriorityType@AgoraThreadPriorityTypeHighest","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHighest"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/highest":{"role":"symbol","title":"AgoraThreadPriorityType.highest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"highest"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/highest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHighest"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/highest"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType":{"role":"symbol","title":"AgoraThreadPriorityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraThreadPriorityType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityType"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraThreadPriorityTypeHighest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHighest"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHighest"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1highest\/title","value":"AgoraThreadPriorityTypeHighest"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1highest\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHighest"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/title","value":"AgoraThreadPriorityType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}