{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorathreadprioritytype\/normal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorathreadprioritytype\/normal"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/normal","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"title":"AgoraThreadPriorityType.normal","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraThreadPriorityType@AgoraThreadPriorityTypeNormal","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeNormal"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType":{"role":"symbol","title":"AgoraThreadPriorityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraThreadPriorityType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityType"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/normal":{"role":"symbol","title":"AgoraThreadPriorityType.normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/normal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeNormal"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/normal"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraThreadPriorityTypeNormal"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeNormal"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraThreadPriorityTypeNormal"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/title","value":"AgoraThreadPriorityType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1normal\/title","value":"AgoraThreadPriorityTypeNormal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1normal\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeNormal"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}