{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMuted"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoremotereason\/localmuted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoremotereason\/localmuted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localMuted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The local user stops receiving the remote video stream or disables the"},{"type":"text","text":" "},{"type":"text","text":"video module."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMuted"}],"title":"AgoraVideoRemoteReason.localMuted","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoRemoteReason@AgoraVideoRemoteReasonLocalMuted","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalMuted"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/localMuted":{"role":"symbol","title":"AgoraVideoRemoteReason.localMuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMuted"}],"abstract":[{"type":"text","text":"3: The local user stops receiving the remote video stream or disables the"},{"type":"text","text":" "},{"type":"text","text":"video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalMuted"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/localmuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason":{"role":"symbol","title":"AgoraVideoRemoteReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteReason"}],"abstract":[{"type":"text","text":"The reason for the remote video state change."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReason"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoRemoteReasonLocalMuted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalMuted"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalMuted"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1localMuted\/title","value":"AgoraVideoRemoteReasonLocalMuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1localMuted\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason\/title","value":"AgoraVideoRemoteReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}