{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetSingingBeautifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetsingingbeautifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetsingingbeautifier"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetSingingBeautifier","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Singing beautifier effect.If you call setVoiceBeautifierPreset(AgoraVoiceBeautifierPresetSingingBeautifier), you can beautify a male-sounding voice and add a reverberation effect that sounds like singing in a small room. Agora recommends using this enumerator to process a male-sounding voice; otherwise, you might experience vocal distortion.If you call setVoiceBeautifierParameters(AgoraVoiceBeautifierPresetSingingBeautifier, param1, param2), you can beautify a male or female-sounding voice and add a reverberation effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetSingingBeautifier"}],"title":"AgoraVoiceBeautifierPreset.presetSingingBeautifier","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVoiceBeautifierPreset@AgoraVoiceBeautifierPresetSingingBeautifier","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetSingingBeautifier"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/presetSingingBeautifier":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.presetSingingBeautifier","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetSingingBeautifier"}],"abstract":[{"type":"text","text":"Singing beautifier effect.If you call setVoiceBeautifierPreset(AgoraVoiceBeautifierPresetSingingBeautifier), you can beautify a male-sounding voice and add a reverberation effect that sounds like singing in a small room. Agora recommends using this enumerator to process a male-sounding voice; otherwise, you might experience vocal distortion.If you call setVoiceBeautifierParameters(AgoraVoiceBeautifierPresetSingingBeautifier, param1, param2), you can beautify a male or female-sounding voice and add a reverberation effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetSingingBeautifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetSingingBeautifier"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetsingingbeautifier"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset":{"role":"symbol","title":"AgoraVoiceBeautifierPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVoiceBeautifierPresetSingingBeautifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetSingingBeautifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetSingingBeautifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetSingingBeautifier\/title","value":"AgoraVoiceBeautifierPresetSingingBeautifier"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetSingingBeautifier\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetSingingBeautifier"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}