{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationMellow"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationmellow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationmellow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationMellow","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A mellower voice."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationMellow"}],"title":"AgoraVoiceBeautifierPreset.timbreTransformationMellow","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVoiceBeautifierPreset@AgoraVoiceBeautifierTimbreTransformationMellow","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationMellow"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationMellow":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationMellow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationMellow"}],"abstract":[{"type":"text","text":"A mellower voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationMellow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationMellow"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationmellow"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset":{"role":"symbol","title":"AgoraVoiceBeautifierPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVoiceBeautifierTimbreTransformationMellow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationMellow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationMellow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationMellow\/title","value":"AgoraVoiceBeautifierTimbreTransformationMellow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationMellow\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationMellow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}