{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationClear"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationclear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationclear"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationClear","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A clearer voice."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationClear"}],"title":"AgoraVoiceBeautifierPreset.timbreTransformationClear","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVoiceBeautifierPreset@AgoraVoiceBeautifierTimbreTransformationClear","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationClear"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationClear":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationClear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationClear"}],"abstract":[{"type":"text","text":"A clearer voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationClear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationClear"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationclear"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset":{"role":"symbol","title":"AgoraVoiceBeautifierPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVoiceBeautifierTimbreTransformationClear"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationClear"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationClear"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationClear\/title","value":"AgoraVoiceBeautifierTimbreTransformationClear"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationClear\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationClear"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}