{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraHighQuality"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/ultrahighquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset\/ultrahighquality"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/ultraHighQuality","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A ultra-high quality voice, which makes the audio clearer and restores more details.To achieve better audio effect quality, Agora recommends that you set the profile of setAudioProfile [2\/2] to AgoraAudioProfileMusicHighQuality(4) or AgoraAudioProfileMusicHighQualityStereo(5) and scenario to AgoraAudioScenarioGameStreaming(3) before calling setVoiceBeautifierPreset.If you have an audio capturing device that can already restore audio details to a high degree, Agora recommends that you do not enable ultra-high quality; otherwise, the SDK may over-restore audio details, and you may not hear the anticipated voice effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraHighQuality"}],"title":"AgoraVoiceBeautifierPreset.ultraHighQuality","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVoiceBeautifierPreset@AgoraVoiceBeautifierUltraHighQuality","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierUltraHighQuality"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/ultraHighQuality":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.ultraHighQuality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraHighQuality"}],"abstract":[{"type":"text","text":"A ultra-high quality voice, which makes the audio clearer and restores more details.To achieve better audio effect quality, Agora recommends that you set the profile of setAudioProfile [2\/2] to AgoraAudioProfileMusicHighQuality(4) or AgoraAudioProfileMusicHighQualityStereo(5) and scenario to AgoraAudioScenarioGameStreaming(3) before calling setVoiceBeautifierPreset.If you have an audio capturing device that can already restore audio details to a high degree, Agora recommends that you do not enable ultra-high quality; otherwise, the SDK may over-restore audio details, and you may not hear the anticipated voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/ultraHighQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierUltraHighQuality"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/ultrahighquality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset":{"role":"symbol","title":"AgoraVoiceBeautifierPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVoiceBeautifierUltraHighQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierUltraHighQuality"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVoiceBeautifierUltraHighQuality"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1ultraHighQuality\/title","value":"AgoraVoiceBeautifierUltraHighQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1ultraHighQuality\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierUltraHighQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}