{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericJpeg"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideocodectype\/genericjpeg"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideocodectype\/genericjpeg"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecType\/genericJpeg","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericJpeg"}],"title":"AgoraVideoCodecType.genericJpeg","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoCodecType@AgoraVideoCodecTypeGenericJpeg","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoCodecTypeGenericJpeg"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoCodecType/genericJpeg":{"role":"symbol","title":"AgoraVideoCodecType.genericJpeg","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericJpeg"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecType\/genericJpeg","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoCodecTypeGenericJpeg"}],"url":"\/documentation\/agorartckit\/agoravideocodectype\/genericjpeg"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoCodecType":{"role":"symbol","title":"AgoraVideoCodecType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoCodecType"}],"abstract":[{"type":"text","text":"Video codec types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoCodecType"}],"url":"\/documentation\/agorartckit\/agoravideocodectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoCodecTypeGenericJpeg"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoCodecTypeGenericJpeg"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoCodecTypeGenericJpeg"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecType~1genericJpeg\/title","value":"AgoraVideoCodecTypeGenericJpeg"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecType~1genericJpeg\/fragments","value":[{"kind":"identifier","text":"AgoraVideoCodecTypeGenericJpeg"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecType\/title","value":"AgoraVideoCodecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoCodecType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}