{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSimulcastStream"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorasimulcaststreammode\/autosimulcaststream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorasimulcaststreammode\/autosimulcaststream"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode\/autoSimulcastStream","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"-1: By default, the low-quality video steam is not sent; the SDK automatically switches to low-quality video stream mode after it receives a request to subscribe to a low-quality video stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSimulcastStream"}],"title":"AgoraSimulcastStreamMode.autoSimulcastStream","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraSimulcastStreamMode@AgoraAutoSimulcastStream","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAutoSimulcastStream"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode":{"role":"symbol","title":"AgoraSimulcastStreamMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"abstract":[{"type":"text","text":"The mode in which the video stream is sent."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode/autoSimulcastStream":{"role":"symbol","title":"AgoraSimulcastStreamMode.autoSimulcastStream","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSimulcastStream"}],"abstract":[{"type":"text","text":"-1: By default, the low-quality video steam is not sent; the SDK automatically switches to low-quality video stream mode after it receives a request to subscribe to a low-quality video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode\/autoSimulcastStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAutoSimulcastStream"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode\/autosimulcaststream"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAutoSimulcastStream"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAutoSimulcastStream"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAutoSimulcastStream"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/title","value":"AgoraSimulcastStreamMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode~1autoSimulcastStream\/title","value":"AgoraAutoSimulcastStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode~1autoSimulcastStream\/fragments","value":[{"kind":"identifier","text":"AgoraAutoSimulcastStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}