{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableSimulcastStream"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorasimulcaststreammode\/disablesimulcaststream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorasimulcaststreammode\/disablesimulcaststream"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode\/disableSimulcastStream","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: Never send low-quality video stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableSimulcastStream"}],"title":"AgoraSimulcastStreamMode.disableSimulcastStream","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraSimulcastStreamMode@AgoraDisableSimulcastStream","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDisableSimulcastStream"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode":{"role":"symbol","title":"AgoraSimulcastStreamMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"abstract":[{"type":"text","text":"The mode in which the video stream is sent."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode/disableSimulcastStream":{"role":"symbol","title":"AgoraSimulcastStreamMode.disableSimulcastStream","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableSimulcastStream"}],"abstract":[{"type":"text","text":"0: Never send low-quality video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode\/disableSimulcastStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDisableSimulcastStream"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode\/disablesimulcaststream"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDisableSimulcastStream"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDisableSimulcastStream"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraDisableSimulcastStream"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/title","value":"AgoraSimulcastStreamMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode~1disableSimulcastStream\/title","value":"AgoraDisableSimulcastStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode~1disableSimulcastStream\/fragments","value":[{"kind":"identifier","text":"AgoraDisableSimulcastStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}