{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSimulcastStream"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorasimulcaststreammode\/enablesimulcaststream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorasimulcaststreammode\/enablesimulcaststream"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode\/enableSimulcastStream","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Always send low-quality video stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSimulcastStream"}],"title":"AgoraSimulcastStreamMode.enableSimulcastStream","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraSimulcastStreamMode@AgoraEnableSimulcastStream","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEnableSimulcastStream"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode":{"role":"symbol","title":"AgoraSimulcastStreamMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"abstract":[{"type":"text","text":"The mode in which the video stream is sent."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSimulcastStreamMode/enableSimulcastStream":{"role":"symbol","title":"AgoraSimulcastStreamMode.enableSimulcastStream","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableSimulcastStream"}],"abstract":[{"type":"text","text":"1: Always send low-quality video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSimulcastStreamMode\/enableSimulcastStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEnableSimulcastStream"}],"url":"\/documentation\/agorartckit\/agorasimulcaststreammode\/enablesimulcaststream"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEnableSimulcastStream"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEnableSimulcastStream"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraEnableSimulcastStream"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/title","value":"AgoraSimulcastStreamMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode\/fragments","value":[{"kind":"identifier","text":"AgoraSimulcastStreamMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode~1enableSimulcastStream\/title","value":"AgoraEnableSimulcastStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSimulcastStreamMode~1enableSimulcastStream\/fragments","value":[{"kind":"identifier","text":"AgoraEnableSimulcastStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}