{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"musicStandard"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioprofile\/musicstandard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioprofile\/musicstandard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile\/musicStandard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: A sample rate of 48 kHz, music encoding, mono, and a bitrate of up to 64"},{"type":"text","text":" "},{"type":"text","text":"Kbps."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"musicStandard"}],"title":"AgoraAudioProfile.musicStandard","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioProfile@AgoraAudioProfileMusicStandard","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProfileMusicStandard"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProfile/musicStandard":{"role":"symbol","title":"AgoraAudioProfile.musicStandard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"musicStandard"}],"abstract":[{"type":"text","text":"2: A sample rate of 48 kHz, music encoding, mono, and a bitrate of up to 64"},{"type":"text","text":" "},{"type":"text","text":"Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile\/musicStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProfileMusicStandard"}],"url":"\/documentation\/agorartckit\/agoraaudioprofile\/musicstandard"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProfile":{"role":"symbol","title":"AgoraAudioProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProfile"}],"abstract":[{"type":"text","text":"The audio profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProfile"}],"url":"\/documentation\/agorartckit\/agoraaudioprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioProfileMusicStandard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProfileMusicStandard"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioProfileMusicStandard"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile~1musicStandard\/title","value":"AgoraAudioProfileMusicStandard"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile~1musicStandard\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProfileMusicStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile\/title","value":"AgoraAudioProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}