{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speechStandard"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioprofile\/speechstandard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioprofile\/speechstandard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile\/speechStandard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: A sample rate of 32 kHz, audio encoding, mono, and a bitrate of up to 18"},{"type":"text","text":" "},{"type":"text","text":"Kbps."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speechStandard"}],"title":"AgoraAudioProfile.speechStandard","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioProfile@AgoraAudioProfileSpeechStandard","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProfileSpeechStandard"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProfile/speechStandard":{"role":"symbol","title":"AgoraAudioProfile.speechStandard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speechStandard"}],"abstract":[{"type":"text","text":"1: A sample rate of 32 kHz, audio encoding, mono, and a bitrate of up to 18"},{"type":"text","text":" "},{"type":"text","text":"Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile\/speechStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProfileSpeechStandard"}],"url":"\/documentation\/agorartckit\/agoraaudioprofile\/speechstandard"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProfile":{"role":"symbol","title":"AgoraAudioProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProfile"}],"abstract":[{"type":"text","text":"The audio profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProfile"}],"url":"\/documentation\/agorartckit\/agoraaudioprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioProfileSpeechStandard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProfileSpeechStandard"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioProfileSpeechStandard"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile~1speechStandard\/title","value":"AgoraAudioProfileSpeechStandard"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile~1speechStandard\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProfileSpeechStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile\/title","value":"AgoraAudioProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProfile\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}