{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOnly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreamfallbackoptions\/audioonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreamfallbackoptions\/audioonly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/audioOnly","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOnly"}],"title":"AgoraStreamFallbackOptions.audioOnly","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraStreamFallbackOptions@AgoraStreamFallbackOptionAudioOnly","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptionAudioOnly"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/audioOnly":{"role":"symbol","title":"AgoraStreamFallbackOptions.audioOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOnly"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/audioOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptionAudioOnly"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/audioonly"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions":{"role":"symbol","title":"AgoraStreamFallbackOptions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamFallbackOptionAudioOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptionAudioOnly"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraStreamFallbackOptionAudioOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1audioOnly\/title","value":"AgoraStreamFallbackOptionAudioOnly"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1audioOnly\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptionAudioOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions\/title","value":"AgoraStreamFallbackOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}