{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoStreamLow"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreamfallbackoptions\/videostreamlow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreamfallbackoptions\/videostreamlow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/videoStreamLow","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoStreamLow"}],"title":"AgoraStreamFallbackOptions.videoStreamLow","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraStreamFallbackOptions@AgoraStreamFallbackOptionVideoStreamLow","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptionVideoStreamLow"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions":{"role":"symbol","title":"AgoraStreamFallbackOptions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/videoStreamLow":{"role":"symbol","title":"AgoraStreamFallbackOptions.videoStreamLow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoStreamLow"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/videoStreamLow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptionVideoStreamLow"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/videostreamlow"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamFallbackOptionVideoStreamLow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptionVideoStreamLow"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraStreamFallbackOptionVideoStreamLow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions\/title","value":"AgoraStreamFallbackOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1videoStreamLow\/title","value":"AgoraStreamFallbackOptionVideoStreamLow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1videoStreamLow\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptionVideoStreamLow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}