{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatRoom"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioscenario\/chatroom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioscenario\/chatroom"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chatRoom","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"5: Chatroom scenario, where users need to frequently switch the user role or mute and unmute the microphone. For example, education scenarios. In this scenario, audience members receive a pop-up window to request permission of using microphones."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatRoom"}],"title":"AgoraAudioScenario.chatRoom","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioScenario@AgoraAudioScenarioChatRoom","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioChatRoom"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/chatRoom":{"role":"symbol","title":"AgoraAudioScenario.chatRoom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatRoom"}],"abstract":[{"type":"text","text":"5: Chatroom scenario, where users need to frequently switch the user role or mute and unmute the microphone. For example, education scenarios. In this scenario, audience members receive a pop-up window to request permission of using microphones."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chatRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioChatRoom"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/chatroom"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario":{"role":"symbol","title":"AgoraAudioScenario","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioScenario"}],"abstract":[{"type":"text","text":"The audio scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenario"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioScenarioChatRoom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioChatRoom"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioScenarioChatRoom"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chatRoom\/title","value":"AgoraAudioScenarioChatRoom"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chatRoom\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioChatRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/title","value":"AgoraAudioScenario"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenario"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}