{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chorus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioscenario\/chorus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioscenario\/chorus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chorus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"7: Real-time chorus scenario, where users have good network conditions and"},{"type":"text","text":" "},{"type":"text","text":"require ultra-low latency."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chorus"}],"title":"AgoraAudioScenario.chorus","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioScenario@AgoraAudioScenarioChorus","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioChorus"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/chorus":{"role":"symbol","title":"AgoraAudioScenario.chorus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chorus"}],"abstract":[{"type":"text","text":"7: Real-time chorus scenario, where users have good network conditions and"},{"type":"text","text":" "},{"type":"text","text":"require ultra-low latency."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chorus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioChorus"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/chorus"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario":{"role":"symbol","title":"AgoraAudioScenario","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioScenario"}],"abstract":[{"type":"text","text":"The audio scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenario"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioScenarioChorus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioChorus"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioScenarioChorus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chorus\/title","value":"AgoraAudioScenarioChorus"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chorus\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioChorus"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/title","value":"AgoraAudioScenario"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenario"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}