{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"meeting"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioscenario\/meeting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioscenario\/meeting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/meeting","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"8: Meeting scenario that mainly contains the human voice."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"meeting"}],"title":"AgoraAudioScenario.meeting","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioScenario@AgoraAudioScenarioMeeting","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioMeeting"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/meeting":{"role":"symbol","title":"AgoraAudioScenario.meeting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"meeting"}],"abstract":[{"type":"text","text":"8: Meeting scenario that mainly contains the human voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/meeting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioMeeting"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/meeting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario":{"role":"symbol","title":"AgoraAudioScenario","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioScenario"}],"abstract":[{"type":"text","text":"The audio scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenario"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioScenarioMeeting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioMeeting"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioScenarioMeeting"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1meeting\/title","value":"AgoraAudioScenarioMeeting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1meeting\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioMeeting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/title","value":"AgoraAudioScenario"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenario"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}