{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEarMonitoringAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams","text":"AgoraAudioParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/getearmonitoringaudioparams()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/getearmonitoringaudioparams()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getEarMonitoringAudioParams()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getEarMonitoringAudioParams"}],"role":"symbol","title":"getEarMonitoringAudioParams()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEarMonitoringAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraAudioFrameDelegate(im)getEarMonitoringAudioParams","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate":{"role":"symbol","title":"AgoraAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"abstract":[{"type":"text","text":"The audio frame observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getEarMonitoringAudioParams()":{"navigatorTitle":[{"kind":"identifier","text":"getEarMonitoringAudioParams"}],"role":"symbol","title":"getEarMonitoringAudioParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEarMonitoringAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getEarMonitoringAudioParams()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getearmonitoringaudioparams()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioParams":{"role":"symbol","title":"AgoraAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioParams"}],"abstract":[{"type":"text","text":"Audio data format."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioParams"}],"url":"\/documentation\/agorartckit\/agoraaudioparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getEarMonitoringAudioParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getEarMonitoringAudioParams"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams","text":"AgoraAudioParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getEarMonitoringAudioParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getEarMonitoringAudioParams()\/title","value":"getEarMonitoringAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getEarMonitoringAudioParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getEarMonitoringAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams\/title","value":"AgoraAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraAudioParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}