{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMixedAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams","text":"AgoraAudioParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/getmixedaudioparams()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/getmixedaudioparams()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getMixedAudioParams()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMixedAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"title":"getMixedAudioParams()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraAudioFrameDelegate(im)getMixedAudioParams","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"getMixedAudioParams"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate":{"role":"symbol","title":"AgoraAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"abstract":[{"type":"text","text":"The audio frame observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getMixedAudioParams()":{"role":"symbol","title":"getMixedAudioParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMixedAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getMixedAudioParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMixedAudioParams"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getmixedaudioparams()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioParams":{"role":"symbol","title":"AgoraAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioParams"}],"abstract":[{"type":"text","text":"Audio data format."},{"type":"text","text":" "},{"type":"text","text":"You can pass the AgoraAudioParams object in the return value of the following"},{"type":"text","text":" "},{"type":"text","text":"callbacksto set the audio data format for the corresponding callback:"},{"type":"text","text":" "},{"type":"text","text":"getRecordAudioParams : Sets the audio data format for the onRecordAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callback. getPlaybackAudioParams : Sets the audio data format for the"},{"type":"text","text":" "},{"type":"text","text":"onPlaybackAudioFrame callback. getMixedAudioParams : Sets the audio data"},{"type":"text","text":" "},{"type":"text","text":"format for the onMixedAudioFrame callback. getEarMonitoringAudioParams : Sets"},{"type":"text","text":" "},{"type":"text","text":"the audio data format for the onEarMonitoringAudioFrame callback.The SDK"},{"type":"text","text":" "},{"type":"text","text":"calculates the sampling interval through the samplesPerCall, sampleRate, and"},{"type":"text","text":" "},{"type":"text","text":"channel parameters in AgoraAudioParams, and triggers the onRecordAudioFrame,"},{"type":"text","text":" "},{"type":"text","text":"onPlaybackAudioFrame, onMixedAudioFrame, and onEarMonitoringAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callbacks according to the sampling interval.Sample interval (sec) ="},{"type":"text","text":" "},{"type":"text","text":"samplePerCall\/(sampleRate × channel).Ensure that the sample interval ≥ 0.01"},{"type":"text","text":" "},{"type":"text","text":"(s)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioParams"}],"url":"\/documentation\/agorartckit\/agoraaudioparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getMixedAudioParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMixedAudioParams"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams","text":"AgoraAudioParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getMixedAudioParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getMixedAudioParams()\/title","value":"getMixedAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getMixedAudioParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMixedAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams\/title","value":"AgoraAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraAudioParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}