{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObservedAudioFramePosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition","text":"AgoraAudioFramePosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/getobservedaudioframeposition()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/getobservedaudioframeposition()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getObservedAudioFramePosition()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getObservedAudioFramePosition"}],"role":"symbol","title":"getObservedAudioFramePosition()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObservedAudioFramePosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraAudioFrameDelegate(im)getObservedAudioFramePosition","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getObservedAudioFramePosition()":{"navigatorTitle":[{"kind":"identifier","text":"getObservedAudioFramePosition"}],"role":"symbol","title":"getObservedAudioFramePosition()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObservedAudioFramePosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getObservedAudioFramePosition()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getobservedaudioframeposition()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate":{"role":"symbol","title":"AgoraAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"abstract":[{"type":"text","text":"The audio frame observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition":{"role":"symbol","title":"AgoraAudioFramePosition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePosition"}],"url":"\/documentation\/agorartckit\/agoraaudioframeposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getObservedAudioFramePosition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getObservedAudioFramePosition"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition","text":"AgoraAudioFramePosition"},{"kind":"text","text":") "},{"kind":"identifier","text":"getObservedAudioFramePosition"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getObservedAudioFramePosition()\/title","value":"getObservedAudioFramePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getObservedAudioFramePosition()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getObservedAudioFramePosition"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition\/title","value":"AgoraAudioFramePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}