{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEarMonitoringAudioFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/onearmonitoringaudioframe(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/onearmonitoringaudioframe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onEarMonitoringAudioFrame(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEarMonitoringAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"onEarMonitoringAudioFrame(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraAudioFrameDelegate(im)onEarMonitoringAudioFrame:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"onEarMonitoringAudioFrame:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate":{"role":"symbol","title":"AgoraAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"abstract":[{"type":"text","text":"The audio frame observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrame":{"role":"symbol","title":"AgoraAudioFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrame"}],"abstract":[{"type":"text","text":"Raw audio data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrame"}],"url":"\/documentation\/agorartckit\/agoraaudioframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onEarMonitoringAudioFrame(_:)":{"role":"symbol","title":"onEarMonitoringAudioFrame(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEarMonitoringAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onEarMonitoringAudioFrame(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onEarMonitoringAudioFrame:"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onearmonitoringaudioframe(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onEarMonitoringAudioFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEarMonitoringAudioFrame:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onEarMonitoringAudioFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/title","value":"AgoraAudioFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onEarMonitoringAudioFrame(_:)\/title","value":"onEarMonitoringAudioFrame:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onEarMonitoringAudioFrame(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEarMonitoringAudioFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}