{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMixedAudioFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The raw audio data. See AgoraAudioFrame ."}]}]},{"name":"channelId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel ID."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Reserved for future use."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/onmixedaudioframe(_:channelid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/onmixedaudioframe(_:channelid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onMixedAudioFrame(_:channelId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the raw audio frame for playback."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the data format of audio frame for playback is as expected,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you choose one of the following two methods to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format:Method 1: After calling"},{"type":"text","text":" "},{"type":"text","text":"setPlaybackAudioFrameParametersWithSampleRate to set the audio data format"},{"type":"text","text":" "},{"type":"text","text":"and setAudioFrameDelegate to register the audio frame observer object, the"},{"type":"text","text":" "},{"type":"text","text":"SDK calculates the sampling interval according to the parameters set in the"},{"type":"text","text":" "},{"type":"text","text":"methods, and triggers the onPlaybackAudioFrame callback according to the"},{"type":"text","text":" "},{"type":"text","text":"sampling interval.Method 2: After calling setAudioFrameDelegate to register"},{"type":"text","text":" "},{"type":"text","text":"the audio frame observer object, set the audio data format in the return"},{"type":"text","text":" "},{"type":"text","text":"value of the getObservedAudioFramePosition callback. The SDK then calculates"},{"type":"text","text":" "},{"type":"text","text":"the sampling interval according to the return value of the"},{"type":"text","text":" "},{"type":"text","text":"getPlaybackAudioParams callback, and triggers the onPlaybackAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callback according to the sampling interval.The priority of method 1 is"},{"type":"text","text":" "},{"type":"text","text":"higher than that of method 2. If method 1 is used to set the audio data"},{"type":"text","text":" "},{"type":"text","text":"format, the setting of method 2 is invalid."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onMixedAudioFrame:channelId:"}],"role":"symbol","title":"onMixedAudioFrame(_:channelId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMixedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraAudioFrameDelegate(im)onMixedAudioFrame:channelId:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onMixedAudioFrame(_:channelId:)":{"navigatorTitle":[{"kind":"identifier","text":"onMixedAudioFrame:channelId:"}],"role":"symbol","title":"onMixedAudioFrame(_:channelId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMixedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the raw audio frame for playback."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the data format of audio frame for playback is as expected,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you choose one of the following two methods to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format:Method 1: After calling"},{"type":"text","text":" "},{"type":"text","text":"setPlaybackAudioFrameParametersWithSampleRate to set the audio data format"},{"type":"text","text":" "},{"type":"text","text":"and setAudioFrameDelegate to register the audio frame observer object, the"},{"type":"text","text":" "},{"type":"text","text":"SDK calculates the sampling interval according to the parameters set in the"},{"type":"text","text":" "},{"type":"text","text":"methods, and triggers the onPlaybackAudioFrame callback according to the"},{"type":"text","text":" "},{"type":"text","text":"sampling interval.Method 2: After calling setAudioFrameDelegate to register"},{"type":"text","text":" "},{"type":"text","text":"the audio frame observer object, set the audio data format in the return"},{"type":"text","text":" "},{"type":"text","text":"value of the getObservedAudioFramePosition callback. The SDK then calculates"},{"type":"text","text":" "},{"type":"text","text":"the sampling interval according to the return value of the"},{"type":"text","text":" "},{"type":"text","text":"getPlaybackAudioParams callback, and triggers the onPlaybackAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callback according to the sampling interval.The priority of method 1 is"},{"type":"text","text":" "},{"type":"text","text":"higher than that of method 2. If method 1 is used to set the audio data"},{"type":"text","text":" "},{"type":"text","text":"format, the setting of method 2 is invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onMixedAudioFrame(_:channelId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onmixedaudioframe(_:channelid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate":{"role":"symbol","title":"AgoraAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"abstract":[{"type":"text","text":"The audio frame observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrame":{"role":"symbol","title":"AgoraAudioFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrame"}],"abstract":[{"type":"text","text":"Raw audio data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrame"}],"url":"\/documentation\/agorartckit\/agoraaudioframe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onMixedAudioFrame:channelId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMixedAudioFrame:channelId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMixedAudioFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onMixedAudioFrame(_:channelId:)\/title","value":"onMixedAudioFrame:channelId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onMixedAudioFrame(_:channelId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMixedAudioFrame:channelId:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/title","value":"AgoraAudioFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrame"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}