{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackAudioFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/onplaybackaudioframe(_:channelid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate\/onplaybackaudioframe(_:channelid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(_:channelId:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPlaybackAudioFrame:channelId:"}],"role":"symbol","title":"onPlaybackAudioFrame(_:channelId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraAudioFrameDelegate(im)onPlaybackAudioFrame:channelId:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrame":{"role":"symbol","title":"AgoraAudioFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrame"}],"abstract":[{"type":"text","text":"Raw audio data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrame"}],"url":"\/documentation\/agorartckit\/agoraaudioframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate":{"role":"symbol","title":"AgoraAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"abstract":[{"type":"text","text":"The audio frame observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onPlaybackAudioFrame(_:channelId:)":{"navigatorTitle":[{"kind":"identifier","text":"onPlaybackAudioFrame:channelId:"}],"role":"symbol","title":"onPlaybackAudioFrame(_:channelId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(_:channelId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onplaybackaudioframe(_:channelid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onPlaybackAudioFrame:channelId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackAudioFrame:channelId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPlaybackAudioFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame","text":"AgoraAudioFrame"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/title","value":"AgoraAudioFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrame\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onPlaybackAudioFrame(_:channelId:)\/title","value":"onPlaybackAudioFrame:channelId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onPlaybackAudioFrame(_:channelId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackAudioFrame:channelId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}