{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturing"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideolocalstate\/capturing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideolocalstate\/capturing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState\/capturing","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: The local video capturing device starts successfully."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturing"}],"title":"AgoraVideoLocalState.capturing","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoLocalState@AgoraVideoLocalStateCapturing","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoLocalStateCapturing"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoLocalState":{"role":"symbol","title":"AgoraVideoLocalState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoLocalState"}],"abstract":[{"type":"text","text":"Local video state types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoLocalState"}],"url":"\/documentation\/agorartckit\/agoravideolocalstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoLocalState/capturing":{"role":"symbol","title":"AgoraVideoLocalState.capturing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturing"}],"abstract":[{"type":"text","text":"1: The local video capturing device starts successfully."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState\/capturing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoLocalStateCapturing"}],"url":"\/documentation\/agorartckit\/agoravideolocalstate\/capturing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoLocalStateCapturing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoLocalStateCapturing"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoLocalStateCapturing"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState\/title","value":"AgoraVideoLocalState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState\/fragments","value":[{"kind":"identifier","text":"AgoraVideoLocalState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState~1capturing\/title","value":"AgoraVideoLocalStateCapturing"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState~1capturing\/fragments","value":[{"kind":"identifier","text":"AgoraVideoLocalStateCapturing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}