{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideolocalstate\/encoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideolocalstate\/encoding"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState\/encoding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The first video frame is successfully encoded."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"}],"title":"AgoraVideoLocalState.encoding","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoLocalState@AgoraVideoLocalStateEncoding","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoLocalStateEncoding"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoLocalState/encoding":{"role":"symbol","title":"AgoraVideoLocalState.encoding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"}],"abstract":[{"type":"text","text":"2: The first video frame is successfully encoded."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState\/encoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoLocalStateEncoding"}],"url":"\/documentation\/agorartckit\/agoravideolocalstate\/encoding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoLocalState":{"role":"symbol","title":"AgoraVideoLocalState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoLocalState"}],"abstract":[{"type":"text","text":"Local video state types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoLocalState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoLocalState"}],"url":"\/documentation\/agorartckit\/agoravideolocalstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoLocalStateEncoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoLocalStateEncoding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoLocalStateEncoding"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState~1encoding\/title","value":"AgoraVideoLocalStateEncoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState~1encoding\/fragments","value":[{"kind":"identifier","text":"AgoraVideoLocalStateEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState\/title","value":"AgoraVideoLocalState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoLocalState\/fragments","value":[{"kind":"identifier","text":"AgoraVideoLocalState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}