{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lighteningContrastLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel","preciseIdentifier":"c:@E@AgoraLighteningContrastLevel","text":"AgoraLighteningContrastLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabeautyoptions\/lighteningcontrastlevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabeautyoptions\/lighteningcontrastlevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningContrastLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The contrast level, used with the lighteningLevel parameter. The larger the"},{"type":"text","text":" "},{"type":"text","text":"value, the greater the contrast between light and dark. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLighteningContrastLevel ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lighteningContrastLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLighteningContrastLevel","preciseIdentifier":"c:@E@AgoraLighteningContrastLevel"}],"title":"lighteningContrastLevel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraBeautyOptions(py)lighteningContrastLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"lighteningContrastLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel":{"role":"symbol","title":"AgoraLighteningContrastLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"abstract":[{"type":"text","text":"The contrast level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions":{"role":"symbol","title":"AgoraBeautyOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBeautyOptions"}],"abstract":[{"type":"text","text":"Image enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBeautyOptions"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions/lighteningContrastLevel":{"role":"symbol","title":"lighteningContrastLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lighteningContrastLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLighteningContrastLevel","preciseIdentifier":"c:@E@AgoraLighteningContrastLevel"}],"abstract":[{"type":"text","text":"The contrast level, used with the lighteningLevel parameter. The larger the"},{"type":"text","text":" "},{"type":"text","text":"value, the greater the contrast between light and dark. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLighteningContrastLevel ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningContrastLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lighteningContrastLevel"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions\/lighteningcontrastlevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lighteningContrastLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"lighteningContrastLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel","preciseIdentifier":"c:@E@AgoraLighteningContrastLevel","text":"AgoraLighteningContrastLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"lighteningContrastLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel\/title","value":"AgoraLighteningContrastLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions\/title","value":"AgoraBeautyOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions\/fragments","value":[{"kind":"identifier","text":"AgoraBeautyOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1lighteningContrastLevel\/title","value":"lighteningContrastLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1lighteningContrastLevel\/fragments","value":[{"kind":"identifier","text":"lighteningContrastLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}