{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabeautyoptions\/sharpnesslevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabeautyoptions\/sharpnesslevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/sharpnessLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The sharpness level, in the range [0.0,1.0], where 0.0 means the original"},{"type":"text","text":" "},{"type":"text","text":"sharpness. The default value is 0.1"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"sharpnessLevel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraBeautyOptions(py)sharpnessLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"sharpnessLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions/sharpnessLevel":{"role":"symbol","title":"sharpnessLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The sharpness level, in the range [0.0,1.0], where 0.0 means the original"},{"type":"text","text":" "},{"type":"text","text":"sharpness. The default value is 0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/sharpnessLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharpnessLevel"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions\/sharpnesslevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions":{"role":"symbol","title":"AgoraBeautyOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBeautyOptions"}],"abstract":[{"type":"text","text":"Image enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBeautyOptions"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sharpnessLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharpnessLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpnessLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1sharpnessLevel\/title","value":"sharpnessLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1sharpnessLevel\/fragments","value":[{"kind":"identifier","text":"sharpnessLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions\/title","value":"AgoraBeautyOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions\/fragments","value":[{"kind":"identifier","text":"AgoraBeautyOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}