{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncWithAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradatastreamconfig\/syncwithaudio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradatastreamconfig\/syncwithaudio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDataStreamConfig\/syncWithAudio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether to synchronize the data packet with the published audio packet.YES:"},{"type":"text","text":" "},{"type":"text","text":"Synchronize the data packet with the audio packet.NO: Do not synchronize the"},{"type":"text","text":" "},{"type":"text","text":"data packet with the audio packet.When you set the data packet to synchronize"},{"type":"text","text":" "},{"type":"text","text":"with the audio, then if the data packet delay is within the audio delay, the"},{"type":"text","text":" "},{"type":"text","text":"SDK triggers the receiveStreamMessageFromUid callback when the synchronized"},{"type":"text","text":" "},{"type":"text","text":"audio packet is played out. Do not set this parameter as YES if you need the"},{"type":"text","text":" "},{"type":"text","text":"receiver to receive the data packet immediately. Agora recommends that you"},{"type":"text","text":" "},{"type":"text","text":"set this parameter to true only when you need to implement specific"},{"type":"text","text":" "},{"type":"text","text":"functions, for example, lyric synchronization."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncWithAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"syncWithAudio","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraDataStreamConfig(py)syncWithAudio","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"syncWithAudio"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDataStreamConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDataStreamConfig/syncWithAudio":{"role":"symbol","title":"syncWithAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncWithAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to synchronize the data packet with the published audio packet.YES:"},{"type":"text","text":" "},{"type":"text","text":"Synchronize the data packet with the audio packet.NO: Do not synchronize the"},{"type":"text","text":" "},{"type":"text","text":"data packet with the audio packet.When you set the data packet to synchronize"},{"type":"text","text":" "},{"type":"text","text":"with the audio, then if the data packet delay is within the audio delay, the"},{"type":"text","text":" "},{"type":"text","text":"SDK triggers the receiveStreamMessageFromUid callback when the synchronized"},{"type":"text","text":" "},{"type":"text","text":"audio packet is played out. Do not set this parameter as YES if you need the"},{"type":"text","text":" "},{"type":"text","text":"receiver to receive the data packet immediately. Agora recommends that you"},{"type":"text","text":" "},{"type":"text","text":"set this parameter to true only when you need to implement specific"},{"type":"text","text":" "},{"type":"text","text":"functions, for example, lyric synchronization."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDataStreamConfig\/syncWithAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"syncWithAudio"}],"url":"\/documentation\/agorartckit\/agoradatastreamconfig\/syncwithaudio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDataStreamConfig":{"role":"symbol","title":"AgoraDataStreamConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDataStreamConfig"}],"abstract":[{"type":"text","text":"The configurations for the data stream."},{"type":"text","text":" "},{"type":"text","text":"The following table shows the SDK behaviors under different parameter"},{"type":"text","text":" "},{"type":"text","text":"settings:"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDataStreamConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDataStreamConfig"}],"url":"\/documentation\/agorartckit\/agoradatastreamconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"syncWithAudio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"syncWithAudio"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncWithAudio"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDataStreamConfig~1syncWithAudio\/title","value":"syncWithAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDataStreamConfig~1syncWithAudio\/fragments","value":[{"kind":"identifier","text":"syncWithAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDataStreamConfig\/title","value":"AgoraDataStreamConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDataStreamConfig\/fragments","value":[{"kind":"identifier","text":"AgoraDataStreamConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}