{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeStop"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediaplayerevent\/freezestop"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediaplayerevent\/freezestop"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStop","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"9: The audio or video playback resumes without freezing."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeStop"}],"title":"AgoraMediaPlayerEvent.freezeStop","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaPlayerEvent@AgoraMediaPlayerEventFreezeStop","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStop"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent":{"role":"symbol","title":"AgoraMediaPlayerEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"abstract":[{"type":"text","text":"Media player events."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/freezeStop":{"role":"symbol","title":"AgoraMediaPlayerEvent.freezeStop","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeStop"}],"abstract":[{"type":"text","text":"9: The audio or video playback resumes without freezing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStop","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStop"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/freezestop"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaPlayerEventFreezeStop"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStop"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStop"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/title","value":"AgoraMediaPlayerEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1freezeStop\/title","value":"AgoraMediaPlayerEventFreezeStop"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1freezeStop\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStop"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}