{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekBegin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediaplayerevent\/seekbegin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediaplayerevent\/seekbegin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekBegin","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The player begins to seek to a new playback position."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekBegin"}],"title":"AgoraMediaPlayerEvent.seekBegin","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaPlayerEvent@AgoraMediaPlayerEventSeekBegin","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekBegin"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent":{"role":"symbol","title":"AgoraMediaPlayerEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"abstract":[{"type":"text","text":"Media player events."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/seekBegin":{"role":"symbol","title":"AgoraMediaPlayerEvent.seekBegin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekBegin"}],"abstract":[{"type":"text","text":"0: The player begins to seek to a new playback position."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekBegin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekBegin"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/seekbegin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaPlayerEventSeekBegin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekBegin"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekBegin"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/title","value":"AgoraMediaPlayerEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekBegin\/title","value":"AgoraMediaPlayerEventSeekBegin"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekBegin\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekBegin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}