{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsourcetype\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsourcetype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSourceType\/none","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"AgoraVirtualBackgroundSourceType.none","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVirtualBackgroundSourceType@AgoraVirtualBackgroundNone","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundNone"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSourceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSourceType/none":{"role":"symbol","title":"AgoraVirtualBackgroundSourceType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSourceType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundNone"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsourcetype\/none"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSourceType":{"role":"symbol","title":"AgoraVirtualBackgroundSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSourceType"}],"abstract":[{"type":"text","text":"The type of the custom background image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSourceType"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsourcetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVirtualBackgroundNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundNone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVirtualBackgroundNone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSourceType~1none\/title","value":"AgoraVirtualBackgroundNone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSourceType~1none\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundNone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSourceType\/title","value":"AgoraVirtualBackgroundSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}