{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedInvalidToken"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedinvalidtoken"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedinvalidtoken"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidToken","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedInvalidToken"}],"title":"AgoraRtmClientConnectionChangeReason.changedInvalidToken","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmClientConnectionChangeReason@AgoraRtmClientConnectionChangedInvalidToken","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidToken"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedInvalidToken":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedInvalidToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedInvalidToken"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidToken"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedinvalidtoken"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmClientConnectionChangedInvalidToken"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidToken"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidToken"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/title","value":"AgoraRtmClientConnectionChangeReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidToken\/title","value":"AgoraRtmClientConnectionChangedInvalidToken"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidToken\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidToken"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}