{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedClientIpAddressChangedByUser"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedclientipaddresschangedbyuser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedclientipaddresschangedbyuser"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChangedByUser","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedClientIpAddressChangedByUser"}],"title":"AgoraRtmClientConnectionChangeReason.changedClientIpAddressChangedByUser","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmClientConnectionChangeReason@AgoraRtmClientConnectionChangedClientIpAddressChangedByUser","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedClientIpAddressChangedByUser":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedClientIpAddressChangedByUser","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedClientIpAddressChangedByUser"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChangedByUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedclientipaddresschangedbyuser"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/title","value":"AgoraRtmClientConnectionChangeReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedClientIpAddressChangedByUser\/title","value":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedClientIpAddressChangedByUser\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}