{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedTooManyBroadcasters"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedtoomanybroadcasters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedtoomanybroadcasters"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTooManyBroadcasters","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedTooManyBroadcasters"}],"title":"AgoraRtmClientConnectionChangeReason.changedTooManyBroadcasters","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmClientConnectionChangeReason@AgoraRtmClientConnectionChangedTooManyBroadcasters","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTooManyBroadcasters"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedTooManyBroadcasters":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedTooManyBroadcasters","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedTooManyBroadcasters"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTooManyBroadcasters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTooManyBroadcasters"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedtoomanybroadcasters"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmClientConnectionChangedTooManyBroadcasters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTooManyBroadcasters"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTooManyBroadcasters"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/title","value":"AgoraRtmClientConnectionChangeReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedTooManyBroadcasters\/title","value":"AgoraRtmClientConnectionChangedTooManyBroadcasters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedTooManyBroadcasters\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTooManyBroadcasters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}