{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradegradationpreference\/balanced"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradegradationpreference\/balanced"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/balanced","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Reduces the video frame rate and video resolution simultaneously during video encoding under limited bandwidth. The AgoraDegradationBalanced has a lower reduction than AgoraDegradationMaintainQuality and AgoraDegradationMaintainFramerate, and this preference is suitable for scenarios where both smoothness and video quality are a priority.The resolution of the video sent may change, so remote users need to handle this issue. See videoSizeChangedOfSourceType."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"title":"AgoraDegradationPreference.balanced","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraDegradationPreference@AgoraDegradationBalanced","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationBalanced"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference":{"role":"symbol","title":"AgoraDegradationPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"}],"abstract":[{"type":"text","text":"Video degradation preferences when the bandwidth is a constraint."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationPreference"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/balanced":{"role":"symbol","title":"AgoraDegradationPreference.balanced","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"abstract":[{"type":"text","text":"2: Reduces the video frame rate and video resolution simultaneously during video encoding under limited bandwidth. The AgoraDegradationBalanced has a lower reduction than AgoraDegradationMaintainQuality and AgoraDegradationMaintainFramerate, and this preference is suitable for scenarios where both smoothness and video quality are a priority.The resolution of the video sent may change, so remote users need to handle this issue. See videoSizeChangedOfSourceType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/balanced","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationBalanced"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference\/balanced"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDegradationBalanced"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationBalanced"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraDegradationBalanced"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/title","value":"AgoraDegradationPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1balanced\/title","value":"AgoraDegradationBalanced"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1balanced\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationBalanced"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}