{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainResolution"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradegradationpreference\/maintainresolution"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradegradationpreference\/maintainresolution"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainResolution","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: Reduces the video frame rate while maintaining the video resolution"},{"type":"text","text":" "},{"type":"text","text":"during video encoding under limited bandwidth. This degradation preference"},{"type":"text","text":" "},{"type":"text","text":"is suitable for scenarios where video quality is prioritized."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainResolution"}],"title":"AgoraDegradationPreference.maintainResolution","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraDegradationPreference@AgoraDegradationMaintainResolution","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationMaintainResolution"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference":{"role":"symbol","title":"AgoraDegradationPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"}],"abstract":[{"type":"text","text":"Video degradation preferences when the bandwidth is a constraint."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationPreference"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/maintainResolution":{"role":"symbol","title":"AgoraDegradationPreference.maintainResolution","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainResolution"}],"abstract":[{"type":"text","text":"3: Reduces the video frame rate while maintaining the video resolution"},{"type":"text","text":" "},{"type":"text","text":"during video encoding under limited bandwidth. This degradation preference"},{"type":"text","text":" "},{"type":"text","text":"is suitable for scenarios where video quality is prioritized."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationMaintainResolution"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference\/maintainresolution"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDegradationMaintainResolution"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationMaintainResolution"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraDegradationMaintainResolution"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/title","value":"AgoraDegradationPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainResolution\/title","value":"AgoraDegradationMaintainResolution"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainResolution\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationMaintainResolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}