{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainQuality"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradegradationpreference\/maintainquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradegradationpreference\/maintainquality"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainQuality","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: (Default) Prefers to reduce the video frame rate while maintaining video resolution during video encoding under limited bandwidth. This degradation preference is suitable for scenarios where video quality is prioritized."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainQuality"}],"title":"AgoraDegradationPreference.maintainQuality","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraDegradationPreference@AgoraDegradationMaintainQuality","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationMaintainQuality"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference":{"role":"symbol","title":"AgoraDegradationPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"}],"abstract":[{"type":"text","text":"Video degradation preferences when the bandwidth is a constraint."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationPreference"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/maintainQuality":{"role":"symbol","title":"AgoraDegradationPreference.maintainQuality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainQuality"}],"abstract":[{"type":"text","text":"0: (Default) Prefers to reduce the video frame rate while maintaining video resolution during video encoding under limited bandwidth. This degradation preference is suitable for scenarios where video quality is prioritized."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationMaintainQuality"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference\/maintainquality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDegradationMaintainQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationMaintainQuality"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraDegradationMaintainQuality"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/title","value":"AgoraDegradationPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainQuality\/title","value":"AgoraDegradationMaintainQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainQuality\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationMaintainQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}