{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioProcessingChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels","preciseIdentifier":"c:@E@AgoraAudioProcessChannels","text":"AgoraAudioProcessChannels"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraadvancedaudiooptions\/audioprocessingchannels"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraadvancedaudiooptions\/audioprocessingchannels"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedAudioOptions\/audioProcessingChannels","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The number of channels for audio preprocessing. See AgoraAudioProcessChannels"},{"type":"text","text":" "},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioProcessingChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioProcessChannels","preciseIdentifier":"c:@E@AgoraAudioProcessChannels"}],"title":"audioProcessingChannels","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraAdvancedAudioOptions(py)audioProcessingChannels","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"audioProcessingChannels"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedAudioOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAdvancedAudioOptions":{"role":"symbol","title":"AgoraAdvancedAudioOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAdvancedAudioOptions"}],"abstract":[{"type":"text","text":"The advanced options for audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedAudioOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAdvancedAudioOptions"}],"url":"\/documentation\/agorartckit\/agoraadvancedaudiooptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels":{"role":"symbol","title":"AgoraAudioProcessChannels","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"abstract":[{"type":"text","text":"The number of channels for audio preprocessing."},{"type":"text","text":" "},{"type":"text","text":"In scenarios that require enhanced realism, such as concerts, local users"},{"type":"text","text":" "},{"type":"text","text":"might need to capture stereo audio and send stereo signals to remote users."},{"type":"text","text":" "},{"type":"text","text":"For example, the singer, guitarist, and drummer are standing in different"},{"type":"text","text":" "},{"type":"text","text":"positions on the stage. The audio capture device captures their stereo audio"},{"type":"text","text":" "},{"type":"text","text":"and sends stereo signals to remote users. Remote users can hear the song,"},{"type":"text","text":" "},{"type":"text","text":"guitar, and drum from different directions as if they were at the"},{"type":"text","text":" "},{"type":"text","text":"auditorium.You can set the dual-channel processing to implement stereo audio"},{"type":"text","text":" "},{"type":"text","text":"in this class. Agora recommends the following settings:Preprocessing: call"},{"type":"text","text":" "},{"type":"text","text":"setAdvancedAudioOptions and set audioProcessingChannels to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAdvancedAudioOptions (2) in"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProcessChannelsStereo.Post-processing: call setAudioProfile [2\/2]"},{"type":"text","text":" "},{"type":"text","text":"profile to AgoraAudioProfileMusicStandardStereo (3) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo (5).The stereo setting only takes"},{"type":"text","text":" "},{"type":"text","text":"effect when the SDK uses the media volume.  On iOS, stereo audio requires"},{"type":"text","text":" "},{"type":"text","text":"high device performance. Stereo audio is only supported on the following"},{"type":"text","text":" "},{"type":"text","text":"devices using iOS 14.0 and later:iPhone XSiPhone XS MaxiPhone XRiPhone"},{"type":"text","text":" "},{"type":"text","text":"11iPhone 11 ProiPhone 11 Pro MaxiPhone SE (2020)iPad Pro 11” and 12.9” (3rd"},{"type":"text","text":" "},{"type":"text","text":"generation)iPad Pro 11” and 12.9” (4th generation)"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"url":"\/documentation\/agorartckit\/agoraaudioprocesschannels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAdvancedAudioOptions/audioProcessingChannels":{"role":"symbol","title":"audioProcessingChannels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioProcessingChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioProcessChannels","preciseIdentifier":"c:@E@AgoraAudioProcessChannels"}],"abstract":[{"type":"text","text":"The number of channels for audio preprocessing. See AgoraAudioProcessChannels"},{"type":"text","text":" "},{"type":"text","text":"."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedAudioOptions\/audioProcessingChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioProcessingChannels"}],"url":"\/documentation\/agorartckit\/agoraadvancedaudiooptions\/audioprocessingchannels"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audioProcessingChannels"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioProcessingChannels"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels","preciseIdentifier":"c:@E@AgoraAudioProcessChannels","text":"AgoraAudioProcessChannels"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioProcessingChannels"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedAudioOptions\/title","value":"AgoraAdvancedAudioOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedAudioOptions\/fragments","value":[{"kind":"identifier","text":"AgoraAdvancedAudioOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels\/title","value":"AgoraAudioProcessChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedAudioOptions~1audioProcessingChannels\/title","value":"audioProcessingChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedAudioOptions~1audioProcessingChannels\/fragments","value":[{"kind":"identifier","text":"audioProcessingChannels"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}