{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingerror\/ok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingerror\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingError\/OK","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: No error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"title":"AgoraDirectCdnStreamingError.OK","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraDirectCdnStreamingError@AgoraDirectCdnStreamingErrorOK","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingErrorOK"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingError/OK":{"role":"symbol","title":"AgoraDirectCdnStreamingError.OK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"abstract":[{"type":"text","text":"0: No error."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingError\/OK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingErrorOK"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingerror\/ok"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingError":{"role":"symbol","title":"AgoraDirectCdnStreamingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingError"}],"abstract":[{"type":"text","text":"The CDN streaming error."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingError"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDirectCdnStreamingErrorOK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingErrorOK"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraDirectCdnStreamingErrorOK"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingError~1OK\/title","value":"AgoraDirectCdnStreamingErrorOK"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingError~1OK\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingErrorOK"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingError\/title","value":"AgoraDirectCdnStreamingError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingError\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}