{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didVideoSubscribeStateChange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState","text":"AgoraStreamSubscribeState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState","text":"AgoraStreamSubscribeState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapseSinceLastState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"engine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AgoraRtcEngineKit object."}]}]},{"name":"channelId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel name."}]}]},{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID of the remote user."}]}]},{"name":"oldState","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The previous subscribing status, see"},{"type":"text","text":" "},{"type":"text","text":"AgoraStreamSubscribeState for details."}]}]},{"name":"newState","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current subscribing status, see"},{"type":"text","text":" "},{"type":"text","text":"AgoraStreamSubscribeState for details."}]}]},{"name":"elapseSinceLastState","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The time elapsed (ms) from the previous"},{"type":"text","text":" "},{"type":"text","text":"state to the current state."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:didvideosubscribestatechange:uid:oldstate:newstate:elapsesincelaststate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:didvideosubscribestatechange:uid:oldstate:newstate:elapsesincelaststate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2\/rtcEngine(_:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the audio subscribing state changes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didVideoSubscribeStateChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapseSinceLastState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"title":"rtcEngine(_:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate2(im)rtcEngine:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate2":{"role":"symbol","title":"AgoraRtcEngineDelegate2","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState":{"role":"symbol","title":"AgoraStreamSubscribeState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"abstract":[{"type":"text","text":"The subscribing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate2/rtcEngine(_:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:)":{"role":"symbol","title":"rtcEngine(_:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didVideoSubscribeStateChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapseSinceLastState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the audio subscribing state changes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2\/rtcEngine(_:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:didvideosubscribestatechange:uid:oldstate:newstate:elapsesincelaststate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"didVideoSubscribeStateChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"unsigned int","preciseIdentifier":"c:i"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"oldState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState","text":"AgoraStreamSubscribeState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"oldState"},{"kind":"text","text":" "},{"kind":"identifier","text":"newState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","preciseIdentifier":"c:@E@AgoraStreamSubscribeState","text":"AgoraStreamSubscribeState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"newState"},{"kind":"text","text":" "},{"kind":"identifier","text":"elapseSinceLastState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"internalParam","text":"elapseSinceLastState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/title","value":"AgoraRtcEngineDelegate2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/title","value":"AgoraStreamSubscribeState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2~1rtcEngine(_:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:)\/title","value":"rtcEngine:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2~1rtcEngine(_:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didVideoSubscribeStateChange:uid:oldState:newState:elapseSinceLastState:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}