{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localAudioStateChanged"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState","preciseIdentifier":"c:@E@AgoraAudioLocalState","text":"AgoraAudioLocalState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError","preciseIdentifier":"c:@E@AgoraAudioLocalError","text":"AgoraAudioLocalError"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"engine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AgoraRtcEngineKit object."}]}]},{"name":"state","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The state of the local audio. See AgoraAudioLocalState ."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Local audio state error codes. See AgoraAudioLocalError ."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:localaudiostatechanged:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:localaudiostatechanged:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2\/rtcEngine(_:localAudioStateChanged:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the local audio stream state changes."},{"type":"text","text":" "},{"type":"text","text":"When the state of the local audio stream changes (including the state of the"},{"type":"text","text":" "},{"type":"text","text":"audio capture and encoding), the SDK triggers this callback to report the"},{"type":"text","text":" "},{"type":"text","text":"current state. This callback indicates the state of the local audio stream,"},{"type":"text","text":" "},{"type":"text","text":"and allows you to troubleshoot issues when audio exceptions occur.When the"},{"type":"text","text":" "},{"type":"text","text":"state is AgoraAudioLocalStateFailed (3), you can view the error information"},{"type":"text","text":" "},{"type":"text","text":"in the error parameter."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:localAudioStateChanged:error:"}],"role":"symbol","title":"rtcEngine(_:localAudioStateChanged:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localAudioStateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioLocalState","preciseIdentifier":"c:@E@AgoraAudioLocalState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioLocalError","preciseIdentifier":"c:@E@AgoraAudioLocalError"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate2(im)rtcEngine:localAudioStateChanged:error:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalError":{"role":"symbol","title":"AgoraAudioLocalError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioLocalError"}],"abstract":[{"type":"text","text":"Local audio state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalError"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalState":{"role":"symbol","title":"AgoraAudioLocalState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioLocalState"}],"abstract":[{"type":"text","text":"The state of the local audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalState"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate2":{"role":"symbol","title":"AgoraRtcEngineDelegate2","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of"},{"type":"text","text":" "},{"type":"text","text":"real-time communication. AgoraRtcEngineKit provides the main methods that"},{"type":"text","text":" "},{"type":"text","text":"your app can call."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate2/rtcEngine(_:localAudioStateChanged:error:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:localAudioStateChanged:error:"}],"role":"symbol","title":"rtcEngine(_:localAudioStateChanged:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localAudioStateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioLocalState","preciseIdentifier":"c:@E@AgoraAudioLocalState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioLocalError","preciseIdentifier":"c:@E@AgoraAudioLocalError"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the local audio stream state changes."},{"type":"text","text":" "},{"type":"text","text":"When the state of the local audio stream changes (including the state of the"},{"type":"text","text":" "},{"type":"text","text":"audio capture and encoding), the SDK triggers this callback to report the"},{"type":"text","text":" "},{"type":"text","text":"current state. This callback indicates the state of the local audio stream,"},{"type":"text","text":" "},{"type":"text","text":"and allows you to troubleshoot issues when audio exceptions occur.When the"},{"type":"text","text":" "},{"type":"text","text":"state is AgoraAudioLocalStateFailed (3), you can view the error information"},{"type":"text","text":" "},{"type":"text","text":"in the error parameter."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2\/rtcEngine(_:localAudioStateChanged:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:localaudiostatechanged:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:localAudioStateChanged:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:localAudioStateChanged:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"localAudioStateChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState","preciseIdentifier":"c:@E@AgoraAudioLocalState","text":"AgoraAudioLocalState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError","preciseIdentifier":"c:@E@AgoraAudioLocalError","text":"AgoraAudioLocalError"},{"kind":"text","text":") "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError\/title","value":"AgoraAudioLocalError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState\/title","value":"AgoraAudioLocalState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/title","value":"AgoraRtcEngineDelegate2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2~1rtcEngine(_:localAudioStateChanged:error:)\/title","value":"rtcEngine:localAudioStateChanged:error:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2~1rtcEngine(_:localAudioStateChanged:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:localAudioStateChanged:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}