{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didVideoPublishStateChange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState","text":"AgoraStreamPublishState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState","text":"AgoraStreamPublishState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapseSinceLastState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:didvideopublishstatechange:sourcetype:oldstate:newstate:elapsesincelaststate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:didvideopublishstatechange:sourcetype:oldstate:newstate:elapsesincelaststate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2\/rtcEngine(_:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didVideoPublishStateChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapseSinceLastState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"title":"rtcEngine(_:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraRtcEngineDelegate2(im)rtcEngine:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType":{"role":"symbol","title":"AgoraVideoSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSourceType"}],"abstract":[{"type":"text","text":"The type of the video source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate2/rtcEngine(_:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:)":{"role":"symbol","title":"rtcEngine(_:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didVideoPublishStateChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapseSinceLastState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2\/rtcEngine(_:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate2\/rtcengine(_:didvideopublishstatechange:sourcetype:oldstate:newstate:elapsesincelaststate:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState":{"role":"symbol","title":"AgoraStreamPublishState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamPublishState"}],"abstract":[{"type":"text","text":"The publishing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishState"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate2":{"role":"symbol","title":"AgoraRtcEngineDelegate2","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate2"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"kind":"identifier","text":"didVideoPublishStateChange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"source"},{"kind":"text","text":" "},{"kind":"identifier","text":"oldState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState","text":"AgoraStreamPublishState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"oldState"},{"kind":"text","text":" "},{"kind":"identifier","text":"newState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","preciseIdentifier":"c:@E@AgoraStreamPublishState","text":"AgoraStreamPublishState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"newState"},{"kind":"text","text":" "},{"kind":"identifier","text":"elapseSinceLastState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"elapseSinceLastState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/title","value":"AgoraVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2~1rtcEngine(_:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:)\/title","value":"rtcEngine:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2~1rtcEngine(_:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didVideoPublishStateChange:sourceType:oldState:newState:elapseSinceLastState:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState\/title","value":"AgoraStreamPublishState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/title","value":"AgoraRtcEngineDelegate2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}