{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorapermissiontype\/camera"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorapermissiontype\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPermissionType\/camera","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Permission for the camera."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"}],"title":"AgoraPermissionType.camera","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraPermissionType@AgoraPermissionTypeCamera","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraPermissionTypeCamera"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPermissionType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPermissionType/camera":{"role":"symbol","title":"AgoraPermissionType.camera","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"}],"abstract":[{"type":"text","text":"1: Permission for the camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPermissionType\/camera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraPermissionTypeCamera"}],"url":"\/documentation\/agorartckit\/agorapermissiontype\/camera"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPermissionType":{"role":"symbol","title":"AgoraPermissionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraPermissionType"}],"abstract":[{"type":"text","text":"The type of the device permission."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPermissionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraPermissionType"}],"url":"\/documentation\/agorartckit\/agorapermissiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraPermissionTypeCamera"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraPermissionTypeCamera"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraPermissionTypeCamera"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPermissionType~1camera\/title","value":"AgoraPermissionTypeCamera"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPermissionType~1camera\/fragments","value":[{"kind":"identifier","text":"AgoraPermissionTypeCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPermissionType\/title","value":"AgoraPermissionType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPermissionType\/fragments","value":[{"kind":"identifier","text":"AgoraPermissionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}