{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"areaCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType","preciseIdentifier":"c:@E@AgoraAreaCodeType","text":"AgoraAreaCodeType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/areacode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/areacode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/areaCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The region for connection. This is an advanced feature and applies to"},{"type":"text","text":" "},{"type":"text","text":"scenarios that have regional restrictions.  The area codes support bitwise"},{"type":"text","text":" "},{"type":"text","text":"operation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"areaCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAreaCodeType","preciseIdentifier":"c:@E@AgoraAreaCodeType"}],"title":"areaCode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcEngineConfig(py)areaCode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"areaCode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig":{"role":"symbol","title":"AgoraRtcEngineConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"abstract":[{"type":"text","text":"Configurations for the AgoraRtcEngineConfig instance."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAreaCodeType":{"role":"symbol","title":"AgoraAreaCodeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAreaCodeType"}],"abstract":[{"type":"text","text":"The region for connection, which is the region where the server the SDK"},{"type":"text","text":" "},{"type":"text","text":"connects to is located."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAreaCodeType"}],"url":"\/documentation\/agorartckit\/agoraareacodetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig/areaCode":{"role":"symbol","title":"areaCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"areaCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAreaCodeType","preciseIdentifier":"c:@E@AgoraAreaCodeType"}],"abstract":[{"type":"text","text":"The region for connection. This is an advanced feature and applies to"},{"type":"text","text":" "},{"type":"text","text":"scenarios that have regional restrictions.  The area codes support bitwise"},{"type":"text","text":" "},{"type":"text","text":"operation."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/areaCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"areaCode"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig\/areacode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"areaCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"areaCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAreaCodeType","preciseIdentifier":"c:@E@AgoraAreaCodeType","text":"AgoraAreaCodeType"},{"kind":"text","text":" "},{"kind":"identifier","text":"areaCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/title","value":"AgoraRtcEngineConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/title","value":"AgoraAreaCodeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAreaCodeType\/fragments","value":[{"kind":"identifier","text":"AgoraAreaCodeType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1areaCode\/title","value":"areaCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1areaCode\/fragments","value":[{"kind":"identifier","text":"areaCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}