{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoRegisterAgoraExtensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/autoregisteragoraextensions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/autoregisteragoraextensions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/autoRegisterAgoraExtensions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether to automatically register the Agora extensions when initializing AgoraRtcEngineKit:YES: (Default) Automatically register the Agora extensions when initializing AgoraRtcEngineKit.NO: Do not register the Agora extensions when initializing AgoraRtcEngineKit. You need to call enableExtensionWithVendor to register the Agora extensions."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoRegisterAgoraExtensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"autoRegisterAgoraExtensions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcEngineConfig(py)autoRegisterAgoraExtensions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"autoRegisterAgoraExtensions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig":{"role":"symbol","title":"AgoraRtcEngineConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"abstract":[{"type":"text","text":"Configurations for the AgoraRtcEngineConfig instance."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig/autoRegisterAgoraExtensions":{"role":"symbol","title":"autoRegisterAgoraExtensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoRegisterAgoraExtensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically register the Agora extensions when initializing AgoraRtcEngineKit:YES: (Default) Automatically register the Agora extensions when initializing AgoraRtcEngineKit.NO: Do not register the Agora extensions when initializing AgoraRtcEngineKit. You need to call enableExtensionWithVendor to register the Agora extensions."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/autoRegisterAgoraExtensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoRegisterAgoraExtensions"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig\/autoregisteragoraextensions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"autoRegisterAgoraExtensions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"autoRegisterAgoraExtensions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoRegisterAgoraExtensions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/title","value":"AgoraRtcEngineConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1autoRegisterAgoraExtensions\/title","value":"autoRegisterAgoraExtensions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1autoRegisterAgoraExtensions\/fragments","value":[{"kind":"identifier","text":"autoRegisterAgoraExtensions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}