{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate","preciseIdentifier":"c:objc(pl)AgoraMediaFilterEventDelegate","text":"AgoraMediaFilterEventDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/eventdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/eventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/eventDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The AgoraMediaFilterEventDelegate instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaFilterEventDelegate","preciseIdentifier":"c:objc(pl)AgoraMediaFilterEventDelegate"},{"kind":"text","text":"?"}],"title":"eventDelegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcEngineConfig(py)eventDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"eventDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig/eventDelegate":{"role":"symbol","title":"eventDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaFilterEventDelegate","preciseIdentifier":"c:objc(pl)AgoraMediaFilterEventDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The AgoraMediaFilterEventDelegate instance."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/eventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"eventDelegate"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig\/eventdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig":{"role":"symbol","title":"AgoraRtcEngineConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"abstract":[{"type":"text","text":"Configurations for the AgoraRtcEngineConfig instance."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaFilterEventDelegate":{"role":"symbol","title":"AgoraMediaFilterEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}],"abstract":[{"type":"text","text":"Extension event callback interface class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}],"url":"\/documentation\/agorartckit\/agoramediafiltereventdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"eventDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"eventDelegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<AgoraMediaFilterEventDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraMediaFilterEventDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eventDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1eventDelegate\/title","value":"eventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1eventDelegate\/fragments","value":[{"kind":"identifier","text":"eventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/title","value":"AgoraRtcEngineConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate\/title","value":"AgoraMediaFilterEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}