{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig","preciseIdentifier":"c:objc(cs)AgoraLogConfig","text":"AgoraLogConfig"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/logconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/logconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/logConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The SDK log files are: agorasdk.log, agorasdk.1.log, agorasdk.2.log, agorasdk.3.log, and agorasdk.4.log."},{"type":"text","text":" "},{"type":"text","text":"The API call log files are: agoraapi.log, agoraapi.1.log, agoraapi.2.log, agoraapi.3.log, and agoraapi.4.log."},{"type":"text","text":" "},{"type":"text","text":"The default size for each SDK log file is 1,024 KB; the default size for each API call log file is 2,048 KB. These log files are encoded in UTF-8."},{"type":"text","text":" "},{"type":"text","text":"The SDK writes the latest logs in agorasdk.log or agoraapi.log."},{"type":"text","text":" "},{"type":"text","text":"When agorasdk.log is full, the SDK processes the log files in the following order:"},{"type":"text","text":" "},{"type":"text","text":"Delete the agorasdk.4.log file (if any)."},{"type":"text","text":" "},{"type":"text","text":"Rename agorasdk.3.log to agorasdk.4.log."},{"type":"text","text":" "},{"type":"text","text":"Rename agorasdk.2.log to agorasdk.3.log."},{"type":"text","text":" "},{"type":"text","text":"Rename agorasdk.1.log to agorasdk.2.log."},{"type":"text","text":" "},{"type":"text","text":"Create a new agorasdk.log file. The overwrite rules for the agoraapi.log file are the same as for agorasdk.log. Sets the log file size. See AgoraLogConfig.By default, the SDK generates five SDK log files and five API call log files with the following rules:"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLogConfig","preciseIdentifier":"c:objc(cs)AgoraLogConfig"},{"kind":"text","text":"?"}],"title":"logConfig","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcEngineConfig(py)logConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"logConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig":{"role":"symbol","title":"AgoraRtcEngineConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"abstract":[{"type":"text","text":"Configurations for the AgoraRtcEngineConfig instance."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig/logConfig":{"role":"symbol","title":"logConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLogConfig","preciseIdentifier":"c:objc(cs)AgoraLogConfig"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The SDK log files are: agorasdk.log, agorasdk.1.log, agorasdk.2.log, agorasdk.3.log, and agorasdk.4.log."},{"type":"text","text":" "},{"type":"text","text":"The API call log files are: agoraapi.log, agoraapi.1.log, agoraapi.2.log, agoraapi.3.log, and agoraapi.4.log."},{"type":"text","text":" "},{"type":"text","text":"The default size for each SDK log file is 1,024 KB; the default size for each API call log file is 2,048 KB. These log files are encoded in UTF-8."},{"type":"text","text":" "},{"type":"text","text":"The SDK writes the latest logs in agorasdk.log or agoraapi.log."},{"type":"text","text":" "},{"type":"text","text":"When agorasdk.log is full, the SDK processes the log files in the following order:"},{"type":"text","text":" "},{"type":"text","text":"Delete the agorasdk.4.log file (if any)."},{"type":"text","text":" "},{"type":"text","text":"Rename agorasdk.3.log to agorasdk.4.log."},{"type":"text","text":" "},{"type":"text","text":"Rename agorasdk.2.log to agorasdk.3.log."},{"type":"text","text":" "},{"type":"text","text":"Rename agorasdk.1.log to agorasdk.2.log."},{"type":"text","text":" "},{"type":"text","text":"Create a new agorasdk.log file. The overwrite rules for the agoraapi.log file are the same as for agorasdk.log. Sets the log file size. See AgoraLogConfig.By default, the SDK generates five SDK log files and five API call log files with the following rules:"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/logConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logConfig"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig\/logconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogConfig":{"role":"symbol","title":"AgoraLogConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogConfig"}],"abstract":[{"type":"text","text":"Configuration of Agora SDK log files."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogConfig"}],"url":"\/documentation\/agorartckit\/agoralogconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"logConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"logConfig"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig","preciseIdentifier":"c:objc(cs)AgoraLogConfig","text":"AgoraLogConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"logConfig"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/title","value":"AgoraRtcEngineConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1logConfig\/title","value":"logConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1logConfig\/fragments","value":[{"kind":"identifier","text":"logConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig\/title","value":"AgoraLogConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLogConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}