{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadPriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType","preciseIdentifier":"c:@E@AgoraThreadPriorityType","text":"AgoraThreadPriorityType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/threadpriority"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcengineconfig\/threadpriority"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/threadPriority","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadPriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraThreadPriorityType","preciseIdentifier":"c:@E@AgoraThreadPriorityType"}],"title":"threadPriority","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtcEngineConfig(py)threadPriority","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"threadPriority"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig":{"role":"symbol","title":"AgoraRtcEngineConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"abstract":[{"type":"text","text":"Configurations for the AgoraRtcEngineConfig instance."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineConfig/threadPriority":{"role":"symbol","title":"threadPriority","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadPriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraThreadPriorityType","preciseIdentifier":"c:@E@AgoraThreadPriorityType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineConfig\/threadPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"threadPriority"}],"url":"\/documentation\/agorartckit\/agorartcengineconfig\/threadpriority"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType":{"role":"symbol","title":"AgoraThreadPriorityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraThreadPriorityType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityType"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"threadPriority"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"threadPriority"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType","preciseIdentifier":"c:@E@AgoraThreadPriorityType","text":"AgoraThreadPriorityType"},{"kind":"text","text":" "},{"kind":"identifier","text":"threadPriority"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/title","value":"AgoraRtcEngineConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1threadPriority\/title","value":"threadPriority"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineConfig~1threadPriority\/fragments","value":[{"kind":"identifier","text":"threadPriority"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/title","value":"AgoraThreadPriorityType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}