{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"supervise"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracontentinspecttype\/supervise"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracontentinspecttype\/supervise"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectType\/supervise","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Screenshot capture. SDK takes screenshots of the video stream in the channel and uploads them."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"supervise"}],"title":"AgoraContentInspectType.supervise","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraContentInspectType@AgoraContentInspectTypeSupervise","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectTypeSupervise"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectType/supervise":{"role":"symbol","title":"AgoraContentInspectType.supervise","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"supervise"}],"abstract":[{"type":"text","text":"2: Screenshot capture. SDK takes screenshots of the video stream in the channel and uploads them."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectType\/supervise","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectTypeSupervise"}],"url":"\/documentation\/agorartckit\/agoracontentinspecttype\/supervise"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectType":{"role":"symbol","title":"AgoraContentInspectType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectType"}],"abstract":[{"type":"text","text":"The type of video content moderation module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectType"}],"url":"\/documentation\/agorartckit\/agoracontentinspecttype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraContentInspectTypeSupervise"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectTypeSupervise"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraContentInspectTypeSupervise"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectType~1supervise\/title","value":"AgoraContentInspectTypeSupervise"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectType~1supervise\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectTypeSupervise"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectType\/title","value":"AgoraContentInspectType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectType\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}