{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection","preciseIdentifier":"c:@E@AgoraCameraDirection","text":"AgoraCameraDirection"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracameracapturerconfiguration\/cameradirection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracameracapturerconfiguration\/cameradirection"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration\/cameraDirection","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCameraDirection","preciseIdentifier":"c:@E@AgoraCameraDirection"}],"title":"cameraDirection","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraCameraCapturerConfiguration(py)cameraDirection","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"cameraDirection"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraDirection":{"role":"symbol","title":"AgoraCameraDirection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCameraDirection"}],"abstract":[{"type":"text","text":"The camera direction."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraDirection"}],"url":"\/documentation\/agorartckit\/agoracameradirection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraCapturerConfiguration":{"role":"symbol","title":"AgoraCameraCapturerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"abstract":[{"type":"text","text":"The camera capturer preference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"url":"\/documentation\/agorartckit\/agoracameracapturerconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraCapturerConfiguration/cameraDirection":{"role":"symbol","title":"cameraDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCameraDirection","preciseIdentifier":"c:@E@AgoraCameraDirection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration\/cameraDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraDirection"}],"url":"\/documentation\/agorartckit\/agoracameracapturerconfiguration\/cameradirection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cameraDirection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cameraDirection"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraDirection","preciseIdentifier":"c:@E@AgoraCameraDirection","text":"AgoraCameraDirection"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraDirection"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection\/title","value":"AgoraCameraDirection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraDirection\/fragments","value":[{"kind":"identifier","text":"AgoraCameraDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/title","value":"AgoraCameraCapturerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration~1cameraDirection\/title","value":"cameraDirection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration~1cameraDirection\/fragments","value":[{"kind":"identifier","text":"cameraDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}