{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"followEncodeDimensionRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracameracapturerconfiguration\/followencodedimensionratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracameracapturerconfiguration\/followencodedimensionratio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration\/followEncodeDimensionRatio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether to follow the video aspect ratio set in setVideoEncoderConfiguration"},{"type":"text","text":" "},{"type":"text","text":":YES: (Default) Follow the set video aspect ratio. The SDK crops the captured"},{"type":"text","text":" "},{"type":"text","text":"video according to the set video aspect ratio and synchronously changes the"},{"type":"text","text":" "},{"type":"text","text":"local preview screen and the video frame in onCaptureVideoFrame and"},{"type":"text","text":" "},{"type":"text","text":"onPreEncodeVideoFrame .NO: Do not follow the system default audio playback"},{"type":"text","text":" "},{"type":"text","text":"device. The SDK does not change the aspect ratio of the captured video frame."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"followEncodeDimensionRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"followEncodeDimensionRatio","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraCameraCapturerConfiguration(py)followEncodeDimensionRatio","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"followEncodeDimensionRatio"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraCapturerConfiguration/followEncodeDimensionRatio":{"role":"symbol","title":"followEncodeDimensionRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"followEncodeDimensionRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to follow the video aspect ratio set in setVideoEncoderConfiguration"},{"type":"text","text":" "},{"type":"text","text":":YES: (Default) Follow the set video aspect ratio. The SDK crops the captured"},{"type":"text","text":" "},{"type":"text","text":"video according to the set video aspect ratio and synchronously changes the"},{"type":"text","text":" "},{"type":"text","text":"local preview screen and the video frame in onCaptureVideoFrame and"},{"type":"text","text":" "},{"type":"text","text":"onPreEncodeVideoFrame .NO: Do not follow the system default audio playback"},{"type":"text","text":" "},{"type":"text","text":"device. The SDK does not change the aspect ratio of the captured video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration\/followEncodeDimensionRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"followEncodeDimensionRatio"}],"url":"\/documentation\/agorartckit\/agoracameracapturerconfiguration\/followencodedimensionratio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCameraCapturerConfiguration":{"role":"symbol","title":"AgoraCameraCapturerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"abstract":[{"type":"text","text":"The camera capturer preference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCameraCapturerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}],"url":"\/documentation\/agorartckit\/agoracameracapturerconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"followEncodeDimensionRatio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"followEncodeDimensionRatio"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"followEncodeDimensionRatio"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration~1followEncodeDimensionRatio\/title","value":"followEncodeDimensionRatio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration~1followEncodeDimensionRatio\/fragments","value":[{"kind":"identifier","text":"followEncodeDimensionRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/title","value":"AgoraCameraCapturerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCameraCapturerConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraCameraCapturerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}