{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVideoSourceType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror\/invalidvideosourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror\/invalidvideosourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidVideoSourceType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The video source type is invalid. You need to re-specify the supported video source type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVideoSourceType"}],"title":"AgoraVideoTranscoderError.invalidVideoSourceType","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoTranscoderError@AgoraVideoTranscoderErrorInvalidVideoSourceType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidVideoSourceType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError":{"role":"symbol","title":"AgoraVideoTranscoderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"abstract":[{"type":"text","text":"The error code of the local video mixing failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/invalidVideoSourceType":{"role":"symbol","title":"AgoraVideoTranscoderError.invalidVideoSourceType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVideoSourceType"}],"abstract":[{"type":"text","text":"2: The video source type is invalid. You need to re-specify the supported video source type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/invalidvideosourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoTranscoderErrorInvalidVideoSourceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidVideoSourceType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidVideoSourceType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/title","value":"AgoraVideoTranscoderError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidVideoSourceType\/title","value":"AgoraVideoTranscoderErrorInvalidVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidVideoSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}