{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportImageFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror\/unsupportimageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror\/unsupportimageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/unsupportImageFormat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: The image format is invalid. Make sure the image format is one of PNG, JPEG, or GIF."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportImageFormat"}],"title":"AgoraVideoTranscoderError.unsupportImageFormat","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoTranscoderError@AgoraVideoTranscoderErrorUnsupportImageFormat","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorUnsupportImageFormat"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/unsupportImageFormat":{"role":"symbol","title":"AgoraVideoTranscoderError.unsupportImageFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportImageFormat"}],"abstract":[{"type":"text","text":"4: The image format is invalid. Make sure the image format is one of PNG, JPEG, or GIF."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/unsupportImageFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorUnsupportImageFormat"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/unsupportimageformat"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError":{"role":"symbol","title":"AgoraVideoTranscoderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"abstract":[{"type":"text","text":"The error code of the local video mixing failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoTranscoderErrorUnsupportImageFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorUnsupportImageFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorUnsupportImageFormat"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1unsupportImageFormat\/title","value":"AgoraVideoTranscoderErrorUnsupportImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1unsupportImageFormat\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorUnsupportImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/title","value":"AgoraVideoTranscoderError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}