{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSourceNotReady"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror\/videosourcenotready"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror\/videosourcenotready"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/videoSourceNotReady","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSourceNotReady"}],"title":"AgoraVideoTranscoderError.videoSourceNotReady","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoTranscoderError@AgoraVideoTranscoderErrorVideoSourceNotReady","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorVideoSourceNotReady"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError":{"role":"symbol","title":"AgoraVideoTranscoderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/videoSourceNotReady":{"role":"symbol","title":"AgoraVideoTranscoderError.videoSourceNotReady","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSourceNotReady"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/videoSourceNotReady","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorVideoSourceNotReady"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/videosourcenotready"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoTranscoderErrorVideoSourceNotReady"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorVideoSourceNotReady"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorVideoSourceNotReady"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/title","value":"AgoraVideoTranscoderError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1videoSourceNotReady\/title","value":"AgoraVideoTranscoderErrorVideoSourceNotReady"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1videoSourceNotReady\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorVideoSourceNotReady"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}