{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiomixingstatetype\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiomixingstatetype\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingStateType\/failed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"714: An error occurs during the playback of the audio mixing file.The possible reasons include:AgoraAudioMixingReasonTypeCanNotOpen(701)AgoraAudioMixingReasonTypeTooFrequentlyCall(702)AgoraAudioMixingReasonTypeInterruptedEOF(703)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"title":"AgoraAudioMixingStateType.failed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioMixingStateType@AgoraAudioMixingStateTypeFailed","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingStateTypeFailed"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingStateType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingStateType/failed":{"role":"symbol","title":"AgoraAudioMixingStateType.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"714: An error occurs during the playback of the audio mixing file.The possible reasons include:AgoraAudioMixingReasonTypeCanNotOpen(701)AgoraAudioMixingReasonTypeTooFrequentlyCall(702)AgoraAudioMixingReasonTypeInterruptedEOF(703)"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingStateType\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingStateTypeFailed"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingstatetype\/failed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingStateType":{"role":"symbol","title":"AgoraAudioMixingStateType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingStateType"}],"abstract":[{"type":"text","text":"The playback state of the music file."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingStateType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingStateType"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingstatetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioMixingStateTypeFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingStateTypeFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioMixingStateTypeFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingStateType~1failed\/title","value":"AgoraAudioMixingStateTypeFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingStateType~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingStateTypeFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingStateType\/title","value":"AgoraAudioMixingStateType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingStateType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingStateType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}