{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptative"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode\/adaptative"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode\/adaptative"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/adaptative","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: (Default) The output video always follows the orientation of the"},{"type":"text","text":" "},{"type":"text","text":"captured video. The receiver takes the rotational information passed on"},{"type":"text","text":" "},{"type":"text","text":"from the video encoder. This mode applies to scenarios where video"},{"type":"text","text":" "},{"type":"text","text":"orientation can be adjusted on the receiver.If the captured video is in"},{"type":"text","text":" "},{"type":"text","text":"landscape mode, the output video is in landscape mode.If the captured video"},{"type":"text","text":" "},{"type":"text","text":"is in portrait mode, the output video is in portrait mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptative"}],"title":"AgoraVideoOutputOrientationMode.adaptative","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoOutputOrientationMode@AgoraVideoOutputOrientationModeAdaptative","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeAdaptative"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/adaptative":{"role":"symbol","title":"AgoraVideoOutputOrientationMode.adaptative","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptative"}],"abstract":[{"type":"text","text":"0: (Default) The output video always follows the orientation of the"},{"type":"text","text":" "},{"type":"text","text":"captured video. The receiver takes the rotational information passed on"},{"type":"text","text":" "},{"type":"text","text":"from the video encoder. This mode applies to scenarios where video"},{"type":"text","text":" "},{"type":"text","text":"orientation can be adjusted on the receiver.If the captured video is in"},{"type":"text","text":" "},{"type":"text","text":"landscape mode, the output video is in landscape mode.If the captured video"},{"type":"text","text":" "},{"type":"text","text":"is in portrait mode, the output video is in portrait mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/adaptative","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeAdaptative"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/adaptative"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode":{"role":"symbol","title":"AgoraVideoOutputOrientationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"abstract":[{"type":"text","text":"Video output orientation mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoOutputOrientationModeAdaptative"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeAdaptative"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeAdaptative"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1adaptative\/title","value":"AgoraVideoOutputOrientationModeAdaptative"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1adaptative\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeAdaptative"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/title","value":"AgoraVideoOutputOrientationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}