{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedPortrait"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedportrait"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedportrait"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedPortrait","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: In this mode, the SDK always outputs video in portrait (portrait) mode. If the captured video is in landscape mode, the video encoder crops it to fit the output. Applies to situations where the receiving end cannot process the rotational information. For example, CDN live streaming."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedPortrait"}],"title":"AgoraVideoOutputOrientationMode.fixedPortrait","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoOutputOrientationMode@AgoraVideoOutputOrientationModeFixedPortrait","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedPortrait"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/fixedPortrait":{"role":"symbol","title":"AgoraVideoOutputOrientationMode.fixedPortrait","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedPortrait"}],"abstract":[{"type":"text","text":"2: In this mode, the SDK always outputs video in portrait (portrait) mode. If the captured video is in landscape mode, the video encoder crops it to fit the output. Applies to situations where the receiving end cannot process the rotational information. For example, CDN live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedPortrait","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedPortrait"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedportrait"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode":{"role":"symbol","title":"AgoraVideoOutputOrientationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"abstract":[{"type":"text","text":"Video output orientation mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoOutputOrientationModeFixedPortrait"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedPortrait"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedPortrait"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedPortrait\/title","value":"AgoraVideoOutputOrientationModeFixedPortrait"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedPortrait\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedPortrait"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/title","value":"AgoraVideoOutputOrientationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}