{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedLandscape"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedlandscape"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedlandscape"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedLandscape","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: In this mode, the SDK always outputs videos in landscape (horizontal)"},{"type":"text","text":" "},{"type":"text","text":"mode. If the captured video is in portrait mode, the video encoder crops it"},{"type":"text","text":" "},{"type":"text","text":"to fit the output. Applies to situations where the receiving end cannot"},{"type":"text","text":" "},{"type":"text","text":"process the rotational information. For example, CDN live streaming."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedLandscape"}],"title":"AgoraVideoOutputOrientationMode.fixedLandscape","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoOutputOrientationMode@AgoraVideoOutputOrientationModeFixedLandscape","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedLandscape"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/fixedLandscape":{"role":"symbol","title":"AgoraVideoOutputOrientationMode.fixedLandscape","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedLandscape"}],"abstract":[{"type":"text","text":"1: In this mode, the SDK always outputs videos in landscape (horizontal)"},{"type":"text","text":" "},{"type":"text","text":"mode. If the captured video is in portrait mode, the video encoder crops it"},{"type":"text","text":" "},{"type":"text","text":"to fit the output. Applies to situations where the receiving end cannot"},{"type":"text","text":" "},{"type":"text","text":"process the rotational information. For example, CDN live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedLandscape","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedLandscape"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedlandscape"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode":{"role":"symbol","title":"AgoraVideoOutputOrientationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"abstract":[{"type":"text","text":"Video output orientation mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoOutputOrientationModeFixedLandscape"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedLandscape"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedLandscape"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedLandscape\/title","value":"AgoraVideoOutputOrientationModeFixedLandscape"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedLandscape\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedLandscape"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/title","value":"AgoraVideoOutputOrientationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}