{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fast"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralowlightenhancelevel\/fast"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralowlightenhancelevel\/fast"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel\/fast","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Promotes performance during low-light enhancement. It processes the brightness and details of the video image. The processing speed is faster."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fast"}],"title":"AgoraLowlightEnhanceLevel.fast","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLowlightEnhanceLevel@AgoraLowlightEnhanceLevelFast","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelFast"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceLevel":{"role":"symbol","title":"AgoraLowlightEnhanceLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}],"abstract":[{"type":"text","text":"The low-light enhancement level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}],"url":"\/documentation\/agorartckit\/agoralowlightenhancelevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceLevel/fast":{"role":"symbol","title":"AgoraLowlightEnhanceLevel.fast","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fast"}],"abstract":[{"type":"text","text":"1: Promotes performance during low-light enhancement. It processes the brightness and details of the video image. The processing speed is faster."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel\/fast","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelFast"}],"url":"\/documentation\/agorartckit\/agoralowlightenhancelevel\/fast"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLowlightEnhanceLevelFast"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelFast"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelFast"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel\/title","value":"AgoraLowlightEnhanceLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel~1fast\/title","value":"AgoraLowlightEnhanceLevelFast"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel~1fast\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelFast"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}