{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralowlightenhancelevel\/quality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralowlightenhancelevel\/quality"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel\/quality","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: (Default) Promotes video quality during low-light enhancement. It processes the brightness, details, and noise of the video image. The performance consumption is moderate, the processing speed is moderate, and the overall video quality is optimal."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"}],"title":"AgoraLowlightEnhanceLevel.quality","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLowlightEnhanceLevel@AgoraLowlightEnhanceLevelQuality","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelQuality"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceLevel":{"role":"symbol","title":"AgoraLowlightEnhanceLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}],"abstract":[{"type":"text","text":"The low-light enhancement level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}],"url":"\/documentation\/agorartckit\/agoralowlightenhancelevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLowlightEnhanceLevel/quality":{"role":"symbol","title":"AgoraLowlightEnhanceLevel.quality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"}],"abstract":[{"type":"text","text":"0: (Default) Promotes video quality during low-light enhancement. It processes the brightness, details, and noise of the video image. The performance consumption is moderate, the processing speed is moderate, and the overall video quality is optimal."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLowlightEnhanceLevel\/quality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelQuality"}],"url":"\/documentation\/agorartckit\/agoralowlightenhancelevel\/quality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLowlightEnhanceLevelQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelQuality"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelQuality"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel\/title","value":"AgoraLowlightEnhanceLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel~1quality\/title","value":"AgoraLowlightEnhanceLevelQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLowlightEnhanceLevel~1quality\/fragments","value":[{"kind":"identifier","text":"AgoraLowlightEnhanceLevelQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}