{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishcustomaudiotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishcustomaudiotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomAudioTrack","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets whether to publish the captured audio from a custom source:YES: Publish"},{"type":"text","text":" "},{"type":"text","text":"the captured audio from a custom source.NO: (Default) Do not publish the"},{"type":"text","text":" "},{"type":"text","text":"captured audio from the custom source."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"publishCustomAudioTrack","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions(py)publishCustomAudioTrack","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"publishCustomAudioTrack"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions":{"role":"symbol","title":"AgoraDirectCdnStreamingMediaOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"abstract":[{"type":"text","text":"The media setting options for the host."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/publishCustomAudioTrack":{"role":"symbol","title":"publishCustomAudioTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets whether to publish the captured audio from a custom source:YES: Publish"},{"type":"text","text":" "},{"type":"text","text":"the captured audio from a custom source.NO: (Default) Do not publish the"},{"type":"text","text":" "},{"type":"text","text":"captured audio from the custom source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCustomAudioTrack"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishcustomaudiotrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"publishCustomAudioTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"publishCustomAudioTrack"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomAudioTrack"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/title","value":"AgoraDirectCdnStreamingMediaOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCustomAudioTrack\/title","value":"publishCustomAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCustomAudioTrack\/fragments","value":[{"kind":"identifier","text":"publishCustomAudioTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}