{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleInPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/watermarkoptions\/visibleinpreview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/watermarkoptions\/visibleinpreview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/visibleInPreview","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reserved for future use."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleInPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"visibleInPreview","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)WatermarkOptions(py)visibleInPreview","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"visibleInPreview"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/WatermarkOptions/visibleInPreview":{"role":"symbol","title":"visibleInPreview","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleInPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Reserved for future use."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/visibleInPreview","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"visibleInPreview"}],"url":"\/documentation\/agorartckit\/watermarkoptions\/visibleinpreview"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/WatermarkOptions":{"role":"symbol","title":"WatermarkOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatermarkOptions"}],"abstract":[{"type":"text","text":"Configurations of the watermark image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatermarkOptions"}],"url":"\/documentation\/agorartckit\/watermarkoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"visibleInPreview"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"visibleInPreview"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleInPreview"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1visibleInPreview\/title","value":"visibleInPreview"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1visibleInPreview\/fragments","value":[{"kind":"identifier","text":"visibleInPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions\/title","value":"WatermarkOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions\/fragments","value":[{"kind":"identifier","text":"WatermarkOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}