{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferAuto"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodingpreference\/preferauto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodingpreference\/preferauto"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferAuto","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"-1: Adaptive preference. The SDK automatically selects the optimal encoding type for encoding based on factors such as platform and device type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferAuto"}],"title":"AgoraEncodingPreference.preferAuto","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraEncodingPreference@AgoraEncodingPreferAuto","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreferAuto"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference":{"role":"symbol","title":"AgoraEncodingPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodingPreference"}],"abstract":[{"type":"text","text":"Video encoder preference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreference"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/preferAuto":{"role":"symbol","title":"AgoraEncodingPreference.preferAuto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferAuto"}],"abstract":[{"type":"text","text":"-1: Adaptive preference. The SDK automatically selects the optimal encoding type for encoding based on factors such as platform and device type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferAuto","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreferAuto"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference\/preferauto"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncodingPreferAuto"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreferAuto"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraEncodingPreferAuto"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/title","value":"AgoraEncodingPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1preferAuto\/title","value":"AgoraEncodingPreferAuto"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1preferAuto\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreferAuto"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}