{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersoftware"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodingpreference\/prefersoftware"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodingpreference\/prefersoftware"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/prefersoftware","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: Software coding preference. The SDK prefers software encoders for video encoding."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersoftware"}],"title":"AgoraEncodingPreference.prefersoftware","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraEncodingPreference@AgoraEncodingPrefersoftware","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPrefersoftware"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/prefersoftware":{"role":"symbol","title":"AgoraEncodingPreference.prefersoftware","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersoftware"}],"abstract":[{"type":"text","text":"0: Software coding preference. The SDK prefers software encoders for video encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/prefersoftware","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPrefersoftware"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference\/prefersoftware"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference":{"role":"symbol","title":"AgoraEncodingPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodingPreference"}],"abstract":[{"type":"text","text":"Video encoder preference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreference"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncodingPrefersoftware"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPrefersoftware"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraEncodingPrefersoftware"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1prefersoftware\/title","value":"AgoraEncodingPrefersoftware"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1prefersoftware\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPrefersoftware"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/title","value":"AgoraEncodingPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreference"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}