{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"unowned(unsafe)"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudioconfig\/rtcengine"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudioconfig\/rtcengine"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioConfig\/rtcEngine","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"AgoraRtcEngineKit."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":"?"}],"title":"rtcEngine","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLocalSpatialAudioConfig(py)rtcEngine","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioConfig"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit":{"role":"symbol","title":"AgoraRtcEngineKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineKit"}],"abstract":[{"type":"text","text":"The basic interface of the Agora SDK that implements the core functions of real-time communication."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineKit"}],"url":"\/documentation\/agorartckit\/agorartcenginekit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioConfig":{"role":"symbol","title":"AgoraLocalSpatialAudioConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioConfig"}],"abstract":[{"type":"text","text":"The configuration of AgoraLocalSpatialAudioKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioConfig"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudioconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioConfig/rtcEngine":{"role":"symbol","title":"rtcEngine","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"AgoraRtcEngineKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioConfig\/rtcEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudioconfig\/rtcengine"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rtcEngine"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rtcEngine"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/title","value":"AgoraRtcEngineKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioConfig\/title","value":"AgoraLocalSpatialAudioConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioConfig~1rtcEngine\/title","value":"rtcEngine"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioConfig~1rtcEngine\/fragments","value":[{"kind":"identifier","text":"rtcEngine"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}