{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreencapturesourcetype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreencapturesourcetype\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/unknown","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"AgoraScreenCaptureSourceType.unknown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraScreenCaptureSourceType@AgoraScreenCaptureSourceTypeUnknown","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeUnknown"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/unknown":{"role":"symbol","title":"AgoraScreenCaptureSourceType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeUnknown"}],"url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/unknown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType":{"role":"symbol","title":"AgoraScreenCaptureSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}],"url":"\/documentation\/agorartckit\/agorascreencapturesourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraScreenCaptureSourceTypeUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeUnknown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1unknown\/title","value":"AgoraScreenCaptureSourceTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1unknown\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType\/title","value":"AgoraScreenCaptureSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}