{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AACLC"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiocodectype\/aaclc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiocodectype\/aaclc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/AACLC","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"8: LC-AAC."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AACLC"}],"title":"AgoraAudioCodecType.AACLC","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioCodecType@AgoraAudioCodecTypeAACLC","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecTypeAACLC"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType":{"role":"symbol","title":"AgoraAudioCodecType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioCodecType"}],"abstract":[{"type":"text","text":"The codec type of audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecType"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/AACLC":{"role":"symbol","title":"AgoraAudioCodecType.AACLC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AACLC"}],"abstract":[{"type":"text","text":"8: LC-AAC."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/AACLC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecTypeAACLC"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype\/aaclc"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioCodecTypeAACLC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecTypeAACLC"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioCodecTypeAACLC"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType\/title","value":"AgoraAudioCodecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1AACLC\/title","value":"AgoraAudioCodecTypeAACLC"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1AACLC\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecTypeAACLC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}