{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compressionPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCompressionPreference","preciseIdentifier":"c:@E@AgoraCompressionPreference","text":"AgoraCompressionPreference"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraadvancedvideooptions\/compressionpreference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraadvancedvideooptions\/compressionpreference"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions\/compressionPreference","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Compression preference for video encoding. See AgoraCompressionPreference."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compressionPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCompressionPreference","preciseIdentifier":"c:@E@AgoraCompressionPreference"}],"title":"compressionPreference","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraAdvancedVideoOptions(py)compressionPreference","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"compressionPreference"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAdvancedVideoOptions":{"role":"symbol","title":"AgoraAdvancedVideoOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}],"url":"\/documentation\/agorartckit\/agoraadvancedvideooptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCompressionPreference":{"role":"symbol","title":"AgoraCompressionPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCompressionPreference"}],"abstract":[{"type":"text","text":"Compression preference for video encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCompressionPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCompressionPreference"}],"url":"\/documentation\/agorartckit\/agoracompressionpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAdvancedVideoOptions/compressionPreference":{"role":"symbol","title":"compressionPreference","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compressionPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraCompressionPreference","preciseIdentifier":"c:@E@AgoraCompressionPreference"}],"abstract":[{"type":"text","text":"Compression preference for video encoding. See AgoraCompressionPreference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions\/compressionPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"compressionPreference"}],"url":"\/documentation\/agorartckit\/agoraadvancedvideooptions\/compressionpreference"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"compressionPreference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"compressionPreference"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCompressionPreference","preciseIdentifier":"c:@E@AgoraCompressionPreference","text":"AgoraCompressionPreference"},{"kind":"text","text":" "},{"kind":"identifier","text":"compressionPreference"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions\/title","value":"AgoraAdvancedVideoOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions\/fragments","value":[{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCompressionPreference\/title","value":"AgoraCompressionPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCompressionPreference\/fragments","value":[{"kind":"identifier","text":"AgoraCompressionPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions~1compressionPreference\/title","value":"compressionPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions~1compressionPreference\/fragments","value":[{"kind":"identifier","text":"compressionPreference"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}