{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference","preciseIdentifier":"c:@E@AgoraEncodingPreference","text":"AgoraEncodingPreference"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraadvancedvideooptions\/encodingpreference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraadvancedvideooptions\/encodingpreference"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions\/encodingPreference","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video encoder preference. See AgoraEncodingPreference ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodingPreference","preciseIdentifier":"c:@E@AgoraEncodingPreference"}],"title":"encodingPreference","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraAdvancedVideoOptions(py)encodingPreference","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"encodingPreference"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAdvancedVideoOptions/encodingPreference":{"role":"symbol","title":"encodingPreference","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodingPreference","preciseIdentifier":"c:@E@AgoraEncodingPreference"}],"abstract":[{"type":"text","text":"Video encoder preference. See AgoraEncodingPreference ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions\/encodingPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodingPreference"}],"url":"\/documentation\/agorartckit\/agoraadvancedvideooptions\/encodingpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference":{"role":"symbol","title":"AgoraEncodingPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodingPreference"}],"abstract":[{"type":"text","text":"Video encoder preference."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreference"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAdvancedVideoOptions":{"role":"symbol","title":"AgoraAdvancedVideoOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAdvancedVideoOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}],"url":"\/documentation\/agorartckit\/agoraadvancedvideooptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"encodingPreference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"encodingPreference"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference","preciseIdentifier":"c:@E@AgoraEncodingPreference","text":"AgoraEncodingPreference"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingPreference"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions~1encodingPreference\/title","value":"encodingPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions~1encodingPreference\/fragments","value":[{"kind":"identifier","text":"encodingPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/title","value":"AgoraEncodingPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions\/title","value":"AgoraAdvancedVideoOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAdvancedVideoOptions\/fragments","value":[{"kind":"identifier","text":"AgoraAdvancedVideoOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}