{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteVideo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediasourcetype\/remotevideo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediasourcetype\/remotevideo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/remoteVideo","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteVideo"}],"title":"AgoraMediaSourceType.remoteVideo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaSourceType@AgoraMediaSourceTypeRemoteVideo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeRemoteVideo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType":{"role":"symbol","title":"AgoraMediaSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaSourceType"}],"abstract":[{"type":"text","text":"Media source type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceType"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/remoteVideo":{"role":"symbol","title":"AgoraMediaSourceType.remoteVideo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteVideo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/remoteVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeRemoteVideo"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/remotevideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaSourceTypeRemoteVideo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeRemoteVideo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaSourceTypeRemoteVideo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType\/title","value":"AgoraMediaSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1remoteVideo\/title","value":"AgoraMediaSourceTypeRemoteVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1remoteVideo\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeRemoteVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}