{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicInfos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmTopicInfo","preciseIdentifier":"c:objc(cs)AgoraRtmTopicInfo","text":"AgoraRtmTopicInfo"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpresenceevent\/topicinfos"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpresenceevent\/topicinfos"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/topicInfos","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicInfos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraRtmTopicInfo","preciseIdentifier":"c:objc(cs)AgoraRtmTopicInfo"},{"kind":"text","text":"]"}],"title":"topicInfos","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtmPresenceEvent(py)topicInfos","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"topicInfos"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmTopicInfo":{"role":"symbol","title":"AgoraRtmTopicInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmTopicInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmTopicInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmTopicInfo"}],"url":"\/documentation\/agorartckit\/agorartmtopicinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent":{"role":"symbol","title":"AgoraRtmPresenceEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmPresenceEvent"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceEvent"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent/topicInfos":{"role":"symbol","title":"topicInfos","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicInfos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraRtmTopicInfo","preciseIdentifier":"c:objc(cs)AgoraRtmTopicInfo"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/topicInfos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topicInfos"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent\/topicinfos"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"topicInfos"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topicInfos"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<AgoraRtmTopicInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topicInfos"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmTopicInfo\/title","value":"AgoraRtmTopicInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmTopicInfo\/fragments","value":[{"kind":"identifier","text":"AgoraRtmTopicInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent\/title","value":"AgoraRtmPresenceEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1topicInfos\/title","value":"topicInfos"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1topicInfos\/fragments","value":[{"kind":"identifier","text":"topicInfos"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}