{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding","preciseIdentifier":"c:objc(cs)AgoraLiveTranscoding","text":"AgoraLiveTranscoding"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default AgoraLiveTranscoding object."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralivetranscoding\/default()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralivetranscoding\/default()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/default()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a default transcoding object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraLiveTranscoding","preciseIdentifier":"c:objc(cs)AgoraLiveTranscoding"}],"title":"default()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraLiveTranscoding(cm)defaultTranscoding","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"defaultTranscoding"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/default()":{"role":"symbol","title":"default()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraLiveTranscoding","preciseIdentifier":"c:objc(cs)AgoraLiveTranscoding"}],"abstract":[{"type":"text","text":"Creates a default transcoding object."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/default()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultTranscoding"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/default()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding":{"role":"symbol","title":"AgoraLiveTranscoding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveTranscoding"}],"abstract":[{"type":"text","text":"Transcoding configurations for Media Push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveTranscoding"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"defaultTranscoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultTranscoding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding","preciseIdentifier":"c:objc(cs)AgoraLiveTranscoding","text":"AgoraLiveTranscoding"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"defaultTranscoding"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1default()\/title","value":"defaultTranscoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1default()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultTranscoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/title","value":"AgoraLiveTranscoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/fragments","value":[{"kind":"identifier","text":"AgoraLiveTranscoding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}