{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAdvancedFeatures"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature","preciseIdentifier":"c:objc(cs)AgoraLiveStreamAdvancedFeature","text":"AgoraLiveStreamAdvancedFeature"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The feature name and whether the feature is enabled. See AgoraLiveStreamAdvancedFeature ."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to enable the advanced features of streaming with transcoding, contact ."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralivetranscoding\/getadvancedfeatures()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralivetranscoding\/getadvancedfeatures()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/getAdvancedFeatures()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the status of the advanced features of streaming with transcoding."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAdvancedFeatures"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AgoraLiveStreamAdvancedFeature","preciseIdentifier":"c:objc(cs)AgoraLiveStreamAdvancedFeature"},{"kind":"text","text":"]?"}],"title":"getAdvancedFeatures()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraLiveTranscoding(im)getAdvancedFeatures","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"getAdvancedFeatures"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/getAdvancedFeatures()":{"role":"symbol","title":"getAdvancedFeatures()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAdvancedFeatures"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AgoraLiveStreamAdvancedFeature","preciseIdentifier":"c:objc(cs)AgoraLiveStreamAdvancedFeature"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Gets the status of the advanced features of streaming with transcoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/getAdvancedFeatures()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAdvancedFeatures"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/getadvancedfeatures()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding":{"role":"symbol","title":"AgoraLiveTranscoding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveTranscoding"}],"abstract":[{"type":"text","text":"Transcoding configurations for Media Push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveTranscoding"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveStreamAdvancedFeature":{"role":"symbol","title":"AgoraLiveStreamAdvancedFeature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"abstract":[{"type":"text","text":"The configuration for advanced features of the RTMP or RTMPS streaming with transcoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"url":"\/documentation\/agorartckit\/agoralivestreamadvancedfeature"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getAdvancedFeatures"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAdvancedFeatures"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<AgoraLiveStreamAdvancedFeature *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getAdvancedFeatures"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1getAdvancedFeatures()\/title","value":"getAdvancedFeatures"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1getAdvancedFeatures()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAdvancedFeatures"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/title","value":"AgoraLiveTranscoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/fragments","value":[{"kind":"identifier","text":"AgoraLiveTranscoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature\/title","value":"AgoraLiveStreamAdvancedFeature"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature\/fragments","value":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}