{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodecProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecProfileType","preciseIdentifier":"c:@E@AgoraVideoCodecProfileType","text":"AgoraVideoCodecProfileType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralivetranscoding\/videocodecprofile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralivetranscoding\/videocodecprofile"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecProfile","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video codec profile type for Media Push. Set it as 66, 77, or 100 (default)."},{"type":"text","text":" "},{"type":"text","text":"See AgoraVideoCodecProfileType for details.If you set this parameter to any"},{"type":"text","text":" "},{"type":"text","text":"other value, Agora adjusts it to the default value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodecProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoCodecProfileType","preciseIdentifier":"c:@E@AgoraVideoCodecProfileType"}],"title":"videoCodecProfile","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLiveTranscoding(py)videoCodecProfile","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"videoCodecProfile"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoCodecProfileType":{"role":"symbol","title":"AgoraVideoCodecProfileType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoCodecProfileType"}],"abstract":[{"type":"text","text":"Video codec profile types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecProfileType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoCodecProfileType"}],"url":"\/documentation\/agorartckit\/agoravideocodecprofiletype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding":{"role":"symbol","title":"AgoraLiveTranscoding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveTranscoding"}],"abstract":[{"type":"text","text":"Transcoding configurations for Media Push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveTranscoding"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/videoCodecProfile":{"role":"symbol","title":"videoCodecProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodecProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoCodecProfileType","preciseIdentifier":"c:@E@AgoraVideoCodecProfileType"}],"abstract":[{"type":"text","text":"Video codec profile type for Media Push. Set it as 66, 77, or 100 (default)."},{"type":"text","text":" "},{"type":"text","text":"See AgoraVideoCodecProfileType for details.If you set this parameter to any"},{"type":"text","text":" "},{"type":"text","text":"other value, Agora adjusts it to the default value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoCodecProfile"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/videocodecprofile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoCodecProfile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoCodecProfile"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecProfileType","preciseIdentifier":"c:@E@AgoraVideoCodecProfileType","text":"AgoraVideoCodecProfileType"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodecProfile"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecProfileType\/title","value":"AgoraVideoCodecProfileType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecProfileType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoCodecProfileType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/title","value":"AgoraLiveTranscoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/fragments","value":[{"kind":"identifier","text":"AgoraLiveTranscoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoCodecProfile\/title","value":"videoCodecProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoCodecProfile\/fragments","value":[{"kind":"identifier","text":"videoCodecProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}