{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoding"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoremotestate\/decoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoremotestate\/decoding"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/decoding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The remote video stream is decoded and plays normally. The SDK reports this state in the case of AgoraVideoRemoteReasonRecovery, AgoraVideoRemoteReasonLocalUnmuted, AgoraVideoRemoteReasonRemoteUnmuted, or AgoraVideoRemoteReasonAudioFallbackRecovery."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoding"}],"title":"AgoraVideoRemoteState.decoding","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoRemoteState@AgoraVideoRemoteStateDecoding","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateDecoding"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState":{"role":"symbol","title":"AgoraVideoRemoteState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteState"}],"abstract":[{"type":"text","text":"The state of the remote video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteState"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/decoding":{"role":"symbol","title":"AgoraVideoRemoteState.decoding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoding"}],"abstract":[{"type":"text","text":"2: The remote video stream is decoded and plays normally. The SDK reports this state in the case of AgoraVideoRemoteReasonRecovery, AgoraVideoRemoteReasonLocalUnmuted, AgoraVideoRemoteReasonRemoteUnmuted, or AgoraVideoRemoteReasonAudioFallbackRecovery."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/decoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateDecoding"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate\/decoding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoRemoteStateDecoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateDecoding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoRemoteStateDecoding"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState\/title","value":"AgoraVideoRemoteState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1decoding\/title","value":"AgoraVideoRemoteStateDecoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1decoding\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateDecoding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}