{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoremotestate\/stopped"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoremotestate\/stopped"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/stopped","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The remote video is in the initial state. The SDK reports this state in the case of AgoraVideoRemoteReasonLocalMuted, AgoraVideoRemoteReasonRemoteMuted, or AgoraVideoRemoteReasonRemoteOffline."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"title":"AgoraVideoRemoteState.stopped","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoRemoteState@AgoraVideoRemoteStateStopped","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateStopped"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/stopped":{"role":"symbol","title":"AgoraVideoRemoteState.stopped","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"abstract":[{"type":"text","text":"0: The remote video is in the initial state. The SDK reports this state in the case of AgoraVideoRemoteReasonLocalMuted, AgoraVideoRemoteReasonRemoteMuted, or AgoraVideoRemoteReasonRemoteOffline."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/stopped","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateStopped"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate\/stopped"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState":{"role":"symbol","title":"AgoraVideoRemoteState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteState"}],"abstract":[{"type":"text","text":"The state of the remote video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteState"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoRemoteStateStopped"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateStopped"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoRemoteStateStopped"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1stopped\/title","value":"AgoraVideoRemoteStateStopped"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1stopped\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateStopped"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState\/title","value":"AgoraVideoRemoteState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}