{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorarhythmplayererror\/ok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorarhythmplayererror\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerError\/OK","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"(0): The beat files are played normally without errors."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"title":"AgoraRhythmPlayerError.OK","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRhythmPlayerError@AgoraRhythmPlayerErrorOK","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerErrorOK"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerError":{"role":"symbol","title":"AgoraRhythmPlayerError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerError"}],"abstract":[{"type":"text","text":"Virtual Metronome error message."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerError"}],"url":"\/documentation\/agorartckit\/agorarhythmplayererror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerError/OK":{"role":"symbol","title":"AgoraRhythmPlayerError.OK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"abstract":[{"type":"text","text":"(0): The beat files are played normally without errors."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerError\/OK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerErrorOK"}],"url":"\/documentation\/agorartckit\/agorarhythmplayererror\/ok"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRhythmPlayerErrorOK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerErrorOK"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRhythmPlayerErrorOK"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerError\/title","value":"AgoraRhythmPlayerError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerError\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerError~1OK\/title","value":"AgoraRhythmPlayerErrorOK"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerError~1OK\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerErrorOK"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}