{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frameData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedAudioFrameInfo","text":"AgoraEncodedAudioFrameInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"samplesPerSec","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Recording sample rate (Hz)."}]}]},{"name":"channels","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of channels.1: Mono.2: Stereo. If the"},{"type":"text","text":" "},{"type":"text","text":"channel uses stereo, the data is interleaved."}]}]},{"name":"samplesPerChannel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of samples per channel in the audio"},{"type":"text","text":" "},{"type":"text","text":"frame."}]}]},{"name":"frameData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio buffer."}]}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Audio information after encoding. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncodedAudioFrameInfo ."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegate\/onplaybackencodedaudioframe(_:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegate\/onplaybackencodedaudioframe(_:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onPlaybackEncodedAudioFrame(_:info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the encoded audio data of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After calling registerAudioEncodedFrameObserver and setting the encoded audio"},{"type":"text","text":" "},{"type":"text","text":"as AgoraAudioEncodedFrameObserverPositionPlayback, you can get encoded audio"},{"type":"text","text":" "},{"type":"text","text":"data of all remote users through this callback."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPlaybackEncodedAudioFrame:info:"}],"role":"symbol","title":"onPlaybackEncodedAudioFrame(_:info:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedAudioFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedAudioFrameInfo"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraAudioEncodedFrameDelegate(im)onPlaybackEncodedAudioFrame:info:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo":{"role":"symbol","title":"AgoraEncodedAudioFrameInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"abstract":[{"type":"text","text":"Audio information after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegate":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}],"abstract":[{"type":"text","text":"The encoded audio observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegate/onPlaybackEncodedAudioFrame(_:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onPlaybackEncodedAudioFrame:info:"}],"role":"symbol","title":"onPlaybackEncodedAudioFrame(_:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedAudioFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedAudioFrameInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets the encoded audio data of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After calling registerAudioEncodedFrameObserver and setting the encoded audio"},{"type":"text","text":" "},{"type":"text","text":"as AgoraAudioEncodedFrameObserverPositionPlayback, you can get encoded audio"},{"type":"text","text":" "},{"type":"text","text":"data of all remote users through this callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onPlaybackEncodedAudioFrame(_:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegate\/onplaybackencodedaudioframe(_:info:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onPlaybackEncodedAudioFrame:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame:info:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"frameData"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedAudioFrameInfo","text":"AgoraEncodedAudioFrameInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo\/title","value":"AgoraEncodedAudioFrameInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate\/title","value":"AgoraAudioEncodedFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onPlaybackEncodedAudioFrame(_:info:)\/title","value":"onPlaybackEncodedAudioFrame:info:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onPlaybackEncodedAudioFrame(_:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame:info:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}