{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaRecorder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"recorder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder","text":"AgoraMediaRecorder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"informationDidUpdated"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderInfo","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderInfo","text":"AgoraMediaRecorderInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorderdelegate\/mediarecorder(_:informationdidupdated:uid:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorderdelegate\/mediarecorder(_:informationdidupdated:uid:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:informationDidUpdated:uid:info:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mediaRecorder:informationDidUpdated:uid:info:"}],"role":"symbol","title":"mediaRecorder(_:informationDidUpdated:uid:info:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaRecorder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"informationDidUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderInfo","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderInfo"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraMediaRecorderDelegate(im)mediaRecorder:informationDidUpdated:uid:info:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderDelegate/mediaRecorder(_:informationDidUpdated:uid:info:)":{"navigatorTitle":[{"kind":"identifier","text":"mediaRecorder:informationDidUpdated:uid:info:"}],"role":"symbol","title":"mediaRecorder(_:informationDidUpdated:uid:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaRecorder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"informationDidUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderInfo","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderInfo"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:informationDidUpdated:uid:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramediarecorderdelegate\/mediarecorder(_:informationdidupdated:uid:info:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderInfo":{"role":"symbol","title":"AgoraMediaRecorderInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderInfo"}],"url":"\/documentation\/agorartckit\/agoramediarecorderinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderDelegate":{"role":"symbol","title":"AgoraMediaRecorderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}],"url":"\/documentation\/agorartckit\/agoramediarecorderdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder":{"role":"symbol","title":"AgoraMediaRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorder"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorder"}],"url":"\/documentation\/agorartckit\/agoramediarecorder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mediaRecorder:informationDidUpdated:uid:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaRecorder:informationDidUpdated:uid:info:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"mediaRecorder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder","text":"AgoraMediaRecorder"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"recorder"},{"kind":"text","text":" "},{"kind":"identifier","text":"informationDidUpdated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderInfo","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderInfo","text":"AgoraMediaRecorderInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate~1mediaRecorder(_:informationDidUpdated:uid:info:)\/title","value":"mediaRecorder:informationDidUpdated:uid:info:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate~1mediaRecorder(_:informationDidUpdated:uid:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaRecorder:informationDidUpdated:uid:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderInfo\/title","value":"AgoraMediaRecorderInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderInfo\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate\/title","value":"AgoraMediaRecorderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/title","value":"AgoraMediaRecorder"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}