{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uplinkReport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeOneWayResult","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeOneWayResult","text":"AgoraLastmileProbeOneWayResult"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralastmileproberesult\/uplinkreport"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralastmileproberesult\/uplinkreport"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResult\/uplinkReport","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Results of the uplink last-mile network test. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLastmileProbeOneWayResult ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uplinkReport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLastmileProbeOneWayResult","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeOneWayResult"}],"title":"uplinkReport","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLastmileProbeResult(py)uplinkReport","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"uplinkReport"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResult"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeResult":{"role":"symbol","title":"AgoraLastmileProbeResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLastmileProbeResult"}],"abstract":[{"type":"text","text":"Results of the uplink and downlink last-mile network tests."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeResult"}],"url":"\/documentation\/agorartckit\/agoralastmileproberesult"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeResult/uplinkReport":{"role":"symbol","title":"uplinkReport","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uplinkReport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLastmileProbeOneWayResult","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeOneWayResult"}],"abstract":[{"type":"text","text":"Results of the uplink last-mile network test. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLastmileProbeOneWayResult ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeResult\/uplinkReport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uplinkReport"}],"url":"\/documentation\/agorartckit\/agoralastmileproberesult\/uplinkreport"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLastmileProbeOneWayResult":{"role":"symbol","title":"AgoraLastmileProbeOneWayResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLastmileProbeOneWayResult"}],"abstract":[{"type":"text","text":"Results of the uplink or downlink last-mile network test."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeOneWayResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLastmileProbeOneWayResult"}],"url":"\/documentation\/agorartckit\/agoralastmileprobeonewayresult"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"uplinkReport"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"uplinkReport"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLastmileProbeOneWayResult","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeOneWayResult","text":"AgoraLastmileProbeOneWayResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"uplinkReport"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResult\/title","value":"AgoraLastmileProbeResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResult\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeResult"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResult~1uplinkReport\/title","value":"uplinkReport"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeResult~1uplinkReport\/fragments","value":[{"kind":"identifier","text":"uplinkReport"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeOneWayResult\/title","value":"AgoraLastmileProbeOneWayResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLastmileProbeOneWayResult\/fragments","value":[{"kind":"identifier","text":"AgoraLastmileProbeOneWayResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}