{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileRecordOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType","preciseIdentifier":"c:@E@AgoraAudioFileRecordingType","text":"AgoraAudioFileRecordingType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/filerecordoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/filerecordoption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/fileRecordOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The recording content. See AgoraAudioFileRecordingType."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileRecordOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFileRecordingType","preciseIdentifier":"c:@E@AgoraAudioFileRecordingType"}],"title":"fileRecordOption","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraAudioRecordingConfiguration(py)fileRecordOption","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"fileRecordOption"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration":{"role":"symbol","title":"AgoraAudioRecordingConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"abstract":[{"type":"text","text":"Recording configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration/fileRecordOption":{"role":"symbol","title":"fileRecordOption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileRecordOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFileRecordingType","preciseIdentifier":"c:@E@AgoraAudioFileRecordingType"}],"abstract":[{"type":"text","text":"The recording content. See AgoraAudioFileRecordingType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/fileRecordOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileRecordOption"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/filerecordoption"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType":{"role":"symbol","title":"AgoraAudioFileRecordingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"abstract":[{"type":"text","text":"Recording content. Set in startAudioRecording [2\/2]."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fileRecordOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fileRecordOption"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType","preciseIdentifier":"c:@E@AgoraAudioFileRecordingType","text":"AgoraAudioFileRecordingType"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileRecordOption"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration\/title","value":"AgoraAudioRecordingConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1fileRecordOption\/title","value":"fileRecordOption"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1fileRecordOption\/fragments","value":[{"kind":"identifier","text":"fileRecordOption"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType\/title","value":"AgoraAudioFileRecordingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}