{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingQuality","preciseIdentifier":"c:@E@AgoraAudioRecordingQuality","text":"AgoraAudioRecordingQuality"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/quality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/quality"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/quality","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Recording quality. See AgoraAudioRecordingQuality .Note: This parameter"},{"type":"text","text":" "},{"type":"text","text":"applies to AAC files only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioRecordingQuality","preciseIdentifier":"c:@E@AgoraAudioRecordingQuality"}],"title":"quality","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraAudioRecordingConfiguration(py)quality","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"quality"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration":{"role":"symbol","title":"AgoraAudioRecordingConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"abstract":[{"type":"text","text":"Recording configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingQuality":{"role":"symbol","title":"AgoraAudioRecordingQuality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingQuality"}],"abstract":[{"type":"text","text":"Recording quality."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingQuality"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingquality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration/quality":{"role":"symbol","title":"quality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioRecordingQuality","preciseIdentifier":"c:@E@AgoraAudioRecordingQuality"}],"abstract":[{"type":"text","text":"Recording quality. See AgoraAudioRecordingQuality .Note: This parameter"},{"type":"text","text":" "},{"type":"text","text":"applies to AAC files only."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/quality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"quality"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/quality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"quality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"quality"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingQuality","preciseIdentifier":"c:@E@AgoraAudioRecordingQuality","text":"AgoraAudioRecordingQuality"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration\/title","value":"AgoraAudioRecordingConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingQuality\/title","value":"AgoraAudioRecordingQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingQuality\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1quality\/title","value":"quality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1quality\/fragments","value":[{"kind":"identifier","text":"quality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}