{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorderstate\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorderstate\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderState\/error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"-1: An error occurs during the recording. See AgoraMediaRecorderErrorCode"},{"type":"text","text":" "},{"type":"text","text":"for the reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"title":"AgoraMediaRecorderState.error","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaRecorderState@AgoraMediaRecorderStateError","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderStateError"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderState":{"role":"symbol","title":"AgoraMediaRecorderState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderState"}],"abstract":[{"type":"text","text":"The current recording state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderState"}],"url":"\/documentation\/agorartckit\/agoramediarecorderstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderState/error":{"role":"symbol","title":"AgoraMediaRecorderState.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[{"type":"text","text":"-1: An error occurs during the recording. See AgoraMediaRecorderErrorCode"},{"type":"text","text":" "},{"type":"text","text":"for the reason."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderState\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderStateError"}],"url":"\/documentation\/agorartckit\/agoramediarecorderstate\/error"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaRecorderStateError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderStateError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaRecorderStateError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderState\/title","value":"AgoraMediaRecorderState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderState\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderState~1error\/title","value":"AgoraMediaRecorderStateError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderState~1error\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderStateError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}