{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType","preciseIdentifier":"c:@E@AgoraAudioCodecType","text":"AgoraAudioCodecType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodedaudioframeinfo\/codectype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodedaudioframeinfo\/codectype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/codecType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio Codec type: AgoraAudioCodecType."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioCodecType","preciseIdentifier":"c:@E@AgoraAudioCodecType"}],"title":"codecType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraEncodedAudioFrameInfo(py)codecType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"codecType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType":{"role":"symbol","title":"AgoraAudioCodecType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioCodecType"}],"abstract":[{"type":"text","text":"The codec type of audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecType"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo":{"role":"symbol","title":"AgoraEncodedAudioFrameInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"abstract":[{"type":"text","text":"Audio information after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo/codecType":{"role":"symbol","title":"codecType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioCodecType","preciseIdentifier":"c:@E@AgoraAudioCodecType"}],"abstract":[{"type":"text","text":"Audio Codec type: AgoraAudioCodecType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/codecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecType"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo\/codectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"codecType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"codecType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType","preciseIdentifier":"c:@E@AgoraAudioCodecType","text":"AgoraAudioCodecType"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType\/title","value":"AgoraAudioCodecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo\/title","value":"AgoraEncodedAudioFrameInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1codecType\/title","value":"codecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1codecType\/fragments","value":[{"kind":"identifier","text":"codecType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}