{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint","preciseIdentifier":"c:@E@AgoraVideoContentHint","text":"AgoraVideoContentHint"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreenvideoparameters\/contenthint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreenvideoparameters\/contenthint"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/contentHint","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The content hint for screen sharing. See AgoraVideoContentHint."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoContentHint","preciseIdentifier":"c:@E@AgoraVideoContentHint"}],"title":"contentHint","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraScreenVideoParameters(py)contentHint","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"contentHint"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters/contentHint":{"role":"symbol","title":"contentHint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoContentHint","preciseIdentifier":"c:@E@AgoraVideoContentHint"}],"abstract":[{"type":"text","text":"The content hint for screen sharing. See AgoraVideoContentHint."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/contentHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentHint"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters\/contenthint"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoContentHint":{"role":"symbol","title":"AgoraVideoContentHint","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoContentHint"}],"abstract":[{"type":"text","text":"The content hint for screen sharing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoContentHint"}],"url":"\/documentation\/agorartckit\/agoravideocontenthint"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters":{"role":"symbol","title":"AgoraScreenVideoParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"abstract":[{"type":"text","text":"The video configuration for the shared screen stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"contentHint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"contentHint"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint","preciseIdentifier":"c:@E@AgoraVideoContentHint","text":"AgoraVideoContentHint"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentHint"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1contentHint\/title","value":"contentHint"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1contentHint\/fragments","value":[{"kind":"identifier","text":"contentHint"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint\/title","value":"AgoraVideoContentHint"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint\/fragments","value":[{"kind":"identifier","text":"AgoraVideoContentHint"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters\/title","value":"AgoraScreenVideoParameters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters\/fragments","value":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}