{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiolocalstate\/encoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiolocalstate\/encoding"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState\/encoding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The first audio frame encodes successfully."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"}],"title":"AgoraAudioLocalState.encoding","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioLocalState@AgoraAudioLocalStateEncoding","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalStateEncoding"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalState/encoding":{"role":"symbol","title":"AgoraAudioLocalState.encoding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoding"}],"abstract":[{"type":"text","text":"2: The first audio frame encodes successfully."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState\/encoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalStateEncoding"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalstate\/encoding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalState":{"role":"symbol","title":"AgoraAudioLocalState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioLocalState"}],"abstract":[{"type":"text","text":"The state of the local audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalState"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioLocalStateEncoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalStateEncoding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioLocalStateEncoding"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState~1encoding\/title","value":"AgoraAudioLocalStateEncoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState~1encoding\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalStateEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState\/title","value":"AgoraAudioLocalState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}