{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiolocalstate\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiolocalstate\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState\/failed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The local audio fails to start."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"title":"AgoraAudioLocalState.failed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioLocalState@AgoraAudioLocalStateFailed","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalStateFailed"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalState/failed":{"role":"symbol","title":"AgoraAudioLocalState.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"3: The local audio fails to start."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalStateFailed"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalstate\/failed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalState":{"role":"symbol","title":"AgoraAudioLocalState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioLocalState"}],"abstract":[{"type":"text","text":"The state of the local audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalState"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioLocalStateFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalStateFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioLocalStateFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState~1failed\/title","value":"AgoraAudioLocalStateFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalStateFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState\/title","value":"AgoraAudioLocalState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalState\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}