{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediaplayerrendermode\/fit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediaplayerrendermode\/fit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerRenderMode\/fit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Uniformly scale the video until one of its dimension fits the boundary"},{"type":"text","text":" "},{"type":"text","text":"(zoomed to fit). Fit mode. Areas that are not filled due to disparity in"},{"type":"text","text":" "},{"type":"text","text":"the aspect ratio are filled with black."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"title":"AgoraMediaPlayerRenderMode.fit","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraMediaPlayerRenderMode@AgoraMediaPlayerRenderModeFit","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerRenderModeFit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerRenderMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerRenderMode":{"role":"symbol","title":"AgoraMediaPlayerRenderMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerRenderMode"}],"abstract":[{"type":"text","text":"Video display modes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerRenderMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerRenderMode"}],"url":"\/documentation\/agorartckit\/agoramediaplayerrendermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerRenderMode/fit":{"role":"symbol","title":"AgoraMediaPlayerRenderMode.fit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"abstract":[{"type":"text","text":"2: Uniformly scale the video until one of its dimension fits the boundary"},{"type":"text","text":" "},{"type":"text","text":"(zoomed to fit). Fit mode. Areas that are not filled due to disparity in"},{"type":"text","text":" "},{"type":"text","text":"the aspect ratio are filled with black."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerRenderMode\/fit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerRenderModeFit"}],"url":"\/documentation\/agorartckit\/agoramediaplayerrendermode\/fit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaPlayerRenderModeFit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerRenderModeFit"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraMediaPlayerRenderModeFit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerRenderMode\/title","value":"AgoraMediaPlayerRenderMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerRenderMode\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerRenderMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerRenderMode~1fit\/title","value":"AgoraMediaPlayerRenderModeFit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerRenderMode~1fit\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerRenderModeFit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}