{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPublishSignalVolume"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The remote playback volume, if the method call succeeds. < 0:"},{"type":"text","text":" "},{"type":"text","text":"Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/getpublishsignalvolume()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/getpublishsignalvolume()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/getPublishSignalVolume()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets the volume of the media file for publishing."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getPublishSignalVolume"}],"role":"symbol","title":"getPublishSignalVolume()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPublishSignalVolume"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerProtocol(im)getPublishSignalVolume","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol/getPublishSignalVolume()":{"navigatorTitle":[{"kind":"identifier","text":"getPublishSignalVolume"}],"role":"symbol","title":"getPublishSignalVolume()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPublishSignalVolume"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Gets the volume of the media file for publishing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/getPublishSignalVolume()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/getpublishsignalvolume()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getPublishSignalVolume"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPublishSignalVolume"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"getPublishSignalVolume"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1getPublishSignalVolume()\/title","value":"getPublishSignalVolume"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1getPublishSignalVolume()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPublishSignalVolume"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}