{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWithCustomSourceAtStartPos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"startPos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPlayerOnReadData"},{"kind":"text","text":" "},{"kind":"internalParam","text":"onReadDataCallback"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCustomSourceOnReadCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnReadCallback","text":"AgoraRtcMediaPlayerCustomSourceOnReadCallback"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andPlayerOnSeek"},{"kind":"text","text":" "},{"kind":"internalParam","text":"onSeekCallback"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCustomSourceOnSeekCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnSeekCallback","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"startPos","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The starting position (ms) for playback. Default value is 0."}]}]},{"name":"onReadDataCallBack","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Occurs when the SDK reads the media resource data. See AgoraRtcMediaPlayerCustomSourceOnReadCallback."}]}]},{"name":"onSeekCallBack","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Occurs when the SDK seeks the media resource data. See AgoraRtcMediaPlayerCustomSourceOnSeekCallback."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated: This method is deprecated, use openWithMediaSource instead. This method allows you to open custom media resource files. For example, you can call this method to open encrypted media resources."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/openwithcustomsourceatstartpos(_:withplayeronreaddata:andplayeronseek:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/openwithcustomsourceatstartpos(_:withplayeronreaddata:andplayeronseek:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/openWithCustomSourceAtStartPos(_:withPlayerOnReadData:andPlayerOnSeek:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Opens the custom media resource file."}],"kind":"symbol","metadata":{"modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"openWithCustomSourceAtStartPos:withPlayerOnReadData:andPlayerOnSeek:"}],"role":"symbol","title":"openWithCustomSourceAtStartPos(_:withPlayerOnReadData:andPlayerOnSeek:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWithCustomSourceAtStartPos"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPlayerOnReadData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCustomSourceOnReadCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnReadCallback"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andPlayerOnSeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnSeekCallback"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerProtocol(im)openWithCustomSourceAtStartPos:withPlayerOnReadData:andPlayerOnSeek:","required":true,"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerCustomSourceOnReadCallback":{"role":"symbol","title":"AgoraRtcMediaPlayerCustomSourceOnReadCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnReadCallback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCustomSourceOnReadCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnReadCallback"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayercustomsourceonreadcallback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerCustomSourceOnSeekCallback":{"role":"symbol","title":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerCustomSourceOnSeekCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayercustomsourceonseekcallback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol/openWithCustomSourceAtStartPos(_:withPlayerOnReadData:andPlayerOnSeek:)":{"navigatorTitle":[{"kind":"identifier","text":"openWithCustomSourceAtStartPos:withPlayerOnReadData:andPlayerOnSeek:"}],"deprecated":true,"role":"symbol","title":"openWithCustomSourceAtStartPos(_:withPlayerOnReadData:andPlayerOnSeek:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openWithCustomSourceAtStartPos"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withPlayerOnReadData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCustomSourceOnReadCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnReadCallback"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andPlayerOnSeek"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback","preciseIdentifier":"c:AgoraObjects.h@T@AgoraRtcMediaPlayerCustomSourceOnSeekCallback"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Opens the custom media resource file."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/openWithCustomSourceAtStartPos(_:withPlayerOnReadData:andPlayerOnSeek:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/openwithcustomsourceatstartpos(_:withplayeronreaddata:andplayeronseek:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"openWithCustomSourceAtStartPos:withPlayerOnReadData:andPlayerOnSeek:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openWithCustomSourceAtStartPos:withPlayerOnReadData:andPlayerOnSeek:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"openWithCustomSourceAtStartPos:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"startPos"},{"kind":"text","text":" "},{"kind":"identifier","text":"withPlayerOnReadData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int (^)(id<AgoraRtcMediaPlayerProtocol>, unsigned char *, int)","preciseIdentifier":"c:BFI(#*Qoobjc(pl)AgoraRtcMediaPlayerProtocol#*c#I)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"onReadDataCallback"},{"kind":"text","text":" "},{"kind":"identifier","text":"andPlayerOnSeek:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"long long (^)(id<AgoraRtcMediaPlayerProtocol>, long long, int)","preciseIdentifier":"c:BFK(#*Qoobjc(pl)AgoraRtcMediaPlayerProtocol#K#I)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"onSeekCallback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCustomSourceOnReadCallback\/title","value":"AgoraRtcMediaPlayerCustomSourceOnReadCallback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCustomSourceOnReadCallback\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnReadCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCustomSourceOnSeekCallback\/title","value":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerCustomSourceOnSeekCallback\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerCustomSourceOnSeekCallback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1openWithCustomSourceAtStartPos(_:withPlayerOnReadData:andPlayerOnSeek:)\/title","value":"openWithCustomSourceAtStartPos:withPlayerOnReadData:andPlayerOnSeek:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1openWithCustomSourceAtStartPos(_:withPlayerOnReadData:andPlayerOnSeek:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openWithCustomSourceAtStartPos:withPlayerOnReadData:andPlayerOnSeek:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}