{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playPreloadedSrc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"src"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"src","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the media resource in the playlist must be consistent with the src set by the preloadSrc method; otherwise, the media resource cannot be played."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After calling the preloadSrc method to preload the media resource into the playlist, you can call this method to play the preloaded media resource. After calling this method, if you receive the didChangedToState callback which reports the AgoraMediaPlayerStatePlaying state, the playback is successful. If you want to change the preloaded media resource to be played, you can call this method again and specify the URL of the new media resource that you want to preload. If you want to replay the media resource, you need to call preloadSrc to preload the media resource to the playlist again before playing. If you want to clear the playlist, call the stop method. If you call this method when playback is paused, this method does not take effect until playback is resumed."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/playpreloadedsrc(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/playpreloadedsrc(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/playPreloadedSrc(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Plays preloaded media resources."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"playPreloadedSrc:"}],"role":"symbol","title":"playPreloadedSrc(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playPreloadedSrc"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerProtocol(im)playPreloadedSrc:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol/playPreloadedSrc(_:)":{"navigatorTitle":[{"kind":"identifier","text":"playPreloadedSrc:"}],"role":"symbol","title":"playPreloadedSrc(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playPreloadedSrc"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Plays preloaded media resources."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/playPreloadedSrc(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/playpreloadedsrc(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playPreloadedSrc:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playPreloadedSrc:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"playPreloadedSrc:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"src"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1playPreloadedSrc(_:)\/title","value":"playPreloadedSrc:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1playPreloadedSrc(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playPreloadedSrc:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}