{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioSpectrumDelegate","text":"AgoraAudioSpectrumDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"intervalInMS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/registermediaplayeraudiospectrumdelegate(_:intervalinms:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/registermediaplayeraudiospectrumdelegate(_:intervalinms:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/registerMediaPlayerAudioSpectrumDelegate(_:intervalInMS:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate:intervalInMS:"}],"role":"symbol","title":"registerMediaPlayerAudioSpectrumDelegate(_:intervalInMS:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioSpectrumDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioSpectrumDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"intervalInMS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerProtocol(im)registerMediaPlayerAudioSpectrumDelegate:intervalInMS:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumDelegate":{"role":"symbol","title":"AgoraAudioSpectrumDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}],"abstract":[{"type":"text","text":"The audio spectrum observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudiospectrumdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol/registerMediaPlayerAudioSpectrumDelegate(_:intervalInMS:)":{"navigatorTitle":[{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate:intervalInMS:"}],"role":"symbol","title":"registerMediaPlayerAudioSpectrumDelegate(_:intervalInMS:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioSpectrumDelegate","preciseIdentifier":"c:objc(pl)AgoraAudioSpectrumDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"intervalInMS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/registerMediaPlayerAudioSpectrumDelegate(_:intervalInMS:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/registermediaplayeraudiospectrumdelegate(_:intervalinms:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerMediaPlayerAudioSpectrumDelegate:intervalInMS:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate:intervalInMS:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<AgoraAudioSpectrumDelegate>","preciseIdentifier":"c:Qoobjc(pl)AgoraAudioSpectrumDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"intervalInMS:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"intervalInMS"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate\/title","value":"AgoraAudioSpectrumDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1registerMediaPlayerAudioSpectrumDelegate(_:intervalInMS:)\/title","value":"registerMediaPlayerAudioSpectrumDelegate:intervalInMS:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1registerMediaPlayerAudioSpectrumDelegate(_:intervalInMS:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerMediaPlayerAudioSpectrumDelegate:intervalInMS:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}