{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioDualMonoMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode","preciseIdentifier":"c:@E@AgoraAudioDualMonoMode","text":"AgoraAudioDualMonoMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel mode. See AgoraAudioDualMonoMode ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/setaudiodualmonomode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/setaudiodualmonomode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/setAudioDualMonoMode(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the channel mode of the current audio file."},{"type":"text","text":" "},{"type":"text","text":"In a stereo music file, the left and right channels can store different audio"},{"type":"text","text":" "},{"type":"text","text":"data. According to your needs, you can set the channel mode to original mode,"},{"type":"text","text":" "},{"type":"text","text":"left channel mode, right channel mode, or mixed channel mode. For example, in"},{"type":"text","text":" "},{"type":"text","text":"the KTV scenario, the left channel of the music file stores the musical"},{"type":"text","text":" "},{"type":"text","text":"accompaniment, and the right channel stores the singing voice. If you only"},{"type":"text","text":" "},{"type":"text","text":"need to listen to the accompaniment, call this method to set the channel mode"},{"type":"text","text":" "},{"type":"text","text":"of the music file to left channel mode; if you need to listen to the"},{"type":"text","text":" "},{"type":"text","text":"accompaniment and the singing voice at the same time, call this method to set"},{"type":"text","text":" "},{"type":"text","text":"the channel mode to mixed channel mode.Call this method after calling open"},{"type":"text","text":" "},{"type":"text","text":".This method only applies to stereo audio files."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setAudioDualMonoMode:"}],"role":"symbol","title":"setAudioDualMonoMode(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioDualMonoMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioDualMonoMode","preciseIdentifier":"c:@E@AgoraAudioDualMonoMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerProtocol(im)setAudioDualMonoMode:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol/setAudioDualMonoMode(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setAudioDualMonoMode:"}],"role":"symbol","title":"setAudioDualMonoMode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioDualMonoMode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioDualMonoMode","preciseIdentifier":"c:@E@AgoraAudioDualMonoMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the channel mode of the current audio file."},{"type":"text","text":" "},{"type":"text","text":"In a stereo music file, the left and right channels can store different audio"},{"type":"text","text":" "},{"type":"text","text":"data. According to your needs, you can set the channel mode to original mode,"},{"type":"text","text":" "},{"type":"text","text":"left channel mode, right channel mode, or mixed channel mode. For example, in"},{"type":"text","text":" "},{"type":"text","text":"the KTV scenario, the left channel of the music file stores the musical"},{"type":"text","text":" "},{"type":"text","text":"accompaniment, and the right channel stores the singing voice. If you only"},{"type":"text","text":" "},{"type":"text","text":"need to listen to the accompaniment, call this method to set the channel mode"},{"type":"text","text":" "},{"type":"text","text":"of the music file to left channel mode; if you need to listen to the"},{"type":"text","text":" "},{"type":"text","text":"accompaniment and the singing voice at the same time, call this method to set"},{"type":"text","text":" "},{"type":"text","text":"the channel mode to mixed channel mode.Call this method after calling open"},{"type":"text","text":" "},{"type":"text","text":".This method only applies to stereo audio files."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/setAudioDualMonoMode(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/setaudiodualmonomode(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode":{"role":"symbol","title":"AgoraAudioDualMonoMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"abstract":[{"type":"text","text":"The channel mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setAudioDualMonoMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioDualMonoMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setAudioDualMonoMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode","preciseIdentifier":"c:@E@AgoraAudioDualMonoMode","text":"AgoraAudioDualMonoMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1setAudioDualMonoMode(_:)\/title","value":"setAudioDualMonoMode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1setAudioDualMonoMode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioDualMonoMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/title","value":"AgoraAudioDualMonoMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}