{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchSrc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"src"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"syncPts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"src","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the media resource."}]}]},{"name":"syncPts","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to synchronize the playback position (ms) before"},{"type":"text","text":" "},{"type":"text","text":"and after the switch:YES: Synchronize the playback position before and after"},{"type":"text","text":" "},{"type":"text","text":"the switch.NO: (Default) Do not synchronize the playback position before and"},{"type":"text","text":" "},{"type":"text","text":"after the switch.Make sure to set this parameter as NO if you need to play"},{"type":"text","text":" "},{"type":"text","text":"live streams, or the switch fails. If you need to play on-demand streams, you"},{"type":"text","text":" "},{"type":"text","text":"can set the value of this parameter according to your scenarios."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/switchsrc(_:syncpts:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/switchsrc(_:syncpts:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/switchSrc(_:syncPts:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Switches the media resource being played."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to switch the media resource to be played according"},{"type":"text","text":" "},{"type":"text","text":"to the current network status. For example:When the network is poor, the"},{"type":"text","text":" "},{"type":"text","text":"media resource to be played is switched to a media resource address with a"},{"type":"text","text":" "},{"type":"text","text":"lower bitrate.When the network is good, the media resource to be played is"},{"type":"text","text":" "},{"type":"text","text":"switched to a media resource address with a higher bitrate.After calling this"},{"type":"text","text":" "},{"type":"text","text":"method, if you receive the AgoraMediaPlayerEventSwitchComplete event in the"},{"type":"text","text":" "},{"type":"text","text":"didOccurEvent callback, the switch is successful; If you receive the"},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaPlayerEventSwitchError event in the didOccurEvent callback, the"},{"type":"text","text":" "},{"type":"text","text":"switch fails.Ensure that you call this method after open .To ensure normal"},{"type":"text","text":" "},{"type":"text","text":"playback, pay attention to the following when calling this method:Do not call"},{"type":"text","text":" "},{"type":"text","text":"this method when playback is paused.Do not call the seekToPosition method"},{"type":"text","text":" "},{"type":"text","text":"during switching.Before switching the media resource, make sure that the"},{"type":"text","text":" "},{"type":"text","text":"playback position does not exceed the total duration of the media resource to"},{"type":"text","text":" "},{"type":"text","text":"be switched."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"switchSrc:syncPts:"}],"role":"symbol","title":"switchSrc(_:syncPts:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchSrc"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"syncPts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtcMediaPlayerProtocol(im)switchSrc:syncPts:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol":{"role":"symbol","title":"AgoraRtcMediaPlayerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"abstract":[{"type":"text","text":"This class provides media player functions and supports multiple instances."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerProtocol/switchSrc(_:syncPts:)":{"navigatorTitle":[{"kind":"identifier","text":"switchSrc:syncPts:"}],"role":"symbol","title":"switchSrc(_:syncPts:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchSrc"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"syncPts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Switches the media resource being played."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to switch the media resource to be played according"},{"type":"text","text":" "},{"type":"text","text":"to the current network status. For example:When the network is poor, the"},{"type":"text","text":" "},{"type":"text","text":"media resource to be played is switched to a media resource address with a"},{"type":"text","text":" "},{"type":"text","text":"lower bitrate.When the network is good, the media resource to be played is"},{"type":"text","text":" "},{"type":"text","text":"switched to a media resource address with a higher bitrate.After calling this"},{"type":"text","text":" "},{"type":"text","text":"method, if you receive the AgoraMediaPlayerEventSwitchComplete event in the"},{"type":"text","text":" "},{"type":"text","text":"didOccurEvent callback, the switch is successful; If you receive the"},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaPlayerEventSwitchError event in the didOccurEvent callback, the"},{"type":"text","text":" "},{"type":"text","text":"switch fails.Ensure that you call this method after open .To ensure normal"},{"type":"text","text":" "},{"type":"text","text":"playback, pay attention to the following when calling this method:Do not call"},{"type":"text","text":" "},{"type":"text","text":"this method when playback is paused.Do not call the seekToPosition method"},{"type":"text","text":" "},{"type":"text","text":"during switching.Before switching the media resource, make sure that the"},{"type":"text","text":" "},{"type":"text","text":"playback position does not exceed the total duration of the media resource to"},{"type":"text","text":" "},{"type":"text","text":"be switched."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerProtocol\/switchSrc(_:syncPts:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerprotocol\/switchsrc(_:syncpts:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"switchSrc:syncPts:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchSrc:syncPts:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"switchSrc:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"src"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncPts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"syncPts"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/title","value":"AgoraRtcMediaPlayerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1switchSrc(_:syncPts:)\/title","value":"switchSrc:syncPts:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerProtocol~1switchSrc(_:syncPts:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchSrc:syncPts:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}