{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageQos","preciseIdentifier":"c:@E@AgoraRtmMessageQos","text":"AgoraRtmMessageQos"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmjointopicoption\/qos"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmjointopicoption\/qos"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmJoinTopicOption\/qos","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmMessageQos","preciseIdentifier":"c:@E@AgoraRtmMessageQos"}],"title":"qos","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraRtmJoinTopicOption(py)qos","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"qos"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmJoinTopicOption"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmJoinTopicOption/qos":{"role":"symbol","title":"qos","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qos"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmMessageQos","preciseIdentifier":"c:@E@AgoraRtmMessageQos"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmJoinTopicOption\/qos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qos"}],"url":"\/documentation\/agorartckit\/agorartmjointopicoption\/qos"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageQos":{"role":"symbol","title":"AgoraRtmMessageQos","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmMessageQos"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageQos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmMessageQos"}],"url":"\/documentation\/agorartckit\/agorartmmessageqos"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmJoinTopicOption":{"role":"symbol","title":"AgoraRtmJoinTopicOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmJoinTopicOption"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmJoinTopicOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmJoinTopicOption"}],"url":"\/documentation\/agorartckit\/agorartmjointopicoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"qos"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"qos"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageQos","preciseIdentifier":"c:@E@AgoraRtmMessageQos","text":"AgoraRtmMessageQos"},{"kind":"text","text":" "},{"kind":"identifier","text":"qos"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmJoinTopicOption~1qos\/title","value":"qos"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmJoinTopicOption~1qos\/fragments","value":[{"kind":"identifier","text":"qos"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageQos\/title","value":"AgoraRtmMessageQos"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageQos\/fragments","value":[{"kind":"identifier","text":"AgoraRtmMessageQos"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmJoinTopicOption\/title","value":"AgoraRtmJoinTopicOption"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmJoinTopicOption\/fragments","value":[{"kind":"identifier","text":"AgoraRtmJoinTopicOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}