{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bad"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraexperiencequality\/bad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraexperiencequality\/bad"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality\/bad","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: The QoE of the local user is poor."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bad"}],"title":"AgoraExperienceQuality.bad","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraExperienceQuality@AgoraExperienceQualityBad","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraExperienceQualityBad"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperienceQuality":{"role":"symbol","title":"AgoraExperienceQuality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExperienceQuality"}],"abstract":[{"type":"text","text":"The Quality of Experience (QoE) of the local user when receiving a remote"},{"type":"text","text":" "},{"type":"text","text":"audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperienceQuality"}],"url":"\/documentation\/agorartckit\/agoraexperiencequality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperienceQuality/bad":{"role":"symbol","title":"AgoraExperienceQuality.bad","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bad"}],"abstract":[{"type":"text","text":"1: The QoE of the local user is poor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality\/bad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperienceQualityBad"}],"url":"\/documentation\/agorartckit\/agoraexperiencequality\/bad"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraExperienceQualityBad"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraExperienceQualityBad"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraExperienceQualityBad"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality\/title","value":"AgoraExperienceQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality\/fragments","value":[{"kind":"identifier","text":"AgoraExperienceQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality~1bad\/title","value":"AgoraExperienceQualityBad"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality~1bad\/fragments","value":[{"kind":"identifier","text":"AgoraExperienceQualityBad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}