{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"good"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraexperiencequality\/good"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraexperiencequality\/good"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality\/good","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The QoE of the local user is good."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"good"}],"title":"AgoraExperienceQuality.good","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraExperienceQuality@AgoraExperienceQualityGood","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraExperienceQualityGood"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperienceQuality/good":{"role":"symbol","title":"AgoraExperienceQuality.good","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"good"}],"abstract":[{"type":"text","text":"0: The QoE of the local user is good."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality\/good","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperienceQualityGood"}],"url":"\/documentation\/agorartckit\/agoraexperiencequality\/good"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraExperienceQuality":{"role":"symbol","title":"AgoraExperienceQuality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraExperienceQuality"}],"abstract":[{"type":"text","text":"The Quality of Experience (QoE) of the local user when receiving a remote"},{"type":"text","text":" "},{"type":"text","text":"audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraExperienceQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraExperienceQuality"}],"url":"\/documentation\/agorartckit\/agoraexperiencequality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraExperienceQualityGood"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraExperienceQualityGood"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraExperienceQualityGood"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality~1good\/title","value":"AgoraExperienceQualityGood"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality~1good\/fragments","value":[{"kind":"identifier","text":"AgoraExperienceQualityGood"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality\/title","value":"AgoraExperienceQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraExperienceQuality\/fragments","value":[{"kind":"identifier","text":"AgoraExperienceQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}