{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraleavechanneloptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraleavechanneloptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The options for leaving a channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"title":"AgoraLeaveChannelOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLeaveChannelOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopAllEffect","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopAudioMixing","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopMicrophoneRecording"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLeaveChannelOptions/stopAllEffect":{"role":"symbol","title":"stopAllEffect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAllEffect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to stop playing all audio effects when a user leaves the channel."},{"type":"text","text":" "},{"type":"text","text":"YES: (Default) Stop playing all audio effects.NO: Do not stop playing any"},{"type":"text","text":" "},{"type":"text","text":"audio effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopAllEffect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAllEffect"}],"url":"\/documentation\/agorartckit\/agoraleavechanneloptions\/stopalleffect"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLeaveChannelOptions":{"role":"symbol","title":"AgoraLeaveChannelOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"abstract":[{"type":"text","text":"The options for leaving a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"url":"\/documentation\/agorartckit\/agoraleavechanneloptions"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLeaveChannelOptions/stopAudioMixing":{"role":"symbol","title":"stopAudioMixing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAudioMixing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to stop playing and mixing the music file when a user leaves the"},{"type":"text","text":" "},{"type":"text","text":"channel. YES: (Default) Stop playing and mixing the music file.NO: Do not"},{"type":"text","text":" "},{"type":"text","text":"stop playing and mixing the music file."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopAudioMixing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopAudioMixing"}],"url":"\/documentation\/agorartckit\/agoraleavechanneloptions\/stopaudiomixing"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLeaveChannelOptions/stopMicrophoneRecording":{"role":"symbol","title":"stopMicrophoneRecording","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopMicrophoneRecording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to stop microphone recording when a user leaves the channel. YES:"},{"type":"text","text":" "},{"type":"text","text":"(Default) Stop microphone recording.NO: Do not stop microphone recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopMicrophoneRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopMicrophoneRecording"}],"url":"\/documentation\/agorartckit\/agoraleavechanneloptions\/stopmicrophonerecording"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLeaveChannelOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopAllEffect","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopAudioMixing","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopMicrophoneRecording"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLeaveChannelOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopAllEffect\/title","value":"stopAllEffect"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopAllEffect\/fragments","value":[{"kind":"identifier","text":"stopAllEffect"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions\/title","value":"AgoraLeaveChannelOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions\/fragments","value":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopAudioMixing\/title","value":"stopAudioMixing"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopAudioMixing\/fragments","value":[{"kind":"identifier","text":"stopAudioMixing"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopMicrophoneRecording\/title","value":"stopMicrophoneRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopMicrophoneRecording\/fragments","value":[{"kind":"identifier","text":"stopMicrophoneRecording"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}