{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoranetworktype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoranetworktype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Network type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkType"}],"title":"AgoraNetworkType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraNetworkType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type2G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type3G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type4G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type5G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeDisconnected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeLAN","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeUnknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeWIFI"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/type3G":{"role":"symbol","title":"AgoraNetworkType.type3G","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type3G"}],"abstract":[{"type":"text","text":"4: The network type is mobile 3G."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type3G","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType3G"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/type3g"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/type2G":{"role":"symbol","title":"AgoraNetworkType.type2G","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type2G"}],"abstract":[{"type":"text","text":"3: The network type is mobile 2G."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type2G","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType2G"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/type2g"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/typeWIFI":{"role":"symbol","title":"AgoraNetworkType.typeWIFI","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWIFI"}],"abstract":[{"type":"text","text":"2: The network type is Wi-Fi (including hotspots)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeWIFI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkTypeWIFI"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/typewifi"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/type4G":{"role":"symbol","title":"AgoraNetworkType.type4G","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type4G"}],"abstract":[{"type":"text","text":"5: The network type is mobile 4G."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type4G","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType4G"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/type4g"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/typeDisconnected":{"role":"symbol","title":"AgoraNetworkType.typeDisconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeDisconnected"}],"abstract":[{"type":"text","text":"0: The SDK disconnects from the network."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeDisconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkTypeDisconnected"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/typedisconnected"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/typeUnknown":{"role":"symbol","title":"AgoraNetworkType.typeUnknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeUnknown"}],"abstract":[{"type":"text","text":"-1: The network type is unknown."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeUnknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkTypeUnknown"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/typeunknown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType":{"role":"symbol","title":"AgoraNetworkType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkType"}],"abstract":[{"type":"text","text":"Network type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType"}],"url":"\/documentation\/agorartckit\/agoranetworktype"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/typeLAN":{"role":"symbol","title":"AgoraNetworkType.typeLAN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeLAN"}],"abstract":[{"type":"text","text":"1: The network type is LAN."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeLAN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkTypeLAN"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/typelan"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoranetworktype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/type5G":{"role":"symbol","title":"AgoraNetworkType.type5G","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type5G"}],"abstract":[{"type":"text","text":"6: The network type is mobile 5G."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type5G","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType5G"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/type5g"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoranetworktype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoranetworktype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraNetworkType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraNetworkType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type2G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type3G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type4G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type5G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeDisconnected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeLAN","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeUnknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeWIFI"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type3G\/title","value":"AgoraNetworkType3G"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type3G\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType3G"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type2G\/title","value":"AgoraNetworkType2G"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type2G\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType2G"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeWIFI\/title","value":"AgoraNetworkTypeWIFI"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeWIFI\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkTypeWIFI"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type4G\/title","value":"AgoraNetworkType4G"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type4G\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType4G"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeDisconnected\/title","value":"AgoraNetworkTypeDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeDisconnected\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkTypeDisconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeUnknown\/title","value":"AgoraNetworkTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeUnknown\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType\/title","value":"AgoraNetworkType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeLAN\/title","value":"AgoraNetworkTypeLAN"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeLAN\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkTypeLAN"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type5G\/title","value":"AgoraNetworkType5G"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type5G\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType5G"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}