{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionerrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionerrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Encryption error type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"title":"AgoraEncryptionErrorType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraEncryptionErrorType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_DECRYPTION_FAILURE","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_ENCRYPTION_FAILURE","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_INTERNAL_FAILURE"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraencryptionerrortype\/equatable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraencryptionerrortype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType/ENCRYPTION_ERROR_INTERNAL_FAILURE":{"role":"symbol","title":"AgoraEncryptionErrorType.ENCRYPTION_ERROR_INTERNAL_FAILURE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ENCRYPTION_ERROR_INTERNAL_FAILURE"}],"abstract":[{"type":"text","text":"0: Internal reason."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_INTERNAL_FAILURE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ENCRYPTION_ERROR_INTERNAL_FAILURE"}],"url":"\/documentation\/agorartckit\/agoraencryptionerrortype\/encryption_error_internal_failure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType":{"role":"symbol","title":"AgoraEncryptionErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"abstract":[{"type":"text","text":"Encryption error type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}],"url":"\/documentation\/agorartckit\/agoraencryptionerrortype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType/ENCRYPTION_ERROR_ENCRYPTION_FAILURE":{"role":"symbol","title":"AgoraEncryptionErrorType.ENCRYPTION_ERROR_ENCRYPTION_FAILURE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ENCRYPTION_ERROR_ENCRYPTION_FAILURE"}],"abstract":[{"type":"text","text":"2: Encryption errors."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_ENCRYPTION_FAILURE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ENCRYPTION_ERROR_ENCRYPTION_FAILURE"}],"url":"\/documentation\/agorartckit\/agoraencryptionerrortype\/encryption_error_encryption_failure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraencryptionerrortype\/init(rawvalue:)"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionErrorType/ENCRYPTION_ERROR_DECRYPTION_FAILURE":{"role":"symbol","title":"AgoraEncryptionErrorType.ENCRYPTION_ERROR_DECRYPTION_FAILURE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}],"abstract":[{"type":"text","text":"1: Decryption errors. Ensure that the receiver and the sender use the same"},{"type":"text","text":" "},{"type":"text","text":"encryption mode and key."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_DECRYPTION_FAILURE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}],"url":"\/documentation\/agorartckit\/agoraencryptionerrortype\/encryption_error_decryption_failure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncryptionErrorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_DECRYPTION_FAILURE","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_ENCRYPTION_FAILURE","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionErrorType\/ENCRYPTION_ERROR_INTERNAL_FAILURE"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionErrorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_INTERNAL_FAILURE\/title","value":"ENCRYPTION_ERROR_INTERNAL_FAILURE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_INTERNAL_FAILURE\/fragments","value":[{"kind":"identifier","text":"ENCRYPTION_ERROR_INTERNAL_FAILURE"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType\/title","value":"AgoraEncryptionErrorType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_ENCRYPTION_FAILURE\/title","value":"ENCRYPTION_ERROR_ENCRYPTION_FAILURE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_ENCRYPTION_FAILURE\/fragments","value":[{"kind":"identifier","text":"ENCRYPTION_ERROR_ENCRYPTION_FAILURE"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_DECRYPTION_FAILURE\/title","value":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionErrorType~1ENCRYPTION_ERROR_DECRYPTION_FAILURE\/fragments","value":[{"kind":"identifier","text":"ENCRYPTION_ERROR_DECRYPTION_FAILURE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}