{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides callbacks for media players."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"title":"AgoraRtcMediaPlayerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraRtcMediaPlayerDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:error:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didPlayBufferUpdated:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didPreloadEvent:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didReceiveData:length:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:infoUpdated:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:playerSrcInfoDidChange:from:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:volumeIndicationDidReceive:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/onAgoraCDNTokenWillExpire()"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didPlayBufferUpdated:)":{"role":"symbol","title":"AgoraRtcMediaPlayer(_:didPlayBufferUpdated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPlayBufferUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didPlayBufferUpdated:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didPlayBufferUpdated:"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didplaybufferupdated:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate":{"role":"symbol","title":"AgoraRtcMediaPlayerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"abstract":[{"type":"text","text":"Provides callbacks for media players."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerEvent","preciseIdentifier":"c:@E@AgoraMediaPlayerEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsedTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didoccur:elapsedtime:message:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:volumeIndicationDidReceive:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:volumeIndicationDidReceive:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:volumeIndicationDidReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"volumeIndicationDidReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:volumeIndicationDidReceive:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:volumeindicationdidreceive:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/onAgoraCDNTokenWillExpire()":{"role":"symbol","title":"onAgoraCDNTokenWillExpire()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAgoraCDNTokenWillExpire"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/onAgoraCDNTokenWillExpire()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAgoraCDNTokenWillExpire"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/onagoracdntokenwillexpire()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didChangedTo:error:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToState:error:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didChangedTo:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerState","preciseIdentifier":"c:@E@AgoraMediaPlayerState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerError","preciseIdentifier":"c:@E@AgoraMediaPlayerError"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didchangedto:error:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didPreloadEvent:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didPreloadEvent:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didPreloadEvent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPreloadEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerPreloadEvent","preciseIdentifier":"c:@E@AgoraMediaPlayerPreloadEvent"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didPreloadEvent:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didpreloadevent:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didReceiveData:length:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveData:length:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didReceiveData:length:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didReceiveData:length:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didreceivedata:length:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:infoUpdated:)":{"role":"symbol","title":"AgoraRtcMediaPlayer(_:infoUpdated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"infoUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerUpdatedInfo","preciseIdentifier":"c:objc(cs)AgoraMediaPlayerUpdatedInfo"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:infoUpdated:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:infoUpdated:"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:infoupdated:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:didChangedTo:)":{"role":"symbol","title":"AgoraRtcMediaPlayer(_:didChangedTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToPosition:"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:didchangedto:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerDelegate/AgoraRtcMediaPlayer(_:playerSrcInfoDidChange:from:)":{"role":"symbol","title":"AgoraRtcMediaPlayer(_:playerSrcInfoDidChange:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playerSrcInfoDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerSrcInfo","preciseIdentifier":"c:objc(cs)AgoraMediaPlayerSrcInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaPlayerSrcInfo","preciseIdentifier":"c:objc(cs)AgoraMediaPlayerSrcInfo"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:playerSrcInfoDidChange:from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:playerSrcInfoDidChange:from:"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayerdelegate\/agorartcmediaplayer(_:playersrcinfodidchange:from:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcMediaPlayerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didChangedTo:error:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didPlayBufferUpdated:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didPreloadEvent:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:didReceiveData:length:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:infoUpdated:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:playerSrcInfoDidChange:from:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/AgoraRtcMediaPlayer(_:volumeIndicationDidReceive:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerDelegate\/onAgoraCDNTokenWillExpire()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didPlayBufferUpdated:)\/title","value":"AgoraRtcMediaPlayer:didPlayBufferUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didPlayBufferUpdated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didPlayBufferUpdated:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/title","value":"AgoraRtcMediaPlayerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)\/title","value":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didOccur:elapsedTime:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didOccurEvent:elapsedTime:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:volumeIndicationDidReceive:)\/title","value":"AgoraRtcMediaPlayer:volumeIndicationDidReceive:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:volumeIndicationDidReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:volumeIndicationDidReceive:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1onAgoraCDNTokenWillExpire()\/title","value":"onAgoraCDNTokenWillExpire"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1onAgoraCDNTokenWillExpire()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAgoraCDNTokenWillExpire"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didChangedTo:error:)\/title","value":"AgoraRtcMediaPlayer:didChangedToState:error:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didChangedTo:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToState:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didPreloadEvent:)\/title","value":"AgoraRtcMediaPlayer:didPreloadEvent:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didPreloadEvent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didPreloadEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didReceiveData:length:)\/title","value":"AgoraRtcMediaPlayer:didReceiveData:length:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didReceiveData:length:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveData:length:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:infoUpdated:)\/title","value":"AgoraRtcMediaPlayer:infoUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:infoUpdated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:infoUpdated:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didChangedTo:)\/title","value":"AgoraRtcMediaPlayer:didChangedToPosition:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:didChangedTo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didChangedToPosition:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:playerSrcInfoDidChange:from:)\/title","value":"AgoraRtcMediaPlayer:playerSrcInfoDidChange:from:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerDelegate~1AgoraRtcMediaPlayer(_:playerSrcInfoDidChange:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:playerSrcInfoDidChange:from:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}