{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWlAccAction"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorawlaccaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorawlaccaction"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionCheck5G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionCloseToWIFI","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionConnectSSID","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionModifySSID"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWlAccAction"}],"title":"AgoraWlAccAction","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraWlAccAction","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccAction"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction":{"role":"symbol","title":"AgoraWlAccAction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWlAccAction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccAction"}],"url":"\/documentation\/agorartckit\/agorawlaccaction"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/suggestActionModifySSID":{"role":"symbol","title":"AgoraWlAccAction.suggestActionModifySSID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestActionModifySSID"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionModifySSID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccSuggestActionModifySSID"}],"url":"\/documentation\/agorartckit\/agorawlaccaction\/suggestactionmodifyssid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/suggestActionCloseToWIFI":{"role":"symbol","title":"AgoraWlAccAction.suggestActionCloseToWIFI","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestActionCloseToWIFI"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionCloseToWIFI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccSuggestActionCloseToWIFI"}],"url":"\/documentation\/agorartckit\/agorawlaccaction\/suggestactionclosetowifi"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/suggestActionCheck5G":{"role":"symbol","title":"AgoraWlAccAction.suggestActionCheck5G","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestActionCheck5G"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionCheck5G","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccSuggestActionCheck5G"}],"url":"\/documentation\/agorartckit\/agorawlaccaction\/suggestactioncheck5g"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorawlaccaction\/init(rawvalue:)"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorawlaccaction\/equatable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/suggestActionConnectSSID":{"role":"symbol","title":"AgoraWlAccAction.suggestActionConnectSSID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestActionConnectSSID"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionConnectSSID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWlAccSuggestActionConnectSSID"}],"url":"\/documentation\/agorartckit\/agorawlaccaction\/suggestactionconnectssid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWlAccAction/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorawlaccaction\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraWlAccAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccAction"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraWlAccAction"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionCheck5G","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionCloseToWIFI","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionConnectSSID","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWlAccAction\/suggestActionModifySSID"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWlAccAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction\/title","value":"AgoraWlAccAction"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccAction"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionModifySSID\/title","value":"AgoraWlAccSuggestActionModifySSID"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionModifySSID\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccSuggestActionModifySSID"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionCloseToWIFI\/title","value":"AgoraWlAccSuggestActionCloseToWIFI"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionCloseToWIFI\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccSuggestActionCloseToWIFI"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionCheck5G\/title","value":"AgoraWlAccSuggestActionCheck5G"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionCheck5G\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccSuggestActionCheck5G"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionConnectSSID\/title","value":"AgoraWlAccSuggestActionConnectSSID"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWlAccAction~1suggestActionConnectSSID\/fragments","value":[{"kind":"identifier","text":"AgoraWlAccSuggestActionConnectSSID"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}