{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioremotereason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioremotereason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The reason for the remote audio state change."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteReason"}],"title":"AgoraAudioRemoteReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioRemoteReason","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReason"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/localMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/localUnmuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkCongestion","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkRecovery","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteOffline","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteUnmuted"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioremotereason\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioremotereason\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/localMuted":{"role":"symbol","title":"AgoraAudioRemoteReason.localMuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMuted"}],"abstract":[{"type":"text","text":"3: The local user stops receiving the remote audio stream or disables the audio module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/localMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonLocalMuted"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/localmuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioremotereason\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/networkCongestion":{"role":"symbol","title":"AgoraAudioRemoteReason.networkCongestion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkCongestion"}],"abstract":[{"type":"text","text":"1: Network congestion."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkCongestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkCongestion"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/networkcongestion"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason":{"role":"symbol","title":"AgoraAudioRemoteReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteReason"}],"abstract":[{"type":"text","text":"The reason for the remote audio state change."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReason"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/remoteUnmuted":{"role":"symbol","title":"AgoraAudioRemoteReason.remoteUnmuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUnmuted"}],"abstract":[{"type":"text","text":"6: The remote user resumes sending the audio stream or enables the audio module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteUnmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonRemoteUnmuted"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/remoteunmuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/localUnmuted":{"role":"symbol","title":"AgoraAudioRemoteReason.localUnmuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localUnmuted"}],"abstract":[{"type":"text","text":"4: The local user resumes receiving the remote audio stream or enables the audio module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/localUnmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonLocalUnmuted"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/localunmuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/internal":{"role":"symbol","title":"AgoraAudioRemoteReason.internal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"}],"abstract":[{"type":"text","text":"0: The SDK reports this reason when the audio state changes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/internal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonInternal"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/internal"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/networkRecovery":{"role":"symbol","title":"AgoraAudioRemoteReason.networkRecovery","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkRecovery"}],"abstract":[{"type":"text","text":"2: Network recovery."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkRecovery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkRecovery"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/networkrecovery"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/remoteMuted":{"role":"symbol","title":"AgoraAudioRemoteReason.remoteMuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteMuted"}],"abstract":[{"type":"text","text":"5: The remote user stops sending the audio stream or disables the audio module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonRemoteMuted"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/remotemuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteReason/remoteOffline":{"role":"symbol","title":"AgoraAudioRemoteReason.remoteOffline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteOffline"}],"abstract":[{"type":"text","text":"7: The remote user leaves the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteOffline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteReasonRemoteOffline"}],"url":"\/documentation\/agorartckit\/agoraaudioremotereason\/remoteoffline"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioRemoteReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioRemoteReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/localMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/localUnmuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkCongestion","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/networkRecovery","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteOffline","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteReason\/remoteUnmuted"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1localMuted\/title","value":"AgoraAudioRemoteReasonLocalMuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1localMuted\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonLocalMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1networkCongestion\/title","value":"AgoraAudioRemoteReasonNetworkCongestion"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1networkCongestion\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkCongestion"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason\/title","value":"AgoraAudioRemoteReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1remoteUnmuted\/title","value":"AgoraAudioRemoteReasonRemoteUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1remoteUnmuted\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonRemoteUnmuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1localUnmuted\/title","value":"AgoraAudioRemoteReasonLocalUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1localUnmuted\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonLocalUnmuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1internal\/title","value":"AgoraAudioRemoteReasonInternal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1internal\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonInternal"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1networkRecovery\/title","value":"AgoraAudioRemoteReasonNetworkRecovery"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1networkRecovery\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonNetworkRecovery"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1remoteMuted\/title","value":"AgoraAudioRemoteReasonRemoteMuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1remoteMuted\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonRemoteMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1remoteOffline\/title","value":"AgoraAudioRemoteReasonRemoteOffline"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteReason~1remoteOffline\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteReasonRemoteOffline"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}