{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioprocesschannels"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioprocesschannels"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The number of channels for audio preprocessing."},{"type":"text","text":" "},{"type":"text","text":"In scenarios that require enhanced realism, such as concerts, local users"},{"type":"text","text":" "},{"type":"text","text":"might need to capture stereo audio and send stereo signals to remote users."},{"type":"text","text":" "},{"type":"text","text":"For example, the singer, guitarist, and drummer are standing in different"},{"type":"text","text":" "},{"type":"text","text":"positions on the stage. The audio capture device captures their stereo audio"},{"type":"text","text":" "},{"type":"text","text":"and sends stereo signals to remote users. Remote users can hear the song,"},{"type":"text","text":" "},{"type":"text","text":"guitar, and drum from different directions as if they were at the"},{"type":"text","text":" "},{"type":"text","text":"auditorium.You can set the dual-channel processing to implement stereo audio"},{"type":"text","text":" "},{"type":"text","text":"in this class. Agora recommends the following settings:Preprocessing: call"},{"type":"text","text":" "},{"type":"text","text":"setAdvancedAudioOptions and set audioProcessingChannels to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAdvancedAudioOptions (2) in"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProcessChannelsStereo.Post-processing: call setAudioProfile [2\/2]"},{"type":"text","text":" "},{"type":"text","text":"profile to AgoraAudioProfileMusicStandardStereo (3) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo (5).The stereo setting only takes"},{"type":"text","text":" "},{"type":"text","text":"effect when the SDK uses the media volume.  On iOS, stereo audio requires"},{"type":"text","text":" "},{"type":"text","text":"high device performance. Stereo audio is only supported on the following"},{"type":"text","text":" "},{"type":"text","text":"devices using iOS 14.0 and later:iPhone XSiPhone XS MaxiPhone XRiPhone"},{"type":"text","text":" "},{"type":"text","text":"11iPhone 11 ProiPhone 11 Pro MaxiPhone SE (2020)iPad Pro 11” and 12.9” (3rd"},{"type":"text","text":" "},{"type":"text","text":"generation)iPad Pro 11” and 12.9” (4th generation)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"title":"AgoraAudioProcessChannels","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioProcessChannels","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelsMono","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelstereo"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels":{"role":"symbol","title":"AgoraAudioProcessChannels","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"abstract":[{"type":"text","text":"The number of channels for audio preprocessing."},{"type":"text","text":" "},{"type":"text","text":"In scenarios that require enhanced realism, such as concerts, local users"},{"type":"text","text":" "},{"type":"text","text":"might need to capture stereo audio and send stereo signals to remote users."},{"type":"text","text":" "},{"type":"text","text":"For example, the singer, guitarist, and drummer are standing in different"},{"type":"text","text":" "},{"type":"text","text":"positions on the stage. The audio capture device captures their stereo audio"},{"type":"text","text":" "},{"type":"text","text":"and sends stereo signals to remote users. Remote users can hear the song,"},{"type":"text","text":" "},{"type":"text","text":"guitar, and drum from different directions as if they were at the"},{"type":"text","text":" "},{"type":"text","text":"auditorium.You can set the dual-channel processing to implement stereo audio"},{"type":"text","text":" "},{"type":"text","text":"in this class. Agora recommends the following settings:Preprocessing: call"},{"type":"text","text":" "},{"type":"text","text":"setAdvancedAudioOptions and set audioProcessingChannels to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAdvancedAudioOptions (2) in"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProcessChannelsStereo.Post-processing: call setAudioProfile [2\/2]"},{"type":"text","text":" "},{"type":"text","text":"profile to AgoraAudioProfileMusicStandardStereo (3) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo (5).The stereo setting only takes"},{"type":"text","text":" "},{"type":"text","text":"effect when the SDK uses the media volume.  On iOS, stereo audio requires"},{"type":"text","text":" "},{"type":"text","text":"high device performance. Stereo audio is only supported on the following"},{"type":"text","text":" "},{"type":"text","text":"devices using iOS 14.0 and later:iPhone XSiPhone XS MaxiPhone XRiPhone"},{"type":"text","text":" "},{"type":"text","text":"11iPhone 11 ProiPhone 11 Pro MaxiPhone SE (2020)iPad Pro 11” and 12.9” (3rd"},{"type":"text","text":" "},{"type":"text","text":"generation)iPad Pro 11” and 12.9” (4th generation)"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}],"url":"\/documentation\/agorartckit\/agoraaudioprocesschannels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels/channelstereo":{"role":"symbol","title":"AgoraAudioProcessChannels.channelstereo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelstereo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelstereo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannelstereo"}],"url":"\/documentation\/agorartckit\/agoraaudioprocesschannels\/channelstereo"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels/channelsMono":{"role":"symbol","title":"AgoraAudioProcessChannels.channelsMono","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelsMono"}],"abstract":[{"type":"text","text":"1: (Default) Mono."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelsMono","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioProcessChannelsMono"}],"url":"\/documentation\/agorartckit\/agoraaudioprocesschannels\/channelsmono"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioprocesschannels\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioprocesschannels\/equatable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioProcessChannels/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioprocesschannels\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioProcessChannels"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelsMono","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioProcessChannels\/channelstereo"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioProcessChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels\/title","value":"AgoraAudioProcessChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels~1channelstereo\/title","value":"AgoraAudioProcessChannelstereo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels~1channelstereo\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannelstereo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels~1channelsMono\/title","value":"AgoraAudioProcessChannelsMono"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioProcessChannels~1channelsMono\/fragments","value":[{"kind":"identifier","text":"AgoraAudioProcessChannelsMono"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}