{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediastreaminfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediastreaminfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The detailed information of the media stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}],"title":"AgoraRtcMediaStreamInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRtcMediaStreamInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/audioChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/audioSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/codecName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/duration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/language","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/rotation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/streamIndex","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/streamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoBitRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoHeight","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoWidth"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/videoHeight":{"role":"symbol","title":"videoHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This parameter only takes effect for video streams, and indicates the video height (pixel)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoHeight"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/videoheight"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The total duration (s) of the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/duration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/videoWidth":{"role":"symbol","title":"videoWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This parameter only takes effect for video streams, and indicates the video width (pixel)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoWidth"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/videowidth"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/audioSampleRate":{"role":"symbol","title":"audioSampleRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This parameter only takes effect for audio streams, and indicates the audio sample rate (Hz)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/audioSampleRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioSampleRate"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/audiosamplerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/rotation":{"role":"symbol","title":"rotation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This parameter only takes effect for video streams, and indicates the video rotation angle."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/rotation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rotation"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/rotation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/videoFrameRate":{"role":"symbol","title":"videoFrameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This parameter only takes effect for video streams, and indicates the video frame rate (fps)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoFrameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoFrameRate"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/videoframerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/audioChannels":{"role":"symbol","title":"audioChannels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This parameter only takes effect for audio streams, and indicates the audio channel number."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/audioChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioChannels"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/audiochannels"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/codecName":{"role":"symbol","title":"codecName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The codec of the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/codecName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecName"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/codecname"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/streamType":{"role":"symbol","title":"streamType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaStreamType","preciseIdentifier":"c:@E@AgoraMediaStreamType"}],"abstract":[{"type":"text","text":"The type of the media stream. See AgoraMediaStreamType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/streamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"streamType"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/streamtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/videoBitRate":{"role":"symbol","title":"videoBitRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoBitRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"This parameter only takes effect for video streams, and indicates the video bitrate (bps)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoBitRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoBitRate"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/videobitrate"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/language":{"role":"symbol","title":"language","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The language of the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/language","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"language"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/language"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo/streamIndex":{"role":"symbol","title":"streamIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The index of the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/streamIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"streamIndex"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo\/streamindex"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaStreamInfo":{"role":"symbol","title":"AgoraRtcMediaStreamInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}],"abstract":[{"type":"text","text":"The detailed information of the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}],"url":"\/documentation\/agorartckit\/agorartcmediastreaminfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcMediaStreamInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/audioChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/audioSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/codecName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/duration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/language","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/rotation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/streamIndex","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/streamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoBitRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoHeight","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaStreamInfo\/videoWidth"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoHeight\/title","value":"videoHeight"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoHeight\/fragments","value":[{"kind":"identifier","text":"videoHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoWidth\/title","value":"videoWidth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoWidth\/fragments","value":[{"kind":"identifier","text":"videoWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1audioSampleRate\/title","value":"audioSampleRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1audioSampleRate\/fragments","value":[{"kind":"identifier","text":"audioSampleRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1rotation\/title","value":"rotation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1rotation\/fragments","value":[{"kind":"identifier","text":"rotation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoFrameRate\/title","value":"videoFrameRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoFrameRate\/fragments","value":[{"kind":"identifier","text":"videoFrameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1audioChannels\/title","value":"audioChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1audioChannels\/fragments","value":[{"kind":"identifier","text":"audioChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1codecName\/title","value":"codecName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1codecName\/fragments","value":[{"kind":"identifier","text":"codecName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1streamType\/title","value":"streamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1streamType\/fragments","value":[{"kind":"identifier","text":"streamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoBitRate\/title","value":"videoBitRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1videoBitRate\/fragments","value":[{"kind":"identifier","text":"videoBitRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1language\/title","value":"language"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1language\/fragments","value":[{"kind":"identifier","text":"language"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1streamIndex\/title","value":"streamIndex"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo~1streamIndex\/fragments","value":[{"kind":"identifier","text":"streamIndex"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo\/title","value":"AgoraRtcMediaStreamInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaStreamInfo\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaStreamInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}