{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration of cross channel media relay."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"title":"AgoraChannelMediaRelayConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChannelMediaRelayConfiguration","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/destinationInfos","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/sourceInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/removeDestinationInfo(forChannelName:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/setDestinationInfo(_:forChannelName:)"]}],"references":{"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration/removeDestinationInfo(forChannelName:)":{"role":"symbol","title":"removeDestinationInfo(forChannelName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDestinationInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Deletes the information of target channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/removeDestinationInfo(forChannelName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeDestinationInfoForChannelName:"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/removedestinationinfo(forchannelname:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration":{"role":"symbol","title":"AgoraChannelMediaRelayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"abstract":[{"type":"text","text":"Configuration of cross channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration/sourceInfo":{"role":"symbol","title":"sourceInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo"}],"abstract":[{"type":"text","text":"The information of the source channel. See AgoraChannelMediaRelayInfo . It"},{"type":"text","text":" "},{"type":"text","text":"contains the following members:channelName: The name of the source channel."},{"type":"text","text":" "},{"type":"text","text":"The default value is nil, which means the SDK applies the name of the current"},{"type":"text","text":" "},{"type":"text","text":"channel.token: The token for joining the source channel. This token is"},{"type":"text","text":" "},{"type":"text","text":"generated with the channelName and uid you set in srcInfo.If you have not"},{"type":"text","text":" "},{"type":"text","text":"enabled the App Certificate, set this parameter as the default value nil,"},{"type":"text","text":" "},{"type":"text","text":"which means the SDK applies the App ID.If you have enabled the App"},{"type":"text","text":" "},{"type":"text","text":"Certificate, you must use the token generated with the channelName and uid,"},{"type":"text","text":" "},{"type":"text","text":"and the uid must be set as 0.uid: The unique user ID to identify the relay"},{"type":"text","text":" "},{"type":"text","text":"stream in the source channel. Agora recommends leaving the default value of 0"},{"type":"text","text":" "},{"type":"text","text":"unchanged."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/sourceInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sourceInfo"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/sourceinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration/setDestinationInfo(_:forChannelName:)":{"role":"symbol","title":"setDestinationInfo(_:forChannelName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDestinationInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets the information of the target channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/setDestinationInfo(_:forChannelName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDestinationInfo:forChannelName:"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/setdestinationinfo(_:forchannelname:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration/destinationInfos":{"role":"symbol","title":"destinationInfos","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"destinationInfos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The information of the target channel AgoraChannelMediaRelayInfo. It contains"},{"type":"text","text":" "},{"type":"text","text":"the following members:channelName: The name of the target channel.token: The"},{"type":"text","text":" "},{"type":"text","text":"token for joining the target channel. It is generated with the channelName"},{"type":"text","text":" "},{"type":"text","text":"and uid you set in destInfos.If you have not enabled the App Certificate, set"},{"type":"text","text":" "},{"type":"text","text":"this parameter as the default value nil, which means the SDK applies the App"},{"type":"text","text":" "},{"type":"text","text":"ID.If you have enabled the App Certificate, you must use the token generated"},{"type":"text","text":" "},{"type":"text","text":"with the channelName and uid.If the token of any target channel expires, the"},{"type":"text","text":" "},{"type":"text","text":"whole media relay stops; hence Agora recommends that you specify the same"},{"type":"text","text":" "},{"type":"text","text":"expiration time for the tokens of all the target channels.uid: The unique"},{"type":"text","text":" "},{"type":"text","text":"user ID to identify the relay stream in the target channel. The value ranges"},{"type":"text","text":" "},{"type":"text","text":"from 0 to (2 32-1). To avoid user ID conflicts, this user ID must be"},{"type":"text","text":" "},{"type":"text","text":"different from any other user ID in the target channel. The default value is"},{"type":"text","text":" "},{"type":"text","text":"0, which means the SDK generates a random user ID."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/destinationInfos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"destinationInfos"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/destinationinfos"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelMediaRelayConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/destinationInfos","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/sourceInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/removeDestinationInfo(forChannelName:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/setDestinationInfo(_:forChannelName:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1removeDestinationInfo(forChannelName:)\/title","value":"removeDestinationInfoForChannelName:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1removeDestinationInfo(forChannelName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDestinationInfoForChannelName:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/title","value":"AgoraChannelMediaRelayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1sourceInfo\/title","value":"sourceInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1sourceInfo\/fragments","value":[{"kind":"identifier","text":"sourceInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1setDestinationInfo(_:forChannelName:)\/title","value":"setDestinationInfo:forChannelName:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1setDestinationInfo(_:forChannelName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDestinationInfo:forChannelName:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1destinationInfos\/title","value":"destinationInfos"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1destinationInfos\/fragments","value":[{"kind":"identifier","text":"destinationInfos"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}