{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiodualmonomode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiodualmonomode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The channel mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"title":"AgoraAudioDualMonoMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioDualMonoMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/L","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/R","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/mix","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/stereo"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode":{"role":"symbol","title":"AgoraAudioDualMonoMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"abstract":[{"type":"text","text":"The channel mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/L":{"role":"symbol","title":"AgoraAudioDualMonoMode.L","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"L"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/L","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoL"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/l"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/stereo":{"role":"symbol","title":"AgoraAudioDualMonoMode.stereo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stereo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/stereo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoStereo"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/stereo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/mix":{"role":"symbol","title":"AgoraAudioDualMonoMode.mix","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/mix","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoMix"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/mix"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/R":{"role":"symbol","title":"AgoraAudioDualMonoMode.R","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"R"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/R","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioDualMonoR"}],"url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/r"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioDualMonoMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiodualmonomode\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioDualMonoMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/L","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/R","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/mix","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioDualMonoMode\/stereo"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioDualMonoMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/title","value":"AgoraAudioDualMonoMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1L\/title","value":"AgoraAudioDualMonoL"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1L\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoL"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1stereo\/title","value":"AgoraAudioDualMonoStereo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1stereo\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoStereo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1mix\/title","value":"AgoraAudioDualMonoMix"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1mix\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoMix"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1R\/title","value":"AgoraAudioDualMonoR"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioDualMonoMode~1R\/fragments","value":[{"kind":"identifier","text":"AgoraAudioDualMonoR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}