{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodedaudioframeinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodedaudioframeinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio information after encoding."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"title":"AgoraEncodedAudioFrameInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraEncodedAudioFrameInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/channels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/codecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/samplesPerChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/samplesPerSec"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo/codecType":{"role":"symbol","title":"codecType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioCodecType","preciseIdentifier":"c:@E@AgoraAudioCodecType"}],"abstract":[{"type":"text","text":"Audio Codec type: AgoraAudioCodecType"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/codecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecType"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo\/codectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo/samplesPerSec":{"role":"symbol","title":"samplesPerSec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"samplesPerSec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Audio sample rate (Hz)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/samplesPerSec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"samplesPerSec"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo\/samplespersec"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo/samplesPerChannel":{"role":"symbol","title":"samplesPerChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"samplesPerChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of audio samples per channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/samplesPerChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"samplesPerChannel"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo\/samplesperchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo/channels":{"role":"symbol","title":"channels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of audio channels."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/channels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channels"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo\/channels"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedAudioFrameInfo":{"role":"symbol","title":"AgoraEncodedAudioFrameInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"abstract":[{"type":"text","text":"Audio information after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}],"url":"\/documentation\/agorartckit\/agoraencodedaudioframeinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncodedAudioFrameInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/channels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/codecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/samplesPerChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedAudioFrameInfo\/samplesPerSec"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1codecType\/title","value":"codecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1codecType\/fragments","value":[{"kind":"identifier","text":"codecType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1samplesPerSec\/title","value":"samplesPerSec"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1samplesPerSec\/fragments","value":[{"kind":"identifier","text":"samplesPerSec"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1samplesPerChannel\/title","value":"samplesPerChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1samplesPerChannel\/fragments","value":[{"kind":"identifier","text":"samplesPerChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1channels\/title","value":"channels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo~1channels\/fragments","value":[{"kind":"identifier","text":"channels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo\/title","value":"AgoraEncodedAudioFrameInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedAudioFrameInfo\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedAudioFrameInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}