{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated: Deprecated as of v3.2.0."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioreverbpreset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioreverbpreset"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Voice reverb presets."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"title":"AgoraAudioReverbPreset","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioReverbPreset","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxKTV","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxPhonograph","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxPopular","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxRNB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxSister","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxStudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxUncle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxVocalConcert","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/off"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxRNB":{"role":"symbol","title":"AgoraAudioReverbPreset.fxRNB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxRNB"}],"abstract":[{"type":"text","text":"The reverb style typical of R&B music (enhanced)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxRNB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxRNB"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxrnb"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/rawrepresentable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxPhonograph":{"role":"symbol","title":"AgoraAudioReverbPreset.fxPhonograph","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxPhonograph"}],"abstract":[{"type":"text","text":"The voice effect typical of a vintage phonograph."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxPhonograph","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxPhonograph"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxphonograph"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxKTV":{"role":"symbol","title":"AgoraAudioReverbPreset.fxKTV","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxKTV"}],"abstract":[{"type":"text","text":"The reverb style typical of a KTV venue (enhanced)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxKTV","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxKTV"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxktv"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset":{"role":"symbol","title":"AgoraAudioReverbPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"abstract":[{"type":"text","text":"Voice reverb presets."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/off":{"role":"symbol","title":"AgoraAudioReverbPreset.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"Turn off voice reverb, that is, to use the original voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetOff"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/off"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxVocalConcert":{"role":"symbol","title":"AgoraAudioReverbPreset.fxVocalConcert","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxVocalConcert"}],"abstract":[{"type":"text","text":"The reverb style typical of a concert hall (enhanced)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxVocalConcert","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxVocalConcert"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxvocalconcert"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxPopular":{"role":"symbol","title":"AgoraAudioReverbPreset.fxPopular","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxPopular"}],"abstract":[{"type":"text","text":"The reverb style typical of popular music (enhanced)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxPopular","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxPopular"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxpopular"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxStudio":{"role":"symbol","title":"AgoraAudioReverbPreset.fxStudio","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxStudio"}],"abstract":[{"type":"text","text":"The reverb style typical of a recording studio (enhanced)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxStudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxStudio"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxstudio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxSister":{"role":"symbol","title":"AgoraAudioReverbPreset.fxSister","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxSister"}],"abstract":[{"type":"text","text":"The reverb style typical of a young woman’s voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxSister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxSister"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxsister"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbPreset/fxUncle":{"role":"symbol","title":"AgoraAudioReverbPreset.fxUncle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fxUncle"}],"abstract":[{"type":"text","text":"A middle-aged man’s voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxUncle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxUncle"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbpreset\/fxuncle"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioReverbPreset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxKTV","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxPhonograph","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxPopular","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxRNB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxSister","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxStudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxUncle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/fxVocalConcert","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbPreset\/off"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxRNB\/title","value":"AgoraAudioReverbPresetFxRNB"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxRNB\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxRNB"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxPhonograph\/title","value":"AgoraAudioReverbPresetFxPhonograph"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxPhonograph\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxPhonograph"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxKTV\/title","value":"AgoraAudioReverbPresetFxKTV"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxKTV\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxKTV"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset\/title","value":"AgoraAudioReverbPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1off\/title","value":"AgoraAudioReverbPresetOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1off\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetOff"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxVocalConcert\/title","value":"AgoraAudioReverbPresetFxVocalConcert"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxVocalConcert\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxVocalConcert"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxPopular\/title","value":"AgoraAudioReverbPresetFxPopular"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxPopular\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxPopular"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxStudio\/title","value":"AgoraAudioReverbPresetFxStudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxStudio\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxStudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxSister\/title","value":"AgoraAudioReverbPresetFxSister"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxSister\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxSister"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxUncle\/title","value":"AgoraAudioReverbPresetFxUncle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbPreset~1fxUncle\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbPresetFxUncle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}