{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since v4.1.1"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideorenderingtracinginfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideorenderingtracinginfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicators during video frame rendering progress."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"title":"AgoraVideoRenderingTracingInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraVideoRenderingTracingInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/elapsedTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/join2JoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/joinSuccess2RemoteJoined","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2PacketReceived","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2SetView","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2UnmuteVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/start2JoinChannel"]}],"references":{"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/remoteJoined2SetView":{"role":"symbol","title":"remoteJoined2SetView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoined2SetView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"If the local user calls startMediaRenderingTracing before the remote user joins the channel, this value is the time interval from when the remote user joins the channel to when the local user sets the remote view. The unit is milliseconds.If the local user calls startMediaRenderingTracing after the remote user joins the channel, this value is the time interval from calling startMediaRenderingTracing to setting the remote view. The unit is milliseconds.If the local user calls startMediaRenderingTracing after setting the remote view, the value is 0 and has no effect.In order to reduce the time of rendering the first frame for remote users, Agora recommends that the local user sets the remote view before the remote user joins the channel, or sets the remote view immediately after the remote user joins the channel to reduce this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2SetView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteJoined2SetView"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/remotejoined2setview"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/remoteJoined2UnmuteVideo":{"role":"symbol","title":"remoteJoined2UnmuteVideo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoined2UnmuteVideo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"If the local user calls startMediaRenderingTracing before the remote user joins the channel, this value is the time interval from the remote user joining the channel to subscribing to the remote video stream. The unit is milliseconds.If the local user calls startMediaRenderingTracing after the remote user joins the channel, this value is the time interval from calling startMediaRenderingTracing to subscribing to the remote video stream. The unit is milliseconds.If the local user calls startMediaRenderingTracing after subscribing to the remote video stream, the value is 0 and has no effect.In order to reduce the time of rendering the first frame for remote users, Agora recommends that after the remote user joins the channel, the local user immediately subscribes to the remote video stream to reduce this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2UnmuteVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteJoined2UnmuteVideo"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/remotejoined2unmutevideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/elapsedTime":{"role":"symbol","title":"elapsedTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elapsedTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The time interval from calling the startMediaRenderingTracing method to SDK triggering the videoRenderingTracingResultOfUid callback. The unit is milliseconds. Agora recommends you call startMediaRenderingTracing before joining a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/elapsedTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"elapsedTime"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/elapsedtime"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/joinSuccess2RemoteJoined":{"role":"symbol","title":"joinSuccess2RemoteJoined","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinSuccess2RemoteJoined"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"If the local user calls startMediaRenderingTracing before successfully joining the channel, this value is the time interval from the local user successfully joining the channel to the remote user joining the channel. The unit is milliseconds.If the local user calls startMediaRenderingTracing after successfully joining the channel, the value is the time interval from calling startMediaRenderingTracing to when the remote user joins the channel. The unit is milliseconds.If the local user calls startMediaRenderingTracing after the remote user joins the channel, the value is 0 and meaningless.In order to reduce the time of rendering the first frame for remote users, Agora recommends that the local user joins the channel when the remote user is in the channel to reduce this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/joinSuccess2RemoteJoined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinSuccess2RemoteJoined"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/joinsuccess2remotejoined"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/remoteJoined2PacketReceived":{"role":"symbol","title":"remoteJoined2PacketReceived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoined2PacketReceived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"If the local user calls startMediaRenderingTracing before the remote user joins the channel, this value is the time interval from when the remote user joins the channel to when the local user receives the remote video stream. The unit is milliseconds.If the local user calls startMediaRenderingTracing after the remote user joins the channel, this value is the time interval from calling startMediaRenderingTracing to receiving the remote video stream. The unit is milliseconds.If the local user calls startMediaRenderingTracing after receiving the remote video stream, the value is 0 and has no effect.In order to reduce the time of rendering the first frame for remote users, Agora recommends that the remote user publishes video streams immediately after joining the channel, and the local user immediately subscribes to remote video streams to reduce this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2PacketReceived","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteJoined2PacketReceived"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/remotejoined2packetreceived"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/join2JoinSuccess":{"role":"symbol","title":"join2JoinSuccess","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"join2JoinSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Time interval from calling joinChannelByToken [2\/4] to successfully joining the channel. The unit is milliseconds."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/join2JoinSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"join2JoinSuccess"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/join2joinsuccess"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo/start2JoinChannel":{"role":"symbol","title":"start2JoinChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"start2JoinChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The time interval from calling startMediaRenderingTracing to calling joinChannelByToken [2\/4]. The unit is milliseconds. A negative number means to call joinChannelByToken [2\/4] after calling startMediaRenderingTracing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/start2JoinChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start2JoinChannel"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo\/start2joinchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderingTracingInfo":{"role":"symbol","title":"AgoraVideoRenderingTracingInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"abstract":[{"type":"text","text":"Indicators during video frame rendering progress."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}],"url":"\/documentation\/agorartckit\/agoravideorenderingtracinginfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoRenderingTracingInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/elapsedTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/join2JoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/joinSuccess2RemoteJoined","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2PacketReceived","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2SetView","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/remoteJoined2UnmuteVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderingTracingInfo\/start2JoinChannel"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2SetView\/title","value":"remoteJoined2SetView"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2SetView\/fragments","value":[{"kind":"identifier","text":"remoteJoined2SetView"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2UnmuteVideo\/title","value":"remoteJoined2UnmuteVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2UnmuteVideo\/fragments","value":[{"kind":"identifier","text":"remoteJoined2UnmuteVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1elapsedTime\/title","value":"elapsedTime"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1elapsedTime\/fragments","value":[{"kind":"identifier","text":"elapsedTime"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1joinSuccess2RemoteJoined\/title","value":"joinSuccess2RemoteJoined"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1joinSuccess2RemoteJoined\/fragments","value":[{"kind":"identifier","text":"joinSuccess2RemoteJoined"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2PacketReceived\/title","value":"remoteJoined2PacketReceived"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1remoteJoined2PacketReceived\/fragments","value":[{"kind":"identifier","text":"remoteJoined2PacketReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1join2JoinSuccess\/title","value":"join2JoinSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1join2JoinSuccess\/fragments","value":[{"kind":"identifier","text":"join2JoinSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1start2JoinChannel\/title","value":"start2JoinChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo~1start2JoinChannel\/fragments","value":[{"kind":"identifier","text":"start2JoinChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/title","value":"AgoraVideoRenderingTracingInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderingTracingInfo\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderingTracingInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}