{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onEnableTranscode(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onQueryChannel(_:originChannel:transcodeChannel:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onTriggerTranscode(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}],"title":"AgoraH265TranscoderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraH265TranscoderDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderDelegate/onQueryChannel(_:originChannel:transcodeChannel:)":{"role":"symbol","title":"onQueryChannel(_:originChannel:transcodeChannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onQueryChannel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscodeResult","preciseIdentifier":"c:@E@AgoraH265TranscodeResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"originChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"transcodeChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onQueryChannel(_:originChannel:transcodeChannel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onQueryChannel:originChannel:transcodeChannel:"}],"url":"\/documentation\/agorartckit\/agorah265transcoderdelegate\/onquerychannel(_:originchannel:transcodechannel:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderDelegate/onTriggerTranscode(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onTriggerTranscode:"}],"role":"symbol","title":"onTriggerTranscode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTriggerTranscode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscodeResult","preciseIdentifier":"c:@E@AgoraH265TranscodeResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onTriggerTranscode(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderdelegate\/ontriggertranscode(_:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderDelegate":{"role":"symbol","title":"AgoraH265TranscoderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}],"url":"\/documentation\/agorartckit\/agorah265transcoderdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderDelegate/onEnableTranscode(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onEnableTranscode:"}],"role":"symbol","title":"onEnableTranscode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEnableTranscode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscodeResult","preciseIdentifier":"c:@E@AgoraH265TranscodeResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onEnableTranscode(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderdelegate\/onenabletranscode(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraH265TranscoderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onEnableTranscode(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onQueryChannel(_:originChannel:transcodeChannel:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onTriggerTranscode(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onQueryChannel(_:originChannel:transcodeChannel:)\/title","value":"onQueryChannel:originChannel:transcodeChannel:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onQueryChannel(_:originChannel:transcodeChannel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onQueryChannel:originChannel:transcodeChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onTriggerTranscode(_:)\/title","value":"onTriggerTranscode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onTriggerTranscode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTriggerTranscode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate\/title","value":"AgoraH265TranscoderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onEnableTranscode(_:)\/title","value":"onEnableTranscode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onEnableTranscode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEnableTranscode:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}