{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioremotestate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioremotestate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Remote audio states."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteState"}],"title":"AgoraAudioRemoteState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioRemoteState","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteState"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/decoding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/frozen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/starting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/stopped"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState":{"role":"symbol","title":"AgoraAudioRemoteState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteState"}],"abstract":[{"type":"text","text":"Remote audio states."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteState"}],"url":"\/documentation\/agorartckit\/agoraaudioremotestate"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/frozen":{"role":"symbol","title":"AgoraAudioRemoteState.frozen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"frozen"}],"abstract":[{"type":"text","text":"3: The remote audio is frozen. The SDK reports this state in the case of"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioRemoteReasonNetworkCongestion."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/frozen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteStateFrozen"}],"url":"\/documentation\/agorartckit\/agoraaudioremotestate\/frozen"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/failed":{"role":"symbol","title":"AgoraAudioRemoteState.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"4: The remote audio fails to start. The SDK reports this state in the case"},{"type":"text","text":" "},{"type":"text","text":"of AgoraAudioRemoteReasonInternal."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteStateFailed"}],"url":"\/documentation\/agorartckit\/agoraaudioremotestate\/failed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioremotestate\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioremotestate\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioremotestate\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/decoding":{"role":"symbol","title":"AgoraAudioRemoteState.decoding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoding"}],"abstract":[{"type":"text","text":"2: The remote audio stream is decoded and plays normally. The SDK reports"},{"type":"text","text":" "},{"type":"text","text":"this state in the case of AgoraAudioRemoteReasonNetworkRecovery,"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioRemoteReasonLocalUnmuted or AgoraAudioRemoteReasonRemoteUnmuted."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/decoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteStateDecoding"}],"url":"\/documentation\/agorartckit\/agoraaudioremotestate\/decoding"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/starting":{"role":"symbol","title":"AgoraAudioRemoteState.starting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"starting"}],"abstract":[{"type":"text","text":"1: The first remote audio packet is received."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/starting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteStateStarting"}],"url":"\/documentation\/agorartckit\/agoraaudioremotestate\/starting"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRemoteState/stopped":{"role":"symbol","title":"AgoraAudioRemoteState.stopped","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"abstract":[{"type":"text","text":"0: The local audio is in the initial state. The SDK reports this state in"},{"type":"text","text":" "},{"type":"text","text":"the case of AgoraAudioRemoteReasonLocalMuted,"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioRemoteReasonRemoteMuted or AgoraAudioRemoteReasonRemoteOffline."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/stopped","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRemoteStateStopped"}],"url":"\/documentation\/agorartckit\/agoraaudioremotestate\/stopped"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioRemoteState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioRemoteState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/decoding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/frozen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/starting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRemoteState\/stopped"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRemoteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState\/title","value":"AgoraAudioRemoteState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1frozen\/title","value":"AgoraAudioRemoteStateFrozen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1frozen\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteStateFrozen"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1failed\/title","value":"AgoraAudioRemoteStateFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteStateFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1decoding\/title","value":"AgoraAudioRemoteStateDecoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1decoding\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteStateDecoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1starting\/title","value":"AgoraAudioRemoteStateStarting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1starting\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteStateStarting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1stopped\/title","value":"AgoraAudioRemoteStateStopped"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRemoteState~1stopped\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRemoteStateStopped"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}