{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceConversionPreset"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravoiceconversionpreset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravoiceconversionpreset"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The options for SDK preset voice conversion effects."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceConversionPreset"}],"title":"AgoraVoiceConversionPreset","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVoiceConversionPreset","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPreset"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerBass","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerCartoon","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerChildlike","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerChipmunk","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerDarthVader","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerGirlishMan","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerGroot","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerIronLady","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerMonster","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerPhoneOperator","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerShinchan","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerSolid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerTransformers","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/neutral","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/off","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/sweet"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerCartoon":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerCartoon","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerCartoon"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerCartoon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerCartoon"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changercartoon"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerChildlike":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerChildlike","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerChildlike"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerChildlike","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerChildlike"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changerchildlike"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerIronLady":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerIronLady","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerIronLady"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerIronLady","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerIronLady"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changerironlady"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/sweet":{"role":"symbol","title":"AgoraVoiceConversionPreset.sweet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sweet"}],"abstract":[{"type":"text","text":"A sweet voice. To avoid audio distortion, ensure that you use this enumerator to process a female-sounding voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/sweet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetSweet"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/sweet"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/neutral":{"role":"symbol","title":"AgoraVoiceConversionPreset.neutral","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"neutral"}],"abstract":[{"type":"text","text":"A gender-neutral voice. To avoid audio distortion, ensure that you use this enumerator to process a female-sounding voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/neutral","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetNeutral"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/neutral"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerDarthVader":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerDarthVader","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerDarthVader"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerDarthVader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerDarthVader"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changerdarthvader"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerChipmunk":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerChipmunk","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerChipmunk"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerChipmunk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerChipmunk"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changerchipmunk"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerMonster":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerMonster","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerMonster"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerMonster","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerMonster"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changermonster"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerBass":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerBass","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerBass"}],"abstract":[{"type":"text","text":"A deep voice. To avoid audio distortion, ensure that you use this enumerator to process a male-sounding voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerBass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerBass"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changerbass"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerGirlishMan":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerGirlishMan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerGirlishMan"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerGirlishMan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerGirlishMan"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changergirlishman"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerPhoneOperator":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerPhoneOperator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerPhoneOperator"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerPhoneOperator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerPhoneOperator"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changerphoneoperator"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset":{"role":"symbol","title":"AgoraVoiceConversionPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceConversionPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice conversion effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPreset"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerGroot":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerGroot","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerGroot"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerGroot","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerGroot"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changergroot"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerTransformers":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerTransformers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerTransformers"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerTransformers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerTransformers"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changertransformers"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerSolid":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerSolid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerSolid"}],"abstract":[{"type":"text","text":"A steady voice. To avoid audio distortion, ensure that you use this enumerator to process a male-sounding voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerSolid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerSolid"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changersolid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/off":{"role":"symbol","title":"AgoraVoiceConversionPreset.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"Turn off voice conversion effects and use the original voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetOff"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/off"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceConversionPreset/changerShinchan":{"role":"symbol","title":"AgoraVoiceConversionPreset.changerShinchan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changerShinchan"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerShinchan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerShinchan"}],"url":"\/documentation\/agorartckit\/agoravoiceconversionpreset\/changershinchan"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVoiceConversionPreset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPreset"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVoiceConversionPreset"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerBass","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerCartoon","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerChildlike","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerChipmunk","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerDarthVader","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerGirlishMan","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerGroot","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerIronLady","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerMonster","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerPhoneOperator","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerShinchan","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerSolid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/changerTransformers","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/neutral","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/off","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceConversionPreset\/sweet"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceConversionPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerCartoon\/title","value":"AgoraVoiceConversionPresetChangerCartoon"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerCartoon\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerCartoon"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerChildlike\/title","value":"AgoraVoiceConversionPresetChangerChildlike"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerChildlike\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerChildlike"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerIronLady\/title","value":"AgoraVoiceConversionPresetChangerIronLady"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerIronLady\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerIronLady"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1sweet\/title","value":"AgoraVoiceConversionPresetSweet"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1sweet\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetSweet"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1neutral\/title","value":"AgoraVoiceConversionPresetNeutral"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1neutral\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetNeutral"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerDarthVader\/title","value":"AgoraVoiceConversionPresetChangerDarthVader"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerDarthVader\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerDarthVader"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerChipmunk\/title","value":"AgoraVoiceConversionPresetChangerChipmunk"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerChipmunk\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerChipmunk"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerMonster\/title","value":"AgoraVoiceConversionPresetChangerMonster"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerMonster\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerMonster"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerBass\/title","value":"AgoraVoiceConversionPresetChangerBass"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerBass\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerBass"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerGirlishMan\/title","value":"AgoraVoiceConversionPresetChangerGirlishMan"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerGirlishMan\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerGirlishMan"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerPhoneOperator\/title","value":"AgoraVoiceConversionPresetChangerPhoneOperator"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerPhoneOperator\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerPhoneOperator"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset\/title","value":"AgoraVoiceConversionPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerGroot\/title","value":"AgoraVoiceConversionPresetChangerGroot"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerGroot\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerGroot"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerTransformers\/title","value":"AgoraVoiceConversionPresetChangerTransformers"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerTransformers\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerTransformers"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerSolid\/title","value":"AgoraVoiceConversionPresetChangerSolid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerSolid\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerSolid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1off\/title","value":"AgoraVoiceConversionPresetOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1off\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetOff"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerShinchan\/title","value":"AgoraVoiceConversionPresetChangerShinchan"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceConversionPreset~1changerShinchan\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceConversionPresetChangerShinchan"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}