{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The AgoraDirectCdnStreamingEventDelegate interface class is used by the SDK"},{"type":"text","text":" "},{"type":"text","text":"to send event notifications of CDN streaming to your app. Your app can get"},{"type":"text","text":" "},{"type":"text","text":"those notifications through methods that inherit this interface class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"title":"AgoraDirectCdnStreamingEventDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraDirectCdnStreamingEventDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStateChanged(_:error:message:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStats(_:)"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate":{"role":"symbol","title":"AgoraDirectCdnStreamingEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"abstract":[{"type":"text","text":"The AgoraDirectCdnStreamingEventDelegate interface class is used by the SDK"},{"type":"text","text":" "},{"type":"text","text":"to send event notifications of CDN streaming to your app. Your app can get"},{"type":"text","text":" "},{"type":"text","text":"those notifications through methods that inherit this interface class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate/onDirectCdnStreamingStats(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onDirectCdnStreamingStats:"}],"role":"symbol","title":"onDirectCdnStreamingStats(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStats"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingStats","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingStats"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reports the CDN streaming statistics."},{"type":"text","text":" "},{"type":"text","text":"When the host directly pushes media streams to the CDN, the SDK triggers this"},{"type":"text","text":" "},{"type":"text","text":"callback every one second."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStats(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstats(_:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate/onDirectCdnStreamingStateChanged(_:error:message:)":{"role":"symbol","title":"onDirectCdnStreamingStateChanged(_:error:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingState","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingError","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the CDN streaming state changes."},{"type":"text","text":" "},{"type":"text","text":"When the host directly pushes streams to the CDN, if the streaming state"},{"type":"text","text":" "},{"type":"text","text":"changes, the SDK triggers this callback to report the changed streaming"},{"type":"text","text":" "},{"type":"text","text":"state, error codes, and other information. You can troubleshoot issues by"},{"type":"text","text":" "},{"type":"text","text":"referring to this callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStateChanged(_:error:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDirectCdnStreamingStateChanged:error:message:"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstatechanged(_:error:message:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDirectCdnStreamingEventDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStateChanged(_:error:message:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStats(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/title","value":"AgoraDirectCdnStreamingEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStats(_:)\/title","value":"onDirectCdnStreamingStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStats(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDirectCdnStreamingStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStateChanged(_:error:message:)\/title","value":"onDirectCdnStreamingStateChanged:error:message:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStateChanged(_:error:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged:error:message:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}