{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclienterrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclienterrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errAlreadyJoinChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedChannelLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedCreateTopicLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedSubscribeTopicLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedUserLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errInvalidTopicName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errNotJoinChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errPublishTopicFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errTopicAlreadyExist"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientErrorCode"}],"title":"AgoraRtmClientErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraRtmClientErrorCode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errExceedUserLimitation":{"role":"symbol","title":"AgoraRtmClientErrorCode.errExceedUserLimitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errExceedUserLimitation"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedUserLimitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrExceedUserLimitation"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errexceeduserlimitation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errExceedSubscribeTopicLimitation":{"role":"symbol","title":"AgoraRtmClientErrorCode.errExceedSubscribeTopicLimitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errExceedSubscribeTopicLimitation"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedSubscribeTopicLimitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrExceedSubscribeTopicLimitation"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errexceedsubscribetopiclimitation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errTopicAlreadyExist":{"role":"symbol","title":"AgoraRtmClientErrorCode.errTopicAlreadyExist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errTopicAlreadyExist"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errTopicAlreadyExist","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrTopicAlreadyExist"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errtopicalreadyexist"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errInvalidTopicName":{"role":"symbol","title":"AgoraRtmClientErrorCode.errInvalidTopicName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errInvalidTopicName"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errInvalidTopicName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrInvalidTopicName"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errinvalidtopicname"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode":{"role":"symbol","title":"AgoraRtmClientErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientErrorCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errExceedCreateTopicLimitation":{"role":"symbol","title":"AgoraRtmClientErrorCode.errExceedCreateTopicLimitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errExceedCreateTopicLimitation"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedCreateTopicLimitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrExceedCreateTopicLimitation"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errexceedcreatetopiclimitation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errNotJoinChannel":{"role":"symbol","title":"AgoraRtmClientErrorCode.errNotJoinChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errNotJoinChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errNotJoinChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrNotJoinChannel"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errnotjoinchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errExceedChannelLimitation":{"role":"symbol","title":"AgoraRtmClientErrorCode.errExceedChannelLimitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errExceedChannelLimitation"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedChannelLimitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrExceedChannelLimitation"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errexceedchannellimitation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errAlreadyJoinChannel":{"role":"symbol","title":"AgoraRtmClientErrorCode.errAlreadyJoinChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errAlreadyJoinChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errAlreadyJoinChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrAlreadyJoinChannel"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/erralreadyjoinchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/errPublishTopicFailed":{"role":"symbol","title":"AgoraRtmClientErrorCode.errPublishTopicFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errPublishTopicFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errPublishTopicFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientErrPublishTopicFailed"}],"url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/errpublishtopicfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorartmclienterrorcode\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmClientErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtmClientErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errAlreadyJoinChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedChannelLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedCreateTopicLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedSubscribeTopicLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errExceedUserLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errInvalidTopicName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errNotJoinChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errPublishTopicFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientErrorCode\/errTopicAlreadyExist"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedUserLimitation\/title","value":"AgoraRtmClientErrExceedUserLimitation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedUserLimitation\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrExceedUserLimitation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedSubscribeTopicLimitation\/title","value":"AgoraRtmClientErrExceedSubscribeTopicLimitation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedSubscribeTopicLimitation\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrExceedSubscribeTopicLimitation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errTopicAlreadyExist\/title","value":"AgoraRtmClientErrTopicAlreadyExist"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errTopicAlreadyExist\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrTopicAlreadyExist"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errInvalidTopicName\/title","value":"AgoraRtmClientErrInvalidTopicName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errInvalidTopicName\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrInvalidTopicName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode\/title","value":"AgoraRtmClientErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedCreateTopicLimitation\/title","value":"AgoraRtmClientErrExceedCreateTopicLimitation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedCreateTopicLimitation\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrExceedCreateTopicLimitation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errNotJoinChannel\/title","value":"AgoraRtmClientErrNotJoinChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errNotJoinChannel\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrNotJoinChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedChannelLimitation\/title","value":"AgoraRtmClientErrExceedChannelLimitation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errExceedChannelLimitation\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrExceedChannelLimitation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errAlreadyJoinChannel\/title","value":"AgoraRtmClientErrAlreadyJoinChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errAlreadyJoinChannel\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrAlreadyJoinChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errPublishTopicFailed\/title","value":"AgoraRtmClientErrPublishTopicFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientErrorCode~1errPublishTopicFailed\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientErrPublishTopicFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}