{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramaxmetadatasizetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramaxmetadatasizetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/default","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/max"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"title":"AgoraMaxMetadataSizeType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraMaxMetadataSizeType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/default":{"role":"symbol","title":"AgoraMaxMetadataSizeType.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeDefault"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/default"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType":{"role":"symbol","title":"AgoraMaxMetadataSizeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/invalid":{"role":"symbol","title":"AgoraMaxMetadataSizeType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeInvalid"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/invalid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/max":{"role":"symbol","title":"AgoraMaxMetadataSizeType.max","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/max","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeMax"}],"url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/max"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMaxMetadataSizeType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramaxmetadatasizetype\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMaxMetadataSizeType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/default","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMaxMetadataSizeType\/max"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMaxMetadataSizeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1default\/title","value":"AgoraMaxMetadataSizeTypeDefault"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1default\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType\/title","value":"AgoraMaxMetadataSizeType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1invalid\/title","value":"AgoraMaxMetadataSizeTypeInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1invalid\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1max\/title","value":"AgoraMaxMetadataSizeTypeMax"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMaxMetadataSizeType~1max\/fragments","value":[{"kind":"identifier","text":"AgoraMaxMetadataSizeTypeMax"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}