{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioScenario"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioscenario"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioscenario"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The audio scenarios."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioScenario"}],"title":"AgoraAudioScenario","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioScenario","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenario"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chatRoom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chorus","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/default","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/gameStreaming","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/meeting"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario":{"role":"symbol","title":"AgoraAudioScenario","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioScenario"}],"abstract":[{"type":"text","text":"The audio scenarios."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenario"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/gameStreaming":{"role":"symbol","title":"AgoraAudioScenario.gameStreaming","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gameStreaming"}],"abstract":[{"type":"text","text":"3: High-quality audio scenario, where users mainly play music. For example, instrument tutoring."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/gameStreaming","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioGameStreaming"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/gamestreaming"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/default":{"role":"symbol","title":"AgoraAudioScenario.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"0: (Default) Automatic scenario match, where the SDK chooses the appropriate audio quality according to the user role and audio route."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioDefault"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/default"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioscenario\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/meeting":{"role":"symbol","title":"AgoraAudioScenario.meeting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"meeting"}],"abstract":[{"type":"text","text":"8: Meeting scenario that mainly contains the human voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/meeting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioMeeting"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/meeting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/chatRoom":{"role":"symbol","title":"AgoraAudioScenario.chatRoom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatRoom"}],"abstract":[{"type":"text","text":"5: Chatroom scenario, where users need to frequently switch the user role or mute and unmute the microphone. For example, education scenarios. In this scenario, audience members receive a pop-up window to request permission of using microphones."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chatRoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioChatRoom"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/chatroom"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioscenario\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/chorus":{"role":"symbol","title":"AgoraAudioScenario.chorus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chorus"}],"abstract":[{"type":"text","text":"7: Real-time chorus scenario, where users have good network conditions and require ultra-low latency."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chorus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioScenarioChorus"}],"url":"\/documentation\/agorartckit\/agoraaudioscenario\/chorus"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioScenario/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioscenario\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioScenario"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenario"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioScenario"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chatRoom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/chorus","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/default","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/gameStreaming","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioScenario\/meeting"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioScenario"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/title","value":"AgoraAudioScenario"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenario"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1gameStreaming\/title","value":"AgoraAudioScenarioGameStreaming"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1gameStreaming\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioGameStreaming"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1default\/title","value":"AgoraAudioScenarioDefault"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1default\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1meeting\/title","value":"AgoraAudioScenarioMeeting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1meeting\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioMeeting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chatRoom\/title","value":"AgoraAudioScenarioChatRoom"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chatRoom\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioChatRoom"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chorus\/title","value":"AgoraAudioScenarioChorus"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioScenario~1chorus\/fragments","value":[{"kind":"identifier","text":"AgoraAudioScenarioChorus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}