{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraPublisherConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorapublisherconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorapublisherconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiobitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiochannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiosamplerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/bitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/defaultLayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/extraInfo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/framerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamHeight","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamWidth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/lifeCycle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/owner","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/publishUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/rawStreamUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/width"]},{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/toJsonString()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/validate()"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AgoraPublisherConfiguration"}],"role":"symbol","title":"AgoraPublisherConfiguration","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraPublisherConfiguration"}],"symbolKind":"class","externalID":"c:objc(cs)AgoraPublisherConfiguration","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration":{"deprecated":true,"role":"symbol","title":"AgoraPublisherConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraPublisherConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraPublisherConfiguration"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/toJsonString()":{"deprecated":true,"role":"symbol","title":"toJsonString()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJsonString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/toJsonString()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toJsonString"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/tojsonstring()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/framerate":{"deprecated":true,"role":"symbol","title":"framerate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"framerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/framerate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"framerate"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/framerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/width":{"deprecated":true,"role":"symbol","title":"width","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/width","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"width"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/width"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/validate()":{"deprecated":true,"role":"symbol","title":"validate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/validate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validate"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/validate()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/lifeCycle":{"deprecated":true,"role":"symbol","title":"lifeCycle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lifeCycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamLifeCycle","preciseIdentifier":"c:@E@AgoraRtmpStreamLifeCycle"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/lifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lifeCycle"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/lifecycle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/defaultLayout":{"deprecated":true,"role":"symbol","title":"defaultLayout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/defaultLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultLayout"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/defaultlayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/height":{"deprecated":true,"role":"symbol","title":"height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/height","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"height"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/height"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/publishUrl":{"deprecated":true,"role":"symbol","title":"publishUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/publishUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishUrl"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/publishurl"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/audiobitrate":{"deprecated":true,"role":"symbol","title":"audiobitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audiobitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiobitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audiobitrate"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/audiobitrate"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/bitrate":{"deprecated":true,"role":"symbol","title":"bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/bitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitrate"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/bitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/extraInfo":{"deprecated":true,"role":"symbol","title":"extraInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/extraInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"extraInfo"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/extrainfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/injectStreamUrl":{"deprecated":true,"role":"symbol","title":"injectStreamUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"injectStreamUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"injectStreamUrl"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/injectstreamurl"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/rawStreamUrl":{"deprecated":true,"role":"symbol","title":"rawStreamUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawStreamUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/rawStreamUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rawStreamUrl"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/rawstreamurl"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/audiochannels":{"deprecated":true,"role":"symbol","title":"audiochannels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audiochannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiochannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audiochannels"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/audiochannels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/owner":{"deprecated":true,"role":"symbol","title":"owner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"owner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/owner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"owner"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/owner"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/audiosamplerate":{"deprecated":true,"role":"symbol","title":"audiosamplerate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audiosamplerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiosamplerate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audiosamplerate"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/audiosamplerate"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/injectStreamWidth":{"deprecated":true,"role":"symbol","title":"injectStreamWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"injectStreamWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"injectStreamWidth"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/injectstreamwidth"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/injectStreamHeight":{"deprecated":true,"role":"symbol","title":"injectStreamHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"injectStreamHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamHeight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"injectStreamHeight"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/injectstreamheight"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraPublisherConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraPublisherConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraPublisherConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiobitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiochannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/audiosamplerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/bitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/defaultLayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/extraInfo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/framerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamHeight","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/injectStreamWidth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/lifeCycle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/owner","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/publishUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/rawStreamUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/width"]},{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/toJsonString()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/validate()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraPublisherConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration\/title","value":"AgoraPublisherConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraPublisherConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1toJsonString()\/title","value":"toJsonString"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1toJsonString()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonString"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1framerate\/title","value":"framerate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1framerate\/fragments","value":[{"kind":"identifier","text":"framerate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1width\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1width\/fragments","value":[{"kind":"identifier","text":"width"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1validate()\/title","value":"validate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1validate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1lifeCycle\/title","value":"lifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1lifeCycle\/fragments","value":[{"kind":"identifier","text":"lifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1defaultLayout\/title","value":"defaultLayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1defaultLayout\/fragments","value":[{"kind":"identifier","text":"defaultLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1height\/fragments","value":[{"kind":"identifier","text":"height"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1publishUrl\/title","value":"publishUrl"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1publishUrl\/fragments","value":[{"kind":"identifier","text":"publishUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1audiobitrate\/title","value":"audiobitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1audiobitrate\/fragments","value":[{"kind":"identifier","text":"audiobitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1bitrate\/title","value":"bitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1bitrate\/fragments","value":[{"kind":"identifier","text":"bitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1extraInfo\/title","value":"extraInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1extraInfo\/fragments","value":[{"kind":"identifier","text":"extraInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1injectStreamUrl\/title","value":"injectStreamUrl"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1injectStreamUrl\/fragments","value":[{"kind":"identifier","text":"injectStreamUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1rawStreamUrl\/title","value":"rawStreamUrl"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1rawStreamUrl\/fragments","value":[{"kind":"identifier","text":"rawStreamUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1audiochannels\/title","value":"audiochannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1audiochannels\/fragments","value":[{"kind":"identifier","text":"audiochannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1owner\/title","value":"owner"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1owner\/fragments","value":[{"kind":"identifier","text":"owner"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1audiosamplerate\/title","value":"audiosamplerate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1audiosamplerate\/fragments","value":[{"kind":"identifier","text":"audiosamplerate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1injectStreamWidth\/title","value":"injectStreamWidth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1injectStreamWidth\/fragments","value":[{"kind":"identifier","text":"injectStreamWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1injectStreamHeight\/title","value":"injectStreamHeight"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1injectStreamHeight\/fragments","value":[{"kind":"identifier","text":"injectStreamHeight"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}