{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradegradationpreference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradegradationpreference"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video degradation preferences when the bandwidth is a constraint."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"}],"title":"AgoraDegradationPreference","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraDegradationPreference","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/balanced","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainFramerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainQuality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainResolution"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/balanced":{"role":"symbol","title":"AgoraDegradationPreference.balanced","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"abstract":[{"type":"text","text":"2: Reduces the video frame rate and video resolution simultaneously during"},{"type":"text","text":" "},{"type":"text","text":"video encoding under limited bandwidth. The AgoraDegradationBalanced has a"},{"type":"text","text":" "},{"type":"text","text":"lower reduction than AgoraDegradationMaintainQuality and"},{"type":"text","text":" "},{"type":"text","text":"AgoraDegradationMaintainFramerate, and this preference is suitable for"},{"type":"text","text":" "},{"type":"text","text":"scenarios where both smoothness and video quality are a priority.The"},{"type":"text","text":" "},{"type":"text","text":"resolution of the video sent may change, so remote users need to handle"},{"type":"text","text":" "},{"type":"text","text":"this issue. See videoSizeChangedOfSourceType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/balanced","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationBalanced"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference\/balanced"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference":{"role":"symbol","title":"AgoraDegradationPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"}],"abstract":[{"type":"text","text":"Video degradation preferences when the bandwidth is a constraint."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationPreference"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/maintainResolution":{"role":"symbol","title":"AgoraDegradationPreference.maintainResolution","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainResolution"}],"abstract":[{"type":"text","text":"3: Reduces the video frame rate while maintaining the video resolution"},{"type":"text","text":" "},{"type":"text","text":"during video encoding under limited bandwidth. This degradation preference"},{"type":"text","text":" "},{"type":"text","text":"is suitable for scenarios where video quality is prioritized."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationMaintainResolution"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference\/maintainresolution"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoradegradationpreference\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoradegradationpreference\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/maintainFramerate":{"role":"symbol","title":"AgoraDegradationPreference.maintainFramerate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainFramerate"}],"abstract":[{"type":"text","text":"1: Reduces the video resolution while maintaining the video frame rate"},{"type":"text","text":" "},{"type":"text","text":"during video encoding under limited bandwidth. This degradation preference"},{"type":"text","text":" "},{"type":"text","text":"is suitable for scenarios where smoothness is prioritized and video quality"},{"type":"text","text":" "},{"type":"text","text":"is allowed to be reduced."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainFramerate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationMaintainFramerate"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference\/maintainframerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/maintainQuality":{"role":"symbol","title":"AgoraDegradationPreference.maintainQuality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maintainQuality"}],"abstract":[{"type":"text","text":"0: (Default) Prefers to reduce the video frame rate while maintaining video"},{"type":"text","text":" "},{"type":"text","text":"resolution during video encoding under limited bandwidth. This degradation"},{"type":"text","text":" "},{"type":"text","text":"preference is suitable for scenarios where video quality is prioritized."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDegradationMaintainQuality"}],"url":"\/documentation\/agorartckit\/agoradegradationpreference\/maintainquality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDegradationPreference/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoradegradationpreference\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDegradationPreference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/balanced","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainFramerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainQuality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDegradationPreference\/maintainResolution"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDegradationPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1balanced\/title","value":"AgoraDegradationBalanced"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1balanced\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationBalanced"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/title","value":"AgoraDegradationPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainResolution\/title","value":"AgoraDegradationMaintainResolution"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainResolution\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationMaintainResolution"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainFramerate\/title","value":"AgoraDegradationMaintainFramerate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainFramerate\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationMaintainFramerate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainQuality\/title","value":"AgoraDegradationMaintainQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDegradationPreference~1maintainQuality\/fragments","value":[{"kind":"identifier","text":"AgoraDegradationMaintainQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}