{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideooutputorientationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video output orientation mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"title":"AgoraVideoOutputOrientationMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoOutputOrientationMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/adaptative","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedLandscape","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedPortrait"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/fixedPortrait":{"role":"symbol","title":"AgoraVideoOutputOrientationMode.fixedPortrait","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedPortrait"}],"abstract":[{"type":"text","text":"2: In this mode, the SDK always outputs video in portrait (portrait) mode."},{"type":"text","text":" "},{"type":"text","text":"If the captured video is in landscape mode, the video encoder crops it to"},{"type":"text","text":" "},{"type":"text","text":"fit the output. Applies to situations where the receiving end cannot"},{"type":"text","text":" "},{"type":"text","text":"process the rotational information. For example, CDN live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedPortrait","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedPortrait"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedportrait"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode":{"role":"symbol","title":"AgoraVideoOutputOrientationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"abstract":[{"type":"text","text":"Video output orientation mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/adaptative":{"role":"symbol","title":"AgoraVideoOutputOrientationMode.adaptative","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptative"}],"abstract":[{"type":"text","text":"0: (Default) The output video always follows the orientation of the"},{"type":"text","text":" "},{"type":"text","text":"captured video. The receiver takes the rotational information passed on"},{"type":"text","text":" "},{"type":"text","text":"from the video encoder. This mode applies to scenarios where video"},{"type":"text","text":" "},{"type":"text","text":"orientation can be adjusted on the receiver.If the captured video is in"},{"type":"text","text":" "},{"type":"text","text":"landscape mode, the output video is in landscape mode.If the captured video"},{"type":"text","text":" "},{"type":"text","text":"is in portrait mode, the output video is in portrait mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/adaptative","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeAdaptative"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/adaptative"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/equatable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoOutputOrientationMode/fixedLandscape":{"role":"symbol","title":"AgoraVideoOutputOrientationMode.fixedLandscape","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedLandscape"}],"abstract":[{"type":"text","text":"1: In this mode, the SDK always outputs videos in landscape (horizontal)"},{"type":"text","text":" "},{"type":"text","text":"mode. If the captured video is in portrait mode, the video encoder crops it"},{"type":"text","text":" "},{"type":"text","text":"to fit the output. Applies to situations where the receiving end cannot"},{"type":"text","text":" "},{"type":"text","text":"process the rotational information. For example, CDN live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedLandscape","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedLandscape"}],"url":"\/documentation\/agorartckit\/agoravideooutputorientationmode\/fixedlandscape"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoOutputOrientationMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/adaptative","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedLandscape","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoOutputOrientationMode\/fixedPortrait"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedPortrait\/title","value":"AgoraVideoOutputOrientationModeFixedPortrait"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedPortrait\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedPortrait"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/title","value":"AgoraVideoOutputOrientationMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1adaptative\/title","value":"AgoraVideoOutputOrientationModeAdaptative"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1adaptative\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeAdaptative"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedLandscape\/title","value":"AgoraVideoOutputOrientationModeFixedLandscape"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoOutputOrientationMode~1fixedLandscape\/fragments","value":[{"kind":"identifier","text":"AgoraVideoOutputOrientationModeFixedLandscape"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}