{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraconnectionstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraconnectionstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Connection states."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionState"}],"title":"AgoraConnectionState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraConnectionState","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionState"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/disconnected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/reconnecting"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/disconnected":{"role":"symbol","title":"AgoraConnectionState.disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"abstract":[{"type":"text","text":"1: The SDK is disconnected from the Agora edge server. The state indicates"},{"type":"text","text":" "},{"type":"text","text":"the SDK is in one of the following phases:Theinitial state before calling"},{"type":"text","text":" "},{"type":"text","text":"the joinChannelByToken [2\/4] method.The app calls the leaveChannel [1\/2]"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/disconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateDisconnected"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate\/disconnected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraconnectionstate\/equatable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/reconnecting":{"role":"symbol","title":"AgoraConnectionState.reconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"abstract":[{"type":"text","text":"4: The SDK keeps reconnecting to the Agora edge server. The SDK keeps"},{"type":"text","text":" "},{"type":"text","text":"rejoining the channel after being disconnected from a joined channel"},{"type":"text","text":" "},{"type":"text","text":"because of network issues.If the SDK cannot rejoin the channel within 10"},{"type":"text","text":" "},{"type":"text","text":"seconds, it triggers rtcEngineConnectionDidLost , stays in the"},{"type":"text","text":" "},{"type":"text","text":"AgoraConnectionStateReconnecting state, and keeps rejoining the channel.If"},{"type":"text","text":" "},{"type":"text","text":"the SDK fails to rejoin the channel 20 minutes after being disconnected"},{"type":"text","text":" "},{"type":"text","text":"from the Agora edge server, the SDK triggers the connectionChangedToState"},{"type":"text","text":" "},{"type":"text","text":"callback, switches to the AgoraConnectionStateFailed state, and stops"},{"type":"text","text":" "},{"type":"text","text":"rejoining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/reconnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateReconnecting"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate\/reconnecting"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/connecting":{"role":"symbol","title":"AgoraConnectionState.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"2: The SDK is connecting to the Agora edge server. This state indicates"},{"type":"text","text":" "},{"type":"text","text":"that the SDK is establishing a connection with the specified channel after"},{"type":"text","text":" "},{"type":"text","text":"the app calls joinChannelByToken [2\/4].If the SDK successfully joins the"},{"type":"text","text":" "},{"type":"text","text":"channel, it triggers the connectionChangedToState callback and the"},{"type":"text","text":" "},{"type":"text","text":"connection state switches to AgoraConnectionStateConnected.After the"},{"type":"text","text":" "},{"type":"text","text":"connection is established, the SDK also initializes the media and triggers"},{"type":"text","text":" "},{"type":"text","text":"didJoinChannel when everything is ready."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateConnecting"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate\/connecting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState":{"role":"symbol","title":"AgoraConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionState"}],"abstract":[{"type":"text","text":"Connection states."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionState"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraconnectionstate\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/connected":{"role":"symbol","title":"AgoraConnectionState.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[{"type":"text","text":"3: The SDK is connected to the Agora edge server. This state also indicates"},{"type":"text","text":" "},{"type":"text","text":"that the user has joined a channel and can now publish or subscribe to a"},{"type":"text","text":" "},{"type":"text","text":"media stream in the channel. If the connection to the channel is lost"},{"type":"text","text":" "},{"type":"text","text":"because, for example, if the network is down or switched, the SDK"},{"type":"text","text":" "},{"type":"text","text":"automatically tries to reconnect and triggers connectionChangedToState"},{"type":"text","text":" "},{"type":"text","text":"callback, notifying that the current network state becomes"},{"type":"text","text":" "},{"type":"text","text":"AgoraConnectionStateReconnecting."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateConnected"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate\/connected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraconnectionstate\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionState/failed":{"role":"symbol","title":"AgoraConnectionState.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"5: The SDK fails to connect to the Agora edge server or join the channel."},{"type":"text","text":" "},{"type":"text","text":"This state indicates that the SDK stops trying to rejoin the channel. You"},{"type":"text","text":" "},{"type":"text","text":"must call leaveChannel [1\/2] You can call joinChannelByToken [2\/4] to"},{"type":"text","text":" "},{"type":"text","text":"rejoin the channel.If the SDK is banned from joining the channel by the"},{"type":"text","text":" "},{"type":"text","text":"Agora edge server through the RESTful API, the SDK triggers the"},{"type":"text","text":" "},{"type":"text","text":"connectionChangedToState callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionStateFailed"}],"url":"\/documentation\/agorartckit\/agoraconnectionstate\/failed"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraConnectionState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraConnectionState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/connecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/disconnected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionState\/reconnecting"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1disconnected\/title","value":"AgoraConnectionStateDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1disconnected\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateDisconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1reconnecting\/title","value":"AgoraConnectionStateReconnecting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1reconnecting\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateReconnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1connecting\/title","value":"AgoraConnectionStateConnecting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1connecting\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState\/title","value":"AgoraConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1connected\/title","value":"AgoraConnectionStateConnected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1connected\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1failed\/title","value":"AgoraConnectionStateFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionState~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionStateFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}