{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionChangedReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraconnectionchangedreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraconnectionchangedreason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/clientIpAddressChangedByUser","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/licenseValidationFailure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonBannedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonClientIpAddressChanged","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonConnecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonEchoTest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInterrupted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidAppId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidChannelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonJoinFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonJoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonKeepAliveTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonLeaveChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRejectedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRejoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRenewToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonSettingProxyServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonTokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/sameUidLogin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/tooManyBroadcasters"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionChangedReason"}],"title":"AgoraConnectionChangedReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraConnectionChangedReason","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReason"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonInvalidChannelName":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonInvalidChannelName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonInvalidChannelName"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidChannelName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInvalidChannelName"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasoninvalidchannelname"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonClientIpAddressChanged":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonClientIpAddressChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonClientIpAddressChanged"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonClientIpAddressChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonClientIpAddressChanged"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonclientipaddresschanged"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonLeaveChannel":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonLeaveChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonLeaveChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonLeaveChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonLeaveChannel"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonleavechannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonBannedByServer":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonBannedByServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonBannedByServer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonBannedByServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonBannedByServer"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonbannedbyserver"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/sameUidLogin":{"role":"symbol","title":"AgoraConnectionChangedReason.sameUidLogin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sameUidLogin"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/sameUidLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedSameUidLogin"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/sameuidlogin"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonInvalidAppId":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonInvalidAppId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonInvalidAppId"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidAppId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInvalidAppId"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasoninvalidappid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonConnecting":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonConnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonConnecting"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonConnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonConnecting"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonconnecting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonSettingProxyServer":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonSettingProxyServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonSettingProxyServer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonSettingProxyServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonSettingProxyServer"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonsettingproxyserver"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/tooManyBroadcasters":{"role":"symbol","title":"AgoraConnectionChangedReason.tooManyBroadcasters","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooManyBroadcasters"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/tooManyBroadcasters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedTooManyBroadcasters"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/toomanybroadcasters"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonRejectedByServer":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonRejectedByServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonRejectedByServer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRejectedByServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonRejectedByServer"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonrejectedbyserver"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/clientIpAddressChangedByUser":{"role":"symbol","title":"AgoraConnectionChangedReason.clientIpAddressChangedByUser","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIpAddressChangedByUser"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/clientIpAddressChangedByUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedClientIpAddressChangedByUser"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/clientipaddresschangedbyuser"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonInvalidToken":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonInvalidToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonInvalidToken"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInvalidToken"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasoninvalidtoken"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonKeepAliveTimeout":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonKeepAliveTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonKeepAliveTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonKeepAliveTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonKeepAliveTimeout"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonkeepalivetimeout"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonEchoTest":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonEchoTest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonEchoTest"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonEchoTest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonEchoTest"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonechotest"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonJoinSuccess":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonJoinSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonJoinSuccess"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonJoinSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonJoinSuccess"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonjoinsuccess"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/licenseValidationFailure":{"role":"symbol","title":"AgoraConnectionChangedReason.licenseValidationFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseValidationFailure"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/licenseValidationFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedLicenseValidationFailure"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/licensevalidationfailure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonTokenExpired":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonTokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonTokenExpired"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonTokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonTokenExpired"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasontokenexpired"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason":{"role":"symbol","title":"AgoraConnectionChangedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionChangedReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReason"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonLost":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonLost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonLost"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonLost"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonlost"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonInterrupted":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonInterrupted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonInterrupted"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInterrupted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInterrupted"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasoninterrupted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonRenewToken":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonRenewToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonRenewToken"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRenewToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonRenewToken"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonrenewtoken"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonRejoinSuccess":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonRejoinSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonRejoinSuccess"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRejoinSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonRejoinSuccess"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonrejoinsuccess"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonJoinFailed":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonJoinFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonJoinFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonJoinFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonJoinFailed"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonjoinfailed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraConnectionChangedReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraConnectionChangedReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/clientIpAddressChangedByUser","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/licenseValidationFailure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonBannedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonClientIpAddressChanged","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonConnecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonEchoTest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInterrupted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidAppId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidChannelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonInvalidToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonJoinFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonJoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonKeepAliveTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonLeaveChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRejectedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRejoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonRenewToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonSettingProxyServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonTokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/sameUidLogin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/tooManyBroadcasters"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionChangedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInvalidChannelName\/title","value":"AgoraConnectionChangedReasonInvalidChannelName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInvalidChannelName\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInvalidChannelName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonClientIpAddressChanged\/title","value":"AgoraConnectionChangedReasonClientIpAddressChanged"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonClientIpAddressChanged\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonClientIpAddressChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonLeaveChannel\/title","value":"AgoraConnectionChangedReasonLeaveChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonLeaveChannel\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonLeaveChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonBannedByServer\/title","value":"AgoraConnectionChangedReasonBannedByServer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonBannedByServer\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonBannedByServer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1sameUidLogin\/title","value":"AgoraConnectionChangedSameUidLogin"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1sameUidLogin\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedSameUidLogin"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInvalidAppId\/title","value":"AgoraConnectionChangedReasonInvalidAppId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInvalidAppId\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInvalidAppId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonConnecting\/title","value":"AgoraConnectionChangedReasonConnecting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonConnecting\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonSettingProxyServer\/title","value":"AgoraConnectionChangedReasonSettingProxyServer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonSettingProxyServer\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonSettingProxyServer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1tooManyBroadcasters\/title","value":"AgoraConnectionChangedTooManyBroadcasters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1tooManyBroadcasters\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedTooManyBroadcasters"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonRejectedByServer\/title","value":"AgoraConnectionChangedReasonRejectedByServer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonRejectedByServer\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonRejectedByServer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1clientIpAddressChangedByUser\/title","value":"AgoraConnectionChangedClientIpAddressChangedByUser"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1clientIpAddressChangedByUser\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedClientIpAddressChangedByUser"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInvalidToken\/title","value":"AgoraConnectionChangedReasonInvalidToken"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInvalidToken\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInvalidToken"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonKeepAliveTimeout\/title","value":"AgoraConnectionChangedReasonKeepAliveTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonKeepAliveTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonKeepAliveTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonEchoTest\/title","value":"AgoraConnectionChangedReasonEchoTest"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonEchoTest\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonEchoTest"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonJoinSuccess\/title","value":"AgoraConnectionChangedReasonJoinSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonJoinSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonJoinSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1licenseValidationFailure\/title","value":"AgoraConnectionChangedLicenseValidationFailure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1licenseValidationFailure\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedLicenseValidationFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonTokenExpired\/title","value":"AgoraConnectionChangedReasonTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonTokenExpired\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason\/title","value":"AgoraConnectionChangedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonLost\/title","value":"AgoraConnectionChangedReasonLost"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonLost\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonLost"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInterrupted\/title","value":"AgoraConnectionChangedReasonInterrupted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonInterrupted\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonInterrupted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonRenewToken\/title","value":"AgoraConnectionChangedReasonRenewToken"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonRenewToken\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonRenewToken"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonRejoinSuccess\/title","value":"AgoraConnectionChangedReasonRejoinSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonRejoinSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonRejoinSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonJoinFailed\/title","value":"AgoraConnectionChangedReasonJoinFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonJoinFailed\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonJoinFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}