{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiencelatencyleveltype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiencelatencyleveltype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The latency level of an audience member in interactive live streaming. This"},{"type":"text","text":" "},{"type":"text","text":"enum takes effect only when the user role is set to AgoraClientRoleAudience ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"title":"AgoraAudienceLatencyLevelType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudienceLatencyLevelType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/lowLatency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/ultraLowLatency"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType":{"role":"symbol","title":"AgoraAudienceLatencyLevelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"abstract":[{"type":"text","text":"The latency level of an audience member in interactive live streaming. This"},{"type":"text","text":" "},{"type":"text","text":"enum takes effect only when the user role is set to AgoraClientRoleAudience ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}],"url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType/lowLatency":{"role":"symbol","title":"AgoraAudienceLatencyLevelType.lowLatency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"}],"abstract":[{"type":"text","text":"1: Low latency."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/lowLatency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelLowLatency"}],"url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/lowlatency"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudienceLatencyLevelType/ultraLowLatency":{"role":"symbol","title":"AgoraAudienceLatencyLevelType.ultraLowLatency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraLowLatency"}],"abstract":[{"type":"text","text":"2: (Default) Ultra low latency."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/ultraLowLatency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelUltraLowLatency"}],"url":"\/documentation\/agorartckit\/agoraaudiencelatencyleveltype\/ultralowlatency"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudienceLatencyLevelType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/lowLatency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudienceLatencyLevelType\/ultraLowLatency"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType\/title","value":"AgoraAudienceLatencyLevelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType~1lowLatency\/title","value":"AgoraAudienceLatencyLevelLowLatency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType~1lowLatency\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelLowLatency"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType~1ultraLowLatency\/title","value":"AgoraAudienceLatencyLevelUltraLowLatency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudienceLatencyLevelType~1ultraLowLatency\/fragments","value":[{"kind":"identifier","text":"AgoraAudienceLatencyLevelUltraLowLatency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}