{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogFilter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralogfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralogfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The output log level of the SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogFilter"}],"title":"AgoraLogFilter","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraLogFilter","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilter"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/critical","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/debug","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/error","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/info","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/off","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoralogfilter\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralogfilter\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/debug":{"role":"symbol","title":"AgoraLogFilter.debug","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"abstract":[{"type":"text","text":"0x080f: Output all log information. Set your log filter to this level if you want to get the most complete log file."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/debug","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterDebug"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/debug"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralogfilter\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/error":{"role":"symbol","title":"AgoraLogFilter.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[{"type":"text","text":"0x000c: Output AgoraLogFilterCritical and AgoraLogFilterError level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterError"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/error"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/warning":{"role":"symbol","title":"AgoraLogFilter.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[{"type":"text","text":"0x000e: Output AgoraLogFilterCritical, AgoraLogFilterError, and AgoraLogFilterWarning level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterWarning"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/warning"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter":{"role":"symbol","title":"AgoraLogFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogFilter"}],"abstract":[{"type":"text","text":"The output log level of the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilter"}],"url":"\/documentation\/agorartckit\/agoralogfilter"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/critical":{"role":"symbol","title":"AgoraLogFilter.critical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"critical"}],"abstract":[{"type":"text","text":"0x0008: Output AgoraLogFilterCritical level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/critical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterCritical"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/critical"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/off":{"role":"symbol","title":"AgoraLogFilter.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"0: Do not output any log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterOff"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/off"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/info":{"role":"symbol","title":"AgoraLogFilter.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[{"type":"text","text":"0x000f: Output AgoraLogFilterCritical, AgoraLogFilterError, AgoraLogFilterWarning, and AgoraLogFilterInfo level log information. We recommend setting your log filter to this level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/info","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterInfo"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/info"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLogFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLogFilter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/critical","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/debug","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/error","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/info","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/off","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/warning"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1debug\/title","value":"AgoraLogFilterDebug"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1debug\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterDebug"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1error\/title","value":"AgoraLogFilterError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1error\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1warning\/title","value":"AgoraLogFilterWarning"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1warning\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/title","value":"AgoraLogFilter"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1critical\/title","value":"AgoraLogFilterCritical"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1critical\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterCritical"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1off\/title","value":"AgoraLogFilterOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1off\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterOff"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1info\/title","value":"AgoraLogFilterInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1info\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}