{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSourceType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideosourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideosourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of the video source."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSourceType"}],"title":"AgoraVideoSourceType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoSourceType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/camera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraFourth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraSecondary","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraThird","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/custom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imageGIF","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imageJPEG","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imagePNG","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/mediaPlayer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/remote","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenFourth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenSecondary","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenThird","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/transCoded","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/unknown":{"role":"symbol","title":"AgoraVideoSourceType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"100: An unknown video source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeUnknown"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/unknown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideosourcetype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideosourcetype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideosourcetype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/mediaPlayer":{"role":"symbol","title":"AgoraVideoSourceType.mediaPlayer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaPlayer"}],"abstract":[{"type":"text","text":"5: The media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/mediaPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeMediaPlayer"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/mediaplayer"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/transCoded":{"role":"symbol","title":"AgoraVideoSourceType.transCoded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transCoded"}],"abstract":[{"type":"text","text":"10: One transcoded video source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/transCoded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeTransCoded"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/transcoded"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/camera":{"role":"symbol","title":"AgoraVideoSourceType.camera","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"}],"abstract":[{"type":"text","text":"0: (Default) The primary camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/camera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeCamera"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/camera"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/screen":{"role":"symbol","title":"AgoraVideoSourceType.screen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screen"}],"abstract":[{"type":"text","text":"2: The primary screen."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreen"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/screen"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/screenFourth":{"role":"symbol","title":"AgoraVideoSourceType.screenFourth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenFourth"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenFourth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreenFourth"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/screenfourth"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/imageJPEG":{"role":"symbol","title":"AgoraVideoSourceType.imageJPEG","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageJPEG"}],"abstract":[{"type":"text","text":"7: One JPEG image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imageJPEG","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeImageJPEG"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/imagejpeg"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/remote":{"role":"symbol","title":"AgoraVideoSourceType.remote","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remote"}],"abstract":[{"type":"text","text":"9: One remote video acquired by the network."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/remote","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeRemote"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/remote"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/screenThird":{"role":"symbol","title":"AgoraVideoSourceType.screenThird","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenThird"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenThird","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreenThird"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/screenthird"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/cameraFourth":{"role":"symbol","title":"AgoraVideoSourceType.cameraFourth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFourth"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraFourth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeCameraFourth"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/camerafourth"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType":{"role":"symbol","title":"AgoraVideoSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSourceType"}],"abstract":[{"type":"text","text":"The type of the video source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/custom":{"role":"symbol","title":"AgoraVideoSourceType.custom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"abstract":[{"type":"text","text":"4: A custom video source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/custom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeCustom"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/custom"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/imagePNG":{"role":"symbol","title":"AgoraVideoSourceType.imagePNG","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePNG"}],"abstract":[{"type":"text","text":"6: One PNG image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imagePNG","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeImagePNG"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/imagepng"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/screenSecondary":{"role":"symbol","title":"AgoraVideoSourceType.screenSecondary","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenSecondary"}],"abstract":[{"type":"text","text":"3: The secondary screen."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenSecondary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreenSecondary"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/screensecondary"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/cameraThird":{"role":"symbol","title":"AgoraVideoSourceType.cameraThird","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraThird"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraThird","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeCameraThird"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/camerathird"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/cameraSecondary":{"role":"symbol","title":"AgoraVideoSourceType.cameraSecondary","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraSecondary"}],"abstract":[{"type":"text","text":"1: The secondary camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraSecondary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeCameraSecondary"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/camerasecondary"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType/imageGIF":{"role":"symbol","title":"AgoraVideoSourceType.imageGIF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageGIF"}],"abstract":[{"type":"text","text":"8: One GIF image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imageGIF","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceTypeImageGIF"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype\/imagegif"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoSourceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoSourceType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/camera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraFourth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraSecondary","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/cameraThird","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/custom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imageGIF","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imageJPEG","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/imagePNG","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/mediaPlayer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/remote","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenFourth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenSecondary","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/screenThird","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/transCoded","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1unknown\/title","value":"AgoraVideoSourceTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1unknown\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1mediaPlayer\/title","value":"AgoraVideoSourceTypeMediaPlayer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1mediaPlayer\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeMediaPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1transCoded\/title","value":"AgoraVideoSourceTypeTransCoded"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1transCoded\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeTransCoded"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1camera\/title","value":"AgoraVideoSourceTypeCamera"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1camera\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screen\/title","value":"AgoraVideoSourceTypeScreen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screen\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screenFourth\/title","value":"AgoraVideoSourceTypeScreenFourth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screenFourth\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreenFourth"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1imageJPEG\/title","value":"AgoraVideoSourceTypeImageJPEG"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1imageJPEG\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeImageJPEG"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1remote\/title","value":"AgoraVideoSourceTypeRemote"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1remote\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeRemote"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screenThird\/title","value":"AgoraVideoSourceTypeScreenThird"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screenThird\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreenThird"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1cameraFourth\/title","value":"AgoraVideoSourceTypeCameraFourth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1cameraFourth\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeCameraFourth"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/title","value":"AgoraVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1custom\/title","value":"AgoraVideoSourceTypeCustom"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1custom\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeCustom"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1imagePNG\/title","value":"AgoraVideoSourceTypeImagePNG"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1imagePNG\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeImagePNG"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screenSecondary\/title","value":"AgoraVideoSourceTypeScreenSecondary"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1screenSecondary\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeScreenSecondary"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1cameraThird\/title","value":"AgoraVideoSourceTypeCameraThird"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1cameraThird\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeCameraThird"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1cameraSecondary\/title","value":"AgoraVideoSourceTypeCameraSecondary"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1cameraSecondary\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeCameraSecondary"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1imageGIF\/title","value":"AgoraVideoSourceTypeImageGIF"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType~1imageGIF\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceTypeImageGIF"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}