{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraclientrolechangefailedreason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The reason for a user role switch failure."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"title":"AgoraClientRoleChangeFailedReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraClientRoleChangeFailedReason","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/connectionFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/notAuthorized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/requestTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/tooManyBroadcasters"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/tooManyBroadcasters":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason.tooManyBroadcasters","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooManyBroadcasters"}],"abstract":[{"type":"text","text":"1: The number of hosts in the channel is already at the upper limit.This"},{"type":"text","text":" "},{"type":"text","text":"enumerator is reported only when the support for 128 users is enabled. The"},{"type":"text","text":" "},{"type":"text","text":"maximum number of hosts is based on the actual number of hosts configured"},{"type":"text","text":" "},{"type":"text","text":"when you enable the 128-user feature."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/tooManyBroadcasters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedTooManyBroadcasters"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/toomanybroadcasters"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/notAuthorized":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason.notAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"abstract":[{"type":"text","text":"2: The request is rejected by the Agora server. Agora recommends you prompt"},{"type":"text","text":" "},{"type":"text","text":"the user to try to switch their user role again."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/notAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedNotAuthorized"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/notauthorized"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/connectionFailed":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason.connectionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionFailed"}],"abstract":[{"type":"text","text":"4: The SDK connection fails. You can use reason reported in the"},{"type":"text","text":" "},{"type":"text","text":"connectionChangedToState callback to troubleshoot the failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/connectionFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedConnectionFailed"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/connectionfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/init(rawvalue:)"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"abstract":[{"type":"text","text":"The reason for a user role switch failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraClientRoleChangeFailedReason/requestTimeout":{"role":"symbol","title":"AgoraClientRoleChangeFailedReason.requestTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTimeout"}],"abstract":[{"type":"text","text":"3: The request is timed out. Agora recommends you prompt the user to check"},{"type":"text","text":" "},{"type":"text","text":"the network connection and try to switch their user role again."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/requestTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedRequestTimeout"}],"url":"\/documentation\/agorartckit\/agoraclientrolechangefailedreason\/requesttimeout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraClientRoleChangeFailedReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/connectionFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/notAuthorized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/requestTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraClientRoleChangeFailedReason\/tooManyBroadcasters"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1tooManyBroadcasters\/title","value":"AgoraClientRoleChangeFailedTooManyBroadcasters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1tooManyBroadcasters\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedTooManyBroadcasters"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1notAuthorized\/title","value":"AgoraClientRoleChangeFailedNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1notAuthorized\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1connectionFailed\/title","value":"AgoraClientRoleChangeFailedConnectionFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1connectionFailed\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedConnectionFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/title","value":"AgoraClientRoleChangeFailedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1requestTimeout\/title","value":"AgoraClientRoleChangeFailedRequestTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraClientRoleChangeFailedReason~1requestTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraClientRoleChangeFailedRequestTimeout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}