{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorderdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorderdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:informationDidUpdated:uid:info:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:stateDidChanged:uid:state:error:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}],"title":"AgoraMediaRecorderDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraMediaRecorderDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderDelegate":{"role":"symbol","title":"AgoraMediaRecorderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}],"url":"\/documentation\/agorartckit\/agoramediarecorderdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderDelegate/mediaRecorder(_:stateDidChanged:uid:state:error:)":{"navigatorTitle":[{"kind":"identifier","text":"mediaRecorder:stateDidChanged:uid:state:error:"}],"role":"symbol","title":"mediaRecorder(_:stateDidChanged:uid:state:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaRecorder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateDidChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderState","preciseIdentifier":"c:@E@AgoraMediaRecorderState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderErrorCode","preciseIdentifier":"c:@E@AgoraMediaRecorderErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:stateDidChanged:uid:state:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramediarecorderdelegate\/mediarecorder(_:statedidchanged:uid:state:error:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderDelegate/mediaRecorder(_:informationDidUpdated:uid:info:)":{"navigatorTitle":[{"kind":"identifier","text":"mediaRecorder:informationDidUpdated:uid:info:"}],"role":"symbol","title":"mediaRecorder(_:informationDidUpdated:uid:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaRecorder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorder","preciseIdentifier":"c:objc(cs)AgoraMediaRecorder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"informationDidUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderInfo","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderInfo"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:informationDidUpdated:uid:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramediarecorderdelegate\/mediarecorder(_:informationdidupdated:uid:info:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaRecorderDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:informationDidUpdated:uid:info:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderDelegate\/mediaRecorder(_:stateDidChanged:uid:state:error:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate\/title","value":"AgoraMediaRecorderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate~1mediaRecorder(_:stateDidChanged:uid:state:error:)\/title","value":"mediaRecorder:stateDidChanged:uid:state:error:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate~1mediaRecorder(_:stateDidChanged:uid:state:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaRecorder:stateDidChanged:uid:state:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate~1mediaRecorder(_:informationDidUpdated:uid:info:)\/title","value":"mediaRecorder:informationDidUpdated:uid:info:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderDelegate~1mediaRecorder(_:informationDidUpdated:uid:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mediaRecorder:informationDidUpdated:uid:info:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}