{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used for recording audio and video on the client."},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaRecorder can record the following:"},{"type":"text","text":" "},{"type":"text","text":"The audio captured by the local microphone and encoded in AAC format.The"},{"type":"text","text":" "},{"type":"text","text":"video captured by the local camera and encoded by the SDK.In the"},{"type":"text","text":" "},{"type":"text","text":"COMMUNICATION channel profile, this feature is unavailable when there are"},{"type":"text","text":" "},{"type":"text","text":"users using SDK versions earlier than v3.0.0."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorder"}],"title":"AgoraMediaRecorder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraMediaRecorder","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorder"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/enableMainQueueDispatch(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/setMediaRecorderDelegate(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/startRecording(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/stopRecording()"]}],"references":{"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder/stopRecording()":{"role":"symbol","title":"stopRecording()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecording"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/stopRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopRecording"}],"url":"\/documentation\/agorartckit\/agoramediarecorder\/stoprecording()"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder":{"role":"symbol","title":"AgoraMediaRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorder"}],"abstract":[{"type":"text","text":"Used for recording audio and video on the client."},{"type":"text","text":" "},{"type":"text","text":"AgoraMediaRecorder can record the following:"},{"type":"text","text":" "},{"type":"text","text":"The audio captured by the local microphone and encoded in AAC format.The"},{"type":"text","text":" "},{"type":"text","text":"video captured by the local camera and encoded by the SDK.In the"},{"type":"text","text":" "},{"type":"text","text":"COMMUNICATION channel profile, this feature is unavailable when there are"},{"type":"text","text":" "},{"type":"text","text":"users using SDK versions earlier than v3.0.0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorder"}],"url":"\/documentation\/agorartckit\/agoramediarecorder"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder/setMediaRecorderDelegate(_:)":{"role":"symbol","title":"setMediaRecorderDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMediaRecorderDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorderDelegate","preciseIdentifier":"c:objc(pl)AgoraMediaRecorderDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/setMediaRecorderDelegate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMediaRecorderDelegate:"}],"url":"\/documentation\/agorartckit\/agoramediarecorder\/setmediarecorderdelegate(_:)"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder/enableMainQueueDispatch(_:)":{"role":"symbol","title":"enableMainQueueDispatch(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableMainQueueDispatch"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables\/Disables dispatching delegate methods to the main queue."},{"type":"text","text":" "},{"type":"text","text":"If disabled, the app should dispatch UI operations to the main queue."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/enableMainQueueDispatch(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableMainQueueDispatch:"}],"url":"\/documentation\/agorartckit\/agoramediarecorder\/enablemainqueuedispatch(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorder/startRecording(_:)":{"role":"symbol","title":"startRecording(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRecording"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMediaRecorderConfiguration","preciseIdentifier":"c:objc(cs)AgoraMediaRecorderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/startRecording(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startRecording:"}],"url":"\/documentation\/agorartckit\/agoramediarecorder\/startrecording(_:)"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaRecorder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaRecorder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/enableMainQueueDispatch(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/setMediaRecorderDelegate(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/startRecording(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorder\/stopRecording()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1stopRecording()\/title","value":"stopRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1stopRecording()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/title","value":"AgoraMediaRecorder"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorder"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1setMediaRecorderDelegate(_:)\/title","value":"setMediaRecorderDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1setMediaRecorderDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMediaRecorderDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1enableMainQueueDispatch(_:)\/title","value":"enableMainQueueDispatch:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1enableMainQueueDispatch(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableMainQueueDispatch:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1startRecording(_:)\/title","value":"startRecording:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorder~1startRecording(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRecording:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}