{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralivestreamadvancedfeature"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralivestreamadvancedfeature"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The configuration for advanced features of the RTMP or RTMPS streaming with"},{"type":"text","text":" "},{"type":"text","text":"transcoding. If you want to enable the advanced features of streaming with"},{"type":"text","text":" "},{"type":"text","text":"transcoding, contact ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"title":"AgoraLiveStreamAdvancedFeature","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLiveStreamAdvancedFeature","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/featureName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/opened"]}],"references":{"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveStreamAdvancedFeature/featureName":{"role":"symbol","title":"featureName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The feature names, including LBHQ (high-quality video with a lower bitrate)"},{"type":"text","text":" "},{"type":"text","text":"and VEO (optimized video encoder)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/featureName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"featureName"}],"url":"\/documentation\/agorartckit\/agoralivestreamadvancedfeature\/featurename"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveStreamAdvancedFeature":{"role":"symbol","title":"AgoraLiveStreamAdvancedFeature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"abstract":[{"type":"text","text":"The configuration for advanced features of the RTMP or RTMPS streaming with"},{"type":"text","text":" "},{"type":"text","text":"transcoding. If you want to enable the advanced features of streaming with"},{"type":"text","text":" "},{"type":"text","text":"transcoding, contact ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}],"url":"\/documentation\/agorartckit\/agoralivestreamadvancedfeature"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveStreamAdvancedFeature/opened":{"role":"symbol","title":"opened","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"opened"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable the advanced features of streaming with transcoding:YES:"},{"type":"text","text":" "},{"type":"text","text":"Enable the advanced features.NO: (Default) Do not enable the advanced"},{"type":"text","text":" "},{"type":"text","text":"features."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/opened","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"opened"}],"url":"\/documentation\/agorartckit\/agoralivestreamadvancedfeature\/opened"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLiveStreamAdvancedFeature"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/featureName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveStreamAdvancedFeature\/opened"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature~1featureName\/title","value":"featureName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature~1featureName\/fragments","value":[{"kind":"identifier","text":"featureName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature\/title","value":"AgoraLiveStreamAdvancedFeature"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature\/fragments","value":[{"kind":"identifier","text":"AgoraLiveStreamAdvancedFeature"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature~1opened\/title","value":"opened"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveStreamAdvancedFeature~1opened\/fragments","value":[{"kind":"identifier","text":"opened"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}