{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate\/AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}],"title":"AgoraRtcMediaPlayerAudioFrameDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraRtcMediaPlayerAudioFrameDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerAudioFrameDelegate/AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)":{"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"}],"role":"symbol","title":"AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveAudioFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs each time the player receives an audio frame."},{"type":"text","text":" "},{"type":"text","text":"After registering the audio frame observer, the callback occurs every time"},{"type":"text","text":" "},{"type":"text","text":"the player receives an audio frame, reporting the detailed information of the"},{"type":"text","text":" "},{"type":"text","text":"audio frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate\/AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate\/agorartcmediaplayer(_:didreceiveaudioframe:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcMediaPlayerAudioFrameDelegate":{"role":"symbol","title":"AgoraRtcMediaPlayerAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agorartcmediaplayeraudioframedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcMediaPlayerAudioFrameDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcMediaPlayerAudioFrameDelegate\/AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate~1AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)\/title","value":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate~1AgoraRtcMediaPlayer(_:didReceiveAudioFrame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"AgoraRtcMediaPlayer:didReceiveAudioFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate\/title","value":"AgoraRtcMediaPlayerAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcMediaPlayerAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcMediaPlayerAudioFrameDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}