{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraearmonitoringfiltertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraearmonitoringfiltertype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP","doc:\/\/AgoraRtcKit\/s9OptionSetP","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP","doc:\/\/AgoraRtcKit\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/builtInAudioFilters","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/noiseSuppression","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/none"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/OptionSet-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/SetAlgebra-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"title":"AgoraEarMonitoringFilterType","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@E@AgoraEarMonitoringFilterType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/noiseSuppression":{"role":"symbol","title":"noiseSuppression","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noiseSuppression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/noiseSuppression","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNoiseSuppression"}],"url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/noisesuppression"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/optionset-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/setalgebra-implementations"},"doc://AgoraRtcKit/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/AgoraRtcKit\/s10SetAlgebraP"},"doc://AgoraRtcKit/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/AgoraRtcKit\/s9OptionSetP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType":{"role":"symbol","title":"AgoraEarMonitoringFilterType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/builtInAudioFilters":{"role":"symbol","title":"builtInAudioFilters","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"builtInAudioFilters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/builtInAudioFilters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterBuiltInAudioFilters"}],"url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/builtinaudiofilters"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/none":{"role":"symbol","title":"none","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNone"}],"url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/none"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/init(rawvalue:)"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEarMonitoringFilterType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/builtInAudioFilters","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/noiseSuppression","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/none"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEarMonitoringFilterType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1noiseSuppression\/title","value":"AgoraEarMonitoringFilterNoiseSuppression"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1noiseSuppression\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNoiseSuppression"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType\/title","value":"AgoraEarMonitoringFilterType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1builtInAudioFilters\/title","value":"AgoraEarMonitoringFilterBuiltInAudioFilters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1builtInAudioFilters\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterBuiltInAudioFilters"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1none\/title","value":"AgoraEarMonitoringFilterNone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1none\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}