{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcremotevideostats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcremotevideostats"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Statistics of the remote video stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}],"title":"AgoraRtcRemoteVideoStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRtcRemoteVideoStats","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/avSyncTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/decoderOutputFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/delay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/e2eDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/frameLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/frozenRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/mosValue","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/packetLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/publishDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/receivedBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/receivedFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rendererOutputFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rxStreamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rxVideoBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/totalActiveTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/totalFrozenTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/uid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/width"]}],"references":{"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/height":{"role":"symbol","title":"height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The height (pixels) of the video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/height","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"height"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/height"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/rxVideoBytes":{"role":"symbol","title":"rxVideoBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxVideoBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rxVideoBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxVideoBytes"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/rxvideobytes"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/avSyncTimeMs":{"role":"symbol","title":"avSyncTimeMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avSyncTimeMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The amount of time (ms) that the audio is ahead of the video.If this value is"},{"type":"text","text":" "},{"type":"text","text":"negative, the audio is lagging behind the video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/avSyncTimeMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"avSyncTimeMs"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/avsynctimems"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/publishDuration":{"role":"symbol","title":"publishDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The total duration (ms) of the remote video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/publishDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishDuration"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/publishduration"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/receivedFrameRate":{"role":"symbol","title":"receivedFrameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The frame rate (Kbps) received since the last count."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/receivedFrameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"receivedFrameRate"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/receivedframerate"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/e2eDelay":{"role":"symbol","title":"e2eDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"e2eDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/e2eDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"e2eDelay"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/e2edelay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/receivedBitrate":{"role":"symbol","title":"receivedBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The bitrate (Kbps) of the remote video received since the last count."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/receivedBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"receivedBitrate"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/receivedbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/rendererOutputFrameRate":{"role":"symbol","title":"rendererOutputFrameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rendererOutputFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The frame rate (fps) of rendering the remote video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rendererOutputFrameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rendererOutputFrameRate"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/rendereroutputframerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/frozenRate":{"role":"symbol","title":"frozenRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frozenRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The total video freeze time as a percentage (%) of the total time the video"},{"type":"text","text":" "},{"type":"text","text":"is available. The video is considered available as long as that the remote"},{"type":"text","text":" "},{"type":"text","text":"user neither stops sending the video stream nor disables the video module"},{"type":"text","text":" "},{"type":"text","text":"after joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/frozenRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frozenRate"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/frozenrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/uid":{"role":"symbol","title":"uid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The user ID of the remote user sending the video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/uid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uid"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/uid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/width":{"role":"symbol","title":"width","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The width (pixels) of the video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/width","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"width"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/width"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/packetLossRate":{"role":"symbol","title":"packetLossRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetLossRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The packet loss rate (%) of the remote video after using the anti-packet-loss"},{"type":"text","text":" "},{"type":"text","text":"technology."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/packetLossRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"packetLossRate"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/packetlossrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/delay":{"deprecated":true,"role":"symbol","title":"delay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/delay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delay"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/delay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/decoderOutputFrameRate":{"role":"symbol","title":"decoderOutputFrameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoderOutputFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The frame rate (fps) of decoding the remote video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/decoderOutputFrameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decoderOutputFrameRate"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/decoderoutputframerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/mosValue":{"role":"symbol","title":"mosValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mosValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/mosValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mosValue"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/mosvalue"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats":{"role":"symbol","title":"AgoraRtcRemoteVideoStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}],"abstract":[{"type":"text","text":"Statistics of the remote video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/totalActiveTime":{"role":"symbol","title":"totalActiveTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalActiveTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The total active time (ms) of the video.As long as the remote user or host"},{"type":"text","text":" "},{"type":"text","text":"neither stops sending the video stream nor disables the video module after"},{"type":"text","text":" "},{"type":"text","text":"joining the channel, the video is available."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/totalActiveTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalActiveTime"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/totalactivetime"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/frameLossRate":{"role":"symbol","title":"frameLossRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameLossRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The packet loss rate (%) of the remote video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/frameLossRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameLossRate"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/framelossrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/totalFrozenTime":{"role":"symbol","title":"totalFrozenTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalFrozenTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The total freeze time (ms) of the remote video stream after the remote user"},{"type":"text","text":" "},{"type":"text","text":"joins the channel. In a video session where the frame rate is set to no less"},{"type":"text","text":" "},{"type":"text","text":"than 5 fps, video freeze occurs when the time interval between two adjacent"},{"type":"text","text":" "},{"type":"text","text":"renderable video frames is more than 500 ms."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/totalFrozenTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalFrozenTime"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/totalfrozentime"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteVideoStats/rxStreamType":{"role":"symbol","title":"rxStreamType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxStreamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType"}],"abstract":[{"type":"text","text":"The type of the video stream. See AgoraVideoStreamType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rxStreamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxStreamType"}],"url":"\/documentation\/agorartckit\/agorartcremotevideostats\/rxstreamtype"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcRemoteVideoStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/avSyncTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/decoderOutputFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/delay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/e2eDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/frameLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/frozenRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/mosValue","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/packetLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/publishDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/receivedBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/receivedFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rendererOutputFrameRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rxStreamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/rxVideoBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/totalActiveTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/totalFrozenTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/uid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteVideoStats\/width"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1height\/fragments","value":[{"kind":"identifier","text":"height"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1rxVideoBytes\/title","value":"rxVideoBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1rxVideoBytes\/fragments","value":[{"kind":"identifier","text":"rxVideoBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1avSyncTimeMs\/title","value":"avSyncTimeMs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1avSyncTimeMs\/fragments","value":[{"kind":"identifier","text":"avSyncTimeMs"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1publishDuration\/title","value":"publishDuration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1publishDuration\/fragments","value":[{"kind":"identifier","text":"publishDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1receivedFrameRate\/title","value":"receivedFrameRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1receivedFrameRate\/fragments","value":[{"kind":"identifier","text":"receivedFrameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1e2eDelay\/title","value":"e2eDelay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1e2eDelay\/fragments","value":[{"kind":"identifier","text":"e2eDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1receivedBitrate\/title","value":"receivedBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1receivedBitrate\/fragments","value":[{"kind":"identifier","text":"receivedBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1rendererOutputFrameRate\/title","value":"rendererOutputFrameRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1rendererOutputFrameRate\/fragments","value":[{"kind":"identifier","text":"rendererOutputFrameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1frozenRate\/title","value":"frozenRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1frozenRate\/fragments","value":[{"kind":"identifier","text":"frozenRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1uid\/title","value":"uid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1uid\/fragments","value":[{"kind":"identifier","text":"uid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1width\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1width\/fragments","value":[{"kind":"identifier","text":"width"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1packetLossRate\/title","value":"packetLossRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1packetLossRate\/fragments","value":[{"kind":"identifier","text":"packetLossRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1delay\/title","value":"delay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1delay\/fragments","value":[{"kind":"identifier","text":"delay"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1decoderOutputFrameRate\/title","value":"decoderOutputFrameRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1decoderOutputFrameRate\/fragments","value":[{"kind":"identifier","text":"decoderOutputFrameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1mosValue\/title","value":"mosValue"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1mosValue\/fragments","value":[{"kind":"identifier","text":"mosValue"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats\/title","value":"AgoraRtcRemoteVideoStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcRemoteVideoStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1totalActiveTime\/title","value":"totalActiveTime"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1totalActiveTime\/fragments","value":[{"kind":"identifier","text":"totalActiveTime"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1frameLossRate\/title","value":"frameLossRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1frameLossRate\/fragments","value":[{"kind":"identifier","text":"frameLossRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1totalFrozenTime\/title","value":"totalFrozenTime"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1totalFrozenTime\/fragments","value":[{"kind":"identifier","text":"totalFrozenTime"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1rxStreamType\/title","value":"rxStreamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteVideoStats~1rxStreamType\/fragments","value":[{"kind":"identifier","text":"rxStreamType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}