{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalaccesspointconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalaccesspointconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/advancedConfig","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/domainList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/ipList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/mode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/verifyDomainName"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"title":"AgoraLocalAccessPointConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLocalAccessPointConfiguration","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration":{"role":"symbol","title":"AgoraLocalAccessPointConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration/mode":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLocalProxyMode","preciseIdentifier":"c:@E@AgoraLocalProxyMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/mode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mode"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/mode"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration/domainList":{"role":"symbol","title":"domainList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"domainList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/domainList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"domainList"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/domainlist"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration/advancedConfig":{"role":"symbol","title":"advancedConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedConfigInfo","preciseIdentifier":"c:objc(cs)AdvancedConfigInfo"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/advancedConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"advancedConfig"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/advancedconfig"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration/verifyDomainName":{"role":"symbol","title":"verifyDomainName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyDomainName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/verifyDomainName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"verifyDomainName"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/verifydomainname"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration/ipList":{"role":"symbol","title":"ipList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ipList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/ipList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ipList"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/iplist"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalAccessPointConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/advancedConfig","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/domainList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/ipList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/mode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/verifyDomainName"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration\/title","value":"AgoraLocalAccessPointConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1mode\/title","value":"mode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1domainList\/title","value":"domainList"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1domainList\/fragments","value":[{"kind":"identifier","text":"domainList"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1advancedConfig\/title","value":"advancedConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1advancedConfig\/fragments","value":[{"kind":"identifier","text":"advancedConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1verifyDomainName\/title","value":"verifyDomainName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1verifyDomainName\/fragments","value":[{"kind":"identifier","text":"verifyDomainName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1ipList\/title","value":"ipList"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1ipList\/fragments","value":[{"kind":"identifier","text":"ipList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}