{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusic"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusic"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/climaxSegmentList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/durationS","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/lyricList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/mvPropertyList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/name","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/pitchType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/poster","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/releaseTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/singer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/songCode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/type"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusic"}],"title":"AgoraMusic","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraMusic","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusic"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/agorartckit\/agoramusic\/type"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/singer":{"role":"symbol","title":"singer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"singer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/singer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"singer"}],"url":"\/documentation\/agorartckit\/agoramusic\/singer"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/climaxSegmentList":{"role":"symbol","title":"climaxSegmentList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"climaxSegmentList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraClimaxSegment","preciseIdentifier":"c:objc(cs)AgoraClimaxSegment"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/climaxSegmentList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"climaxSegmentList"}],"url":"\/documentation\/agorartckit\/agoramusic\/climaxsegmentlist"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic":{"role":"symbol","title":"AgoraMusic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusic"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusic"}],"url":"\/documentation\/agorartckit\/agoramusic"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/lyricList":{"role":"symbol","title":"lyricList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lyricList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/lyricList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lyricList"}],"url":"\/documentation\/agorartckit\/agoramusic\/lyriclist"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/mvPropertyList":{"role":"symbol","title":"mvPropertyList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mvPropertyList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraMvProperty","preciseIdentifier":"c:objc(cs)AgoraMvProperty"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/mvPropertyList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mvPropertyList"}],"url":"\/documentation\/agorartckit\/agoramusic\/mvpropertylist"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/agorartckit\/agoramusic\/name"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/releaseTime":{"role":"symbol","title":"releaseTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"releaseTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/releaseTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"releaseTime"}],"url":"\/documentation\/agorartckit\/agoramusic\/releasetime"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/poster":{"role":"symbol","title":"poster","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"poster"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/poster","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"poster"}],"url":"\/documentation\/agorartckit\/agoramusic\/poster"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/songCode":{"role":"symbol","title":"songCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"songCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/songCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"songCode"}],"url":"\/documentation\/agorartckit\/agoramusic\/songcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/durationS":{"role":"symbol","title":"durationS","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"durationS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/durationS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"durationS"}],"url":"\/documentation\/agorartckit\/agoramusic\/durations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusic/pitchType":{"role":"symbol","title":"pitchType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitchType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/pitchType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pitchType"}],"url":"\/documentation\/agorartckit\/agoramusic\/pitchtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusic"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusic"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMusic"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/climaxSegmentList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/durationS","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/lyricList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/mvPropertyList","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/name","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/pitchType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/poster","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/releaseTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/singer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/songCode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusic\/type"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusic"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1singer\/title","value":"singer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1singer\/fragments","value":[{"kind":"identifier","text":"singer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1climaxSegmentList\/title","value":"climaxSegmentList"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1climaxSegmentList\/fragments","value":[{"kind":"identifier","text":"climaxSegmentList"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic\/title","value":"AgoraMusic"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic\/fragments","value":[{"kind":"identifier","text":"AgoraMusic"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1lyricList\/title","value":"lyricList"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1lyricList\/fragments","value":[{"kind":"identifier","text":"lyricList"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1mvPropertyList\/title","value":"mvPropertyList"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1mvPropertyList\/fragments","value":[{"kind":"identifier","text":"mvPropertyList"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1releaseTime\/title","value":"releaseTime"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1releaseTime\/fragments","value":[{"kind":"identifier","text":"releaseTime"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1poster\/title","value":"poster"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1poster\/fragments","value":[{"kind":"identifier","text":"poster"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1songCode\/title","value":"songCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1songCode\/fragments","value":[{"kind":"identifier","text":"songCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1durationS\/title","value":"durationS"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1durationS\/fragments","value":[{"kind":"identifier","text":"durationS"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1pitchType\/title","value":"pitchType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusic~1pitchType\/fragments","value":[{"kind":"identifier","text":"pitchType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}