{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The encoded audio observer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}],"title":"AgoraAudioEncodedFrameDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraAudioEncodedFrameDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onMixedEncodedAudioFrame(_:info:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onPlaybackEncodedAudioFrame(_:info:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onRecordEncodedAudioFrame(_:info:)"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegate/onMixedEncodedAudioFrame(_:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onMixedEncodedAudioFrame:info:"}],"role":"symbol","title":"onMixedEncodedAudioFrame(_:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMixedEncodedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedAudioFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedAudioFrameInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets the mixed and encoded audio data of the local and all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onMixedEncodedAudioFrame(_:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegate\/onmixedencodedaudioframe(_:info:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegate":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}],"abstract":[{"type":"text","text":"The encoded audio observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegate/onPlaybackEncodedAudioFrame(_:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onPlaybackEncodedAudioFrame:info:"}],"role":"symbol","title":"onPlaybackEncodedAudioFrame(_:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedAudioFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedAudioFrameInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets the encoded audio data of all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onPlaybackEncodedAudioFrame(_:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegate\/onplaybackencodedaudioframe(_:info:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegate/onRecordEncodedAudioFrame(_:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onRecordEncodedAudioFrame:info:"}],"role":"symbol","title":"onRecordEncodedAudioFrame(_:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecordEncodedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncodedAudioFrameInfo","preciseIdentifier":"c:objc(cs)AgoraEncodedAudioFrameInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Gets the encoded audio data of the local user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onRecordEncodedAudioFrame(_:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegate\/onrecordencodedaudioframe(_:info:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEncodedFrameDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onMixedEncodedAudioFrame(_:info:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onPlaybackEncodedAudioFrame(_:info:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegate\/onRecordEncodedAudioFrame(_:info:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onMixedEncodedAudioFrame(_:info:)\/title","value":"onMixedEncodedAudioFrame:info:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onMixedEncodedAudioFrame(_:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMixedEncodedAudioFrame:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate\/title","value":"AgoraAudioEncodedFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onPlaybackEncodedAudioFrame(_:info:)\/title","value":"onPlaybackEncodedAudioFrame:info:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onPlaybackEncodedAudioFrame(_:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackEncodedAudioFrame:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onRecordEncodedAudioFrame(_:info:)\/title","value":"onRecordEncodedAudioFrame:info:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegate~1onRecordEncodedAudioFrame(_:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRecordEncodedAudioFrame:info:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}