{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideodenoiseroptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideodenoiseroptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video noise reduction options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}],"title":"AgoraVideoDenoiserOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraVideoDenoiserOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions\/level","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions\/mode"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserOptions/level":{"role":"symbol","title":"level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoDenoiserLevel","preciseIdentifier":"c:@E@AgoraVideoDenoiserLevel"}],"abstract":[{"type":"text","text":"Video noise reduction level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions\/level","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"level"}],"url":"\/documentation\/agorartckit\/agoravideodenoiseroptions\/level"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserOptions":{"role":"symbol","title":"AgoraVideoDenoiserOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}],"abstract":[{"type":"text","text":"Video noise reduction options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}],"url":"\/documentation\/agorartckit\/agoravideodenoiseroptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserOptions/mode":{"role":"symbol","title":"mode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoDenoiserMode","preciseIdentifier":"c:@E@AgoraVideoDenoiserMode"}],"abstract":[{"type":"text","text":"Video noise reduction mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions\/mode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mode"}],"url":"\/documentation\/agorartckit\/agoravideodenoiseroptions\/mode"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoDenoiserOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions\/level","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserOptions\/mode"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions~1level\/title","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions~1level\/fragments","value":[{"kind":"identifier","text":"level"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions\/title","value":"AgoraVideoDenoiserOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions~1mode\/title","value":"mode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserOptions~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}