{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWarningCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorawarningcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorawarningcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admGlitchState","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admImproperSettings","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admInterruption","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admPlaybackMalfunction","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admPlayoutAudioLowlevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordAudioLowlevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordAudioSilence","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordMalfunction","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRuntimePlayoutWarning","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRuntimeRecordingWarning","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/apmHowling","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/audioMixingOpenError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/initVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/invalidView","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/lookupChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/lookupChannelTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/noAvailableChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelInvalidTicket","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelTryNextVos","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/pending","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/setClientRoleNotAuthorized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/setClientRoleTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/switchLiveVideoTimeout"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWarningCode"}],"title":"AgoraWarningCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraWarningCode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorawarningcode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/setClientRoleNotAuthorized":{"role":"symbol","title":"AgoraWarningCode.setClientRoleNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRoleNotAuthorized"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/setClientRoleNotAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeSetClientRoleNotAuthorized"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/setclientrolenotauthorized"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/openChannelTimeout":{"role":"symbol","title":"AgoraWarningCode.openChannelTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelTimeout"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/openchanneltimeout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/lookupChannelRejected":{"role":"symbol","title":"AgoraWarningCode.lookupChannelRejected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lookupChannelRejected"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/lookupChannelRejected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeLookupChannelRejected"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/lookupchannelrejected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/apmHowling":{"role":"symbol","title":"AgoraWarningCode.apmHowling","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"apmHowling"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/apmHowling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeApmHowling"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/apmhowling"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/pending":{"role":"symbol","title":"AgoraWarningCode.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodePending"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/pending"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/openChannelInvalidTicket":{"role":"symbol","title":"AgoraWarningCode.openChannelInvalidTicket","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelInvalidTicket"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelInvalidTicket","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelInvalidTicket"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/openchannelinvalidticket"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/audioMixingOpenError":{"role":"symbol","title":"AgoraWarningCode.audioMixingOpenError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioMixingOpenError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/audioMixingOpenError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAudioMixingOpenError"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/audiomixingopenerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admPlaybackMalfunction":{"role":"symbol","title":"AgoraWarningCode.admPlaybackMalfunction","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admPlaybackMalfunction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admPlaybackMalfunction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmPlaybackMalfunction"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admplaybackmalfunction"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admRecordAudioLowlevel":{"role":"symbol","title":"AgoraWarningCode.admRecordAudioLowlevel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRecordAudioLowlevel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordAudioLowlevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmRecordAudioLowlevel"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admrecordaudiolowlevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/initVideo":{"role":"symbol","title":"AgoraWarningCode.initVideo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initVideo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/initVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeInitVideo"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/initvideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admRecordMalfunction":{"role":"symbol","title":"AgoraWarningCode.admRecordMalfunction","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRecordMalfunction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordMalfunction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmRecordMalfunction"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admrecordmalfunction"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/openChannelTryNextVos":{"role":"symbol","title":"AgoraWarningCode.openChannelTryNextVos","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelTryNextVos"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelTryNextVos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelTryNextVos"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/openchanneltrynextvos"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admPlayoutAudioLowlevel":{"role":"symbol","title":"AgoraWarningCode.admPlayoutAudioLowlevel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admPlayoutAudioLowlevel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admPlayoutAudioLowlevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmPlayoutAudioLowlevel"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admplayoutaudiolowlevel"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/openChannelRejected":{"role":"symbol","title":"AgoraWarningCode.openChannelRejected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelRejected"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelRejected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelRejected"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/openchannelrejected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admImproperSettings":{"role":"symbol","title":"AgoraWarningCode.admImproperSettings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admImproperSettings"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admImproperSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmImproperSettings"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admimpropersettings"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/noAvailableChannel":{"role":"symbol","title":"AgoraWarningCode.noAvailableChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noAvailableChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/noAvailableChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeNoAvailableChannel"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/noavailablechannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/setClientRoleTimeout":{"role":"symbol","title":"AgoraWarningCode.setClientRoleTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRoleTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/setClientRoleTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeSetClientRoleTimeout"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/setclientroletimeout"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/switchLiveVideoTimeout":{"role":"symbol","title":"AgoraWarningCode.switchLiveVideoTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchLiveVideoTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/switchLiveVideoTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeSwitchLiveVideoTimeout"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/switchlivevideotimeout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorawarningcode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/lookupChannelTimeout":{"role":"symbol","title":"AgoraWarningCode.lookupChannelTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lookupChannelTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/lookupChannelTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeLookupChannelTimeout"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/lookupchanneltimeout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admRuntimePlayoutWarning":{"role":"symbol","title":"AgoraWarningCode.admRuntimePlayoutWarning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRuntimePlayoutWarning"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRuntimePlayoutWarning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmRuntimePlayoutWarning"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admruntimeplayoutwarning"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorawarningcode\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admRuntimeRecordingWarning":{"role":"symbol","title":"AgoraWarningCode.admRuntimeRecordingWarning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRuntimeRecordingWarning"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRuntimeRecordingWarning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmRuntimeRecordingWarning"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admruntimerecordingwarning"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/invalidView":{"role":"symbol","title":"AgoraWarningCode.invalidView","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidView"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/invalidView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeInvalidView"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/invalidview"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admInterruption":{"role":"symbol","title":"AgoraWarningCode.admInterruption","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admInterruption"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admInterruption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmInterruption"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/adminterruption"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admRecordAudioSilence":{"role":"symbol","title":"AgoraWarningCode.admRecordAudioSilence","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRecordAudioSilence"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordAudioSilence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmRecordAudioSilence"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admrecordaudiosilence"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admGlitchState":{"role":"symbol","title":"AgoraWarningCode.admGlitchState","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admGlitchState"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admGlitchState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmGlitchState"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admglitchstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode":{"role":"symbol","title":"AgoraWarningCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWarningCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCode"}],"url":"\/documentation\/agorartckit\/agorawarningcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraWarningCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraWarningCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admGlitchState","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admImproperSettings","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admInterruption","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admPlaybackMalfunction","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admPlayoutAudioLowlevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordAudioLowlevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordAudioSilence","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRecordMalfunction","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRuntimePlayoutWarning","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admRuntimeRecordingWarning","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/apmHowling","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/audioMixingOpenError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/initVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/invalidView","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/lookupChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/lookupChannelTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/noAvailableChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelInvalidTicket","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/openChannelTryNextVos","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/pending","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/setClientRoleNotAuthorized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/setClientRoleTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/switchLiveVideoTimeout"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWarningCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1setClientRoleNotAuthorized\/title","value":"AgoraWarningCodeSetClientRoleNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1setClientRoleNotAuthorized\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeSetClientRoleNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelTimeout\/title","value":"AgoraWarningCodeOpenChannelTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1lookupChannelRejected\/title","value":"AgoraWarningCodeLookupChannelRejected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1lookupChannelRejected\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeLookupChannelRejected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1apmHowling\/title","value":"AgoraWarningCodeApmHowling"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1apmHowling\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeApmHowling"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1pending\/title","value":"AgoraWarningCodePending"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1pending\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodePending"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelInvalidTicket\/title","value":"AgoraWarningCodeOpenChannelInvalidTicket"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelInvalidTicket\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelInvalidTicket"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1audioMixingOpenError\/title","value":"AgoraWarningCodeAudioMixingOpenError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1audioMixingOpenError\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAudioMixingOpenError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admPlaybackMalfunction\/title","value":"AgoraWarningCodeAdmPlaybackMalfunction"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admPlaybackMalfunction\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmPlaybackMalfunction"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRecordAudioLowlevel\/title","value":"AgoraWarningCodeAdmRecordAudioLowlevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRecordAudioLowlevel\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmRecordAudioLowlevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1initVideo\/title","value":"AgoraWarningCodeInitVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1initVideo\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeInitVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRecordMalfunction\/title","value":"AgoraWarningCodeAdmRecordMalfunction"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRecordMalfunction\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmRecordMalfunction"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelTryNextVos\/title","value":"AgoraWarningCodeOpenChannelTryNextVos"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelTryNextVos\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelTryNextVos"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admPlayoutAudioLowlevel\/title","value":"AgoraWarningCodeAdmPlayoutAudioLowlevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admPlayoutAudioLowlevel\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmPlayoutAudioLowlevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelRejected\/title","value":"AgoraWarningCodeOpenChannelRejected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1openChannelRejected\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeOpenChannelRejected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admImproperSettings\/title","value":"AgoraWarningCodeAdmImproperSettings"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admImproperSettings\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmImproperSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1noAvailableChannel\/title","value":"AgoraWarningCodeNoAvailableChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1noAvailableChannel\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeNoAvailableChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1setClientRoleTimeout\/title","value":"AgoraWarningCodeSetClientRoleTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1setClientRoleTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeSetClientRoleTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1switchLiveVideoTimeout\/title","value":"AgoraWarningCodeSwitchLiveVideoTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1switchLiveVideoTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeSwitchLiveVideoTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1lookupChannelTimeout\/title","value":"AgoraWarningCodeLookupChannelTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1lookupChannelTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeLookupChannelTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRuntimePlayoutWarning\/title","value":"AgoraWarningCodeAdmRuntimePlayoutWarning"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRuntimePlayoutWarning\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmRuntimePlayoutWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRuntimeRecordingWarning\/title","value":"AgoraWarningCodeAdmRuntimeRecordingWarning"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRuntimeRecordingWarning\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmRuntimeRecordingWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1invalidView\/title","value":"AgoraWarningCodeInvalidView"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1invalidView\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeInvalidView"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admInterruption\/title","value":"AgoraWarningCodeAdmInterruption"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admInterruption\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmInterruption"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRecordAudioSilence\/title","value":"AgoraWarningCodeAdmRecordAudioSilence"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admRecordAudioSilence\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmRecordAudioSilence"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admGlitchState\/title","value":"AgoraWarningCodeAdmGlitchState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admGlitchState\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmGlitchState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode\/title","value":"AgoraWarningCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}