{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoformat"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The video pixel format."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFormat"}],"title":"AgoraVideoFormat","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoFormat","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormat"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/BGRA","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/I420","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/I422","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/NV12","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/NV21","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/RGBA","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelBGRA","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelI420","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelNV12","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/default"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/cvPixelBGRA":{"role":"symbol","title":"AgoraVideoFormat.cvPixelBGRA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvPixelBGRA"}],"abstract":[{"type":"text","text":"14: The format is CVPixelBufferRef BGRA."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelBGRA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatCVPixelBGRA"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/cvpixelbgra"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat":{"role":"symbol","title":"AgoraVideoFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFormat"}],"abstract":[{"type":"text","text":"The video pixel format."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormat"}],"url":"\/documentation\/agorartckit\/agoravideoformat"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/cvPixelNV12":{"role":"symbol","title":"AgoraVideoFormat.cvPixelNV12","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvPixelNV12"}],"abstract":[{"type":"text","text":"12: The format is CVPixelBufferRef NV12."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelNV12","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatCVPixelNV12"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/cvpixelnv12"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/I420":{"role":"symbol","title":"AgoraVideoFormat.I420","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"I420"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/I420","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatI420"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/i420"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/I422":{"role":"symbol","title":"AgoraVideoFormat.I422","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"I422"}],"abstract":[{"type":"text","text":"16: The format is I422."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/I422","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatI422"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/i422"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/NV12":{"role":"symbol","title":"AgoraVideoFormat.NV12","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NV12"}],"abstract":[{"type":"text","text":"8: The format is NV12."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/NV12","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatNV12"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/nv12"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/NV21":{"role":"symbol","title":"AgoraVideoFormat.NV21","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NV21"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/NV21","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatNV21"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/nv21"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/default":{"role":"symbol","title":"AgoraVideoFormat.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"0: Raw video pixel format."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatDefault"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/default"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideoformat\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/RGBA":{"role":"symbol","title":"AgoraVideoFormat.RGBA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RGBA"}],"abstract":[{"type":"text","text":"4: The format is RGBA."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/RGBA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatRGBA"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/rgba"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoformat\/equatable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/cvPixelI420":{"role":"symbol","title":"AgoraVideoFormat.cvPixelI420","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvPixelI420"}],"abstract":[{"type":"text","text":"13: The format is CVPixelBufferRef I420."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelI420","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatCVPixelI420"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/cvpixeli420"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoformat\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFormat/BGRA":{"role":"symbol","title":"AgoraVideoFormat.BGRA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BGRA"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/BGRA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFormatBGRA"}],"url":"\/documentation\/agorartckit\/agoravideoformat\/bgra"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormat"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoFormat"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/BGRA","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/I420","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/I422","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/NV12","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/NV21","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/RGBA","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelBGRA","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelI420","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/cvPixelNV12","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFormat\/default"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1cvPixelBGRA\/title","value":"AgoraVideoFormatCVPixelBGRA"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1cvPixelBGRA\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatCVPixelBGRA"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat\/title","value":"AgoraVideoFormat"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1cvPixelNV12\/title","value":"AgoraVideoFormatCVPixelNV12"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1cvPixelNV12\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatCVPixelNV12"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1I420\/title","value":"AgoraVideoFormatI420"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1I420\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatI420"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1I422\/title","value":"AgoraVideoFormatI422"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1I422\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatI422"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1NV12\/title","value":"AgoraVideoFormatNV12"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1NV12\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatNV12"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1NV21\/title","value":"AgoraVideoFormatNV21"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1NV21\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatNV21"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1default\/title","value":"AgoraVideoFormatDefault"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1default\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1RGBA\/title","value":"AgoraVideoFormatRGBA"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1RGBA\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatRGBA"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1cvPixelI420\/title","value":"AgoraVideoFormatCVPixelI420"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1cvPixelI420\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatCVPixelI420"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1BGRA\/title","value":"AgoraVideoFormatBGRA"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFormat~1BGRA\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFormatBGRA"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}