{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralogconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralogconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration of Agora SDK log files."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogConfig"}],"title":"AgoraLogConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLogConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLogConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/filePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/fileSizeInKB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/level"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogConfig":{"role":"symbol","title":"AgoraLogConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogConfig"}],"abstract":[{"type":"text","text":"Configuration of Agora SDK log files."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogConfig"}],"url":"\/documentation\/agorartckit\/agoralogconfig"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogConfig/filePath":{"role":"symbol","title":"filePath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The complete path of the log files. Ensure that the path for the log file"},{"type":"text","text":" "},{"type":"text","text":"exists and is writable. You can use this parameter to rename the log"},{"type":"text","text":" "},{"type":"text","text":"files.The default path is AppSandbox\/Library\/caches\/agorasdk.log."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/filePath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"filePath"}],"url":"\/documentation\/agorartckit\/agoralogconfig\/filepath"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogConfig/level":{"role":"symbol","title":"level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLogLevel","preciseIdentifier":"c:@E@AgoraLogLevel"}],"abstract":[{"type":"text","text":"The output level of the SDK log file. See AgoraLogLevel .For example, if you"},{"type":"text","text":" "},{"type":"text","text":"set the log level to WARN, the SDK outputs the logs within levels FATAL,"},{"type":"text","text":" "},{"type":"text","text":"ERROR, and WARN."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/level","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"level"}],"url":"\/documentation\/agorartckit\/agoralogconfig\/level"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogConfig/fileSizeInKB":{"role":"symbol","title":"fileSizeInKB","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSizeInKB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The size (KB) of an agorasdk.log file. The value range is [128,1024]. The"},{"type":"text","text":" "},{"type":"text","text":"default value is 1,024 KB. If you set fileSizeInKByte to a value lower than"},{"type":"text","text":" "},{"type":"text","text":"128 KB, the SDK adjusts it to 128 KB. If you set fileSizeInKBytes to a value"},{"type":"text","text":" "},{"type":"text","text":"higher than 1,024 KB, the SDK adjusts it to 1,024 KB."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/fileSizeInKB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileSizeInKB"}],"url":"\/documentation\/agorartckit\/agoralogconfig\/filesizeinkb"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLogConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLogConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLogConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/filePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/fileSizeInKB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogConfig\/level"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig\/title","value":"AgoraLogConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLogConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig~1filePath\/title","value":"filePath"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig~1filePath\/fragments","value":[{"kind":"identifier","text":"filePath"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig~1level\/title","value":"level"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig~1level\/fragments","value":[{"kind":"identifier","text":"level"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig~1fileSizeInKB\/title","value":"fileSizeInKB"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogConfig~1fileSizeInKB\/fragments","value":[{"kind":"identifier","text":"fileSizeInKB"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}