{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravoicebeautifierpreset"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"title":"AgoraVoiceBeautifierPreset","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVoiceBeautifierPreset","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierFresh","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierMagnetic","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierVitality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetOff","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetSingingBeautifier","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformatRinging","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationClear","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationDeep","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationFalsetto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationFull","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationMellow","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationResounding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationVigorous","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/ultraHighQuality"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformatRinging":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformatRinging","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformatRinging"}],"abstract":[{"type":"text","text":"A more ringing voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformatRinging","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformatRinging"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformatringing"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationFalsetto":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationFalsetto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationFalsetto"}],"abstract":[{"type":"text","text":"Falsetto."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationFalsetto","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationFalsetto"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationfalsetto"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationClear":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationClear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationClear"}],"abstract":[{"type":"text","text":"A clearer voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationClear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationClear"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationclear"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationResounding":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationResounding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationResounding"}],"abstract":[{"type":"text","text":"A more resounding voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationResounding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationResounding"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationresounding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationFull":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationFull","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationFull"}],"abstract":[{"type":"text","text":"A fuller voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationFull","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationFull"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationfull"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationMellow":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationMellow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationMellow"}],"abstract":[{"type":"text","text":"A mellower voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationMellow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationMellow"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationmellow"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/presetChatBeautifierVitality":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.presetChatBeautifierVitality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetChatBeautifierVitality"}],"abstract":[{"type":"text","text":"A more vital voice.Agora recommends using this enumerator to process a"},{"type":"text","text":" "},{"type":"text","text":"female-sounding voice; otherwise, you may experience vocal distortion."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierVitality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetChatBeautifierVitality"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetchatbeautifiervitality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/ultraHighQuality":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.ultraHighQuality","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ultraHighQuality"}],"abstract":[{"type":"text","text":"A ultra-high quality voice, which makes the audio clearer and restores more"},{"type":"text","text":" "},{"type":"text","text":"details.To achieve better audio effect quality, Agora recommends that you"},{"type":"text","text":" "},{"type":"text","text":"set the profile of setAudioProfile [2\/2] to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQuality(4) or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioProfileMusicHighQualityStereo(5) and scenario to"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioScenarioGameStreaming(3) before calling setVoiceBeautifierPreset"},{"type":"text","text":" "},{"type":"text","text":".If you have an audio capturing device that can already restore audio"},{"type":"text","text":" "},{"type":"text","text":"details to a high degree, Agora recommends that you do not enable"},{"type":"text","text":" "},{"type":"text","text":"ultra-high quality; otherwise, the SDK may over-restore audio details, and"},{"type":"text","text":" "},{"type":"text","text":"you may not hear the anticipated voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/ultraHighQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierUltraHighQuality"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/ultrahighquality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationVigorous":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationVigorous","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationVigorous"}],"abstract":[{"type":"text","text":"A more vigorous voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationVigorous","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationVigorous"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationvigorous"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/timbreTransformationDeep":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.timbreTransformationDeep","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timbreTransformationDeep"}],"abstract":[{"type":"text","text":"A deep voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationDeep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationDeep"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/timbretransformationdeep"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/presetSingingBeautifier":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.presetSingingBeautifier","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetSingingBeautifier"}],"abstract":[{"type":"text","text":"Singing beautifier effect.If you call setVoiceBeautifierPreset"},{"type":"text","text":" "},{"type":"text","text":"(AgoraVoiceBeautifierPresetSingingBeautifier), you can beautify a"},{"type":"text","text":" "},{"type":"text","text":"male-sounding voice and add a reverberation effect that sounds like singing"},{"type":"text","text":" "},{"type":"text","text":"in a small room. Agora recommends using this enumerator to process a"},{"type":"text","text":" "},{"type":"text","text":"male-sounding voice; otherwise, you might experience vocal distortion.If"},{"type":"text","text":" "},{"type":"text","text":"you call setVoiceBeautifierParameters"},{"type":"text","text":" "},{"type":"text","text":"(AgoraVoiceBeautifierPresetSingingBeautifier, param1, param2), you can"},{"type":"text","text":" "},{"type":"text","text":"beautify a male or female-sounding voice and add a reverberation effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetSingingBeautifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetSingingBeautifier"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetsingingbeautifier"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset":{"role":"symbol","title":"AgoraVoiceBeautifierPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"abstract":[{"type":"text","text":"The options for SDK preset voice beautifier effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/presetChatBeautifierFresh":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.presetChatBeautifierFresh","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetChatBeautifierFresh"}],"abstract":[{"type":"text","text":"A fresher voice.Agora recommends using this enumerator to process a"},{"type":"text","text":" "},{"type":"text","text":"female-sounding voice; otherwise, you may experience vocal distortion."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierFresh","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetChatBeautifierFresh"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetchatbeautifierfresh"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/presetChatBeautifierMagnetic":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.presetChatBeautifierMagnetic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetChatBeautifierMagnetic"}],"abstract":[{"type":"text","text":"A more magnetic voice.Agora recommends using this enumerator to process a"},{"type":"text","text":" "},{"type":"text","text":"male-sounding voice; otherwise, you may experience vocal distortion."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierMagnetic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetChatBeautifierMagnetic"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetchatbeautifiermagnetic"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVoiceBeautifierPreset/presetOff":{"role":"symbol","title":"AgoraVoiceBeautifierPreset.presetOff","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presetOff"}],"abstract":[{"type":"text","text":"Turn off voice beautifier effects and use the original voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetOff","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetOff"}],"url":"\/documentation\/agorartckit\/agoravoicebeautifierpreset\/presetoff"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierFresh","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierMagnetic","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetChatBeautifierVitality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetOff","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/presetSingingBeautifier","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformatRinging","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationClear","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationDeep","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationFalsetto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationFull","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationMellow","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationResounding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/timbreTransformationVigorous","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVoiceBeautifierPreset\/ultraHighQuality"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformatRinging\/title","value":"AgoraVoiceBeautifierTimbreTransformatRinging"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformatRinging\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformatRinging"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationFalsetto\/title","value":"AgoraVoiceBeautifierTimbreTransformationFalsetto"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationFalsetto\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationFalsetto"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationClear\/title","value":"AgoraVoiceBeautifierTimbreTransformationClear"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationClear\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationClear"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationResounding\/title","value":"AgoraVoiceBeautifierTimbreTransformationResounding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationResounding\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationResounding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationFull\/title","value":"AgoraVoiceBeautifierTimbreTransformationFull"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationFull\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationFull"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationMellow\/title","value":"AgoraVoiceBeautifierTimbreTransformationMellow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationMellow\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationMellow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetChatBeautifierVitality\/title","value":"AgoraVoiceBeautifierPresetChatBeautifierVitality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetChatBeautifierVitality\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetChatBeautifierVitality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1ultraHighQuality\/title","value":"AgoraVoiceBeautifierUltraHighQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1ultraHighQuality\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierUltraHighQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationVigorous\/title","value":"AgoraVoiceBeautifierTimbreTransformationVigorous"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationVigorous\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationVigorous"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationDeep\/title","value":"AgoraVoiceBeautifierTimbreTransformationDeep"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1timbreTransformationDeep\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierTimbreTransformationDeep"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetSingingBeautifier\/title","value":"AgoraVoiceBeautifierPresetSingingBeautifier"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetSingingBeautifier\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetSingingBeautifier"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/title","value":"AgoraVoiceBeautifierPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetChatBeautifierFresh\/title","value":"AgoraVoiceBeautifierPresetChatBeautifierFresh"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetChatBeautifierFresh\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetChatBeautifierFresh"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetChatBeautifierMagnetic\/title","value":"AgoraVoiceBeautifierPresetChatBeautifierMagnetic"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetChatBeautifierMagnetic\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetChatBeautifierMagnetic"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetOff\/title","value":"AgoraVoiceBeautifierPresetOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVoiceBeautifierPreset~1presetOff\/fragments","value":[{"kind":"identifier","text":"AgoraVoiceBeautifierPresetOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}