{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodingPreference"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since v4.1.0"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodingpreference"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodingpreference"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video encoder preference."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodingPreference"}],"title":"AgoraEncodingPreference","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraEncodingPreference","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreference"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferAuto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferhardware","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/prefersoftware"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/preferAuto":{"role":"symbol","title":"AgoraEncodingPreference.preferAuto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferAuto"}],"abstract":[{"type":"text","text":"-1: Adaptive preference. The SDK automatically selects the optimal encoding type for encoding based on factors such as platform and device type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferAuto","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreferAuto"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference\/preferauto"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraencodingpreference\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference":{"role":"symbol","title":"AgoraEncodingPreference","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodingPreference"}],"abstract":[{"type":"text","text":"Video encoder preference."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreference"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraencodingpreference\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/preferhardware":{"role":"symbol","title":"AgoraEncodingPreference.preferhardware","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferhardware"}],"abstract":[{"type":"text","text":"1: Hardware encoding preference. The SDK prefers a hardware encoder for video encoding. When the device does not support hardware encoding, the SDK automatically uses software encoding and reports the currently used video encoder type through hwEncoderAccelerating in the localVideoStats callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferhardware","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPreferhardware"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference\/preferhardware"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraencodingpreference\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodingPreference/prefersoftware":{"role":"symbol","title":"AgoraEncodingPreference.prefersoftware","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefersoftware"}],"abstract":[{"type":"text","text":"0: Software coding preference. The SDK prefers software encoders for video encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/prefersoftware","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodingPrefersoftware"}],"url":"\/documentation\/agorartckit\/agoraencodingpreference\/prefersoftware"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncodingPreference"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreference"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEncodingPreference"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferAuto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/preferhardware","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodingPreference\/prefersoftware"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodingPreference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1preferAuto\/title","value":"AgoraEncodingPreferAuto"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1preferAuto\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreferAuto"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/title","value":"AgoraEncodingPreference"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreference"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1preferhardware\/title","value":"AgoraEncodingPreferhardware"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1preferhardware\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPreferhardware"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1prefersoftware\/title","value":"AgoraEncodingPrefersoftware"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodingPreference~1prefersoftware\/fragments","value":[{"kind":"identifier","text":"AgoraEncodingPrefersoftware"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}