{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since v4.2.0"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideotranscodererror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The error code of the local video mixing failure."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"title":"AgoraVideoTranscoderError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoTranscoderError","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/OK","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidImagePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidLayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidVideoSourceType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/unsupportImageFormat","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/videoSourceNotReady"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/invalidVideoSourceType":{"role":"symbol","title":"AgoraVideoTranscoderError.invalidVideoSourceType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidVideoSourceType"}],"abstract":[{"type":"text","text":"2: The video source type is invalid. You need to re-specify the supported video source type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/invalidvideosourcetype"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideotranscodererror\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/invalidLayout":{"role":"symbol","title":"AgoraVideoTranscoderError.invalidLayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidLayout"}],"abstract":[{"type":"text","text":"5: The video encoding resolution after video mixing is invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidLayout"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/invalidlayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/unsupportImageFormat":{"role":"symbol","title":"AgoraVideoTranscoderError.unsupportImageFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportImageFormat"}],"abstract":[{"type":"text","text":"4: The image format is invalid. Make sure the image format is one of PNG, JPEG, or GIF."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/unsupportImageFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorUnsupportImageFormat"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/unsupportimageformat"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideotranscodererror\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError":{"role":"symbol","title":"AgoraVideoTranscoderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"abstract":[{"type":"text","text":"The error code of the local video mixing failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/videoSourceNotReady":{"role":"symbol","title":"AgoraVideoTranscoderError.videoSourceNotReady","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSourceNotReady"}],"abstract":[{"type":"text","text":"1: The selected video source has not started video capture. You need to create a video track for it and start video capture."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/videoSourceNotReady","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorVideoSourceNotReady"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/videosourcenotready"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/OK":{"role":"symbol","title":"AgoraVideoTranscoderError.OK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/OK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorOK"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/ok"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/invalidImagePath":{"role":"symbol","title":"AgoraVideoTranscoderError.invalidImagePath","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidImagePath"}],"abstract":[{"type":"text","text":"3: The image path is invalid. You need to re-specify the correct image path."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidImagePath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidImagePath"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/invalidimagepath"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/internal":{"role":"symbol","title":"AgoraVideoTranscoderError.internal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"}],"abstract":[{"type":"text","text":"20: Unknown internal error."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/internal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInternal"}],"url":"\/documentation\/agorartckit\/agoravideotranscodererror\/internal"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoTranscoderError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideotranscodererror\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoTranscoderError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/OK","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidImagePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidLayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/invalidVideoSourceType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/unsupportImageFormat","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoTranscoderError\/videoSourceNotReady"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoTranscoderError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidVideoSourceType\/title","value":"AgoraVideoTranscoderErrorInvalidVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidVideoSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidLayout\/title","value":"AgoraVideoTranscoderErrorInvalidLayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidLayout\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidLayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1unsupportImageFormat\/title","value":"AgoraVideoTranscoderErrorUnsupportImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1unsupportImageFormat\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorUnsupportImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/title","value":"AgoraVideoTranscoderError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1videoSourceNotReady\/title","value":"AgoraVideoTranscoderErrorVideoSourceNotReady"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1videoSourceNotReady\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorVideoSourceNotReady"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1OK\/title","value":"AgoraVideoTranscoderErrorOK"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1OK\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorOK"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidImagePath\/title","value":"AgoraVideoTranscoderErrorInvalidImagePath"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1invalidImagePath\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInvalidImagePath"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1internal\/title","value":"AgoraVideoTranscoderErrorInternal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoTranscoderError~1internal\/fragments","value":[{"kind":"identifier","text":"AgoraVideoTranscoderErrorInternal"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}