{"seeAlsoSections":[{"title":"Advanced Classes","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"title":"AgoraRtcLocalAudioStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRtcLocalAudioStats","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}]},"abstract":[{"type":"text","text":"Local audio statistics."}],"sections":[],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/audioDeviceDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/internalCodec","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/numChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/sentBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/sentSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/txPacketLossRate"]}],"variants":[{"paths":["\/documentation\/agorartckit\/agorartclocalaudiostats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartclocalaudiostats"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats/numChannels":{"role":"symbol","title":"numChannels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The number of audio channels."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/numChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numChannels"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats\/numchannels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats/txPacketLossRate":{"role":"symbol","title":"txPacketLossRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txPacketLossRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The packet loss rate (%) from the local client to the Agora server before"},{"type":"text","text":" "},{"type":"text","text":"applying the anti-packet loss strategies."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/txPacketLossRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txPacketLossRate"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats\/txpacketlossrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset":{"role":"symbol","title":"AgoraAudioEffectPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"abstract":[{"type":"text","text":"Preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"To get better audio effects, Agora recommends calling setAudioProfile [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"and setting the profile parameter as recommended below before using the"},{"type":"text","text":" "},{"type":"text","text":"preset audio effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats/internalCodec":{"role":"symbol","title":"internalCodec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalCodec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The internal payload codec."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/internalCodec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"internalCodec"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats\/internalcodec"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats/sentSampleRate":{"role":"symbol","title":"sentSampleRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sentSampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The sampling rate (Hz) of sending the local user’s audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/sentSampleRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sentSampleRate"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats\/sentsamplerate"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig":{"role":"symbol","title":"AgoraEncryptionConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionConfig"}],"abstract":[{"type":"text","text":"Built-in encryption configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionConfig"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats":{"role":"symbol","title":"AgoraRtcLocalAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"abstract":[{"type":"text","text":"Local audio statistics."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame":{"role":"symbol","title":"AgoraVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrame"}],"abstract":[{"type":"text","text":"The external video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrame"}],"url":"\/documentation\/agorartckit\/agoravideoframe"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats/audioDeviceDelay":{"role":"symbol","title":"audioDeviceDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDeviceDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The delay of the audio device module when playing or recording audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/audioDeviceDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioDeviceDelay"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats\/audiodevicedelay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats/sentBitrate":{"role":"symbol","title":"sentBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sentBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The average bitrate (Kbps) of sending the local user’s audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/sentBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sentBitrate"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats\/sentbitrate"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcLocalAudioStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/audioDeviceDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/internalCodec","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/numChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/sentBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/sentSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats\/txPacketLossRate"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Advanced Classes","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalAudioStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1numChannels\/title","value":"numChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1numChannels\/fragments","value":[{"kind":"identifier","text":"numChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1txPacketLossRate\/title","value":"txPacketLossRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1txPacketLossRate\/fragments","value":[{"kind":"identifier","text":"txPacketLossRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1internalCodec\/title","value":"internalCodec"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1internalCodec\/fragments","value":[{"kind":"identifier","text":"internalCodec"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1sentSampleRate\/title","value":"sentSampleRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1sentSampleRate\/fragments","value":[{"kind":"identifier","text":"sentSampleRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/title","value":"AgoraEncryptionConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/title","value":"AgoraRtcLocalAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/title","value":"AgoraVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1audioDeviceDelay\/title","value":"audioDeviceDelay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1audioDeviceDelay\/fragments","value":[{"kind":"identifier","text":"audioDeviceDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1sentBitrate\/title","value":"sentBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats~1sentBitrate\/fragments","value":[{"kind":"identifier","text":"sentBitrate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}