{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The current CDN streaming state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"title":"AgoraDirectCdnStreamingState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraDirectCdnStreamingState","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/recovering","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/running","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/stopped"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/running":{"role":"symbol","title":"AgoraDirectCdnStreamingState.running","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"running"}],"abstract":[{"type":"text","text":"1: Streams are being pushed to the CDN. The SDK returns this value when you"},{"type":"text","text":" "},{"type":"text","text":"call the startDirectCdnStreaming method to push streams to the CDN."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/running","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateRunning"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/running"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/equatable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/idle":{"role":"symbol","title":"AgoraDirectCdnStreamingState.idle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"abstract":[{"type":"text","text":"0: The initial state before the CDN streaming starts."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/idle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateIdle"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/idle"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/stopped":{"role":"symbol","title":"AgoraDirectCdnStreamingState.stopped","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"abstract":[{"type":"text","text":"2: Stops pushing streams to the CDN. The SDK returns this value when you"},{"type":"text","text":" "},{"type":"text","text":"call the stopDirectCdnStreaming method to stop pushing streams to the CDN."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/stopped","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateStopped"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/stopped"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/recovering":{"role":"symbol","title":"AgoraDirectCdnStreamingState.recovering","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recovering"}],"abstract":[{"type":"text","text":"4: Tries to reconnect the Agora server to the CDN. The SDK attempts to"},{"type":"text","text":" "},{"type":"text","text":"reconnect a maximum of 10 times; if the connection is not restored, the"},{"type":"text","text":" "},{"type":"text","text":"streaming state becomes AgoraDirectCdnStreamingStateFailed."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/recovering","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateRecovering"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/recovering"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/failed":{"role":"symbol","title":"AgoraDirectCdnStreamingState.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"3: Fails to push streams to the CDN. You can troubleshoot the issue with"},{"type":"text","text":" "},{"type":"text","text":"the information reported by the onDirectCdnStreamingStateChanged callback,"},{"type":"text","text":" "},{"type":"text","text":"and then push streams to the CDN again."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateFailed"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/failed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState":{"role":"symbol","title":"AgoraDirectCdnStreamingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"abstract":[{"type":"text","text":"The current CDN streaming state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDirectCdnStreamingState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/recovering","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/running","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState\/stopped"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1running\/title","value":"AgoraDirectCdnStreamingStateRunning"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1running\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateRunning"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1idle\/title","value":"AgoraDirectCdnStreamingStateIdle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1idle\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateIdle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1stopped\/title","value":"AgoraDirectCdnStreamingStateStopped"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1stopped\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateStopped"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1recovering\/title","value":"AgoraDirectCdnStreamingStateRecovering"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1recovering\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateRecovering"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1failed\/title","value":"AgoraDirectCdnStreamingStateFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStateFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState\/title","value":"AgoraDirectCdnStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}