{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoqualityadaptindication"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoqualityadaptindication"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Quality change of the local video in terms of target frame rate and target bit rate since last count."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"title":"AgoraVideoQualityAdaptIndication","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoQualityAdaptIndication","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/downBandwidth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/none","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/upBandwidth"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/downBandwidth":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication.downBandwidth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downBandwidth"}],"abstract":[{"type":"text","text":"2: The local video quality deteriorates because the network bandwidth decreases."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/downBandwidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptDownBandwidth"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/downbandwidth"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"abstract":[{"type":"text","text":"Quality change of the local video in terms of target frame rate and target bit rate since last count."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/none":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"0: The local video quality stays the same."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptNone"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/none"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoQualityAdaptIndication/upBandwidth":{"role":"symbol","title":"AgoraVideoQualityAdaptIndication.upBandwidth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upBandwidth"}],"abstract":[{"type":"text","text":"1: The local video quality improves because the network bandwidth increases."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/upBandwidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoQualityAdaptUpBandwidth"}],"url":"\/documentation\/agorartckit\/agoravideoqualityadaptindication\/upbandwidth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoQualityAdaptIndication"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/downBandwidth","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/none","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoQualityAdaptIndication\/upBandwidth"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1downBandwidth\/title","value":"AgoraVideoQualityAdaptDownBandwidth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1downBandwidth\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptDownBandwidth"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/title","value":"AgoraVideoQualityAdaptIndication"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptIndication"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1none\/title","value":"AgoraVideoQualityAdaptNone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1none\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptNone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1upBandwidth\/title","value":"AgoraVideoQualityAdaptUpBandwidth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoQualityAdaptIndication~1upBandwidth\/fragments","value":[{"kind":"identifier","text":"AgoraVideoQualityAdaptUpBandwidth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}