{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediaplayerevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediaplayerevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Media player events."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"title":"AgoraMediaPlayerEvent","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraMediaPlayerEvent","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/audioTrackChanged","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/bufferLow","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/bufferRecover","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/firstDisplayed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStart","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStop","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/reachCacheFileMaxCount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/reachCacheFileMaxSize","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekBegin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekComplete","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchBegin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchComplete","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenStart","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenSucceed"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/tryOpenFailed":{"role":"symbol","title":"AgoraMediaPlayerEvent.tryOpenFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryOpenFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventTryOpenFailed"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/tryopenfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediaplayerevent\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediaplayerevent\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/switchBegin":{"role":"symbol","title":"AgoraMediaPlayerEvent.switchBegin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchBegin"}],"abstract":[{"type":"text","text":"10: The player starts switching the media resource."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchBegin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSwitchBegin"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/switchbegin"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/switchComplete":{"role":"symbol","title":"AgoraMediaPlayerEvent.switchComplete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchComplete"}],"abstract":[{"type":"text","text":"11: Media resource switching is complete."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchComplete","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSwitchComplete"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/switchcomplete"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/seekError":{"role":"symbol","title":"AgoraMediaPlayerEvent.seekError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekError"}],"abstract":[{"type":"text","text":"2: An error occurs when seeking to a new playback position."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekError"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/seekerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/switchError":{"role":"symbol","title":"AgoraMediaPlayerEvent.switchError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchError"}],"abstract":[{"type":"text","text":"12: Media resource switching error."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSwitchError"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/switcherror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/seekComplete":{"role":"symbol","title":"AgoraMediaPlayerEvent.seekComplete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekComplete"}],"abstract":[{"type":"text","text":"1: The player finishes seeking to a new playback position."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekComplete","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekComplete"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/seekcomplete"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/bufferRecover":{"role":"symbol","title":"AgoraMediaPlayerEvent.bufferRecover","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferRecover"}],"abstract":[{"type":"text","text":"7: The currently buffered data is just enough to support playback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/bufferRecover","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventBufferRecover"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/bufferrecover"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/tryOpenSucceed":{"role":"symbol","title":"AgoraMediaPlayerEvent.tryOpenSucceed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryOpenSucceed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenSucceed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventTryOpenSucceed"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/tryopensucceed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/freezeStop":{"role":"symbol","title":"AgoraMediaPlayerEvent.freezeStop","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeStop"}],"abstract":[{"type":"text","text":"9: The audio or video playback resumes without freezing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStop","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStop"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/freezestop"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/reachCacheFileMaxSize":{"role":"symbol","title":"AgoraMediaPlayerEvent.reachCacheFileMaxSize","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reachCacheFileMaxSize"}],"abstract":[{"type":"text","text":"15: The cached media files reach the limit in aggregate storage space."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/reachCacheFileMaxSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventReachCacheFileMaxSize"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/reachcachefilemaxsize"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/firstDisplayed":{"role":"symbol","title":"AgoraMediaPlayerEvent.firstDisplayed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstDisplayed"}],"abstract":[{"type":"text","text":"13: The first video frame is rendered."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/firstDisplayed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventFirstDisplayed"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/firstdisplayed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/audioTrackChanged":{"role":"symbol","title":"AgoraMediaPlayerEvent.audioTrackChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTrackChanged"}],"abstract":[{"type":"text","text":"5: The audio track used by the player has been changed."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/audioTrackChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventAudioTrackChanged"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/audiotrackchanged"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/tryOpenStart":{"role":"symbol","title":"AgoraMediaPlayerEvent.tryOpenStart","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryOpenStart"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenStart","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventTryOpenStart"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/tryopenstart"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/bufferLow":{"role":"symbol","title":"AgoraMediaPlayerEvent.bufferLow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferLow"}],"abstract":[{"type":"text","text":"6: The currently buffered data is not enough to support playback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/bufferLow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventBufferLow"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/bufferlow"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent":{"role":"symbol","title":"AgoraMediaPlayerEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"abstract":[{"type":"text","text":"Media player events."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/reachCacheFileMaxCount":{"role":"symbol","title":"AgoraMediaPlayerEvent.reachCacheFileMaxCount","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reachCacheFileMaxCount"}],"abstract":[{"type":"text","text":"14: The cached media files reach the limit in number."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/reachCacheFileMaxCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventReachCacheFileMaxCount"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/reachcachefilemaxcount"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/seekBegin":{"role":"symbol","title":"AgoraMediaPlayerEvent.seekBegin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekBegin"}],"abstract":[{"type":"text","text":"0: The player begins to seek to a new playback position."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekBegin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekBegin"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/seekbegin"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoramediaplayerevent\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaPlayerEvent/freezeStart":{"role":"symbol","title":"AgoraMediaPlayerEvent.freezeStart","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeStart"}],"abstract":[{"type":"text","text":"8: The audio or video playback freezes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStart","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStart"}],"url":"\/documentation\/agorartckit\/agoramediaplayerevent\/freezestart"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaPlayerEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/audioTrackChanged","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/bufferLow","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/bufferRecover","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/firstDisplayed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStart","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/freezeStop","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/reachCacheFileMaxCount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/reachCacheFileMaxSize","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekBegin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekComplete","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/seekError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchBegin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchComplete","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/switchError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenStart","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaPlayerEvent\/tryOpenSucceed"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaPlayerEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1tryOpenFailed\/title","value":"AgoraMediaPlayerEventTryOpenFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1tryOpenFailed\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventTryOpenFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1switchBegin\/title","value":"AgoraMediaPlayerEventSwitchBegin"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1switchBegin\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSwitchBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1switchComplete\/title","value":"AgoraMediaPlayerEventSwitchComplete"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1switchComplete\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSwitchComplete"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekError\/title","value":"AgoraMediaPlayerEventSeekError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekError\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1switchError\/title","value":"AgoraMediaPlayerEventSwitchError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1switchError\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSwitchError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekComplete\/title","value":"AgoraMediaPlayerEventSeekComplete"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekComplete\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekComplete"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1bufferRecover\/title","value":"AgoraMediaPlayerEventBufferRecover"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1bufferRecover\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventBufferRecover"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1tryOpenSucceed\/title","value":"AgoraMediaPlayerEventTryOpenSucceed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1tryOpenSucceed\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventTryOpenSucceed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1freezeStop\/title","value":"AgoraMediaPlayerEventFreezeStop"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1freezeStop\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStop"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1reachCacheFileMaxSize\/title","value":"AgoraMediaPlayerEventReachCacheFileMaxSize"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1reachCacheFileMaxSize\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventReachCacheFileMaxSize"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1firstDisplayed\/title","value":"AgoraMediaPlayerEventFirstDisplayed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1firstDisplayed\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventFirstDisplayed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1audioTrackChanged\/title","value":"AgoraMediaPlayerEventAudioTrackChanged"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1audioTrackChanged\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventAudioTrackChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1tryOpenStart\/title","value":"AgoraMediaPlayerEventTryOpenStart"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1tryOpenStart\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventTryOpenStart"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1bufferLow\/title","value":"AgoraMediaPlayerEventBufferLow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1bufferLow\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventBufferLow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/title","value":"AgoraMediaPlayerEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1reachCacheFileMaxCount\/title","value":"AgoraMediaPlayerEventReachCacheFileMaxCount"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1reachCacheFileMaxCount\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventReachCacheFileMaxCount"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekBegin\/title","value":"AgoraMediaPlayerEventSeekBegin"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1seekBegin\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventSeekBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1freezeStart\/title","value":"AgoraMediaPlayerEventFreezeStart"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaPlayerEvent~1freezeStart\/fragments","value":[{"kind":"identifier","text":"AgoraMediaPlayerEventFreezeStart"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}