{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraColorEnhanceOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracolorenhanceoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracolorenhanceoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The color enhancement options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraColorEnhanceOptions"}],"title":"AgoraColorEnhanceOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraColorEnhanceOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraColorEnhanceOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/skinProtectLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/strengthLevel"]}],"references":{"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraColorEnhanceOptions/skinProtectLevel":{"role":"symbol","title":"skinProtectLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"skinProtectLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The level of skin tone protection. The value range is [0.0, 1.0]. 0.0 means"},{"type":"text","text":" "},{"type":"text","text":"no skin tone protection. The higher the value, the higher the level of skin"},{"type":"text","text":" "},{"type":"text","text":"tone protection. The default value is 1.0.When the level of color enhancement"},{"type":"text","text":" "},{"type":"text","text":"is higher, the portrait skin tone can be significantly distorted, so you need"},{"type":"text","text":" "},{"type":"text","text":"to set the level of skin tone protection.When the level of skin tone"},{"type":"text","text":" "},{"type":"text","text":"protection is higher, the color enhancement effect can be slightly"},{"type":"text","text":" "},{"type":"text","text":"reduced.Therefore, to get the best color enhancement effect, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"that you adjust strengthLevel and skinProtectLevel to get the most"},{"type":"text","text":" "},{"type":"text","text":"appropriate values."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/skinProtectLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"skinProtectLevel"}],"url":"\/documentation\/agorartckit\/agoracolorenhanceoptions\/skinprotectlevel"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraColorEnhanceOptions/strengthLevel":{"role":"symbol","title":"strengthLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strengthLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The level of color enhancement. The value range is [0.0, 1.0]. 0.0 is the"},{"type":"text","text":" "},{"type":"text","text":"default value, which means no color enhancement is applied to the video. The"},{"type":"text","text":" "},{"type":"text","text":"higher the value, the higher the level of color enhancement. The default"},{"type":"text","text":" "},{"type":"text","text":"value is 0.5."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/strengthLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"strengthLevel"}],"url":"\/documentation\/agorartckit\/agoracolorenhanceoptions\/strengthlevel"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraColorEnhanceOptions":{"role":"symbol","title":"AgoraColorEnhanceOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraColorEnhanceOptions"}],"abstract":[{"type":"text","text":"The color enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraColorEnhanceOptions"}],"url":"\/documentation\/agorartckit\/agoracolorenhanceoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraColorEnhanceOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraColorEnhanceOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraColorEnhanceOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/skinProtectLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraColorEnhanceOptions\/strengthLevel"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraColorEnhanceOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions~1skinProtectLevel\/title","value":"skinProtectLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions~1skinProtectLevel\/fragments","value":[{"kind":"identifier","text":"skinProtectLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions~1strengthLevel\/title","value":"strengthLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions~1strengthLevel\/fragments","value":[{"kind":"identifier","text":"strengthLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions\/title","value":"AgoraColorEnhanceOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraColorEnhanceOptions\/fragments","value":[{"kind":"identifier","text":"AgoraColorEnhanceOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}