{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class contains some of the APIs in the AgoraLocalSpatialAudioKit class."},{"type":"text","text":" "},{"type":"text","text":"The AgoraLocalSpatialAudioKit class inherits from AgoraBaseSpatialAudioKit."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"title":"AgoraBaseSpatialAudioKit","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraBaseSpatialAudioKit","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteAllRemoteAudioStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteLocalAudioStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteRemoteAudioStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setAudioRecvRange(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setDistanceUnit(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setMaxAudioRecvCount(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setPlayerAttenuation(_:playerId:forceSet:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setZones(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updatePlayerPositionInfo(_:positionInfo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPosition(_:axisForward:axisRight:axisUp:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPositionEx(_:axisForward:axisRight:axisUp:connection:)"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/setZones(_:)":{"role":"symbol","title":"setZones(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setZones"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraSpatialAudioZone","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioZone"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the sound insulation area."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1In virtual interactive scenarios, you can use this method to set"},{"type":"text","text":" "},{"type":"text","text":"the sound insulation area and sound attenuation coefficient. When the sound"},{"type":"text","text":" "},{"type":"text","text":"source (which can be the user or the media player) and the listener belong to"},{"type":"text","text":" "},{"type":"text","text":"the inside and outside of the sound insulation area, they can experience the"},{"type":"text","text":" "},{"type":"text","text":"attenuation effect of sound similar to the real environment when it"},{"type":"text","text":" "},{"type":"text","text":"encounters a building partition.When the sound source and the listener belong"},{"type":"text","text":" "},{"type":"text","text":"to the inside and outside of the sound insulation area, the sound attenuation"},{"type":"text","text":" "},{"type":"text","text":"effect is determined by the sound attenuation coefficient in"},{"type":"text","text":" "},{"type":"text","text":"AgoraSpatialAudioZone .If the user or media player is in the same sound"},{"type":"text","text":" "},{"type":"text","text":"insulation area, it is not affected by AgoraSpatialAudioZone, and the sound"},{"type":"text","text":" "},{"type":"text","text":"attenuation effect is determined by the attenuation parameter in"},{"type":"text","text":" "},{"type":"text","text":"setPlayerAttenuation or setRemoteAudioAttenuation. If you do not call"},{"type":"text","text":" "},{"type":"text","text":"setPlayerAttenuation or setRemoteAudioAttenuation, the default sound"},{"type":"text","text":" "},{"type":"text","text":"attenuation coefficient of the SDK is 0.5, which simulates the attenuation of"},{"type":"text","text":" "},{"type":"text","text":"the sound in the real environment.If the sound source and the receiver belong"},{"type":"text","text":" "},{"type":"text","text":"to two sound insulation areas, the receiver cannot hear the sound source.If"},{"type":"text","text":" "},{"type":"text","text":"this method is called multiple times, the last sound insulation area set"},{"type":"text","text":" "},{"type":"text","text":"takes effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setZones(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setZones:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/setzones(_:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/updateSelfPositionEx(_:axisForward:axisRight:axisUp:connection:)":{"role":"symbol","title":"updateSelfPositionEx(_:axisForward:axisRight:axisUp:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSelfPositionEx"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisForward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisUp"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPositionEx(_:axisForward:axisRight:axisUp:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateSelfPositionEx:axisForward:axisRight:axisUp:connection:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/updateselfpositionex(_:axisforward:axisright:axisup:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/setPlayerAttenuation(_:playerId:forceSet:)":{"role":"symbol","title":"setPlayerAttenuation(_:playerId:forceSet:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPlayerAttenuation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"playerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forceSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the sound attenuation properties of the media player."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setPlayerAttenuation(_:playerId:forceSet:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPlayerAttenuation:playerId:forceSet:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/setplayerattenuation(_:playerid:forceset:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/muteLocalAudioStream(_:)":{"role":"symbol","title":"muteLocalAudioStream(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteLocalAudioStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes publishing the local audio stream."},{"type":"text","text":" "},{"type":"text","text":"This method does not affect any ongoing audio recording, because it does not"},{"type":"text","text":" "},{"type":"text","text":"disable the audio capture device.Call this method after joinChannelByToken"},{"type":"text","text":" "},{"type":"text","text":"[2\/4] .When using the spatial audio effect, if you need to set whether to"},{"type":"text","text":" "},{"type":"text","text":"stop subscribing to the audio stream of a specified user, Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"calling this method instead of the muteLocalAudioStream method in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcEngineKit ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteLocalAudioStream(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteLocalAudioStream:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/mutelocalaudiostream(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/setAudioRecvRange(_:)":{"role":"symbol","title":"setAudioRecvRange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAudioRecvRange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the audio reception range of the local user."},{"type":"text","text":" "},{"type":"text","text":"After the setting is successful, the local user can only hear the remote"},{"type":"text","text":" "},{"type":"text","text":"users within the setting range or belonging to the same team. You can call"},{"type":"text","text":" "},{"type":"text","text":"this method at any time to update the audio reception range."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setAudioRecvRange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAudioRecvRange:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/setaudiorecvrange(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/setMaxAudioRecvCount(_:)":{"role":"symbol","title":"setMaxAudioRecvCount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxAudioRecvCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the maximum number of streams that a user can receive in a specified"},{"type":"text","text":" "},{"type":"text","text":"audio reception range. If the number of receivable streams exceeds the set"},{"type":"text","text":" "},{"type":"text","text":"value, the local user receives the maxCount streams that are closest to the"},{"type":"text","text":" "},{"type":"text","text":"local user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setMaxAudioRecvCount(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMaxAudioRecvCount:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/setmaxaudiorecvcount(_:)"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/updateSelfPosition(_:axisForward:axisRight:axisUp:)":{"role":"symbol","title":"updateSelfPosition(_:axisForward:axisRight:axisUp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSelfPosition"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisForward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisUp"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the spatial position of the local user."},{"type":"text","text":" "},{"type":"text","text":"Under the AgoraLocalSpatialAudioKit class, this method needs to be used with"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition . The SDK calculates the relative position between the"},{"type":"text","text":" "},{"type":"text","text":"local and remote users according to this method and the parameter settings in"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition, and then calculates the user’s spatial audio effect"},{"type":"text","text":" "},{"type":"text","text":"parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPosition(_:axisForward:axisRight:axisUp:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateSelfPosition:axisForward:axisRight:axisUp:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/updateselfposition(_:axisforward:axisright:axisup:)"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit":{"role":"symbol","title":"AgoraLocalSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/updatePlayerPositionInfo(_:positionInfo:)":{"role":"symbol","title":"updatePlayerPositionInfo(_:positionInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePlayerPositionInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRemoteVoicePositionInfo","preciseIdentifier":"c:objc(cs)AgoraRemoteVoicePositionInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the spatial position of the media player."},{"type":"text","text":" "},{"type":"text","text":"After a successful update, the local user can hear the change in the spatial"},{"type":"text","text":" "},{"type":"text","text":"position of the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updatePlayerPositionInfo(_:positionInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatePlayerPositionInfo:positionInfo:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/updateplayerpositioninfo(_:positioninfo:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/setDistanceUnit(_:)":{"role":"symbol","title":"setDistanceUnit(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDistanceUnit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the length (in meters) of the game engine distance per unit."},{"type":"text","text":" "},{"type":"text","text":"In a game engine, the unit of distance is customized, while in the Agora"},{"type":"text","text":" "},{"type":"text","text":"spatial audio algorithm, distance is measured in meters. By default, the SDK"},{"type":"text","text":" "},{"type":"text","text":"converts the game engine distance per unit to one meter. You can call this"},{"type":"text","text":" "},{"type":"text","text":"method to convert the game engine distance per unit to a specified number of"},{"type":"text","text":" "},{"type":"text","text":"meters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setDistanceUnit(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDistanceUnit:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/setdistanceunit(_:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit":{"role":"symbol","title":"AgoraBaseSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"abstract":[{"type":"text","text":"This class contains some of the APIs in the AgoraLocalSpatialAudioKit class."},{"type":"text","text":" "},{"type":"text","text":"The AgoraLocalSpatialAudioKit class inherits from AgoraBaseSpatialAudioKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/muteAllRemoteAudioStreams(_:)":{"role":"symbol","title":"muteAllRemoteAudioStreams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteAudioStreams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio streams of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the local user stops or resumes"},{"type":"text","text":" "},{"type":"text","text":"subscribing to the audio streams of all remote users, including all"},{"type":"text","text":" "},{"type":"text","text":"subsequent users.Call this method after joinChannelByToken [2\/4] .When using"},{"type":"text","text":" "},{"type":"text","text":"the spatial audio effect, if you need to set whether to stop subscribing to"},{"type":"text","text":" "},{"type":"text","text":"the audio streams of all remote users, Agora recommends calling this method"},{"type":"text","text":" "},{"type":"text","text":"instead of the muteAllRemoteAudioStreams method in AgoraRtcEngineKit .After"},{"type":"text","text":" "},{"type":"text","text":"calling this method, you need to call updateSelfPosition and"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition to update the spatial location of the local user and the"},{"type":"text","text":" "},{"type":"text","text":"remote user; otherwise, the settings in this method do not take effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteAllRemoteAudioStreams(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/muteallremoteaudiostreams(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/muteRemoteAudioStream(_:mute:)":{"role":"symbol","title":"muteRemoteAudioStream(_:mute:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteRemoteAudioStream"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio stream of a specified user."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1Call this method after joinChannelByToken [2\/4] .When using the"},{"type":"text","text":" "},{"type":"text","text":"spatial audio effect, if you need to set whether to stop subscribing to the"},{"type":"text","text":" "},{"type":"text","text":"audio stream of a specified user, Agora recommends calling this method"},{"type":"text","text":" "},{"type":"text","text":"instead of the muteRemoteAudioStream method in AgoraRtcEngineKit ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteRemoteAudioStream(_:mute:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteRemoteAudioStream:mute:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/muteremoteaudiostream(_:mute:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraBaseSpatialAudioKit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteAllRemoteAudioStreams(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteLocalAudioStream(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteRemoteAudioStream(_:mute:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setAudioRecvRange(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setDistanceUnit(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setMaxAudioRecvCount(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setPlayerAttenuation(_:playerId:forceSet:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setZones(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updatePlayerPositionInfo(_:positionInfo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPosition(_:axisForward:axisRight:axisUp:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPositionEx(_:axisForward:axisRight:axisUp:connection:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setZones(_:)\/title","value":"setZones:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setZones(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setZones:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updateSelfPositionEx(_:axisForward:axisRight:axisUp:connection:)\/title","value":"updateSelfPositionEx:axisForward:axisRight:axisUp:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updateSelfPositionEx(_:axisForward:axisRight:axisUp:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSelfPositionEx:axisForward:axisRight:axisUp:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setPlayerAttenuation(_:playerId:forceSet:)\/title","value":"setPlayerAttenuation:playerId:forceSet:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setPlayerAttenuation(_:playerId:forceSet:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPlayerAttenuation:playerId:forceSet:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteLocalAudioStream(_:)\/title","value":"muteLocalAudioStream:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteLocalAudioStream(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteLocalAudioStream:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setAudioRecvRange(_:)\/title","value":"setAudioRecvRange:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setAudioRecvRange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAudioRecvRange:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setMaxAudioRecvCount(_:)\/title","value":"setMaxAudioRecvCount:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setMaxAudioRecvCount(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMaxAudioRecvCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updateSelfPosition(_:axisForward:axisRight:axisUp:)\/title","value":"updateSelfPosition:axisForward:axisRight:axisUp:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updateSelfPosition(_:axisForward:axisRight:axisUp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSelfPosition:axisForward:axisRight:axisUp:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/title","value":"AgoraLocalSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updatePlayerPositionInfo(_:positionInfo:)\/title","value":"updatePlayerPositionInfo:positionInfo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updatePlayerPositionInfo(_:positionInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePlayerPositionInfo:positionInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setDistanceUnit(_:)\/title","value":"setDistanceUnit:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setDistanceUnit(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDistanceUnit:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/title","value":"AgoraBaseSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteAllRemoteAudioStreams(_:)\/title","value":"muteAllRemoteAudioStreams:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteAllRemoteAudioStreams(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteRemoteAudioStream(_:mute:)\/title","value":"muteRemoteAudioStream:mute:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteRemoteAudioStream(_:mute:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteRemoteAudioStream:mute:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}