{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraloglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraloglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The output log level of the SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogLevel"}],"title":"AgoraLogLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraLogLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLogLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/error","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/fatal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/info","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/none","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/warn"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraloglevel\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel":{"role":"symbol","title":"AgoraLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogLevel"}],"abstract":[{"type":"text","text":"The output log level of the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogLevel"}],"url":"\/documentation\/agorartckit\/agoraloglevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/warn":{"role":"symbol","title":"AgoraLogLevel.warn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warn"}],"abstract":[{"type":"text","text":"0x0002: Output FATAL, ERROR, and WARN level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/warn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogLevelWarn"}],"url":"\/documentation\/agorartckit\/agoraloglevel\/warn"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/fatal":{"role":"symbol","title":"AgoraLogLevel.fatal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fatal"}],"abstract":[{"type":"text","text":"0x0008: Output FATAL level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/fatal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogLevelFatal"}],"url":"\/documentation\/agorartckit\/agoraloglevel\/fatal"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraloglevel\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/error":{"role":"symbol","title":"AgoraLogLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[{"type":"text","text":"0x0004: Output FATAL and ERROR level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogLevelError"}],"url":"\/documentation\/agorartckit\/agoraloglevel\/error"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/none":{"role":"symbol","title":"AgoraLogLevel.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"0: Do not output any log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogLevelNone"}],"url":"\/documentation\/agorartckit\/agoraloglevel\/none"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/info":{"role":"symbol","title":"AgoraLogLevel.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[{"type":"text","text":"0x0001: (Default) Output FATAL, ERROR, WARN, and INFO level log"},{"type":"text","text":" "},{"type":"text","text":"information. We recommend setting your log filter to this level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/info","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogLevelInfo"}],"url":"\/documentation\/agorartckit\/agoraloglevel\/info"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraloglevel\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLogLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLogLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLogLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/error","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/fatal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/info","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/none","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogLevel\/warn"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel\/title","value":"AgoraLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel\/fragments","value":[{"kind":"identifier","text":"AgoraLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1warn\/title","value":"AgoraLogLevelWarn"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1warn\/fragments","value":[{"kind":"identifier","text":"AgoraLogLevelWarn"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1fatal\/title","value":"AgoraLogLevelFatal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1fatal\/fragments","value":[{"kind":"identifier","text":"AgoraLogLevelFatal"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1error\/title","value":"AgoraLogLevelError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1error\/fragments","value":[{"kind":"identifier","text":"AgoraLogLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1none\/title","value":"AgoraLogLevelNone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1none\/fragments","value":[{"kind":"identifier","text":"AgoraLogLevelNone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1info\/title","value":"AgoraLogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogLevel~1info\/fragments","value":[{"kind":"identifier","text":"AgoraLogLevelInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}