{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/enableTranscode(token:channel:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/queryChannel(token:channel:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/registerTranscoderDelegate(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/triggerTranscode(token:channel:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/unregisterTranscoderDelegate(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}],"title":"AgoraH265TranscoderProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraH265TranscoderProtocol","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol/unregisterTranscoderDelegate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"unregisterTranscoderDelegate:"}],"role":"symbol","title":"unregisterTranscoderDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterTranscoderDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscoderDelegate","preciseIdentifier":"c:objc(pl)AgoraH265TranscoderDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/unregisterTranscoderDelegate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderprotocol\/unregistertranscoderdelegate(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol/queryChannel(token:channel:uid:)":{"navigatorTitle":[{"kind":"identifier","text":"queryChannelWithToken:channel:uid:"}],"role":"symbol","title":"queryChannel(token:channel:uid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/queryChannel(token:channel:uid:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderprotocol\/querychannel(token:channel:uid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol/triggerTranscode(token:channel:uid:)":{"navigatorTitle":[{"kind":"identifier","text":"triggerTranscodeWithToken:channel:uid:"}],"role":"symbol","title":"triggerTranscode(token:channel:uid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"triggerTranscode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/triggerTranscode(token:channel:uid:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderprotocol\/triggertranscode(token:channel:uid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol/registerTranscoderDelegate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"registerTranscoderDelegate:"}],"role":"symbol","title":"registerTranscoderDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerTranscoderDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscoderDelegate","preciseIdentifier":"c:objc(pl)AgoraH265TranscoderDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/registerTranscoderDelegate(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderprotocol\/registertranscoderdelegate(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol":{"role":"symbol","title":"AgoraH265TranscoderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}],"url":"\/documentation\/agorartckit\/agorah265transcoderprotocol"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderProtocol/enableTranscode(token:channel:uid:)":{"navigatorTitle":[{"kind":"identifier","text":"enableTranscodeWithToken:channel:uid:"}],"role":"symbol","title":"enableTranscode(token:channel:uid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTranscode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/enableTranscode(token:channel:uid:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderprotocol\/enabletranscode(token:channel:uid:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraH265TranscoderProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/enableTranscode(token:channel:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/queryChannel(token:channel:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/registerTranscoderDelegate(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/triggerTranscode(token:channel:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderProtocol\/unregisterTranscoderDelegate(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderProtocol"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1unregisterTranscoderDelegate(_:)\/title","value":"unregisterTranscoderDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1unregisterTranscoderDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterTranscoderDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1queryChannel(token:channel:uid:)\/title","value":"queryChannelWithToken:channel:uid:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1queryChannel(token:channel:uid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryChannelWithToken:channel:uid:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1triggerTranscode(token:channel:uid:)\/title","value":"triggerTranscodeWithToken:channel:uid:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1triggerTranscode(token:channel:uid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"triggerTranscodeWithToken:channel:uid:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1registerTranscoderDelegate(_:)\/title","value":"registerTranscoderDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1registerTranscoderDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerTranscoderDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol\/title","value":"AgoraH265TranscoderProtocol"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscoderProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1enableTranscode(token:channel:uid:)\/title","value":"enableTranscodeWithToken:channel:uid:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderProtocol~1enableTranscode(token:channel:uid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableTranscodeWithToken:channel:uid:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}