{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodedvideoframeinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodedvideoframeinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/captureTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/codecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/decodeTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/frameType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/framesPerSecond","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/rotation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/streamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/trackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/uid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/width"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"title":"AgoraEncodedVideoFrameInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraEncodedVideoFrameInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/frameType":{"role":"symbol","title":"frameType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFrameType","preciseIdentifier":"c:@E@AgoraVideoFrameType"}],"abstract":[{"type":"text","text":"The video frame type. See AgoraVideoFrameType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/frameType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameType"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/frametype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/codecType":{"role":"symbol","title":"codecType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoCodecType","preciseIdentifier":"c:@E@AgoraVideoCodecType"}],"abstract":[{"type":"text","text":"The codec type of the local video stream. See AgoraVideoCodecType . The"},{"type":"text","text":" "},{"type":"text","text":"default value is AgoraVideoCodecTypeH264 (2)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/codecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecType"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/codectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/decodeTimeMs":{"role":"symbol","title":"decodeTimeMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeTimeMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/decodeTimeMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decodeTimeMs"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/decodetimems"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo":{"role":"symbol","title":"AgoraEncodedVideoFrameInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/rotation":{"role":"symbol","title":"rotation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The rotation information of the video frame. See AgoraVideoRotation ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/rotation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rotation"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/rotation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/streamType":{"role":"symbol","title":"streamType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType"}],"abstract":[{"type":"text","text":"The type of video streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/streamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"streamType"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/streamtype"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/width":{"role":"symbol","title":"width","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Width (pixel) of the video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/width","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"width"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/width"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/trackId":{"role":"symbol","title":"trackId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Reserved for future use."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/trackId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackId"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/trackid"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/uid":{"role":"symbol","title":"uid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The user ID to push the externally encoded video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/uid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uid"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/uid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/framesPerSecond":{"role":"symbol","title":"framesPerSecond","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"framesPerSecond"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of video frames per second.When this parameter is not 0, you can"},{"type":"text","text":" "},{"type":"text","text":"use it to calculate the Unix timestamp of externally encoded video frames."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/framesPerSecond","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"framesPerSecond"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/framespersecond"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/height":{"role":"symbol","title":"height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Height (pixel) of the video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/height","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"height"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/height"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoFrameInfo/captureTimeMs":{"role":"symbol","title":"captureTimeMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureTimeMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The Unix timestamp (ms) for capturing the external encoded video frames."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/captureTimeMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureTimeMs"}],"url":"\/documentation\/agorartckit\/agoraencodedvideoframeinfo\/capturetimems"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncodedVideoFrameInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/captureTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/codecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/decodeTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/frameType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/framesPerSecond","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/rotation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/streamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/trackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/uid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoFrameInfo\/width"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1frameType\/title","value":"frameType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1frameType\/fragments","value":[{"kind":"identifier","text":"frameType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1codecType\/title","value":"codecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1codecType\/fragments","value":[{"kind":"identifier","text":"codecType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1decodeTimeMs\/title","value":"decodeTimeMs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1decodeTimeMs\/fragments","value":[{"kind":"identifier","text":"decodeTimeMs"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo\/title","value":"AgoraEncodedVideoFrameInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoFrameInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1rotation\/title","value":"rotation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1rotation\/fragments","value":[{"kind":"identifier","text":"rotation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1streamType\/title","value":"streamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1streamType\/fragments","value":[{"kind":"identifier","text":"streamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1width\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1width\/fragments","value":[{"kind":"identifier","text":"width"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1trackId\/title","value":"trackId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1trackId\/fragments","value":[{"kind":"identifier","text":"trackId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1uid\/title","value":"uid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1uid\/fragments","value":[{"kind":"identifier","text":"uid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1framesPerSecond\/title","value":"framesPerSecond"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1framesPerSecond\/fragments","value":[{"kind":"identifier","text":"framesPerSecond"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1height\/fragments","value":[{"kind":"identifier","text":"height"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1captureTimeMs\/title","value":"captureTimeMs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoFrameInfo~1captureTimeMs\/fragments","value":[{"kind":"identifier","text":"captureTimeMs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}