{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorarhythmplayerstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorarhythmplayerstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Virtual metronome state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerState"}],"title":"AgoraRhythmPlayerState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraRhythmPlayerState","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerState"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/decoding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/opening","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/playing"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/opening":{"role":"symbol","title":"AgoraRhythmPlayerState.opening","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opening"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/opening","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerStateOpening"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/opening"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState":{"role":"symbol","title":"AgoraRhythmPlayerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerState"}],"abstract":[{"type":"text","text":"Virtual metronome state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerState"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerstate"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/idle":{"role":"symbol","title":"AgoraRhythmPlayerState.idle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"abstract":[{"type":"text","text":"(810): The virtual metronome is not enabled or disabled already."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/idle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerStateIdle"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/idle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/decoding":{"role":"symbol","title":"AgoraRhythmPlayerState.decoding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoding"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/decoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerStateDecoding"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/decoding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/playing":{"role":"symbol","title":"AgoraRhythmPlayerState.playing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/playing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerStatePlaying"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/playing"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerState/failed":{"role":"symbol","title":"AgoraRhythmPlayerState.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerStateFailed"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerstate\/failed"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRhythmPlayerState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRhythmPlayerState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/decoding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/opening","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerState\/playing"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1opening\/title","value":"AgoraRhythmPlayerStateOpening"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1opening\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerStateOpening"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState\/title","value":"AgoraRhythmPlayerState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1idle\/title","value":"AgoraRhythmPlayerStateIdle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1idle\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerStateIdle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1decoding\/title","value":"AgoraRhythmPlayerStateDecoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1decoding\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerStateDecoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1playing\/title","value":"AgoraRhythmPlayerStatePlaying"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1playing\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerStatePlaying"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1failed\/title","value":"AgoraRhythmPlayerStateFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerState~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerStateFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}