{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The event code of channel media relay."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"title":"AgoraChannelMediaRelayEvent","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChannelMediaRelayEvent","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/connected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/disconnect","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedSourceChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/receivedAudioPacketFromSource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/receivedVideoPacketFromSource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/sentToDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelIsNil","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelNotChange","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelRefused","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/videoProfileUpdate"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/joinedSourceChannel":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.joinedSourceChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedSourceChannel"}],"abstract":[{"type":"text","text":"2: The user joins the source channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedSourceChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedSourceChannel"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/joinedsourcechannel"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/connected":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[{"type":"text","text":"1: The user is connected to the server."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventConnected"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/connected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/updateDestinationChannelIsNil":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.updateDestinationChannelIsNil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelIsNil"}],"abstract":[{"type":"text","text":"10: The target channel name is nil."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelIsNil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelisnil"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/updateDestinationChannelNotChange":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.updateDestinationChannelNotChange","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelNotChange"}],"abstract":[{"type":"text","text":"9: The target channel does not change, which means that the target channel fails to be updated."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelNotChange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelnotchange"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/receivedAudioPacketFromSource":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.receivedAudioPacketFromSource","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedAudioPacketFromSource"}],"abstract":[{"type":"text","text":"6: The server receives the audio stream from the source channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/receivedAudioPacketFromSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventReceivedAudioPacketFromSource"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/receivedaudiopacketfromsource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent":{"role":"symbol","title":"AgoraChannelMediaRelayEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"abstract":[{"type":"text","text":"The event code of channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/updateDestinationChannelRefused":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.updateDestinationChannelRefused","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannelRefused"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelRefused","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelRefused"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannelrefused"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/disconnect":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.disconnect","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"}],"abstract":[{"type":"text","text":"0: The user disconnects from the server due to a poor network connection."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/disconnect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventDisconnect"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/disconnect"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/joinedDestinationChannel":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.joinedDestinationChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinedDestinationChannel"}],"abstract":[{"type":"text","text":"3: The user joins the target channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedDestinationChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedDestinationChannel"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/joineddestinationchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/updateDestinationChannel":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.updateDestinationChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDestinationChannel"}],"abstract":[{"type":"text","text":"7: The target channel is updated."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannel"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/updatedestinationchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/videoProfileUpdate":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.videoProfileUpdate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoProfileUpdate"}],"abstract":[{"type":"text","text":"11: The video profile is sent to the server."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/videoProfileUpdate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventVideoProfileUpdate"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/videoprofileupdate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/receivedVideoPacketFromSource":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.receivedVideoPacketFromSource","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedVideoPacketFromSource"}],"abstract":[{"type":"text","text":"5: The server receives the audio stream from the source channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/receivedVideoPacketFromSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventReceivedVideoPacketFromSource"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/receivedvideopacketfromsource"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayEvent/sentToDestinationChannel":{"role":"symbol","title":"AgoraChannelMediaRelayEvent.sentToDestinationChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sentToDestinationChannel"}],"abstract":[{"type":"text","text":"4: The SDK starts relaying the media stream to the target channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/sentToDestinationChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventSentToDestinationChannel"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayevent\/senttodestinationchannel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelMediaRelayEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/connected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/disconnect","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/joinedSourceChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/receivedAudioPacketFromSource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/receivedVideoPacketFromSource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/sentToDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelIsNil","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelNotChange","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/updateDestinationChannelRefused","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayEvent\/videoProfileUpdate"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1joinedSourceChannel\/title","value":"AgoraChannelMediaRelayEventJoinedSourceChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1joinedSourceChannel\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedSourceChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1connected\/title","value":"AgoraChannelMediaRelayEventConnected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1connected\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelIsNil\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelIsNil\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelIsNil"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelNotChange\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelNotChange\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelNotChange"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1receivedAudioPacketFromSource\/title","value":"AgoraChannelMediaRelayEventReceivedAudioPacketFromSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1receivedAudioPacketFromSource\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventReceivedAudioPacketFromSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/title","value":"AgoraChannelMediaRelayEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelRefused\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannelRefused"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannelRefused\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannelRefused"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1disconnect\/title","value":"AgoraChannelMediaRelayEventDisconnect"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1disconnect\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventDisconnect"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1joinedDestinationChannel\/title","value":"AgoraChannelMediaRelayEventJoinedDestinationChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1joinedDestinationChannel\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventJoinedDestinationChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannel\/title","value":"AgoraChannelMediaRelayEventUpdateDestinationChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1updateDestinationChannel\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventUpdateDestinationChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1videoProfileUpdate\/title","value":"AgoraChannelMediaRelayEventVideoProfileUpdate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1videoProfileUpdate\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventVideoProfileUpdate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1receivedVideoPacketFromSource\/title","value":"AgoraChannelMediaRelayEventReceivedVideoPacketFromSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1receivedVideoPacketFromSource\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventReceivedVideoPacketFromSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1sentToDestinationChannel\/title","value":"AgoraChannelMediaRelayEventSentToDestinationChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayEvent~1sentToDestinationChannel\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayEventSentToDestinationChannel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}