{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiomixingreasoncode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The reason why the playback state of the music file changes. Reported in the audioMixingStateChanged callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"title":"AgoraAudioMixingReasonCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioMixingReasonCode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/allLoopsCompleted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/canNotOpen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/interruptedEOF","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/oneLoopCompleted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/stoppedByUser","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/tooFrequentlyCall","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/typeOk"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode":{"role":"symbol","title":"AgoraAudioMixingReasonCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"abstract":[{"type":"text","text":"The reason why the playback state of the music file changes. Reported in the audioMixingStateChanged callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/typeOk":{"role":"symbol","title":"AgoraAudioMixingReasonCode.typeOk","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeOk"}],"abstract":[{"type":"text","text":"0: The SDK opens music file successfully."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/typeOk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonTypeOk"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/typeok"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/canNotOpen":{"role":"symbol","title":"AgoraAudioMixingReasonCode.canNotOpen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canNotOpen"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/canNotOpen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonCanNotOpen"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/cannotopen"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/stoppedByUser":{"role":"symbol","title":"AgoraAudioMixingReasonCode.stoppedByUser","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stoppedByUser"}],"abstract":[{"type":"text","text":"724: Successfully call stopAudioMixing to stop playing the music file."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/stoppedByUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonStoppedByUser"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/stoppedbyuser"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/allLoopsCompleted":{"role":"symbol","title":"AgoraAudioMixingReasonCode.allLoopsCompleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allLoopsCompleted"}],"abstract":[{"type":"text","text":"723: The music file completes all loop playback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/allLoopsCompleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonAllLoopsCompleted"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/allloopscompleted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/interruptedEOF":{"role":"symbol","title":"AgoraAudioMixingReasonCode.interruptedEOF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interruptedEOF"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/interruptedEOF","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonInterruptedEOF"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/interruptedeof"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/oneLoopCompleted":{"role":"symbol","title":"AgoraAudioMixingReasonCode.oneLoopCompleted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneLoopCompleted"}],"abstract":[{"type":"text","text":"721: The music file completes a loop playback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/oneLoopCompleted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonOneLoopCompleted"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/oneloopcompleted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/tooFrequentlyCall":{"role":"symbol","title":"AgoraAudioMixingReasonCode.tooFrequentlyCall","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooFrequentlyCall"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/tooFrequentlyCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingReasonTooFrequentlyCall"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/toofrequentlycall"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingReasonCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiomixingreasoncode\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioMixingReasonCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/allLoopsCompleted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/canNotOpen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/interruptedEOF","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/oneLoopCompleted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/stoppedByUser","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/tooFrequentlyCall","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingReasonCode\/typeOk"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingReasonCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/title","value":"AgoraAudioMixingReasonCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1typeOk\/title","value":"AgoraAudioMixingReasonTypeOk"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1typeOk\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonTypeOk"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1canNotOpen\/title","value":"AgoraAudioMixingReasonCanNotOpen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1canNotOpen\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonCanNotOpen"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1stoppedByUser\/title","value":"AgoraAudioMixingReasonStoppedByUser"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1stoppedByUser\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonStoppedByUser"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1allLoopsCompleted\/title","value":"AgoraAudioMixingReasonAllLoopsCompleted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1allLoopsCompleted\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonAllLoopsCompleted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1interruptedEOF\/title","value":"AgoraAudioMixingReasonInterruptedEOF"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1interruptedEOF\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonInterruptedEOF"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1oneLoopCompleted\/title","value":"AgoraAudioMixingReasonOneLoopCompleted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1oneLoopCompleted\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonOneLoopCompleted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1tooFrequentlyCall\/title","value":"AgoraAudioMixingReasonTooFrequentlyCall"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingReasonCode~1tooFrequentlyCall\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingReasonTooFrequentlyCall"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}