{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodingType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodingtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodingtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio encoding type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodingType"}],"title":"AgoraAudioEncodingType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioEncodingType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac16000Low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac16000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000High","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000Low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac48000High","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac48000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus16000Low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000High","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus6000Medium"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/aac32000Low":{"role":"symbol","title":"AgoraAudioEncodingType.aac32000Low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aac32000Low"}],"abstract":[{"type":"text","text":"AAC encoding format, 32000 Hz sampling rate, bass quality. A file with an"},{"type":"text","text":" "},{"type":"text","text":"audio duration of 10 minutes is approximately 1.2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000Low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC32000Low"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/aac32000low"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/aac32000Medium":{"role":"symbol","title":"AgoraAudioEncodingType.aac32000Medium","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aac32000Medium"}],"abstract":[{"type":"text","text":"AAC encoding format, 32000 Hz sampling rate, medium sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000Medium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC32000Medium"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/aac32000medium"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/aac48000High":{"role":"symbol","title":"AgoraAudioEncodingType.aac48000High","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aac48000High"}],"abstract":[{"type":"text","text":"AAC encoding format, 48000 Hz sampling rate, high sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 3.5 MB after"},{"type":"text","text":" "},{"type":"text","text":"encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac48000High","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC48000High"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/aac48000high"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/opus48000Medium":{"role":"symbol","title":"AgoraAudioEncodingType.opus48000Medium","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opus48000Medium"}],"abstract":[{"type":"text","text":"OPUS encoding format, 48000 Hz sampling rate, medium sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000Medium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000Medium"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/opus48000medium"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/aac16000Medium":{"role":"symbol","title":"AgoraAudioEncodingType.aac16000Medium","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aac16000Medium"}],"abstract":[{"type":"text","text":"AAC encoding format, 16000 Hz sampling rate, medium sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac16000Medium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC16000Medium"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/aac16000medium"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/aac16000Low":{"role":"symbol","title":"AgoraAudioEncodingType.aac16000Low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aac16000Low"}],"abstract":[{"type":"text","text":"AAC encoding format, 16000 Hz sampling rate, bass quality. A file with an"},{"type":"text","text":" "},{"type":"text","text":"audio duration of 10 minutes is approximately 1.2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac16000Low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC16000Low"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/aac16000low"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/opus6000Medium":{"role":"symbol","title":"AgoraAudioEncodingType.opus6000Medium","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opus6000Medium"}],"abstract":[{"type":"text","text":"OPUS encoding format, 16000 Hz sampling rate, medium sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus6000Medium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS6000Medium"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/opus6000medium"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/aac48000Medium":{"role":"symbol","title":"AgoraAudioEncodingType.aac48000Medium","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aac48000Medium"}],"abstract":[{"type":"text","text":"AAC encoding format, 48000 Hz sampling rate, medium sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac48000Medium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC48000Medium"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/aac48000medium"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType":{"role":"symbol","title":"AgoraAudioEncodingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodingType"}],"abstract":[{"type":"text","text":"Audio encoding type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingType"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/opus48000High":{"role":"symbol","title":"AgoraAudioEncodingType.opus48000High","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opus48000High"}],"abstract":[{"type":"text","text":"OPUS encoding format, 48000 Hz sampling rate, high sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 3.5 MB after"},{"type":"text","text":" "},{"type":"text","text":"encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000High","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000High"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/opus48000high"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/aac32000High":{"role":"symbol","title":"AgoraAudioEncodingType.aac32000High","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aac32000High"}],"abstract":[{"type":"text","text":"AAC encoding format, 32000 Hz sampling rate, high sound quality. A file"},{"type":"text","text":" "},{"type":"text","text":"with an audio duration of 10 minutes is approximately 3.5 MB after"},{"type":"text","text":" "},{"type":"text","text":"encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000High","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC32000High"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/aac32000high"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodingType/opus16000Low":{"role":"symbol","title":"AgoraAudioEncodingType.opus16000Low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"opus16000Low"}],"abstract":[{"type":"text","text":"OPUS encoding format, 16000 Hz sampling rate, bass quality. A file with an"},{"type":"text","text":" "},{"type":"text","text":"audio duration of 10 minutes is approximately 2 MB after encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus16000Low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS16000Low"}],"url":"\/documentation\/agorartckit\/agoraaudioencodingtype\/opus16000low"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEncodingType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioEncodingType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac16000Low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac16000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000High","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000Low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac32000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac48000High","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/aac48000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus16000Low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000High","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus48000Medium","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodingType\/opus6000Medium"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac32000Low\/title","value":"AgoraAudioEncodingTypeAAC32000Low"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac32000Low\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC32000Low"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac32000Medium\/title","value":"AgoraAudioEncodingTypeAAC32000Medium"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac32000Medium\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC32000Medium"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac48000High\/title","value":"AgoraAudioEncodingTypeAAC48000High"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac48000High\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC48000High"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus48000Medium\/title","value":"AgoraAudioEncodingTypeOPUS48000Medium"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus48000Medium\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000Medium"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac16000Medium\/title","value":"AgoraAudioEncodingTypeAAC16000Medium"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac16000Medium\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC16000Medium"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac16000Low\/title","value":"AgoraAudioEncodingTypeAAC16000Low"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac16000Low\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC16000Low"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus6000Medium\/title","value":"AgoraAudioEncodingTypeOPUS6000Medium"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus6000Medium\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS6000Medium"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac48000Medium\/title","value":"AgoraAudioEncodingTypeAAC48000Medium"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac48000Medium\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC48000Medium"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType\/title","value":"AgoraAudioEncodingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus48000High\/title","value":"AgoraAudioEncodingTypeOPUS48000High"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus48000High\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS48000High"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac32000High\/title","value":"AgoraAudioEncodingTypeAAC32000High"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1aac32000High\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeAAC32000High"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus16000Low\/title","value":"AgoraAudioEncodingTypeOPUS16000Low"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodingType~1opus16000Low\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodingTypeOPUS16000Low"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}