{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenterconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/appId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/maxCacheSize","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/mccUid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/rtcEngine","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/token"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}],"title":"AgoraMusicContentCenterConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraMusicContentCenterConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterConfig/rtcEngine":{"role":"symbol","title":"rtcEngine","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/rtcEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterconfig\/rtcengine"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterConfig/mccUid":{"role":"symbol","title":"mccUid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mccUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/mccUid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mccUid"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterconfig\/mccuid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterConfig/appId":{"role":"symbol","title":"appId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/appId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appId"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterconfig\/appid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterConfig/token":{"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/token","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"token"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterconfig\/token"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterConfig/maxCacheSize":{"role":"symbol","title":"maxCacheSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxCacheSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/maxCacheSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxCacheSize"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterconfig\/maxcachesize"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterConfig":{"role":"symbol","title":"AgoraMusicContentCenterConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenterconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicContentCenterConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/appId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/maxCacheSize","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/mccUid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/rtcEngine","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterConfig\/token"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1rtcEngine\/title","value":"rtcEngine"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1rtcEngine\/fragments","value":[{"kind":"identifier","text":"rtcEngine"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1mccUid\/title","value":"mccUid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1mccUid\/fragments","value":[{"kind":"identifier","text":"mccUid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1appId\/title","value":"appId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1appId\/fragments","value":[{"kind":"identifier","text":"appId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1token\/fragments","value":[{"kind":"identifier","text":"token"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1maxCacheSize\/title","value":"maxCacheSize"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig~1maxCacheSize\/fragments","value":[{"kind":"identifier","text":"maxCacheSize"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig\/title","value":"AgoraMusicContentCenterConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterConfig\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}