{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioCodecType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiocodectype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiocodectype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The codec type of audio."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioCodecType"}],"title":"AgoraAudioCodecType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioCodecType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/AACLC","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/HEAAC","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/HEAAC2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/OPUS"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/OPUS":{"role":"symbol","title":"AgoraAudioCodecType.OPUS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OPUS"}],"abstract":[{"type":"text","text":"1: OPUS."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/OPUS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecTypeOPUS"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype\/opus"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiocodectype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiocodectype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/HEAAC2":{"role":"symbol","title":"AgoraAudioCodecType.HEAAC2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HEAAC2"}],"abstract":[{"type":"text","text":"11: HE-AAC v2."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/HEAAC2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecTypeHEAAC2"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype\/heaac2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/AACLC":{"role":"symbol","title":"AgoraAudioCodecType.AACLC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AACLC"}],"abstract":[{"type":"text","text":"8: LC-AAC."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/AACLC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecTypeAACLC"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype\/aaclc"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType":{"role":"symbol","title":"AgoraAudioCodecType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioCodecType"}],"abstract":[{"type":"text","text":"The codec type of audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecType"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/HEAAC":{"role":"symbol","title":"AgoraAudioCodecType.HEAAC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HEAAC"}],"abstract":[{"type":"text","text":"9: HE-AAC."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/HEAAC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioCodecTypeHEAAC"}],"url":"\/documentation\/agorartckit\/agoraaudiocodectype\/heaac"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioCodecType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiocodectype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioCodecType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioCodecType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/AACLC","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/HEAAC","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/HEAAC2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioCodecType\/OPUS"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioCodecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1OPUS\/title","value":"AgoraAudioCodecTypeOPUS"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1OPUS\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecTypeOPUS"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1HEAAC2\/title","value":"AgoraAudioCodecTypeHEAAC2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1HEAAC2\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecTypeHEAAC2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1AACLC\/title","value":"AgoraAudioCodecTypeAACLC"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1AACLC\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecTypeAACLC"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType\/title","value":"AgoraAudioCodecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1HEAAC\/title","value":"AgoraAudioCodecTypeHEAAC"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioCodecType~1HEAAC\/fragments","value":[{"kind":"identifier","text":"AgoraAudioCodecTypeHEAAC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}