{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP","doc:\/\/AgoraRtcKit\/s9OptionSetP","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP","doc:\/\/AgoraRtcKit\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/all","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/configureSession","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/deactivateSession","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/setCategory"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/OptionSet-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/SetAlgebra-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"title":"AgoraAudioSessionOperationRestriction","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@E@AgoraAudioSessionOperationRestriction","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction":{"role":"symbol","title":"AgoraAudioSessionOperationRestriction","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/setCategory":{"role":"symbol","title":"setCategory","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/setCategory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionSetCategory"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/setcategory"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/deactivateSession":{"role":"symbol","title":"deactivateSession","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deactivateSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/deactivateSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionDeactivateSession"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/deactivatesession"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/setalgebra-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/AgoraRtcKit\/s10SetAlgebraP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/AgoraRtcKit\/s9OptionSetP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/AgoraAudioSessionOperationRestrictionNone":{"role":"symbol","title":"AgoraAudioSessionOperationRestrictionNone","fragments":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionNone"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/AgoraAudioSessionOperationRestrictionNone","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/agoraaudiosessionoperationrestrictionnone"},"doc://AgoraRtcKit/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/configureSession":{"role":"symbol","title":"configureSession","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/configureSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionConfigureSession"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/configuresession"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/optionset-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/all":{"role":"symbol","title":"all","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSessionOperationRestriction","preciseIdentifier":"c:@E@AgoraAudioSessionOperationRestriction"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionAll"}],"url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/all"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSessionOperationRestriction/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiosessionoperationrestriction\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioSessionOperationRestriction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/AgoraAudioSessionOperationRestrictionNone","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/all","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/configureSession","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/deactivateSession","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSessionOperationRestriction\/setCategory"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction\/title","value":"AgoraAudioSessionOperationRestriction"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestriction"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1setCategory\/title","value":"AgoraAudioSessionOperationRestrictionSetCategory"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1setCategory\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionSetCategory"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1deactivateSession\/title","value":"AgoraAudioSessionOperationRestrictionDeactivateSession"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1deactivateSession\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionDeactivateSession"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1configureSession\/title","value":"AgoraAudioSessionOperationRestrictionConfigureSession"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1configureSession\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionConfigureSession"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1all\/title","value":"AgoraAudioSessionOperationRestrictionAll"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSessionOperationRestriction~1all\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSessionOperationRestrictionAll"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}