{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorarhythmplayerconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorarhythmplayerconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The metronome configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}],"title":"AgoraRhythmPlayerConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRhythmPlayerConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMeasure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMinute"]}],"references":{"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerConfig/beatsPerMeasure":{"role":"symbol","title":"beatsPerMeasure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beatsPerMeasure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The number of beats per measure, which ranges from 1 to 9. The default value"},{"type":"text","text":" "},{"type":"text","text":"is 4, which means that each measure contains one downbeat and three upbeats."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMeasure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"beatsPerMeasure"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerconfig\/beatspermeasure"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerConfig/beatsPerMinute":{"role":"symbol","title":"beatsPerMinute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beatsPerMinute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The beat speed (beats\/minute), which ranges from 60 to 360. The default value"},{"type":"text","text":" "},{"type":"text","text":"is 60, which means that the metronome plays 60 beats in one minute."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMinute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"beatsPerMinute"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerconfig\/beatsperminute"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRhythmPlayerConfig":{"role":"symbol","title":"AgoraRhythmPlayerConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}],"abstract":[{"type":"text","text":"The metronome configuration."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}],"url":"\/documentation\/agorartckit\/agorarhythmplayerconfig"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRhythmPlayerConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMeasure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRhythmPlayerConfig\/beatsPerMinute"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRhythmPlayerConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig~1beatsPerMeasure\/title","value":"beatsPerMeasure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig~1beatsPerMeasure\/fragments","value":[{"kind":"identifier","text":"beatsPerMeasure"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig~1beatsPerMinute\/title","value":"beatsPerMinute"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig~1beatsPerMinute\/fragments","value":[{"kind":"identifier","text":"beatsPerMinute"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig\/title","value":"AgoraRhythmPlayerConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRhythmPlayerConfig\/fragments","value":[{"kind":"identifier","text":"AgoraRhythmPlayerConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}