{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelProfile"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelprofile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelprofile"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The channel profile."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelProfile"}],"title":"AgoraChannelProfile","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChannelProfile","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfile"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/cloudGaming","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication_1v1","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/game","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/liveBroadcasting"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/liveBroadcasting":{"role":"symbol","title":"AgoraChannelProfile.liveBroadcasting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveBroadcasting"}],"abstract":[{"type":"text","text":"1: Live streaming. Live streaming. Use this profile when there are more"},{"type":"text","text":" "},{"type":"text","text":"than two users in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/liveBroadcasting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileLiveBroadcasting"}],"url":"\/documentation\/agorartckit\/agorachannelprofile\/livebroadcasting"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorachannelprofile\/equatable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile":{"role":"symbol","title":"AgoraChannelProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelProfile"}],"abstract":[{"type":"text","text":"The channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfile"}],"url":"\/documentation\/agorartckit\/agorachannelprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorachannelprofile\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/game":{"deprecated":true,"role":"symbol","title":"AgoraChannelProfile.game","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"game"}],"abstract":[{"type":"text","text":"1: Live streaming. Live streaming. Use this profile when there are more"},{"type":"text","text":" "},{"type":"text","text":"than two users in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/game","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileGame"}],"url":"\/documentation\/agorartckit\/agorachannelprofile\/game"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/cloudGaming":{"deprecated":true,"role":"symbol","title":"AgoraChannelProfile.cloudGaming","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudGaming"}],"abstract":[{"type":"text","text":"1: Live streaming. Live streaming. Use this profile when there are more"},{"type":"text","text":" "},{"type":"text","text":"than two users in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/cloudGaming","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileCloudGaming"}],"url":"\/documentation\/agorartckit\/agorachannelprofile\/cloudgaming"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorachannelprofile\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/communication":{"role":"symbol","title":"AgoraChannelProfile.communication","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communication"}],"abstract":[{"type":"text","text":"0: Communication. Use this profile when there are only two users in the"},{"type":"text","text":" "},{"type":"text","text":"channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileCommunication"}],"url":"\/documentation\/agorartckit\/agorachannelprofile\/communication"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelProfile/communication_1v1":{"deprecated":true,"role":"symbol","title":"AgoraChannelProfile.communication_1v1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"communication_1v1"}],"abstract":[{"type":"text","text":"1: Live streaming. Live streaming. Use this profile when there are more"},{"type":"text","text":" "},{"type":"text","text":"than two users in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication_1v1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelProfileCommunication_1v1"}],"url":"\/documentation\/agorartckit\/agorachannelprofile\/communication_1v1"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelProfile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfile"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChannelProfile"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/cloudGaming","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/communication_1v1","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/game","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelProfile\/liveBroadcasting"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1liveBroadcasting\/title","value":"AgoraChannelProfileLiveBroadcasting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1liveBroadcasting\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileLiveBroadcasting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile\/title","value":"AgoraChannelProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1game\/title","value":"AgoraChannelProfileGame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1game\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileGame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1cloudGaming\/title","value":"AgoraChannelProfileCloudGaming"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1cloudGaming\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileCloudGaming"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1communication\/title","value":"AgoraChannelProfileCommunication"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1communication\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileCommunication"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1communication_1v1\/title","value":"AgoraChannelProfileCommunication_1v1"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelProfile~1communication_1v1\/fragments","value":[{"kind":"identifier","text":"AgoraChannelProfileCommunication_1v1"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}