{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracontentinspectconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracontentinspectconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration of video screenshot and upload."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectConfig"}],"title":"AgoraContentInspectConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraContentInspectConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/extraInfo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/modules"]}],"references":{"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectConfig/modules":{"role":"symbol","title":"modules","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraContentInspectModule","preciseIdentifier":"c:objc(cs)AgoraContentInspectModule"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Functional module. See AgoraContentInspectModule .A maximum of 32"},{"type":"text","text":" "},{"type":"text","text":"AgoraContentInspectModule instances can be configured, and the value range of"},{"type":"text","text":" "},{"type":"text","text":"MAX_CONTENT_INSPECT_MODULE_COUNT is an integer in [1,32].A function module"},{"type":"text","text":" "},{"type":"text","text":"can only be configured with one instance at most. Currently only the video"},{"type":"text","text":" "},{"type":"text","text":"screenshot and upload function is supported."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/modules","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modules"}],"url":"\/documentation\/agorartckit\/agoracontentinspectconfig\/modules"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectConfig":{"role":"symbol","title":"AgoraContentInspectConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectConfig"}],"abstract":[{"type":"text","text":"Configuration of video screenshot and upload."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraContentInspectConfig"}],"url":"\/documentation\/agorartckit\/agoracontentinspectconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraContentInspectConfig/extraInfo":{"role":"symbol","title":"extraInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"extraInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Additional information on the video content (maximum length: 1024 Bytes).The"},{"type":"text","text":" "},{"type":"text","text":"SDK sends the screenshots and additional information on the video content to"},{"type":"text","text":" "},{"type":"text","text":"the Agora server. Once the video screenshot and upload process is completed,"},{"type":"text","text":" "},{"type":"text","text":"the Agora server sends the additional information and the callback"},{"type":"text","text":" "},{"type":"text","text":"notification to your server."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/extraInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"extraInfo"}],"url":"\/documentation\/agorartckit\/agoracontentinspectconfig\/extrainfo"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraContentInspectConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraContentInspectConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/extraInfo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraContentInspectConfig\/modules"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraContentInspectConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig~1modules\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig~1modules\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig\/title","value":"AgoraContentInspectConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig\/fragments","value":[{"kind":"identifier","text":"AgoraContentInspectConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig~1extraInfo\/title","value":"extraInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraContentInspectConfig~1extraInfo\/fragments","value":[{"kind":"identifier","text":"extraInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}