{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFramePosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframeposition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoframeposition"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP","doc:\/\/AgoraRtcKit\/s9OptionSetP","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP","doc:\/\/AgoraRtcKit\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/postCapture","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/preEncoder","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/preRenderer"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/OptionSet-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/SetAlgebra-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFramePosition"}],"title":"AgoraVideoFramePosition","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@E@AgoraVideoFramePosition","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFramePosition"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/AgoraRtcKit\/s9OptionSetP"},"doc://AgoraRtcKit/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoframeposition\/optionset-implementations"},"doc://AgoraRtcKit/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/AgoraRtcKit\/s10SetAlgebraP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideoframeposition\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition/preRenderer":{"role":"symbol","title":"preRenderer","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preRenderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFramePosition","preciseIdentifier":"c:@E@AgoraVideoFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/preRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFramePositionPreRenderer"}],"url":"\/documentation\/agorartckit\/agoravideoframeposition\/prerenderer"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoframeposition\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoframeposition\/setalgebra-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition/postCapture":{"role":"symbol","title":"postCapture","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFramePosition","preciseIdentifier":"c:@E@AgoraVideoFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/postCapture","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFramePositionPostCapture"}],"url":"\/documentation\/agorartckit\/agoravideoframeposition\/postcapture"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition":{"role":"symbol","title":"AgoraVideoFramePosition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFramePosition"}],"url":"\/documentation\/agorartckit\/agoravideoframeposition"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition/preEncoder":{"role":"symbol","title":"preEncoder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preEncoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFramePosition","preciseIdentifier":"c:@E@AgoraVideoFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/preEncoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFramePositionPreEncoder"}],"url":"\/documentation\/agorartckit\/agoravideoframeposition\/preencoder"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoFramePosition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFramePosition"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoFramePosition"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/postCapture","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/preEncoder","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition\/preRenderer"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFramePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition~1preRenderer\/title","value":"AgoraVideoFramePositionPreRenderer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition~1preRenderer\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFramePositionPreRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition~1postCapture\/title","value":"AgoraVideoFramePositionPostCapture"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition~1postCapture\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFramePositionPostCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition\/title","value":"AgoraVideoFramePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFramePosition"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition~1preEncoder\/title","value":"AgoraVideoFramePositionPreEncoder"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition~1preEncoder\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFramePositionPreEncoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}