{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Observer settings for encoded audio."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"title":"AgoraAudioEncodedFrameDelegateConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraAudioEncodedFrameDelegateConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/encodingType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/postionType"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegateConfig/postionType":{"role":"symbol","title":"postionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioEncodedFrameDelegatePosition","preciseIdentifier":"c:@E@AgoraAudioEncodedFrameDelegatePosition"}],"abstract":[{"type":"text","text":"Audio profile. See AgoraAudioEncodedFrameDelegatePosition ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/postionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"postionType"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig\/postiontype"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegateConfig/encodingType":{"role":"symbol","title":"encodingType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioEncodingType","preciseIdentifier":"c:@E@AgoraAudioEncodingType"}],"abstract":[{"type":"text","text":"Audio encoding type. See AgoraAudioEncodingType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/encodingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodingType"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig\/encodingtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEncodedFrameDelegateConfig":{"role":"symbol","title":"AgoraAudioEncodedFrameDelegateConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"abstract":[{"type":"text","text":"Observer settings for encoded audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}],"url":"\/documentation\/agorartckit\/agoraaudioencodedframedelegateconfig"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEncodedFrameDelegateConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/encodingType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEncodedFrameDelegateConfig\/postionType"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig~1postionType\/title","value":"postionType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig~1postionType\/fragments","value":[{"kind":"identifier","text":"postionType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig~1encodingType\/title","value":"encodingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig~1encodingType\/fragments","value":[{"kind":"identifier","text":"encodingType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig\/title","value":"AgoraAudioEncodedFrameDelegateConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEncodedFrameDelegateConfig\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEncodedFrameDelegateConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}