{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclientdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclientdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:channel:connectionStateChanged:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:on:)-3zvu4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:on:)-9cigc","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinChannel:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:leaveChannel:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:leaveTopic:inChannel:withMeta:result:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientDelegate"}],"title":"AgoraRtmClientDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraRtmClientDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:on:)-9cigc":{"role":"symbol","title":"rtmKit(_:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmMessageEvent","preciseIdentifier":"c:objc(cs)AgoraRtmMessageEvent"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:on:)-9cigc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtmKit:onMessageEvent:"}],"url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:on:)-9cigc"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:)":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:"}],"role":"symbol","title":"rtmKit(_:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withUnsubscribeSuccess"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withUnsubscribeFailed"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:intopic:inchannel:withunsubscribesuccess:withunsubscribefailed:result:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate":{"role":"symbol","title":"AgoraRtmClientDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientDelegate"}],"url":"\/documentation\/agorartckit\/agorartmclientdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:on:)-3zvu4":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:onPresenceEvent:"}],"role":"symbol","title":"rtmKit(_:on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmPresenceEvent","preciseIdentifier":"c:objc(cs)AgoraRtmPresenceEvent"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:on:)-3zvu4","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:on:)-3zvu4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"}],"role":"symbol","title":"rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMeta"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:jointopic:inchannel:withmeta:result:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:onUser:leaveChannel:result:)":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:leaveChannel:result:"}],"role":"symbol","title":"rtmKit(_:onUser:leaveChannel:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leaveChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:leaveChannel:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:leavechannel:result:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:onUser:leaveTopic:inChannel:withMeta:result:)":{"role":"symbol","title":"rtmKit(_:onUser:leaveTopic:inChannel:withMeta:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leaveTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMeta"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:leaveTopic:inChannel:withMeta:result:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:leaveTopic:inChannel:withMeta:result:"}],"url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:leavetopic:inchannel:withmeta:result:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:onUser:joinChannel:result:)":{"role":"symbol","title":"rtmKit(_:onUser:joinChannel:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinChannel:result:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:joinChannel:result:"}],"url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:joinchannel:result:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:channel:connectionStateChanged:result:)":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:channel:connectionStateChanged:result:"}],"role":"symbol","title":"rtmKit(_:channel:connectionStateChanged:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionStateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmClientConnectionState","preciseIdentifier":"c:@E@AgoraRtmClientConnectionState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmClientConnectionChangeReason","preciseIdentifier":"c:@E@AgoraRtmClientConnectionChangeReason"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:channel:connectionStateChanged:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:channel:connectionstatechanged:result:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:)":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:"}],"role":"symbol","title":"rtmKit(_:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSubscribeSuccess"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withSubscribeFailed"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:intopic:inchannel:withsubscribesuccess:withsubscribefailed:result:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmClientDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtmClientDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:channel:connectionStateChanged:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:on:)-3zvu4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:on:)-9cigc","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinChannel:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:leaveChannel:result:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:leaveTopic:inChannel:withMeta:result:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:on:)-9cigc\/title","value":"rtmKit:onMessageEvent:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:on:)-9cigc\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onMessageEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:)\/title","value":"rtmKit:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:inTopic:inChannel:withUnsubscribeSuccess:withUnsubscribeFailed:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate\/title","value":"AgoraRtmClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:on:)-3zvu4\/title","value":"rtmKit:onPresenceEvent:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:on:)-3zvu4\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onPresenceEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)\/title","value":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:leaveChannel:result:)\/title","value":"rtmKit:onUser:leaveChannel:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:leaveChannel:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:leaveChannel:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:leaveTopic:inChannel:withMeta:result:)\/title","value":"rtmKit:onUser:leaveTopic:inChannel:withMeta:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:leaveTopic:inChannel:withMeta:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:leaveTopic:inChannel:withMeta:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:joinChannel:result:)\/title","value":"rtmKit:onUser:joinChannel:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:joinChannel:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:joinChannel:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:channel:connectionStateChanged:result:)\/title","value":"rtmKit:channel:connectionStateChanged:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:channel:connectionStateChanged:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:channel:connectionStateChanged:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:)\/title","value":"rtmKit:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:inTopic:inChannel:withSubscribeSuccess:withSubscribeFailed:result:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}