{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraheadphoneeqpreset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraheadphoneeqpreset"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetInear","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOff","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOverear"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"title":"AgoraHeadphoneEQPreset","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraHeadphoneEQPreset","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/audioHeadphoneEQPresetInear":{"role":"symbol","title":"AgoraHeadphoneEQPreset.audioHeadphoneEQPresetInear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetInear"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetInear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetInear"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetinear"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/audioHeadphoneEQPresetOff":{"role":"symbol","title":"AgoraHeadphoneEQPreset.audioHeadphoneEQPresetOff","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetOff"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOff","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOff"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetoff"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/init(rawvalue:)"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset/audioHeadphoneEQPresetOverear":{"role":"symbol","title":"AgoraHeadphoneEQPreset.audioHeadphoneEQPresetOverear","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioHeadphoneEQPresetOverear"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOverear","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOverear"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset\/audioheadphoneeqpresetoverear"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraHeadphoneEQPreset":{"role":"symbol","title":"AgoraHeadphoneEQPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}],"url":"\/documentation\/agorartckit\/agoraheadphoneeqpreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraHeadphoneEQPreset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetInear","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOff","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraHeadphoneEQPreset\/audioHeadphoneEQPresetOverear"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraHeadphoneEQPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetInear\/title","value":"AgoraAudioHeadphoneEQPresetInear"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetInear\/fragments","value":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetInear"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetOff\/title","value":"AgoraAudioHeadphoneEQPresetOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetOff\/fragments","value":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOff"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetOverear\/title","value":"AgoraAudioHeadphoneEQPresetOverear"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset~1audioHeadphoneEQPresetOverear\/fragments","value":[{"kind":"identifier","text":"AgoraAudioHeadphoneEQPresetOverear"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/title","value":"AgoraHeadphoneEQPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraHeadphoneEQPreset\/fragments","value":[{"kind":"identifier","text":"AgoraHeadphoneEQPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}