{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocaltranscoderconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocaltranscoderconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/syncWithPrimaryCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoInputStreams","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoOutputConfiguration"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}],"title":"AgoraLocalTranscoderConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLocalTranscoderConfiguration","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalTranscoderConfiguration/videoOutputConfiguration":{"role":"symbol","title":"videoOutputConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoOutputConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoEncoderConfiguration","preciseIdentifier":"c:objc(cs)AgoraVideoEncoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoOutputConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoOutputConfiguration"}],"url":"\/documentation\/agorartckit\/agoralocaltranscoderconfiguration\/videooutputconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalTranscoderConfiguration/syncWithPrimaryCamera":{"role":"symbol","title":"syncWithPrimaryCamera","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncWithPrimaryCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/syncWithPrimaryCamera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"syncWithPrimaryCamera"}],"url":"\/documentation\/agorartckit\/agoralocaltranscoderconfiguration\/syncwithprimarycamera"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalTranscoderConfiguration":{"role":"symbol","title":"AgoraLocalTranscoderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}],"url":"\/documentation\/agorartckit\/agoralocaltranscoderconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalTranscoderConfiguration/videoInputStreams":{"role":"symbol","title":"videoInputStreams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoInputStreams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraTranscodingVideoStream","preciseIdentifier":"c:objc(cs)AgoraTranscodingVideoStream"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoInputStreams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoInputStreams"}],"url":"\/documentation\/agorartckit\/agoralocaltranscoderconfiguration\/videoinputstreams"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalTranscoderConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/syncWithPrimaryCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoInputStreams","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalTranscoderConfiguration\/videoOutputConfiguration"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1videoOutputConfiguration\/title","value":"videoOutputConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1videoOutputConfiguration\/fragments","value":[{"kind":"identifier","text":"videoOutputConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1syncWithPrimaryCamera\/title","value":"syncWithPrimaryCamera"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1syncWithPrimaryCamera\/fragments","value":[{"kind":"identifier","text":"syncWithPrimaryCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration\/title","value":"AgoraLocalTranscoderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraLocalTranscoderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1videoInputStreams\/title","value":"videoInputStreams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalTranscoderConfiguration~1videoInputStreams\/fragments","value":[{"kind":"identifier","text":"videoInputStreams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}