{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoremotereason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoremotereason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The reason for the remote video state change."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteReason"}],"title":"AgoraVideoRemoteReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoRemoteReason","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReason"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/audioFallback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/audioFallbackRecovery","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/codecNotSupport","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/congestion","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localUnmuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/recovery","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteOffline","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteUnmuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/sdkInBackground"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/sdkInBackground":{"role":"symbol","title":"AgoraVideoRemoteReason.sdkInBackground","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInBackground"}],"abstract":[{"type":"text","text":"12: (iOS only) The remote user’s app has switched to the background."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/sdkInBackground","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonSDKInBackground"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/sdkinbackground"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/localMuted":{"role":"symbol","title":"AgoraVideoRemoteReason.localMuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localMuted"}],"abstract":[{"type":"text","text":"3: The local user stops receiving the remote video stream or disables the video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalMuted"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/localmuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/recovery":{"role":"symbol","title":"AgoraVideoRemoteReason.recovery","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recovery"}],"abstract":[{"type":"text","text":"2: Network is recovered."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/recovery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRecovery"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/recovery"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoremotereason\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideoremotereason\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/congestion":{"role":"symbol","title":"AgoraVideoRemoteReason.congestion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"congestion"}],"abstract":[{"type":"text","text":"1: Network congestion."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/congestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonCongestion"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/congestion"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/remoteMuted":{"role":"symbol","title":"AgoraVideoRemoteReason.remoteMuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteMuted"}],"abstract":[{"type":"text","text":"5: The remote user stops sending the video stream or disables the video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteMuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRemoteMuted"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/remotemuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoremotereason\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/remoteOffline":{"role":"symbol","title":"AgoraVideoRemoteReason.remoteOffline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteOffline"}],"abstract":[{"type":"text","text":"7: The remote user leaves the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteOffline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRemoteOffline"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/remoteoffline"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/codecNotSupport":{"role":"symbol","title":"AgoraVideoRemoteReason.codecNotSupport","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecNotSupport"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/codecNotSupport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonCodecNotSupport"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/codecnotsupport"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/audioFallback":{"role":"symbol","title":"AgoraVideoRemoteReason.audioFallback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioFallback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/audioFallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonAudioFallback"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/audiofallback"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/internal":{"role":"symbol","title":"AgoraVideoRemoteReason.internal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"}],"abstract":[{"type":"text","text":"0: The SDK reports this reason when the video state changes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/internal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonInternal"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/internal"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/audioFallbackRecovery":{"role":"symbol","title":"AgoraVideoRemoteReason.audioFallbackRecovery","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioFallbackRecovery"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/audioFallbackRecovery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonAudioFallbackRecovery"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/audiofallbackrecovery"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/remoteUnmuted":{"role":"symbol","title":"AgoraVideoRemoteReason.remoteUnmuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUnmuted"}],"abstract":[{"type":"text","text":"6: The remote user resumes sending the video stream or enables the video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteUnmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRemoteUnmuted"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/remoteunmuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason/localUnmuted":{"role":"symbol","title":"AgoraVideoRemoteReason.localUnmuted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localUnmuted"}],"abstract":[{"type":"text","text":"4: The local user resumes receiving the remote video stream or enables the video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localUnmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalUnmuted"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason\/localunmuted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteReason":{"role":"symbol","title":"AgoraVideoRemoteReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteReason"}],"abstract":[{"type":"text","text":"The reason for the remote video state change."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteReason"}],"url":"\/documentation\/agorartckit\/agoravideoremotereason"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoRemoteReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoRemoteReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/audioFallback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/audioFallbackRecovery","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/codecNotSupport","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/congestion","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/localUnmuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/recovery","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteMuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteOffline","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/remoteUnmuted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteReason\/sdkInBackground"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1sdkInBackground\/title","value":"AgoraVideoRemoteReasonSDKInBackground"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1sdkInBackground\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonSDKInBackground"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1localMuted\/title","value":"AgoraVideoRemoteReasonLocalMuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1localMuted\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1recovery\/title","value":"AgoraVideoRemoteReasonRecovery"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1recovery\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRecovery"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1congestion\/title","value":"AgoraVideoRemoteReasonCongestion"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1congestion\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonCongestion"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1remoteMuted\/title","value":"AgoraVideoRemoteReasonRemoteMuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1remoteMuted\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRemoteMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1remoteOffline\/title","value":"AgoraVideoRemoteReasonRemoteOffline"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1remoteOffline\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRemoteOffline"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1codecNotSupport\/title","value":"AgoraVideoRemoteReasonCodecNotSupport"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1codecNotSupport\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonCodecNotSupport"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1audioFallback\/title","value":"AgoraVideoRemoteReasonAudioFallback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1audioFallback\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonAudioFallback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1internal\/title","value":"AgoraVideoRemoteReasonInternal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1internal\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonInternal"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1audioFallbackRecovery\/title","value":"AgoraVideoRemoteReasonAudioFallbackRecovery"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1audioFallbackRecovery\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonAudioFallbackRecovery"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1remoteUnmuted\/title","value":"AgoraVideoRemoteReasonRemoteUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1remoteUnmuted\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonRemoteUnmuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1localUnmuted\/title","value":"AgoraVideoRemoteReasonLocalUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason~1localUnmuted\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReasonLocalUnmuted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason\/title","value":"AgoraVideoRemoteReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteReason\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}