{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:audioMixingPositionChanged:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:audioMixingStateChanged:reasonCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:cameraExposureDidChangedTo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:cameraFocusDidChangedTo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didAudioRouteChanged:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChangeFailed:currentRole:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didLeaveChannelWith:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didLocalUserRegisteredWithUserId:userAccount:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccur:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccurError:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didUserInfoUpdatedWithUserId:userInfo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalAudioFramePublished:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalVideoFramePublishedWithElapsed:sourceType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalVideoFrameWith:elapsed:sourceType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:lastmileProbeTest:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:lastmileQuality:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:localAudioStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:localVideoStats:sourceType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:remoteAudioStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:remoteVideoStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:reportRtcStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingEventWithUrl:eventCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:streamPublishedWithUrl:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:streamUnpublishedWithUrl:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:uploadLogResultRequestId:success:reason:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineCameraDidReady(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidBanned(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidInterrupted(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidLost(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineDidAudioEffectFinish(_:soundId:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineLocalAudioMixingDidFinish(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineMediaEngineDidLoaded(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineMediaEngineDidStartCall(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRemoteAudioMixingDidFinish(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRemoteAudioMixingDidStart(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRequestToken(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineTranscodingUpdated(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineVideoDidStop(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseDelegate"}],"title":"AgoraBaseDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraBaseDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraBaseDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineRemoteAudioMixingDidFinish(_:)":{"role":"symbol","title":"rtcEngineRemoteAudioMixingDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineRemoteAudioMixingDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRemoteAudioMixingDidFinish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineRemoteAudioMixingDidFinish:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengineremoteaudiomixingdidfinish(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didLocalUserRegisteredWithUserId:userAccount:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didLocalUserRegisteredWithUserId:userAccount:"}],"role":"symbol","title":"rtcEngine(_:didLocalUserRegisteredWithUserId:userAccount:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLocalUserRegisteredWithUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didLocalUserRegisteredWithUserId:userAccount:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didlocaluserregisteredwithuserid:useraccount:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate2":{"role":"symbol","title":"AgoraRtcEngineDelegate2","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:streamUnpublishedWithUrl:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:streamUnpublishedWithUrl:"}],"role":"symbol","title":"rtcEngine(_:streamUnpublishedWithUrl:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamUnpublishedWithUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:streamUnpublishedWithUrl:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:streamunpublishedwithurl:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:firstLocalVideoFrameWith:elapsed:sourceType:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:firstLocalVideoFrameWithSize:elapsed:sourceType:"}],"role":"symbol","title":"rtcEngine(_:firstLocalVideoFrameWith:elapsed:sourceType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"firstLocalVideoFrameWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalVideoFrameWith:elapsed:sourceType:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:firstlocalvideoframewith:elapsed:sourcetype:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineConnectionDidLost(_:)":{"role":"symbol","title":"rtcEngineConnectionDidLost(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineConnectionDidLost"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidLost(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineConnectionDidLost:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengineconnectiondidlost(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:lastmileQuality:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:lastmileQuality:"}],"role":"symbol","title":"rtcEngine(_:lastmileQuality:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastmileQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:lastmileQuality:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:lastmilequality:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didOccur:)":{"role":"symbol","title":"rtcEngine(_:didOccur:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccur"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEncryptionErrorType","preciseIdentifier":"c:@E@AgoraEncryptionErrorType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccur:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didOccurEncryptionError:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didoccur:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineTranscodingUpdated(_:)":{"role":"symbol","title":"rtcEngineTranscodingUpdated(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineTranscodingUpdated"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineTranscodingUpdated(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineTranscodingUpdated:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginetranscodingupdated(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineConnectionDidBanned(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngineConnectionDidBanned:"}],"role":"symbol","title":"rtcEngineConnectionDidBanned(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineConnectionDidBanned"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidBanned(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengineconnectiondidbanned(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:audioMixingPositionChanged:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:audioMixingPositionChanged:"}],"role":"symbol","title":"rtcEngine(_:audioMixingPositionChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioMixingPositionChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:audioMixingPositionChanged:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:audiomixingpositionchanged:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineDidAudioEffectFinish(_:soundId:)":{"role":"symbol","title":"rtcEngineDidAudioEffectFinish(_:soundId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineDidAudioEffectFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"soundId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineDidAudioEffectFinish(_:soundId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineDidAudioEffectFinish:soundId:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginedidaudioeffectfinish(_:soundid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"}],"role":"symbol","title":"rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rtmpStreamingChangedToState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamingState","preciseIdentifier":"c:@E@AgoraRtmpStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamingErrorCode","preciseIdentifier":"c:@E@AgoraRtmpStreamingErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:rtmpstreamingchangedtostate:state:errcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:firstLocalAudioFramePublished:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:firstLocalAudioFramePublished:"}],"role":"symbol","title":"rtcEngine(_:firstLocalAudioFramePublished:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"firstLocalAudioFramePublished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalAudioFramePublished:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:firstlocalaudioframepublished:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:cameraFocusDidChangedTo:)":{"role":"symbol","title":"rtcEngine(_:cameraFocusDidChangedTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFocusDidChangedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:cameraFocusDidChangedTo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:cameraFocusDidChangedToRect:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:camerafocusdidchangedto:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:streamPublishedWithUrl:errorCode:)":{"role":"symbol","title":"rtcEngine(_:streamPublishedWithUrl:errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamPublishedWithUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraErrorCode","preciseIdentifier":"c:@E@AgoraErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:streamPublishedWithUrl:errorCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:streamPublishedWithUrl:errorCode:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:streampublishedwithurl:errorcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:audioMixingStateChanged:reasonCode:)":{"role":"symbol","title":"rtcEngine(_:audioMixingStateChanged:reasonCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioMixingStateChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioMixingStateType","preciseIdentifier":"c:@E@AgoraAudioMixingStateType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reasonCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioMixingReasonCode","preciseIdentifier":"c:@E@AgoraAudioMixingReasonCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:audioMixingStateChanged:reasonCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:audioMixingStateChanged:reasonCode:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:audiomixingstatechanged:reasoncode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:localAudioStats:)":{"role":"symbol","title":"rtcEngine(_:localAudioStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localAudioStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcLocalAudioStats","preciseIdentifier":"c:objc(cs)AgoraRtcLocalAudioStats"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:localAudioStats:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:localAudioStats:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:localaudiostats:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineLocalAudioMixingDidFinish(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngineLocalAudioMixingDidFinish:"}],"role":"symbol","title":"rtcEngineLocalAudioMixingDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineLocalAudioMixingDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineLocalAudioMixingDidFinish(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginelocalaudiomixingdidfinish(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didUserInfoUpdatedWithUserId:userInfo:)":{"role":"symbol","title":"rtcEngine(_:didUserInfoUpdatedWithUserId:userInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUserInfoUpdatedWithUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraUserInfo","preciseIdentifier":"c:objc(cs)AgoraUserInfo"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didUserInfoUpdatedWithUserId:userInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didUserInfoUpdatedWithUserId:userInfo:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:diduserinfoupdatedwithuserid:userinfo:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineMediaEngineDidStartCall(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngineMediaEngineDidStartCall:"}],"role":"symbol","title":"rtcEngineMediaEngineDidStartCall(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineMediaEngineDidStartCall"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineMediaEngineDidStartCall(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginemediaenginedidstartcall(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:remoteVideoStats:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:remoteVideoStats:"}],"role":"symbol","title":"rtcEngine(_:remoteVideoStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"remoteVideoStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcRemoteVideoStats","preciseIdentifier":"c:objc(cs)AgoraRtcRemoteVideoStats"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:remoteVideoStats:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:remotevideostats:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didLeaveChannelWith:)":{"role":"symbol","title":"rtcEngine(_:didLeaveChannelWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLeaveChannelWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didLeaveChannelWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didLeaveChannelWithStats:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didleavechannelwith:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:cameraExposureDidChangedTo:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:cameraExposureDidChangedToRect:"}],"role":"symbol","title":"rtcEngine(_:cameraExposureDidChangedTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraExposureDidChangedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:cameraExposureDidChangedTo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:cameraexposuredidchangedto:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineVideoDidStop(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngineVideoDidStop:"}],"role":"symbol","title":"rtcEngineVideoDidStop(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineVideoDidStop"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineVideoDidStop(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginevideodidstop(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:remoteAudioStats:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:remoteAudioStats:"}],"role":"symbol","title":"rtcEngine(_:remoteAudioStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"remoteAudioStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcRemoteAudioStats","preciseIdentifier":"c:objc(cs)AgoraRtcRemoteAudioStats"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:remoteAudioStats:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:remoteaudiostats:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineRemoteAudioMixingDidStart(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngineRemoteAudioMixingDidStart:"}],"role":"symbol","title":"rtcEngineRemoteAudioMixingDidStart(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineRemoteAudioMixingDidStart"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRemoteAudioMixingDidStart(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengineremoteaudiomixingdidstart(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:lastmileProbeTest:)":{"role":"symbol","title":"rtcEngine(_:lastmileProbeTest:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lastmileProbeTest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLastmileProbeResult","preciseIdentifier":"c:objc(cs)AgoraLastmileProbeResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:lastmileProbeTest:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:lastmileProbeTestResult:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:lastmileprobetest:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineRequestToken(_:)":{"role":"symbol","title":"rtcEngineRequestToken(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineRequestToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRequestToken(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineRequestToken:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginerequesttoken(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didOccurError:)":{"role":"symbol","title":"rtcEngine(_:didOccurError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccurError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraErrorCode","preciseIdentifier":"c:@E@AgoraErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccurError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didOccurError:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didoccurerror:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)":{"role":"symbol","title":"rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"facePositionDidChangeWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faces"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraFacePositionInfo","preciseIdentifier":"c:objc(cs)AgoraFacePositionInfo"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:facepositiondidchangewidth:previewheight:faces:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didAudioRouteChanged:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didAudioRouteChanged:"}],"role":"symbol","title":"rtcEngine(_:didAudioRouteChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAudioRouteChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioOutputRouting","preciseIdentifier":"c:@E@AgoraAudioOutputRouting"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didAudioRouteChanged:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didaudioroutechanged:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:localVideoStats:sourceType:)":{"role":"symbol","title":"rtcEngine(_:localVideoStats:sourceType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"localVideoStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcLocalVideoStats","preciseIdentifier":"c:objc(cs)AgoraRtcLocalVideoStats"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:localVideoStats:sourceType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:localVideoStats:sourceType:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:localvideostats:sourcetype:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineMediaEngineDidLoaded(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngineMediaEngineDidLoaded:"}],"role":"symbol","title":"rtcEngineMediaEngineDidLoaded(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineMediaEngineDidLoaded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineMediaEngineDidLoaded(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginemediaenginedidloaded(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineConnectionDidInterrupted(_:)":{"role":"symbol","title":"rtcEngineConnectionDidInterrupted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineConnectionDidInterrupted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidInterrupted(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineConnectionDidInterrupted:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengineconnectiondidinterrupted(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:rtmpStreamingEventWithUrl:eventCode:)":{"role":"symbol","title":"rtcEngine(_:rtmpStreamingEventWithUrl:eventCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rtmpStreamingEventWithUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"eventCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamingEvent","preciseIdentifier":"c:@E@AgoraRtmpStreamingEvent"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingEventWithUrl:eventCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:rtmpStreamingEventWithUrl:eventCode:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:rtmpstreamingeventwithurl:eventcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:firstLocalVideoFramePublishedWithElapsed:sourceType:)":{"role":"symbol","title":"rtcEngine(_:firstLocalVideoFramePublishedWithElapsed:sourceType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"firstLocalVideoFramePublishedWithElapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalVideoFramePublishedWithElapsed:sourceType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:firstLocalVideoFramePublishedWithElapsed:sourceType:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:firstlocalvideoframepublishedwithelapsed:sourcetype:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}],"role":"symbol","title":"rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reportAudioVolumeIndicationOfSpeakers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraRtcAudioVolumeInfo","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"totalVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)":{"role":"symbol","title":"rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClientRoleChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRoleOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didclientrolechanged:newrole:newroleoptions:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:reportRtcStats:)":{"role":"symbol","title":"rtcEngine(_:reportRtcStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reportRtcStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:reportRtcStats:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:reportRtcStats:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:reportrtcstats:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngineCameraDidReady(_:)":{"role":"symbol","title":"rtcEngineCameraDidReady(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineCameraDidReady"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineCameraDidReady(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineCameraDidReady:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcenginecameradidready(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:didClientRoleChangeFailed:currentRole:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didClientRoleChangeFailed:currentRole:"}],"role":"symbol","title":"rtcEngine(_:didClientRoleChangeFailed:currentRole:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClientRoleChangeFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleChangeFailedReason","preciseIdentifier":"c:@E@AgoraClientRoleChangeFailedReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChangeFailed:currentRole:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:didclientrolechangefailed:currentrole:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate":{"role":"symbol","title":"AgoraBaseDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseDelegate"}],"url":"\/documentation\/agorartckit\/agorabasedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseDelegate/rtcEngine(_:uploadLogResultRequestId:success:reason:)":{"role":"symbol","title":"rtcEngine(_:uploadLogResultRequestId:success:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uploadLogResultRequestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraUploadErrorReason","preciseIdentifier":"c:@E@AgoraUploadErrorReason"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:uploadLogResultRequestId:success:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:uploadLogResultRequestId:success:reason:"}],"url":"\/documentation\/agorartckit\/agorabasedelegate\/rtcengine(_:uploadlogresultrequestid:success:reason:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraBaseDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraBaseDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraBaseDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:audioMixingPositionChanged:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:audioMixingStateChanged:reasonCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:cameraExposureDidChangedTo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:cameraFocusDidChangedTo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didAudioRouteChanged:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChangeFailed:currentRole:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didLeaveChannelWith:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didLocalUserRegisteredWithUserId:userAccount:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccur:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didOccurError:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:didUserInfoUpdatedWithUserId:userInfo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalAudioFramePublished:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalVideoFramePublishedWithElapsed:sourceType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:firstLocalVideoFrameWith:elapsed:sourceType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:lastmileProbeTest:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:lastmileQuality:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:localAudioStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:localVideoStats:sourceType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:remoteAudioStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:remoteVideoStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:reportRtcStats:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:rtmpStreamingEventWithUrl:eventCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:streamPublishedWithUrl:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:streamUnpublishedWithUrl:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngine(_:uploadLogResultRequestId:success:reason:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineCameraDidReady(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidBanned(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidInterrupted(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineConnectionDidLost(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineDidAudioEffectFinish(_:soundId:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineLocalAudioMixingDidFinish(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineMediaEngineDidLoaded(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineMediaEngineDidStartCall(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRemoteAudioMixingDidFinish(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRemoteAudioMixingDidStart(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineRequestToken(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineTranscodingUpdated(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseDelegate\/rtcEngineVideoDidStop(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate2"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineRemoteAudioMixingDidFinish(_:)\/title","value":"rtcEngineRemoteAudioMixingDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineRemoteAudioMixingDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineRemoteAudioMixingDidFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didLocalUserRegisteredWithUserId:userAccount:)\/title","value":"rtcEngine:didLocalUserRegisteredWithUserId:userAccount:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didLocalUserRegisteredWithUserId:userAccount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didLocalUserRegisteredWithUserId:userAccount:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/title","value":"AgoraRtcEngineDelegate2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate2\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:streamUnpublishedWithUrl:)\/title","value":"rtcEngine:streamUnpublishedWithUrl:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:streamUnpublishedWithUrl:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:streamUnpublishedWithUrl:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:firstLocalVideoFrameWith:elapsed:sourceType:)\/title","value":"rtcEngine:firstLocalVideoFrameWithSize:elapsed:sourceType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:firstLocalVideoFrameWith:elapsed:sourceType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:firstLocalVideoFrameWithSize:elapsed:sourceType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineConnectionDidLost(_:)\/title","value":"rtcEngineConnectionDidLost:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineConnectionDidLost(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineConnectionDidLost:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:lastmileQuality:)\/title","value":"rtcEngine:lastmileQuality:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:lastmileQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:lastmileQuality:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didOccur:)\/title","value":"rtcEngine:didOccurEncryptionError:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didOccur:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didOccurEncryptionError:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineTranscodingUpdated(_:)\/title","value":"rtcEngineTranscodingUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineTranscodingUpdated(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineTranscodingUpdated:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineConnectionDidBanned(_:)\/title","value":"rtcEngineConnectionDidBanned:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineConnectionDidBanned(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineConnectionDidBanned:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:audioMixingPositionChanged:)\/title","value":"rtcEngine:audioMixingPositionChanged:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:audioMixingPositionChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:audioMixingPositionChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineDidAudioEffectFinish(_:soundId:)\/title","value":"rtcEngineDidAudioEffectFinish:soundId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineDidAudioEffectFinish(_:soundId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineDidAudioEffectFinish:soundId:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)\/title","value":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:rtmpStreamingChangedToState:state:errCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:rtmpStreamingChangedToState:state:errCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:firstLocalAudioFramePublished:)\/title","value":"rtcEngine:firstLocalAudioFramePublished:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:firstLocalAudioFramePublished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:firstLocalAudioFramePublished:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:cameraFocusDidChangedTo:)\/title","value":"rtcEngine:cameraFocusDidChangedToRect:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:cameraFocusDidChangedTo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:cameraFocusDidChangedToRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:streamPublishedWithUrl:errorCode:)\/title","value":"rtcEngine:streamPublishedWithUrl:errorCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:streamPublishedWithUrl:errorCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:streamPublishedWithUrl:errorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:audioMixingStateChanged:reasonCode:)\/title","value":"rtcEngine:audioMixingStateChanged:reasonCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:audioMixingStateChanged:reasonCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:audioMixingStateChanged:reasonCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:localAudioStats:)\/title","value":"rtcEngine:localAudioStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:localAudioStats:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:localAudioStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineLocalAudioMixingDidFinish(_:)\/title","value":"rtcEngineLocalAudioMixingDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineLocalAudioMixingDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineLocalAudioMixingDidFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didUserInfoUpdatedWithUserId:userInfo:)\/title","value":"rtcEngine:didUserInfoUpdatedWithUserId:userInfo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didUserInfoUpdatedWithUserId:userInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didUserInfoUpdatedWithUserId:userInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineMediaEngineDidStartCall(_:)\/title","value":"rtcEngineMediaEngineDidStartCall:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineMediaEngineDidStartCall(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineMediaEngineDidStartCall:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:remoteVideoStats:)\/title","value":"rtcEngine:remoteVideoStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:remoteVideoStats:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:remoteVideoStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didLeaveChannelWith:)\/title","value":"rtcEngine:didLeaveChannelWithStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didLeaveChannelWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didLeaveChannelWithStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:cameraExposureDidChangedTo:)\/title","value":"rtcEngine:cameraExposureDidChangedToRect:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:cameraExposureDidChangedTo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:cameraExposureDidChangedToRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineVideoDidStop(_:)\/title","value":"rtcEngineVideoDidStop:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineVideoDidStop(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineVideoDidStop:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:remoteAudioStats:)\/title","value":"rtcEngine:remoteAudioStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:remoteAudioStats:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:remoteAudioStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineRemoteAudioMixingDidStart(_:)\/title","value":"rtcEngineRemoteAudioMixingDidStart:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineRemoteAudioMixingDidStart(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineRemoteAudioMixingDidStart:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:lastmileProbeTest:)\/title","value":"rtcEngine:lastmileProbeTestResult:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:lastmileProbeTest:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:lastmileProbeTestResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineRequestToken(_:)\/title","value":"rtcEngineRequestToken:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineRequestToken(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineRequestToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didOccurError:)\/title","value":"rtcEngine:didOccurError:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didOccurError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didOccurError:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)\/title","value":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:facePositionDidChangeWidth:previewHeight:faces:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:facePositionDidChangeWidth:previewHeight:faces:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didAudioRouteChanged:)\/title","value":"rtcEngine:didAudioRouteChanged:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didAudioRouteChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didAudioRouteChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:localVideoStats:sourceType:)\/title","value":"rtcEngine:localVideoStats:sourceType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:localVideoStats:sourceType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:localVideoStats:sourceType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineMediaEngineDidLoaded(_:)\/title","value":"rtcEngineMediaEngineDidLoaded:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineMediaEngineDidLoaded(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineMediaEngineDidLoaded:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineConnectionDidInterrupted(_:)\/title","value":"rtcEngineConnectionDidInterrupted:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineConnectionDidInterrupted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineConnectionDidInterrupted:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:rtmpStreamingEventWithUrl:eventCode:)\/title","value":"rtcEngine:rtmpStreamingEventWithUrl:eventCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:rtmpStreamingEventWithUrl:eventCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:rtmpStreamingEventWithUrl:eventCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:firstLocalVideoFramePublishedWithElapsed:sourceType:)\/title","value":"rtcEngine:firstLocalVideoFramePublishedWithElapsed:sourceType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:firstLocalVideoFramePublishedWithElapsed:sourceType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:firstLocalVideoFramePublishedWithElapsed:sourceType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/title","value":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)\/title","value":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:reportRtcStats:)\/title","value":"rtcEngine:reportRtcStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:reportRtcStats:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:reportRtcStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineCameraDidReady(_:)\/title","value":"rtcEngineCameraDidReady:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngineCameraDidReady(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineCameraDidReady:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didClientRoleChangeFailed:currentRole:)\/title","value":"rtcEngine:didClientRoleChangeFailed:currentRole:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:didClientRoleChangeFailed:currentRole:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didClientRoleChangeFailed:currentRole:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/title","value":"AgoraBaseDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraBaseDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:uploadLogResultRequestId:success:reason:)\/title","value":"rtcEngine:uploadLogResultRequestId:success:reason:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseDelegate~1rtcEngine(_:uploadLogResultRequestId:success:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:uploadLogResultRequestId:success:reason:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}