{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideohwencoderaccelerating"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideohwencoderaccelerating"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The local video encoding acceleration type."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"title":"AgoraVideoHwEncoderAccelerating","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoHwEncoderAccelerating","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/hardware","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/software"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"abstract":[{"type":"text","text":"The local video encoding acceleration type."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.0"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/equatable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating/software":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating.software","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"software"}],"abstract":[{"type":"text","text":"0: Software encoding is applied without acceleration."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/software","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderSoftware"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/software"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating/hardware":{"role":"symbol","title":"AgoraVideoHwEncoderAccelerating.hardware","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardware"}],"abstract":[{"type":"text","text":"1: Hardware encoding is applied for acceleration."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/hardware","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoHwEncoderHardware"}],"url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/hardware"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoHwEncoderAccelerating/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideohwencoderaccelerating\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoHwEncoderAccelerating"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/hardware","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoHwEncoderAccelerating\/software"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/title","value":"AgoraVideoHwEncoderAccelerating"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderAccelerating"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1software\/title","value":"AgoraVideoHwEncoderSoftware"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1software\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderSoftware"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1hardware\/title","value":"AgoraVideoHwEncoderHardware"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoHwEncoderAccelerating~1hardware\/fragments","value":[{"kind":"identifier","text":"AgoraVideoHwEncoderHardware"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}