{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiomixingdualmonomode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiomixingdualmonomode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The channel mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}],"title":"AgoraAudioMixingDualMonoMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioMixingDualMonoMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/L","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/R","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/auto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/mix"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode":{"role":"symbol","title":"AgoraAudioMixingDualMonoMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}],"abstract":[{"type":"text","text":"The channel mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/L":{"role":"symbol","title":"AgoraAudioMixingDualMonoMode.L","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"L"}],"abstract":[{"type":"text","text":"1: Left channel mode. This mode replaces the audio of the right channel"},{"type":"text","text":" "},{"type":"text","text":"with the audio of the left channel, which means the user can only hear the"},{"type":"text","text":" "},{"type":"text","text":"audio of the left channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/L","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoL"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/l"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/auto":{"role":"symbol","title":"AgoraAudioMixingDualMonoMode.auto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"abstract":[{"type":"text","text":"0: Original mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/auto","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoAuto"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/auto"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/mix":{"role":"symbol","title":"AgoraAudioMixingDualMonoMode.mix","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mix"}],"abstract":[{"type":"text","text":"3: Mixed channel mode. This mode mixes the audio of the left channel and"},{"type":"text","text":" "},{"type":"text","text":"the right channel, which means the user can hear the audio of the left"},{"type":"text","text":" "},{"type":"text","text":"channel and the right channel at the same time."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/mix","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMix"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/mix"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/R":{"role":"symbol","title":"AgoraAudioMixingDualMonoMode.R","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"R"}],"abstract":[{"type":"text","text":"2: Right channel mode. This mode replaces the audio of the left channel"},{"type":"text","text":" "},{"type":"text","text":"with the audio of the right channel, which means the user can only hear the"},{"type":"text","text":" "},{"type":"text","text":"audio of the right channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/R","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoR"}],"url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/r"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/init(rawvalue:)"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioMixingDualMonoMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiomixingdualmonomode\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioMixingDualMonoMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/L","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/R","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/auto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioMixingDualMonoMode\/mix"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode\/title","value":"AgoraAudioMixingDualMonoMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1L\/title","value":"AgoraAudioMixingDualMonoL"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1L\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoL"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1auto\/title","value":"AgoraAudioMixingDualMonoAuto"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1auto\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoAuto"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1mix\/title","value":"AgoraAudioMixingDualMonoMix"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1mix\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoMix"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1R\/title","value":"AgoraAudioMixingDualMonoR"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioMixingDualMonoMode~1R\/fragments","value":[{"kind":"identifier","text":"AgoraAudioMixingDualMonoR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}