{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkQuality"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoranetworkquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoranetworkquality"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Network quality types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkQuality"}],"title":"AgoraNetworkQuality","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraNetworkQuality","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQuality"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/bad","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/detecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/down","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/excellent","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/good","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/poor","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/unknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/unsupported","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/vBad"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/detecting":{"role":"symbol","title":"AgoraNetworkQuality.detecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detecting"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/detecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityDetecting"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/detecting"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality":{"role":"symbol","title":"AgoraNetworkQuality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkQuality"}],"abstract":[{"type":"text","text":"Network quality types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQuality"}],"url":"\/documentation\/agorartckit\/agoranetworkquality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/good":{"role":"symbol","title":"AgoraNetworkQuality.good","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"good"}],"abstract":[{"type":"text","text":"2: The network quality is quite good, but the bitrate may be slightly lower"},{"type":"text","text":" "},{"type":"text","text":"than excellent."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/good","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityGood"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/good"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoranetworkquality\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/poor":{"role":"symbol","title":"AgoraNetworkQuality.poor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"poor"}],"abstract":[{"type":"text","text":"3: Users can feel the communication is slightly impaired."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/poor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityPoor"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/poor"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/vBad":{"role":"symbol","title":"AgoraNetworkQuality.vBad","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vBad"}],"abstract":[{"type":"text","text":"5: The quality is so bad that users can barely communicate."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/vBad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityVBad"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/vbad"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoranetworkquality\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoranetworkquality\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/down":{"role":"symbol","title":"AgoraNetworkQuality.down","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"down"}],"abstract":[{"type":"text","text":"6: The network is down and users cannot communicate at all."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/down","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityDown"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/down"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/unknown":{"role":"symbol","title":"AgoraNetworkQuality.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"0: The network quality is unknown."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityUnknown"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/unknown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/bad":{"role":"symbol","title":"AgoraNetworkQuality.bad","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bad"}],"abstract":[{"type":"text","text":"4: Users cannot communicate smoothly."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/bad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityBad"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/bad"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/excellent":{"role":"symbol","title":"AgoraNetworkQuality.excellent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"excellent"}],"abstract":[{"type":"text","text":"1: The network quality is excellent."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/excellent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityExcellent"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/excellent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/unsupported":{"role":"symbol","title":"AgoraNetworkQuality.unsupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupported"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/unsupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityUnsupported"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/unsupported"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraNetworkQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQuality"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraNetworkQuality"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/bad","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/detecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/down","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/excellent","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/good","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/poor","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/unknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/unsupported","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/vBad"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1detecting\/title","value":"AgoraNetworkQualityDetecting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1detecting\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityDetecting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality\/title","value":"AgoraNetworkQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1good\/title","value":"AgoraNetworkQualityGood"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1good\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityGood"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1poor\/title","value":"AgoraNetworkQualityPoor"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1poor\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityPoor"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1vBad\/title","value":"AgoraNetworkQualityVBad"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1vBad\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityVBad"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1down\/title","value":"AgoraNetworkQualityDown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1down\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityDown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1unknown\/title","value":"AgoraNetworkQualityUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1unknown\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1bad\/title","value":"AgoraNetworkQualityBad"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1bad\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityBad"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1excellent\/title","value":"AgoraNetworkQualityExcellent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1excellent\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityExcellent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1unsupported\/title","value":"AgoraNetworkQualityUnsupported"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1unsupported\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityUnsupported"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}