{"seeAlsoSections":[{"title":"Advanced Classes","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrame"}],"title":"AgoraVideoFrame","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraVideoFrame","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrame"}]},"abstract":[{"type":"text","text":"The external video frame."}],"sections":[],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropBottom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropLeft","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropRight","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropTop","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/dataBuf","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/format","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/image","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/rotation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/stride","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/strideInPixels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/textureBuf","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/time"]}],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoframe"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrame"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/height":{"role":"symbol","title":"height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/height","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"height"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/height"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/cropLeft":{"role":"symbol","title":"cropLeft","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Raw data related parameter. The number of pixels trimmed from the left. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropLeft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cropLeft"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/cropleft"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/textureBuf":{"role":"symbol","title":"textureBuf","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textureBuf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Buffer of iOS texture."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/textureBuf","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textureBuf"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/texturebuf"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/time":{"role":"symbol","title":"time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"}],"abstract":[{"type":"text","text":"Timestamp (ms) of the incoming video frame. An incorrect timestamp results in frame loss or unsynchronized audio and video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/time","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"time"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/time"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/strideInPixels":{"role":"symbol","title":"strideInPixels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strideInPixels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The line span of the frame, that is, the number of pixels between two adjacent lines of video frames.The unit of this parameter is pixels, not bytes.If the video is in Texture format, set this parameter to the width of Texture.If the video frame format is set to 12, do not use this field."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/strideInPixels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"strideInPixels"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/strideinpixels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/format":{"role":"symbol","title":"format","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The format of the incoming video frame. This parameter must be specified as one of the following values:1: I4202: BGRA3: NV214: RGBA5: IMC27: ARGB8: NV1212: iOS texture (CVPixelBufferRef)16: I422"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/format","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"format"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/format"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/cropRight":{"role":"symbol","title":"cropRight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Raw data related parameter. The number of pixels trimmed from the right. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropRight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cropRight"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/cropright"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset":{"role":"symbol","title":"AgoraAudioEffectPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"abstract":[{"type":"text","text":"Preset audio effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/cropTop":{"role":"symbol","title":"cropTop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropTop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Raw data related parameter. The number of pixels trimmed from the top. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropTop","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cropTop"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/croptop"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/image":{"role":"symbol","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/image"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame":{"role":"symbol","title":"AgoraVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrame"}],"abstract":[{"type":"text","text":"The external video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrame"}],"url":"\/documentation\/agorartckit\/agoravideoframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/rotation":{"role":"symbol","title":"rotation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Raw data related parameter. The clockwise rotation of the video frame. You can set the rotation angle as 0, 90, 180, or 270. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/rotation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rotation"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/rotation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/cropBottom":{"role":"symbol","title":"cropBottom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Raw data related parameter. The number of pixels trimmed from the bottom. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropBottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cropBottom"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/cropbottom"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/dataBuf":{"role":"symbol","title":"dataBuf","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataBuf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/dataBuf","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataBuf"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/databuf"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig":{"role":"symbol","title":"AgoraEncryptionConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionConfig"}],"abstract":[{"type":"text","text":"Built-in encryption configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionConfig"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame/stride":{"deprecated":true,"role":"symbol","title":"stride","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stride"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The external video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/stride","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stride"}],"url":"\/documentation\/agorartckit\/agoravideoframe\/stride"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats":{"role":"symbol","title":"AgoraRtcLocalAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"abstract":[{"type":"text","text":"Local audio statistics."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoFrame"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrame"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoFrame"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropBottom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropLeft","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropRight","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/cropTop","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/dataBuf","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/format","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/height","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/image","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/rotation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/stride","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/strideInPixels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/textureBuf","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame\/time"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Advanced Classes","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrame"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1height\/fragments","value":[{"kind":"identifier","text":"height"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropLeft\/title","value":"cropLeft"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropLeft\/fragments","value":[{"kind":"identifier","text":"cropLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1textureBuf\/title","value":"textureBuf"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1textureBuf\/fragments","value":[{"kind":"identifier","text":"textureBuf"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1time\/title","value":"time"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1time\/fragments","value":[{"kind":"identifier","text":"time"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1strideInPixels\/title","value":"strideInPixels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1strideInPixels\/fragments","value":[{"kind":"identifier","text":"strideInPixels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1format\/title","value":"format"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1format\/fragments","value":[{"kind":"identifier","text":"format"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropRight\/title","value":"cropRight"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropRight\/fragments","value":[{"kind":"identifier","text":"cropRight"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropTop\/title","value":"cropTop"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropTop\/fragments","value":[{"kind":"identifier","text":"cropTop"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/title","value":"AgoraVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1rotation\/title","value":"rotation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1rotation\/fragments","value":[{"kind":"identifier","text":"rotation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropBottom\/title","value":"cropBottom"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1cropBottom\/fragments","value":[{"kind":"identifier","text":"cropBottom"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1dataBuf\/title","value":"dataBuf"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1dataBuf\/fragments","value":[{"kind":"identifier","text":"dataBuf"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/title","value":"AgoraEncryptionConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1stride\/title","value":"stride"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame~1stride\/fragments","value":[{"kind":"identifier","text":"stride"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/title","value":"AgoraRtcLocalAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}