{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmMessageEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmmessageevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmmessageevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelTopic","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/message","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/publisher"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmMessageEvent"}],"title":"AgoraRtmMessageEvent","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRtmMessageEvent","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmMessageEvent"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageEvent/publisher":{"role":"symbol","title":"publisher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/publisher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publisher"}],"url":"\/documentation\/agorartckit\/agorartmmessageevent\/publisher"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageEvent/channelName":{"role":"symbol","title":"channelName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelName"}],"url":"\/documentation\/agorartckit\/agorartmmessageevent\/channelname"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageEvent":{"role":"symbol","title":"AgoraRtmMessageEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmMessageEvent"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmMessageEvent"}],"url":"\/documentation\/agorartckit\/agorartmmessageevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageEvent/channelType":{"role":"symbol","title":"channelType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmChannelType","preciseIdentifier":"c:@E@AgoraRtmChannelType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelType"}],"url":"\/documentation\/agorartckit\/agorartmmessageevent\/channeltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageEvent/channelTopic":{"role":"symbol","title":"channelTopic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelTopic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelTopic"}],"url":"\/documentation\/agorartckit\/agorartmmessageevent\/channeltopic"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmMessageEvent/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"message"}],"url":"\/documentation\/agorartckit\/agorartmmessageevent\/message"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmMessageEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmMessageEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtmMessageEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelTopic","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/channelType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/message","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmMessageEvent\/publisher"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmMessageEvent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1publisher\/title","value":"publisher"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1publisher\/fragments","value":[{"kind":"identifier","text":"publisher"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1channelName\/title","value":"channelName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1channelName\/fragments","value":[{"kind":"identifier","text":"channelName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent\/title","value":"AgoraRtmMessageEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent\/fragments","value":[{"kind":"identifier","text":"AgoraRtmMessageEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1channelType\/title","value":"channelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1channelType\/fragments","value":[{"kind":"identifier","text":"channelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1channelTopic\/title","value":"channelTopic"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1channelTopic\/fragments","value":[{"kind":"identifier","text":"channelTopic"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmMessageEvent~1message\/fragments","value":[{"kind":"identifier","text":"message"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}