{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An error code indicates that the SDK encountered an unrecoverable error that requires application intervention. For example, an error is returned when the camera fails to open, and the app needs to inform the user that the camera cannot be used."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"title":"AgoraErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraErrorCode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/abort","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admGeneralError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitLoopback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admJavaResource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admNoPlayoutDevice","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admNoRecordingDevice","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admPlayAbnormalFrequency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRecordAbnormalFrequency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRecordAudioFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRuntimePlayoutError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRuntimeRecordingError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartLoopback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStopPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStopRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/alreadyInUse","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bindSocket","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bitrateLimit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bufferTooSmall","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/canceled","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/clientIsBannedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionInterrupted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/decryptionFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/encryptedStreamNotAllowedPublish","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/initNetEngine","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidAppId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidArgument","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidChannelId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidState","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidUserAccount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidUserId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/joinChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/leaveChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/loadMediaEngine","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/moduleNotFound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/netDown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noBufs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noPermission","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noServerResources","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notInChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notInitialized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notReady","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notSupported","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/publishFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/publishStreamCDNError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/refused","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/resourceLimited","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/setClientRoleNotAuthorzed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/sizeTooLarge","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startCall","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startVideoRender","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/streamMessageTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/timedOut","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tooManyDataStreams","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tooOften","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderEncodeError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderInitError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderSetError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmUnknownError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vdmCameraNotAuthorized"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/startVideoRender":{"role":"symbol","title":"AgoraErrorCode.startVideoRender","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startVideoRender"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startVideoRender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeStartVideoRender"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/startvideorender"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/alreadyInUse":{"role":"symbol","title":"AgoraErrorCode.alreadyInUse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyInUse"}],"abstract":[{"type":"text","text":"19: Resources are already in use."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/alreadyInUse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAlreadyInUse"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/alreadyinuse"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/noPermission":{"role":"symbol","title":"AgoraErrorCode.noPermission","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPermission"}],"abstract":[{"type":"text","text":"9: Permission to access is not granted. Check whether your app has access to the audio and video device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noPermission","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNoPermission"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/nopermission"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/bindSocket":{"role":"symbol","title":"AgoraErrorCode.bindSocket","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindSocket"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bindSocket","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeBindSocket"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/bindsocket"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/tokenExpired":{"role":"symbol","title":"AgoraErrorCode.tokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenExpired"}],"abstract":[{"type":"text","text":"109: The current token has expired. Apply for a new token on the server and call renewToken.Deprecated:This enumerator is deprecated. Use AgoraConnectionChangedReasonTokenExpired(9) in the connectionChangedToState callback instead."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeTokenExpired"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/tokenexpired"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/notInitialized":{"role":"symbol","title":"AgoraErrorCode.notInitialized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInitialized"}],"abstract":[{"type":"text","text":"7: A method is called before the initialization of AgoraRtcEngineKit. Ensure that the AgoraRtcEngineKit object is initialized before using this method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notInitialized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNotInitialized"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/notinitialized"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/moduleNotFound":{"role":"symbol","title":"AgoraErrorCode.moduleNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleNotFound"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/moduleNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeModuleNotFound"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/modulenotfound"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admInitLoopback":{"role":"symbol","title":"AgoraErrorCode.admInitLoopback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admInitLoopback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitLoopback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmInitLoopback"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/adminitloopback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/startCall":{"role":"symbol","title":"AgoraErrorCode.startCall","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCall"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeStartCall"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/startcall"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraerrorcode\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/joinChannelRejected":{"role":"symbol","title":"AgoraErrorCode.joinChannelRejected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannelRejected"}],"abstract":[{"type":"text","text":"17: The request to join the channel is rejected. Possible reasons include the following:The user is already in the channel. Agora recommends that you use the connectionChangedToState callback to determine whether the user exists in the channel. Do not call this method to join the channel unless you receive the AgoraConnectionStateDisconnected(1) state.After calling startEchoTestWithConfig for the call test, the user tries to join the channel without calling stopEchoTest to end the current test. To join a channel, the call test must be ended by calling stopEchoTest."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/joinChannelRejected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeJoinChannelRejected"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/joinchannelrejected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/invalidChannelId":{"role":"symbol","title":"AgoraErrorCode.invalidChannelId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidChannelId"}],"abstract":[{"type":"text","text":"102: The specified channel name is invalid. A possible reason is that the parameter’s data type is incorrect. Rejoin the channel with a valid channel name."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidChannelId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInvalidChannelId"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/invalidchannelid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/invalidToken":{"role":"symbol","title":"AgoraErrorCode.invalidToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidToken"}],"abstract":[{"type":"text","text":"110: Invalid token. Typical reasons include the following:App Certificate is enabled in Agora Console, but the code still uses App ID for authentication. Once App Certificate is enabled for a project, you must use token-based authentication.The uid used to generate the token is not the same as the uid used to join the channel.Deprecated:This enumerator is deprecated. Use AgoraConnectionChangedReasonInvalidToken(8) in the connectionChangedToState callback instead."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInvalidToken"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/invalidtoken"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/vcmUnknownError":{"role":"symbol","title":"AgoraErrorCode.vcmUnknownError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vcmUnknownError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmUnknownError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeVcmUnknownError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/vcmunknownerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/encryptedStreamNotAllowedPublish":{"role":"symbol","title":"AgoraErrorCode.encryptedStreamNotAllowedPublish","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptedStreamNotAllowedPublish"}],"abstract":[{"type":"text","text":"130: The SDK does not support pushing encrypted streams to CDN."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/encryptedStreamNotAllowedPublish","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeEncryptedStreamNotAllowedPublish"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/encryptedstreamnotallowedpublish"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/invalidArgument":{"role":"symbol","title":"AgoraErrorCode.invalidArgument","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidArgument"}],"abstract":[{"type":"text","text":"2: An invalid parameter is used. For example, the specified channel name includes illegal characters. Reset the parameter."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidArgument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInvalidArgument"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/invalidargument"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/vdmCameraNotAuthorized":{"role":"symbol","title":"AgoraErrorCode.vdmCameraNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vdmCameraNotAuthorized"}],"abstract":[{"type":"text","text":"1501: Permission to access the camera is not granted. Check whether permission to access the camera permission is granted."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vdmCameraNotAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeVdmCameraNotAuthorized"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/vdmcameranotauthorized"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/notSupported":{"role":"symbol","title":"AgoraErrorCode.notSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"abstract":[{"type":"text","text":"4: The AgoraRtcEngineKit does not support the request. Possible reasons include the following:The built-in encryption mode is incorrect, or the SDK fails to load the external encryption library. Check the encryption mode setting, or reload the external encryption library."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNotSupported"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/notsupported"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admInitPlayout":{"role":"symbol","title":"AgoraErrorCode.admInitPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admInitPlayout"}],"abstract":[{"type":"text","text":"1008: An error occurs when initializing the playback device. Check whether the playback device is already in use by another app, or try rejoining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmInitPlayout"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/adminitplayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admRuntimeRecordingError":{"role":"symbol","title":"AgoraErrorCode.admRuntimeRecordingError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRuntimeRecordingError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRuntimeRecordingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmRuntimeRecordingError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admruntimerecordingerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admRecordAbnormalFrequency":{"role":"symbol","title":"AgoraErrorCode.admRecordAbnormalFrequency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRecordAbnormalFrequency"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRecordAbnormalFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmRecordAbnormalFrequency"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admrecordabnormalfrequency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/invalidAppId":{"role":"symbol","title":"AgoraErrorCode.invalidAppId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAppId"}],"abstract":[{"type":"text","text":"101: The specified App ID is invalid. Rejoin the channel with a valid App ID."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidAppId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInvalidAppId"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/invalidappid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/canceled":{"role":"symbol","title":"AgoraErrorCode.canceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/canceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeCanceled"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/canceled"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/abort":{"role":"symbol","title":"AgoraErrorCode.abort","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"abort"}],"abstract":[{"type":"text","text":"20: The request is abandoned by the SDK, possibly because the request has been sent too frequently."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/abort","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAbort"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/abort"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/notReady":{"role":"symbol","title":"AgoraErrorCode.notReady","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notReady"}],"abstract":[{"type":"text","text":"3: The SDK is not ready. Possible reasons include the following:The initialization of AgoraRtcEngineKit fails. Reinitialize the AgoraRtcEngineKit.No user has joined the channel when the method is called. Check the code logic.The user has not left the channel when the rate or complain method is called. Check the code logic.The audio module is disabled.The program is not complete."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notReady","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNotReady"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/notready"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/setClientRoleNotAuthorzed":{"role":"symbol","title":"AgoraErrorCode.setClientRoleNotAuthorzed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRoleNotAuthorzed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/setClientRoleNotAuthorzed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeSetClientRoleNotAuthorzed"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/setclientrolenotauthorzed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admRecordAudioFailed":{"role":"symbol","title":"AgoraErrorCode.admRecordAudioFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRecordAudioFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRecordAudioFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmRecordAudioFailed"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admrecordaudiofailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/invalidUserId":{"role":"symbol","title":"AgoraErrorCode.invalidUserId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUserId"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidUserId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInvalidUserId"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/invaliduserid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/resourceLimited":{"role":"symbol","title":"AgoraErrorCode.resourceLimited","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resourceLimited"}],"abstract":[{"type":"text","text":"22: The SDK fails to allocate resources because your app uses too many system resources or system resources are insufficient."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/resourceLimited","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeResourceLimited"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/resourcelimited"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/publishFailed":{"role":"symbol","title":"AgoraErrorCode.publishFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/publishFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodePublishFailed"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/publishfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/bufferTooSmall":{"role":"symbol","title":"AgoraErrorCode.bufferTooSmall","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferTooSmall"}],"abstract":[{"type":"text","text":"6: The buffer size is insufficient to store the returned data."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bufferTooSmall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeBufferTooSmall"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/buffertoosmall"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admStopPlayout":{"role":"symbol","title":"AgoraErrorCode.admStopPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStopPlayout"}],"abstract":[{"type":"text","text":"1010: An error occurs when stopping the playback device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStopPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmStopPlayout"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admstopplayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/vcmEncoderSetError":{"deprecated":true,"role":"symbol","title":"AgoraErrorCode.vcmEncoderSetError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vcmEncoderSetError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderSetError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeVcmEncoderSetError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/vcmencoderseterror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/clientIsBannedByServer":{"role":"symbol","title":"AgoraErrorCode.clientIsBannedByServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIsBannedByServer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/clientIsBannedByServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeClientIsBannedByServer"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/clientisbannedbyserver"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/notInChannel":{"role":"symbol","title":"AgoraErrorCode.notInChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notInChannel"}],"abstract":[{"type":"text","text":"113: The user is not in the channel when calling the sendStreamMessage method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notInChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNotInChannel"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/notinchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/invalidUserAccount":{"role":"symbol","title":"AgoraErrorCode.invalidUserAccount","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUserAccount"}],"abstract":[{"type":"text","text":"134: The user account is invalid, possibly because it contains invalid parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidUserAccount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInvalidUserAccount"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/invaliduseraccount"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/decryptionFailed":{"role":"symbol","title":"AgoraErrorCode.decryptionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptionFailed"}],"abstract":[{"type":"text","text":"120: Decryption fails. The user might have entered an incorrect password to join the channel. Check the entered password, or tell the user to try rejoining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/decryptionFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeDecryptionFailed"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/decryptionfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraerrorcode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/vcmEncoderEncodeError":{"role":"symbol","title":"AgoraErrorCode.vcmEncoderEncodeError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vcmEncoderEncodeError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderEncodeError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeVcmEncoderEncodeError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/vcmencoderencodeerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admStopRecording":{"role":"symbol","title":"AgoraErrorCode.admStopRecording","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStopRecording"}],"abstract":[{"type":"text","text":"1013: An error occurs when stopping the recording device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStopRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmStopRecording"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admstoprecording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/failed":{"role":"symbol","title":"AgoraErrorCode.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"1: General error with no classified reason. Try calling the method again."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeFailed"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/failed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/refused":{"role":"symbol","title":"AgoraErrorCode.refused","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"refused"}],"abstract":[{"type":"text","text":"5: The request is rejected. Possible reasons include the following:The AgoraRtcEngineKit initialization fails. Reinitialize the AgoraRtcEngineKit.The channel name is set as the empty string “” when joining the channel. Reset the channel name.When the joinChannelExByToken [1\/2] method is called to join multiple channels, the specified channel name is already in use. Reset the channel name."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/refused","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeRefused"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/refused"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admInitRecording":{"role":"symbol","title":"AgoraErrorCode.admInitRecording","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admInitRecording"}],"abstract":[{"type":"text","text":"1011: An error occurs when initializing the recording device. Check the recording device, or try rejoining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmInitRecording"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/adminitrecording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admStartPlayout":{"role":"symbol","title":"AgoraErrorCode.admStartPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStartPlayout"}],"abstract":[{"type":"text","text":"1009: An error occurs when starting the playback device. Check the playback device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartPlayout"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admstartplayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/streamMessageTimeout":{"role":"symbol","title":"AgoraErrorCode.streamMessageTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamMessageTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/streamMessageTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeStreamMessageTimeout"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/streammessagetimeout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/initNetEngine":{"role":"symbol","title":"AgoraErrorCode.initNetEngine","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initNetEngine"}],"abstract":[{"type":"text","text":"21: The AgoraRtcEngineKit fails to initialize and has crashed because of specific Windows firewall settings."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/initNetEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInitNetEngine"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/initnetengine"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admJavaResource":{"role":"symbol","title":"AgoraErrorCode.admJavaResource","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admJavaResource"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admJavaResource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmJavaResource"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admjavaresource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/leaveChannelRejected":{"role":"symbol","title":"AgoraErrorCode.leaveChannelRejected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannelRejected"}],"abstract":[{"type":"text","text":"18: Fails to leave the channel. Possible reasons include the following:The user has left the channel before calling the leaveChannel [2\/2] method. Stop calling this method to clear this error.The user calls the leaveChannel [2\/2] method to leave the channel before joining the channel. In this case, no extra operation is needed."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/leaveChannelRejected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeLeaveChannelRejected"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/leavechannelrejected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admStartRecording":{"role":"symbol","title":"AgoraErrorCode.admStartRecording","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStartRecording"}],"abstract":[{"type":"text","text":"1012: An error occurs when starting the recording device. Check the recording device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartRecording"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admstartrecording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admNoPlayoutDevice":{"role":"symbol","title":"AgoraErrorCode.admNoPlayoutDevice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admNoPlayoutDevice"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admNoPlayoutDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmNoPlayoutDevice"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admnoplayoutdevice"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/timedOut":{"role":"symbol","title":"AgoraErrorCode.timedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timedOut"}],"abstract":[{"type":"text","text":"10: A timeout occurs. Some API calls require the SDK to return the execution result. This error occurs if the SDK takes too long (more than 10 seconds) to return the result."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/timedOut","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeTimedOut"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/timedout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/connectionInterrupted":{"role":"symbol","title":"AgoraErrorCode.connectionInterrupted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionInterrupted"}],"abstract":[{"type":"text","text":"111: The network connection is interrupted. The SDK triggers this callback when it loses connection with the server for more than four seconds after the connection is established."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionInterrupted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeConnectionInterrupted"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/connectioninterrupted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admPlayAbnormalFrequency":{"role":"symbol","title":"AgoraErrorCode.admPlayAbnormalFrequency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admPlayAbnormalFrequency"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admPlayAbnormalFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmPlayAbnormalFrequency"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admplayabnormalfrequency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admStartLoopback":{"role":"symbol","title":"AgoraErrorCode.admStartLoopback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admStartLoopback"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartLoopback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartLoopback"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admstartloopback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/invalidState":{"role":"symbol","title":"AgoraErrorCode.invalidState","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidState"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeInvalidState"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/invalidstate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/connectionLost":{"role":"symbol","title":"AgoraErrorCode.connectionLost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionLost"}],"abstract":[{"type":"text","text":"112: The network connection is lost. Occurs when the SDK cannot reconnect to Agora’s edge server 10 seconds after its connection to the server is interrupted."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeConnectionLost"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/connectionlost"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admNoRecordingDevice":{"role":"symbol","title":"AgoraErrorCode.admNoRecordingDevice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admNoRecordingDevice"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admNoRecordingDevice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmNoRecordingDevice"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admnorecordingdevice"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraerrorcode\/equatable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admSampleRate":{"role":"symbol","title":"AgoraErrorCode.admSampleRate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admSampleRate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admSampleRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmSampleRate"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admsamplerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/noServerResources":{"role":"symbol","title":"AgoraErrorCode.noServerResources","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noServerResources"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noServerResources","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNoServerResources"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/noserverresources"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/netDown":{"role":"symbol","title":"AgoraErrorCode.netDown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"netDown"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/netDown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNetDown"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/netdown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/tooManyDataStreams":{"role":"symbol","title":"AgoraErrorCode.tooManyDataStreams","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooManyDataStreams"}],"abstract":[{"type":"text","text":"116: More than five data streams are created when calling the createDataStream [2\/2] method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tooManyDataStreams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeTooManyDataStreams"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/toomanydatastreams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/publishStreamCDNError":{"role":"symbol","title":"AgoraErrorCode.publishStreamCDNError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishStreamCDNError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/publishStreamCDNError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodePublishStreamCDNError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/publishstreamcdnerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode":{"role":"symbol","title":"AgoraErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"}],"abstract":[{"type":"text","text":"Error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCode"}],"url":"\/documentation\/agorartckit\/agoraerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/vcmEncoderInitError":{"role":"symbol","title":"AgoraErrorCode.vcmEncoderInitError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vcmEncoderInitError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderInitError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeVcmEncoderInitError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/vcmencoderiniterror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/tooOften":{"role":"symbol","title":"AgoraErrorCode.tooOften","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooOften"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tooOften","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeTooOften"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/toooften"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/sizeTooLarge":{"role":"symbol","title":"AgoraErrorCode.sizeTooLarge","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeTooLarge"}],"abstract":[{"type":"text","text":"114: The data size exceeds 1 KB when calling the sendStreamMessage method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/sizeTooLarge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeSizeTooLarge"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/sizetoolarge"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/bitrateLimit":{"role":"symbol","title":"AgoraErrorCode.bitrateLimit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrateLimit"}],"abstract":[{"type":"text","text":"115: The data bitrate exceeds 6 KB\/s when calling the sendStreamMessage method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bitrateLimit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeBitrateLimit"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/bitratelimit"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admGeneralError":{"role":"symbol","title":"AgoraErrorCode.admGeneralError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admGeneralError"}],"abstract":[{"type":"text","text":"1005: A general error occurs (no specified reason). Check whether the audio device is already in use by another app, or try rejoining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admGeneralError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmGeneralError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admgeneralerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/startCamera":{"role":"symbol","title":"AgoraErrorCode.startCamera","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCamera"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startCamera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeStartCamera"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/startcamera"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/loadMediaEngine":{"role":"symbol","title":"AgoraErrorCode.loadMediaEngine","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMediaEngine"}],"abstract":[{"type":"text","text":"1001: The SDK fails to load the media engine."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/loadMediaEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeLoadMediaEngine"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/loadmediaengine"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/noBufs":{"role":"symbol","title":"AgoraErrorCode.noBufs","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noBufs"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noBufs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNoBufs"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/nobufs"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/admRuntimePlayoutError":{"role":"symbol","title":"AgoraErrorCode.admRuntimePlayoutError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admRuntimePlayoutError"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRuntimePlayoutError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeAdmRuntimePlayoutError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/admruntimeplayouterror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraErrorCode/noError":{"role":"symbol","title":"AgoraErrorCode.noError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noError"}],"abstract":[{"type":"text","text":"0: No error."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraErrorCodeNoError"}],"url":"\/documentation\/agorartckit\/agoraerrorcode\/noerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/abort","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admGeneralError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitLoopback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admInitRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admJavaResource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admNoPlayoutDevice","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admNoRecordingDevice","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admPlayAbnormalFrequency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRecordAbnormalFrequency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRecordAudioFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRuntimePlayoutError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admRuntimeRecordingError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartLoopback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStartRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStopPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/admStopRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/alreadyInUse","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bindSocket","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bitrateLimit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/bufferTooSmall","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/canceled","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/clientIsBannedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionInterrupted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/connectionLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/decryptionFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/encryptedStreamNotAllowedPublish","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/initNetEngine","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidAppId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidArgument","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidChannelId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidState","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidUserAccount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/invalidUserId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/joinChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/leaveChannelRejected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/loadMediaEngine","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/moduleNotFound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/netDown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noBufs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noPermission","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/noServerResources","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notInChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notInitialized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notReady","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/notSupported","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/publishFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/publishStreamCDNError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/refused","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/resourceLimited","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/setClientRoleNotAuthorzed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/sizeTooLarge","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startCall","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/startVideoRender","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/streamMessageTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/timedOut","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tooManyDataStreams","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/tooOften","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderEncodeError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderInitError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmEncoderSetError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vcmUnknownError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraErrorCode\/vdmCameraNotAuthorized"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1startVideoRender\/title","value":"AgoraErrorCodeStartVideoRender"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1startVideoRender\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeStartVideoRender"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1alreadyInUse\/title","value":"AgoraErrorCodeAlreadyInUse"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1alreadyInUse\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAlreadyInUse"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noPermission\/title","value":"AgoraErrorCodeNoPermission"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noPermission\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNoPermission"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1bindSocket\/title","value":"AgoraErrorCodeBindSocket"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1bindSocket\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeBindSocket"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1tokenExpired\/title","value":"AgoraErrorCodeTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1tokenExpired\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notInitialized\/title","value":"AgoraErrorCodeNotInitialized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notInitialized\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNotInitialized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1moduleNotFound\/title","value":"AgoraErrorCodeModuleNotFound"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1moduleNotFound\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeModuleNotFound"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admInitLoopback\/title","value":"AgoraErrorCodeAdmInitLoopback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admInitLoopback\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmInitLoopback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1startCall\/title","value":"AgoraErrorCodeStartCall"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1startCall\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeStartCall"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1joinChannelRejected\/title","value":"AgoraErrorCodeJoinChannelRejected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1joinChannelRejected\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeJoinChannelRejected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidChannelId\/title","value":"AgoraErrorCodeInvalidChannelId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidChannelId\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInvalidChannelId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidToken\/title","value":"AgoraErrorCodeInvalidToken"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidToken\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInvalidToken"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmUnknownError\/title","value":"AgoraErrorCodeVcmUnknownError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmUnknownError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeVcmUnknownError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1encryptedStreamNotAllowedPublish\/title","value":"AgoraErrorCodeEncryptedStreamNotAllowedPublish"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1encryptedStreamNotAllowedPublish\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeEncryptedStreamNotAllowedPublish"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidArgument\/title","value":"AgoraErrorCodeInvalidArgument"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidArgument\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInvalidArgument"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vdmCameraNotAuthorized\/title","value":"AgoraErrorCodeVdmCameraNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vdmCameraNotAuthorized\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeVdmCameraNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notSupported\/title","value":"AgoraErrorCodeNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notSupported\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admInitPlayout\/title","value":"AgoraErrorCodeAdmInitPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admInitPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmInitPlayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRuntimeRecordingError\/title","value":"AgoraErrorCodeAdmRuntimeRecordingError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRuntimeRecordingError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmRuntimeRecordingError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRecordAbnormalFrequency\/title","value":"AgoraErrorCodeAdmRecordAbnormalFrequency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRecordAbnormalFrequency\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmRecordAbnormalFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidAppId\/title","value":"AgoraErrorCodeInvalidAppId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidAppId\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInvalidAppId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1canceled\/title","value":"AgoraErrorCodeCanceled"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1canceled\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeCanceled"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1abort\/title","value":"AgoraErrorCodeAbort"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1abort\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAbort"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notReady\/title","value":"AgoraErrorCodeNotReady"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notReady\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNotReady"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1setClientRoleNotAuthorzed\/title","value":"AgoraErrorCodeSetClientRoleNotAuthorzed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1setClientRoleNotAuthorzed\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeSetClientRoleNotAuthorzed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRecordAudioFailed\/title","value":"AgoraErrorCodeAdmRecordAudioFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRecordAudioFailed\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmRecordAudioFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidUserId\/title","value":"AgoraErrorCodeInvalidUserId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidUserId\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInvalidUserId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1resourceLimited\/title","value":"AgoraErrorCodeResourceLimited"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1resourceLimited\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeResourceLimited"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1publishFailed\/title","value":"AgoraErrorCodePublishFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1publishFailed\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodePublishFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1bufferTooSmall\/title","value":"AgoraErrorCodeBufferTooSmall"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1bufferTooSmall\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeBufferTooSmall"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStopPlayout\/title","value":"AgoraErrorCodeAdmStopPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStopPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmStopPlayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmEncoderSetError\/title","value":"AgoraErrorCodeVcmEncoderSetError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmEncoderSetError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeVcmEncoderSetError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1clientIsBannedByServer\/title","value":"AgoraErrorCodeClientIsBannedByServer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1clientIsBannedByServer\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeClientIsBannedByServer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notInChannel\/title","value":"AgoraErrorCodeNotInChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1notInChannel\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNotInChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidUserAccount\/title","value":"AgoraErrorCodeInvalidUserAccount"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidUserAccount\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInvalidUserAccount"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1decryptionFailed\/title","value":"AgoraErrorCodeDecryptionFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1decryptionFailed\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeDecryptionFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmEncoderEncodeError\/title","value":"AgoraErrorCodeVcmEncoderEncodeError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmEncoderEncodeError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeVcmEncoderEncodeError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStopRecording\/title","value":"AgoraErrorCodeAdmStopRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStopRecording\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmStopRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1failed\/title","value":"AgoraErrorCodeFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1refused\/title","value":"AgoraErrorCodeRefused"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1refused\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeRefused"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admInitRecording\/title","value":"AgoraErrorCodeAdmInitRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admInitRecording\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmInitRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartPlayout\/title","value":"AgoraErrorCodeAdmStartPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartPlayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1streamMessageTimeout\/title","value":"AgoraErrorCodeStreamMessageTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1streamMessageTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeStreamMessageTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1initNetEngine\/title","value":"AgoraErrorCodeInitNetEngine"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1initNetEngine\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInitNetEngine"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admJavaResource\/title","value":"AgoraErrorCodeAdmJavaResource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admJavaResource\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmJavaResource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1leaveChannelRejected\/title","value":"AgoraErrorCodeLeaveChannelRejected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1leaveChannelRejected\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeLeaveChannelRejected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartRecording\/title","value":"AgoraErrorCodeAdmStartRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartRecording\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admNoPlayoutDevice\/title","value":"AgoraErrorCodeAdmNoPlayoutDevice"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admNoPlayoutDevice\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmNoPlayoutDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1timedOut\/title","value":"AgoraErrorCodeTimedOut"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1timedOut\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeTimedOut"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1connectionInterrupted\/title","value":"AgoraErrorCodeConnectionInterrupted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1connectionInterrupted\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeConnectionInterrupted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admPlayAbnormalFrequency\/title","value":"AgoraErrorCodeAdmPlayAbnormalFrequency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admPlayAbnormalFrequency\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmPlayAbnormalFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartLoopback\/title","value":"AgoraErrorCodeAdmStartLoopback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admStartLoopback\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmStartLoopback"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidState\/title","value":"AgoraErrorCodeInvalidState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1invalidState\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeInvalidState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1connectionLost\/title","value":"AgoraErrorCodeConnectionLost"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1connectionLost\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeConnectionLost"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admNoRecordingDevice\/title","value":"AgoraErrorCodeAdmNoRecordingDevice"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admNoRecordingDevice\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmNoRecordingDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admSampleRate\/title","value":"AgoraErrorCodeAdmSampleRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admSampleRate\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmSampleRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noServerResources\/title","value":"AgoraErrorCodeNoServerResources"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noServerResources\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNoServerResources"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1netDown\/title","value":"AgoraErrorCodeNetDown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1netDown\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNetDown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1tooManyDataStreams\/title","value":"AgoraErrorCodeTooManyDataStreams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1tooManyDataStreams\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeTooManyDataStreams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1publishStreamCDNError\/title","value":"AgoraErrorCodePublishStreamCDNError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1publishStreamCDNError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodePublishStreamCDNError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/title","value":"AgoraErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmEncoderInitError\/title","value":"AgoraErrorCodeVcmEncoderInitError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1vcmEncoderInitError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeVcmEncoderInitError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1tooOften\/title","value":"AgoraErrorCodeTooOften"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1tooOften\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeTooOften"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1sizeTooLarge\/title","value":"AgoraErrorCodeSizeTooLarge"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1sizeTooLarge\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeSizeTooLarge"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1bitrateLimit\/title","value":"AgoraErrorCodeBitrateLimit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1bitrateLimit\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeBitrateLimit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admGeneralError\/title","value":"AgoraErrorCodeAdmGeneralError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admGeneralError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmGeneralError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1startCamera\/title","value":"AgoraErrorCodeStartCamera"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1startCamera\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeStartCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1loadMediaEngine\/title","value":"AgoraErrorCodeLoadMediaEngine"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1loadMediaEngine\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeLoadMediaEngine"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noBufs\/title","value":"AgoraErrorCodeNoBufs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noBufs\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNoBufs"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRuntimePlayoutError\/title","value":"AgoraErrorCodeAdmRuntimePlayoutError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1admRuntimePlayoutError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeAdmRuntimePlayoutError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noError\/title","value":"AgoraErrorCodeNoError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraErrorCode~1noError\/fragments","value":[{"kind":"identifier","text":"AgoraErrorCodeNoError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}