{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiospectrumdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiospectrumdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The audio spectrum observer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}],"title":"AgoraAudioSpectrumDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraAudioSpectrumDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate\/onLocalAudioSpectrum(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate\/onRemoteAudioSpectrum(_:)"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumDelegate/onRemoteAudioSpectrum(_:)":{"role":"symbol","title":"onRemoteAudioSpectrum(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRemoteAudioSpectrum"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraAudioSpectrumInfo","preciseIdentifier":"c:objc(cs)AgoraAudioSpectrumInfo"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the remote audio spectrum."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling registerAudioSpectrumDelegate to implement the"},{"type":"text","text":" "},{"type":"text","text":"onRemoteAudioSpectrum callback in the AgoraAudioSpectrumDelegate and calling"},{"type":"text","text":" "},{"type":"text","text":"enableAudioSpectrumMonitor to enable audio spectrum monitoring, the SDK will"},{"type":"text","text":" "},{"type":"text","text":"trigger the callback as the time interval you set to report the received"},{"type":"text","text":" "},{"type":"text","text":"remote audio data spectrum."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate\/onRemoteAudioSpectrum(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRemoteAudioSpectrum:"}],"url":"\/documentation\/agorartckit\/agoraaudiospectrumdelegate\/onremoteaudiospectrum(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumDelegate":{"role":"symbol","title":"AgoraAudioSpectrumDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}],"abstract":[{"type":"text","text":"The audio spectrum observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudiospectrumdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumDelegate/onLocalAudioSpectrum(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onLocalAudioSpectrum:"}],"role":"symbol","title":"onLocalAudioSpectrum(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLocalAudioSpectrum"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate\/onLocalAudioSpectrum(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudiospectrumdelegate\/onlocalaudiospectrum(_:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioSpectrumDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate\/onLocalAudioSpectrum(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumDelegate\/onRemoteAudioSpectrum(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate~1onRemoteAudioSpectrum(_:)\/title","value":"onRemoteAudioSpectrum:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate~1onRemoteAudioSpectrum(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRemoteAudioSpectrum:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate\/title","value":"AgoraAudioSpectrumDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSpectrumDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate~1onLocalAudioSpectrum(_:)\/title","value":"onLocalAudioSpectrum:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumDelegate~1onLocalAudioSpectrum(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLocalAudioSpectrum:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}