{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediarecorderconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configurations for the local audio and video recording."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"title":"AgoraMediaRecorderConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraMediaRecorderConfiguration","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/containerFormat","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/maxDurationMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/recorderInfoUpdateInterval","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/storagePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/streamType"]}],"references":{"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/containerFormat":{"role":"symbol","title":"containerFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderContainerFormat","preciseIdentifier":"c:@E@AgoraMediaRecorderContainerFormat"}],"abstract":[{"type":"text","text":"The format of the recording file. See AgoraMediaRecorderContainerFormat ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/containerFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"containerFormat"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/containerformat"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/storagePath":{"role":"symbol","title":"storagePath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"storagePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The absolute path (including the filename extensions) of the recording file."},{"type":"text","text":" "},{"type":"text","text":"For example:Windows:"},{"type":"text","text":" "},{"type":"text","text":"C:\\Users<user_name>\\AppData\\Local\\Agora<process_name>\\example.mp4iOS: \/App"},{"type":"text","text":" "},{"type":"text","text":"Sandbox\/Library\/Caches\/example.mp4macOS: \/Library\/Logs\/example.mp4Android:"},{"type":"text","text":" "},{"type":"text","text":"\/storage\/emulated\/0\/Android\/data\/"},{"type":"text","text":"\/files\/example.mp4Ensure that"},{"type":"text","text":" "},{"type":"text","text":"the directory for the log files exists and is writable."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/storagePath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storagePath"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/storagepath"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/streamType":{"role":"symbol","title":"streamType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMediaRecorderStreamType","preciseIdentifier":"c:@E@AgoraMediaRecorderStreamType"}],"abstract":[{"type":"text","text":"The recording content. See AgoraMediaRecorderStreamType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/streamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"streamType"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/streamtype"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/recorderInfoUpdateInterval":{"role":"symbol","title":"recorderInfoUpdateInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recorderInfoUpdateInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The interval (ms) of updating the recording information. The value range is"},{"type":"text","text":" "},{"type":"text","text":"[1000,10000]. Based on the value you set in this parameter, the SDK triggers"},{"type":"text","text":" "},{"type":"text","text":"the informationDidUpdated callback to report the updated recording"},{"type":"text","text":" "},{"type":"text","text":"information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/recorderInfoUpdateInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recorderInfoUpdateInterval"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/recorderinfoupdateinterval"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration/maxDurationMs":{"role":"symbol","title":"maxDurationMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDurationMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The maximum recording duration, in milliseconds. The default value is 120000."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/maxDurationMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxDurationMs"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration\/maxdurationms"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaRecorderConfiguration":{"role":"symbol","title":"AgoraMediaRecorderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"abstract":[{"type":"text","text":"Configurations for the local audio and video recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}],"url":"\/documentation\/agorartckit\/agoramediarecorderconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaRecorderConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/containerFormat","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/maxDurationMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/recorderInfoUpdateInterval","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/storagePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaRecorderConfiguration\/streamType"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1containerFormat\/title","value":"containerFormat"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1containerFormat\/fragments","value":[{"kind":"identifier","text":"containerFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1storagePath\/title","value":"storagePath"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1storagePath\/fragments","value":[{"kind":"identifier","text":"storagePath"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1streamType\/title","value":"streamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1streamType\/fragments","value":[{"kind":"identifier","text":"streamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1recorderInfoUpdateInterval\/title","value":"recorderInfoUpdateInterval"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1recorderInfoUpdateInterval\/fragments","value":[{"kind":"identifier","text":"recorderInfoUpdateInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1maxDurationMs\/title","value":"maxDurationMs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration~1maxDurationMs\/fragments","value":[{"kind":"identifier","text":"maxDurationMs"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/title","value":"AgoraMediaRecorderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaRecorderConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraMediaRecorderConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}