{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEchoTestConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraechotestconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraechotestconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The configuration of the audio and video call loop test."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEchoTestConfiguration"}],"title":"AgoraEchoTestConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraEchoTestConfiguration","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEchoTestConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/channelId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/enableAudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/enableVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/intervalInSeconds","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/token","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/view"]}],"references":{"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration/intervalInSeconds":{"role":"symbol","title":"intervalInSeconds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intervalInSeconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The time interval (s) between when you start the call and when the recording plays back. The value range is [2, 10], and the default value is 2."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/intervalInSeconds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intervalInSeconds"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration\/intervalinseconds"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration/channelId":{"role":"symbol","title":"channelId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The channel name that identifies each audio and video call loop. To ensure proper loop test functionality, the channel name passed in to identify each loop test cannot be the same when users of the same project (App ID) perform audio and video call loop tests on different devices."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/channelId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelId"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration\/channelid"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration":{"role":"symbol","title":"AgoraEchoTestConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEchoTestConfiguration"}],"abstract":[{"type":"text","text":"The configuration of the audio and video call loop test."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEchoTestConfiguration"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration/view":{"role":"symbol","title":"view","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The view used to render the local user’s video. This parameter is only applicable to scenarios testing video devices, that is, when enableVideo is YES."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/view","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"view"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration\/view"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration/enableAudio":{"role":"symbol","title":"enableAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable the audio device for the loop test:YES: (Default) Enable the audio device. To test the audio device, set this parameter as YES.NO: Disable the audio device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/enableAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableAudio"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration\/enableaudio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration/enableVideo":{"role":"symbol","title":"enableVideo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable the video device for the loop test:YES: (Default) Enable the video device. To test the video device, set this parameter as YES.NO: Disable the video device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/enableVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableVideo"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration\/enablevideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEchoTestConfiguration/token":{"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The token used to secure the audio and video call loop test. If you do not enable App Certificate in Agora Console, you do not need to pass a value in this parameter; if you have enabled App Certificate in Agora Console, you must pass a token in this parameter; the uid used when you generate the token must be 0xFFFFFFFF, and the channel name used must be the channel name that identifies each audio and video call loop tested. For server-side token generation, see ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/token","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"token"}],"url":"\/documentation\/agorartckit\/agoraechotestconfiguration\/token"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEchoTestConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEchoTestConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEchoTestConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/channelId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/enableAudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/enableVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/intervalInSeconds","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/token","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEchoTestConfiguration\/view"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEchoTestConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1intervalInSeconds\/title","value":"intervalInSeconds"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1intervalInSeconds\/fragments","value":[{"kind":"identifier","text":"intervalInSeconds"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1channelId\/title","value":"channelId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1channelId\/fragments","value":[{"kind":"identifier","text":"channelId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration\/title","value":"AgoraEchoTestConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraEchoTestConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1view\/title","value":"view"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1view\/fragments","value":[{"kind":"identifier","text":"view"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1enableAudio\/title","value":"enableAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1enableAudio\/fragments","value":[{"kind":"identifier","text":"enableAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1enableVideo\/title","value":"enableVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1enableVideo\/fragments","value":[{"kind":"identifier","text":"enableVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEchoTestConfiguration~1token\/fragments","value":[{"kind":"identifier","text":"token"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}