{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoremotestate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoremotestate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The state of the remote video stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteState"}],"title":"AgoraVideoRemoteState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoRemoteState","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteState"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/decoding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/frozen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/starting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/stopped"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoremotestate\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideoremotestate\/init(rawvalue:)"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState":{"role":"symbol","title":"AgoraVideoRemoteState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteState"}],"abstract":[{"type":"text","text":"The state of the remote video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteState"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/frozen":{"role":"symbol","title":"AgoraVideoRemoteState.frozen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"frozen"}],"abstract":[{"type":"text","text":"3: The remote video is frozen. The SDK reports this state in the case of AgoraVideoRemoteReasonCongestion or AgoraVideoRemoteReasonAudioFallback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/frozen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateFrozen"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate\/frozen"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/failed":{"role":"symbol","title":"AgoraVideoRemoteState.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"4: The remote video fails to start. The SDK reports this state in the case of AgoraVideoRemoteReasonInternal."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateFailed"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate\/failed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoremotestate\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/starting":{"role":"symbol","title":"AgoraVideoRemoteState.starting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"starting"}],"abstract":[{"type":"text","text":"1: The first remote video packet is received."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/starting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateStarting"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate\/starting"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/stopped":{"role":"symbol","title":"AgoraVideoRemoteState.stopped","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"abstract":[{"type":"text","text":"0: The remote video is in the initial state. The SDK reports this state in the case of AgoraVideoRemoteReasonLocalMuted, AgoraVideoRemoteReasonRemoteMuted, or AgoraVideoRemoteReasonRemoteOffline."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/stopped","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateStopped"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate\/stopped"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRemoteState/decoding":{"role":"symbol","title":"AgoraVideoRemoteState.decoding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoding"}],"abstract":[{"type":"text","text":"2: The remote video stream is decoded and plays normally. The SDK reports this state in the case of AgoraVideoRemoteReasonRecovery, AgoraVideoRemoteReasonLocalUnmuted, AgoraVideoRemoteReasonRemoteUnmuted, or AgoraVideoRemoteReasonAudioFallbackRecovery."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/decoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRemoteStateDecoding"}],"url":"\/documentation\/agorartckit\/agoravideoremotestate\/decoding"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoRemoteState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoRemoteState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/decoding","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/failed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/frozen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/starting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRemoteState\/stopped"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRemoteState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState\/title","value":"AgoraVideoRemoteState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1frozen\/title","value":"AgoraVideoRemoteStateFrozen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1frozen\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateFrozen"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1failed\/title","value":"AgoraVideoRemoteStateFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1failed\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1starting\/title","value":"AgoraVideoRemoteStateStarting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1starting\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateStarting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1stopped\/title","value":"AgoraVideoRemoteStateStopped"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1stopped\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateStopped"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1decoding\/title","value":"AgoraVideoRemoteStateDecoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRemoteState~1decoding\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRemoteStateDecoding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}