{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamPublishState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreampublishstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreampublishstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The publishing state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamPublishState"}],"title":"AgoraStreamPublishState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraStreamPublishState","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishState"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/noPublished","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/published","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/publishing"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/publishing":{"role":"symbol","title":"AgoraStreamPublishState.publishing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishing"}],"abstract":[{"type":"text","text":"2: Publishing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/publishing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishStatePublishing"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate\/publishing"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/idle":{"role":"symbol","title":"AgoraStreamPublishState.idle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"abstract":[{"type":"text","text":"0: The initial publishing state after joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/idle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishStateIdle"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate\/idle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorastreampublishstate\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/noPublished":{"role":"symbol","title":"AgoraStreamPublishState.noPublished","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPublished"}],"abstract":[{"type":"text","text":"1: Fails to publish the local stream. Possible reasons:The local user calls"},{"type":"text","text":" "},{"type":"text","text":"muteLocalAudioStream (YES) or muteLocalVideoStream (YES) to stop sending"},{"type":"text","text":" "},{"type":"text","text":"local media streams.The local user calls disableAudio or disableVideo to"},{"type":"text","text":" "},{"type":"text","text":"disable the local audio or video module.The local user calls"},{"type":"text","text":" "},{"type":"text","text":"enableLocalAudio (NO) or enableLocalVideo (NO) to disable the local audio"},{"type":"text","text":" "},{"type":"text","text":"or video capture.The role of the local user is audience."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/noPublished","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishStateNoPublished"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate\/nopublished"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorastreampublishstate\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState":{"role":"symbol","title":"AgoraStreamPublishState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamPublishState"}],"abstract":[{"type":"text","text":"The publishing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishState"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorastreampublishstate\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/published":{"role":"symbol","title":"AgoraStreamPublishState.published","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"published"}],"abstract":[{"type":"text","text":"3: Publishes successfully."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/published","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishStatePublished"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate\/published"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamPublishState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraStreamPublishState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/noPublished","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/published","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/publishing"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamPublishState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1publishing\/title","value":"AgoraStreamPublishStatePublishing"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1publishing\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishStatePublishing"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1idle\/title","value":"AgoraStreamPublishStateIdle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1idle\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishStateIdle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1noPublished\/title","value":"AgoraStreamPublishStateNoPublished"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1noPublished\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishStateNoPublished"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState\/title","value":"AgoraStreamPublishState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1published\/title","value":"AgoraStreamPublishStatePublished"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1published\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishStatePublished"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}