{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveTranscoding"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralivetranscoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralivetranscoding"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Transcoding configurations for Media Push."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveTranscoding"}],"title":"AgoraLiveTranscoding","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLiveTranscoding","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLiveTranscoding"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioCodecProfile","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/backgroundColor","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/backgroundImageArray","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/lowLatency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/size","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/transcodingExtraInfo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/transcodingUsers","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecProfile","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoFramerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoGop","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/watermarkArray"]},{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/add(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/getAdvancedFeatures()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/removeUser(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/setAdvancedFeatures(_:opened:)"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/default()"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/backgroundImageArray":{"role":"symbol","title":"backgroundImageArray","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImageArray"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraImage","preciseIdentifier":"c:objc(cs)AgoraImage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array of background images on the live video. See AgoraImage . You can use"},{"type":"text","text":" "},{"type":"text","text":"backgroundImageArray to add one or more background images. The image format"},{"type":"text","text":" "},{"type":"text","text":"needs to be PNG. The total number of watermarks and background images on a"},{"type":"text","text":" "},{"type":"text","text":"live video must be greater than or equal to 0 and less than or equal to 10."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/backgroundImageArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundImageArray"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/backgroundimagearray"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/setAdvancedFeatures(_:opened:)":{"role":"symbol","title":"setAdvancedFeatures(_:opened:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAdvancedFeatures"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"opened"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets whether to enable the advanced features of streaming with transcoding."},{"type":"text","text":" "},{"type":"text","text":"If you want to enable the advanced features of streaming with transcoding,"},{"type":"text","text":" "},{"type":"text","text":"contact ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/setAdvancedFeatures(_:opened:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAdvancedFeatures:opened:"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/setadvancedfeatures(_:opened:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/lowLatency":{"role":"symbol","title":"lowLatency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowLatency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"DeprecatedThis member is deprecated.Latency mode:YES: Low latency with"},{"type":"text","text":" "},{"type":"text","text":"unassured quality.NO: (Default) High latency with assured quality."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/lowLatency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lowLatency"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/lowlatency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/videoFramerate":{"role":"symbol","title":"videoFramerate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFramerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Frame rate (fps) of the output video stream set for Media Push. The default"},{"type":"text","text":" "},{"type":"text","text":"value is 15. The value range is (0,30].The Agora server adjusts any value"},{"type":"text","text":" "},{"type":"text","text":"over 30 to 30."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoFramerate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoFramerate"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/videoframerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/videoCodecType":{"role":"symbol","title":"videoCodecType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoCodecTypeForStream","preciseIdentifier":"c:@E@AgoraVideoCodecTypeForStream"}],"abstract":[{"type":"text","text":"Video codec profile types for Media Push. See AgoraVideoCodecTypeForStream ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoCodecType"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/videocodectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/removeUser(_:)":{"role":"symbol","title":"removeUser(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Removes a user from video mixing during the CDN live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/removeUser(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeUser:"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/removeuser(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/videoCodecProfile":{"role":"symbol","title":"videoCodecProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodecProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoCodecProfileType","preciseIdentifier":"c:@E@AgoraVideoCodecProfileType"}],"abstract":[{"type":"text","text":"Video codec profile type for Media Push. Set it as 66, 77, or 100 (default)."},{"type":"text","text":" "},{"type":"text","text":"See AgoraVideoCodecProfileType for details.If you set this parameter to any"},{"type":"text","text":" "},{"type":"text","text":"other value, Agora adjusts it to the default value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoCodecProfile"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/videocodecprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/audioChannels":{"role":"symbol","title":"audioChannels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of audio channels for Media Push. Agora recommends choosing 1"},{"type":"text","text":" "},{"type":"text","text":"(mono), or 2 (stereo) audio channels. Special players are required if you"},{"type":"text","text":" "},{"type":"text","text":"choose 3, 4, or 5.1: (Default) Mono2: Stereo.3: Three audio channels.4: Four"},{"type":"text","text":" "},{"type":"text","text":"audio channels.5: Five audio channels."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioChannels"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/audiochannels"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/transcodingExtraInfo":{"role":"symbol","title":"transcodingExtraInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transcodingExtraInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Reserved property. Extra user-defined information to send SEI for the"},{"type":"text","text":" "},{"type":"text","text":"H.264\/H.265 video stream to the CDN live client. Maximum length: 4096 bytes."},{"type":"text","text":" "},{"type":"text","text":"For more information on SEI, see SEI-related questions."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/transcodingExtraInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transcodingExtraInfo"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/transcodingextrainfo"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The background color in for Media Push.The color of the custom background"},{"type":"text","text":" "},{"type":"text","text":"image. The format is a hexadecimal integer defined by RGB, without the #"},{"type":"text","text":" "},{"type":"text","text":"sign, such as 0xFFB6C1 for light pink. The default value is"},{"type":"text","text":" "},{"type":"text","text":"0x000000(black).COLOR_CLASS is a general name for the type:iOS: UIColormacOS:"},{"type":"text","text":" "},{"type":"text","text":"NSColor"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/backgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/backgroundcolor"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/transcodingUsers":{"role":"symbol","title":"transcodingUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transcodingUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraLiveTranscodingUser","preciseIdentifier":"c:objc(cs)AgoraLiveTranscodingUser"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Manages the user layout configuration in the Media Push. Agora supports a"},{"type":"text","text":" "},{"type":"text","text":"maximum of 17 transcoding users in a Media Push channel. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLiveTranscodingUser ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/transcodingUsers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transcodingUsers"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/transcodingusers"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/audioSampleRate":{"role":"symbol","title":"audioSampleRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSampleRateType","preciseIdentifier":"c:@E@AgoraAudioSampleRateType"}],"abstract":[{"type":"text","text":"The audio sampling rate (Hz) of the output media stream. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioSampleRateType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioSampleRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioSampleRate"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/audiosamplerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/add(_:)":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraLiveTranscodingUser","preciseIdentifier":"c:objc(cs)AgoraLiveTranscodingUser"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Adds a user for video mixing during the CDN live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/add(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addUser:"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/add(_:)"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding":{"role":"symbol","title":"AgoraLiveTranscoding","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveTranscoding"}],"abstract":[{"type":"text","text":"Transcoding configurations for Media Push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveTranscoding"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size of the video (width and height in pixels).When pushing video streams"},{"type":"text","text":" "},{"type":"text","text":"to the CDN, note the following:The value range of the width is [64,1920]. If"},{"type":"text","text":" "},{"type":"text","text":"the value is less than 64, Agora server automatically adjusts it to 64; if"},{"type":"text","text":" "},{"type":"text","text":"the value is greater than 1920, Agora server automatically adjusts it to"},{"type":"text","text":" "},{"type":"text","text":"1920.The value range of the height is [64,1080]. If the value is less than"},{"type":"text","text":" "},{"type":"text","text":"64, Agora server automatically adjusts it to 64; if the value is greater than"},{"type":"text","text":" "},{"type":"text","text":"1080, Agora server automatically adjusts it to 1080.When pushing audio"},{"type":"text","text":" "},{"type":"text","text":"streams to the CDN, set the width and height as 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/size"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/watermarkArray":{"role":"symbol","title":"watermarkArray","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"watermarkArray"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraImage","preciseIdentifier":"c:objc(cs)AgoraImage"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The array of watermarks on the live video. See AgoraImage . You can add one"},{"type":"text","text":" "},{"type":"text","text":"or more watermarks using watermarkArray. The image format needs to be PNG."},{"type":"text","text":" "},{"type":"text","text":"The total number of watermarks and background images on a live video must be"},{"type":"text","text":" "},{"type":"text","text":"greater than or equal to 0 and less than or equal to 10."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/watermarkArray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"watermarkArray"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/watermarkarray"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/getAdvancedFeatures()":{"role":"symbol","title":"getAdvancedFeatures()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAdvancedFeatures"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"AgoraLiveStreamAdvancedFeature","preciseIdentifier":"c:objc(cs)AgoraLiveStreamAdvancedFeature"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Gets the status of the advanced features of streaming with transcoding."},{"type":"text","text":" "},{"type":"text","text":"If you want to enable the advanced features of streaming with transcoding,"},{"type":"text","text":" "},{"type":"text","text":"contact ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/getAdvancedFeatures()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getAdvancedFeatures"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/getadvancedfeatures()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/audioCodecProfile":{"role":"symbol","title":"audioCodecProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioCodecProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioCodecProfileType","preciseIdentifier":"c:@E@AgoraAudioCodecProfileType"}],"abstract":[{"type":"text","text":"Audio codec profile type for Media Push. See AgoraAudioCodecProfileType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioCodecProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioCodecProfile"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/audiocodecprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/videoGop":{"role":"symbol","title":"videoGop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoGop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"GOP (Group of Pictures) in fps of the video frames for Media Push. The"},{"type":"text","text":" "},{"type":"text","text":"default value is 30."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoGop","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoGop"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/videogop"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/audioBitrate":{"role":"symbol","title":"audioBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Bitrate (Kbps) of the audio output stream for Media Push. The default value"},{"type":"text","text":" "},{"type":"text","text":"is 48, and the highest value is 128."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioBitrate"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/audiobitrate"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/default()":{"role":"symbol","title":"default()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraLiveTranscoding","preciseIdentifier":"c:objc(cs)AgoraLiveTranscoding"}],"abstract":[{"type":"text","text":"Creates a default transcoding object."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/default()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultTranscoding"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/default()"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveTranscoding/videoBitrate":{"role":"symbol","title":"videoBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Bitrate of the output video stream for Media Push in Kbps. The default value"},{"type":"text","text":" "},{"type":"text","text":"is 400 Kbps.Set this member according to the Video profile table. If you set"},{"type":"text","text":" "},{"type":"text","text":"a bitrate beyond the proper range, the SDK automatically adapts it to a value"},{"type":"text","text":" "},{"type":"text","text":"within the range."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoBitrate"}],"url":"\/documentation\/agorartckit\/agoralivetranscoding\/videobitrate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLiveTranscoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLiveTranscoding"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLiveTranscoding"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioCodecProfile","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/audioSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/backgroundColor","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/backgroundImageArray","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/lowLatency","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/size","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/transcodingExtraInfo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/transcodingUsers","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecProfile","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoCodecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoFramerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/videoGop","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/watermarkArray"]},{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/add(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/getAdvancedFeatures()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/removeUser(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/setAdvancedFeatures(_:opened:)"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveTranscoding\/default()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveTranscoding"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1backgroundImageArray\/title","value":"backgroundImageArray"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1backgroundImageArray\/fragments","value":[{"kind":"identifier","text":"backgroundImageArray"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1setAdvancedFeatures(_:opened:)\/title","value":"setAdvancedFeatures:opened:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1setAdvancedFeatures(_:opened:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAdvancedFeatures:opened:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1lowLatency\/title","value":"lowLatency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1lowLatency\/fragments","value":[{"kind":"identifier","text":"lowLatency"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoFramerate\/title","value":"videoFramerate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoFramerate\/fragments","value":[{"kind":"identifier","text":"videoFramerate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoCodecType\/title","value":"videoCodecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoCodecType\/fragments","value":[{"kind":"identifier","text":"videoCodecType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1removeUser(_:)\/title","value":"removeUser:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1removeUser(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoCodecProfile\/title","value":"videoCodecProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoCodecProfile\/fragments","value":[{"kind":"identifier","text":"videoCodecProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioChannels\/title","value":"audioChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioChannels\/fragments","value":[{"kind":"identifier","text":"audioChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1transcodingExtraInfo\/title","value":"transcodingExtraInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1transcodingExtraInfo\/fragments","value":[{"kind":"identifier","text":"transcodingExtraInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1transcodingUsers\/title","value":"transcodingUsers"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1transcodingUsers\/fragments","value":[{"kind":"identifier","text":"transcodingUsers"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioSampleRate\/title","value":"audioSampleRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioSampleRate\/fragments","value":[{"kind":"identifier","text":"audioSampleRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1add(_:)\/title","value":"addUser:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/title","value":"AgoraLiveTranscoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding\/fragments","value":[{"kind":"identifier","text":"AgoraLiveTranscoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1watermarkArray\/title","value":"watermarkArray"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1watermarkArray\/fragments","value":[{"kind":"identifier","text":"watermarkArray"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1getAdvancedFeatures()\/title","value":"getAdvancedFeatures"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1getAdvancedFeatures()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getAdvancedFeatures"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioCodecProfile\/title","value":"audioCodecProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioCodecProfile\/fragments","value":[{"kind":"identifier","text":"audioCodecProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoGop\/title","value":"videoGop"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoGop\/fragments","value":[{"kind":"identifier","text":"videoGop"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioBitrate\/title","value":"audioBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1audioBitrate\/fragments","value":[{"kind":"identifier","text":"audioBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1default()\/title","value":"defaultTranscoding"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1default()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultTranscoding"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoBitrate\/title","value":"videoBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveTranscoding~1videoBitrate\/fragments","value":[{"kind":"identifier","text":"videoBitrate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}