{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaDeviceType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediadevicetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediadevicetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioApplicationPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioUnknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/videoCapture","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/videoRender"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaDeviceType"}],"title":"AgoraMediaDeviceType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraMediaDeviceType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediadevicetype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediadevicetype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoramediadevicetype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioVirtualRecording":{"role":"symbol","title":"AgoraMediaDeviceType.audioVirtualRecording","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualRecording"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualRecording"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualrecording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioRecording":{"role":"symbol","title":"AgoraMediaDeviceType.audioRecording","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecording"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioRecording"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audiorecording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioUnknown":{"role":"symbol","title":"AgoraMediaDeviceType.audioUnknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioUnknown"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioUnknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioUnknown"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audiounknown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioPlayout":{"role":"symbol","title":"AgoraMediaDeviceType.audioPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioPlayout"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audioplayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioVirtualPlayout":{"role":"symbol","title":"AgoraMediaDeviceType.audioVirtualPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioVirtualPlayout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualPlayout"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audiovirtualplayout"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/videoCapture":{"role":"symbol","title":"AgoraMediaDeviceType.videoCapture","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCapture"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/videoCapture","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeVideoCapture"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/videocapture"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType":{"role":"symbol","title":"AgoraMediaDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaDeviceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceType"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/videoRender":{"role":"symbol","title":"AgoraMediaDeviceType.videoRender","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRender"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/videoRender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeVideoRender"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/videorender"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaDeviceType/audioApplicationPlayout":{"role":"symbol","title":"AgoraMediaDeviceType.audioApplicationPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioApplicationPlayout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioApplicationPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioApplicationPlayout"}],"url":"\/documentation\/agorartckit\/agoramediadevicetype\/audioapplicationplayout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaDeviceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaDeviceType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioApplicationPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioUnknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/audioVirtualRecording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/videoCapture","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaDeviceType\/videoRender"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaDeviceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualRecording\/title","value":"AgoraMediaDeviceTypeAudioVirtualRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualRecording\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioRecording\/title","value":"AgoraMediaDeviceTypeAudioRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioRecording\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioUnknown\/title","value":"AgoraMediaDeviceTypeAudioUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioUnknown\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioPlayout\/title","value":"AgoraMediaDeviceTypeAudioPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioPlayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualPlayout\/title","value":"AgoraMediaDeviceTypeAudioVirtualPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioVirtualPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioVirtualPlayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1videoCapture\/title","value":"AgoraMediaDeviceTypeVideoCapture"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1videoCapture\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeVideoCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType\/title","value":"AgoraMediaDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1videoRender\/title","value":"AgoraMediaDeviceTypeVideoRender"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1videoRender\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeVideoRender"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioApplicationPlayout\/title","value":"AgoraMediaDeviceTypeAudioApplicationPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaDeviceType~1audioApplicationPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraMediaDeviceTypeAudioApplicationPlayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}