{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreenvideoparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreenvideoparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The video configuration for the shared screen stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"title":"AgoraScreenVideoParameters","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraScreenVideoParameters","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/bitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/contentHint","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/dimensions","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/frameRate"]}],"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters/dimensions":{"role":"symbol","title":"dimensions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimensions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The video encoding dimension. The default value is 1280 × 720."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/dimensions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dimensions"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters\/dimensions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters/frameRate":{"role":"symbol","title":"frameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoFrameRate","preciseIdentifier":"c:@E@AgoraVideoFrameRate"}],"abstract":[{"type":"text","text":"The video encoding frame rate (fps). The default value is 15."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/frameRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frameRate"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters\/framerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters/contentHint":{"role":"symbol","title":"contentHint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoContentHint","preciseIdentifier":"c:@E@AgoraVideoContentHint"}],"abstract":[{"type":"text","text":"The content hint for screen sharing. See AgoraVideoContentHint ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/contentHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentHint"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters\/contenthint"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters":{"role":"symbol","title":"AgoraScreenVideoParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"abstract":[{"type":"text","text":"The video configuration for the shared screen stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenVideoParameters/bitrate":{"role":"symbol","title":"bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The video encoding bitrate (Kbps)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/bitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitrate"}],"url":"\/documentation\/agorartckit\/agorascreenvideoparameters\/bitrate"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraScreenVideoParameters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/bitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/contentHint","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/dimensions","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenVideoParameters\/frameRate"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenVideoParameters"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1dimensions\/title","value":"dimensions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1dimensions\/fragments","value":[{"kind":"identifier","text":"dimensions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1frameRate\/title","value":"frameRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1frameRate\/fragments","value":[{"kind":"identifier","text":"frameRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1contentHint\/title","value":"contentHint"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1contentHint\/fragments","value":[{"kind":"identifier","text":"contentHint"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters\/title","value":"AgoraScreenVideoParameters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters\/fragments","value":[{"kind":"identifier","text":"AgoraScreenVideoParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1bitrate\/title","value":"bitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenVideoParameters~1bitrate\/fragments","value":[{"kind":"identifier","text":"bitrate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}