{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracapturebrightnessleveltype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracapturebrightnessleveltype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The brightness level of the video image captured by the local camera."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"title":"AgoraCaptureBrightnessLevelType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraCaptureBrightnessLevelType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/bright","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/dark","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/normal"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/equatable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/normal":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType.normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"abstract":[{"type":"text","text":"0: The brightness level of the video image is normal."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/normal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelNormal"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/normal"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/bright":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType.bright","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bright"}],"abstract":[{"type":"text","text":"1: The brightness level of the video image is too bright."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/bright","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelBright"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/bright"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"abstract":[{"type":"text","text":"The brightness level of the video image captured by the local camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/dark":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType.dark","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dark"}],"abstract":[{"type":"text","text":"2: The brightness level of the video image is too dark."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/dark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelDark"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/dark"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCaptureBrightnessLevelType/invalid":{"role":"symbol","title":"AgoraCaptureBrightnessLevelType.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"-1: The SDK does not detect the brightness level of the video image. Wait a few seconds to get the brightness level from captureBrightnessLevel in the next callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelInvalid"}],"url":"\/documentation\/agorartckit\/agoracapturebrightnessleveltype\/invalid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCaptureBrightnessLevelType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/bright","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/dark","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCaptureBrightnessLevelType\/normal"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1normal\/title","value":"AgoraCaptureBrightnessLevelNormal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1normal\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelNormal"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1bright\/title","value":"AgoraCaptureBrightnessLevelBright"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1bright\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelBright"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/title","value":"AgoraCaptureBrightnessLevelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1dark\/title","value":"AgoraCaptureBrightnessLevelDark"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1dark\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelDark"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1invalid\/title","value":"AgoraCaptureBrightnessLevelInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCaptureBrightnessLevelType~1invalid\/fragments","value":[{"kind":"identifier","text":"AgoraCaptureBrightnessLevelInvalid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}