{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraProxyType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraproxytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraproxytype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/httpProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/httpsProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/localProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/noneProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyAutoFallbackType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/udpProxyType"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraProxyType"}],"title":"AgoraProxyType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraProxyType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraProxyType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/tcpProxyAutoFallbackType":{"role":"symbol","title":"AgoraProxyType.tcpProxyAutoFallbackType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpProxyAutoFallbackType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyAutoFallbackType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraTcpProxyAutoFallbackType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/tcpproxyautofallbacktype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraproxytype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/localProxyType":{"role":"symbol","title":"AgoraProxyType.localProxyType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/localProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/localproxytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType":{"role":"symbol","title":"AgoraProxyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraproxytype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/httpProxyType":{"role":"symbol","title":"AgoraProxyType.httpProxyType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/httpProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraHttpProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/httpproxytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/udpProxyType":{"role":"symbol","title":"AgoraProxyType.udpProxyType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"udpProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/udpProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUdpProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/udpproxytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraproxytype\/init(rawvalue:)"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/noneProxyType":{"role":"symbol","title":"AgoraProxyType.noneProxyType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noneProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/noneProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNoneProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/noneproxytype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/httpsProxyType":{"role":"symbol","title":"AgoraProxyType.httpsProxyType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpsProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/httpsProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraHttpsProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/httpsproxytype"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraProxyType/tcpProxyType":{"role":"symbol","title":"AgoraProxyType.tcpProxyType","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tcpProxyType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraTcpProxyType"}],"url":"\/documentation\/agorartckit\/agoraproxytype\/tcpproxytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraProxyType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraProxyType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraProxyType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/httpProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/httpsProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/localProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/noneProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyAutoFallbackType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/tcpProxyType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraProxyType\/udpProxyType"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraProxyType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1tcpProxyAutoFallbackType\/title","value":"AgoraTcpProxyAutoFallbackType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1tcpProxyAutoFallbackType\/fragments","value":[{"kind":"identifier","text":"AgoraTcpProxyAutoFallbackType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1localProxyType\/title","value":"AgoraLocalProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1localProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraLocalProxyType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType\/title","value":"AgoraProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraProxyType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1httpProxyType\/title","value":"AgoraHttpProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1httpProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraHttpProxyType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1udpProxyType\/title","value":"AgoraUdpProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1udpProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraUdpProxyType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1noneProxyType\/title","value":"AgoraNoneProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1noneProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraNoneProxyType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1httpsProxyType\/title","value":"AgoraHttpsProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1httpsProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraHttpsProxyType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1tcpProxyType\/title","value":"AgoraTcpProxyType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraProxyType~1tcpProxyType\/fragments","value":[{"kind":"identifier","text":"AgoraTcpProxyType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}