{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The media setting options for the host."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"title":"AgoraDirectCdnStreamingMediaOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraDirectCdnStreamingMediaOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/customVideoTrackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCameraTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMediaPlayerAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMediaPlayerId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMicrophoneTrack"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/publishCameraTrack":{"role":"symbol","title":"publishCameraTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCameraTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets whether to publish the video captured by the camera:YES: Publish the video captured by the camera.NO: (Default) Do not publish the video captured by the camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCameraTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCameraTrack"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishcameratrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/publishMicrophoneTrack":{"role":"symbol","title":"publishMicrophoneTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishMicrophoneTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets whether to publish the audio captured by the microphone:YES: Publish the audio captured by the microphone.NO: (Default) Do not publish the audio captured by the microphone."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMicrophoneTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishMicrophoneTrack"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishmicrophonetrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/publishCustomVideoTrack":{"role":"symbol","title":"publishCustomVideoTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets whether to publish the captured video from a custom source:YES: Publish the captured video from a custom source.NO: (Default) Do not publish the captured video from the custom source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCustomVideoTrack"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishcustomvideotrack"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/publishMediaPlayerId":{"role":"symbol","title":"publishMediaPlayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishMediaPlayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMediaPlayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishMediaPlayerId"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishmediaplayerid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions":{"role":"symbol","title":"AgoraDirectCdnStreamingMediaOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"abstract":[{"type":"text","text":"The media setting options for the host."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/publishCustomAudioTrack":{"role":"symbol","title":"publishCustomAudioTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets whether to publish the captured audio from a custom source:YES: Publish the captured audio from a custom source.NO: (Default) Do not publish the captured audio from the custom source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCustomAudioTrack"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishcustomaudiotrack"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/customVideoTrackId":{"role":"symbol","title":"customVideoTrackId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customVideoTrackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The video track ID returned by calling the createCustomVideoTrack method. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/customVideoTrackId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customVideoTrackId"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/customvideotrackid"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingMediaOptions/publishMediaPlayerAudioTrack":{"role":"symbol","title":"publishMediaPlayerAudioTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishMediaPlayerAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMediaPlayerAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishMediaPlayerAudioTrack"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingmediaoptions\/publishmediaplayeraudiotrack"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraDirectCdnStreamingMediaOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/customVideoTrackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCameraTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishCustomVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMediaPlayerAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMediaPlayerId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingMediaOptions\/publishMicrophoneTrack"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCameraTrack\/title","value":"publishCameraTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCameraTrack\/fragments","value":[{"kind":"identifier","text":"publishCameraTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishMicrophoneTrack\/title","value":"publishMicrophoneTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishMicrophoneTrack\/fragments","value":[{"kind":"identifier","text":"publishMicrophoneTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCustomVideoTrack\/title","value":"publishCustomVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCustomVideoTrack\/fragments","value":[{"kind":"identifier","text":"publishCustomVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishMediaPlayerId\/title","value":"publishMediaPlayerId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishMediaPlayerId\/fragments","value":[{"kind":"identifier","text":"publishMediaPlayerId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/title","value":"AgoraDirectCdnStreamingMediaOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingMediaOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCustomAudioTrack\/title","value":"publishCustomAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishCustomAudioTrack\/fragments","value":[{"kind":"identifier","text":"publishCustomAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1customVideoTrackId\/title","value":"customVideoTrackId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1customVideoTrackId\/fragments","value":[{"kind":"identifier","text":"customVideoTrackId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishMediaPlayerAudioTrack\/title","value":"publishMediaPlayerAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingMediaOptions~1publishMediaPlayerAudioTrack\/fragments","value":[{"kind":"identifier","text":"publishMediaPlayerAudioTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}