{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The midrange frequency for audio equalization."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"title":"AgoraAudioEqualizationBandFrequency","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioEqualizationBandFrequency","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band125","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band16K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band1K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band250","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band2K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band31","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band4K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band500","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band62","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band8K"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band125":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band125","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band125"}],"abstract":[{"type":"text","text":"2: 125 Hz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band125","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand125"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band125"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band62":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band62","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band62"}],"abstract":[{"type":"text","text":"1: 62 Hz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band62","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand62"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band62"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band500":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band500","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band500"}],"abstract":[{"type":"text","text":"4: 500 Hz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band500","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand500"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band500"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band8K":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band8K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band8K"}],"abstract":[{"type":"text","text":"8: 8 kHz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band8K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand8K"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band8k"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/init(rawvalue:)"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band31":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band31","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band31"}],"abstract":[{"type":"text","text":"0: 31 Hz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band31","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand31"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band31"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band250":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band250","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band250"}],"abstract":[{"type":"text","text":"3: 250 Hz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band250","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand250"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band250"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band1K":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band1K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band1K"}],"abstract":[{"type":"text","text":"5: 1 kHz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band1K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand1K"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band1k"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"abstract":[{"type":"text","text":"The midrange frequency for audio equalization."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band16K":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band16K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band16K"}],"abstract":[{"type":"text","text":"9: 16 kHz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band16K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand16K"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band16k"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band4K":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band4K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band4K"}],"abstract":[{"type":"text","text":"7: 4 kHz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band4K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand4K"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band4k"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEqualizationBandFrequency/band2K":{"role":"symbol","title":"AgoraAudioEqualizationBandFrequency.band2K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"band2K"}],"abstract":[{"type":"text","text":"6: 2 kHz"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band2K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEqualizationBand2K"}],"url":"\/documentation\/agorartckit\/agoraaudioequalizationbandfrequency\/band2k"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEqualizationBandFrequency"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band125","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band16K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band1K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band250","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band2K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band31","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band4K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band500","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band62","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEqualizationBandFrequency\/band8K"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band125\/title","value":"AgoraAudioEqualizationBand125"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band125\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand125"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band62\/title","value":"AgoraAudioEqualizationBand62"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band62\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand62"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band500\/title","value":"AgoraAudioEqualizationBand500"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band500\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand500"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band8K\/title","value":"AgoraAudioEqualizationBand8K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band8K\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand8K"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band31\/title","value":"AgoraAudioEqualizationBand31"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band31\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand31"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band250\/title","value":"AgoraAudioEqualizationBand250"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band250\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand250"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band1K\/title","value":"AgoraAudioEqualizationBand1K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band1K\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand1K"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency\/title","value":"AgoraAudioEqualizationBandFrequency"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBandFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band16K\/title","value":"AgoraAudioEqualizationBand16K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band16K\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand16K"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band4K\/title","value":"AgoraAudioEqualizationBand4K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band4K\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand4K"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band2K\/title","value":"AgoraAudioEqualizationBand2K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEqualizationBandFrequency~1band2K\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEqualizationBand2K"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}