{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaSourceType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediasourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediasourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Media source type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaSourceType"}],"title":"AgoraMediaSourceType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraMediaSourceType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/audioPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/customVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/mediaPlayer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/primaryCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/primaryScreen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/recording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/remoteVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImageGif","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImageJpeg","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImagePng","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/secondaryCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/secondaryScreen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/transcodedVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/mediaPlayer":{"role":"symbol","title":"AgoraMediaSourceType.mediaPlayer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaPlayer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/mediaPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeMediaPlayer"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/mediaplayer"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/primaryCamera":{"role":"symbol","title":"AgoraMediaSourceType.primaryCamera","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryCamera"}],"abstract":[{"type":"text","text":"2: The primary camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/primaryCamera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypePrimaryCamera"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/primarycamera"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediasourcetype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/primaryScreen":{"role":"symbol","title":"AgoraMediaSourceType.primaryScreen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryScreen"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/primaryScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypePrimaryScreen"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/primaryscreen"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediasourcetype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/remoteVideo":{"role":"symbol","title":"AgoraMediaSourceType.remoteVideo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteVideo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/remoteVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeRemoteVideo"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/remotevideo"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/transcodedVideo":{"role":"symbol","title":"AgoraMediaSourceType.transcodedVideo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transcodedVideo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/transcodedVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeTranscodedVideo"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/transcodedvideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/rtcImageJpeg":{"role":"symbol","title":"AgoraMediaSourceType.rtcImageJpeg","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcImageJpeg"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImageJpeg","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeRtcImageJpeg"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/rtcimagejpeg"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType":{"role":"symbol","title":"AgoraMediaSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaSourceType"}],"abstract":[{"type":"text","text":"Media source type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceType"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/unknown":{"role":"symbol","title":"AgoraMediaSourceType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"100: Unknown media source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeUnknown"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/unknown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/recording":{"role":"symbol","title":"AgoraMediaSourceType.recording","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recording"}],"abstract":[{"type":"text","text":"1: Audio capturing device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/recording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeRecording"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/recording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/rtcImageGif":{"role":"symbol","title":"AgoraMediaSourceType.rtcImageGif","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcImageGif"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImageGif","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeRtcImageGif"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/rtcimagegif"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/audioPlayout":{"role":"symbol","title":"AgoraMediaSourceType.audioPlayout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayout"}],"abstract":[{"type":"text","text":"0: Audio playback device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/audioPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeAudioPlayout"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/audioplayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/secondaryCamera":{"role":"symbol","title":"AgoraMediaSourceType.secondaryCamera","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryCamera"}],"abstract":[{"type":"text","text":"3: The secondary camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/secondaryCamera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeSecondaryCamera"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/secondarycamera"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/secondaryScreen":{"role":"symbol","title":"AgoraMediaSourceType.secondaryScreen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryScreen"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/secondaryScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeSecondaryScreen"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/secondaryscreen"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/customVideo":{"role":"symbol","title":"AgoraMediaSourceType.customVideo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customVideo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/customVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeCustomVideo"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/customvideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoramediasourcetype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaSourceType/rtcImagePng":{"role":"symbol","title":"AgoraMediaSourceType.rtcImagePng","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcImagePng"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImagePng","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaSourceTypeRtcImagePng"}],"url":"\/documentation\/agorartckit\/agoramediasourcetype\/rtcimagepng"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaSourceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaSourceType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/audioPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/customVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/mediaPlayer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/primaryCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/primaryScreen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/recording","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/remoteVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImageGif","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImageJpeg","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/rtcImagePng","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/secondaryCamera","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/secondaryScreen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/transcodedVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaSourceType\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaSourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1mediaPlayer\/title","value":"AgoraMediaSourceTypeMediaPlayer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1mediaPlayer\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeMediaPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1primaryCamera\/title","value":"AgoraMediaSourceTypePrimaryCamera"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1primaryCamera\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypePrimaryCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1primaryScreen\/title","value":"AgoraMediaSourceTypePrimaryScreen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1primaryScreen\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypePrimaryScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1remoteVideo\/title","value":"AgoraMediaSourceTypeRemoteVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1remoteVideo\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeRemoteVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1transcodedVideo\/title","value":"AgoraMediaSourceTypeTranscodedVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1transcodedVideo\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeTranscodedVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1rtcImageJpeg\/title","value":"AgoraMediaSourceTypeRtcImageJpeg"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1rtcImageJpeg\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeRtcImageJpeg"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType\/title","value":"AgoraMediaSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1unknown\/title","value":"AgoraMediaSourceTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1unknown\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1recording\/title","value":"AgoraMediaSourceTypeRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1recording\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1rtcImageGif\/title","value":"AgoraMediaSourceTypeRtcImageGif"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1rtcImageGif\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeRtcImageGif"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1audioPlayout\/title","value":"AgoraMediaSourceTypeAudioPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1audioPlayout\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeAudioPlayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1secondaryCamera\/title","value":"AgoraMediaSourceTypeSecondaryCamera"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1secondaryCamera\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeSecondaryCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1secondaryScreen\/title","value":"AgoraMediaSourceTypeSecondaryScreen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1secondaryScreen\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeSecondaryScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1customVideo\/title","value":"AgoraMediaSourceTypeCustomVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1customVideo\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeCustomVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1rtcImagePng\/title","value":"AgoraMediaSourceTypeRtcImagePng"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaSourceType~1rtcImagePng\/fragments","value":[{"kind":"identifier","text":"AgoraMediaSourceTypeRtcImagePng"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}