{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralighteningcontrastlevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralighteningcontrastlevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The contrast level."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"title":"AgoraLighteningContrastLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraLighteningContrastLevel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/high","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/normal"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel/high":{"role":"symbol","title":"AgoraLighteningContrastLevel.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[{"type":"text","text":"2: High contrast level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastHigh"}],"url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel\/high"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel\/init(rawvalue:)"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel/low":{"role":"symbol","title":"AgoraLighteningContrastLevel.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[{"type":"text","text":"0: Low contrast level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastLow"}],"url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel\/low"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel":{"role":"symbol","title":"AgoraLighteningContrastLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"abstract":[{"type":"text","text":"The contrast level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}],"url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel/normal":{"role":"symbol","title":"AgoraLighteningContrastLevel.normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"abstract":[{"type":"text","text":"1: (Default) Normal contrast level."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/normal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLighteningContrastNormal"}],"url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel\/normal"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel\/rawrepresentable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLighteningContrastLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralighteningcontrastlevel\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLighteningContrastLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/high","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLighteningContrastLevel\/normal"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLighteningContrastLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1high\/title","value":"AgoraLighteningContrastHigh"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1high\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1low\/title","value":"AgoraLighteningContrastLow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1low\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastLow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel\/title","value":"AgoraLighteningContrastLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1normal\/title","value":"AgoraLighteningContrastNormal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLighteningContrastLevel~1normal\/fragments","value":[{"kind":"identifier","text":"AgoraLighteningContrastNormal"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}