{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaMetadataDataSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediametadatadatasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediametadatadatasource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"AgoraMediaMetadataDataSource protocol."},{"type":"text","text":" "},{"type":"text","text":"Implement all the callbacks in this class in the critical thread. We"},{"type":"text","text":" "},{"type":"text","text":"recommend avoiding any time-consuming operation in the critical thread."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}],"title":"AgoraMediaMetadataDataSource","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraMediaMetadataDataSource","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/metadataMaxSize()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/readyToSendMetadata(atTimestamp:sourceType:)"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaMetadataDataSource/readyToSendMetadata(atTimestamp:sourceType:)":{"navigatorTitle":[{"kind":"identifier","text":"readyToSendMetadataAtTimestamp:sourceType:"}],"role":"symbol","title":"readyToSendMetadata(atTimestamp:sourceType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToSendMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Occurs when the SDK is ready to send metadata."},{"type":"text","text":" "},{"type":"text","text":"This callback is triggered when the SDK is ready to send metadata.Ensure that"},{"type":"text","text":" "},{"type":"text","text":"the size of the metadata does not exceed the value set in the metadataMaxSize"},{"type":"text","text":" "},{"type":"text","text":"callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/readyToSendMetadata(atTimestamp:sourceType:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramediametadatadatasource\/readytosendmetadata(attimestamp:sourcetype:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaMetadataDataSource":{"role":"symbol","title":"AgoraMediaMetadataDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}],"abstract":[{"type":"text","text":"AgoraMediaMetadataDataSource protocol."},{"type":"text","text":" "},{"type":"text","text":"Implement all the callbacks in this class in the critical thread. We"},{"type":"text","text":" "},{"type":"text","text":"recommend avoiding any time-consuming operation in the critical thread."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}],"url":"\/documentation\/agorartckit\/agoramediametadatadatasource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaMetadataDataSource/metadataMaxSize()":{"navigatorTitle":[{"kind":"identifier","text":"metadataMaxSize"}],"role":"symbol","title":"metadataMaxSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadataMaxSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/metadataMaxSize()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramediametadatadatasource\/metadatamaxsize()"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaMetadataDataSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/metadataMaxSize()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaMetadataDataSource\/readyToSendMetadata(atTimestamp:sourceType:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaMetadataDataSource"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource~1readyToSendMetadata(atTimestamp:sourceType:)\/title","value":"readyToSendMetadataAtTimestamp:sourceType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource~1readyToSendMetadata(atTimestamp:sourceType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readyToSendMetadataAtTimestamp:sourceType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource\/title","value":"AgoraMediaMetadataDataSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource\/fragments","value":[{"kind":"identifier","text":"AgoraMediaMetadataDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource~1metadataMaxSize()\/title","value":"metadataMaxSize"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaMetadataDataSource~1metadataMaxSize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"metadataMaxSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}