{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onLyricResult(_:lyricUrl:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onMusicChartsResult(_:result:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onMusicCollectionResult(_:result:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}],"title":"AgoraMusicContentCenterEventDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraMusicContentCenterEventDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterEventDelegate/onMusicCollectionResult(_:result:errorCode:)":{"navigatorTitle":[{"kind":"identifier","text":"onMusicCollectionResult:result:errorCode:"}],"role":"symbol","title":"onMusicCollectionResult(_:result:errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMusicCollectionResult"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicCollection","preciseIdentifier":"c:objc(cs)AgoraMusicCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onMusicCollectionResult(_:result:errorCode:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate\/onmusiccollectionresult(_:result:errorcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterEventDelegate/onLyricResult(_:lyricUrl:errorCode:)":{"navigatorTitle":[{"kind":"identifier","text":"onLyricResult:lyricUrl:errorCode:"}],"role":"symbol","title":"onLyricResult(_:lyricUrl:errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLyricResult"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lyricUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onLyricResult(_:lyricUrl:errorCode:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate\/onlyricresult(_:lyricurl:errorcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterEventDelegate":{"role":"symbol","title":"AgoraMusicContentCenterEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterEventDelegate/onMusicChartsResult(_:result:errorCode:)":{"navigatorTitle":[{"kind":"identifier","text":"onMusicChartsResult:result:errorCode:"}],"role":"symbol","title":"onMusicChartsResult(_:result:errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMusicChartsResult"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraMusicChartInfo","preciseIdentifier":"c:objc(cs)AgoraMusicChartInfo"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onMusicChartsResult(_:result:errorCode:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate\/onmusicchartsresult(_:result:errorcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenterEventDelegate/onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)":{"navigatorTitle":[{"kind":"identifier","text":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"}],"role":"symbol","title":"onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPreLoadEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"percent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lyricUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterPreloadStatus","preciseIdentifier":"c:@E@AgoraMusicContentCenterPreloadStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterStatusCode","preciseIdentifier":"c:@E@AgoraMusicContentCenterStatusCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramusiccontentcentereventdelegate\/onpreloadevent(_:percent:lyricurl:status:errorcode:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicContentCenterEventDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onLyricResult(_:lyricUrl:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onMusicChartsResult(_:result:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onMusicCollectionResult(_:result:errorCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenterEventDelegate\/onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onMusicCollectionResult(_:result:errorCode:)\/title","value":"onMusicCollectionResult:result:errorCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onMusicCollectionResult(_:result:errorCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMusicCollectionResult:result:errorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onLyricResult(_:lyricUrl:errorCode:)\/title","value":"onLyricResult:lyricUrl:errorCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onLyricResult(_:lyricUrl:errorCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLyricResult:lyricUrl:errorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate\/title","value":"AgoraMusicContentCenterEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenterEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onMusicChartsResult(_:result:errorCode:)\/title","value":"onMusicChartsResult:result:errorCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onMusicChartsResult(_:result:errorCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMusicChartsResult:result:errorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)\/title","value":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenterEventDelegate~1onPreLoadEvent(_:percent:lyricUrl:status:errorCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPreLoadEvent:percent:lyricUrl:status:errorCode:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}