{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencryptionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencryptionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The built-in encryption mode."},{"type":"text","text":" "},{"type":"text","text":"Agora recommends using AgoraEncryptionModeAES128GCM2 or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncryptionModeAES256GCM2 encrypted mode. These two modes support the use"},{"type":"text","text":" "},{"type":"text","text":"of salt for higher security."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"}],"title":"AgoraEncryptionMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraEncryptionMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128ECB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128GCM","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128GCM2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128XTS","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256GCM","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256GCM2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256XTS","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/SM4128ECB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/end"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES128GCM2":{"role":"symbol","title":"AgoraEncryptionMode.AES128GCM2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES128GCM2"}],"abstract":[{"type":"text","text":"7: (Default) 128-bit AES encryption, GCM mode. This encryption mode"},{"type":"text","text":" "},{"type":"text","text":"requires the setting of salt (encryptionKdfSalt)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128GCM2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES128GCM2"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes128gcm2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/SM4128ECB":{"role":"symbol","title":"AgoraEncryptionMode.SM4128ECB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SM4128ECB"}],"abstract":[{"type":"text","text":"4: 128-bit SM4 encryption, ECB mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/SM4128ECB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeSM4128ECB"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/sm4128ecb"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES128XTS":{"role":"symbol","title":"AgoraEncryptionMode.AES128XTS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES128XTS"}],"abstract":[{"type":"text","text":"1: 128-bit AES encryption, XTS mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128XTS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES128XTS"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes128xts"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES128GCM":{"role":"symbol","title":"AgoraEncryptionMode.AES128GCM","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES128GCM"}],"abstract":[{"type":"text","text":"5: 128-bit AES encryption, GCM mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128GCM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES128GCM"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes128gcm"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraencryptionmode\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraencryptionmode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode":{"role":"symbol","title":"AgoraEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"}],"abstract":[{"type":"text","text":"The built-in encryption mode."},{"type":"text","text":" "},{"type":"text","text":"Agora recommends using AgoraEncryptionModeAES128GCM2 or"},{"type":"text","text":" "},{"type":"text","text":"AgoraEncryptionModeAES256GCM2 encrypted mode. These two modes support the use"},{"type":"text","text":" "},{"type":"text","text":"of salt for higher security."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionMode"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraencryptionmode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES256GCM":{"role":"symbol","title":"AgoraEncryptionMode.AES256GCM","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES256GCM"}],"abstract":[{"type":"text","text":"6: 256-bit AES encryption, GCM mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256GCM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES256GCM"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes256gcm"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES128ECB":{"role":"symbol","title":"AgoraEncryptionMode.AES128ECB","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES128ECB"}],"abstract":[{"type":"text","text":"2: 128-bit AES encryption, ECB mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128ECB","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES128ECB"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes128ecb"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/end":{"role":"symbol","title":"AgoraEncryptionMode.end","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"}],"abstract":[{"type":"text","text":"8: 256-bit AES encryption, GCM mode. This encryption mode requires the"},{"type":"text","text":" "},{"type":"text","text":"setting of salt (encryptionKdfSalt)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/end","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeEnd"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/end"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES256XTS":{"role":"symbol","title":"AgoraEncryptionMode.AES256XTS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES256XTS"}],"abstract":[{"type":"text","text":"3: 256-bit AES encryption, XTS mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256XTS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES256XTS"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes256xts"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionMode/AES256GCM2":{"role":"symbol","title":"AgoraEncryptionMode.AES256GCM2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AES256GCM2"}],"abstract":[{"type":"text","text":"8: 256-bit AES encryption, GCM mode. This encryption mode requires the"},{"type":"text","text":" "},{"type":"text","text":"setting of salt (encryptionKdfSalt)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256GCM2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionModeAES256GCM2"}],"url":"\/documentation\/agorartckit\/agoraencryptionmode\/aes256gcm2"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncryptionMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEncryptionMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128ECB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128GCM","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128GCM2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES128XTS","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256GCM","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256GCM2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/AES256XTS","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/SM4128ECB","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionMode\/end"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128GCM2\/title","value":"AgoraEncryptionModeAES128GCM2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128GCM2\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES128GCM2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1SM4128ECB\/title","value":"AgoraEncryptionModeSM4128ECB"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1SM4128ECB\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeSM4128ECB"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128XTS\/title","value":"AgoraEncryptionModeAES128XTS"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128XTS\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES128XTS"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128GCM\/title","value":"AgoraEncryptionModeAES128GCM"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128GCM\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES128GCM"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/title","value":"AgoraEncryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256GCM\/title","value":"AgoraEncryptionModeAES256GCM"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256GCM\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES256GCM"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128ECB\/title","value":"AgoraEncryptionModeAES128ECB"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES128ECB\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES128ECB"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1end\/title","value":"AgoraEncryptionModeEnd"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1end\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeEnd"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256XTS\/title","value":"AgoraEncryptionModeAES256XTS"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256XTS\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES256XTS"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256GCM2\/title","value":"AgoraEncryptionModeAES256GCM2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionMode~1AES256GCM2\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionModeAES256GCM2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}