{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The error code of the channel media relay."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayError"}],"title":"AgoraChannelMediaRelayError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraChannelMediaRelayError","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayError"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/destinationTokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedJoinDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedJoinSourceChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedPacketReceivedFromSource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedPacketSentToDestination","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/internalError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/noResourceAvailable","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/none","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverConnectionLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverErrorResponse","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverNoResponse","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/sourceTokenExpired"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/internalError":{"role":"symbol","title":"AgoraChannelMediaRelayError.internalError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"abstract":[{"type":"text","text":"9: An internal error occurs in the server."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/internalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorInternalError"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/internalerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/failedJoinSourceChannel":{"role":"symbol","title":"AgoraChannelMediaRelayError.failedJoinSourceChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedJoinSourceChannel"}],"abstract":[{"type":"text","text":"4: Fails to send the relay request."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedJoinSourceChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedJoinSourceChannel"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/failedjoinsourcechannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/sourceTokenExpired":{"role":"symbol","title":"AgoraChannelMediaRelayError.sourceTokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceTokenExpired"}],"abstract":[{"type":"text","text":"10: The token of the source channel has expired."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/sourceTokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorSourceTokenExpired"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/sourcetokenexpired"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/failedPacketSentToDestination":{"role":"symbol","title":"AgoraChannelMediaRelayError.failedPacketSentToDestination","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedPacketSentToDestination"}],"abstract":[{"type":"text","text":"7: The server fails to send the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedPacketSentToDestination","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedPacketSentToDestination"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/failedpacketsenttodestination"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/serverConnectionLost":{"role":"symbol","title":"AgoraChannelMediaRelayError.serverConnectionLost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverConnectionLost"}],"abstract":[{"type":"text","text":"8: The SDK disconnects from the server due to poor network connections. You can call leaveChannel [1\/2]"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverConnectionLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerConnectionLost"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/serverconnectionlost"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/failedJoinDestinationChannel":{"role":"symbol","title":"AgoraChannelMediaRelayError.failedJoinDestinationChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedJoinDestinationChannel"}],"abstract":[{"type":"text","text":"5: Fails to accept the relay request."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedJoinDestinationChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedJoinDestinationChannel"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/failedjoindestinationchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/serverNoResponse":{"role":"symbol","title":"AgoraChannelMediaRelayError.serverNoResponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverNoResponse"}],"abstract":[{"type":"text","text":"2: No server response.You can call leaveChannel [1\/2]This error can also occur if your project has not enabled co-host token authentication. You can to enable the service for cohosting across channels before starting a channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverNoResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerNoResponse"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/servernoresponse"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/serverErrorResponse":{"role":"symbol","title":"AgoraChannelMediaRelayError.serverErrorResponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverErrorResponse"}],"abstract":[{"type":"text","text":"1: An error occurs in the server response."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverErrorResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerErrorResponse"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/servererrorresponse"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/failedPacketReceivedFromSource":{"role":"symbol","title":"AgoraChannelMediaRelayError.failedPacketReceivedFromSource","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedPacketReceivedFromSource"}],"abstract":[{"type":"text","text":"6: The server fails to receive the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedPacketReceivedFromSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedPacketReceivedFromSource"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/failedpacketreceivedfromsource"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/none":{"role":"symbol","title":"AgoraChannelMediaRelayError.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"0: No error."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorNone"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/none"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError":{"role":"symbol","title":"AgoraChannelMediaRelayError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayError"}],"abstract":[{"type":"text","text":"The error code of the channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayError"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/destinationTokenExpired":{"role":"symbol","title":"AgoraChannelMediaRelayError.destinationTokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"destinationTokenExpired"}],"abstract":[{"type":"text","text":"11: The token of the destination channel has expired."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/destinationTokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorDestinationTokenExpired"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/destinationtokenexpired"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/noResourceAvailable":{"role":"symbol","title":"AgoraChannelMediaRelayError.noResourceAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noResourceAvailable"}],"abstract":[{"type":"text","text":"3: The SDK fails to access the service, probably due to limited resources of the server."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/noResourceAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorNoResourceAvailable"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/noresourceavailable"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorachannelmediarelayerror\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelMediaRelayError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/destinationTokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedJoinDestinationChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedJoinSourceChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedPacketReceivedFromSource","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/failedPacketSentToDestination","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/internalError","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/noResourceAvailable","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/none","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverConnectionLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverErrorResponse","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/serverNoResponse","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayError\/sourceTokenExpired"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1internalError\/title","value":"AgoraChannelMediaRelayErrorInternalError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1internalError\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedJoinSourceChannel\/title","value":"AgoraChannelMediaRelayErrorFailedJoinSourceChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedJoinSourceChannel\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedJoinSourceChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1sourceTokenExpired\/title","value":"AgoraChannelMediaRelayErrorSourceTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1sourceTokenExpired\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorSourceTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedPacketSentToDestination\/title","value":"AgoraChannelMediaRelayErrorFailedPacketSentToDestination"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedPacketSentToDestination\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedPacketSentToDestination"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverConnectionLost\/title","value":"AgoraChannelMediaRelayErrorServerConnectionLost"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverConnectionLost\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerConnectionLost"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedJoinDestinationChannel\/title","value":"AgoraChannelMediaRelayErrorFailedJoinDestinationChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedJoinDestinationChannel\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedJoinDestinationChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverNoResponse\/title","value":"AgoraChannelMediaRelayErrorServerNoResponse"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverNoResponse\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerNoResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverErrorResponse\/title","value":"AgoraChannelMediaRelayErrorServerErrorResponse"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1serverErrorResponse\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorServerErrorResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedPacketReceivedFromSource\/title","value":"AgoraChannelMediaRelayErrorFailedPacketReceivedFromSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1failedPacketReceivedFromSource\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorFailedPacketReceivedFromSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1none\/title","value":"AgoraChannelMediaRelayErrorNone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1none\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorNone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError\/title","value":"AgoraChannelMediaRelayError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1destinationTokenExpired\/title","value":"AgoraChannelMediaRelayErrorDestinationTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1destinationTokenExpired\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorDestinationTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1noResourceAvailable\/title","value":"AgoraChannelMediaRelayErrorNoResourceAvailable"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayError~1noResourceAvailable\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayErrorNoResourceAvailable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}