{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediatraceevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediatraceevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The rendering state of the media frame."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"title":"AgoraMediaTraceEvent","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraMediaTraceEvent","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoDecoded","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoRendered"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediatraceevent\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent/videoRendered":{"role":"symbol","title":"AgoraMediaTraceEvent.videoRendered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoRendered"}],"abstract":[{"type":"text","text":"0: The video frame has been rendered."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoRendered","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoRendered"}],"url":"\/documentation\/agorartckit\/agoramediatraceevent\/videorendered"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediatraceevent\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoramediatraceevent\/init(rawvalue:)"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent/videoDecoded":{"role":"symbol","title":"AgoraMediaTraceEvent.videoDecoded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoDecoded"}],"abstract":[{"type":"text","text":"1: The video frame has been decoded."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoDecoded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoDecoded"}],"url":"\/documentation\/agorartckit\/agoramediatraceevent\/videodecoded"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaTraceEvent":{"role":"symbol","title":"AgoraMediaTraceEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"abstract":[{"type":"text","text":"The rendering state of the media frame."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.1.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}],"url":"\/documentation\/agorartckit\/agoramediatraceevent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaTraceEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoDecoded","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaTraceEvent\/videoRendered"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaTraceEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent~1videoRendered\/title","value":"AgoraMediaTraceEventVideoRendered"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent~1videoRendered\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoRendered"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent~1videoDecoded\/title","value":"AgoraMediaTraceEventVideoDecoded"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent~1videoDecoded\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEventVideoDecoded"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent\/title","value":"AgoraMediaTraceEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaTraceEvent\/fragments","value":[{"kind":"identifier","text":"AgoraMediaTraceEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}