{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Agora supports publishing multiple audio streams and one video stream at the same time and in the same AgoraRtcConnection . For example, publishMicrophoneTrack , publishAudioTrack , publishCustomAudioTrack, and publishMediaPlayerAudioTrack can be set as YES at the same time, but only one of publishCameraTrack , publishScreenCaptureVideo publishCustomVideoTrack , or publishEncodedVideoTrack can be set as YES . Agora recommends that you set member parameter values yourself according to your business scenario, otherwise the SDK will automatically assign values to member parameters."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcchannelmediaoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcchannelmediaoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The channel media options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}],"title":"AgoraRtcChannelMediaOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRtcChannelMediaOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/audienceLatencyLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/audioDelayMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/autoSubscribeAudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/autoSubscribeVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/channelProfile","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/clientRoleType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/customVideoTrackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/defaultVideoStreamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/enableAudioRecordingOrPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/enableBuiltInMediaEncryption","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/isAudioFilterable","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/isInteractiveAudience","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/mediaPlayerAudioDelayMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCameraTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomAudioTrackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishEncodedVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMicrophoneTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishRhythmPlayerTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishScreenCaptureAudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishScreenCaptureVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishSecondaryCameraTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishTranscodedVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/token"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/audienceLatencyLevel":{"role":"symbol","title":"audienceLatencyLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audienceLatencyLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudienceLatencyLevelType","preciseIdentifier":"c:@E@AgoraAudienceLatencyLevelType"}],"abstract":[{"type":"text","text":"The latency level of an audience member in interactive live streaming. See AgoraAudienceLatencyLevelType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/audienceLatencyLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audienceLatencyLevel"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/audiencelatencylevel"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishCustomAudioTrack":{"role":"symbol","title":"publishCustomAudioTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCustomAudioTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishcustomaudiotrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishCustomAudioTrackId":{"role":"symbol","title":"publishCustomAudioTrackId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomAudioTrackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The ID of the custom audio source to publish. The default value is 0.If you have set sourceNumber in setExternalAudioSource [2\/2] to a value greater than 1, the SDK creates the corresponding number of custom audio tracks and assigns an ID to each audio track, starting from 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomAudioTrackId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCustomAudioTrackId"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishcustomaudiotrackid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishMediaPlayerId":{"role":"symbol","title":"publishMediaPlayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishMediaPlayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The ID of the media player to be published. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishMediaPlayerId"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishmediaplayerid"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishScreenCaptureAudio":{"role":"symbol","title":"publishScreenCaptureAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishScreenCaptureAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the audio captured from the screen:YES: Publish the audio captured from the screen.NO: Publish the audio captured from the screen."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishScreenCaptureAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishScreenCaptureAudio"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishscreencaptureaudio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishEncodedVideoTrack":{"role":"symbol","title":"publishEncodedVideoTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishEncodedVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the encoded video:YES: Publish the encoded video.NO: Do not publish the encoded video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishEncodedVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishEncodedVideoTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishencodedvideotrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/mediaPlayerAudioDelayMs":{"role":"symbol","title":"mediaPlayerAudioDelayMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaPlayerAudioDelayMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/mediaPlayerAudioDelayMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaPlayerAudioDelayMs"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/mediaplayeraudiodelayms"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions":{"role":"symbol","title":"AgoraRtcChannelMediaOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}],"abstract":[{"type":"text","text":"The channel media options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/isInteractiveAudience":{"role":"symbol","title":"isInteractiveAudience","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInteractiveAudience"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable interactive mode:YES: Enable interactive mode. Once this mode is enabled and the user role is set as audience, the user can receive remote video streams with low latency.NO:Do not enable interactive mode. If this mode is disabled, the user receives the remote video streams in default settings.This parameter only applies to scenarios involving cohosting across channels. The cohosts need to call the joinChannelExByToken [1\/2] method to join the other host’s channel as an audience member, and set isInteractiveAudience to YES.This parameter takes effect only when the user role is AgoraClientRoleAudience."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/isInteractiveAudience","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isInteractiveAudience"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/isinteractiveaudience"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/clientRoleType":{"role":"symbol","title":"clientRoleType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientRoleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"}],"abstract":[{"type":"text","text":"The user role. See AgoraClientRole."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/clientRoleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientRoleType"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/clientroletype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/autoSubscribeAudio":{"role":"symbol","title":"autoSubscribeAudio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSubscribeAudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically subscribe to all remote audio streams when the user joins a channel:YES: Subscribe to all remote audio streams.NO: Do not automatically subscribe to any remote audio streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/autoSubscribeAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoSubscribeAudio"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/autosubscribeaudio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/channelProfile":{"role":"symbol","title":"channelProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChannelProfile","preciseIdentifier":"c:@E@AgoraChannelProfile"}],"abstract":[{"type":"text","text":"The channel profile. See AgoraChannelProfile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/channelProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelProfile"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/channelprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/autoSubscribeVideo":{"role":"symbol","title":"autoSubscribeVideo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSubscribeVideo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to automatically subscribe to all remote video streams when the user joins the channel:YES: Subscribe to all remote video streams.NO: Do not automatically subscribe to any remote video streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/autoSubscribeVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoSubscribeVideo"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/autosubscribevideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishCameraTrack":{"role":"symbol","title":"publishCameraTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCameraTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the video captured by the camera:YES: Publish the video captured by the camera.NO: Do not publish the video captured by the camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCameraTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCameraTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishcameratrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/enableAudioRecordingOrPlayout":{"role":"symbol","title":"enableAudioRecordingOrPlayout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableAudioRecordingOrPlayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to enable audio capturing or playback:YES: Do not enable audio capturing or playback.NO: Do not enable audio capturing or playback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/enableAudioRecordingOrPlayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableAudioRecordingOrPlayout"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/enableaudiorecordingorplayout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/enableBuiltInMediaEncryption":{"role":"symbol","title":"enableBuiltInMediaEncryption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableBuiltInMediaEncryption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/enableBuiltInMediaEncryption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableBuiltInMediaEncryption"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/enablebuiltinmediaencryption"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishMediaPlayerAudioTrack":{"role":"symbol","title":"publishMediaPlayerAudioTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishMediaPlayerAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the audio from the media player:YES: Publish the audio from the media player.NO: Do not publish the audio from the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishMediaPlayerAudioTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishmediaplayeraudiotrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/token":{"role":"symbol","title":"token","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"(Optional) The token generated on your server for authentication. See Authenticate Your Users with Token.This parameter takes effect only when calling updateChannelWithMediaOptions or updateChannelExWithMediaOptions.Ensure that the App ID, channel name, and user name used for creating the token are the same as those used by the sharedEngineWithConfig method for initializing the RTC engine, and those used by the joinChannelByToken [2\/4] and joinChannelExByToken [1\/2] methods for joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/token","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"token"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/token"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishMediaPlayerVideoTrack":{"role":"symbol","title":"publishMediaPlayerVideoTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishMediaPlayerVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the video from the media player:YES: Publish the video from the media player.NO: Do not publish the video from the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishMediaPlayerVideoTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishmediaplayervideotrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishScreenCaptureVideo":{"role":"symbol","title":"publishScreenCaptureVideo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishScreenCaptureVideo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishScreenCaptureVideo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishScreenCaptureVideo"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishscreencapturevideo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishMicrophoneTrack":{"role":"symbol","title":"publishMicrophoneTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishMicrophoneTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the audio captured by the microphone:YES: Publish the audio captured by the microphone.NO: Do not publish the audio captured by the microphone."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMicrophoneTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishMicrophoneTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishmicrophonetrack"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishRhythmPlayerTrack":{"role":"symbol","title":"publishRhythmPlayerTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishRhythmPlayerTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the sound of a metronome to remote users:YES: Publish processed audio frames. Both the local user and remote users can hear the metronome.NO: Do not publish the sound of the metronome. Only the local user can hear the metronome."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishRhythmPlayerTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishRhythmPlayerTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishrhythmplayertrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishCustomVideoTrack":{"role":"symbol","title":"publishCustomVideoTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishCustomVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to publish the video captured from a custom source:YES: Publish the video captured from the custom source.NO: Do not publish the captured video from a custom source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishCustomVideoTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishcustomvideotrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/audioDelayMs":{"role":"symbol","title":"audioDelayMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDelayMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/audioDelayMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioDelayMs"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/audiodelayms"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/isAudioFilterable":{"role":"symbol","title":"isAudioFilterable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAudioFilterable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the audio stream being published is filtered according to the volume algorithm:YES: The audio stream is not filtered. If the audio stream filter is not enabled, this setting does not takes effect.NO: The audio stream is not filtered.If you need to enable this function, contact ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/isAudioFilterable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isAudioFilterable"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/isaudiofilterable"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishSecondaryCameraTrack":{"role":"symbol","title":"publishSecondaryCameraTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishSecondaryCameraTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishSecondaryCameraTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishSecondaryCameraTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishsecondarycameratrack"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/defaultVideoStreamType":{"role":"symbol","title":"defaultVideoStreamType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultVideoStreamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoStreamType","preciseIdentifier":"c:@E@AgoraVideoStreamType"}],"abstract":[{"type":"text","text":"The default video-stream type. See AgoraVideoStreamType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/defaultVideoStreamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultVideoStreamType"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/defaultvideostreamtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/customVideoTrackId":{"role":"symbol","title":"customVideoTrackId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customVideoTrackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The video track ID returned by calling the createCustomVideoTrack method. The default value is 0."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/customVideoTrackId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customVideoTrackId"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/customvideotrackid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcChannelMediaOptions/publishTranscodedVideoTrack":{"role":"symbol","title":"publishTranscodedVideoTrack","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishTranscodedVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishTranscodedVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishTranscodedVideoTrack"}],"url":"\/documentation\/agorartckit\/agorartcchannelmediaoptions\/publishtranscodedvideotrack"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcChannelMediaOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/audienceLatencyLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/audioDelayMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/autoSubscribeAudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/autoSubscribeVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/channelProfile","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/clientRoleType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/customVideoTrackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/defaultVideoStreamType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/enableAudioRecordingOrPlayout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/enableBuiltInMediaEncryption","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/isAudioFilterable","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/isInteractiveAudience","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/mediaPlayerAudioDelayMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCameraTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomAudioTrackId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishCustomVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishEncodedVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerAudioTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMediaPlayerVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishMicrophoneTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishRhythmPlayerTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishScreenCaptureAudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishScreenCaptureVideo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishSecondaryCameraTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/publishTranscodedVideoTrack","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcChannelMediaOptions\/token"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1audienceLatencyLevel\/title","value":"audienceLatencyLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1audienceLatencyLevel\/fragments","value":[{"kind":"identifier","text":"audienceLatencyLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCustomAudioTrack\/title","value":"publishCustomAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCustomAudioTrack\/fragments","value":[{"kind":"identifier","text":"publishCustomAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCustomAudioTrackId\/title","value":"publishCustomAudioTrackId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCustomAudioTrackId\/fragments","value":[{"kind":"identifier","text":"publishCustomAudioTrackId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMediaPlayerId\/title","value":"publishMediaPlayerId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMediaPlayerId\/fragments","value":[{"kind":"identifier","text":"publishMediaPlayerId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishScreenCaptureAudio\/title","value":"publishScreenCaptureAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishScreenCaptureAudio\/fragments","value":[{"kind":"identifier","text":"publishScreenCaptureAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishEncodedVideoTrack\/title","value":"publishEncodedVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishEncodedVideoTrack\/fragments","value":[{"kind":"identifier","text":"publishEncodedVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1mediaPlayerAudioDelayMs\/title","value":"mediaPlayerAudioDelayMs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1mediaPlayerAudioDelayMs\/fragments","value":[{"kind":"identifier","text":"mediaPlayerAudioDelayMs"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions\/title","value":"AgoraRtcChannelMediaOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions\/fragments","value":[{"kind":"identifier","text":"AgoraRtcChannelMediaOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1isInteractiveAudience\/title","value":"isInteractiveAudience"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1isInteractiveAudience\/fragments","value":[{"kind":"identifier","text":"isInteractiveAudience"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1clientRoleType\/title","value":"clientRoleType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1clientRoleType\/fragments","value":[{"kind":"identifier","text":"clientRoleType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1autoSubscribeAudio\/title","value":"autoSubscribeAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1autoSubscribeAudio\/fragments","value":[{"kind":"identifier","text":"autoSubscribeAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1channelProfile\/title","value":"channelProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1channelProfile\/fragments","value":[{"kind":"identifier","text":"channelProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1autoSubscribeVideo\/title","value":"autoSubscribeVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1autoSubscribeVideo\/fragments","value":[{"kind":"identifier","text":"autoSubscribeVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCameraTrack\/title","value":"publishCameraTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCameraTrack\/fragments","value":[{"kind":"identifier","text":"publishCameraTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1enableAudioRecordingOrPlayout\/title","value":"enableAudioRecordingOrPlayout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1enableAudioRecordingOrPlayout\/fragments","value":[{"kind":"identifier","text":"enableAudioRecordingOrPlayout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1enableBuiltInMediaEncryption\/title","value":"enableBuiltInMediaEncryption"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1enableBuiltInMediaEncryption\/fragments","value":[{"kind":"identifier","text":"enableBuiltInMediaEncryption"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMediaPlayerAudioTrack\/title","value":"publishMediaPlayerAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMediaPlayerAudioTrack\/fragments","value":[{"kind":"identifier","text":"publishMediaPlayerAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1token\/fragments","value":[{"kind":"identifier","text":"token"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMediaPlayerVideoTrack\/title","value":"publishMediaPlayerVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMediaPlayerVideoTrack\/fragments","value":[{"kind":"identifier","text":"publishMediaPlayerVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishScreenCaptureVideo\/title","value":"publishScreenCaptureVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishScreenCaptureVideo\/fragments","value":[{"kind":"identifier","text":"publishScreenCaptureVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMicrophoneTrack\/title","value":"publishMicrophoneTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishMicrophoneTrack\/fragments","value":[{"kind":"identifier","text":"publishMicrophoneTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishRhythmPlayerTrack\/title","value":"publishRhythmPlayerTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishRhythmPlayerTrack\/fragments","value":[{"kind":"identifier","text":"publishRhythmPlayerTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCustomVideoTrack\/title","value":"publishCustomVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishCustomVideoTrack\/fragments","value":[{"kind":"identifier","text":"publishCustomVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1audioDelayMs\/title","value":"audioDelayMs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1audioDelayMs\/fragments","value":[{"kind":"identifier","text":"audioDelayMs"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1isAudioFilterable\/title","value":"isAudioFilterable"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1isAudioFilterable\/fragments","value":[{"kind":"identifier","text":"isAudioFilterable"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishSecondaryCameraTrack\/title","value":"publishSecondaryCameraTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishSecondaryCameraTrack\/fragments","value":[{"kind":"identifier","text":"publishSecondaryCameraTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1defaultVideoStreamType\/title","value":"defaultVideoStreamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1defaultVideoStreamType\/fragments","value":[{"kind":"identifier","text":"defaultVideoStreamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1customVideoTrackId\/title","value":"customVideoTrackId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1customVideoTrackId\/fragments","value":[{"kind":"identifier","text":"customVideoTrackId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishTranscodedVideoTrack\/title","value":"publishTranscodedVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcChannelMediaOptions~1publishTranscodedVideoTrack\/fragments","value":[{"kind":"identifier","text":"publishTranscodedVideoTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}