{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiorecordingconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Recording configurations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"title":"AgoraAudioRecordingConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraAudioRecordingConfiguration","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/filePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/fileRecordOption","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/quality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/recordingChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/sampleRate"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration":{"role":"symbol","title":"AgoraAudioRecordingConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"abstract":[{"type":"text","text":"Recording configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration/filePath":{"role":"symbol","title":"filePath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"filePath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The absolute path (including the filename extensions) of the recording file."},{"type":"text","text":" "},{"type":"text","text":"For example: \/var\/mobile\/Containers\/Data\/audio.mp4.Ensure that the directory"},{"type":"text","text":" "},{"type":"text","text":"for the log files exists and is writable."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/filePath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"filePath"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/filepath"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration/recordingChannel":{"role":"symbol","title":"recordingChannel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The audio channel of recording: The parameter supports the following"},{"type":"text","text":" "},{"type":"text","text":"values:1: (Default) Mono.2: Stereo.The actual recorded audio channel is"},{"type":"text","text":" "},{"type":"text","text":"related to the audio channel that you capture.If the captured audio is mono"},{"type":"text","text":" "},{"type":"text","text":"and recordingChannel is 2, the recorded audio is the dual-channel data that"},{"type":"text","text":" "},{"type":"text","text":"is copied from mono data, not stereo.If the captured audio is dual channel"},{"type":"text","text":" "},{"type":"text","text":"and recordingChannel is 1, the recorded audio is the mono data that is mixed"},{"type":"text","text":" "},{"type":"text","text":"by dual-channel data.The integration scheme also affects the final recorded"},{"type":"text","text":" "},{"type":"text","text":"audio channel. If you need to record in stereo, contact ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/recordingChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recordingChannel"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/recordingchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration/sampleRate":{"role":"symbol","title":"sampleRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Recording sample rate (Hz).16000(Default) 320004410048000If you set this"},{"type":"text","text":" "},{"type":"text","text":"parameter to 44100 or 48000, Agora recommends recording WAV files, or AAC"},{"type":"text","text":" "},{"type":"text","text":"files with quality set as AgoraAudioRecordingQualityMedium or"},{"type":"text","text":" "},{"type":"text","text":"AgoraAudioRecordingQualityHigh for better recording quality."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/sampleRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sampleRate"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/samplerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration/quality":{"role":"symbol","title":"quality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioRecordingQuality","preciseIdentifier":"c:@E@AgoraAudioRecordingQuality"}],"abstract":[{"type":"text","text":"Recording quality. See AgoraAudioRecordingQuality .Note: This parameter"},{"type":"text","text":" "},{"type":"text","text":"applies to AAC files only."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/quality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"quality"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/quality"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioRecordingConfiguration/fileRecordOption":{"role":"symbol","title":"fileRecordOption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileRecordOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFileRecordingType","preciseIdentifier":"c:@E@AgoraAudioFileRecordingType"}],"abstract":[{"type":"text","text":"The recording content. See AgoraAudioFileRecordingType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/fileRecordOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileRecordOption"}],"url":"\/documentation\/agorartckit\/agoraaudiorecordingconfiguration\/filerecordoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioRecordingConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/filePath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/fileRecordOption","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/quality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/recordingChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioRecordingConfiguration\/sampleRate"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration\/title","value":"AgoraAudioRecordingConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraAudioRecordingConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1filePath\/title","value":"filePath"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1filePath\/fragments","value":[{"kind":"identifier","text":"filePath"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1recordingChannel\/title","value":"recordingChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1recordingChannel\/fragments","value":[{"kind":"identifier","text":"recordingChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1sampleRate\/title","value":"sampleRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1sampleRate\/fragments","value":[{"kind":"identifier","text":"sampleRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1quality\/title","value":"quality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1quality\/fragments","value":[{"kind":"identifier","text":"quality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1fileRecordOption\/title","value":"fileRecordOption"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioRecordingConfiguration~1fileRecordOption\/fragments","value":[{"kind":"identifier","text":"fileRecordOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}