{"seeAlsoSections":[{"title":"Advanced Classes","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"title":"AgoraAudioEffectPreset","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioEffectPreset","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]},"abstract":[{"type":"text","text":"Preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"To get better audio effects, Agora recommends calling setAudioProfile [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"and setting the profile parameter as recommended below before using the"},{"type":"text","text":" "},{"type":"text","text":"preset audio effects."}],"sections":[],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/off","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/pitchCorrection","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcous3DVoice","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousEthereal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousPhonograph","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousSpatial","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousStudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualStereo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualSurroundSound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVocalConcer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousticsKTV","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/styleTransformationPopular","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/styleTransformationRnb","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectBoy","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectGirl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectHulk","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectOldMan","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectPigKin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectSister","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectUncle"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioeffectpreset"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/styleTransformationRnb":{"role":"symbol","title":"AgoraAudioEffectPreset.styleTransformationRnb","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleTransformationRnb"}],"abstract":[{"type":"text","text":"The voice effect typical of R&B music."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/styleTransformationRnb","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetStyleTransformationRnb"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/styletransformationrnb"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectGirl":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectGirl","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectGirl"}],"abstract":[{"type":"text","text":"A girl’s voice.Agora recommends using this preset to process a"},{"type":"text","text":" "},{"type":"text","text":"female-sounding voice; otherwise, you may not hear the anticipated voice"},{"type":"text","text":" "},{"type":"text","text":"effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectGirl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectGirl"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectgirl"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectOldMan":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectOldMan","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectOldMan"}],"abstract":[{"type":"text","text":"An older man’s voice.Agora recommends using this preset to process a"},{"type":"text","text":" "},{"type":"text","text":"male-sounding voice; otherwise, you may not hear the anticipated voice"},{"type":"text","text":" "},{"type":"text","text":"effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectOldMan","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectOldMan"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectoldman"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousPhonograph":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousPhonograph","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousPhonograph"}],"abstract":[{"type":"text","text":"The voice effect typical of a vintage phonograph."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousPhonograph","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousPhonograph"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousphonograph"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousStudio":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousStudio","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousStudio"}],"abstract":[{"type":"text","text":"The voice effect typical of a recording studio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousStudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousStudio"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousstudio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectUncle":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectUncle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectUncle"}],"abstract":[{"type":"text","text":"A middle-aged man’s voice.Agora recommends using this preset to process a"},{"type":"text","text":" "},{"type":"text","text":"male-sounding voice; otherwise, you may not hear the anticipated voice"},{"type":"text","text":" "},{"type":"text","text":"effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectUncle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectUncle"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectuncle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/equatable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousticsKTV":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousticsKTV","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousticsKTV"}],"abstract":[{"type":"text","text":"The voice effect typical of a KTV venue."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousticsKTV","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousticsKTV"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousticsktv"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcous3DVoice":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcous3DVoice","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcous3DVoice"}],"abstract":[{"type":"text","text":"A 3D voice effect that makes the voice appear to be moving around the user."},{"type":"text","text":" "},{"type":"text","text":"The default cycle period is 10 seconds. After setting this effect, you can"},{"type":"text","text":" "},{"type":"text","text":"call setAudioEffectParameters to modify the movement period.If the 3D voice"},{"type":"text","text":" "},{"type":"text","text":"effect is enabled, users need to use stereo audio playback devices to hear"},{"type":"text","text":" "},{"type":"text","text":"the anticipated voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcous3DVoice","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcous3DVoice"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacous3dvoice"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/off":{"role":"symbol","title":"AgoraAudioEffectPreset.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"Turn off voice effects, that is, use the original voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetOff"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/off"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcLocalAudioStats":{"role":"symbol","title":"AgoraRtcLocalAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"abstract":[{"type":"text","text":"Local audio statistics."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}],"url":"\/documentation\/agorartckit\/agorartclocalaudiostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrame":{"role":"symbol","title":"AgoraVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrame"}],"abstract":[{"type":"text","text":"The external video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrame"}],"url":"\/documentation\/agorartckit\/agoravideoframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousEthereal":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousEthereal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousEthereal"}],"abstract":[{"type":"text","text":"A more ethereal voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousEthereal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousEthereal"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousethereal"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncryptionConfig":{"role":"symbol","title":"AgoraEncryptionConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncryptionConfig"}],"abstract":[{"type":"text","text":"Built-in encryption configurations."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncryptionConfig"}],"url":"\/documentation\/agorartckit\/agoraencryptionconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/styleTransformationPopular":{"role":"symbol","title":"AgoraAudioEffectPreset.styleTransformationPopular","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"styleTransformationPopular"}],"abstract":[{"type":"text","text":"The voice effect typical of popular music."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/styleTransformationPopular","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetStyleTransformationPopular"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/styletransformationpopular"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectPigKin":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectPigKin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectPigKin"}],"abstract":[{"type":"text","text":"The voice of Pig King, a character in Journey to the West who has a voice"},{"type":"text","text":" "},{"type":"text","text":"like a growling bear."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectPigKin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectPigKin"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectpigkin"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectBoy":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectBoy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectBoy"}],"abstract":[{"type":"text","text":"A boy’s voice.Agora recommends using this preset to process a male-sounding"},{"type":"text","text":" "},{"type":"text","text":"voice; otherwise, you may not hear the anticipated voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectBoy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectBoy"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectboy"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectSister":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectSister","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectSister"}],"abstract":[{"type":"text","text":"A young woman’s voice.Agora recommends using this preset to process a"},{"type":"text","text":" "},{"type":"text","text":"female-sounding voice; otherwise, you may not hear the anticipated voice"},{"type":"text","text":" "},{"type":"text","text":"effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectSister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectSister"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffectsister"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousSpatial":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousSpatial","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousSpatial"}],"abstract":[{"type":"text","text":"A more spatial voice effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousSpatial","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousSpatial"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousspatial"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/voiceChangerEffectHulk":{"role":"symbol","title":"AgoraAudioEffectPreset.voiceChangerEffectHulk","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"voiceChangerEffectHulk"}],"abstract":[{"type":"text","text":"The Hulk’s voice."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectHulk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectHulk"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/voicechangereffecthulk"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/pitchCorrection":{"role":"symbol","title":"AgoraAudioEffectPreset.pitchCorrection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitchCorrection"}],"abstract":[{"type":"text","text":"A pitch correction effect that corrects the user’s pitch based on the pitch"},{"type":"text","text":" "},{"type":"text","text":"of the natural C major scale. After setting this voice effect, you can call"},{"type":"text","text":" "},{"type":"text","text":"setAudioEffectParameters to adjust the basic mode of tuning and the pitch"},{"type":"text","text":" "},{"type":"text","text":"of the main tone."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/pitchCorrection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetPitchCorrection"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/pitchcorrection"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousVocalConcer":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousVocalConcer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousVocalConcer"}],"abstract":[{"type":"text","text":"The voice effect typical of a concert hall."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVocalConcer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVocalConcer"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousvocalconcer"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousVirtualSurroundSound":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousVirtualSurroundSound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousVirtualSurroundSound"}],"abstract":[{"type":"text","text":"Virtual surround sound, that is, the SDK generates a simulated surround"},{"type":"text","text":" "},{"type":"text","text":"sound field on the basis of stereo channels, thereby creating a surround"},{"type":"text","text":" "},{"type":"text","text":"sound effect.If the virtual surround sound is enabled, users need to use"},{"type":"text","text":" "},{"type":"text","text":"stereo audio playback devices to hear the anticipated audio effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualSurroundSound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousvirtualsurroundsound"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset":{"role":"symbol","title":"AgoraAudioEffectPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"abstract":[{"type":"text","text":"Preset audio effects."},{"type":"text","text":" "},{"type":"text","text":"To get better audio effects, Agora recommends calling setAudioProfile [1\/2]"},{"type":"text","text":" "},{"type":"text","text":"and setting the profile parameter as recommended below before using the"},{"type":"text","text":" "},{"type":"text","text":"preset audio effects."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioEffectPreset/roomAcousVirtualStereo":{"role":"symbol","title":"AgoraAudioEffectPreset.roomAcousVirtualStereo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomAcousVirtualStereo"}],"abstract":[{"type":"text","text":"The virtual stereo effect, which renders monophonic audio as stereo audio."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualStereo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualStereo"}],"url":"\/documentation\/agorartckit\/agoraaudioeffectpreset\/roomacousvirtualstereo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/off","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/pitchCorrection","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcous3DVoice","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousEthereal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousPhonograph","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousSpatial","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousStudio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualStereo","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVirtualSurroundSound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousVocalConcer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/roomAcousticsKTV","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/styleTransformationPopular","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/styleTransformationRnb","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectBoy","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectGirl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectHulk","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectOldMan","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectPigKin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectSister","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioEffectPreset\/voiceChangerEffectUncle"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Advanced Classes","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcLocalAudioStats","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncryptionConfig","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrame"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioEffectPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1styleTransformationRnb\/title","value":"AgoraAudioEffectPresetStyleTransformationRnb"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1styleTransformationRnb\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetStyleTransformationRnb"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectGirl\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectGirl"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectGirl\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectGirl"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectOldMan\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectOldMan"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectOldMan\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectOldMan"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousPhonograph\/title","value":"AgoraAudioEffectPresetRoomAcousPhonograph"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousPhonograph\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousPhonograph"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousStudio\/title","value":"AgoraAudioEffectPresetRoomAcousStudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousStudio\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousStudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectUncle\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectUncle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectUncle\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectUncle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousticsKTV\/title","value":"AgoraAudioEffectPresetRoomAcousticsKTV"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousticsKTV\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousticsKTV"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcous3DVoice\/title","value":"AgoraAudioEffectPresetRoomAcous3DVoice"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcous3DVoice\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcous3DVoice"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1off\/title","value":"AgoraAudioEffectPresetOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1off\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetOff"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/title","value":"AgoraRtcLocalAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcLocalAudioStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcLocalAudioStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/title","value":"AgoraVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousEthereal\/title","value":"AgoraAudioEffectPresetRoomAcousEthereal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousEthereal\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousEthereal"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/title","value":"AgoraEncryptionConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncryptionConfig\/fragments","value":[{"kind":"identifier","text":"AgoraEncryptionConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1styleTransformationPopular\/title","value":"AgoraAudioEffectPresetStyleTransformationPopular"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1styleTransformationPopular\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetStyleTransformationPopular"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectPigKin\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectPigKin"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectPigKin\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectPigKin"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectBoy\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectBoy"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectBoy\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectBoy"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectSister\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectSister"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectSister\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectSister"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousSpatial\/title","value":"AgoraAudioEffectPresetRoomAcousSpatial"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousSpatial\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousSpatial"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectHulk\/title","value":"AgoraAudioEffectPresetVoiceChangerEffectHulk"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1voiceChangerEffectHulk\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetVoiceChangerEffectHulk"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1pitchCorrection\/title","value":"AgoraAudioEffectPresetPitchCorrection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1pitchCorrection\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetPitchCorrection"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVocalConcer\/title","value":"AgoraAudioEffectPresetRoomAcousVocalConcer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVocalConcer\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVocalConcer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVirtualSurroundSound\/title","value":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVirtualSurroundSound\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualSurroundSound"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/title","value":"AgoraAudioEffectPreset"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVirtualStereo\/title","value":"AgoraAudioEffectPresetRoomAcousVirtualStereo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioEffectPreset~1roomAcousVirtualStereo\/fragments","value":[{"kind":"identifier","text":"AgoraAudioEffectPresetRoomAcousVirtualStereo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}