{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravirtualbackgroundsource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The custom background."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"title":"AgoraVirtualBackgroundSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraVirtualBackgroundSource","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/backgroundSourceType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/blurDegree","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/color","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/source"]}],"references":{"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource/color":{"role":"symbol","title":"color","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The type of the custom background image. The color of the custom background image. The format is a hexadecimal integer defined by RGB, without the # sign, such as 0xFFB6C1 for light pink. The default value is 0xFFFFFF, which signifies white. The value range is [0x000000, 0xffffff]. If the value is invalid, the SDK replaces the original background image with a white background image.This parameter takes effect only when the type of the custom background image is AgoraVirtualBackgroundColor."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/color","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"color"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource\/color"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource/source":{"role":"symbol","title":"source","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The local absolute path of the custom background image. PNG and JPG formats are supported. If the path is invalid, the SDK replaces the original background image with a white background image.This parameter takes effect only when the type of the custom background image is AgoraVirtualBackgroundImg."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/source","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"source"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource\/source"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource/blurDegree":{"role":"symbol","title":"blurDegree","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blurDegree"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraBlurDegree","preciseIdentifier":"c:@E@AgoraBlurDegree"}],"abstract":[{"type":"text","text":"The degree of blurring applied to the custom background image. See AgoraBlurDegree.This parameter takes effect only when the type of the custom background image is AgoraVirtualBackgroundBlur."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/blurDegree","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"blurDegree"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource\/blurdegree"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource":{"role":"symbol","title":"AgoraVirtualBackgroundSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"abstract":[{"type":"text","text":"The custom background."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVirtualBackgroundSource/backgroundSourceType":{"role":"symbol","title":"backgroundSourceType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundSourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVirtualBackgroundSourceType","preciseIdentifier":"c:@E@AgoraVirtualBackgroundSourceType"}],"abstract":[{"type":"text","text":"The custom background. See AgoraVirtualBackgroundSourceType."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/backgroundSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundSourceType"}],"url":"\/documentation\/agorartckit\/agoravirtualbackgroundsource\/backgroundsourcetype"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVirtualBackgroundSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/backgroundSourceType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/blurDegree","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/color","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVirtualBackgroundSource\/source"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVirtualBackgroundSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1color\/title","value":"color"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1color\/fragments","value":[{"kind":"identifier","text":"color"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1source\/title","value":"source"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1source\/fragments","value":[{"kind":"identifier","text":"source"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1blurDegree\/title","value":"blurDegree"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1blurDegree\/fragments","value":[{"kind":"identifier","text":"blurDegree"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/title","value":"AgoraVirtualBackgroundSource"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource\/fragments","value":[{"kind":"identifier","text":"AgoraVirtualBackgroundSource"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1backgroundSourceType\/title","value":"backgroundSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVirtualBackgroundSource~1backgroundSourceType\/fragments","value":[{"kind":"identifier","text":"backgroundSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}