{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorainjectstreamstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorainjectstreamstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/broken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startAlreadyExists","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startTimedout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startUnauthorized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopNotFound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopTimedout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopUnauthorized"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"title":"AgoraInjectStreamStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraInjectStreamStatus","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/stopSuccess":{"role":"symbol","title":"AgoraInjectStreamStatus.stopSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopSuccess"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopSuccess"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/stopsuccess"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/startUnauthorized":{"role":"symbol","title":"AgoraInjectStreamStatus.startUnauthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUnauthorized"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startUnauthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartUnauthorized"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/startunauthorized"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/stopNotFound":{"role":"symbol","title":"AgoraInjectStreamStatus.stopNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopNotFound"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopNotFound"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/stopnotfound"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/stopUnauthorized":{"role":"symbol","title":"AgoraInjectStreamStatus.stopUnauthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopUnauthorized"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopUnauthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopUnauthorized"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/stopunauthorized"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus":{"role":"symbol","title":"AgoraInjectStreamStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/startTimedout":{"role":"symbol","title":"AgoraInjectStreamStatus.startTimedout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTimedout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startTimedout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartTimedout"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/starttimedout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/startAlreadyExists":{"role":"symbol","title":"AgoraInjectStreamStatus.startAlreadyExists","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAlreadyExists"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startAlreadyExists","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartAlreadyExists"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/startalreadyexists"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/startSuccess":{"role":"symbol","title":"AgoraInjectStreamStatus.startSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSuccess"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartSuccess"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/startsuccess"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/stopTimedout":{"role":"symbol","title":"AgoraInjectStreamStatus.stopTimedout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopTimedout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopTimedout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopTimedout"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/stoptimedout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/stopFailed":{"role":"symbol","title":"AgoraInjectStreamStatus.stopFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopFailed"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/stopfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/broken":{"role":"symbol","title":"AgoraInjectStreamStatus.broken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"broken"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/broken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusBroken"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/broken"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraInjectStreamStatus/startFailed":{"role":"symbol","title":"AgoraInjectStreamStatus.startFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartFailed"}],"url":"\/documentation\/agorartckit\/agorainjectstreamstatus\/startfailed"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraInjectStreamStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/broken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startAlreadyExists","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startTimedout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/startUnauthorized","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopNotFound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopTimedout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraInjectStreamStatus\/stopUnauthorized"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraInjectStreamStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopSuccess\/title","value":"AgoraInjectStreamStatusStopSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startUnauthorized\/title","value":"AgoraInjectStreamStatusStartUnauthorized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startUnauthorized\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartUnauthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopNotFound\/title","value":"AgoraInjectStreamStatusStopNotFound"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopNotFound\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopNotFound"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopUnauthorized\/title","value":"AgoraInjectStreamStatusStopUnauthorized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopUnauthorized\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopUnauthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus\/title","value":"AgoraInjectStreamStatus"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startTimedout\/title","value":"AgoraInjectStreamStatusStartTimedout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startTimedout\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartTimedout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startAlreadyExists\/title","value":"AgoraInjectStreamStatusStartAlreadyExists"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startAlreadyExists\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartAlreadyExists"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startSuccess\/title","value":"AgoraInjectStreamStatusStartSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopTimedout\/title","value":"AgoraInjectStreamStatusStopTimedout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopTimedout\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopTimedout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopFailed\/title","value":"AgoraInjectStreamStatusStopFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1stopFailed\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStopFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1broken\/title","value":"AgoraInjectStreamStatusBroken"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1broken\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusBroken"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startFailed\/title","value":"AgoraInjectStreamStatusStartFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraInjectStreamStatus~1startFailed\/fragments","value":[{"kind":"identifier","text":"AgoraInjectStreamStatusStartFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}