{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The audio frame observer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"title":"AgoraAudioFrameDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraAudioFrameDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getEarMonitoringAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getMixedAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getObservedAudioFramePosition()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getPlaybackAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getRecordAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onEarMonitoringAudioFrame(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onMixedAudioFrame(_:channelId:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(_:channelId:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(beforeMixing:channelId:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onRecordAudioFrame(_:channelId:)"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getRecordAudioParams()":{"navigatorTitle":[{"kind":"identifier","text":"getRecordAudioParams"}],"role":"symbol","title":"getRecordAudioParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRecordAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getRecordAudioParams()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getrecordaudioparams()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onPlaybackAudioFrame(_:channelId:)":{"role":"symbol","title":"onPlaybackAudioFrame(_:channelId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the raw audio frame for playback."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the data format of audio frame for playback is as expected,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you choose one of the following two methods to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format:Method 1: After calling"},{"type":"text","text":" "},{"type":"text","text":"setPlaybackAudioFrameParametersWithSampleRate to set the audio data format"},{"type":"text","text":" "},{"type":"text","text":"and setAudioFrameDelegate to register the audio frame observer object, the"},{"type":"text","text":" "},{"type":"text","text":"SDK calculates the sampling interval according to the parameters set in the"},{"type":"text","text":" "},{"type":"text","text":"methods, and triggers the onPlaybackAudioFrame callback according to the"},{"type":"text","text":" "},{"type":"text","text":"sampling interval.Method 2: After calling setAudioFrameDelegate to register"},{"type":"text","text":" "},{"type":"text","text":"the audio frame observer object, set the audio data format in the return"},{"type":"text","text":" "},{"type":"text","text":"value of the getObservedAudioFramePosition callback. The SDK then calculates"},{"type":"text","text":" "},{"type":"text","text":"the sampling interval according to the return value of the"},{"type":"text","text":" "},{"type":"text","text":"getPlaybackAudioParams callback, and triggers the onPlaybackAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callback according to the sampling interval.The priority of method 1 is"},{"type":"text","text":" "},{"type":"text","text":"higher than that of method 2. If method 1 is used to set the audio data"},{"type":"text","text":" "},{"type":"text","text":"format, the setting of method 2 is invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(_:channelId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPlaybackAudioFrame:channelId:"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onplaybackaudioframe(_:channelid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onPlaybackAudioFrame(beforeMixing:channelId:uid:)":{"navigatorTitle":[{"kind":"identifier","text":"onPlaybackAudioFrameBeforeMixing:channelId:uid:"}],"role":"symbol","title":"onPlaybackAudioFrame(beforeMixing:channelId:uid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPlaybackAudioFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"beforeMixing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Retrieves the audio frame of a specified user before mixing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(beforeMixing:channelId:uid:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onplaybackaudioframe(beforemixing:channelid:uid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate":{"role":"symbol","title":"AgoraAudioFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"abstract":[{"type":"text","text":"The audio frame observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getObservedAudioFramePosition()":{"navigatorTitle":[{"kind":"identifier","text":"getObservedAudioFramePosition"}],"role":"symbol","title":"getObservedAudioFramePosition()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObservedAudioFramePosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getObservedAudioFramePosition()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getobservedaudioframeposition()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onRecordAudioFrame(_:channelId:)":{"role":"symbol","title":"onRecordAudioFrame(_:channelId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecordAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the raw audio frame for playback."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the data format of audio frame for playback is as expected,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you choose one of the following two methods to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format:Method 1: After calling"},{"type":"text","text":" "},{"type":"text","text":"setPlaybackAudioFrameParametersWithSampleRate to set the audio data format"},{"type":"text","text":" "},{"type":"text","text":"and setAudioFrameDelegate to register the audio frame observer object, the"},{"type":"text","text":" "},{"type":"text","text":"SDK calculates the sampling interval according to the parameters set in the"},{"type":"text","text":" "},{"type":"text","text":"methods, and triggers the onPlaybackAudioFrame callback according to the"},{"type":"text","text":" "},{"type":"text","text":"sampling interval.Method 2: After calling setAudioFrameDelegate to register"},{"type":"text","text":" "},{"type":"text","text":"the audio frame observer object, set the audio data format in the return"},{"type":"text","text":" "},{"type":"text","text":"value of the getObservedAudioFramePosition callback. The SDK then calculates"},{"type":"text","text":" "},{"type":"text","text":"the sampling interval according to the return value of the"},{"type":"text","text":" "},{"type":"text","text":"getPlaybackAudioParams callback, and triggers the onPlaybackAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callback according to the sampling interval.The priority of method 1 is"},{"type":"text","text":" "},{"type":"text","text":"higher than that of method 2. If method 1 is used to set the audio data"},{"type":"text","text":" "},{"type":"text","text":"format, the setting of method 2 is invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onRecordAudioFrame(_:channelId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onRecordAudioFrame:channelId:"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onrecordaudioframe(_:channelid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onEarMonitoringAudioFrame(_:)":{"role":"symbol","title":"onEarMonitoringAudioFrame(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEarMonitoringAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the captured audio frame."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the format of the cpatured audio frame is as expected, you can"},{"type":"text","text":" "},{"type":"text","text":"choose one of the following two methods to set the audio data format:Method"},{"type":"text","text":" "},{"type":"text","text":"1: After calling setRecordingAudioFrameParametersWithSampleRate to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format and setAudioFrameDelegate to register the audio frame"},{"type":"text","text":" "},{"type":"text","text":"observer object, the SDK calculates the sampling interval according to the"},{"type":"text","text":" "},{"type":"text","text":"parameters set in the methods, and triggers the onRecordAudioFrame callback"},{"type":"text","text":" "},{"type":"text","text":"according to the sampling interval.Method 2: After calling"},{"type":"text","text":" "},{"type":"text","text":"setAudioFrameDelegate to register the audio frame observer object, set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format in the return value of the getObservedAudioFramePosition"},{"type":"text","text":" "},{"type":"text","text":"callback. The SDK then calculates the sampling interval according to the"},{"type":"text","text":" "},{"type":"text","text":"return value of the getRecordAudioParams callback, and triggers the"},{"type":"text","text":" "},{"type":"text","text":"onRecordAudioFrame callback according to the sampling interval.The priority"},{"type":"text","text":" "},{"type":"text","text":"of method 1 is higher than that of method 2. If method 1 is used to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format, the setting of method 2 is invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onEarMonitoringAudioFrame(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onEarMonitoringAudioFrame:"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onearmonitoringaudioframe(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getPlaybackAudioParams()":{"role":"symbol","title":"getPlaybackAudioParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPlaybackAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getPlaybackAudioParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPlaybackAudioParams"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getplaybackaudioparams()"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/onMixedAudioFrame(_:channelId:)":{"navigatorTitle":[{"kind":"identifier","text":"onMixedAudioFrame:channelId:"}],"role":"symbol","title":"onMixedAudioFrame(_:channelId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMixedAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraAudioFrame","preciseIdentifier":"c:objc(cs)AgoraAudioFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets the raw audio frame for playback."},{"type":"text","text":" "},{"type":"text","text":"To ensure that the data format of audio frame for playback is as expected,"},{"type":"text","text":" "},{"type":"text","text":"Agora recommends that you choose one of the following two methods to set the"},{"type":"text","text":" "},{"type":"text","text":"audio data format:Method 1: After calling"},{"type":"text","text":" "},{"type":"text","text":"setPlaybackAudioFrameParametersWithSampleRate to set the audio data format"},{"type":"text","text":" "},{"type":"text","text":"and setAudioFrameDelegate to register the audio frame observer object, the"},{"type":"text","text":" "},{"type":"text","text":"SDK calculates the sampling interval according to the parameters set in the"},{"type":"text","text":" "},{"type":"text","text":"methods, and triggers the onPlaybackAudioFrame callback according to the"},{"type":"text","text":" "},{"type":"text","text":"sampling interval.Method 2: After calling setAudioFrameDelegate to register"},{"type":"text","text":" "},{"type":"text","text":"the audio frame observer object, set the audio data format in the return"},{"type":"text","text":" "},{"type":"text","text":"value of the getObservedAudioFramePosition callback. The SDK then calculates"},{"type":"text","text":" "},{"type":"text","text":"the sampling interval according to the return value of the"},{"type":"text","text":" "},{"type":"text","text":"getPlaybackAudioParams callback, and triggers the onPlaybackAudioFrame"},{"type":"text","text":" "},{"type":"text","text":"callback according to the sampling interval.The priority of method 1 is"},{"type":"text","text":" "},{"type":"text","text":"higher than that of method 2. If method 1 is used to set the audio data"},{"type":"text","text":" "},{"type":"text","text":"format, the setting of method 2 is invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onMixedAudioFrame(_:channelId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/onmixedaudioframe(_:channelid:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getMixedAudioParams()":{"role":"symbol","title":"getMixedAudioParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMixedAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getMixedAudioParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMixedAudioParams"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getmixedaudioparams()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFrameDelegate/getEarMonitoringAudioParams()":{"role":"symbol","title":"getEarMonitoringAudioParams()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getEarMonitoringAudioParams"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraAudioParams","preciseIdentifier":"c:objc(cs)AgoraAudioParams"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getEarMonitoringAudioParams()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getEarMonitoringAudioParams"}],"url":"\/documentation\/agorartckit\/agoraaudioframedelegate\/getearmonitoringaudioparams()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getEarMonitoringAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getMixedAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getObservedAudioFramePosition()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getPlaybackAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/getRecordAudioParams()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onEarMonitoringAudioFrame(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onMixedAudioFrame(_:channelId:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(_:channelId:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onPlaybackAudioFrame(beforeMixing:channelId:uid:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFrameDelegate\/onRecordAudioFrame(_:channelId:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFrameDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getRecordAudioParams()\/title","value":"getRecordAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getRecordAudioParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRecordAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onPlaybackAudioFrame(_:channelId:)\/title","value":"onPlaybackAudioFrame:channelId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onPlaybackAudioFrame(_:channelId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackAudioFrame:channelId:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onPlaybackAudioFrame(beforeMixing:channelId:uid:)\/title","value":"onPlaybackAudioFrameBeforeMixing:channelId:uid:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onPlaybackAudioFrame(beforeMixing:channelId:uid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPlaybackAudioFrameBeforeMixing:channelId:uid:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/title","value":"AgoraAudioFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getObservedAudioFramePosition()\/title","value":"getObservedAudioFramePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getObservedAudioFramePosition()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getObservedAudioFramePosition"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onRecordAudioFrame(_:channelId:)\/title","value":"onRecordAudioFrame:channelId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onRecordAudioFrame(_:channelId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRecordAudioFrame:channelId:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onEarMonitoringAudioFrame(_:)\/title","value":"onEarMonitoringAudioFrame:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onEarMonitoringAudioFrame(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEarMonitoringAudioFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getPlaybackAudioParams()\/title","value":"getPlaybackAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getPlaybackAudioParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPlaybackAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onMixedAudioFrame(_:channelId:)\/title","value":"onMixedAudioFrame:channelId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1onMixedAudioFrame(_:channelId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMixedAudioFrame:channelId:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getMixedAudioParams()\/title","value":"getMixedAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getMixedAudioParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMixedAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getEarMonitoringAudioParams()\/title","value":"getEarMonitoringAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFrameDelegate~1getEarMonitoringAudioParams()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getEarMonitoringAudioParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}