{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUserOfflineReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorauserofflinereason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorauserofflinereason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/becomeAudience","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/dropped","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/quit"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUserOfflineReason"}],"title":"AgoraUserOfflineReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraUserOfflineReason","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReason"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorauserofflinereason\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason":{"role":"symbol","title":"AgoraUserOfflineReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUserOfflineReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReason"}],"url":"\/documentation\/agorartckit\/agorauserofflinereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason/becomeAudience":{"role":"symbol","title":"AgoraUserOfflineReason.becomeAudience","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"becomeAudience"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/becomeAudience","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReasonBecomeAudience"}],"url":"\/documentation\/agorartckit\/agorauserofflinereason\/becomeaudience"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorauserofflinereason\/equatable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorauserofflinereason\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason/quit":{"role":"symbol","title":"AgoraUserOfflineReason.quit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/quit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReasonQuit"}],"url":"\/documentation\/agorartckit\/agorauserofflinereason\/quit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraUserOfflineReason/dropped":{"role":"symbol","title":"AgoraUserOfflineReason.dropped","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dropped"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/dropped","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraUserOfflineReasonDropped"}],"url":"\/documentation\/agorartckit\/agorauserofflinereason\/dropped"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraUserOfflineReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraUserOfflineReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/becomeAudience","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/dropped","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraUserOfflineReason\/quit"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraUserOfflineReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason\/title","value":"AgoraUserOfflineReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1becomeAudience\/title","value":"AgoraUserOfflineReasonBecomeAudience"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1becomeAudience\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReasonBecomeAudience"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1quit\/title","value":"AgoraUserOfflineReasonQuit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1quit\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReasonQuit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1dropped\/title","value":"AgoraUserOfflineReasonDropped"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraUserOfflineReason~1dropped\/fragments","value":[{"kind":"identifier","text":"AgoraUserOfflineReasonDropped"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}