{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCodecCapMask"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since v4.2.0"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracodeccapmask"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracodeccapmask"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The bit mask that indicates the device codec capability."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCodecCapMask"}],"title":"AgoraCodecCapMask","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraCodecCapMask","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCodecCapMask"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwDec","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwEnc","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskNone","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwDec","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwEnc"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask":{"role":"symbol","title":"AgoraCodecCapMask","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCodecCapMask"}],"abstract":[{"type":"text","text":"The bit mask that indicates the device codec capability."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecCapMask"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskNone":{"role":"symbol","title":"AgoraCodecCapMask.maskNone","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskNone"}],"abstract":[{"type":"text","text":"(0): The device does not support encoding or decoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskNone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskNone"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/masknone"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoracodeccapmask\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskHwEnc":{"role":"symbol","title":"AgoraCodecCapMask.maskHwEnc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskHwEnc"}],"abstract":[{"type":"text","text":"(1 << 1): The device supports hardware encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwEnc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskHwEnc"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/maskhwenc"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoracodeccapmask\/rawrepresentable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskSwEnc":{"role":"symbol","title":"AgoraCodecCapMask.maskSwEnc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwEnc"}],"abstract":[{"type":"text","text":"(1 << 3): The device supports software ecoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwEnc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskSwEnc"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/maskswenc"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskSwDec":{"role":"symbol","title":"AgoraCodecCapMask.maskSwDec","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwDec"}],"abstract":[{"type":"text","text":"(1 << 2): The device supports software decoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwDec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskSwDec"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/maskswdec"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskHwDec":{"role":"symbol","title":"AgoraCodecCapMask.maskHwDec","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskHwDec"}],"abstract":[{"type":"text","text":"(1 << 0): The device supports hardware decoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwDec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskHwDec"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/maskhwdec"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoracodeccapmask\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCodecCapMask"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCodecCapMask"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraCodecCapMask"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwDec","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwEnc","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskNone","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwDec","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwEnc"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCodecCapMask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/title","value":"AgoraCodecCapMask"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/fragments","value":[{"kind":"identifier","text":"AgoraCodecCapMask"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskNone\/title","value":"AgoraCodecMaskNone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskNone\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskNone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskHwEnc\/title","value":"AgoraCodecMaskHwEnc"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskHwEnc\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskHwEnc"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwEnc\/title","value":"AgoraCodecMaskSwEnc"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwEnc\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskSwEnc"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwDec\/title","value":"AgoraCodecMaskSwDec"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwDec\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskSwDec"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskHwDec\/title","value":"AgoraCodecMaskHwDec"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskHwDec\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskHwDec"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}