{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcremoteaudiostats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcremoteaudiostats"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio statistics of the remote user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}],"title":"AgoraRtcRemoteAudioStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRtcRemoteAudioStats","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/audioLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/frozenRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/frozenRateByCustomPlcCount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/jitterBufferDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/mosValue","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/networkTransportDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/numChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/plcCount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/publishDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qoeQuality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/quality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qualityChangedReason","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/receivedBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/receivedSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/rxAudioBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/totalActiveTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/totalFrozenTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/uid"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/plcCount":{"role":"symbol","title":"plcCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"plcCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/plcCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"plcCount"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/plccount"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/receivedBitrate":{"role":"symbol","title":"receivedBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The average bitrate (Kbps) of the received audio stream in the reported interval."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/receivedBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"receivedBitrate"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/receivedbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/publishDuration":{"role":"symbol","title":"publishDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The total duration (ms) of the remote audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/publishDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishDuration"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/publishduration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/rxAudioBytes":{"role":"symbol","title":"rxAudioBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxAudioBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/rxAudioBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxAudioBytes"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/rxaudiobytes"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/receivedSampleRate":{"role":"symbol","title":"receivedSampleRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receivedSampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The sampling rate of the received audio stream in the reported interval."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/receivedSampleRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"receivedSampleRate"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/receivedsamplerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/totalFrozenTime":{"role":"symbol","title":"totalFrozenTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalFrozenTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The total freeze time (ms) of the remote audio stream after the remote user joins the channel. In a session, audio freeze occurs when the audio frame loss rate reaches 4%."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/totalFrozenTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalFrozenTime"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/totalfrozentime"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/audioLossRate":{"role":"symbol","title":"audioLossRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioLossRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The frame loss rate (%) of the remote audio stream in the reported interval."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/audioLossRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioLossRate"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/audiolossrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/quality":{"role":"symbol","title":"quality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The quality of the audio stream sent by the user. See AgoraNetworkQuality."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/quality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"quality"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/quality"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/numChannels":{"role":"symbol","title":"numChannels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The number of audio channels."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/numChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numChannels"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/numchannels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/totalActiveTime":{"role":"symbol","title":"totalActiveTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalActiveTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The total active time (ms) between the start of the audio call and the callback of the remote user.The active time refers to the total duration of the remote user without the mute state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/totalActiveTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalActiveTime"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/totalactivetime"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/qualityChangedReason":{"role":"symbol","title":"qualityChangedReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityChangedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraExperiencePoorReason","preciseIdentifier":"c:@E@AgoraExperiencePoorReason"}],"abstract":[{"type":"text","text":"Reasons why the QoE of the local user when receiving a remote audio stream is poor. See AgoraExperiencePoorReason."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qualityChangedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityChangedReason"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/qualitychangedreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/mosValue":{"role":"symbol","title":"mosValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mosValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The quality of the remote audio stream in the reported interval. The quality is determined by the Agora real-time audio MOS (Mean Opinion Score) measurement method. The return value range is [0, 500]. Dividing the return value by 100 gets the MOS score, which ranges from 0 to 5. The higher the score, the better the audio quality.The subjective perception of audio quality corresponding to the Agora real-time audio MOS scores is as follows:MOS scorePerception of audio qualityGreater than 4Excellent. The audio sounds clear and smooth.From 3.5 to 4Good. The audio has some perceptible impairment but still sounds clear.From 3 to 3.5Fair. The audio freezes occasionally and requires attentive listening.From 2.5 to 3Poor. The audio sounds choppy and requires considerable effort to understand.From 2 to 2.5Bad. The audio has occasional noise. Consecutive audio dropouts occur, resulting in some information loss. The users can communicate only with difficulty.Less than 2Very bad. The audio has persistent noise. Consecutive audio dropouts are frequent, resulting in severe information loss. Communication is nearly impossible."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/mosValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mosValue"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/mosvalue"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/jitterBufferDelay":{"role":"symbol","title":"jitterBufferDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitterBufferDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The network delay (ms) from the audio receiver to the jitter buffer.When the receiving end is an audience member and audienceLatencyLevel of AgoraClientRoleOptions is 1, this parameter does not take effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/jitterBufferDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jitterBufferDelay"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/jitterbufferdelay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/qoeQuality":{"role":"symbol","title":"qoeQuality","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qoeQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraExperienceQuality","preciseIdentifier":"c:@E@AgoraExperienceQuality"}],"abstract":[{"type":"text","text":"The Quality of Experience (QoE) of the local user when receiving a remote audio stream. See AgoraExperienceQuality."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qoeQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qoeQuality"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/qoequality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats":{"role":"symbol","title":"AgoraRtcRemoteAudioStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}],"abstract":[{"type":"text","text":"Audio statistics of the remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/uid":{"role":"symbol","title":"uid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The user ID of the remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/uid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uid"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/uid"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/networkTransportDelay":{"role":"symbol","title":"networkTransportDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkTransportDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The network delay (ms) from the sender to the receiver."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/networkTransportDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"networkTransportDelay"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/networktransportdelay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/frozenRate":{"role":"symbol","title":"frozenRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frozenRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The total audio freeze time as a percentage (%) of the total time when the audio is available. The audio is considered available when the remote user neither stops sending the audio stream nor disables the audio module after joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/frozenRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frozenRate"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/frozenrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcRemoteAudioStats/frozenRateByCustomPlcCount":{"role":"symbol","title":"frozenRateByCustomPlcCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frozenRateByCustomPlcCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/frozenRateByCustomPlcCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frozenRateByCustomPlcCount"}],"url":"\/documentation\/agorartckit\/agorartcremoteaudiostats\/frozenratebycustomplccount"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtcRemoteAudioStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/audioLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/frozenRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/frozenRateByCustomPlcCount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/jitterBufferDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/mosValue","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/networkTransportDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/numChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/plcCount","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/publishDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qoeQuality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/quality","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/qualityChangedReason","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/receivedBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/receivedSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/rxAudioBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/totalActiveTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/totalFrozenTime","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcRemoteAudioStats\/uid"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1plcCount\/title","value":"plcCount"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1plcCount\/fragments","value":[{"kind":"identifier","text":"plcCount"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1receivedBitrate\/title","value":"receivedBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1receivedBitrate\/fragments","value":[{"kind":"identifier","text":"receivedBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1publishDuration\/title","value":"publishDuration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1publishDuration\/fragments","value":[{"kind":"identifier","text":"publishDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1rxAudioBytes\/title","value":"rxAudioBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1rxAudioBytes\/fragments","value":[{"kind":"identifier","text":"rxAudioBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1receivedSampleRate\/title","value":"receivedSampleRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1receivedSampleRate\/fragments","value":[{"kind":"identifier","text":"receivedSampleRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1totalFrozenTime\/title","value":"totalFrozenTime"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1totalFrozenTime\/fragments","value":[{"kind":"identifier","text":"totalFrozenTime"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1audioLossRate\/title","value":"audioLossRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1audioLossRate\/fragments","value":[{"kind":"identifier","text":"audioLossRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1quality\/title","value":"quality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1quality\/fragments","value":[{"kind":"identifier","text":"quality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1numChannels\/title","value":"numChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1numChannels\/fragments","value":[{"kind":"identifier","text":"numChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1totalActiveTime\/title","value":"totalActiveTime"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1totalActiveTime\/fragments","value":[{"kind":"identifier","text":"totalActiveTime"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1qualityChangedReason\/title","value":"qualityChangedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1qualityChangedReason\/fragments","value":[{"kind":"identifier","text":"qualityChangedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1mosValue\/title","value":"mosValue"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1mosValue\/fragments","value":[{"kind":"identifier","text":"mosValue"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1jitterBufferDelay\/title","value":"jitterBufferDelay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1jitterBufferDelay\/fragments","value":[{"kind":"identifier","text":"jitterBufferDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1qoeQuality\/title","value":"qoeQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1qoeQuality\/fragments","value":[{"kind":"identifier","text":"qoeQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats\/title","value":"AgoraRtcRemoteAudioStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats\/fragments","value":[{"kind":"identifier","text":"AgoraRtcRemoteAudioStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1uid\/title","value":"uid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1uid\/fragments","value":[{"kind":"identifier","text":"uid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1networkTransportDelay\/title","value":"networkTransportDelay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1networkTransportDelay\/fragments","value":[{"kind":"identifier","text":"networkTransportDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1frozenRate\/title","value":"frozenRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1frozenRate\/fragments","value":[{"kind":"identifier","text":"frozenRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1frozenRateByCustomPlcCount\/title","value":"frozenRateByCustomPlcCount"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcRemoteAudioStats~1frozenRateByCustomPlcCount\/fragments","value":[{"kind":"identifier","text":"frozenRateByCustomPlcCount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}