{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicCacheInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccacheinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccacheinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/songCode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/statusType"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicCacheInfo"}],"title":"AgoraMusicCacheInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraMusicCacheInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicCacheInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicCacheInfo/statusType":{"role":"symbol","title":"statusType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicCacheStatusType","preciseIdentifier":"c:@E@AgoraMusicCacheStatusType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/statusType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusType"}],"url":"\/documentation\/agorartckit\/agoramusiccacheinfo\/statustype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicCacheInfo":{"role":"symbol","title":"AgoraMusicCacheInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicCacheInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicCacheInfo"}],"url":"\/documentation\/agorartckit\/agoramusiccacheinfo"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicCacheInfo/songCode":{"role":"symbol","title":"songCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"songCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/songCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"songCode"}],"url":"\/documentation\/agorartckit\/agoramusiccacheinfo\/songcode"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicCacheInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicCacheInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMusicCacheInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/songCode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/statusType"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicCacheInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo~1statusType\/title","value":"statusType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo~1statusType\/fragments","value":[{"kind":"identifier","text":"statusType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo\/title","value":"AgoraMusicCacheInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo\/fragments","value":[{"kind":"identifier","text":"AgoraMusicCacheInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo~1songCode\/title","value":"songCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo~1songCode\/fragments","value":[{"kind":"identifier","text":"songCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}