{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/clearRemotePositions()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/clearRemotePositionsEx(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePosition(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePositionEx(_:connection:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/setRemoteAudioAttenuation(_:userId:forceSet:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePosition(_:positionInfo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePositionEx(_:positionInfo:connection:)"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/destroy()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/sharedLocalSpatialAudio(with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"title":"AgoraLocalSpatialAudioKit","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLocalSpatialAudioKit","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/clearRemotePositions()":{"role":"symbol","title":"clearRemotePositions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearRemotePositions"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Removes the spatial positions of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the local user no longer hears any"},{"type":"text","text":" "},{"type":"text","text":"remote users.After leaving the channel, to avoid wasting resources, you can"},{"type":"text","text":" "},{"type":"text","text":"also call this method to delete the spatial positions of all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/clearRemotePositions()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearRemotePositions"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/clearremotepositions()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/clearRemotePositionsEx(_:)":{"role":"symbol","title":"clearRemotePositionsEx(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearRemotePositionsEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Set the blocklist of subscriptions for video streams."},{"type":"text","text":" "},{"type":"text","text":"You can call this method to specify the video streams of a user that you do"},{"type":"text","text":" "},{"type":"text","text":"not want to subscribe to.If a user is added in the allowlist and blocklist at"},{"type":"text","text":" "},{"type":"text","text":"the same time, only the blocklist takes effect.Once the blocklist of"},{"type":"text","text":" "},{"type":"text","text":"subscriptions is set, it is effective even if you leave the current channel"},{"type":"text","text":" "},{"type":"text","text":"and rejoin the channel.You can call this method either before or after"},{"type":"text","text":" "},{"type":"text","text":"joining a channel.The blocklist is not affected by the setting in"},{"type":"text","text":" "},{"type":"text","text":"muteRemoteVideoStream , muteAllRemoteVideoStreams and autoSubscribeAudio in"},{"type":"text","text":" "},{"type":"text","text":"AgoraRtcChannelMediaOptions ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/clearRemotePositionsEx(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearRemotePositionsEx:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/clearremotepositionsex(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/sharedLocalSpatialAudio(with:)":{"role":"symbol","title":"sharedLocalSpatialAudio(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedLocalSpatialAudio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLocalSpatialAudioConfig","preciseIdentifier":"c:objc(cs)AgoraLocalSpatialAudioConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Initializes AgoraLocalSpatialAudioKit ."},{"type":"text","text":" "},{"type":"text","text":"Before calling other methods of the AgoraLocalSpatialAudioKit class, you need"},{"type":"text","text":" "},{"type":"text","text":"to call this method to initialize AgoraLocalSpatialAudioKit.The SDK supports"},{"type":"text","text":" "},{"type":"text","text":"creating only one AgoraLocalSpatialAudioKit instance for an app."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/sharedLocalSpatialAudio(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedLocalSpatialAudioWithConfig:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/sharedlocalspatialaudio(with:)"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/updateRemotePositionEx(_:positionInfo:connection:)":{"role":"symbol","title":"updateRemotePositionEx(_:positionInfo:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRemotePositionEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRemoteVoicePositionInfo","preciseIdentifier":"c:objc(cs)AgoraRemoteVoicePositionInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePositionEx(_:positionInfo:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateRemotePositionEx:positionInfo:connection:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/updateremotepositionex(_:positioninfo:connection:)"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/updateRemotePosition(_:positionInfo:)":{"role":"symbol","title":"updateRemotePosition(_:positionInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRemotePosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRemoteVoicePositionInfo","preciseIdentifier":"c:objc(cs)AgoraRemoteVoicePositionInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the spatial position of the specified remote user."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the SDK calculates the spatial audio"},{"type":"text","text":" "},{"type":"text","text":"parameters based on the relative position of the local and remote user.Call"},{"type":"text","text":" "},{"type":"text","text":"this method after joinChannelByToken [2\/4] ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePosition(_:positionInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateRemotePosition:positionInfo:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/updateremoteposition(_:positioninfo:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit":{"role":"symbol","title":"AgoraLocalSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/destroy()":{"role":"symbol","title":"destroy()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroy"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Destroys AgoraLocalSpatialAudioKit ."},{"type":"text","text":" "},{"type":"text","text":"This method releases all resources under AgoraLocalSpatialAudioKit. When the"},{"type":"text","text":" "},{"type":"text","text":"user does not need to use the spatial audio effect, you can call this method"},{"type":"text","text":" "},{"type":"text","text":"to release resources for other operations.After calling this method, you can"},{"type":"text","text":" "},{"type":"text","text":"no longer use any of the APIs under AgoraLocalSpatialAudioKit. To use the"},{"type":"text","text":" "},{"type":"text","text":"spatial audio effect again, you need to wait until the destroy method"},{"type":"text","text":" "},{"type":"text","text":"execution to complete before calling sharedLocalSpatialAudioWithConfig to"},{"type":"text","text":" "},{"type":"text","text":"create a new AgoraLocalSpatialAudioKit.Call this method before the destroy"},{"type":"text","text":" "},{"type":"text","text":"method under AgoraRtcEngineKit ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/destroy()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"destroy"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/destroy()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/removeRemotePosition(_:)":{"role":"symbol","title":"removeRemotePosition(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRemotePosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Removes the spatial position of the specified remote user."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the local user no longer hears the"},{"type":"text","text":" "},{"type":"text","text":"specified remote user.After leaving the channel, to avoid wasting resources,"},{"type":"text","text":" "},{"type":"text","text":"you can also call this method to delete the spatial position of the specified"},{"type":"text","text":" "},{"type":"text","text":"remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePosition(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeRemotePosition:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/removeremoteposition(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/removeRemotePositionEx(_:connection:)":{"role":"symbol","title":"removeRemotePositionEx(_:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRemotePositionEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePositionEx(_:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeRemotePositionEx:connection:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/removeremotepositionex(_:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/setRemoteAudioAttenuation(_:userId:forceSet:)":{"role":"symbol","title":"setRemoteAudioAttenuation(_:userId:forceSet:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteAudioAttenuation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forceSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the sound attenuation effect for the specified user."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/setRemoteAudioAttenuation(_:userId:forceSet:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteAudioAttenuation:userId:forceSet:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/setremoteaudioattenuation(_:userid:forceset:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit":{"role":"symbol","title":"AgoraBaseSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"abstract":[{"type":"text","text":"This class contains some of the APIs in the AgoraLocalSpatialAudioKit class."},{"type":"text","text":" "},{"type":"text","text":"The AgoraLocalSpatialAudioKit class inherits from AgoraBaseSpatialAudioKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalSpatialAudioKit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/clearRemotePositions()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/clearRemotePositionsEx(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePosition(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePositionEx(_:connection:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/setRemoteAudioAttenuation(_:userId:forceSet:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePosition(_:positionInfo:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePositionEx(_:positionInfo:connection:)"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/destroy()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/sharedLocalSpatialAudio(with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","preciseIdentifier":"c:objc(cs)AgoraBaseSpatialAudioKit","text":"AgoraBaseSpatialAudioKit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1clearRemotePositions()\/title","value":"clearRemotePositions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1clearRemotePositions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearRemotePositions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1clearRemotePositionsEx(_:)\/title","value":"clearRemotePositionsEx:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1clearRemotePositionsEx(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearRemotePositionsEx:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1sharedLocalSpatialAudio(with:)\/title","value":"sharedLocalSpatialAudioWithConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1sharedLocalSpatialAudio(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedLocalSpatialAudioWithConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1updateRemotePositionEx(_:positionInfo:connection:)\/title","value":"updateRemotePositionEx:positionInfo:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1updateRemotePositionEx(_:positionInfo:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRemotePositionEx:positionInfo:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1updateRemotePosition(_:positionInfo:)\/title","value":"updateRemotePosition:positionInfo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1updateRemotePosition(_:positionInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRemotePosition:positionInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/title","value":"AgoraLocalSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1destroy()\/title","value":"destroy"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1destroy()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"destroy"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1removeRemotePosition(_:)\/title","value":"removeRemotePosition:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1removeRemotePosition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeRemotePosition:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1removeRemotePositionEx(_:connection:)\/title","value":"removeRemotePositionEx:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1removeRemotePositionEx(_:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeRemotePositionEx:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1setRemoteAudioAttenuation(_:userId:forceSet:)\/title","value":"setRemoteAudioAttenuation:userId:forceSet:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1setRemoteAudioAttenuation(_:userId:forceSet:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteAudioAttenuation:userId:forceSet:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/title","value":"AgoraBaseSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}