{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideorendermode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideorendermode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/adaptive","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/fit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/hidden"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderMode"}],"title":"AgoraVideoRenderMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoRenderMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode":{"role":"symbol","title":"AgoraVideoRenderMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderMode"}],"url":"\/documentation\/agorartckit\/agoravideorendermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode/hidden":{"role":"symbol","title":"AgoraVideoRenderMode.hidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/hidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderModeHidden"}],"url":"\/documentation\/agorartckit\/agoravideorendermode\/hidden"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode/adaptive":{"deprecated":true,"role":"symbol","title":"AgoraVideoRenderMode.adaptive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adaptive"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/adaptive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderModeAdaptive"}],"url":"\/documentation\/agorartckit\/agoravideorendermode\/adaptive"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode/fit":{"role":"symbol","title":"AgoraVideoRenderMode.fit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/fit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderModeFit"}],"url":"\/documentation\/agorartckit\/agoravideorendermode\/fit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideorendermode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideorendermode\/init(rawvalue:)"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideorendermode\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoRenderMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoRenderMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/adaptive","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/fit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode\/hidden"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/title","value":"AgoraVideoRenderMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode~1hidden\/title","value":"AgoraVideoRenderModeHidden"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode~1hidden\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderModeHidden"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode~1adaptive\/title","value":"AgoraVideoRenderModeAdaptive"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode~1adaptive\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderModeAdaptive"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode~1fit\/title","value":"AgoraVideoRenderModeFit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode~1fit\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderModeFit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}