{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaStreamType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediastreamtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediastreamtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of the media stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaStreamType"}],"title":"AgoraMediaStreamType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraMediaStreamType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/audio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/subtitle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/unknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/video"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/video":{"role":"symbol","title":"AgoraMediaStreamType.video","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"}],"abstract":[{"type":"text","text":"1: The video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/video","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamTypeVideo"}],"url":"\/documentation\/agorartckit\/agoramediastreamtype\/video"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/audio":{"role":"symbol","title":"AgoraMediaStreamType.audio","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"}],"abstract":[{"type":"text","text":"2: The audio stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/audio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamTypeAudio"}],"url":"\/documentation\/agorartckit\/agoramediastreamtype\/audio"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType":{"role":"symbol","title":"AgoraMediaStreamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaStreamType"}],"abstract":[{"type":"text","text":"The type of the media stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamType"}],"url":"\/documentation\/agorartckit\/agoramediastreamtype"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/unknown":{"role":"symbol","title":"AgoraMediaStreamType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"0: The type is unknown."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamTypeUnknown"}],"url":"\/documentation\/agorartckit\/agoramediastreamtype\/unknown"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/subtitle":{"role":"symbol","title":"AgoraMediaStreamType.subtitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"}],"abstract":[{"type":"text","text":"3: The subtitle stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/subtitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaStreamTypeSubtitle"}],"url":"\/documentation\/agorartckit\/agoramediastreamtype\/subtitle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediastreamtype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoramediastreamtype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaStreamType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoramediastreamtype\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaStreamType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaStreamType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/audio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/subtitle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/unknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaStreamType\/video"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaStreamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1video\/title","value":"AgoraMediaStreamTypeVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1video\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamTypeVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1audio\/title","value":"AgoraMediaStreamTypeAudio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1audio\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamTypeAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType\/title","value":"AgoraMediaStreamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1unknown\/title","value":"AgoraMediaStreamTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1unknown\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1subtitle\/title","value":"AgoraMediaStreamTypeSubtitle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaStreamType~1subtitle\/fragments","value":[{"kind":"identifier","text":"AgoraMediaStreamTypeSubtitle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}