{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenter"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccontentcenter"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/createMusicPlayer(delegate:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/enableMainQueueDispatch(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getCaches()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getLyric(songCode:lyricType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getMusicCharts()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getMusicCollection(musicChartId:page:pageSize:jsonOption:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/isPreloaded(songCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/preload(songCode:jsonOption:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/register(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/removeCache(songCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/renewToken(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/searchMusic(keyWord:page:pageSize:jsonOption:)"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/destroy()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/sharedContentCenter(config:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenter"}],"title":"AgoraMusicContentCenter","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraMusicContentCenter","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenter"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/removeCache(songCode:)":{"role":"symbol","title":"removeCache(songCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"songCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/removeCache(songCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeCacheWithSongCode:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/removecache(songcode:)"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/sharedContentCenter(config:)":{"role":"symbol","title":"sharedContentCenter(config:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedContentCenter"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterConfig","preciseIdentifier":"c:objc(cs)AgoraMusicContentCenterConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/sharedContentCenter(config:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedContentCenterWithConfig:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/sharedcontentcenter(config:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/createMusicPlayer(delegate:)":{"role":"symbol","title":"createMusicPlayer(delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createMusicPlayer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcMediaPlayerDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcMediaPlayerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AgoraMusicPlayerProtocol","preciseIdentifier":"c:objc(pl)AgoraMusicPlayerProtocol"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/createMusicPlayer(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createMusicPlayerWithDelegate:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/createmusicplayer(delegate:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter":{"role":"symbol","title":"AgoraMusicContentCenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenter"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicContentCenter"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/getLyric(songCode:lyricType:)":{"role":"symbol","title":"getLyric(songCode:lyricType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLyric"},{"kind":"text","text":"("},{"kind":"externalParam","text":"songCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lyricType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getLyric(songCode:lyricType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getLyricWithSongCode:lyricType:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/getlyric(songcode:lyrictype:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/destroy()":{"role":"symbol","title":"destroy()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroy"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/destroy()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"destroy"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/destroy()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/getMusicCollection(musicChartId:page:pageSize:jsonOption:)":{"role":"symbol","title":"getMusicCollection(musicChartId:page:pageSize:jsonOption:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMusicCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"musicChartId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"page"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jsonOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getMusicCollection(musicChartId:page:pageSize:jsonOption:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMusicCollectionWithMusicChartId:page:pageSize:jsonOption:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/getmusiccollection(musicchartid:page:pagesize:jsonoption:)"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/enableMainQueueDispatch(_:)":{"role":"symbol","title":"enableMainQueueDispatch(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableMainQueueDispatch"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/enableMainQueueDispatch(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableMainQueueDispatch:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/enablemainqueuedispatch(_:)"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/preload(songCode:jsonOption:)":{"role":"symbol","title":"preload(songCode:jsonOption:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preload"},{"kind":"text","text":"("},{"kind":"externalParam","text":"songCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jsonOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/preload(songCode:jsonOption:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preloadWithSongCode:jsonOption:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/preload(songcode:jsonoption:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/getMusicCharts()":{"role":"symbol","title":"getMusicCharts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMusicCharts"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getMusicCharts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getMusicCharts"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/getmusiccharts()"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/isPreloaded(songCode:)":{"role":"symbol","title":"isPreloaded(songCode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreloaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"songCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/isPreloaded(songCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPreloadedWithSongCode:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/ispreloaded(songcode:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/renewToken(_:)":{"role":"symbol","title":"renewToken(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"renewToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/renewToken(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renewToken:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/renewtoken(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/searchMusic(keyWord:page:pageSize:jsonOption:)":{"role":"symbol","title":"searchMusic(keyWord:page:pageSize:jsonOption:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchMusic"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyWord"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"page"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jsonOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/searchMusic(keyWord:page:pageSize:jsonOption:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchMusicWithKeyWord:page:pageSize:jsonOption:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/searchmusic(keyword:page:pagesize:jsonoption:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/getCaches()":{"role":"symbol","title":"getCaches()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCaches"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getCaches()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getCaches"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/getcaches()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicContentCenter/register(_:)":{"role":"symbol","title":"register(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraMusicContentCenterEventDelegate","preciseIdentifier":"c:objc(pl)AgoraMusicContentCenterEventDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/register(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerEventDelegate:"}],"url":"\/documentation\/agorartckit\/agoramusiccontentcenter\/register(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMusicContentCenter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMusicContentCenter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/createMusicPlayer(delegate:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/enableMainQueueDispatch(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getCaches()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getLyric(songCode:lyricType:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getMusicCharts()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/getMusicCollection(musicChartId:page:pageSize:jsonOption:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/isPreloaded(songCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/preload(songCode:jsonOption:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/register(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/removeCache(songCode:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/renewToken(_:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/searchMusic(keyWord:page:pageSize:jsonOption:)"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/destroy()","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicContentCenter\/sharedContentCenter(config:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicContentCenter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1removeCache(songCode:)\/title","value":"removeCacheWithSongCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1removeCache(songCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeCacheWithSongCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1sharedContentCenter(config:)\/title","value":"sharedContentCenterWithConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1sharedContentCenter(config:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedContentCenterWithConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1createMusicPlayer(delegate:)\/title","value":"createMusicPlayerWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1createMusicPlayer(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMusicPlayerWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter\/title","value":"AgoraMusicContentCenter"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter\/fragments","value":[{"kind":"identifier","text":"AgoraMusicContentCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getLyric(songCode:lyricType:)\/title","value":"getLyricWithSongCode:lyricType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getLyric(songCode:lyricType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLyricWithSongCode:lyricType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1destroy()\/title","value":"destroy"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1destroy()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"destroy"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getMusicCollection(musicChartId:page:pageSize:jsonOption:)\/title","value":"getMusicCollectionWithMusicChartId:page:pageSize:jsonOption:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getMusicCollection(musicChartId:page:pageSize:jsonOption:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMusicCollectionWithMusicChartId:page:pageSize:jsonOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1enableMainQueueDispatch(_:)\/title","value":"enableMainQueueDispatch:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1enableMainQueueDispatch(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableMainQueueDispatch:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1preload(songCode:jsonOption:)\/title","value":"preloadWithSongCode:jsonOption:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1preload(songCode:jsonOption:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preloadWithSongCode:jsonOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getMusicCharts()\/title","value":"getMusicCharts"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getMusicCharts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMusicCharts"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1isPreloaded(songCode:)\/title","value":"isPreloadedWithSongCode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1isPreloaded(songCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPreloadedWithSongCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1renewToken(_:)\/title","value":"renewToken:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1renewToken(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renewToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1searchMusic(keyWord:page:pageSize:jsonOption:)\/title","value":"searchMusicWithKeyWord:page:pageSize:jsonOption:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1searchMusic(keyWord:page:pageSize:jsonOption:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchMusicWithKeyWord:page:pageSize:jsonOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getCaches()\/title","value":"getCaches"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1getCaches()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCaches"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1register(_:)\/title","value":"registerEventDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicContentCenter~1register(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerEventDelegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}