{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoprofile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoprofile"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video profile."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"title":"AgoraVideoProfile","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoProfile","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfile"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape120P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape120P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1440P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1440P_2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_11","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_7","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape4K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape4K_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1440P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1440P_2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_11","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_7","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait4K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait4K_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_6"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/DEFAULT"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_6":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_6","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_6"}],"abstract":[{"type":"text","text":"35: 360 × 360, frame rate 30 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_6"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_6"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait480P_10":{"role":"symbol","title":"AgoraVideoProfile.portrait480P_10","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait480P_10"}],"abstract":[{"type":"text","text":"1049: 480 × 640, frame rate 10 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_10","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_10"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait480p_10"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_10":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_10","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_10"}],"abstract":[{"type":"text","text":"1039: 360 × 640, frame rate 24 fps, bitrate 800 Kbps.This profile applies only to the live streaming channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_10","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_10"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_10"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_3"}],"abstract":[{"type":"text","text":"32: 360 × 360, frame rate 15 fps, bitrate 260 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait4K":{"role":"symbol","title":"AgoraVideoProfile.portrait4K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait4K"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait4K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait4K"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait4k"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait180P_3":{"role":"symbol","title":"AgoraVideoProfile.portrait180P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait180P_3"}],"abstract":[{"type":"text","text":"1012: 180 × 180, frame rate 15 fps, bitrate 100 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait180P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait180p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape240P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape240P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape240P_3"}],"abstract":[{"type":"text","text":"22: 240 × 240, frame rate 15 fps, bitrate 140 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape240P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape240p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape4K_3":{"role":"symbol","title":"AgoraVideoProfile.landscape4K_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape4K_3"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape4K_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape4K_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape4k_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/invalid":{"role":"symbol","title":"AgoraVideoProfile.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"Invalid video attribute."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileInvalid"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/invalid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape1440P_2":{"role":"symbol","title":"AgoraVideoProfile.landscape1440P_2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1440P_2"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1440P_2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1440P_2"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape1440p_2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape1080P":{"role":"symbol","title":"AgoraVideoProfile.landscape1080P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1080P"}],"abstract":[{"type":"text","text":"60: 1920 × 1080, frame rate 15 fps, bitrate 2080 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape1080p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_11":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_11","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_11"}],"abstract":[{"type":"text","text":"1100: 360 × 640, frame rate 24 fps, bitrate 1000 Kbps.This profile applies only to the live streaming channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_11","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_11"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_11"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait720P_5":{"role":"symbol","title":"AgoraVideoProfile.portrait720P_5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait720P_5"}],"abstract":[{"type":"text","text":"1054: 720 × 960, frame rate 15 fps, bitrate 910 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P_5"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait720p_5"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait1080P":{"role":"symbol","title":"AgoraVideoProfile.portrait1080P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1080P"}],"abstract":[{"type":"text","text":"1060: 1080 × 1920, frame rate 15 fps, bitrate 2080 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait1080p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_7":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_7","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_7"}],"abstract":[{"type":"text","text":"1036: 360 × 480, frame rate 15 fps, bitrate 320 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_7"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_7"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape4K":{"role":"symbol","title":"AgoraVideoProfile.landscape4K","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape4K"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape4K","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape4K"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape4k"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape180P":{"role":"symbol","title":"AgoraVideoProfile.landscape180P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape180P"}],"abstract":[{"type":"text","text":"10: 320 × 180, frame rate 15 fps, bitrate 140 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape180P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape180p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape480P_6":{"role":"symbol","title":"AgoraVideoProfile.landscape480P_6","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape480P_6"}],"abstract":[{"type":"text","text":"45: 480 × 480, frame rate 30 fps, bitrate 600 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_6"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape480p_6"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait720P_3":{"role":"symbol","title":"AgoraVideoProfile.portrait720P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait720P_3"}],"abstract":[{"type":"text","text":"1052: 720 × 1280, frame rate 30 fps, bitrate 1710 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait720p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_9":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_9","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_9"}],"abstract":[{"type":"text","text":"1038: 360 × 640, frame rate 15 fps, bitrate 800 Kbps.This profile applies only to the live streaming channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_9","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_9"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_9"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait180P_4":{"role":"symbol","title":"AgoraVideoProfile.portrait180P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait180P_4"}],"abstract":[{"type":"text","text":"1013: 180 × 240, frame rate 15 fps, bitrate 120 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait180P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait180p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape720P_6":{"role":"symbol","title":"AgoraVideoProfile.landscape720P_6","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape720P_6"}],"abstract":[{"type":"text","text":"55: 960 × 720, frame rate 30 fps, bitrate 1380 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P_6"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape720p_6"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait480P_4":{"role":"symbol","title":"AgoraVideoProfile.portrait480P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait480P_4"}],"abstract":[{"type":"text","text":"1043: 480 × 640, frame rate 30 fps, bitrate 750 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait480p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait480P":{"role":"symbol","title":"AgoraVideoProfile.portrait480P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait480P"}],"abstract":[{"type":"text","text":"1040: 480 × 640, frame rate 15 fps, bitrate 500 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait480p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_11":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_11","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_11"}],"abstract":[{"type":"text","text":"100: 640 × 360, frame rate 24 fps, bitrate 1000 Kbps.This profile applies only to the live streaming channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_11","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_11"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_11"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape480P_10":{"role":"symbol","title":"AgoraVideoProfile.landscape480P_10","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape480P_10"}],"abstract":[{"type":"text","text":"49: 640 × 480, frame rate 10 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_10","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_10"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape480p_10"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait240P_4":{"role":"symbol","title":"AgoraVideoProfile.portrait240P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait240P_4"}],"abstract":[{"type":"text","text":"1023: 240 × 424, frame rate 15 fps, bitrate 220 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait240P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait240p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_3":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_3"}],"abstract":[{"type":"text","text":"1032: 360 × 360, frame rate 15 fps, bitrate 260 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_9":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_9","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_9"}],"abstract":[{"type":"text","text":"38: 640 × 360, frame rate 15 fps, bitrate 800 Kbps.This profile applies only to the live streaming channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_9","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_9"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_9"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait120P_3":{"role":"symbol","title":"AgoraVideoProfile.portrait120P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait120P_3"}],"abstract":[{"type":"text","text":"1002: 120 × 120, frame rate 15 fps, bitrate 50 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait120p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P":{"role":"symbol","title":"AgoraVideoProfile.landscape360P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P"}],"abstract":[{"type":"text","text":"30: 640 × 360, frame rate 15 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape180P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape180P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape180P_3"}],"abstract":[{"type":"text","text":"12: 180 × 180, frame rate 15 fps, bitrate 100 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape180P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape180p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape720P_5":{"role":"symbol","title":"AgoraVideoProfile.landscape720P_5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape720P_5"}],"abstract":[{"type":"text","text":"54: 960 × 720, frame rate 15 fps, bitrate 910 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P_5"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape720p_5"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape180P_4":{"role":"symbol","title":"AgoraVideoProfile.landscape180P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape180P_4"}],"abstract":[{"type":"text","text":"13: 240 × 180, frame rate 15 fps, bitrate 120 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape180P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape180p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait240P_3":{"role":"symbol","title":"AgoraVideoProfile.portrait240P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait240P_3"}],"abstract":[{"type":"text","text":"1022: 240 × 240, frame rate 15 fps, bitrate 140 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait240P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait240p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait480P_3":{"role":"symbol","title":"AgoraVideoProfile.portrait480P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait480P_3"}],"abstract":[{"type":"text","text":"1042: 480 × 480, frame rate 15 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait480p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape120P":{"role":"symbol","title":"AgoraVideoProfile.landscape120P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape120P"}],"abstract":[{"type":"text","text":"0: 160 × 120, frame rate 15 fps, bitrate 65 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape120P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape120P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape120p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape480P_4":{"role":"symbol","title":"AgoraVideoProfile.landscape480P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape480P_4"}],"abstract":[{"type":"text","text":"43: 640 × 480, frame rate 30 fps, bitrate 750 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape480p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait480P_9":{"role":"symbol","title":"AgoraVideoProfile.portrait480P_9","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait480P_9"}],"abstract":[{"type":"text","text":"1048: 480 × 848, frame rate 30 fps, bitrate 930 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_9","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_9"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait480p_9"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_6":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_6","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_6"}],"abstract":[{"type":"text","text":"1035: 360 × 360, frame rate 30 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_6"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_6"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait120P":{"role":"symbol","title":"AgoraVideoProfile.portrait120P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait120P"}],"abstract":[{"type":"text","text":"1000: 120 × 160, frame rate 15 fps, bitrate 65 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait120p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait1440P":{"role":"symbol","title":"AgoraVideoProfile.portrait1440P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1440P"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1440P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1440P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait1440p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait720P_6":{"role":"symbol","title":"AgoraVideoProfile.portrait720P_6","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait720P_6"}],"abstract":[{"type":"text","text":"1055: 720 × 960, frame rate 30 fps, bitrate 1380 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P_6"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait720p_6"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_4":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_4"}],"abstract":[{"type":"text","text":"33: 640 × 360, frame rate 30 fps, bitrate 600 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile":{"role":"symbol","title":"AgoraVideoProfile","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"}],"abstract":[{"type":"text","text":"Video profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfile"}],"url":"\/documentation\/agorartckit\/agoravideoprofile"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape480P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape480P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape480P_3"}],"abstract":[{"type":"text","text":"42: 480 × 480, frame rate 15 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape480p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait180P":{"role":"symbol","title":"AgoraVideoProfile.portrait180P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait180P"}],"abstract":[{"type":"text","text":"1010: 180 × 320, frame rate 15 fps, bitrate 140 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait180P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait180p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_4":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_4"}],"abstract":[{"type":"text","text":"1033: 360 × 640, frame rate 15 fps, bitrate 600 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait1440P_2":{"role":"symbol","title":"AgoraVideoProfile.portrait1440P_2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1440P_2"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1440P_2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1440P_2"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait1440p_2"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait480P_8":{"role":"symbol","title":"AgoraVideoProfile.portrait480P_8","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait480P_8"}],"abstract":[{"type":"text","text":"1047: 480 × 848, frame rate 15 fps, bitrate 610 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_8","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_8"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait480p_8"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait1080P_5":{"role":"symbol","title":"AgoraVideoProfile.portrait1080P_5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1080P_5"}],"abstract":[{"type":"text","text":"1064: 1080 × 1920, frame rate 60 fps, bitrate 4780 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_5"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait1080p_5"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape120P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape120P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape120P_3"}],"abstract":[{"type":"text","text":"2: 120 × 120, frame rate 15 fps, bitrate 50 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape120P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape120P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape120p_3"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape720P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape720P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape720P_3"}],"abstract":[{"type":"text","text":"52: 1280 × 720, frame rate 30 fps, bitrate 1710 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape720p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P_8":{"role":"symbol","title":"AgoraVideoProfile.portrait360P_8","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P_8"}],"abstract":[{"type":"text","text":"1037: 360 × 480, frame rate 30 fps, bitrate 490 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_8","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_8"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p_8"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideoprofile\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_7":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_7","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_7"}],"abstract":[{"type":"text","text":"36: 480 × 360, frame rate 15 fps, bitrate 320 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_7"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_7"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape1440P":{"role":"symbol","title":"AgoraVideoProfile.landscape1440P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1440P"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1440P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1440P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape1440p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_8":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_8","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_8"}],"abstract":[{"type":"text","text":"37: 480 × 360, frame rate 30 fps, bitrate 490 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_8","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_8"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_8"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape480P_9":{"role":"symbol","title":"AgoraVideoProfile.landscape480P_9","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape480P_9"}],"abstract":[{"type":"text","text":"48: 848 × 480, frame rate 30 fps, bitrate 930 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_9","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_9"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape480p_9"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait240P":{"role":"symbol","title":"AgoraVideoProfile.portrait240P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait240P"}],"abstract":[{"type":"text","text":"1020: 240 × 320, frame rate 15 fps, bitrate 200 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait240P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait240p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoprofile\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape480P_8":{"role":"symbol","title":"AgoraVideoProfile.landscape480P_8","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape480P_8"}],"abstract":[{"type":"text","text":"47: 848 × 480, frame rate 15 fps, bitrate 610 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_8","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_8"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape480p_8"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait360P":{"role":"symbol","title":"AgoraVideoProfile.portrait360P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait360P"}],"abstract":[{"type":"text","text":"1030: 360 × 640, frame rate 15 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait360p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait1080P_3":{"role":"symbol","title":"AgoraVideoProfile.portrait1080P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait1080P_3"}],"abstract":[{"type":"text","text":"1062: 1080 × 1920, frame rate 30 fps, bitrate 3150 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait1080p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape720P":{"role":"symbol","title":"AgoraVideoProfile.landscape720P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape720P"}],"abstract":[{"type":"text","text":"50: 1280 × 720, frame rate 15 fps, bitrate 1130 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape720p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape480P":{"role":"symbol","title":"AgoraVideoProfile.landscape480P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape480P"}],"abstract":[{"type":"text","text":"40: 640 × 480, frame rate 15 fps, bitrate 500 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape480p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape360P_10":{"role":"symbol","title":"AgoraVideoProfile.landscape360P_10","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape360P_10"}],"abstract":[{"type":"text","text":"39: 640 × 360, frame rate 24 fps, bitrate 800 Kbps.This profile applies only to the live streaming channel profile."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_10","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_10"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape360p_10"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait4K_3":{"role":"symbol","title":"AgoraVideoProfile.portrait4K_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait4K_3"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait4K_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait4K_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait4k_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait480P_6":{"role":"symbol","title":"AgoraVideoProfile.portrait480P_6","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait480P_6"}],"abstract":[{"type":"text","text":"1045: 480 × 480, frame rate 30 fps, bitrate 600 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_6","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_6"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait480p_6"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideoprofile\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/DEFAULT":{"role":"symbol","title":"DEFAULT","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoProfile","preciseIdentifier":"c:@E@AgoraVideoProfile"}],"abstract":[{"type":"text","text":"(Default) 640 × 360, frame rate 15 fps, bitrate 400 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/DEFAULT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileDEFAULT"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/default"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape240P_4":{"role":"symbol","title":"AgoraVideoProfile.landscape240P_4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape240P_4"}],"abstract":[{"type":"text","text":"23: 424 × 240, frame rate 15 fps, bitrate 220 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P_4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape240P_4"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape240p_4"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape240P":{"role":"symbol","title":"AgoraVideoProfile.landscape240P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape240P"}],"abstract":[{"type":"text","text":"20: 320 × 240, frame rate 15 fps, bitrate 200 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape240P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape240p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/portrait720P":{"role":"symbol","title":"AgoraVideoProfile.portrait720P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait720P"}],"abstract":[{"type":"text","text":"1050: 720 × 1280, frame rate 15 fps, bitrate 1130 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/portrait720p"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape1080P_3":{"role":"symbol","title":"AgoraVideoProfile.landscape1080P_3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1080P_3"}],"abstract":[{"type":"text","text":"60: 1920 × 1080, frame rate 30 fps, bitrate 3150 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_3"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape1080p_3"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoProfile/landscape1080P_5":{"role":"symbol","title":"AgoraVideoProfile.landscape1080P_5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape1080P_5"}],"abstract":[{"type":"text","text":"64: 1920 × 1080, frame rate 60 fps, bitrate 4780 Kbps."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_5"}],"url":"\/documentation\/agorartckit\/agoravideoprofile\/landscape1080p_5"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoProfile"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/DEFAULT","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1080P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape120P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape120P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1440P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape1440P_2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape180P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape240P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_11","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_7","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape360P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape480P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape4K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape4K_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/landscape720P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1080P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait120P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1440P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait1440P_2","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait180P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait240P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_11","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_7","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait360P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_10","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_4","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_6","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_8","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait480P_9","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait4K","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait4K_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_3","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_5","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoProfile\/portrait720P_6"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_6\/title","value":"AgoraVideoProfileLandscape360P_6"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_6\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_6"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_10\/title","value":"AgoraVideoProfilePortrait480P_10"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_10\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_10"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_10\/title","value":"AgoraVideoProfilePortrait360P_10"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_10\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_10"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_3\/title","value":"AgoraVideoProfileLandscape360P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait4K\/title","value":"AgoraVideoProfilePortrait4K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait4K\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait4K"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait180P_3\/title","value":"AgoraVideoProfilePortrait180P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait180P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait180P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape240P_3\/title","value":"AgoraVideoProfileLandscape240P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape240P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape240P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape4K_3\/title","value":"AgoraVideoProfileLandscape4K_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape4K_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape4K_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1invalid\/title","value":"AgoraVideoProfileInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1invalid\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1440P_2\/title","value":"AgoraVideoProfileLandscape1440P_2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1440P_2\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1440P_2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P\/title","value":"AgoraVideoProfileLandscape1080P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_11\/title","value":"AgoraVideoProfilePortrait360P_11"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_11\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_11"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P_5\/title","value":"AgoraVideoProfilePortrait720P_5"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P_5\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P_5"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P\/title","value":"AgoraVideoProfilePortrait1080P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_7\/title","value":"AgoraVideoProfilePortrait360P_7"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_7\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_7"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape4K\/title","value":"AgoraVideoProfileLandscape4K"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape4K\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape4K"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape180P\/title","value":"AgoraVideoProfileLandscape180P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape180P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape180P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_6\/title","value":"AgoraVideoProfileLandscape480P_6"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_6\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_6"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P_3\/title","value":"AgoraVideoProfilePortrait720P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_9\/title","value":"AgoraVideoProfilePortrait360P_9"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_9\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_9"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait180P_4\/title","value":"AgoraVideoProfilePortrait180P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait180P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait180P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P_6\/title","value":"AgoraVideoProfileLandscape720P_6"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P_6\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P_6"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_4\/title","value":"AgoraVideoProfilePortrait480P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P\/title","value":"AgoraVideoProfilePortrait480P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_11\/title","value":"AgoraVideoProfileLandscape360P_11"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_11\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_11"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_10\/title","value":"AgoraVideoProfileLandscape480P_10"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_10\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_10"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait240P_4\/title","value":"AgoraVideoProfilePortrait240P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait240P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait240P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_3\/title","value":"AgoraVideoProfilePortrait360P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_9\/title","value":"AgoraVideoProfileLandscape360P_9"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_9\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_9"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait120P_3\/title","value":"AgoraVideoProfilePortrait120P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait120P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P\/title","value":"AgoraVideoProfileLandscape360P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape180P_3\/title","value":"AgoraVideoProfileLandscape180P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape180P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape180P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P_5\/title","value":"AgoraVideoProfileLandscape720P_5"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P_5\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P_5"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape180P_4\/title","value":"AgoraVideoProfileLandscape180P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape180P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape180P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait240P_3\/title","value":"AgoraVideoProfilePortrait240P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait240P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait240P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_3\/title","value":"AgoraVideoProfilePortrait480P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape120P\/title","value":"AgoraVideoProfileLandscape120P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape120P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape120P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_4\/title","value":"AgoraVideoProfileLandscape480P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_9\/title","value":"AgoraVideoProfilePortrait480P_9"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_9\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_9"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_6\/title","value":"AgoraVideoProfilePortrait360P_6"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_6\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_6"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait120P\/title","value":"AgoraVideoProfilePortrait120P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait120P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait120P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1440P\/title","value":"AgoraVideoProfilePortrait1440P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1440P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1440P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P_6\/title","value":"AgoraVideoProfilePortrait720P_6"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P_6\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P_6"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_4\/title","value":"AgoraVideoProfileLandscape360P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/title","value":"AgoraVideoProfile"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_3\/title","value":"AgoraVideoProfileLandscape480P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait180P\/title","value":"AgoraVideoProfilePortrait180P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait180P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait180P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_4\/title","value":"AgoraVideoProfilePortrait360P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1440P_2\/title","value":"AgoraVideoProfilePortrait1440P_2"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1440P_2\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1440P_2"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_8\/title","value":"AgoraVideoProfilePortrait480P_8"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_8\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_8"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P_5\/title","value":"AgoraVideoProfilePortrait1080P_5"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P_5\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_5"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape120P_3\/title","value":"AgoraVideoProfileLandscape120P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape120P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape120P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P_3\/title","value":"AgoraVideoProfileLandscape720P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_8\/title","value":"AgoraVideoProfilePortrait360P_8"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P_8\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P_8"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_7\/title","value":"AgoraVideoProfileLandscape360P_7"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_7\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_7"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1440P\/title","value":"AgoraVideoProfileLandscape1440P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1440P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1440P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_8\/title","value":"AgoraVideoProfileLandscape360P_8"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_8\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_8"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_9\/title","value":"AgoraVideoProfileLandscape480P_9"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_9\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_9"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait240P\/title","value":"AgoraVideoProfilePortrait240P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait240P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait240P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_8\/title","value":"AgoraVideoProfileLandscape480P_8"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P_8\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P_8"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P\/title","value":"AgoraVideoProfilePortrait360P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait360P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait360P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P_3\/title","value":"AgoraVideoProfilePortrait1080P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait1080P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait1080P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P\/title","value":"AgoraVideoProfileLandscape720P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape720P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape720P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P\/title","value":"AgoraVideoProfileLandscape480P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape480P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape480P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_10\/title","value":"AgoraVideoProfileLandscape360P_10"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape360P_10\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape360P_10"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait4K_3\/title","value":"AgoraVideoProfilePortrait4K_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait4K_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait4K_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_6\/title","value":"AgoraVideoProfilePortrait480P_6"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait480P_6\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait480P_6"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1DEFAULT\/title","value":"AgoraVideoProfileDEFAULT"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1DEFAULT\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileDEFAULT"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape240P_4\/title","value":"AgoraVideoProfileLandscape240P_4"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape240P_4\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape240P_4"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape240P\/title","value":"AgoraVideoProfileLandscape240P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape240P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape240P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P\/title","value":"AgoraVideoProfilePortrait720P"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1portrait720P\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfilePortrait720P"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P_3\/title","value":"AgoraVideoProfileLandscape1080P_3"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P_3\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_3"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P_5\/title","value":"AgoraVideoProfileLandscape1080P_5"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoProfile~1landscape1080P_5\/fragments","value":[{"kind":"identifier","text":"AgoraVideoProfileLandscape1080P_5"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}