{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFramePosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioframeposition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioframeposition"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP","doc:\/\/AgoraRtcKit\/s9OptionSetP","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP","doc:\/\/AgoraRtcKit\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/beforeMixing","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/earMonitoring","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/mixed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/playback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/record"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/OptionSet-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/SetAlgebra-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFramePosition"}],"title":"AgoraAudioFramePosition","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@E@AgoraAudioFramePosition","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePosition"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/AgoraRtcKit\/s25ExpressibleByArrayLiteralP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/beforeMixing":{"role":"symbol","title":"beforeMixing","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"beforeMixing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/beforeMixing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePositionBeforeMixing"}],"url":"\/documentation\/agorartckit\/agoraaudioframeposition\/beforemixing"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/mixed":{"role":"symbol","title":"mixed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/mixed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePositionMixed"}],"url":"\/documentation\/agorartckit\/agoraaudioframeposition\/mixed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframeposition\/optionset-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/record":{"role":"symbol","title":"record","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"record"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/record","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePositionRecord"}],"url":"\/documentation\/agorartckit\/agoraaudioframeposition\/record"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/earMonitoring":{"role":"symbol","title":"earMonitoring","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"earMonitoring"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/earMonitoring","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePositionEarMonitoring"}],"url":"\/documentation\/agorartckit\/agoraaudioframeposition\/earmonitoring"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframeposition\/equatable-implementations"},"doc://AgoraRtcKit/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/AgoraRtcKit\/s10SetAlgebraP"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/AgoraRtcKit\/s9OptionSetP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition":{"role":"symbol","title":"AgoraAudioFramePosition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePosition"}],"url":"\/documentation\/agorartckit\/agoraaudioframeposition"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/playback":{"role":"symbol","title":"playback","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioFramePosition","preciseIdentifier":"c:@E@AgoraAudioFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/playback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFramePositionPlayback"}],"url":"\/documentation\/agorartckit\/agoraaudioframeposition\/playback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframeposition\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFramePosition/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioframeposition\/setalgebra-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioFramePosition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePosition"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioFramePosition"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/beforeMixing","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/earMonitoring","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/mixed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/playback","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFramePosition\/record"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFramePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1beforeMixing\/title","value":"AgoraAudioFramePositionBeforeMixing"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1beforeMixing\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePositionBeforeMixing"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1mixed\/title","value":"AgoraAudioFramePositionMixed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1mixed\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePositionMixed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1record\/title","value":"AgoraAudioFramePositionRecord"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1record\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePositionRecord"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1earMonitoring\/title","value":"AgoraAudioFramePositionEarMonitoring"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1earMonitoring\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePositionEarMonitoring"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition\/title","value":"AgoraAudioFramePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePosition"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1playback\/title","value":"AgoraAudioFramePositionPlayback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFramePosition~1playback\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFramePositionPlayback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}