{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelStats"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelstats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelstats"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Statistics of the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelStats"}],"title":"AgoraChannelStats","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraChannelStats","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraChannelStats"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/connectTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/cpuAppUsage","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/cpuTotalUsage","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/duration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstAudioPacketDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstVideoKeyFramePacketDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstVideoPacketDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/gatewayRtt","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/lastmileDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryAppUsageInKbytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryAppUsageRatio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryTotalUsageRatio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/packetsBeforeFirstKeyFramePacket","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxAudioBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxAudioKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxPacketLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxVideoBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxVideoKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txAudioBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txAudioKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txPacketLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txVideoBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txVideoKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/userCount"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats":{"role":"symbol","title":"AgoraChannelStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelStats"}],"abstract":[{"type":"text","text":"Statistics of the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelStats"}],"url":"\/documentation\/agorartckit\/agorachannelstats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/memoryTotalUsageRatio":{"role":"symbol","title":"memoryTotalUsageRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryTotalUsageRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The memory occupied by the system (%).This value is for reference only. Due"},{"type":"text","text":" "},{"type":"text","text":"to system limitations, you may not get this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryTotalUsageRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memoryTotalUsageRatio"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/memorytotalusageratio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/firstAudioPacketDuration":{"role":"symbol","title":"firstAudioPacketDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstAudioPacketDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstAudioPacketDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstAudioPacketDuration"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/firstaudiopacketduration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Call duration of the local user in seconds, represented by an aggregate"},{"type":"text","text":" "},{"type":"text","text":"value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/duration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/txAudioKBitrate":{"role":"symbol","title":"txAudioKBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txAudioKBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The bitrate (Kbps) of sending the audio packet."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txAudioKBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txAudioKBitrate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/txaudiokbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/txKBitrate":{"role":"symbol","title":"txKBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txKBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Video transmission bitrate (Kbps), represented by an instantaneous value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txKBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txKBitrate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/txkbitrate"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/packetsBeforeFirstKeyFramePacket":{"role":"symbol","title":"packetsBeforeFirstKeyFramePacket","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsBeforeFirstKeyFramePacket"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/packetsBeforeFirstKeyFramePacket","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"packetsBeforeFirstKeyFramePacket"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/packetsbeforefirstkeyframepacket"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/rxAudioKBitrate":{"role":"symbol","title":"rxAudioKBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxAudioKBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Audio receive bitrate (Kbps), represented by an instantaneous value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxAudioKBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxAudioKBitrate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/rxaudiokbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/lastmileDelay":{"role":"symbol","title":"lastmileDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastmileDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The client-to-server delay (ms)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/lastmileDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastmileDelay"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/lastmiledelay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/firstVideoPacketDuration":{"role":"symbol","title":"firstVideoPacketDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstVideoPacketDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstVideoPacketDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstVideoPacketDuration"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/firstvideopacketduration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/txPacketLossRate":{"role":"symbol","title":"txPacketLossRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txPacketLossRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The packet loss rate (%) from the client to the Agora server before applying"},{"type":"text","text":" "},{"type":"text","text":"the anti-packet-loss algorithm."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txPacketLossRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txPacketLossRate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/txpacketlossrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/rxAudioBytes":{"role":"symbol","title":"rxAudioBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxAudioBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The total number of audio bytes received, represented by an aggregate value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxAudioBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxAudioBytes"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/rxaudiobytes"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/rxVideoKBitrate":{"role":"symbol","title":"rxVideoKBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxVideoKBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Video receive bitrate (Kbps), represented by an instantaneous value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxVideoKBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxVideoKBitrate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/rxvideokbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/memoryAppUsageInKbytes":{"role":"symbol","title":"memoryAppUsageInKbytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryAppUsageInKbytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The memory size occupied by the app (KB).This value is for reference only."},{"type":"text","text":" "},{"type":"text","text":"Due to system limitations, you may not get this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryAppUsageInKbytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memoryAppUsageInKbytes"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/memoryappusageinkbytes"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/txVideoBytes":{"role":"symbol","title":"txVideoBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txVideoBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The total number of video bytes sent, represented by an aggregate value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txVideoBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txVideoBytes"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/txvideobytes"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/txAudioBytes":{"role":"symbol","title":"txAudioBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txAudioBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Total number of audio bytes sent, represented by an aggregate value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txAudioBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txAudioBytes"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/txaudiobytes"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/firstVideoKeyFramePacketDuration":{"role":"symbol","title":"firstVideoKeyFramePacketDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstVideoKeyFramePacketDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstVideoKeyFramePacketDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstVideoKeyFramePacketDuration"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/firstvideokeyframepacketduration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/connectTimeMs":{"role":"symbol","title":"connectTimeMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectTimeMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The duration (ms) between the SDK starts connecting and the connection is"},{"type":"text","text":" "},{"type":"text","text":"established. If the value reported is 0, it means invalid."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/connectTimeMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectTimeMs"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/connecttimems"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/rxKBitrate":{"role":"symbol","title":"rxKBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxKBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The receiving bitrate (Kbps), represented by an instantaneous value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxKBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxKBitrate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/rxkbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/cpuTotalUsage":{"role":"symbol","title":"cpuTotalUsage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpuTotalUsage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The system CPU usage (%).The value of cpuTotalUsage is always reported as 0"},{"type":"text","text":" "},{"type":"text","text":"in the didLeaveChannelWithStats callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/cpuTotalUsage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cpuTotalUsage"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/cputotalusage"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/txBytes":{"role":"symbol","title":"txBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Total number of bytes transmitted, represented by an aggregate value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txBytes"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/txbytes"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/rxVideoBytes":{"role":"symbol","title":"rxVideoBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxVideoBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The total number of video bytes received, represented by an aggregate value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxVideoBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxVideoBytes"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/rxvideobytes"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/cpuAppUsage":{"role":"symbol","title":"cpuAppUsage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpuAppUsage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Application CPU usage (%).The value of cpuTotalUsage is always reported as 0"},{"type":"text","text":" "},{"type":"text","text":"in the didLeaveChannelWithStats callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/cpuAppUsage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cpuAppUsage"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/cpuappusage"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/userCount":{"role":"symbol","title":"userCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The number of users in the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/userCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userCount"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/usercount"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/rxPacketLossRate":{"role":"symbol","title":"rxPacketLossRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxPacketLossRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The packet loss rate (%) from the Agora server to the client before using the"},{"type":"text","text":" "},{"type":"text","text":"anti-packet-loss method."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxPacketLossRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxPacketLossRate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/rxpacketlossrate"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/memoryAppUsageRatio":{"role":"symbol","title":"memoryAppUsageRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryAppUsageRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The memory ratio occupied by the app (%).This value is for reference only."},{"type":"text","text":" "},{"type":"text","text":"Due to system limitations, you may not get this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryAppUsageRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memoryAppUsageRatio"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/memoryappusageratio"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/txVideoKBitrate":{"role":"symbol","title":"txVideoKBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"txVideoKBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The bitrate (Kbps) of sending the video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txVideoKBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"txVideoKBitrate"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/txvideokbitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/rxBytes":{"role":"symbol","title":"rxBytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Total number of bytes received, represented by an aggregate value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxBytes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rxBytes"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/rxbytes"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/gatewayRtt":{"role":"symbol","title":"gatewayRtt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayRtt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The round-trip time delay (ms) from the client to the local router.This"},{"type":"text","text":" "},{"type":"text","text":"property is disabled on devices running iOS 14 or later, and enabled on"},{"type":"text","text":" "},{"type":"text","text":"devices running versions earlier than iOS 14 by default.To enable this"},{"type":"text","text":" "},{"type":"text","text":"property on devices running iOS 14 or later, ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/gatewayRtt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gatewayRtt"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/gatewayrtt"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraChannelStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraChannelStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraChannelStats"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/connectTimeMs","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/cpuAppUsage","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/cpuTotalUsage","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/duration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstAudioPacketDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstVideoKeyFramePacketDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/firstVideoPacketDuration","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/gatewayRtt","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/lastmileDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryAppUsageInKbytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryAppUsageRatio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/memoryTotalUsageRatio","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/packetsBeforeFirstKeyFramePacket","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxAudioBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxAudioKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxPacketLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxVideoBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/rxVideoKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txAudioBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txAudioKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txPacketLossRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txVideoBytes","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/txVideoKBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/userCount"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/title","value":"AgoraChannelStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/fragments","value":[{"kind":"identifier","text":"AgoraChannelStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1memoryTotalUsageRatio\/title","value":"memoryTotalUsageRatio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1memoryTotalUsageRatio\/fragments","value":[{"kind":"identifier","text":"memoryTotalUsageRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1firstAudioPacketDuration\/title","value":"firstAudioPacketDuration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1firstAudioPacketDuration\/fragments","value":[{"kind":"identifier","text":"firstAudioPacketDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txAudioKBitrate\/title","value":"txAudioKBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txAudioKBitrate\/fragments","value":[{"kind":"identifier","text":"txAudioKBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txKBitrate\/title","value":"txKBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txKBitrate\/fragments","value":[{"kind":"identifier","text":"txKBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1packetsBeforeFirstKeyFramePacket\/title","value":"packetsBeforeFirstKeyFramePacket"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1packetsBeforeFirstKeyFramePacket\/fragments","value":[{"kind":"identifier","text":"packetsBeforeFirstKeyFramePacket"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxAudioKBitrate\/title","value":"rxAudioKBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxAudioKBitrate\/fragments","value":[{"kind":"identifier","text":"rxAudioKBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1lastmileDelay\/title","value":"lastmileDelay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1lastmileDelay\/fragments","value":[{"kind":"identifier","text":"lastmileDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1firstVideoPacketDuration\/title","value":"firstVideoPacketDuration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1firstVideoPacketDuration\/fragments","value":[{"kind":"identifier","text":"firstVideoPacketDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txPacketLossRate\/title","value":"txPacketLossRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txPacketLossRate\/fragments","value":[{"kind":"identifier","text":"txPacketLossRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxAudioBytes\/title","value":"rxAudioBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxAudioBytes\/fragments","value":[{"kind":"identifier","text":"rxAudioBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxVideoKBitrate\/title","value":"rxVideoKBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxVideoKBitrate\/fragments","value":[{"kind":"identifier","text":"rxVideoKBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1memoryAppUsageInKbytes\/title","value":"memoryAppUsageInKbytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1memoryAppUsageInKbytes\/fragments","value":[{"kind":"identifier","text":"memoryAppUsageInKbytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txVideoBytes\/title","value":"txVideoBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txVideoBytes\/fragments","value":[{"kind":"identifier","text":"txVideoBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txAudioBytes\/title","value":"txAudioBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txAudioBytes\/fragments","value":[{"kind":"identifier","text":"txAudioBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1firstVideoKeyFramePacketDuration\/title","value":"firstVideoKeyFramePacketDuration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1firstVideoKeyFramePacketDuration\/fragments","value":[{"kind":"identifier","text":"firstVideoKeyFramePacketDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1connectTimeMs\/title","value":"connectTimeMs"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1connectTimeMs\/fragments","value":[{"kind":"identifier","text":"connectTimeMs"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxKBitrate\/title","value":"rxKBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxKBitrate\/fragments","value":[{"kind":"identifier","text":"rxKBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1cpuTotalUsage\/title","value":"cpuTotalUsage"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1cpuTotalUsage\/fragments","value":[{"kind":"identifier","text":"cpuTotalUsage"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txBytes\/title","value":"txBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txBytes\/fragments","value":[{"kind":"identifier","text":"txBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxVideoBytes\/title","value":"rxVideoBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxVideoBytes\/fragments","value":[{"kind":"identifier","text":"rxVideoBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1cpuAppUsage\/title","value":"cpuAppUsage"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1cpuAppUsage\/fragments","value":[{"kind":"identifier","text":"cpuAppUsage"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1userCount\/title","value":"userCount"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1userCount\/fragments","value":[{"kind":"identifier","text":"userCount"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxPacketLossRate\/title","value":"rxPacketLossRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxPacketLossRate\/fragments","value":[{"kind":"identifier","text":"rxPacketLossRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1memoryAppUsageRatio\/title","value":"memoryAppUsageRatio"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1memoryAppUsageRatio\/fragments","value":[{"kind":"identifier","text":"memoryAppUsageRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txVideoKBitrate\/title","value":"txVideoKBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1txVideoKBitrate\/fragments","value":[{"kind":"identifier","text":"txVideoKBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxBytes\/title","value":"rxBytes"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1rxBytes\/fragments","value":[{"kind":"identifier","text":"rxBytes"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1gatewayRtt\/title","value":"gatewayRtt"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1gatewayRtt\/fragments","value":[{"kind":"identifier","text":"gatewayRtt"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}