{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideodenoisermode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideodenoisermode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Video noise reduction mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"title":"AgoraVideoDenoiserMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraVideoDenoiserMode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/auto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/manual"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode/auto":{"role":"symbol","title":"AgoraVideoDenoiserMode.auto","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"abstract":[{"type":"text","text":"0: (Default) Automatic mode. The SDK automatically enables or disables the"},{"type":"text","text":" "},{"type":"text","text":"video noise reduction feature according to the ambient light."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/auto","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserModeAuto"}],"url":"\/documentation\/agorartckit\/agoravideodenoisermode\/auto"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideodenoisermode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoravideodenoisermode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode/manual":{"role":"symbol","title":"AgoraVideoDenoiserMode.manual","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}],"abstract":[{"type":"text","text":"1: Manual mode. Users need to enable or disable the video noise reduction"},{"type":"text","text":" "},{"type":"text","text":"feature manually."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/manual","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserModeManual"}],"url":"\/documentation\/agorartckit\/agoravideodenoisermode\/manual"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode":{"role":"symbol","title":"AgoraVideoDenoiserMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"abstract":[{"type":"text","text":"Video noise reduction mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}],"url":"\/documentation\/agorartckit\/agoravideodenoisermode"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoDenoiserMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoravideodenoisermode\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoDenoiserMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/auto","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoDenoiserMode\/manual"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoDenoiserMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1auto\/title","value":"AgoraVideoDenoiserModeAuto"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1auto\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserModeAuto"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1manual\/title","value":"AgoraVideoDenoiserModeManual"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode~1manual\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserModeManual"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode\/title","value":"AgoraVideoDenoiserMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoDenoiserMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoDenoiserMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}