{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudioreverbtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudioreverbtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio reverberation types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbType"}],"title":"AgoraAudioReverbType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioReverbType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/dryLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/roomSize","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/strength","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetLevel"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/equatable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/wetDelay":{"role":"symbol","title":"AgoraAudioReverbType.wetDelay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wetDelay"}],"abstract":[{"type":"text","text":"3: The length of the initial delay of the wet signal (ms). The value is"},{"type":"text","text":" "},{"type":"text","text":"between 0 and 200."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbWetDelay"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/wetdelay"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/roomSize":{"role":"symbol","title":"AgoraAudioReverbType.roomSize","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roomSize"}],"abstract":[{"type":"text","text":"2: The room size of the reflection. The value is between 0 and 100."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/roomSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbRoomSize"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/roomsize"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/dryLevel":{"role":"symbol","title":"AgoraAudioReverbType.dryLevel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dryLevel"}],"abstract":[{"type":"text","text":"0: The level of the dry signal (dB). The value is between -20 and 10."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/dryLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbDryLevel"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/drylevel"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType":{"role":"symbol","title":"AgoraAudioReverbType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbType"}],"abstract":[{"type":"text","text":"Audio reverberation types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbType"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/strength":{"role":"symbol","title":"AgoraAudioReverbType.strength","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"strength"}],"abstract":[{"type":"text","text":"4: The reverberation strength. The value is between 0 and 100."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/strength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbStrength"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/strength"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioReverbType/wetLevel":{"role":"symbol","title":"AgoraAudioReverbType.wetLevel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wetLevel"}],"abstract":[{"type":"text","text":"1: The level of the early reflection signal (wet signal) (dB). The value is"},{"type":"text","text":" "},{"type":"text","text":"between -20 and 10."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioReverbWetLevel"}],"url":"\/documentation\/agorartckit\/agoraaudioreverbtype\/wetlevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioReverbType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioReverbType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/dryLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/roomSize","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/strength","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetDelay","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioReverbType\/wetLevel"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioReverbType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1wetDelay\/title","value":"AgoraAudioReverbWetDelay"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1wetDelay\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbWetDelay"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1roomSize\/title","value":"AgoraAudioReverbRoomSize"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1roomSize\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbRoomSize"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1dryLevel\/title","value":"AgoraAudioReverbDryLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1dryLevel\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbDryLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/title","value":"AgoraAudioReverbType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1strength\/title","value":"AgoraAudioReverbStrength"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1strength\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbStrength"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1wetLevel\/title","value":"AgoraAudioReverbWetLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioReverbType~1wetLevel\/fragments","value":[{"kind":"identifier","text":"AgoraAudioReverbWetLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}