{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Local video state error codes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"title":"AgoraLocalVideoStreamError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraLocalVideoStreamError","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/OK","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceDisconnected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceInvalidId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureFailure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureInBackGround","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureMultipleForegroundApps","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureNoDeviceFound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceBusy","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceNoPermission","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/encodeFailure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/failure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureNoPermission","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureWindowClosed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureWindowMinimized"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureMultipleForegroundApps":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureMultipleForegroundApps","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMultipleForegroundApps"}],"abstract":[{"type":"text","text":"7: The current application window is running in Slide Over, Split View, or"},{"type":"text","text":" "},{"type":"text","text":"Picture in Picture mode, and another app is occupying the camera. Remind"},{"type":"text","text":" "},{"type":"text","text":"the user that the application cannot capture video properly when the app is"},{"type":"text","text":" "},{"type":"text","text":"running in Slide Over, Split View, or Picture in Picture mode and another"},{"type":"text","text":" "},{"type":"text","text":"app is occupying the camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureMultipleForegroundApps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureMultipleForegroundApps"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturemultipleforegroundapps"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureNoDeviceFound":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureNoDeviceFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureNoDeviceFound"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureNoDeviceFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureNoDeviceFound"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturenodevicefound"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/screenCaptureNoPermission":{"role":"symbol","title":"AgoraLocalVideoStreamError.screenCaptureNoPermission","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenCaptureNoPermission"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureNoPermission","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorScreenCaptureNoPermission"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/screencapturenopermission"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/failure":{"role":"symbol","title":"AgoraLocalVideoStreamError.failure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"abstract":[{"type":"text","text":"1: No specified reason for the local video failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/failure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorFailure"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/failure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureInBackGround":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureInBackGround","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureInBackGround"}],"abstract":[{"type":"text","text":"6:The app is in the background. Remind the user that video capture cannot"},{"type":"text","text":" "},{"type":"text","text":"be performed normally when the app is in the background."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureInBackGround","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureInBackGround"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/captureinbackground"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureDeviceInvalidId":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureDeviceInvalidId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDeviceInvalidId"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceInvalidId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceInvalidId"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturedeviceinvalidid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError":{"role":"symbol","title":"AgoraLocalVideoStreamError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"abstract":[{"type":"text","text":"Local video state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/deviceBusy":{"role":"symbol","title":"AgoraLocalVideoStreamError.deviceBusy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceBusy"}],"abstract":[{"type":"text","text":"3: The local video capturing device is in use. Remind the user to check"},{"type":"text","text":" "},{"type":"text","text":"whether another application occupies the camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceBusy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceBusy"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/devicebusy"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/OK":{"role":"symbol","title":"AgoraLocalVideoStreamError.OK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"abstract":[{"type":"text","text":"0: The local video is normal."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/OK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorOK"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/ok"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureFailure":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureFailure"}],"abstract":[{"type":"text","text":"4: The local video capture fails. Remind your user to check whether the"},{"type":"text","text":" "},{"type":"text","text":"video capture device is working properly, whether the camera is occupied by"},{"type":"text","text":" "},{"type":"text","text":"another application, or try to rejoin the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureFailure"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturefailure"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/screenCaptureWindowClosed":{"role":"symbol","title":"AgoraLocalVideoStreamError.screenCaptureWindowClosed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenCaptureWindowClosed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureWindowClosed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorScreenCaptureWindowClosed"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/screencapturewindowclosed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureDeviceDisconnected":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureDeviceDisconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDeviceDisconnected"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceDisconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturedevicedisconnected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/screenCaptureWindowMinimized":{"role":"symbol","title":"AgoraLocalVideoStreamError.screenCaptureWindowMinimized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenCaptureWindowMinimized"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureWindowMinimized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorScreenCaptureWindowMinimized"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/screencapturewindowminimized"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/encodeFailure":{"role":"symbol","title":"AgoraLocalVideoStreamError.encodeFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeFailure"}],"abstract":[{"type":"text","text":"5: The local video encoding fails."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/encodeFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorEncodeFailure"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/encodefailure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/deviceNoPermission":{"role":"symbol","title":"AgoraLocalVideoStreamError.deviceNoPermission","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNoPermission"}],"abstract":[{"type":"text","text":"2: No permission to use the local video capturing device. Remind the user"},{"type":"text","text":" "},{"type":"text","text":"to grant permissions and rejoin the channel.Deprecated:This enumerator is"},{"type":"text","text":" "},{"type":"text","text":"deprecated. Please use AgoraPermissionTypeCamera in the permissionError"},{"type":"text","text":" "},{"type":"text","text":"callback instead."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceNoPermission","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceNoPermission"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/devicenopermission"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalVideoStreamError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/OK","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceDisconnected","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceInvalidId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureFailure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureInBackGround","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureMultipleForegroundApps","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureNoDeviceFound","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceBusy","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceNoPermission","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/encodeFailure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/failure","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureNoPermission","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureWindowClosed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/screenCaptureWindowMinimized"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureMultipleForegroundApps\/title","value":"AgoraLocalVideoStreamErrorCaptureMultipleForegroundApps"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureMultipleForegroundApps\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureMultipleForegroundApps"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureNoDeviceFound\/title","value":"AgoraLocalVideoStreamErrorCaptureNoDeviceFound"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureNoDeviceFound\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureNoDeviceFound"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1screenCaptureNoPermission\/title","value":"AgoraLocalVideoStreamErrorScreenCaptureNoPermission"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1screenCaptureNoPermission\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorScreenCaptureNoPermission"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1failure\/title","value":"AgoraLocalVideoStreamErrorFailure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1failure\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureInBackGround\/title","value":"AgoraLocalVideoStreamErrorCaptureInBackGround"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureInBackGround\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureInBackGround"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureDeviceInvalidId\/title","value":"AgoraLocalVideoStreamErrorCaptureDeviceInvalidId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureDeviceInvalidId\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceInvalidId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/title","value":"AgoraLocalVideoStreamError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1deviceBusy\/title","value":"AgoraLocalVideoStreamErrorDeviceBusy"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1deviceBusy\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceBusy"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1OK\/title","value":"AgoraLocalVideoStreamErrorOK"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1OK\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorOK"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureFailure\/title","value":"AgoraLocalVideoStreamErrorCaptureFailure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureFailure\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1screenCaptureWindowClosed\/title","value":"AgoraLocalVideoStreamErrorScreenCaptureWindowClosed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1screenCaptureWindowClosed\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorScreenCaptureWindowClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureDeviceDisconnected\/title","value":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureDeviceDisconnected\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1screenCaptureWindowMinimized\/title","value":"AgoraLocalVideoStreamErrorScreenCaptureWindowMinimized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1screenCaptureWindowMinimized\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorScreenCaptureWindowMinimized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1encodeFailure\/title","value":"AgoraLocalVideoStreamErrorEncodeFailure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1encodeFailure\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorEncodeFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1deviceNoPermission\/title","value":"AgoraLocalVideoStreamErrorDeviceNoPermission"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1deviceNoPermission\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceNoPermission"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}