{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraliveinjectstreamconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraliveinjectstreamconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/size","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoFramerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoGop"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/defaultConfig()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}],"title":"AgoraLiveInjectStreamConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraLiveInjectStreamConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/audioBitrate":{"role":"symbol","title":"audioBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioBitrate"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/audiobitrate"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/defaultConfig()":{"role":"symbol","title":"defaultConfig()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfig"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraLiveInjectStreamConfig","preciseIdentifier":"c:objc(cs)AgoraLiveInjectStreamConfig"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/defaultConfig()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultConfig"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/defaultconfig()"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig":{"role":"symbol","title":"AgoraLiveInjectStreamConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/videoBitrate":{"role":"symbol","title":"videoBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoBitrate"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/videobitrate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/videoGop":{"role":"symbol","title":"videoGop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoGop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoGop","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoGop"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/videogop"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/audioChannels":{"role":"symbol","title":"audioChannels","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioChannels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioChannels"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/audiochannels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/audioSampleRate":{"role":"symbol","title":"audioSampleRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraAudioSampleRateType","preciseIdentifier":"c:@E@AgoraAudioSampleRateType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioSampleRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioSampleRate"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/audiosamplerate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/size"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLiveInjectStreamConfig/videoFramerate":{"role":"symbol","title":"videoFramerate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFramerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoFramerate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoFramerate"}],"url":"\/documentation\/agorartckit\/agoraliveinjectstreamconfig\/videoframerate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLiveInjectStreamConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioChannels","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/audioSampleRate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/size","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoBitrate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoFramerate","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/videoGop"]},{"title":"Type Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLiveInjectStreamConfig\/defaultConfig()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1audioBitrate\/title","value":"audioBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1audioBitrate\/fragments","value":[{"kind":"identifier","text":"audioBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1defaultConfig()\/title","value":"defaultConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1defaultConfig()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig\/title","value":"AgoraLiveInjectStreamConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLiveInjectStreamConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1videoBitrate\/title","value":"videoBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1videoBitrate\/fragments","value":[{"kind":"identifier","text":"videoBitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1videoGop\/title","value":"videoGop"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1videoGop\/fragments","value":[{"kind":"identifier","text":"videoGop"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1audioChannels\/title","value":"audioChannels"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1audioChannels\/fragments","value":[{"kind":"identifier","text":"audioChannels"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1audioSampleRate\/title","value":"audioSampleRate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1audioSampleRate\/fragments","value":[{"kind":"identifier","text":"audioSampleRate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1videoFramerate\/title","value":"videoFramerate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLiveInjectStreamConfig~1videoFramerate\/fragments","value":[{"kind":"identifier","text":"videoFramerate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}