{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclientconnectionchangereason"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedBannedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedChangedLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChanged","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChangedByUser","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedConnecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedEchoTest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInterrupted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidAppId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidChannelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedJoinFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedJoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedKeepAliveTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedLeaveChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRejectedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRejoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRenewToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedSameUidLogin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedSettingProxyServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTooManyBroadcasters"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"title":"AgoraRtmClientConnectionChangeReason","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraRtmClientConnectionChangeReason","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedRejoinSuccess":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedRejoinSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedRejoinSuccess"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRejoinSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedRejoinSuccess"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedrejoinsuccess"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedConnecting":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedConnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedConnecting"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedConnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedConnecting"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedconnecting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedInterrupted":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedInterrupted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedInterrupted"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInterrupted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInterrupted"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedinterrupted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedClientIpAddressChanged":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedClientIpAddressChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedClientIpAddressChanged"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChanged","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChanged"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedclientipaddresschanged"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedClientIpAddressChangedByUser":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedClientIpAddressChangedByUser","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedClientIpAddressChangedByUser"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChangedByUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedclientipaddresschangedbyuser"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedInvalidChannelName":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedInvalidChannelName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedInvalidChannelName"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidChannelName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidChannelName"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedinvalidchannelname"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedBannedByServer":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedBannedByServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedBannedByServer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedBannedByServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedBannedByServer"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedbannedbyserver"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedRejectedByServer":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedRejectedByServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedRejectedByServer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRejectedByServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedRejectedByServer"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedrejectedbyserver"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedSettingProxyServer":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedSettingProxyServer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedSettingProxyServer"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedSettingProxyServer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedSettingProxyServer"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedsettingproxyserver"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedRenewToken":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedRenewToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedRenewToken"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRenewToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedRenewToken"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedrenewtoken"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedEchoTest":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedEchoTest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedEchoTest"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedEchoTest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedEchoTest"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedechotest"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedKeepAliveTimeout":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedKeepAliveTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedKeepAliveTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedKeepAliveTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedKeepAliveTimeout"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedkeepalivetimeout"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedTokenExpired":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedTokenExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedTokenExpired"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTokenExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTokenExpired"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedtokenexpired"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedLeaveChannel":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedLeaveChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedLeaveChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedLeaveChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedLeaveChannel"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedleavechannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedTooManyBroadcasters":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedTooManyBroadcasters","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedTooManyBroadcasters"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTooManyBroadcasters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTooManyBroadcasters"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedtoomanybroadcasters"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedJoinSuccess":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedJoinSuccess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedJoinSuccess"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedJoinSuccess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedJoinSuccess"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedjoinsuccess"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedInvalidToken":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedInvalidToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedInvalidToken"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidToken"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedinvalidtoken"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedInvalidAppId":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedInvalidAppId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedInvalidAppId"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidAppId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidAppId"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedinvalidappid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedChangedLost":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedChangedLost","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedChangedLost"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedChangedLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedChangedLost"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedchangedlost"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedJoinFailed":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedJoinFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedJoinFailed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedJoinFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedJoinFailed"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedjoinfailed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/changedSameUidLogin":{"role":"symbol","title":"AgoraRtmClientConnectionChangeReason.changedSameUidLogin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"changedSameUidLogin"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedSameUidLogin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedSameUidLogin"}],"url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/changedsameuidlogin"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientConnectionChangeReason/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorartmclientconnectionchangereason\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmClientConnectionChangeReason"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedBannedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedChangedLost","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChanged","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedClientIpAddressChangedByUser","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedConnecting","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedEchoTest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInterrupted","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidAppId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidChannelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedInvalidToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedJoinFailed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedJoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedKeepAliveTimeout","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedLeaveChannel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRejectedByServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRejoinSuccess","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedRenewToken","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedSameUidLogin","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedSettingProxyServer","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTokenExpired","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientConnectionChangeReason\/changedTooManyBroadcasters"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/title","value":"AgoraRtmClientConnectionChangeReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangeReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedRejoinSuccess\/title","value":"AgoraRtmClientConnectionChangedRejoinSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedRejoinSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedRejoinSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedConnecting\/title","value":"AgoraRtmClientConnectionChangedConnecting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedConnecting\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInterrupted\/title","value":"AgoraRtmClientConnectionChangedInterrupted"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInterrupted\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInterrupted"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedClientIpAddressChanged\/title","value":"AgoraRtmClientConnectionChangedClientIpAddressChanged"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedClientIpAddressChanged\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedClientIpAddressChangedByUser\/title","value":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedClientIpAddressChangedByUser\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedClientIpAddressChangedByUser"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidChannelName\/title","value":"AgoraRtmClientConnectionChangedInvalidChannelName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidChannelName\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidChannelName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedBannedByServer\/title","value":"AgoraRtmClientConnectionChangedBannedByServer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedBannedByServer\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedBannedByServer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedRejectedByServer\/title","value":"AgoraRtmClientConnectionChangedRejectedByServer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedRejectedByServer\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedRejectedByServer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedSettingProxyServer\/title","value":"AgoraRtmClientConnectionChangedSettingProxyServer"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedSettingProxyServer\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedSettingProxyServer"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedRenewToken\/title","value":"AgoraRtmClientConnectionChangedRenewToken"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedRenewToken\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedRenewToken"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedEchoTest\/title","value":"AgoraRtmClientConnectionChangedEchoTest"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedEchoTest\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedEchoTest"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedKeepAliveTimeout\/title","value":"AgoraRtmClientConnectionChangedKeepAliveTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedKeepAliveTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedKeepAliveTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedTokenExpired\/title","value":"AgoraRtmClientConnectionChangedTokenExpired"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedTokenExpired\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTokenExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedLeaveChannel\/title","value":"AgoraRtmClientConnectionChangedLeaveChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedLeaveChannel\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedLeaveChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedTooManyBroadcasters\/title","value":"AgoraRtmClientConnectionChangedTooManyBroadcasters"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedTooManyBroadcasters\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedTooManyBroadcasters"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedJoinSuccess\/title","value":"AgoraRtmClientConnectionChangedJoinSuccess"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedJoinSuccess\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedJoinSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidToken\/title","value":"AgoraRtmClientConnectionChangedInvalidToken"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidToken\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidToken"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidAppId\/title","value":"AgoraRtmClientConnectionChangedInvalidAppId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedInvalidAppId\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedInvalidAppId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedChangedLost\/title","value":"AgoraRtmClientConnectionChangedChangedLost"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedChangedLost\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedChangedLost"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedJoinFailed\/title","value":"AgoraRtmClientConnectionChangedJoinFailed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedJoinFailed\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedJoinFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedSameUidLogin\/title","value":"AgoraRtmClientConnectionChangedSameUidLogin"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientConnectionChangeReason~1changedSameUidLogin\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientConnectionChangedSameUidLogin"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}