{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiofilerecordingtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiofilerecordingtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Recording content. Set in startAudioRecording [2\/2]."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"title":"AgoraAudioFileRecordingType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraAudioFileRecordingType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/mic","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/mixed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/playback"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType":{"role":"symbol","title":"AgoraAudioFileRecordingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"abstract":[{"type":"text","text":"Recording content. Set in startAudioRecording [2\/2]."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}],"url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType/mic":{"role":"symbol","title":"AgoraAudioFileRecordingType.mic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mic"}],"abstract":[{"type":"text","text":"1: Only records the audio of the local user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/mic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypeMic"}],"url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/mic"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType/mixed":{"role":"symbol","title":"AgoraAudioFileRecordingType.mixed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixed"}],"abstract":[{"type":"text","text":"3: Records the mixed audio of the local and all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/mixed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypeMixed"}],"url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/mixed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType/playback":{"role":"symbol","title":"AgoraAudioFileRecordingType.playback","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playback"}],"abstract":[{"type":"text","text":"2: Only records the audio of all remote users."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/playback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypePlayback"}],"url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/playback"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioFileRecordingType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoraaudiofilerecordingtype\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioFileRecordingType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/mic","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/mixed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioFileRecordingType\/playback"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioFileRecordingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType\/title","value":"AgoraAudioFileRecordingType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1mic\/title","value":"AgoraAudioFileRecordingTypeMic"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1mic\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypeMic"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1mixed\/title","value":"AgoraAudioFileRecordingTypeMixed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1mixed\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypeMixed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1playback\/title","value":"AgoraAudioFileRecordingTypePlayback"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioFileRecordingType~1playback\/fragments","value":[{"kind":"identifier","text":"AgoraAudioFileRecordingTypePlayback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}