{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramediafiltereventdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramediafiltereventdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Extension event callback interface class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}],"title":"AgoraMediaFilterEventDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AgoraMediaFilterEventDelegate","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onEvent(_:extension:key:value:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionError(_:extension:error:message:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionStarted(_:extension:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionStopped(_:extension:)"]}],"references":{"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaFilterEventDelegate/onExtensionStopped(_:extension:)":{"role":"symbol","title":"onExtensionStopped(_:extension:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtensionStopped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the extension is enabled."},{"type":"text","text":" "},{"type":"text","text":"After a successful call of enableExtensionWithVendor (YES), the extension"},{"type":"text","text":" "},{"type":"text","text":"triggers this callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionStopped(_:extension:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onExtensionStopped:extension:"}],"url":"\/documentation\/agorartckit\/agoramediafiltereventdelegate\/onextensionstopped(_:extension:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaFilterEventDelegate":{"role":"symbol","title":"AgoraMediaFilterEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}],"abstract":[{"type":"text","text":"Extension event callback interface class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}],"url":"\/documentation\/agorartckit\/agoramediafiltereventdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaFilterEventDelegate/onEvent(_:extension:key:value:)":{"role":"symbol","title":"onEvent(_:extension:key:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onEvent(_:extension:key:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onEvent:extension:key:value:"}],"url":"\/documentation\/agorartckit\/agoramediafiltereventdelegate\/onevent(_:extension:key:value:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaFilterEventDelegate/onExtensionError(_:extension:error:message:)":{"role":"symbol","title":"onExtensionError(_:extension:error:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtensionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the extension runs incorrectly."},{"type":"text","text":" "},{"type":"text","text":"When calling enableExtensionWithVendor (YES) fails or the extension runs in"},{"type":"text","text":" "},{"type":"text","text":"error, the extension triggers this callback and reports the error code and"},{"type":"text","text":" "},{"type":"text","text":"reason."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionError(_:extension:error:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onExtensionError:extension:error:message:"}],"url":"\/documentation\/agorartckit\/agoramediafiltereventdelegate\/onextensionerror(_:extension:error:message:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMediaFilterEventDelegate/onExtensionStarted(_:extension:)":{"navigatorTitle":[{"kind":"identifier","text":"onExtensionStarted:extension:"}],"role":"symbol","title":"onExtensionStarted(_:extension:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtensionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the extension is enabled."},{"type":"text","text":" "},{"type":"text","text":"After a successful call of enableExtensionWithVendor (YES), the extension"},{"type":"text","text":" "},{"type":"text","text":"triggers this callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionStarted(_:extension:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoramediafiltereventdelegate\/onextensionstarted(_:extension:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AgoraMediaFilterEventDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onEvent(_:extension:key:value:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionError(_:extension:error:message:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionStarted(_:extension:)","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMediaFilterEventDelegate\/onExtensionStopped(_:extension:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onExtensionStopped(_:extension:)\/title","value":"onExtensionStopped:extension:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onExtensionStopped(_:extension:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtensionStopped:extension:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate\/title","value":"AgoraMediaFilterEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraMediaFilterEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onEvent(_:extension:key:value:)\/title","value":"onEvent:extension:key:value:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onEvent(_:extension:key:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onEvent:extension:key:value:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onExtensionError(_:extension:error:message:)\/title","value":"onExtensionError:extension:error:message:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onExtensionError(_:extension:error:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtensionError:extension:error:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onExtensionStarted(_:extension:)\/title","value":"onExtensionStarted:extension:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMediaFilterEventDelegate~1onExtensionStarted(_:extension:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtensionStarted:extension:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}