{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiospectruminfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiospectruminfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio spectrum information of the remote user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}],"title":"AgoraAudioSpectrumInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraAudioSpectrumInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo\/audioSpectrumData","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo\/uid"]}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumInfo/audioSpectrumData":{"role":"symbol","title":"audioSpectrumData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioSpectrumData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Audio spectrum information of the remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo\/audioSpectrumData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioSpectrumData"}],"url":"\/documentation\/agorartckit\/agoraaudiospectruminfo\/audiospectrumdata"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumInfo/uid":{"role":"symbol","title":"uid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The user ID of the remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo\/uid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uid"}],"url":"\/documentation\/agorartckit\/agoraaudiospectruminfo\/uid"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioSpectrumInfo":{"role":"symbol","title":"AgoraAudioSpectrumInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}],"abstract":[{"type":"text","text":"Audio spectrum information of the remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}],"url":"\/documentation\/agorartckit\/agoraaudiospectruminfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioSpectrumInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo\/audioSpectrumData","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioSpectrumInfo\/uid"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioSpectrumInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumInfo~1audioSpectrumData\/title","value":"audioSpectrumData"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumInfo~1audioSpectrumData\/fragments","value":[{"kind":"identifier","text":"audioSpectrumData"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumInfo~1uid\/title","value":"uid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumInfo~1uid\/fragments","value":[{"kind":"identifier","text":"uid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumInfo\/title","value":"AgoraAudioSpectrumInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioSpectrumInfo\/fragments","value":[{"kind":"identifier","text":"AgoraAudioSpectrumInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}