{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmPresenceEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpresenceevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpresenceevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/channelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/channelType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/topicInfos","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/type","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/userId"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmPresenceEvent"}],"title":"AgoraRtmPresenceEvent","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraRtmPresenceEvent","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceEvent"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent/channelType":{"role":"symbol","title":"channelType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmChannelType","preciseIdentifier":"c:@E@AgoraRtmChannelType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/channelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelType"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent\/channeltype"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmPresenceType","preciseIdentifier":"c:@E@AgoraRtmPresenceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent\/type"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent/channelName":{"role":"symbol","title":"channelName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/channelName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelName"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent\/channelname"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent":{"role":"symbol","title":"AgoraRtmPresenceEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmPresenceEvent"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceEvent"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent/userId":{"role":"symbol","title":"userId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/userId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userId"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent\/userid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceEvent/topicInfos":{"role":"symbol","title":"topicInfos","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicInfos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AgoraRtmTopicInfo","preciseIdentifier":"c:objc(cs)AgoraRtmTopicInfo"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/topicInfos","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"topicInfos"}],"url":"\/documentation\/agorartckit\/agorartmpresenceevent\/topicinfos"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmPresenceEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtmPresenceEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/channelName","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/channelType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/topicInfos","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/type","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceEvent\/userId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmPresenceEvent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1channelType\/title","value":"channelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1channelType\/fragments","value":[{"kind":"identifier","text":"channelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1channelName\/title","value":"channelName"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1channelName\/fragments","value":[{"kind":"identifier","text":"channelName"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent\/title","value":"AgoraRtmPresenceEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1userId\/title","value":"userId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1userId\/fragments","value":[{"kind":"identifier","text":"userId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1topicInfos\/title","value":"topicInfos"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceEvent~1topicInfos\/fragments","value":[{"kind":"identifier","text":"topicInfos"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}