{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreamfallbackoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreamfallbackoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/audioOnly","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/disabled","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/videoStreamLow"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"title":"AgoraStreamFallbackOptions","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraStreamFallbackOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/videoStreamLow":{"role":"symbol","title":"AgoraStreamFallbackOptions.videoStreamLow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoStreamLow"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/videoStreamLow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptionVideoStreamLow"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/videostreamlow"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/equatable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/disabled":{"role":"symbol","title":"AgoraStreamFallbackOptions.disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/disabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptionDisabled"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/disabled"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions":{"role":"symbol","title":"AgoraStreamFallbackOptions","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamFallbackOptions/audioOnly":{"role":"symbol","title":"AgoraStreamFallbackOptions.audioOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOnly"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/audioOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamFallbackOptionAudioOnly"}],"url":"\/documentation\/agorartckit\/agorastreamfallbackoptions\/audioonly"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamFallbackOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/audioOnly","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/disabled","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamFallbackOptions\/videoStreamLow"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamFallbackOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1videoStreamLow\/title","value":"AgoraStreamFallbackOptionVideoStreamLow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1videoStreamLow\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptionVideoStreamLow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1disabled\/title","value":"AgoraStreamFallbackOptionDisabled"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1disabled\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptionDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions\/title","value":"AgoraStreamFallbackOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1audioOnly\/title","value":"AgoraStreamFallbackOptionAudioOnly"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamFallbackOptions~1audioOnly\/fragments","value":[{"kind":"identifier","text":"AgoraStreamFallbackOptionAudioOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}