{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorascreencapturesourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorascreencapturesourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/custom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/screen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/unknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/window"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}],"title":"AgoraScreenCaptureSourceType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraScreenCaptureSourceType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/custom":{"role":"symbol","title":"AgoraScreenCaptureSourceType.custom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/custom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeCustom"}],"url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/custom"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType":{"role":"symbol","title":"AgoraScreenCaptureSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}],"url":"\/documentation\/agorartckit\/agorascreencapturesourcetype"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/screen":{"role":"symbol","title":"AgoraScreenCaptureSourceType.screen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"screen"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/screen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeScreen"}],"url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/screen"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/equatable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/window":{"role":"symbol","title":"AgoraScreenCaptureSourceType.window","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"window"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/window","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeWindow"}],"url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/window"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraScreenCaptureSourceType/unknown":{"role":"symbol","title":"AgoraScreenCaptureSourceType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeUnknown"}],"url":"\/documentation\/agorartckit\/agorascreencapturesourcetype\/unknown"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraScreenCaptureSourceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/custom","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/screen","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/unknown","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraScreenCaptureSourceType\/window"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraScreenCaptureSourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1custom\/title","value":"AgoraScreenCaptureSourceTypeCustom"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1custom\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeCustom"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType\/title","value":"AgoraScreenCaptureSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1screen\/title","value":"AgoraScreenCaptureSourceTypeScreen"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1screen\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1window\/title","value":"AgoraScreenCaptureSourceTypeWindow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1window\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeWindow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1unknown\/title","value":"AgoraScreenCaptureSourceTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraScreenCaptureSourceType~1unknown\/fragments","value":[{"kind":"identifier","text":"AgoraScreenCaptureSourceTypeUnknown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}