{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraTranscodingVideoStream"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoratranscodingvideostream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoratranscodingvideostream"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/alpha","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/imageUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/mediaPlayerId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/mirror","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/rect","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/remoteUserUid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/sourceType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/zOrder"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraTranscodingVideoStream"}],"title":"AgoraTranscodingVideoStream","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraTranscodingVideoStream","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraTranscodingVideoStream"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/mirror":{"role":"symbol","title":"mirror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/mirror","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mirror"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/mirror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/alpha":{"role":"symbol","title":"alpha","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alpha"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/alpha","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"alpha"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/alpha"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/zOrder":{"role":"symbol","title":"zOrder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/zOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"zOrder"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/zorder"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/rect":{"role":"symbol","title":"rect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/rect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rect"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/rect"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream":{"role":"symbol","title":"AgoraTranscodingVideoStream","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraTranscodingVideoStream"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraTranscodingVideoStream"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/remoteUserUid":{"role":"symbol","title":"remoteUserUid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUserUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/remoteUserUid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remoteUserUid"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/remoteuseruid"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/imageUrl":{"role":"symbol","title":"imageUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/imageUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageUrl"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/imageurl"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/mediaPlayerId":{"role":"symbol","title":"mediaPlayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaPlayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/mediaPlayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaPlayerId"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/mediaplayerid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraTranscodingVideoStream/sourceType":{"role":"symbol","title":"sourceType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/sourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sourceType"}],"url":"\/documentation\/agorartckit\/agoratranscodingvideostream\/sourcetype"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraTranscodingVideoStream"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraTranscodingVideoStream"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraTranscodingVideoStream"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/alpha","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/imageUrl","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/mediaPlayerId","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/mirror","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/rect","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/remoteUserUid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/sourceType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraTranscodingVideoStream\/zOrder"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraTranscodingVideoStream"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1mirror\/title","value":"mirror"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1mirror\/fragments","value":[{"kind":"identifier","text":"mirror"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1alpha\/title","value":"alpha"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1alpha\/fragments","value":[{"kind":"identifier","text":"alpha"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1zOrder\/title","value":"zOrder"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1zOrder\/fragments","value":[{"kind":"identifier","text":"zOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1rect\/title","value":"rect"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1rect\/fragments","value":[{"kind":"identifier","text":"rect"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream\/title","value":"AgoraTranscodingVideoStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream\/fragments","value":[{"kind":"identifier","text":"AgoraTranscodingVideoStream"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1remoteUserUid\/title","value":"remoteUserUid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1remoteUserUid\/fragments","value":[{"kind":"identifier","text":"remoteUserUid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1imageUrl\/title","value":"imageUrl"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1imageUrl\/fragments","value":[{"kind":"identifier","text":"imageUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1mediaPlayerId\/title","value":"mediaPlayerId"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1mediaPlayerId\/fragments","value":[{"kind":"identifier","text":"mediaPlayerId"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1sourceType\/title","value":"sourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraTranscodingVideoStream~1sourceType\/fragments","value":[{"kind":"identifier","text":"sourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}