{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraThreadPriorityType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorathreadprioritytype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorathreadprioritytype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/critical","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/high","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/highest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/lowest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/normal"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraThreadPriorityType"}],"title":"AgoraThreadPriorityType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraThreadPriorityType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/highest":{"role":"symbol","title":"AgoraThreadPriorityType.highest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"highest"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/highest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHighest"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/highest"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorathreadprioritytype\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/high":{"role":"symbol","title":"AgoraThreadPriorityType.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHigh"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/high"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/critical":{"role":"symbol","title":"AgoraThreadPriorityType.critical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"critical"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/critical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeCritical"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/critical"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorathreadprioritytype\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorathreadprioritytype\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/lowest":{"role":"symbol","title":"AgoraThreadPriorityType.lowest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowest"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/lowest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeLowest"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/lowest"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/normal":{"role":"symbol","title":"AgoraThreadPriorityType.normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/normal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeNormal"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/normal"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType/low":{"role":"symbol","title":"AgoraThreadPriorityType.low","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"low"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/low","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityTypeLow"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype\/low"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraThreadPriorityType":{"role":"symbol","title":"AgoraThreadPriorityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraThreadPriorityType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraThreadPriorityType"}],"url":"\/documentation\/agorartckit\/agorathreadprioritytype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraThreadPriorityType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraThreadPriorityType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/critical","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/high","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/highest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/low","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/lowest","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraThreadPriorityType\/normal"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraThreadPriorityType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1highest\/title","value":"AgoraThreadPriorityTypeHighest"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1highest\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHighest"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1high\/title","value":"AgoraThreadPriorityTypeHigh"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1high\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeHigh"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1critical\/title","value":"AgoraThreadPriorityTypeCritical"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1critical\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeCritical"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1lowest\/title","value":"AgoraThreadPriorityTypeLowest"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1lowest\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeLowest"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1normal\/title","value":"AgoraThreadPriorityTypeNormal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1normal\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeNormal"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1low\/title","value":"AgoraThreadPriorityTypeLow"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType~1low\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityTypeLow"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/title","value":"AgoraThreadPriorityType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraThreadPriorityType\/fragments","value":[{"kind":"identifier","text":"AgoraThreadPriorityType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}