{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreamsubscribestate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The subscribing state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"title":"AgoraStreamSubscribeState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraStreamSubscribeState","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/noSubscribed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribing"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/subscribing":{"role":"symbol","title":"AgoraStreamSubscribeState.subscribing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribing"}],"abstract":[{"type":"text","text":"2: Subscribing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribing"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/subscribing"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState":{"role":"symbol","title":"AgoraStreamSubscribeState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"abstract":[{"type":"text","text":"The subscribing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/subscribed":{"role":"symbol","title":"AgoraStreamSubscribeState.subscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribed"}],"abstract":[{"type":"text","text":"3: The remote stream is received, and the subscription is successful."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribed"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/subscribed"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/noSubscribed":{"role":"symbol","title":"AgoraStreamSubscribeState.noSubscribed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noSubscribed"}],"abstract":[{"type":"text","text":"1: Fails to subscribe to the remote stream. Possible reasons:The remote user:Calls muteLocalAudioStream(YES) or muteLocalVideoStream(YES) to stop sending local media stream.Calls disableAudio or disableVideo to disable the local audio or video module.Calls enableLocalAudio(NO) or enableLocalVideo(NO) to disable local audio or video capture.The role of the remote user is audience.The local user calls the following methods to stop receiving remote streams:Call muteRemoteAudioStream(YES) or muteAllRemoteAudioStreams(YES) to stop receiving the remote audio stream.Call muteRemoteVideoStream(YES) or muteAllRemoteVideoStreams(YES) to stop receiving the remote video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/noSubscribed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateNoSubscribed"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/nosubscribed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/idle":{"role":"symbol","title":"AgoraStreamSubscribeState.idle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"abstract":[{"type":"text","text":"0: The initial publishing state after joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/idle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamSubscribeStateIdle"}],"url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/idle"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamSubscribeState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorastreamsubscribestate\/equatable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamSubscribeState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/idle","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/noSubscribed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribed","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamSubscribeState\/subscribing"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamSubscribeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1subscribing\/title","value":"AgoraStreamSubscribeStateSubscribing"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1subscribing\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribing"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/title","value":"AgoraStreamSubscribeState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1subscribed\/title","value":"AgoraStreamSubscribeStateSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1subscribed\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateSubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1noSubscribed\/title","value":"AgoraStreamSubscribeStateNoSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1noSubscribed\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateNoSubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1idle\/title","value":"AgoraStreamSubscribeStateIdle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamSubscribeState~1idle\/fragments","value":[{"kind":"identifier","text":"AgoraStreamSubscribeStateIdle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}