{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralicenseverifycode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralicenseverifycode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/diffDevices","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/expire","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/limitedPeriod","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/minutesExceed"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"title":"AgoraLicenseVerifyCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraLicenseVerifyCode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralicenseverifycode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agoralicenseverifycode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/limitedPeriod":{"role":"symbol","title":"AgoraLicenseVerifyCode.limitedPeriod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitedPeriod"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/limitedPeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyLimitedPeriod"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/limitedperiod"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agoralicenseverifycode\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode":{"role":"symbol","title":"AgoraLicenseVerifyCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/minutesExceed":{"role":"symbol","title":"AgoraLicenseVerifyCode.minutesExceed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minutesExceed"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/minutesExceed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyMinutesExceed"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/minutesexceed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/invalid":{"role":"symbol","title":"AgoraLicenseVerifyCode.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyInvalid"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/invalid"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/internal":{"role":"symbol","title":"AgoraLicenseVerifyCode.internal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`internal`"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/internal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyInternal"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/internal"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/expire":{"role":"symbol","title":"AgoraLicenseVerifyCode.expire","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expire"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/expire","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyExpire"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/expire"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLicenseVerifyCode/diffDevices":{"role":"symbol","title":"AgoraLicenseVerifyCode.diffDevices","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"diffDevices"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/diffDevices","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLicenseVerifyDiffDevices"}],"url":"\/documentation\/agorartckit\/agoralicenseverifycode\/diffdevices"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLicenseVerifyCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/diffDevices","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/expire","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/internal","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/invalid","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/limitedPeriod","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLicenseVerifyCode\/minutesExceed"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLicenseVerifyCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1limitedPeriod\/title","value":"AgoraLicenseVerifyLimitedPeriod"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1limitedPeriod\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyLimitedPeriod"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode\/title","value":"AgoraLicenseVerifyCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1minutesExceed\/title","value":"AgoraLicenseVerifyMinutesExceed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1minutesExceed\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyMinutesExceed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1invalid\/title","value":"AgoraLicenseVerifyInvalid"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1invalid\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1internal\/title","value":"AgoraLicenseVerifyInternal"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1internal\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyInternal"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1expire\/title","value":"AgoraLicenseVerifyExpire"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1expire\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyExpire"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1diffDevices\/title","value":"AgoraLicenseVerifyDiffDevices"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLicenseVerifyCode~1diffDevices\/fragments","value":[{"kind":"identifier","text":"AgoraLicenseVerifyDiffDevices"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}