{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBeautyOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabeautyoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabeautyoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image enhancement options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBeautyOptions"}],"title":"AgoraBeautyOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraBeautyOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraBeautyOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningContrastLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/rednessLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/sharpnessLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/smoothnessLevel"]}],"references":{"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions/lighteningContrastLevel":{"role":"symbol","title":"lighteningContrastLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lighteningContrastLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLighteningContrastLevel","preciseIdentifier":"c:@E@AgoraLighteningContrastLevel"}],"abstract":[{"type":"text","text":"The contrast level, used with the lighteningLevel parameter. The larger the value, the greater the contrast between light and dark. See AgoraLighteningContrastLevel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningContrastLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lighteningContrastLevel"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions\/lighteningcontrastlevel"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions/rednessLevel":{"role":"symbol","title":"rednessLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rednessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The redness level, in the range [0.0,1.0], where 0.0 means the original redness. The default value is 0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/rednessLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rednessLevel"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions\/rednesslevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions/lighteningLevel":{"role":"symbol","title":"lighteningLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lighteningLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The brightening level, in the range [0.0,1.0], where 0.0 means the original brightening. The default value is 0.7"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lighteningLevel"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions\/lighteninglevel"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions":{"role":"symbol","title":"AgoraBeautyOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBeautyOptions"}],"abstract":[{"type":"text","text":"Image enhancement options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBeautyOptions"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions/smoothnessLevel":{"role":"symbol","title":"smoothnessLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smoothnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The smoothness level, in the range [0.0,1.0], where 0.0 means the original smoothness. The default value is 0.5"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/smoothnessLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smoothnessLevel"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions\/smoothnesslevel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBeautyOptions/sharpnessLevel":{"role":"symbol","title":"sharpnessLevel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpnessLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The sharpness level, in the range [0.0,1.0], where 0.0 means the original sharpness. The default value is 0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/sharpnessLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharpnessLevel"}],"url":"\/documentation\/agorartckit\/agorabeautyoptions\/sharpnesslevel"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraBeautyOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraBeautyOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraBeautyOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningContrastLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/lighteningLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/rednessLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/sharpnessLevel","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBeautyOptions\/smoothnessLevel"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBeautyOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1lighteningContrastLevel\/title","value":"lighteningContrastLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1lighteningContrastLevel\/fragments","value":[{"kind":"identifier","text":"lighteningContrastLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1rednessLevel\/title","value":"rednessLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1rednessLevel\/fragments","value":[{"kind":"identifier","text":"rednessLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1lighteningLevel\/title","value":"lighteningLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1lighteningLevel\/fragments","value":[{"kind":"identifier","text":"lighteningLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions\/title","value":"AgoraBeautyOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions\/fragments","value":[{"kind":"identifier","text":"AgoraBeautyOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1smoothnessLevel\/title","value":"smoothnessLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1smoothnessLevel\/fragments","value":[{"kind":"identifier","text":"smoothnessLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1sharpnessLevel\/title","value":"sharpnessLevel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBeautyOptions~1sharpnessLevel\/fragments","value":[{"kind":"identifier","text":"sharpnessLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}