{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamingevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamingevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Events during the media push."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"title":"AgoraRtmpStreamingEvent","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraRtmpStreamingEvent","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/advancedFeatureNotSupport","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/failedLoadImage","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/requestTooOften","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/urlAlreadyInUse"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/failedLoadImage":{"role":"symbol","title":"AgoraRtmpStreamingEvent.failedLoadImage","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedLoadImage"}],"abstract":[{"type":"text","text":"1: An error occurs when you add a background image or a watermark image in"},{"type":"text","text":" "},{"type":"text","text":"the media push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/failedLoadImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventFailedLoadImage"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/failedloadimage"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/init(rawvalue:)"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/requestTooOften":{"role":"symbol","title":"AgoraRtmpStreamingEvent.requestTooOften","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestTooOften"}],"abstract":[{"type":"text","text":"4: Reserved."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/requestTooOften","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventRequestTooOften"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/requesttoooften"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent":{"role":"symbol","title":"AgoraRtmpStreamingEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"abstract":[{"type":"text","text":"Events during the media push."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/advancedFeatureNotSupport":{"role":"symbol","title":"AgoraRtmpStreamingEvent.advancedFeatureNotSupport","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedFeatureNotSupport"}],"abstract":[{"type":"text","text":"3: The feature is not supported."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/advancedFeatureNotSupport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventAdvancedFeatureNotSupport"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/advancedfeaturenotsupport"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/urlAlreadyInUse":{"role":"symbol","title":"AgoraRtmpStreamingEvent.urlAlreadyInUse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlAlreadyInUse"}],"abstract":[{"type":"text","text":"2: The streaming URL is already being used for CDN live streaming. If you"},{"type":"text","text":" "},{"type":"text","text":"want to start new streaming, use a new streaming URL."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/urlAlreadyInUse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingEventUrlAlreadyInUse"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/urlalreadyinuse"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingEvent/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmpstreamingevent\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamingEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/advancedFeatureNotSupport","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/failedLoadImage","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/requestTooOften","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingEvent\/urlAlreadyInUse"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1failedLoadImage\/title","value":"AgoraRtmpStreamingEventFailedLoadImage"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1failedLoadImage\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventFailedLoadImage"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1requestTooOften\/title","value":"AgoraRtmpStreamingEventRequestTooOften"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1requestTooOften\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventRequestTooOften"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent\/title","value":"AgoraRtmpStreamingEvent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1advancedFeatureNotSupport\/title","value":"AgoraRtmpStreamingEventAdvancedFeatureNotSupport"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1advancedFeatureNotSupport\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventAdvancedFeatureNotSupport"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1urlAlreadyInUse\/title","value":"AgoraRtmpStreamingEventUrlAlreadyInUse"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingEvent~1urlAlreadyInUse\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingEventUrlAlreadyInUse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}