{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmstreamchannelerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmstreamchannelerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/erroExceedLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/errorOk","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/errorUserNotExist"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"title":"AgoraRtmStreamChannelErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AgoraRtmStreamChannelErrorCode","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode":{"role":"symbol","title":"AgoraRtmStreamChannelErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode/errorOk":{"role":"symbol","title":"AgoraRtmStreamChannelErrorCode.errorOk","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorOk"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/errorOk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorOk"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/errorok"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode/errorUserNotExist":{"role":"symbol","title":"AgoraRtmStreamChannelErrorCode.errorUserNotExist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUserNotExist"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/errorUserNotExist","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorUserNotExist"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/errorusernotexist"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/init(rawvalue:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode/erroExceedLimitation":{"role":"symbol","title":"AgoraRtmStreamChannelErrorCode.erroExceedLimitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"erroExceedLimitation"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/erroExceedLimitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErroExceedLimitation"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/erroexceedlimitation"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmStreamChannelErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/erroExceedLimitation","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/errorOk","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/errorUserNotExist"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode\/title","value":"AgoraRtmStreamChannelErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1errorOk\/title","value":"AgoraRtmStreamChannelErrorOk"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1errorOk\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorOk"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1errorUserNotExist\/title","value":"AgoraRtmStreamChannelErrorUserNotExist"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1errorUserNotExist\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorUserNotExist"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1erroExceedLimitation\/title","value":"AgoraRtmStreamChannelErroExceedLimitation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1erroExceedLimitation\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErroExceedLimitation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}