{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraencodedvideotrackoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraencodedvideotrackoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/ccMode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/codecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/targetBitrate"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}],"title":"AgoraEncodedVideoTrackOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)AgoraEncodedVideoTrackOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoTrackOptions":{"role":"symbol","title":"AgoraEncodedVideoTrackOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}],"url":"\/documentation\/agorartckit\/agoraencodedvideotrackoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoTrackOptions/codecType":{"role":"symbol","title":"codecType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codecType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/codecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"codecType"}],"url":"\/documentation\/agorartckit\/agoraencodedvideotrackoptions\/codectype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoTrackOptions/ccMode":{"role":"symbol","title":"ccMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/ccMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ccMode"}],"url":"\/documentation\/agorartckit\/agoraencodedvideotrackoptions\/ccmode"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEncodedVideoTrackOptions/targetBitrate":{"role":"symbol","title":"targetBitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetBitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/targetBitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"targetBitrate"}],"url":"\/documentation\/agorartckit\/agoraencodedvideotrackoptions\/targetbitrate"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEncodedVideoTrackOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/ccMode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/codecType","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEncodedVideoTrackOptions\/targetBitrate"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions\/title","value":"AgoraEncodedVideoTrackOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions\/fragments","value":[{"kind":"identifier","text":"AgoraEncodedVideoTrackOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions~1codecType\/title","value":"codecType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions~1codecType\/fragments","value":[{"kind":"identifier","text":"codecType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions~1ccMode\/title","value":"ccMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions~1ccMode\/fragments","value":[{"kind":"identifier","text":"ccMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions~1targetBitrate\/title","value":"targetBitrate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEncodedVideoTrackOptions~1targetBitrate\/fragments","value":[{"kind":"identifier","text":"targetBitrate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}