{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/audio_ains_mode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/audio_ains_mode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH","doc:\/\/AgoraRtcKit\/SY","doc:\/\/AgoraRtcKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_AGGRESSIVE","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_BALANCED","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_ULTRALOWLATENCY"]},{"title":"Initializers","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/Equatable-Implementations","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"title":"AUDIO_AINS_MODE","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@AUDIO_AINS_MODE","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/audio_ains_mode\/rawrepresentable-implementations"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/AINS_MODE_AGGRESSIVE":{"role":"symbol","title":"AUDIO_AINS_MODE.AINS_MODE_AGGRESSIVE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_AGGRESSIVE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}],"url":"\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_aggressive"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/AINS_MODE_ULTRALOWLATENCY":{"role":"symbol","title":"AUDIO_AINS_MODE.AINS_MODE_ULTRALOWLATENCY","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_ULTRALOWLATENCY","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}],"url":"\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_ultralowlatency"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/AINS_MODE_BALANCED":{"role":"symbol","title":"AUDIO_AINS_MODE.AINS_MODE_BALANCED","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AINS_MODE_BALANCED"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_BALANCED","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AINS_MODE_BALANCED"}],"url":"\/documentation\/agorartckit\/audio_ains_mode\/ains_mode_balanced"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/audio_ains_mode\/equatable-implementations"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE":{"role":"symbol","title":"AUDIO_AINS_MODE","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}],"url":"\/documentation\/agorartckit\/audio_ains_mode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AUDIO_AINS_MODE/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit\/audio_ains_mode\/init(rawvalue:)"},"doc://AgoraRtcKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/AgoraRtcKit\/SY"},"doc://AgoraRtcKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AgoraRtcKit\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"AUDIO_AINS_MODE"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_AGGRESSIVE","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_BALANCED","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AUDIO_AINS_MODE\/AINS_MODE_ULTRALOWLATENCY"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_AINS_MODE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_AGGRESSIVE\/title","value":"AINS_MODE_AGGRESSIVE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_AGGRESSIVE\/fragments","value":[{"kind":"identifier","text":"AINS_MODE_AGGRESSIVE"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_ULTRALOWLATENCY\/title","value":"AINS_MODE_ULTRALOWLATENCY"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_ULTRALOWLATENCY\/fragments","value":[{"kind":"identifier","text":"AINS_MODE_ULTRALOWLATENCY"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_BALANCED\/title","value":"AINS_MODE_BALANCED"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE~1AINS_MODE_BALANCED\/fragments","value":[{"kind":"identifier","text":"AINS_MODE_BALANCED"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE\/title","value":"AUDIO_AINS_MODE"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AUDIO_AINS_MODE\/fragments","value":[{"kind":"identifier","text":"AUDIO_AINS_MODE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}