{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The ins-and-outs of managing your connection to Video channels with Agora."}]},{"anchor":"Channel-Management","level":2,"type":"heading","text":"Channel Management"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For joining, leaving, and updating channel information, here are some of the most useful functions:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateChannel(with:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setClientRole(_:options:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/getConnectionState()"}]}]}]},{"anchor":"Channel-Events","level":2,"type":"heading","text":"Channel Events"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"},{"type":"text","text":" contians all the callbacks needed for updates to your channel, such as other members joining, leaving, network chnages, and when your token is soon to expire."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here are a collection of some of the most frequently used delegate methods, but see more in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate"},{"type":"text","text":"."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didJoinChannel:withUid:elapsed:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didRejoinChannel:withUid:elapsed:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didClientRoleChangeFailed:currentRole:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didLeaveChannelWith:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didJoinedOfUid:elapsed:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didOfflineOfUid:reason:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:networkTypeChanged:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:uplinkNetworkInfoUpdate:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngineConnectionDidLost(_:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:connectionChangedTo:reason:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngineRequestToken(_:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:tokenPrivilegeWillExpire:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didOccurError:)"}]}]}]},{"anchor":"Multiple-Channel-Connections","level":2,"type":"heading","text":"Multiple Channel Connections"},{"type":"paragraph","inlineContent":[{"type":"text","text":"With AgoraRtcKit, you’re able to join multiple channels. The best way to join a secondary channel as an audience member (not broadcasting), is using this join method:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannelEx(byToken:connection:delegate:mediaOptions:joinSuccess:)"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/channels"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/channels"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/Channels","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Joining channels, leaving channels, and everything inbetween."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Channels","role":"article","modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/GettingStarted","doc:\/\/AgoraRtcKit\/tutorials\/TOC"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setClientRole(_:options:)":{"role":"symbol","title":"setClientRole(_:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setClientRole"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the user role and level in an interactive live streaming channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setClientRole(_:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setClientRole:options:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setclientrole(_:options:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:uplinkNetworkInfoUpdate:)":{"role":"symbol","title":"rtcEngine(_:uplinkNetworkInfoUpdate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uplinkNetworkInfoUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraUplinkNetworkInfo","preciseIdentifier":"c:objc(cs)AgoraUplinkNetworkInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the uplink network information changes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:uplinkNetworkInfoUpdate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:uplinkNetworkInfoUpdate:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:uplinknetworkinfoupdate:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:networkTypeChanged:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:networkTypeChanged:"}],"role":"symbol","title":"rtcEngine(_:networkTypeChanged:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"networkTypeChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraNetworkType","preciseIdentifier":"c:@E@AgoraNetworkType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:networkTypeChanged:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:networktypechanged:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didClientRoleChangeFailed:currentRole:)":{"role":"symbol","title":"rtcEngine(_:didClientRoleChangeFailed:currentRole:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClientRoleChangeFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleChangeFailedReason","preciseIdentifier":"c:@E@AgoraClientRoleChangeFailedReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currentRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the user role switching fails in the interactive live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didClientRoleChangeFailed:currentRole:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didClientRoleChangeFailed:currentRole:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didclientrolechangefailed:currentrole:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/GettingStarted":{"role":"article","title":"Getting Started","abstract":[{"type":"text","text":"Get connected to a video call in your application."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/gettingstarted"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/joinChannelEx(byToken:connection:delegate:mediaOptions:joinSuccess:)":{"role":"symbol","title":"joinChannelEx(byToken:connection:delegate:mediaOptions:joinSuccess:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannelEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcEngineDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mediaOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcChannelMediaOptions","preciseIdentifier":"c:objc(cs)AgoraRtcChannelMediaOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinSuccess"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Joins a channel with the connection ID."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannelEx(byToken:connection:delegate:mediaOptions:joinSuccess:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinChannelExByToken:connection:delegate:mediaOptions:joinSuccess:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/joinchannelex(bytoken:connection:delegate:mediaoptions:joinsuccess:)"},"doc://AgoraRtcKit/tutorials/TOC":{"role":"overview","title":"Agora Video SDK Tutorials","abstract":[{"type":"text","text":"These tutorials will show you how to use Agora’s Video SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/tutorials\/TOC","kind":"overview","type":"topic","url":"\/tutorials\/toc"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didOccurError:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didOccurError:"}],"role":"symbol","title":"rtcEngine(_:didOccurError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOccurError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraErrorCode","preciseIdentifier":"c:@E@AgoraErrorCode"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reports an error during SDK runtime."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didOccurError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didoccurerror:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didOfflineOfUid:reason:)":{"role":"symbol","title":"rtcEngine(_:didOfflineOfUid:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOfflineOfUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraUserOfflineReason","preciseIdentifier":"c:@E@AgoraUserOfflineReason"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a remote user (in the communication profile)\/ host (in the live streaming profile) leaves the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didOfflineOfUid:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didOfflineOfUid:reason:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didofflineofuid:reason:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/leaveChannel(_:)":{"role":"symbol","title":"leaveChannel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveChannel"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Leaves a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/leaveChannel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leaveChannel:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/leavechannel(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didJoinedOfUid:elapsed:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didJoinedOfUid:elapsed:"}],"role":"symbol","title":"rtcEngine(_:didJoinedOfUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didJoinedOfUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a remote user (in the communication profile)\/ host (in the live streaming profile) leaves the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didJoinedOfUid:elapsed:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didjoinedofuid:elapsed:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngineRequestToken(_:)":{"role":"symbol","title":"rtcEngineRequestToken(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineRequestToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the token expires."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngineRequestToken(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngineRequestToken:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcenginerequesttoken(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didLeaveChannelWith:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didLeaveChannelWithStats:"}],"role":"symbol","title":"rtcEngine(_:didLeaveChannelWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLeaveChannelWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChannelStats","preciseIdentifier":"c:objc(cs)AgoraChannelStats"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user leaves a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didLeaveChannelWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didleavechannelwith:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)":{"role":"symbol","title":"joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcChannelMediaOptions","preciseIdentifier":"c:objc(cs)AgoraRtcChannelMediaOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinSuccess"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Joins a channel with media options."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinChannelByToken:channelId:uid:mediaOptions:joinSuccess:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/joinchannel(bytoken:channelid:uid:mediaoptions:joinsuccess:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate":{"role":"symbol","title":"AgoraRtcEngineDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"abstract":[{"type":"text","text":"AgoraRtcEngineDelegateThe SDK uses the interface to send event notifications to your app. Your app can get those notifications through methods that inherit this interface."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}],"role":"symbol","title":"rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didClientRoleChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRole"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRole","preciseIdentifier":"c:@E@AgoraClientRole"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newRoleOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraClientRoleOptions","preciseIdentifier":"c:objc(cs)AgoraClientRoleOptions"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the user role switches during the interactive live streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didclientrolechanged:newrole:newroleoptions:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didJoinChannel:withUid:elapsed:)":{"role":"symbol","title":"rtcEngine(_:didJoinChannel:withUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didJoinChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user joins a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didJoinChannel:withUid:elapsed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didJoinChannel:withUid:elapsed:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didjoinchannel:withuid:elapsed:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:tokenPrivilegeWillExpire:)":{"role":"symbol","title":"rtcEngine(_:tokenPrivilegeWillExpire:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tokenPrivilegeWillExpire"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the token expires in 30 seconds."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:tokenPrivilegeWillExpire:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:tokenPrivilegeWillExpire:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:tokenprivilegewillexpire:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/getConnectionState()":{"role":"symbol","title":"getConnectionState()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getConnectionState"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraConnectionState","preciseIdentifier":"c:@E@AgoraConnectionState"}],"abstract":[{"type":"text","text":"Gets the current connection state of the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/getConnectionState()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getConnectionState"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/getconnectionstate()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngineConnectionDidLost(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngineConnectionDidLost:"}],"role":"symbol","title":"rtcEngineConnectionDidLost(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngineConnectionDidLost"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the SDK cannot reconnect to Agora’s edge server 10 seconds after its connection to the server is interrupted."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngineConnectionDidLost(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengineconnectiondidlost(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/updateChannel(with:)":{"role":"symbol","title":"updateChannel(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcChannelMediaOptions","preciseIdentifier":"c:objc(cs)AgoraRtcChannelMediaOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the channel media options after joining the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/updateChannel(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelWithMediaOptions:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/updatechannel(with:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:connectionChangedTo:reason:)":{"role":"symbol","title":"rtcEngine(_:connectionChangedTo:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionChangedTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraConnectionState","preciseIdentifier":"c:@E@AgoraConnectionState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraConnectionChangedReason","preciseIdentifier":"c:@E@AgoraConnectionChangedReason"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when the network connection state changes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:connectionChangedTo:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:connectionChangedToState:reason:"}],"url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:connectionchangedto:reason:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didRejoinChannel:withUid:elapsed:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didRejoinChannel:withUid:elapsed:"}],"role":"symbol","title":"rtcEngine(_:didRejoinChannel:withUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRejoinChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a user rejoins the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didRejoinChannel:withUid:elapsed:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didrejoinchannel:withuid:elapsed:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/GettingStarted","doc:\/\/AgoraRtcKit\/tutorials\/TOC"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setClientRole(_:options:)\/title","value":"setClientRole:options:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setClientRole(_:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setClientRole:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:uplinkNetworkInfoUpdate:)\/title","value":"rtcEngine:uplinkNetworkInfoUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:uplinkNetworkInfoUpdate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:uplinkNetworkInfoUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:networkTypeChanged:)\/title","value":"rtcEngine:networkTypeChanged:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:networkTypeChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:networkTypeChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didClientRoleChangeFailed:currentRole:)\/title","value":"rtcEngine:didClientRoleChangeFailed:currentRole:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didClientRoleChangeFailed:currentRole:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didClientRoleChangeFailed:currentRole:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannelEx(byToken:connection:delegate:mediaOptions:joinSuccess:)\/title","value":"joinChannelExByToken:connection:delegate:mediaOptions:joinSuccess:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannelEx(byToken:connection:delegate:mediaOptions:joinSuccess:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinChannelExByToken:connection:delegate:mediaOptions:joinSuccess:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didOccurError:)\/title","value":"rtcEngine:didOccurError:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didOccurError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didOccurError:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didOfflineOfUid:reason:)\/title","value":"rtcEngine:didOfflineOfUid:reason:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didOfflineOfUid:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didOfflineOfUid:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannel(_:)\/title","value":"leaveChannel:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1leaveChannel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didJoinedOfUid:elapsed:)\/title","value":"rtcEngine:didJoinedOfUid:elapsed:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didJoinedOfUid:elapsed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didJoinedOfUid:elapsed:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngineRequestToken(_:)\/title","value":"rtcEngineRequestToken:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngineRequestToken(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineRequestToken:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didLeaveChannelWith:)\/title","value":"rtcEngine:didLeaveChannelWithStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didLeaveChannelWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didLeaveChannelWithStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)\/title","value":"joinChannelByToken:channelId:uid:mediaOptions:joinSuccess:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1joinChannel(byToken:channelId:uid:mediaOptions:joinSuccess:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinChannelByToken:channelId:uid:mediaOptions:joinSuccess:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/title","value":"AgoraRtcEngineDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtcEngineDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)\/title","value":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didClientRoleChanged:newRole:newRoleOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didClientRoleChanged:newRole:newRoleOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didJoinChannel:withUid:elapsed:)\/title","value":"rtcEngine:didJoinChannel:withUid:elapsed:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didJoinChannel:withUid:elapsed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didJoinChannel:withUid:elapsed:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:tokenPrivilegeWillExpire:)\/title","value":"rtcEngine:tokenPrivilegeWillExpire:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:tokenPrivilegeWillExpire:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:tokenPrivilegeWillExpire:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1getConnectionState()\/title","value":"getConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1getConnectionState()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngineConnectionDidLost(_:)\/title","value":"rtcEngineConnectionDidLost:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngineConnectionDidLost(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngineConnectionDidLost:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateChannel(with:)\/title","value":"updateChannelWithMediaOptions:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1updateChannel(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithMediaOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:connectionChangedTo:reason:)\/title","value":"rtcEngine:connectionChangedToState:reason:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:connectionChangedTo:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:connectionChangedToState:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didRejoinChannel:withUid:elapsed:)\/title","value":"rtcEngine:didRejoinChannel:withUid:elapsed:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didRejoinChannel:withUid:elapsed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didRejoinChannel:withUid:elapsed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}