{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Real-time video immerses people in the sights and sounds of human connections, keeping them engaged in your app longer."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Video Calling enables one-to-one or small-group video chat connections with smooth, jitter-free streaming video. Agora’s Video SDK makes it easy to embed real-time video chat into web, mobile and native apps."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Thanks to Agora’s intelligent and global Software Defined Real-time Network (Agora SD-RTN™), you can rely on the highest available video and audio quality."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This page shows the minimum code you need to integrate high-quality, low-latency Video Calling features into your app using Video SDK."}]},{"anchor":"Importing-the-AgoraRtcEngine-Framework","level":2,"type":"heading","text":"Importing the AgoraRtcEngine Framework"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To get started with the Agora SDK on iOS, you’ll need to import the AgoraRtcEngine framework into your Xcode project. You can do this by adding the Swift Package from this URL:"}]},{"type":"codeListing","syntax":"text","code":["https:\/\/github.com\/AgoraIO\/AgoraRtcEngine_iOS.git"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After this, you can import the SDK to your file as so:"}]},{"type":"codeListing","syntax":"swift","code":["import AgoraRtcKit"]},{"anchor":"Adding-Credentials","level":2,"type":"heading","text":"Adding Credentials"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Next, you’ll need to add your Agora App ID to your project. You can obtain an App ID by creating an account on the Agora Developer Portal and creating a new project. Once you have your App ID, you can add it to your project by initializing the AgoraRtcEngine with the App ID:"}]},{"type":"codeListing","syntax":"swift","code":["let agoraKit = AgoraRtcEngineKit.sharedEngine(withAppId: \"YOUR_APP_ID\", delegate: self)"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/sharedEngine(withAppId:delegate:)"}]}]}]},{"anchor":"Setting-Up-Views","level":2,"type":"heading","text":"Setting Up Views"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To show local and remote video feeds in your iOS app, you’ll need to set up views for the video streams. You can create views programmatically or use Interface Builder to create your views."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here’s an example of creating a local video view programmatically:"}]},{"type":"codeListing","syntax":"swift","code":["func setupLocalVideo() {","    \/\/ Enable the video module","    agoraKit.enableVideo()","    \/\/ Start the local video preview","    agoraKit.startPreview()","    let videoCanvas = AgoraRtcVideoCanvas()","    videoCanvas.uid = 0","    videoCanvas.renderMode = .hidden","    videoCanvas.view = localView","     \/\/ Set the local video view","    agoraKit.setupLocalVideo(videoCanvas)","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To show remote video feeds, you’ll need to subscribe to the remote user’s video stream and add the remote video view to your app’s view hierarchy. Here’s an example of subscribing to a remote user’s video stream:"}]},{"type":"codeListing","syntax":"swift","code":["func rtcEngine(_ engine: AgoraRtcEngineKit, didJoinedOfUid uid: UInt, elapsed: Int) {","    let remoteVideoView = UIView(frame: CGRect(x: 100, y: 0, width: 100, height: 100))","    view.addSubview(remoteVideoView)","","    let videoCanvas = AgoraRtcVideoCanvas()","    videoCanvas.uid = uid","    videoCanvas.renderMode = .hidden","    videoCanvas.view = remoteView","    agoraKit.setupRemoteVideo(videoCanvas)","    agoraKit.setupRemoteVideo(remoteVideoView)","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didJoinedOfUid:elapsed:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/gettingstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/GettingStarted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get connected to a video call in your application."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting Started","role":"article","modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"seeAlsoSections":[{"title":"Getting Started","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/Channels","doc:\/\/AgoraRtcKit\/tutorials\/TOC"],"generated":true}],"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setupLocalVideo(_:)":{"role":"symbol","title":"setupLocalVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLocalVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Initializes the local video view."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupLocalVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLocalVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setuplocalvideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/startPreview()":{"role":"symbol","title":"startPreview()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startPreview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the local video preview."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/startPreview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startPreview"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/startpreview()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineDelegate/rtcEngine(_:didJoinedOfUid:elapsed:)":{"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didJoinedOfUid:elapsed:"}],"role":"symbol","title":"rtcEngine(_:didJoinedOfUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didJoinedOfUid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Occurs when a remote user (in the communication profile)\/ host (in the live streaming profile) leaves the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineDelegate\/rtcEngine(_:didJoinedOfUid:elapsed:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartcenginedelegate\/rtcengine(_:didjoinedofuid:elapsed:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/sharedEngine(withAppId:delegate:)":{"role":"symbol","title":"sharedEngine(withAppId:delegate:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedEngine"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineDelegate","preciseIdentifier":"c:objc(pl)AgoraRtcEngineDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Creates and initializes AgoraRtcEngineKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/sharedEngine(withAppId:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedEngineWithAppId:delegate:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/sharedengine(withappid:delegate:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/enableVideo()":{"role":"symbol","title":"enableVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Enables the video module."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/enableVideo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableVideo"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/enablevideo()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCanvas":{"role":"symbol","title":"AgoraRtcVideoCanvas","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"abstract":[{"type":"text","text":"Attributes of the video canvas object."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCanvas","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}],"url":"\/documentation\/agorartckit\/agorartcvideocanvas"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcEngineKit/setupRemoteVideo(_:)":{"role":"symbol","title":"setupRemoteVideo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupRemoteVideo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcVideoCanvas","preciseIdentifier":"c:objc(cs)AgoraRtcVideoCanvas"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Initializes the video view of a remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcEngineKit\/setupRemoteVideo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupRemoteVideo:"}],"url":"\/documentation\/agorartckit\/agorartcenginekit\/setupremotevideo(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/Channels":{"role":"article","title":"Channels","abstract":[{"type":"text","text":"Joining channels, leaving channels, and everything inbetween."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/Channels","kind":"article","type":"topic","url":"\/documentation\/agorartckit\/channels"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/tutorials/TOC":{"role":"overview","title":"Agora Video SDK Tutorials","abstract":[{"type":"text","text":"These tutorials will show you how to use Agora’s Video SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/tutorials\/TOC","kind":"overview","type":"topic","url":"\/tutorials\/toc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Getting Started","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/Channels","doc:\/\/AgoraRtcKit\/tutorials\/TOC"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupLocalVideo(_:)\/title","value":"setupLocalVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupLocalVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLocalVideo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startPreview()\/title","value":"startPreview"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1startPreview()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didJoinedOfUid:elapsed:)\/title","value":"rtcEngine:didJoinedOfUid:elapsed:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineDelegate~1rtcEngine(_:didJoinedOfUid:elapsed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didJoinedOfUid:elapsed:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1sharedEngine(withAppId:delegate:)\/title","value":"sharedEngineWithAppId:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1sharedEngine(withAppId:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedEngineWithAppId:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideo()\/title","value":"enableVideo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1enableVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/title","value":"AgoraRtcVideoCanvas"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCanvas\/fragments","value":[{"kind":"identifier","text":"AgoraRtcVideoCanvas"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideo(_:)\/title","value":"setupRemoteVideo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcEngineKit~1setupRemoteVideo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupRemoteVideo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}