{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogUploadServerInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/loguploadserverinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/loguploadserverinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverDomain","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverHttps","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverPath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverPort"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogUploadServerInfo"}],"title":"LogUploadServerInfo","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)LogUploadServerInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"LogUploadServerInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/LogUploadServerInfo/serverDomain":{"role":"symbol","title":"serverDomain","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverDomain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverDomain"}],"url":"\/documentation\/agorartckit\/loguploadserverinfo\/serverdomain"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/LogUploadServerInfo/serverHttps":{"role":"symbol","title":"serverHttps","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverHttps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverHttps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverHttps"}],"url":"\/documentation\/agorartckit\/loguploadserverinfo\/serverhttps"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/LogUploadServerInfo":{"role":"symbol","title":"LogUploadServerInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogUploadServerInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogUploadServerInfo"}],"url":"\/documentation\/agorartckit\/loguploadserverinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/LogUploadServerInfo/serverPath":{"role":"symbol","title":"serverPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverPath","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverPath"}],"url":"\/documentation\/agorartckit\/loguploadserverinfo\/serverpath"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/LogUploadServerInfo/serverPort":{"role":"symbol","title":"serverPort","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverPort"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverPort","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverPort"}],"url":"\/documentation\/agorartckit\/loguploadserverinfo\/serverport"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LogUploadServerInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LogUploadServerInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LogUploadServerInfo"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverDomain","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverHttps","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverPath","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/LogUploadServerInfo\/serverPort"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogUploadServerInfo"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverDomain\/title","value":"serverDomain"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverDomain\/fragments","value":[{"kind":"identifier","text":"serverDomain"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverHttps\/title","value":"serverHttps"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverHttps\/fragments","value":[{"kind":"identifier","text":"serverHttps"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo\/title","value":"LogUploadServerInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo\/fragments","value":[{"kind":"identifier","text":"LogUploadServerInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverPath\/title","value":"serverPath"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverPath\/fragments","value":[{"kind":"identifier","text":"serverPath"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverPort\/title","value":"serverPort"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1LogUploadServerInfo~1serverPort\/fragments","value":[{"kind":"identifier","text":"serverPort"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}