{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatermarkOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/watermarkoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/watermarkoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/AgoraRtcKit\/objc(pl)NSObject","doc:\/\/AgoraRtcKit\/s7CVarArgP","doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP","doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP","doc:\/\/AgoraRtcKit\/SQ","doc:\/\/AgoraRtcKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configurations of the watermark image."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatermarkOptions"}],"title":"WatermarkOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)WatermarkOptions","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"WatermarkOptions"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/positionInLandscapeMode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/positionInPortraitMode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/visibleInPreview"]}],"references":{"doc://AgoraRtcKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AgoraRtcKit\/SH"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/WatermarkOptions":{"role":"symbol","title":"WatermarkOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatermarkOptions"}],"abstract":[{"type":"text","text":"Configurations of the watermark image."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WatermarkOptions"}],"url":"\/documentation\/agorartckit\/watermarkoptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/WatermarkOptions/positionInPortraitMode":{"role":"symbol","title":"positionInPortraitMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionInPortraitMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The area to display the watermark image in portrait mode. This parameter contains the following members:x: The horizontal position of the watermark relative to the upper left corner.y: The vertical position of the watermark relative to the upper left corner.width: The width (pixel) of the watermark area.height: The height (pixel) of the watermark area."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/positionInPortraitMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"positionInPortraitMode"}],"url":"\/documentation\/agorartckit\/watermarkoptions\/positioninportraitmode"},"doc://AgoraRtcKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s28CustomDebugStringConvertibleP"},"doc://AgoraRtcKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/AgoraRtcKit\/s23CustomStringConvertibleP"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/WatermarkOptions/visibleInPreview":{"role":"symbol","title":"visibleInPreview","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleInPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Reserved for future use."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/visibleInPreview","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"visibleInPreview"}],"url":"\/documentation\/agorartckit\/watermarkoptions\/visibleinpreview"},"doc://AgoraRtcKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/AgoraRtcKit\/objc(cs)NSObject"},"doc://AgoraRtcKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/AgoraRtcKit\/objc(pl)NSObject"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/WatermarkOptions/positionInLandscapeMode":{"role":"symbol","title":"positionInLandscapeMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionInLandscapeMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The area to display the watermark image in landscape mode. This parameter contains the following members:x: The horizontal position of the watermark relative to the upper left corner.y: The vertical position of the watermark relative to the upper left corner.width: The width (pixel) of the watermark area.height: The height (pixel) of the watermark area."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/positionInLandscapeMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"positionInLandscapeMode"}],"url":"\/documentation\/agorartckit\/watermarkoptions\/positioninlandscapemode"},"doc://AgoraRtcKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/AgoraRtcKit\/s7CVarArgP"},"doc://AgoraRtcKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AgoraRtcKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WatermarkOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WatermarkOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WatermarkOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/positionInLandscapeMode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/positionInPortraitMode","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/WatermarkOptions\/visibleInPreview"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/AgoraRtcKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WatermarkOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions\/title","value":"WatermarkOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions\/fragments","value":[{"kind":"identifier","text":"WatermarkOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1positionInPortraitMode\/title","value":"positionInPortraitMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1positionInPortraitMode\/fragments","value":[{"kind":"identifier","text":"positionInPortraitMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1visibleInPreview\/title","value":"visibleInPreview"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1visibleInPreview\/fragments","value":[{"kind":"identifier","text":"visibleInPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1positionInLandscapeMode\/title","value":"positionInLandscapeMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1WatermarkOptions~1positionInLandscapeMode\/fragments","value":[{"kind":"identifier","text":"positionInLandscapeMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}