{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectivityFirst"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalproxymode\/connectivityfirst"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalproxymode\/connectivityfirst"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalProxyMode\/connectivityFirst","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectivityFirst"}],"title":"AgoraLocalProxyMode.connectivityFirst","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLocalProxyMode@AgoraConnectivityFirst","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraConnectivityFirst"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalProxyMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalProxyMode/connectivityFirst":{"role":"symbol","title":"AgoraLocalProxyMode.connectivityFirst","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectivityFirst"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalProxyMode\/connectivityFirst","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectivityFirst"}],"url":"\/documentation\/agorartckit\/agoralocalproxymode\/connectivityfirst"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalProxyMode":{"role":"symbol","title":"AgoraLocalProxyMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalProxyMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalProxyMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalProxyMode"}],"url":"\/documentation\/agorartckit\/agoralocalproxymode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraConnectivityFirst"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraConnectivityFirst"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraConnectivityFirst"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalProxyMode~1connectivityFirst\/title","value":"AgoraConnectivityFirst"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalProxyMode~1connectivityFirst\/fragments","value":[{"kind":"identifier","text":"AgoraConnectivityFirst"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalProxyMode\/title","value":"AgoraLocalProxyMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalProxyMode\/fragments","value":[{"kind":"identifier","text":"AgoraLocalProxyMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}