{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeUnpublishOK"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codeunpublishok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codeunpublishok"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode\/codeUnpublishOK","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"100: The streaming has been stopped normally. After you call stopRtmpStream"},{"type":"text","text":" "},{"type":"text","text":"to stop streaming, the SDK returns this value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeUnpublishOK"}],"title":"AgoraRtmpStreamingErrorCode.codeUnpublishOK","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamingErrorCode@AgoraRtmpStreamingErrorCodeUnpublishOK","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeUnpublishOK"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingErrorCode/codeUnpublishOK":{"role":"symbol","title":"AgoraRtmpStreamingErrorCode.codeUnpublishOK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeUnpublishOK"}],"abstract":[{"type":"text","text":"100: The streaming has been stopped normally. After you call stopRtmpStream"},{"type":"text","text":" "},{"type":"text","text":"to stop streaming, the SDK returns this value."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode\/codeUnpublishOK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeUnpublishOK"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codeunpublishok"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingErrorCode":{"role":"symbol","title":"AgoraRtmpStreamingErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"abstract":[{"type":"text","text":"Error codes of the RTMP or RTMPS streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingerrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamingErrorCodeUnpublishOK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeUnpublishOK"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeUnpublishOK"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode~1codeUnpublishOK\/title","value":"AgoraRtmpStreamingErrorCodeUnpublishOK"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode~1codeUnpublishOK\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeUnpublishOK"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/title","value":"AgoraRtmpStreamingErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}