{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeNotAuthorized"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codenotauthorized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codenotauthorized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode\/codeNotAuthorized","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"8: The host manipulates other hosts’ URLs. For example, the host updates or"},{"type":"text","text":" "},{"type":"text","text":"stops other hosts’ streams. Check your app logic."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeNotAuthorized"}],"title":"AgoraRtmpStreamingErrorCode.codeNotAuthorized","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamingErrorCode@AgoraRtmpStreamingErrorCodeNotAuthorized","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeNotAuthorized"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingErrorCode/codeNotAuthorized":{"role":"symbol","title":"AgoraRtmpStreamingErrorCode.codeNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeNotAuthorized"}],"abstract":[{"type":"text","text":"8: The host manipulates other hosts’ URLs. For example, the host updates or"},{"type":"text","text":" "},{"type":"text","text":"stops other hosts’ streams. Check your app logic."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode\/codeNotAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeNotAuthorized"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codenotauthorized"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingErrorCode":{"role":"symbol","title":"AgoraRtmpStreamingErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"abstract":[{"type":"text","text":"Error codes of the RTMP or RTMPS streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamingErrorCodeNotAuthorized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeNotAuthorized"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeNotAuthorized"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode~1codeNotAuthorized\/title","value":"AgoraRtmpStreamingErrorCodeNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode~1codeNotAuthorized\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/title","value":"AgoraRtmpStreamingErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}