{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeEncryptedStreamNotAllowed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codeencryptedstreamnotallowed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codeencryptedstreamnotallowed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode\/codeEncryptedStreamNotAllowed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The RTMP or RTMPS streaming is encrypted and cannot be published."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeEncryptedStreamNotAllowed"}],"title":"AgoraRtmpStreamingErrorCode.codeEncryptedStreamNotAllowed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamingErrorCode@AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingErrorCode/codeEncryptedStreamNotAllowed":{"role":"symbol","title":"AgoraRtmpStreamingErrorCode.codeEncryptedStreamNotAllowed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeEncryptedStreamNotAllowed"}],"abstract":[{"type":"text","text":"2: The RTMP or RTMPS streaming is encrypted and cannot be published."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode\/codeEncryptedStreamNotAllowed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingerrorcode\/codeencryptedstreamnotallowed"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamingErrorCode":{"role":"symbol","title":"AgoraRtmpStreamingErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"abstract":[{"type":"text","text":"Error codes of the RTMP or RTMPS streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamingErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmpstreamingerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode~1codeEncryptedStreamNotAllowed\/title","value":"AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode~1codeEncryptedStreamNotAllowed\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCodeEncryptedStreamNotAllowed"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/title","value":"AgoraRtmpStreamingErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamingErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamingErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}