{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AdvancedConfigInfo","preciseIdentifier":"c:objc(cs)AdvancedConfigInfo","text":"AdvancedConfigInfo"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/advancedconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/advancedconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/advancedConfig","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedConfigInfo","preciseIdentifier":"c:objc(cs)AdvancedConfigInfo"},{"kind":"text","text":"?"}],"title":"advancedConfig","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLocalAccessPointConfiguration(py)advancedConfig","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"advancedConfig"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration/advancedConfig":{"role":"symbol","title":"advancedConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"advancedConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvancedConfigInfo","preciseIdentifier":"c:objc(cs)AdvancedConfigInfo"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/advancedConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"advancedConfig"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/advancedconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration":{"role":"symbol","title":"AgoraLocalAccessPointConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AdvancedConfigInfo":{"role":"symbol","title":"AdvancedConfigInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvancedConfigInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AdvancedConfigInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdvancedConfigInfo"}],"url":"\/documentation\/agorartckit\/advancedconfiginfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"advancedConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"advancedConfig"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AdvancedConfigInfo","preciseIdentifier":"c:objc(cs)AdvancedConfigInfo","text":"AdvancedConfigInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"advancedConfig"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1advancedConfig\/title","value":"advancedConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1advancedConfig\/fragments","value":[{"kind":"identifier","text":"advancedConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration\/title","value":"AgoraLocalAccessPointConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AdvancedConfigInfo\/title","value":"AdvancedConfigInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AdvancedConfigInfo\/fragments","value":[{"kind":"identifier","text":"AdvancedConfigInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}