{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ipList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/iplist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/iplist"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/ipList","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ipList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"ipList","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLocalAccessPointConfiguration(py)ipList","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"ipList"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration":{"role":"symbol","title":"AgoraLocalAccessPointConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalAccessPointConfiguration/ipList":{"role":"symbol","title":"ipList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ipList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalAccessPointConfiguration\/ipList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ipList"}],"url":"\/documentation\/agorartckit\/agoralocalaccesspointconfiguration\/iplist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ipList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ipList"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ipList"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration\/title","value":"AgoraLocalAccessPointConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraLocalAccessPointConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1ipList\/title","value":"ipList"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalAccessPointConfiguration~1ipList\/fragments","value":[{"kind":"identifier","text":"ipList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}