{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNoPermission"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiolocalerror\/devicenopermission"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiolocalerror\/devicenopermission"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError\/deviceNoPermission","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: No permission to use the local audio capturing device. Remind your users"},{"type":"text","text":" "},{"type":"text","text":"to grant permission.Deprecated:This enumerator is deprecated. Please use"},{"type":"text","text":" "},{"type":"text","text":"AgoraPermissionTypeRecordAudio in the permissionError callback instead."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNoPermission"}],"title":"AgoraAudioLocalError.deviceNoPermission","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioLocalError@AgoraAudioLocalErrorDeviceNoPermission","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalErrorDeviceNoPermission"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalError/deviceNoPermission":{"role":"symbol","title":"AgoraAudioLocalError.deviceNoPermission","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNoPermission"}],"abstract":[{"type":"text","text":"2: No permission to use the local audio capturing device. Remind your users"},{"type":"text","text":" "},{"type":"text","text":"to grant permission.Deprecated:This enumerator is deprecated. Please use"},{"type":"text","text":" "},{"type":"text","text":"AgoraPermissionTypeRecordAudio in the permissionError callback instead."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError\/deviceNoPermission","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalErrorDeviceNoPermission"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalerror\/devicenopermission"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalError":{"role":"symbol","title":"AgoraAudioLocalError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioLocalError"}],"abstract":[{"type":"text","text":"Local audio state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalError"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioLocalErrorDeviceNoPermission"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalErrorDeviceNoPermission"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioLocalErrorDeviceNoPermission"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError~1deviceNoPermission\/title","value":"AgoraAudioLocalErrorDeviceNoPermission"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError~1deviceNoPermission\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalErrorDeviceNoPermission"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError\/title","value":"AgoraAudioLocalError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}