{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordFailure"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiolocalerror\/recordfailure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiolocalerror\/recordfailure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError\/recordFailure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: The local audio capture fails."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordFailure"}],"title":"AgoraAudioLocalError.recordFailure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioLocalError@AgoraAudioLocalErrorRecordFailure","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalErrorRecordFailure"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalError":{"role":"symbol","title":"AgoraAudioLocalError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioLocalError"}],"abstract":[{"type":"text","text":"Local audio state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalError"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioLocalError/recordFailure":{"role":"symbol","title":"AgoraAudioLocalError.recordFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordFailure"}],"abstract":[{"type":"text","text":"4: The local audio capture fails."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioLocalError\/recordFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioLocalErrorRecordFailure"}],"url":"\/documentation\/agorartckit\/agoraaudiolocalerror\/recordfailure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioLocalErrorRecordFailure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalErrorRecordFailure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioLocalErrorRecordFailure"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError\/title","value":"AgoraAudioLocalError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError~1recordFailure\/title","value":"AgoraAudioLocalErrorRecordFailure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioLocalError~1recordFailure\/fragments","value":[{"kind":"identifier","text":"AgoraAudioLocalErrorRecordFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}