{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObservedFramePosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition","preciseIdentifier":"c:@E@AgoraVideoFramePosition","text":"AgoraVideoFramePosition"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A bit mask that controls the frame position of the video observer."},{"type":"text","text":" "},{"type":"text","text":"See AgoraVideoFramePosition ."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/getobservedframeposition()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/getobservedframeposition()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/getObservedFramePosition()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the frame position for the video observer."},{"type":"text","text":" "},{"type":"text","text":"After successfully registering the video data observer, the SDK uses this"},{"type":"text","text":" "},{"type":"text","text":"callback to determine whether to trigger onCaptureVideoFrame ,"},{"type":"text","text":" "},{"type":"text","text":"onRenderVideoFrame and onPreEncodeVideoFrame callback at each specific video"},{"type":"text","text":" "},{"type":"text","text":"frame processing position, so that you can observe the locally collected"},{"type":"text","text":" "},{"type":"text","text":"video data, the video data sent by the remote end, and the video data before"},{"type":"text","text":" "},{"type":"text","text":"encoding. You can set one or more positions you need to observe by modifying"},{"type":"text","text":" "},{"type":"text","text":"the return value according to your"},{"type":"text","text":" "},{"type":"text","text":"scenario:AgoraVideoFramePositionPostCapture(1 << 0): The position after"},{"type":"text","text":" "},{"type":"text","text":"capturing the video data, which corresponds to the onCaptureVideoFrame"},{"type":"text","text":" "},{"type":"text","text":"callback.AgoraVideoFramePositionPreRenderer(1 << 1): The position of the"},{"type":"text","text":" "},{"type":"text","text":"received remote video data before rendering, which corresponds to the"},{"type":"text","text":" "},{"type":"text","text":"onRenderVideoFrame callback.AgoraVideoFramePositionPreEncoder(1 << 2): The"},{"type":"text","text":" "},{"type":"text","text":"position before encoding the video data, which corresponds to the"},{"type":"text","text":" "},{"type":"text","text":"onPreEncodeVideoFrame callback.Use ‘|’ (the OR operator) to observe multiple"},{"type":"text","text":" "},{"type":"text","text":"frame positions.This callback observes AgoraVideoFramePositionPostCapture(1"},{"type":"text","text":" "},{"type":"text","text":"<< 0) and AgoraVideoFramePositionPreRenderer(1 << 1) by default.To conserve"},{"type":"text","text":" "},{"type":"text","text":"system resources, you can reduce the number of frame positions that you want"},{"type":"text","text":" "},{"type":"text","text":"to observe.When the video processing mode is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFrameProcessModeReadWrite and the observation position is set to"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFramePositionPreEncoder | AgoraVideoFramePositionPostCapture, the"},{"type":"text","text":" "},{"type":"text","text":"getMirrorApplied does not take effect; you need to modify the video"},{"type":"text","text":" "},{"type":"text","text":"processing mode or the position of the observer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObservedFramePosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraVideoFramePosition","preciseIdentifier":"c:@E@AgoraVideoFramePosition"}],"title":"getObservedFramePosition()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraVideoFrameDelegate(im)getObservedFramePosition","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"getObservedFramePosition"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate/getObservedFramePosition()":{"role":"symbol","title":"getObservedFramePosition()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getObservedFramePosition"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraVideoFramePosition","preciseIdentifier":"c:@E@AgoraVideoFramePosition"}],"abstract":[{"type":"text","text":"Sets the frame position for the video observer."},{"type":"text","text":" "},{"type":"text","text":"After successfully registering the video data observer, the SDK uses this"},{"type":"text","text":" "},{"type":"text","text":"callback to determine whether to trigger onCaptureVideoFrame ,"},{"type":"text","text":" "},{"type":"text","text":"onRenderVideoFrame and onPreEncodeVideoFrame callback at each specific video"},{"type":"text","text":" "},{"type":"text","text":"frame processing position, so that you can observe the locally collected"},{"type":"text","text":" "},{"type":"text","text":"video data, the video data sent by the remote end, and the video data before"},{"type":"text","text":" "},{"type":"text","text":"encoding. You can set one or more positions you need to observe by modifying"},{"type":"text","text":" "},{"type":"text","text":"the return value according to your"},{"type":"text","text":" "},{"type":"text","text":"scenario:AgoraVideoFramePositionPostCapture(1 << 0): The position after"},{"type":"text","text":" "},{"type":"text","text":"capturing the video data, which corresponds to the onCaptureVideoFrame"},{"type":"text","text":" "},{"type":"text","text":"callback.AgoraVideoFramePositionPreRenderer(1 << 1): The position of the"},{"type":"text","text":" "},{"type":"text","text":"received remote video data before rendering, which corresponds to the"},{"type":"text","text":" "},{"type":"text","text":"onRenderVideoFrame callback.AgoraVideoFramePositionPreEncoder(1 << 2): The"},{"type":"text","text":" "},{"type":"text","text":"position before encoding the video data, which corresponds to the"},{"type":"text","text":" "},{"type":"text","text":"onPreEncodeVideoFrame callback.Use ‘|’ (the OR operator) to observe multiple"},{"type":"text","text":" "},{"type":"text","text":"frame positions.This callback observes AgoraVideoFramePositionPostCapture(1"},{"type":"text","text":" "},{"type":"text","text":"<< 0) and AgoraVideoFramePositionPreRenderer(1 << 1) by default.To conserve"},{"type":"text","text":" "},{"type":"text","text":"system resources, you can reduce the number of frame positions that you want"},{"type":"text","text":" "},{"type":"text","text":"to observe.When the video processing mode is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFrameProcessModeReadWrite and the observation position is set to"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFramePositionPreEncoder | AgoraVideoFramePositionPostCapture, the"},{"type":"text","text":" "},{"type":"text","text":"getMirrorApplied does not take effect; you need to modify the video"},{"type":"text","text":" "},{"type":"text","text":"processing mode or the position of the observer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/getObservedFramePosition()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getObservedFramePosition"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate\/getobservedframeposition()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFramePosition":{"role":"symbol","title":"AgoraVideoFramePosition","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFramePosition"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFramePosition"}],"url":"\/documentation\/agorartckit\/agoravideoframeposition"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate":{"role":"symbol","title":"AgoraVideoFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"abstract":[{"type":"text","text":"The IVideoFrameObserver class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getObservedFramePosition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getObservedFramePosition"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFramePosition","preciseIdentifier":"c:@E@AgoraVideoFramePosition","text":"AgoraVideoFramePosition"},{"kind":"text","text":") "},{"kind":"identifier","text":"getObservedFramePosition"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1getObservedFramePosition()\/title","value":"getObservedFramePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1getObservedFramePosition()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getObservedFramePosition"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition\/title","value":"AgoraVideoFramePosition"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFramePosition\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFramePosition"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/title","value":"AgoraVideoFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}