{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRotationApplied"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Sets whether to rotate the captured video: YES : Rotate the"},{"type":"text","text":" "},{"type":"text","text":"captured video. NO : (Default) Do not rotate the captured video."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/getrotationapplied()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/getrotationapplied()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/getRotationApplied()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame, and prompts you whether to"},{"type":"text","text":" "},{"type":"text","text":"rotate the captured video. If the video has been rotated according to"},{"type":"text","text":" "},{"type":"text","text":"rotation in AgoraOutputVideoFrame on the capture device, you do not need to"},{"type":"text","text":" "},{"type":"text","text":"call this method to set the video rotation.This function only applies to the"},{"type":"text","text":" "},{"type":"text","text":"scenarios where the video processing mode is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFrameProcessModeReadOnly.This function only supports video data in"},{"type":"text","text":" "},{"type":"text","text":"RGBA and YUV420."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRotationApplied"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"getRotationApplied()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraVideoFrameDelegate(im)getRotationApplied","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"getRotationApplied"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate":{"role":"symbol","title":"AgoraVideoFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"abstract":[{"type":"text","text":"The IVideoFrameObserver class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate/getRotationApplied()":{"role":"symbol","title":"getRotationApplied()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRotationApplied"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame, and prompts you whether to"},{"type":"text","text":" "},{"type":"text","text":"rotate the captured video. If the video has been rotated according to"},{"type":"text","text":" "},{"type":"text","text":"rotation in AgoraOutputVideoFrame on the capture device, you do not need to"},{"type":"text","text":" "},{"type":"text","text":"call this method to set the video rotation.This function only applies to the"},{"type":"text","text":" "},{"type":"text","text":"scenarios where the video processing mode is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFrameProcessModeReadOnly.This function only supports video data in"},{"type":"text","text":" "},{"type":"text","text":"RGBA and YUV420."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/getRotationApplied()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getRotationApplied"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate\/getrotationapplied()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getRotationApplied"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRotationApplied"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"getRotationApplied"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/title","value":"AgoraVideoFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1getRotationApplied()\/title","value":"getRotationApplied"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1getRotationApplied()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRotationApplied"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}