{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVideoFrameProcessMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameProcessMode","preciseIdentifier":"c:@E@AgoraVideoFrameProcessMode","text":"AgoraVideoFrameProcessMode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See AgoraVideoFrameProcessMode ."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/getvideoframeprocessmode()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/getvideoframeprocessmode()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/getVideoFrameProcessMode()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame and prompts you to set the"},{"type":"text","text":" "},{"type":"text","text":"process mode of the video frame. After you successfully register the video"},{"type":"text","text":" "},{"type":"text","text":"frame observer, the SDK triggers this callback each time it receives a video"},{"type":"text","text":" "},{"type":"text","text":"frame. You need to set your preferred process mode in the return value of"},{"type":"text","text":" "},{"type":"text","text":"this callback."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"getVideoFrameProcessMode"}],"role":"symbol","title":"getVideoFrameProcessMode()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVideoFrameProcessMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraVideoFrameProcessMode","preciseIdentifier":"c:@E@AgoraVideoFrameProcessMode"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraVideoFrameDelegate(im)getVideoFrameProcessMode","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate":{"role":"symbol","title":"AgoraVideoFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"abstract":[{"type":"text","text":"The IVideoFrameObserver class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate/getVideoFrameProcessMode()":{"navigatorTitle":[{"kind":"identifier","text":"getVideoFrameProcessMode"}],"role":"symbol","title":"getVideoFrameProcessMode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVideoFrameProcessMode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AgoraVideoFrameProcessMode","preciseIdentifier":"c:@E@AgoraVideoFrameProcessMode"}],"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame and prompts you to set the"},{"type":"text","text":" "},{"type":"text","text":"process mode of the video frame. After you successfully register the video"},{"type":"text","text":" "},{"type":"text","text":"frame observer, the SDK triggers this callback each time it receives a video"},{"type":"text","text":" "},{"type":"text","text":"frame. You need to set your preferred process mode in the return value of"},{"type":"text","text":" "},{"type":"text","text":"this callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/getVideoFrameProcessMode()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoravideoframedelegate\/getvideoframeprocessmode()"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameProcessMode":{"role":"symbol","title":"AgoraVideoFrameProcessMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameProcessMode"}],"abstract":[{"type":"text","text":"The process mode of the video frame:"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameProcessMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameProcessMode"}],"url":"\/documentation\/agorartckit\/agoravideoframeprocessmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getVideoFrameProcessMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVideoFrameProcessMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameProcessMode","preciseIdentifier":"c:@E@AgoraVideoFrameProcessMode","text":"AgoraVideoFrameProcessMode"},{"kind":"text","text":") "},{"kind":"identifier","text":"getVideoFrameProcessMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/title","value":"AgoraVideoFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1getVideoFrameProcessMode()\/title","value":"getVideoFrameProcessMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1getVideoFrameProcessMode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVideoFrameProcessMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameProcessMode\/title","value":"AgoraVideoFrameProcessMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameProcessMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameProcessMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}