{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","text":"AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the video processing mode is AgoraVideoFrameProcessModeReadOnly : YES : Reserved for future use. NO : Reserved for future use. When the video processing mode is AgoraVideoFrameProcessModeReadWrite : YES : Sets the SDK to receive the video frame. NO : Sets the SDK to discard the video frame."}]}]},{"kind":"parameters","parameters":[{"name":"videoFrame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video frame. See AgoraOutputVideoFrame.The default value of the video frame data format obtained through this callback is as follows:iOS: cvPixelBuffer"}]}]},{"name":"sourceType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the video source. See AgoraVideoSourceType."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After you successfully register the video frame observer, the SDK triggers this callback each time it receives a video frame. In this callback, you can get the video data captured by the local camera. You can then pre-process the data according to your scenarios. Once the pre-processing is complete, you can directly modify videoFrame in this callback, and set the return value to YES to send the modified video data to the SDK. The video data that this callback gets has not been pre-processed, and is not watermarked, cropped, rotated or beautified. If the video data type you get is RGBA, the SDK does not support processing the data of the alpha channel."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/oncapture(_:sourcetype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/oncapture(_:sourcetype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/onCapture(_:sourceType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame captured by the local camera."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCapture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"onCapture(_:sourceType:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraVideoFrameDelegate(im)onCaptureVideoFrame:sourceType:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"onCaptureVideoFrame:sourceType:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate/onCapture(_:sourceType:)":{"role":"symbol","title":"onCapture(_:sourceType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCapture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame captured by the local camera."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/onCapture(_:sourceType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCaptureVideoFrame:sourceType:"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate\/oncapture(_:sourcetype:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoSourceType":{"role":"symbol","title":"AgoraVideoSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoSourceType"}],"abstract":[{"type":"text","text":"The type of the video source."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoSourceType"}],"url":"\/documentation\/agorartckit\/agoravideosourcetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraOutputVideoFrame":{"role":"symbol","title":"AgoraOutputVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"abstract":[{"type":"text","text":"Configurations of the video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"url":"\/documentation\/agorartckit\/agoraoutputvideoframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate":{"role":"symbol","title":"AgoraVideoFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"abstract":[{"type":"text","text":"The IVideoFrameObserver class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onCaptureVideoFrame:sourceType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCaptureVideoFrame:sourceType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCaptureVideoFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","text":"AgoraOutputVideoFrame"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"videoFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"sourceType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1onCapture(_:sourceType:)\/title","value":"onCaptureVideoFrame:sourceType:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1onCapture(_:sourceType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCaptureVideoFrame:sourceType:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/title","value":"AgoraVideoSourceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoSourceType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoSourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/title","value":"AgoraOutputVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/title","value":"AgoraVideoFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}