{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPreEncodeVideoFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","text":"AgoraOutputVideoFrame"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"videoFrame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the video processing mode is AgoraVideoFrameProcessModeReadOnly :"},{"type":"text","text":" "},{"type":"text","text":"YES : Reserved for future use."},{"type":"text","text":" "},{"type":"text","text":"NO : Reserved for future use. When the video processing mode is AgoraVideoFrameProcessModeReadWrite :"},{"type":"text","text":" "},{"type":"text","text":"YES : Sets the SDK to receive the video frame."},{"type":"text","text":" "},{"type":"text","text":"NO : Sets the SDK to discard the video frame."}]}]},{"kind":"parameters","parameters":[{"name":"videoFrame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video frame. See AgoraOutputVideoFrame.The default value of the video frame data format obtained through this callback is as follows:"},{"type":"text","text":" "},{"type":"text","text":"iOS: cvPixelBuffer"}]}]},{"name":"sourceType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the video source. See AgoraVideoSourceType."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After you successfully register the video frame observer, the SDK triggers this callback each time it receives a video frame. In this callback, you can get the video data before encoding and then process the data according to your particular scenarios. After processing, you can send the processed video data back to the SDK in this callback. To get the video data captured from the second screen before encoding, you need to set AgoraVideoFramePositionPreEncoder (1 << 2) as a frame position through getObservedFramePosition . The video data that this callback gets has been preprocessed, with its content cropped and rotated, and the image enhanced."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/onpreencodevideoframe:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/onPreEncodeVideoFrame:","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame before encoding."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onPreEncodeVideoFrame:"}],"role":"symbol","title":"onPreEncodeVideoFrame:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPreEncodeVideoFrame:"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraVideoFrameDelegate(im)onPreEncodeVideoFrame:","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraOutputVideoFrame":{"role":"symbol","title":"AgoraOutputVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"abstract":[{"type":"text","text":"Configurations of the video frame."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"url":"\/documentation\/agorartckit\/agoraoutputvideoframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate/onPreEncodeVideoFrame:":{"role":"symbol","title":"onPreEncodeVideoFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPreEncodeVideoFrame:"}],"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame before encoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/onPreEncodeVideoFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPreEncodeVideoFrame:"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate\/onpreencodevideoframe:"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate":{"role":"symbol","title":"AgoraVideoFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"abstract":[{"type":"text","text":"The IVideoFrameObserver class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/title","value":"AgoraOutputVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/title","value":"AgoraVideoFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}