{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderVideoFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"videoFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","text":"AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"videoFrame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video frame. See AgoraOutputVideoFrame .The"},{"type":"text","text":" "},{"type":"text","text":"default value of the video frame data format obtained through this callback"},{"type":"text","text":" "},{"type":"text","text":"is as follows:iOS: cvPixelBuffer"}]}]},{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID of the remote user who sends the current video"},{"type":"text","text":" "},{"type":"text","text":"frame."}]}]},{"name":"channelId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel ID."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the video processing mode is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFrameProcessModeReadOnly : YES : Reserved for future use. NO :"},{"type":"text","text":" "},{"type":"text","text":"Reserved for future use. When the video processing mode is"},{"type":"text","text":" "},{"type":"text","text":"AgoraVideoFrameProcessModeReadWrite : YES : Sets the SDK to receive the video"},{"type":"text","text":" "},{"type":"text","text":"frame. NO : Sets the SDK to discard the video frame."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/onrendervideoframe(_:uid:channelid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideoframedelegate\/onrendervideoframe(_:uid:channelid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/onRenderVideoFrame(_:uid:channelId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame sent by the remote user."},{"type":"text","text":" "},{"type":"text","text":"After you successfully register the video frame observer, the SDK triggers"},{"type":"text","text":" "},{"type":"text","text":"this callback each time it receives a video frame. In this callback, you can"},{"type":"text","text":" "},{"type":"text","text":"get the video data sent from the remote end before rendering, and then"},{"type":"text","text":" "},{"type":"text","text":"process it according to the particular scenarios.If the video data type you"},{"type":"text","text":" "},{"type":"text","text":"get is RGBA, the SDK does not support processing the data of the alpha"},{"type":"text","text":" "},{"type":"text","text":"channel."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onRenderVideoFrame:uid:channelId:"}],"role":"symbol","title":"onRenderVideoFrame(_:uid:channelId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderVideoFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraVideoFrameDelegate(im)onRenderVideoFrame:uid:channelId:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate":{"role":"symbol","title":"AgoraVideoFrameDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"abstract":[{"type":"text","text":"The IVideoFrameObserver class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}],"url":"\/documentation\/agorartckit\/agoravideoframedelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraOutputVideoFrame":{"role":"symbol","title":"AgoraOutputVideoFrame","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"abstract":[{"type":"text","text":"Configurations of the video frame."},{"type":"text","text":" "},{"type":"text","text":"Note that the buffer provides a pointer to a pointer. This interface cannot"},{"type":"text","text":" "},{"type":"text","text":"modify the pointer of the buffer, but it can modify the content of the"},{"type":"text","text":" "},{"type":"text","text":"buffer."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}],"url":"\/documentation\/agorartckit\/agoraoutputvideoframe"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoFrameDelegate/onRenderVideoFrame(_:uid:channelId:)":{"navigatorTitle":[{"kind":"identifier","text":"onRenderVideoFrame:uid:channelId:"}],"role":"symbol","title":"onRenderVideoFrame(_:uid:channelId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderVideoFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Occurs each time the SDK receives a video frame sent by the remote user."},{"type":"text","text":" "},{"type":"text","text":"After you successfully register the video frame observer, the SDK triggers"},{"type":"text","text":" "},{"type":"text","text":"this callback each time it receives a video frame. In this callback, you can"},{"type":"text","text":" "},{"type":"text","text":"get the video data sent from the remote end before rendering, and then"},{"type":"text","text":" "},{"type":"text","text":"process it according to the particular scenarios.If the video data type you"},{"type":"text","text":" "},{"type":"text","text":"get is RGBA, the SDK does not support processing the data of the alpha"},{"type":"text","text":" "},{"type":"text","text":"channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoFrameDelegate\/onRenderVideoFrame(_:uid:channelId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoravideoframedelegate\/onrendervideoframe(_:uid:channelid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onRenderVideoFrame:uid:channelId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRenderVideoFrame:uid:channelId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"onRenderVideoFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","text":"AgoraOutputVideoFrame"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"uid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"channelId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/title","value":"AgoraVideoFrameDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraVideoFrameDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/title","value":"AgoraOutputVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraOutputVideoFrame\/fragments","value":[{"kind":"identifier","text":"AgoraOutputVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1onRenderVideoFrame(_:uid:channelId:)\/title","value":"onRenderVideoFrame:uid:channelId:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoFrameDelegate~1onRenderVideoFrame(_:uid:channelId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRenderVideoFrame:uid:channelId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}