{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"greenCapacity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorasegmentationproperty\/greencapacity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorasegmentationproperty\/greencapacity"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty\/greenCapacity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The range of accuracy for identifying green colors (different shades of"},{"type":"text","text":" "},{"type":"text","text":"green) in the view. The value range is [0,1], and the default value is 0.5."},{"type":"text","text":" "},{"type":"text","text":"The larger the value, the wider the range of identifiable shades of green."},{"type":"text","text":" "},{"type":"text","text":"When the value of this parameter is too large, the edge of the portrait and"},{"type":"text","text":" "},{"type":"text","text":"the green color in the portrait range are also detected. Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"that you dynamically adjust the value of this parameter according to the"},{"type":"text","text":" "},{"type":"text","text":"actual effect.This parameter only takes effect when modelType is set to"},{"type":"text","text":" "},{"type":"text","text":"SegModelAgoraGreen."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"greenCapacity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"greenCapacity","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSegmentationProperty(py)greenCapacity","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"greenCapacity"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSegmentationProperty/greenCapacity":{"role":"symbol","title":"greenCapacity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"greenCapacity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The range of accuracy for identifying green colors (different shades of"},{"type":"text","text":" "},{"type":"text","text":"green) in the view. The value range is [0,1], and the default value is 0.5."},{"type":"text","text":" "},{"type":"text","text":"The larger the value, the wider the range of identifiable shades of green."},{"type":"text","text":" "},{"type":"text","text":"When the value of this parameter is too large, the edge of the portrait and"},{"type":"text","text":" "},{"type":"text","text":"the green color in the portrait range are also detected. Agora recommends"},{"type":"text","text":" "},{"type":"text","text":"that you dynamically adjust the value of this parameter according to the"},{"type":"text","text":" "},{"type":"text","text":"actual effect.This parameter only takes effect when modelType is set to"},{"type":"text","text":" "},{"type":"text","text":"SegModelAgoraGreen."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty\/greenCapacity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"greenCapacity"}],"url":"\/documentation\/agorartckit\/agorasegmentationproperty\/greencapacity"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSegmentationProperty":{"role":"symbol","title":"AgoraSegmentationProperty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSegmentationProperty"}],"abstract":[{"type":"text","text":"Processing properties for background images."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSegmentationProperty"}],"url":"\/documentation\/agorartckit\/agorasegmentationproperty"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"greenCapacity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"greenCapacity"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"greenCapacity"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty~1greenCapacity\/title","value":"greenCapacity"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty~1greenCapacity\/fragments","value":[{"kind":"identifier","text":"greenCapacity"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty\/title","value":"AgoraSegmentationProperty"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty\/fragments","value":[{"kind":"identifier","text":"AgoraSegmentationProperty"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}