{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/SegModelType","preciseIdentifier":"c:@E@SegModelType","text":"SegModelType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorasegmentationproperty\/modeltype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorasegmentationproperty\/modeltype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty\/modelType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of algorithms to user for background processing. See SegModelType ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SegModelType","preciseIdentifier":"c:@E@SegModelType"}],"title":"modelType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSegmentationProperty(py)modelType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"modelType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSegmentationProperty":{"role":"symbol","title":"AgoraSegmentationProperty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSegmentationProperty"}],"abstract":[{"type":"text","text":"Processing properties for background images."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSegmentationProperty"}],"url":"\/documentation\/agorartckit\/agorasegmentationproperty"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/SegModelType":{"role":"symbol","title":"SegModelType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegModelType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/SegModelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegModelType"}],"url":"\/documentation\/agorartckit\/segmodeltype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSegmentationProperty/modelType":{"role":"symbol","title":"modelType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SegModelType","preciseIdentifier":"c:@E@SegModelType"}],"abstract":[{"type":"text","text":"The type of algorithms to user for background processing. See SegModelType ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSegmentationProperty\/modelType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modelType"}],"url":"\/documentation\/agorartckit\/agorasegmentationproperty\/modeltype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"modelType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"modelType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/SegModelType","preciseIdentifier":"c:@E@SegModelType","text":"SegModelType"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty\/title","value":"AgoraSegmentationProperty"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty\/fragments","value":[{"kind":"identifier","text":"AgoraSegmentationProperty"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1SegModelType\/title","value":"SegModelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1SegModelType\/fragments","value":[{"kind":"identifier","text":"SegModelType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty~1modelType\/title","value":"modelType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSegmentationProperty~1modelType\/fragments","value":[{"kind":"identifier","text":"modelType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}