{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheStatusType","preciseIdentifier":"c:@E@AgoraMusicCacheStatusType","text":"AgoraMusicCacheStatusType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoramusiccacheinfo\/statustype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoramusiccacheinfo\/statustype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/statusType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicCacheStatusType","preciseIdentifier":"c:@E@AgoraMusicCacheStatusType"}],"title":"statusType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraMusicCacheInfo(py)statusType","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"statusType"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicCacheInfo/statusType":{"role":"symbol","title":"statusType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraMusicCacheStatusType","preciseIdentifier":"c:@E@AgoraMusicCacheStatusType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo\/statusType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusType"}],"url":"\/documentation\/agorartckit\/agoramusiccacheinfo\/statustype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicCacheStatusType":{"role":"symbol","title":"AgoraMusicCacheStatusType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicCacheStatusType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheStatusType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicCacheStatusType"}],"url":"\/documentation\/agorartckit\/agoramusiccachestatustype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraMusicCacheInfo":{"role":"symbol","title":"AgoraMusicCacheInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraMusicCacheInfo"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraMusicCacheInfo"}],"url":"\/documentation\/agorartckit\/agoramusiccacheinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"statusType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"statusType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraMusicCacheStatusType","preciseIdentifier":"c:@E@AgoraMusicCacheStatusType","text":"AgoraMusicCacheStatusType"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo~1statusType\/title","value":"statusType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo~1statusType\/fragments","value":[{"kind":"identifier","text":"statusType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheStatusType\/title","value":"AgoraMusicCacheStatusType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheStatusType\/fragments","value":[{"kind":"identifier","text":"AgoraMusicCacheStatusType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo\/title","value":"AgoraMusicCacheInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraMusicCacheInfo\/fragments","value":[{"kind":"identifier","text":"AgoraMusicCacheInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}