{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPublished"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorastreampublishstate\/nopublished"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorastreampublishstate\/nopublished"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/noPublished","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: Fails to publish the local stream. Possible reasons:The local user calls"},{"type":"text","text":" "},{"type":"text","text":"muteLocalAudioStream (YES) or muteLocalVideoStream (YES) to stop sending"},{"type":"text","text":" "},{"type":"text","text":"local media streams.The local user calls disableAudio or disableVideo to"},{"type":"text","text":" "},{"type":"text","text":"disable the local audio or video module.The local user calls"},{"type":"text","text":" "},{"type":"text","text":"enableLocalAudio (NO) or enableLocalVideo (NO) to disable the local audio"},{"type":"text","text":" "},{"type":"text","text":"or video capture.The role of the local user is audience."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPublished"}],"title":"AgoraStreamPublishState.noPublished","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraStreamPublishState@AgoraStreamPublishStateNoPublished","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishStateNoPublished"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState/noPublished":{"role":"symbol","title":"AgoraStreamPublishState.noPublished","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noPublished"}],"abstract":[{"type":"text","text":"1: Fails to publish the local stream. Possible reasons:The local user calls"},{"type":"text","text":" "},{"type":"text","text":"muteLocalAudioStream (YES) or muteLocalVideoStream (YES) to stop sending"},{"type":"text","text":" "},{"type":"text","text":"local media streams.The local user calls disableAudio or disableVideo to"},{"type":"text","text":" "},{"type":"text","text":"disable the local audio or video module.The local user calls"},{"type":"text","text":" "},{"type":"text","text":"enableLocalAudio (NO) or enableLocalVideo (NO) to disable the local audio"},{"type":"text","text":" "},{"type":"text","text":"or video capture.The role of the local user is audience."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState\/noPublished","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishStateNoPublished"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate\/nopublished"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraStreamPublishState":{"role":"symbol","title":"AgoraStreamPublishState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraStreamPublishState"}],"abstract":[{"type":"text","text":"The publishing state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraStreamPublishState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraStreamPublishState"}],"url":"\/documentation\/agorartckit\/agorastreampublishstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraStreamPublishStateNoPublished"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishStateNoPublished"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraStreamPublishStateNoPublished"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1noPublished\/title","value":"AgoraStreamPublishStateNoPublished"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState~1noPublished\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishStateNoPublished"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState\/title","value":"AgoraStreamPublishState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraStreamPublishState\/fragments","value":[{"kind":"identifier","text":"AgoraStreamPublishState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}