{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskHwEnc"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracodeccapmask\/maskhwenc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracodeccapmask\/maskhwenc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwEnc","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskHwEnc"}],"title":"AgoraCodecCapMask.maskHwEnc","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCodecCapMask@AgoraCodecMaskHwEnc","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskHwEnc"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask":{"role":"symbol","title":"AgoraCodecCapMask","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCodecCapMask"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecCapMask"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskHwEnc":{"role":"symbol","title":"AgoraCodecCapMask.maskHwEnc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskHwEnc"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskHwEnc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskHwEnc"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/maskhwenc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCodecMaskHwEnc"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskHwEnc"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCodecMaskHwEnc"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/title","value":"AgoraCodecCapMask"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/fragments","value":[{"kind":"identifier","text":"AgoraCodecCapMask"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskHwEnc\/title","value":"AgoraCodecMaskHwEnc"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskHwEnc\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskHwEnc"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}