{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwEnc"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracodeccapmask\/maskswenc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracodeccapmask\/maskswenc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwEnc","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwEnc"}],"title":"AgoraCodecCapMask.maskSwEnc","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCodecCapMask@AgoraCodecMaskSwEnc","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskSwEnc"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask":{"role":"symbol","title":"AgoraCodecCapMask","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCodecCapMask"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecCapMask"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskSwEnc":{"role":"symbol","title":"AgoraCodecCapMask.maskSwEnc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwEnc"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwEnc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskSwEnc"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/maskswenc"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCodecMaskSwEnc"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskSwEnc"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCodecMaskSwEnc"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/title","value":"AgoraCodecCapMask"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/fragments","value":[{"kind":"identifier","text":"AgoraCodecCapMask"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwEnc\/title","value":"AgoraCodecMaskSwEnc"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwEnc\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskSwEnc"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}