{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwDec"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoracodeccapmask\/maskswdec"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoracodeccapmask\/maskswdec"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwDec","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"(1 << 2): The device supports software decoding."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwDec"}],"title":"AgoraCodecCapMask.maskSwDec","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraCodecCapMask@AgoraCodecMaskSwDec","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskSwDec"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask":{"role":"symbol","title":"AgoraCodecCapMask","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraCodecCapMask"}],"abstract":[{"type":"text","text":"The bit mask that indicates the device codec capability."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecCapMask"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraCodecCapMask/maskSwDec":{"role":"symbol","title":"AgoraCodecCapMask.maskSwDec","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskSwDec"}],"abstract":[{"type":"text","text":"(1 << 2): The device supports software decoding."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraCodecCapMask\/maskSwDec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraCodecMaskSwDec"}],"url":"\/documentation\/agorartckit\/agoracodeccapmask\/maskswdec"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraCodecMaskSwDec"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskSwDec"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraCodecMaskSwDec"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/title","value":"AgoraCodecCapMask"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask\/fragments","value":[{"kind":"identifier","text":"AgoraCodecCapMask"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwDec\/title","value":"AgoraCodecMaskSwDec"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraCodecCapMask~1maskSwDec\/fragments","value":[{"kind":"identifier","text":"AgoraCodecMaskSwDec"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}