{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admImproperSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorawarningcode\/admimpropersettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorawarningcode\/admimpropersettings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admImproperSettings","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admImproperSettings"}],"title":"AgoraWarningCode.admImproperSettings","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraWarningCode@AgoraWarningCodeAdmImproperSettings","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmImproperSettings"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode/admImproperSettings":{"role":"symbol","title":"AgoraWarningCode.admImproperSettings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"admImproperSettings"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode\/admImproperSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCodeAdmImproperSettings"}],"url":"\/documentation\/agorartckit\/agorawarningcode\/admimpropersettings"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraWarningCode":{"role":"symbol","title":"AgoraWarningCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraWarningCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraWarningCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraWarningCode"}],"url":"\/documentation\/agorartckit\/agorawarningcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraWarningCodeAdmImproperSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmImproperSettings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraWarningCodeAdmImproperSettings"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admImproperSettings\/title","value":"AgoraWarningCodeAdmImproperSettings"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode~1admImproperSettings\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCodeAdmImproperSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode\/title","value":"AgoraWarningCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraWarningCode\/fragments","value":[{"kind":"identifier","text":"AgoraWarningCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}