{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureFailure"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturefailure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturefailure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureFailure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: The local video capture fails. Remind your user to check whether the video capture device is working properly, whether the camera is occupied by another application, or try to rejoin the channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureFailure"}],"title":"AgoraLocalVideoStreamError.captureFailure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLocalVideoStreamError@AgoraLocalVideoStreamErrorCaptureFailure","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureFailure"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureFailure":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureFailure"}],"abstract":[{"type":"text","text":"4: The local video capture fails. Remind your user to check whether the video capture device is working properly, whether the camera is occupied by another application, or try to rejoin the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureFailure"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturefailure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError":{"role":"symbol","title":"AgoraLocalVideoStreamError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"abstract":[{"type":"text","text":"Local video state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalVideoStreamErrorCaptureFailure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureFailure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureFailure"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureFailure\/title","value":"AgoraLocalVideoStreamErrorCaptureFailure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureFailure\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/title","value":"AgoraLocalVideoStreamError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}