{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDeviceDisconnected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturedevicedisconnected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturedevicedisconnected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceDisconnected","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDeviceDisconnected"}],"title":"AgoraLocalVideoStreamError.captureDeviceDisconnected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLocalVideoStreamError@AgoraLocalVideoStreamErrorCaptureDeviceDisconnected","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError":{"role":"symbol","title":"AgoraLocalVideoStreamError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"abstract":[{"type":"text","text":"Local video state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/captureDeviceDisconnected":{"role":"symbol","title":"AgoraLocalVideoStreamError.captureDeviceDisconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDeviceDisconnected"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/captureDeviceDisconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/capturedevicedisconnected"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/title","value":"AgoraLocalVideoStreamError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureDeviceDisconnected\/title","value":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1captureDeviceDisconnected\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorCaptureDeviceDisconnected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}