{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNoPermission"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/devicenopermission"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/devicenopermission"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceNoPermission","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: No permission to use the local video capturing device. Remind the user to grant permissions and rejoin the channel.Deprecated:This enumerator is deprecated. Please use AgoraPermissionTypeCamera in the permissionError callback instead."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNoPermission"}],"title":"AgoraLocalVideoStreamError.deviceNoPermission","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLocalVideoStreamError@AgoraLocalVideoStreamErrorDeviceNoPermission","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceNoPermission"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/deviceNoPermission":{"role":"symbol","title":"AgoraLocalVideoStreamError.deviceNoPermission","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNoPermission"}],"abstract":[{"type":"text","text":"2: No permission to use the local video capturing device. Remind the user to grant permissions and rejoin the channel.Deprecated:This enumerator is deprecated. Please use AgoraPermissionTypeCamera in the permissionError callback instead."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/deviceNoPermission","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceNoPermission"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/devicenopermission"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError":{"role":"symbol","title":"AgoraLocalVideoStreamError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"abstract":[{"type":"text","text":"Local video state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalVideoStreamErrorDeviceNoPermission"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceNoPermission"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceNoPermission"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1deviceNoPermission\/title","value":"AgoraLocalVideoStreamErrorDeviceNoPermission"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1deviceNoPermission\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorDeviceNoPermission"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/title","value":"AgoraLocalVideoStreamError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}