{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/failure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/failure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/failure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: No specified reason for the local video failure."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"title":"AgoraLocalVideoStreamError.failure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLocalVideoStreamError@AgoraLocalVideoStreamErrorFailure","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorFailure"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError":{"role":"symbol","title":"AgoraLocalVideoStreamError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"abstract":[{"type":"text","text":"Local video state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/failure":{"role":"symbol","title":"AgoraLocalVideoStreamError.failure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"abstract":[{"type":"text","text":"1: No specified reason for the local video failure."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/failure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorFailure"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/failure"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalVideoStreamErrorFailure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorFailure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorFailure"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/title","value":"AgoraLocalVideoStreamError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1failure\/title","value":"AgoraLocalVideoStreamErrorFailure"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1failure\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}