{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/ok"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalvideostreamerror\/ok"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/OK","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: The local video is normal."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"title":"AgoraLocalVideoStreamError.OK","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLocalVideoStreamError@AgoraLocalVideoStreamErrorOK","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorOK"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError/OK":{"role":"symbol","title":"AgoraLocalVideoStreamError.OK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OK"}],"abstract":[{"type":"text","text":"0: The local video is normal."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError\/OK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorOK"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror\/ok"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalVideoStreamError":{"role":"symbol","title":"AgoraLocalVideoStreamError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"abstract":[{"type":"text","text":"Local video state error codes."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalVideoStreamError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}],"url":"\/documentation\/agorartckit\/agoralocalvideostreamerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLocalVideoStreamErrorOK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorOK"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorOK"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1OK\/title","value":"AgoraLocalVideoStreamErrorOK"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError~1OK\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamErrorOK"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/title","value":"AgoraLocalVideoStreamError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalVideoStreamError\/fragments","value":[{"kind":"identifier","text":"AgoraLocalVideoStreamError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}