{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"erroExceedLimitation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/erroexceedlimitation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/erroexceedlimitation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/erroExceedLimitation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"erroExceedLimitation"}],"title":"AgoraRtmStreamChannelErrorCode.erroExceedLimitation","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmStreamChannelErrorCode@AgoraRtmStreamChannelErroExceedLimitation","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErroExceedLimitation"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode/erroExceedLimitation":{"role":"symbol","title":"AgoraRtmStreamChannelErrorCode.erroExceedLimitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"erroExceedLimitation"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode\/erroExceedLimitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErroExceedLimitation"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode\/erroexceedlimitation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode":{"role":"symbol","title":"AgoraRtmStreamChannelErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmStreamChannelErroExceedLimitation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErroExceedLimitation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmStreamChannelErroExceedLimitation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1erroExceedLimitation\/title","value":"AgoraRtmStreamChannelErroExceedLimitation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode~1erroExceedLimitation\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErroExceedLimitation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode\/title","value":"AgoraRtmStreamChannelErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}