{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayRtt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelstats\/gatewayrtt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelstats\/gatewayrtt"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/gatewayRtt","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The round-trip time delay (ms) from the client to the local router.This"},{"type":"text","text":" "},{"type":"text","text":"property is disabled on devices running iOS 14 or later, and enabled on"},{"type":"text","text":" "},{"type":"text","text":"devices running versions earlier than iOS 14 by default.To enable this"},{"type":"text","text":" "},{"type":"text","text":"property on devices running iOS 14 or later, ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayRtt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"gatewayRtt","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChannelStats(py)gatewayRtt","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"gatewayRtt"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats":{"role":"symbol","title":"AgoraChannelStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelStats"}],"abstract":[{"type":"text","text":"Statistics of the channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelStats"}],"url":"\/documentation\/agorartckit\/agorachannelstats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelStats/gatewayRtt":{"role":"symbol","title":"gatewayRtt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayRtt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The round-trip time delay (ms) from the client to the local router.This"},{"type":"text","text":" "},{"type":"text","text":"property is disabled on devices running iOS 14 or later, and enabled on"},{"type":"text","text":" "},{"type":"text","text":"devices running versions earlier than iOS 14 by default.To enable this"},{"type":"text","text":" "},{"type":"text","text":"property on devices running iOS 14 or later, ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelStats\/gatewayRtt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gatewayRtt"}],"url":"\/documentation\/agorartckit\/agorachannelstats\/gatewayrtt"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"gatewayRtt"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"gatewayRtt"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"gatewayRtt"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/title","value":"AgoraChannelStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats\/fragments","value":[{"kind":"identifier","text":"AgoraChannelStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1gatewayRtt\/title","value":"gatewayRtt"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelStats~1gatewayRtt\/fragments","value":[{"kind":"identifier","text":"gatewayRtt"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}