{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioAttenuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraspatialaudiozone\/audioattenuation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraspatialaudiozone\/audioattenuation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone\/audioAttenuation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The sound attenuation coefficient when users within the sound insulation area"},{"type":"text","text":" "},{"type":"text","text":"communicate with external users. The value range is [0,1]. The values are as"},{"type":"text","text":" "},{"type":"text","text":"follows:0: Broadcast mode, where the volume and timbre are not attenuated"},{"type":"text","text":" "},{"type":"text","text":"with distance, and the volume and timbre heard by local users do not change"},{"type":"text","text":" "},{"type":"text","text":"regardless of distance.(0,0.5): Weak attenuation mode, that is, the volume"},{"type":"text","text":" "},{"type":"text","text":"and timbre are only weakly attenuated during the propagation process, and the"},{"type":"text","text":" "},{"type":"text","text":"sound can travel farther than the real environment.0.5: (Default) simulates"},{"type":"text","text":" "},{"type":"text","text":"the attenuation of the volume in the real environment; the effect is"},{"type":"text","text":" "},{"type":"text","text":"equivalent to not setting the audioAttenuation parameter.(0.5,1]: Strong"},{"type":"text","text":" "},{"type":"text","text":"attenuation mode (default value is 1), that is, the volume and timbre"},{"type":"text","text":" "},{"type":"text","text":"attenuate rapidly during propagation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioAttenuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"audioAttenuation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSpatialAudioZone(py)audioAttenuation","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"audioAttenuation"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioZone/audioAttenuation":{"role":"symbol","title":"audioAttenuation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioAttenuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The sound attenuation coefficient when users within the sound insulation area"},{"type":"text","text":" "},{"type":"text","text":"communicate with external users. The value range is [0,1]. The values are as"},{"type":"text","text":" "},{"type":"text","text":"follows:0: Broadcast mode, where the volume and timbre are not attenuated"},{"type":"text","text":" "},{"type":"text","text":"with distance, and the volume and timbre heard by local users do not change"},{"type":"text","text":" "},{"type":"text","text":"regardless of distance.(0,0.5): Weak attenuation mode, that is, the volume"},{"type":"text","text":" "},{"type":"text","text":"and timbre are only weakly attenuated during the propagation process, and the"},{"type":"text","text":" "},{"type":"text","text":"sound can travel farther than the real environment.0.5: (Default) simulates"},{"type":"text","text":" "},{"type":"text","text":"the attenuation of the volume in the real environment; the effect is"},{"type":"text","text":" "},{"type":"text","text":"equivalent to not setting the audioAttenuation parameter.(0.5,1]: Strong"},{"type":"text","text":" "},{"type":"text","text":"attenuation mode (default value is 1), that is, the volume and timbre"},{"type":"text","text":" "},{"type":"text","text":"attenuate rapidly during propagation."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone\/audioAttenuation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioAttenuation"}],"url":"\/documentation\/agorartckit\/agoraspatialaudiozone\/audioattenuation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioZone":{"role":"symbol","title":"AgoraSpatialAudioZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioZone"}],"abstract":[{"type":"text","text":"Sound insulation area settings."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioZone"}],"url":"\/documentation\/agorartckit\/agoraspatialaudiozone"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audioAttenuation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioAttenuation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioAttenuation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone~1audioAttenuation\/title","value":"audioAttenuation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone~1audioAttenuation\/fragments","value":[{"kind":"identifier","text":"audioAttenuation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone\/title","value":"AgoraSpatialAudioZone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioZone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}