{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"up"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraspatialaudiozone\/up"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraspatialaudiozone\/up"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone\/up","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starting at position, the up unit vector. This parameter is an array of"},{"type":"text","text":" "},{"type":"text","text":"length 3, and the three values represent the front, right, and top"},{"type":"text","text":" "},{"type":"text","text":"coordinates in turn."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"up"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"title":"up","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSpatialAudioZone(py)up","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"up"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioZone":{"role":"symbol","title":"AgoraSpatialAudioZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioZone"}],"abstract":[{"type":"text","text":"Sound insulation area settings."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioZone"}],"url":"\/documentation\/agorartckit\/agoraspatialaudiozone"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioZone/up":{"role":"symbol","title":"up","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"up"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Starting at position, the up unit vector. This parameter is an array of"},{"type":"text","text":" "},{"type":"text","text":"length 3, and the three values represent the front, right, and top"},{"type":"text","text":" "},{"type":"text","text":"coordinates in turn."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone\/up","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"up"}],"url":"\/documentation\/agorartckit\/agoraspatialaudiozone\/up"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"up"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"up"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"up"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone\/title","value":"AgoraSpatialAudioZone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioZone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone~1up\/title","value":"up"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone~1up\/fragments","value":[{"kind":"identifier","text":"up"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}