{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode","text":"AgoraVideoRenderMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartcvideocompositingregion\/rendermode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartcvideocompositingregion\/rendermode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCompositingRegion\/renderMode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"renderMode"}],"role":"symbol","title":"renderMode","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"}],"symbolKind":"property","externalID":"c:objc(cs)AgoraRtcVideoCompositingRegion(py)renderMode","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCompositingRegion"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoRenderMode":{"role":"symbol","title":"AgoraVideoRenderMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoRenderMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoRenderMode"}],"url":"\/documentation\/agorartckit\/agoravideorendermode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCompositingRegion":{"deprecated":true,"role":"symbol","title":"AgoraRtcVideoCompositingRegion","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcVideoCompositingRegion"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCompositingRegion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcVideoCompositingRegion"}],"url":"\/documentation\/agorartckit\/agorartcvideocompositingregion"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcVideoCompositingRegion/renderMode":{"deprecated":true,"role":"symbol","title":"renderMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcVideoCompositingRegion\/renderMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"renderMode"}],"url":"\/documentation\/agorartckit\/agorartcvideocompositingregion\/rendermode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"renderMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"renderMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoRenderMode","preciseIdentifier":"c:@E@AgoraVideoRenderMode","text":"AgoraVideoRenderMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/title","value":"AgoraVideoRenderMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoRenderMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoRenderMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCompositingRegion\/title","value":"AgoraRtcVideoCompositingRegion"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCompositingRegion\/fragments","value":[{"kind":"identifier","text":"AgoraRtcVideoCompositingRegion"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCompositingRegion~1renderMode\/title","value":"renderMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcVideoCompositingRegion~1renderMode\/fragments","value":[{"kind":"identifier","text":"renderMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}