{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonKeepAliveTimeout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonkeepalivetimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonkeepalivetimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonKeepAliveTimeout","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonKeepAliveTimeout"}],"title":"AgoraConnectionChangedReason.reasonKeepAliveTimeout","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraConnectionChangedReason@AgoraConnectionChangedReasonKeepAliveTimeout","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonKeepAliveTimeout"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason":{"role":"symbol","title":"AgoraConnectionChangedReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraConnectionChangedReason"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReason"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraConnectionChangedReason/reasonKeepAliveTimeout":{"role":"symbol","title":"AgoraConnectionChangedReason.reasonKeepAliveTimeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reasonKeepAliveTimeout"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraConnectionChangedReason\/reasonKeepAliveTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraConnectionChangedReasonKeepAliveTimeout"}],"url":"\/documentation\/agorartckit\/agoraconnectionchangedreason\/reasonkeepalivetimeout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraConnectionChangedReasonKeepAliveTimeout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonKeepAliveTimeout"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraConnectionChangedReasonKeepAliveTimeout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason\/title","value":"AgoraConnectionChangedReason"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReason"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonKeepAliveTimeout\/title","value":"AgoraConnectionChangedReasonKeepAliveTimeout"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraConnectionChangedReason~1reasonKeepAliveTimeout\/fragments","value":[{"kind":"identifier","text":"AgoraConnectionChangedReasonKeepAliveTimeout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}