{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noiseSuppression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType","text":"AgoraEarMonitoringFilterType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/noisesuppression"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/noisesuppression"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/noiseSuppression","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noiseSuppression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType"}],"title":"noiseSuppression","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@AgoraEarMonitoringFilterType@AgoraEarMonitoringFilterNoiseSuppression","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNoiseSuppression"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType/noiseSuppression":{"role":"symbol","title":"noiseSuppression","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noiseSuppression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraEarMonitoringFilterType","preciseIdentifier":"c:@E@AgoraEarMonitoringFilterType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType\/noiseSuppression","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNoiseSuppression"}],"url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype\/noisesuppression"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraEarMonitoringFilterType":{"role":"symbol","title":"AgoraEarMonitoringFilterType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraEarMonitoringFilterType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}],"url":"\/documentation\/agorartckit\/agoraearmonitoringfiltertype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraEarMonitoringFilterNoiseSuppression"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNoiseSuppression"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNoiseSuppression"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1noiseSuppression\/title","value":"AgoraEarMonitoringFilterNoiseSuppression"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType~1noiseSuppression\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterNoiseSuppression"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType\/title","value":"AgoraEarMonitoringFilterType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraEarMonitoringFilterType\/fragments","value":[{"kind":"identifier","text":"AgoraEarMonitoringFilterType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}