{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type2G"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoranetworktype\/type2g"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoranetworktype\/type2g"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type2G","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The network type is mobile 2G."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type2G"}],"title":"AgoraNetworkType.type2G","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraNetworkType@AgoraNetworkType2G","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType2G"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType":{"role":"symbol","title":"AgoraNetworkType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkType"}],"abstract":[{"type":"text","text":"Network type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType"}],"url":"\/documentation\/agorartckit\/agoranetworktype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/type2G":{"role":"symbol","title":"AgoraNetworkType.type2G","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"type2G"}],"abstract":[{"type":"text","text":"3: The network type is mobile 2G."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/type2G","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType2G"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/type2g"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraNetworkType2G"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType2G"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraNetworkType2G"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType\/title","value":"AgoraNetworkType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type2G\/title","value":"AgoraNetworkType2G"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1type2G\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType2G"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}