{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWIFI"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoranetworktype\/typewifi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoranetworktype\/typewifi"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeWIFI","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: The network type is Wi-Fi (including hotspots)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWIFI"}],"title":"AgoraNetworkType.typeWIFI","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraNetworkType@AgoraNetworkTypeWIFI","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkTypeWIFI"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType/typeWIFI":{"role":"symbol","title":"AgoraNetworkType.typeWIFI","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeWIFI"}],"abstract":[{"type":"text","text":"2: The network type is Wi-Fi (including hotspots)."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType\/typeWIFI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkTypeWIFI"}],"url":"\/documentation\/agorartckit\/agoranetworktype\/typewifi"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkType":{"role":"symbol","title":"AgoraNetworkType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkType"}],"abstract":[{"type":"text","text":"Network type."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkType"}],"url":"\/documentation\/agorartckit\/agoranetworktype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraNetworkTypeWIFI"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkTypeWIFI"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraNetworkTypeWIFI"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeWIFI\/title","value":"AgoraNetworkTypeWIFI"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType~1typeWIFI\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkTypeWIFI"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType\/title","value":"AgoraNetworkType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkType\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}