{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideostreamtype\/high"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideostreamtype\/high"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoStreamType\/high","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: High-quality video stream."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"title":"AgoraVideoStreamType.high","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoStreamType@AgoraVideoStreamTypeHigh","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoStreamTypeHigh"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoStreamType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoStreamType":{"role":"symbol","title":"AgoraVideoStreamType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoStreamType"}],"abstract":[{"type":"text","text":"The type of video streams."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoStreamType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoStreamType"}],"url":"\/documentation\/agorartckit\/agoravideostreamtype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoStreamType/high":{"role":"symbol","title":"AgoraVideoStreamType.high","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"high"}],"abstract":[{"type":"text","text":"0: High-quality video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoStreamType\/high","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoStreamTypeHigh"}],"url":"\/documentation\/agorartckit\/agoravideostreamtype\/high"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoStreamTypeHigh"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoStreamTypeHigh"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoStreamTypeHigh"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoStreamType\/title","value":"AgoraVideoStreamType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoStreamType\/fragments","value":[{"kind":"identifier","text":"AgoraVideoStreamType"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoStreamType~1high\/title","value":"AgoraVideoStreamTypeHigh"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoStreamType~1high\/fragments","value":[{"kind":"identifier","text":"AgoraVideoStreamTypeHigh"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}