{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lifeCycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle","preciseIdentifier":"c:@E@AgoraRtmpStreamLifeCycle","text":"AgoraRtmpStreamLifeCycle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorapublisherconfiguration\/lifecycle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorapublisherconfiguration\/lifecycle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/lifeCycle","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"lifeCycle"}],"role":"symbol","title":"lifeCycle","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lifeCycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamLifeCycle","preciseIdentifier":"c:@E@AgoraRtmpStreamLifeCycle"}],"symbolKind":"property","externalID":"c:objc(cs)AgoraPublisherConfiguration(py)lifeCycle","modules":[{"name":"AgoraRtcKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration/lifeCycle":{"deprecated":true,"role":"symbol","title":"lifeCycle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lifeCycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmpStreamLifeCycle","preciseIdentifier":"c:@E@AgoraRtmpStreamLifeCycle"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration\/lifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lifeCycle"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration\/lifecycle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraPublisherConfiguration":{"deprecated":true,"role":"symbol","title":"AgoraPublisherConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraPublisherConfiguration"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraPublisherConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraPublisherConfiguration"}],"url":"\/documentation\/agorartckit\/agorapublisherconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamLifeCycle":{"role":"symbol","title":"AgoraRtmpStreamLifeCycle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}],"abstract":[{"type":"text","text":"Lifecycle of the CDN live video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}],"url":"\/documentation\/agorartckit\/agorartmpstreamlifecycle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lifeCycle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"lifeCycle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle","preciseIdentifier":"c:@E@AgoraRtmpStreamLifeCycle","text":"AgoraRtmpStreamLifeCycle"},{"kind":"text","text":" "},{"kind":"identifier","text":"lifeCycle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1lifeCycle\/title","value":"lifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration~1lifeCycle\/fragments","value":[{"kind":"identifier","text":"lifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration\/title","value":"AgoraPublisherConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraPublisherConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraPublisherConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle\/title","value":"AgoraRtmpStreamLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}