{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideocontenthint\/details"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideocontenthint\/details"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint\/details","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Motionless content. Choose this option if you prefer sharpness or when you are sharing a picture, PowerPoint slides, or texts."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"}],"title":"AgoraVideoContentHint.details","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoContentHint@AgoraVideoContentHintDetails","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoContentHintDetails"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoContentHint/details":{"role":"symbol","title":"AgoraVideoContentHint.details","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"}],"abstract":[{"type":"text","text":"Motionless content. Choose this option if you prefer sharpness or when you are sharing a picture, PowerPoint slides, or texts."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint\/details","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoContentHintDetails"}],"url":"\/documentation\/agorartckit\/agoravideocontenthint\/details"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoContentHint":{"role":"symbol","title":"AgoraVideoContentHint","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoContentHint"}],"abstract":[{"type":"text","text":"The content hint for screen sharing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoContentHint"}],"url":"\/documentation\/agorartckit\/agoravideocontenthint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoContentHintDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoContentHintDetails"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoContentHintDetails"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint~1details\/title","value":"AgoraVideoContentHintDetails"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint~1details\/fragments","value":[{"kind":"identifier","text":"AgoraVideoContentHintDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint\/title","value":"AgoraVideoContentHint"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint\/fragments","value":[{"kind":"identifier","text":"AgoraVideoContentHint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}