{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"motion"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideocontenthint\/motion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideocontenthint\/motion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint\/motion","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Motion-intensive content. Choose this option if you prefer smoothness or"},{"type":"text","text":" "},{"type":"text","text":"when you are sharing a video clip, movie, or video game."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"motion"}],"title":"AgoraVideoContentHint.motion","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoContentHint@AgoraVideoContentHintMotion","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoContentHintMotion"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoContentHint/motion":{"role":"symbol","title":"AgoraVideoContentHint.motion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"motion"}],"abstract":[{"type":"text","text":"Motion-intensive content. Choose this option if you prefer smoothness or"},{"type":"text","text":" "},{"type":"text","text":"when you are sharing a video clip, movie, or video game."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint\/motion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoContentHintMotion"}],"url":"\/documentation\/agorartckit\/agoravideocontenthint\/motion"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoContentHint":{"role":"symbol","title":"AgoraVideoContentHint","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoContentHint"}],"abstract":[{"type":"text","text":"The content hint for screen sharing."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoContentHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoContentHint"}],"url":"\/documentation\/agorartckit\/agoravideocontenthint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoContentHintMotion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoContentHintMotion"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoContentHintMotion"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint~1motion\/title","value":"AgoraVideoContentHintMotion"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint~1motion\/fragments","value":[{"kind":"identifier","text":"AgoraVideoContentHintMotion"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint\/title","value":"AgoraVideoContentHint"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoContentHint\/fragments","value":[{"kind":"identifier","text":"AgoraVideoContentHint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}