{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideomirrormode\/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideomirrormode\/disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode\/disabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: Disable mirror mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"title":"AgoraVideoMirrorMode.disabled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoMirrorMode@AgoraVideoMirrorModeDisabled","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoMirrorModeDisabled"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoMirrorMode":{"role":"symbol","title":"AgoraVideoMirrorMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"abstract":[{"type":"text","text":"Video mirror mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}],"url":"\/documentation\/agorartckit\/agoravideomirrormode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoMirrorMode/disabled":{"role":"symbol","title":"AgoraVideoMirrorMode.disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"abstract":[{"type":"text","text":"2: Disable mirror mode."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoMirrorMode\/disabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoMirrorModeDisabled"}],"url":"\/documentation\/agorartckit\/agoravideomirrormode\/disabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoMirrorModeDisabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoMirrorModeDisabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoMirrorModeDisabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/title","value":"AgoraVideoMirrorMode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode\/fragments","value":[{"kind":"identifier","text":"AgoraVideoMirrorMode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode~1disabled\/title","value":"AgoraVideoMirrorModeDisabled"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoMirrorMode~1disabled\/fragments","value":[{"kind":"identifier","text":"AgoraVideoMirrorModeDisabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}