{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rtmKit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit","text":"AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinTopic"},{"kind":"text","text":" "},{"kind":"internalParam","text":"topic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inChannel"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMeta"},{"kind":"text","text":" "},{"kind":"internalParam","text":"meta"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode","text":"AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:jointopic:inchannel:withmeta:result:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:jointopic:inchannel:withmeta:result:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"}],"role":"symbol","title":"rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMeta"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraRtmClientDelegate(im)rtmKit:onUser:joinTopic:inChannel:withMeta:result:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientKit":{"role":"symbol","title":"AgoraRtmClientKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientKit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientKit"}],"url":"\/documentation\/agorartckit\/agorartmclientkit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmStreamChannelErrorCode":{"role":"symbol","title":"AgoraRtmStreamChannelErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}],"url":"\/documentation\/agorartckit\/agorartmstreamchannelerrorcode"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate":{"role":"symbol","title":"AgoraRtmClientDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmClientDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmClientDelegate"}],"url":"\/documentation\/agorartckit\/agorartmclientdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmClientDelegate/rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)":{"navigatorTitle":[{"kind":"identifier","text":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"}],"role":"symbol","title":"rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtmKit"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"joinTopic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMeta"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientDelegate\/rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorartmclientdelegate\/rtmkit(_:onuser:jointopic:inchannel:withmeta:result:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtmKit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmClientKit","preciseIdentifier":"c:objc(cs)AgoraRtmClientKit","text":"AgoraRtmClientKit"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"rtmKit"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinTopic:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"topic"},{"kind":"text","text":" "},{"kind":"identifier","text":"inChannel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelName"},{"kind":"text","text":" "},{"kind":"identifier","text":"withMeta:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"meta"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmStreamChannelErrorCode","preciseIdentifier":"c:@E@AgoraRtmStreamChannelErrorCode","text":"AgoraRtmStreamChannelErrorCode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"errorCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientKit\/title","value":"AgoraRtmClientKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientKit\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode\/title","value":"AgoraRtmStreamChannelErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmStreamChannelErrorCode\/fragments","value":[{"kind":"identifier","text":"AgoraRtmStreamChannelErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate\/title","value":"AgoraRtmClientDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraRtmClientDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)\/title","value":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmClientDelegate~1rtmKit(_:onUser:joinTopic:inChannel:withMeta:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtmKit:onUser:joinTopic:inChannel:withMeta:result:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}