{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingState","text":"AgoraDirectCdnStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingError","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingError","text":"AgoraDirectCdnStreamingError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"state","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current CDN streaming state. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraDirectCdnStreamingState ."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CDN streaming error. See AgoraDirectCdnStreamingError"},{"type":"text","text":" "},{"type":"text","text":"."}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The information about the changed streaming state."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstatechanged(_:error:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstatechanged(_:error:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStateChanged(_:error:message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when the CDN streaming state changes."},{"type":"text","text":" "},{"type":"text","text":"When the host directly pushes streams to the CDN, if the streaming state"},{"type":"text","text":" "},{"type":"text","text":"changes, the SDK triggers this callback to report the changed streaming"},{"type":"text","text":" "},{"type":"text","text":"state, error codes, and other information. You can troubleshoot issues by"},{"type":"text","text":" "},{"type":"text","text":"referring to this callback."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingState","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingError","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"onDirectCdnStreamingStateChanged(_:error:message:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)AgoraDirectCdnStreamingEventDelegate(im)onDirectCdnStreamingStateChanged:error:message:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"onDirectCdnStreamingStateChanged:error:message:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate":{"role":"symbol","title":"AgoraDirectCdnStreamingEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"abstract":[{"type":"text","text":"The AgoraDirectCdnStreamingEventDelegate interface class is used by the SDK"},{"type":"text","text":" "},{"type":"text","text":"to send event notifications of CDN streaming to your app. Your app can get"},{"type":"text","text":" "},{"type":"text","text":"those notifications through methods that inherit this interface class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingError":{"role":"symbol","title":"AgoraDirectCdnStreamingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingError"}],"abstract":[{"type":"text","text":"The CDN streaming error."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingError"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingerror"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate/onDirectCdnStreamingStateChanged(_:error:message:)":{"role":"symbol","title":"onDirectCdnStreamingStateChanged(_:error:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingState","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingError","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Occurs when the CDN streaming state changes."},{"type":"text","text":" "},{"type":"text","text":"When the host directly pushes streams to the CDN, if the streaming state"},{"type":"text","text":" "},{"type":"text","text":"changes, the SDK triggers this callback to report the changed streaming"},{"type":"text","text":" "},{"type":"text","text":"state, error codes, and other information. You can troubleshoot issues by"},{"type":"text","text":" "},{"type":"text","text":"referring to this callback."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStateChanged(_:error:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onDirectCdnStreamingStateChanged:error:message:"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstatechanged(_:error:message:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingState":{"role":"symbol","title":"AgoraDirectCdnStreamingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"abstract":[{"type":"text","text":"The current CDN streaming state."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onDirectCdnStreamingStateChanged:error:message:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged:error:message:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingState","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingState","text":"AgoraDirectCdnStreamingState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"state"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingError","preciseIdentifier":"c:@E@AgoraDirectCdnStreamingError","text":"AgoraDirectCdnStreamingError"},{"kind":"text","text":") "},{"kind":"internalParam","text":"error"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/title","value":"AgoraDirectCdnStreamingEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingError\/title","value":"AgoraDirectCdnStreamingError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingError\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStateChanged(_:error:message:)\/title","value":"onDirectCdnStreamingStateChanged:error:message:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStateChanged(_:error:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDirectCdnStreamingStateChanged:error:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState\/title","value":"AgoraDirectCdnStreamingState"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingState\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}