{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStats"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"stats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingStats","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingStats","text":"AgoraDirectCdnStreamingStats"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"stats","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The statistics of the current CDN streaming. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraDirectCdnStreamingStats ."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstats(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstats(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStats(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Reports the CDN streaming statistics."},{"type":"text","text":" "},{"type":"text","text":"When the host directly pushes media streams to the CDN, the SDK triggers this"},{"type":"text","text":" "},{"type":"text","text":"callback every one second."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onDirectCdnStreamingStats:"}],"role":"symbol","title":"onDirectCdnStreamingStats(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStats"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingStats","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingStats"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraDirectCdnStreamingEventDelegate(im)onDirectCdnStreamingStats:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingStats":{"role":"symbol","title":"AgoraDirectCdnStreamingStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingStats"}],"abstract":[{"type":"text","text":"The statistics of the current CDN streaming."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStats"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingstats"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate":{"role":"symbol","title":"AgoraDirectCdnStreamingEventDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"abstract":[{"type":"text","text":"The AgoraDirectCdnStreamingEventDelegate interface class is used by the SDK"},{"type":"text","text":" "},{"type":"text","text":"to send event notifications of CDN streaming to your app. Your app can get"},{"type":"text","text":" "},{"type":"text","text":"those notifications through methods that inherit this interface class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}],"url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraDirectCdnStreamingEventDelegate/onDirectCdnStreamingStats(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onDirectCdnStreamingStats:"}],"role":"symbol","title":"onDirectCdnStreamingStats(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDirectCdnStreamingStats"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraDirectCdnStreamingStats","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingStats"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Reports the CDN streaming statistics."},{"type":"text","text":" "},{"type":"text","text":"When the host directly pushes media streams to the CDN, the SDK triggers this"},{"type":"text","text":" "},{"type":"text","text":"callback every one second."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingEventDelegate\/onDirectCdnStreamingStats(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agoradirectcdnstreamingeventdelegate\/ondirectcdnstreamingstats(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onDirectCdnStreamingStats:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDirectCdnStreamingStats:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onDirectCdnStreamingStats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraDirectCdnStreamingStats","preciseIdentifier":"c:objc(cs)AgoraDirectCdnStreamingStats","text":"AgoraDirectCdnStreamingStats"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"stats"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingStats\/title","value":"AgoraDirectCdnStreamingStats"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingStats\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingStats"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/title","value":"AgoraDirectCdnStreamingEventDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraDirectCdnStreamingEventDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStats(_:)\/title","value":"onDirectCdnStreamingStats:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraDirectCdnStreamingEventDelegate~1onDirectCdnStreamingStats(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDirectCdnStreamingStats:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}