{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralogfilter\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralogfilter\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0x000c: Output AgoraLogFilterCritical and AgoraLogFilterError level log information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"title":"AgoraLogFilter.error","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLogFilter@AgoraLogFilterError","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterError"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/error":{"role":"symbol","title":"AgoraLogFilter.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[{"type":"text","text":"0x000c: Output AgoraLogFilterCritical and AgoraLogFilterError level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterError"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/error"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter":{"role":"symbol","title":"AgoraLogFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogFilter"}],"abstract":[{"type":"text","text":"The output log level of the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilter"}],"url":"\/documentation\/agorartckit\/agoralogfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLogFilterError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLogFilterError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1error\/title","value":"AgoraLogFilterError"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1error\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterError"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/title","value":"AgoraLogFilter"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}