{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralogfilter\/off"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralogfilter\/off"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/off","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0: Do not output any log information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"title":"AgoraLogFilter.off","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLogFilter@AgoraLogFilterOff","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterOff"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter":{"role":"symbol","title":"AgoraLogFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogFilter"}],"abstract":[{"type":"text","text":"The output log level of the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilter"}],"url":"\/documentation\/agorartckit\/agoralogfilter"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/off":{"role":"symbol","title":"AgoraLogFilter.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[{"type":"text","text":"0: Do not output any log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterOff"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/off"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLogFilterOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterOff"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLogFilterOff"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/title","value":"AgoraLogFilter"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1off\/title","value":"AgoraLogFilterOff"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1off\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}