{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralogfilter\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralogfilter\/warning"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/warning","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0x000e: Output AgoraLogFilterCritical, AgoraLogFilterError, and"},{"type":"text","text":" "},{"type":"text","text":"AgoraLogFilterWarning level log information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"title":"AgoraLogFilter.warning","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraLogFilter@AgoraLogFilterWarning","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterWarning"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter":{"role":"symbol","title":"AgoraLogFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLogFilter"}],"abstract":[{"type":"text","text":"The output log level of the SDK."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilter"}],"url":"\/documentation\/agorartckit\/agoralogfilter"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLogFilter/warning":{"role":"symbol","title":"AgoraLogFilter.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[{"type":"text","text":"0x000e: Output AgoraLogFilterCritical, AgoraLogFilterError, and"},{"type":"text","text":" "},{"type":"text","text":"AgoraLogFilterWarning level log information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLogFilter\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLogFilterWarning"}],"url":"\/documentation\/agorartckit\/agoralogfilter\/warning"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraLogFilterWarning"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterWarning"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraLogFilterWarning"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/title","value":"AgoraLogFilter"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1warning\/title","value":"AgoraLogFilterWarning"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLogFilter~1warning\/fragments","value":[{"kind":"identifier","text":"AgoraLogFilterWarning"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}