{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDestinationInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channelName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel name of the target channel."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES : Success. NO : Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/removedestinationinfo(forchannelname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/removedestinationinfo(forchannelname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/removeDestinationInfo(forChannelName:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deletes the information of target channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDestinationInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"removeDestinationInfo(forChannelName:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChannelMediaRelayConfiguration(im)removeDestinationInfoForChannelName:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"removeDestinationInfoForChannelName:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration":{"role":"symbol","title":"AgoraChannelMediaRelayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"abstract":[{"type":"text","text":"Configuration of cross channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration/removeDestinationInfo(forChannelName:)":{"role":"symbol","title":"removeDestinationInfo(forChannelName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDestinationInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Deletes the information of target channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/removeDestinationInfo(forChannelName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeDestinationInfoForChannelName:"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/removedestinationinfo(forchannelname:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeDestinationInfoForChannelName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDestinationInfoForChannelName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeDestinationInfoForChannelName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"channelName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/title","value":"AgoraChannelMediaRelayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1removeDestinationInfo(forChannelName:)\/title","value":"removeDestinationInfoForChannelName:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1removeDestinationInfo(forChannelName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDestinationInfoForChannelName:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}