{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDestinationInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"destinationInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo","text":"AgoraChannelMediaRelayInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"destinationInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The information of the target channel. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraChannelMediaRelayInfo. It contains the following members:channelName:"},{"type":"text","text":" "},{"type":"text","text":"The name of the target channel.token: The token for joining the target"},{"type":"text","text":" "},{"type":"text","text":"channel. This token is generated with the channelName and uid you set in"},{"type":"text","text":" "},{"type":"text","text":"destInfos.If you have not enabled the App Certificate, set this parameter as"},{"type":"text","text":" "},{"type":"text","text":"the default value nil, which means the SDK applies the App ID.If you have"},{"type":"text","text":" "},{"type":"text","text":"enabled the App Certificate, you must use the token generated with the"},{"type":"text","text":" "},{"type":"text","text":"channelName and uid.If the token of any target channel expires, the whole"},{"type":"text","text":" "},{"type":"text","text":"media relay stops; hence Agora recommends that you specify the same"},{"type":"text","text":" "},{"type":"text","text":"expiration time for the tokens of all the target channels.uid: The unique"},{"type":"text","text":" "},{"type":"text","text":"user ID to identify the relay stream in the target channel. The value ranges"},{"type":"text","text":" "},{"type":"text","text":"from 0 to (2 32-1). To avoid user ID conflicts, this user ID must be"},{"type":"text","text":" "},{"type":"text","text":"different from any other user ID in the target channel. The default value is"},{"type":"text","text":" "},{"type":"text","text":"0, which means the SDK generates a random user ID."}]}]},{"name":"channelName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel name of the target channel."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES : Success. NO : Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/setdestinationinfo(_:forchannelname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/setdestinationinfo(_:forchannelname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/setDestinationInfo(_:forChannelName:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the information of the target channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDestinationInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"setDestinationInfo(_:forChannelName:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraChannelMediaRelayConfiguration(im)setDestinationInfo:forChannelName:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setDestinationInfo:forChannelName:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration/setDestinationInfo(_:forChannelName:)":{"role":"symbol","title":"setDestinationInfo(_:forChannelName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDestinationInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forChannelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Sets the information of the target channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/setDestinationInfo(_:forChannelName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDestinationInfo:forChannelName:"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/setdestinationinfo(_:forchannelname:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration":{"role":"symbol","title":"AgoraChannelMediaRelayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"abstract":[{"type":"text","text":"Configuration of cross channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayInfo":{"role":"symbol","title":"AgoraChannelMediaRelayInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayInfo"}],"abstract":[{"type":"text","text":"Channel media information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayInfo"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setDestinationInfo:forChannelName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDestinationInfo:forChannelName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDestinationInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo","text":"AgoraChannelMediaRelayInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"destinationInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"forChannelName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"channelName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1setDestinationInfo(_:forChannelName:)\/title","value":"setDestinationInfo:forChannelName:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1setDestinationInfo(_:forChannelName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDestinationInfo:forChannelName:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/title","value":"AgoraChannelMediaRelayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayInfo\/title","value":"AgoraChannelMediaRelayInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayInfo\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}