{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo","text":"AgoraChannelMediaRelayInfo"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/sourceinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/sourceinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/sourceInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The information of the source channel. See AgoraChannelMediaRelayInfo . It"},{"type":"text","text":" "},{"type":"text","text":"contains the following members:channelName: The name of the source channel."},{"type":"text","text":" "},{"type":"text","text":"The default value is nil, which means the SDK applies the name of the current"},{"type":"text","text":" "},{"type":"text","text":"channel.token: The token for joining the source channel. This token is"},{"type":"text","text":" "},{"type":"text","text":"generated with the channelName and uid you set in srcInfo.If you have not"},{"type":"text","text":" "},{"type":"text","text":"enabled the App Certificate, set this parameter as the default value nil,"},{"type":"text","text":" "},{"type":"text","text":"which means the SDK applies the App ID.If you have enabled the App"},{"type":"text","text":" "},{"type":"text","text":"Certificate, you must use the token generated with the channelName and uid,"},{"type":"text","text":" "},{"type":"text","text":"and the uid must be set as 0.uid: The unique user ID to identify the relay"},{"type":"text","text":" "},{"type":"text","text":"stream in the source channel. Agora recommends leaving the default value of 0"},{"type":"text","text":" "},{"type":"text","text":"unchanged."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo"}],"title":"sourceInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraChannelMediaRelayConfiguration(py)sourceInfo","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"sourceInfo"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayInfo":{"role":"symbol","title":"AgoraChannelMediaRelayInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayInfo"}],"abstract":[{"type":"text","text":"Channel media information."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayInfo"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration/sourceInfo":{"role":"symbol","title":"sourceInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo"}],"abstract":[{"type":"text","text":"The information of the source channel. See AgoraChannelMediaRelayInfo . It"},{"type":"text","text":" "},{"type":"text","text":"contains the following members:channelName: The name of the source channel."},{"type":"text","text":" "},{"type":"text","text":"The default value is nil, which means the SDK applies the name of the current"},{"type":"text","text":" "},{"type":"text","text":"channel.token: The token for joining the source channel. This token is"},{"type":"text","text":" "},{"type":"text","text":"generated with the channelName and uid you set in srcInfo.If you have not"},{"type":"text","text":" "},{"type":"text","text":"enabled the App Certificate, set this parameter as the default value nil,"},{"type":"text","text":" "},{"type":"text","text":"which means the SDK applies the App ID.If you have enabled the App"},{"type":"text","text":" "},{"type":"text","text":"Certificate, you must use the token generated with the channelName and uid,"},{"type":"text","text":" "},{"type":"text","text":"and the uid must be set as 0.uid: The unique user ID to identify the relay"},{"type":"text","text":" "},{"type":"text","text":"stream in the source channel. Agora recommends leaving the default value of 0"},{"type":"text","text":" "},{"type":"text","text":"unchanged."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration\/sourceInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sourceInfo"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration\/sourceinfo"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraChannelMediaRelayConfiguration":{"role":"symbol","title":"AgoraChannelMediaRelayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"abstract":[{"type":"text","text":"Configuration of cross channel media relay."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}],"url":"\/documentation\/agorartckit\/agorachannelmediarelayconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sourceInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sourceInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraChannelMediaRelayInfo","preciseIdentifier":"c:objc(cs)AgoraChannelMediaRelayInfo","text":"AgoraChannelMediaRelayInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sourceInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayInfo\/title","value":"AgoraChannelMediaRelayInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayInfo\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1sourceInfo\/title","value":"sourceInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration~1sourceInfo\/fragments","value":[{"kind":"identifier","text":"sourceInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/title","value":"AgoraChannelMediaRelayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraChannelMediaRelayConfiguration\/fragments","value":[{"kind":"identifier","text":"AgoraChannelMediaRelayConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}