{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoinChannel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpresencetype\/remotejoinchannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpresencetype\/remotejoinchannel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType\/remoteJoinChannel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoinChannel"}],"title":"AgoraRtmPresenceType.remoteJoinChannel","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmPresenceType@AgoraRtmPresenceTypeRemoteJoinChannel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceTypeRemoteJoinChannel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceType/remoteJoinChannel":{"role":"symbol","title":"AgoraRtmPresenceType.remoteJoinChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteJoinChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType\/remoteJoinChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceTypeRemoteJoinChannel"}],"url":"\/documentation\/agorartckit\/agorartmpresencetype\/remotejoinchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceType":{"role":"symbol","title":"AgoraRtmPresenceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmPresenceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceType"}],"url":"\/documentation\/agorartckit\/agorartmpresencetype"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmPresenceTypeRemoteJoinChannel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceTypeRemoteJoinChannel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmPresenceTypeRemoteJoinChannel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType~1remoteJoinChannel\/title","value":"AgoraRtmPresenceTypeRemoteJoinChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType~1remoteJoinChannel\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceTypeRemoteJoinChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType\/title","value":"AgoraRtmPresenceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}