{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"selfJoinChannel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpresencetype\/selfjoinchannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpresencetype\/selfjoinchannel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType\/selfJoinChannel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"selfJoinChannel"}],"title":"AgoraRtmPresenceType.selfJoinChannel","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmPresenceType@AgoraRtmPresenceTypeSelfJoinChannel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceTypeSelfJoinChannel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceType/selfJoinChannel":{"role":"symbol","title":"AgoraRtmPresenceType.selfJoinChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"selfJoinChannel"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType\/selfJoinChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceTypeSelfJoinChannel"}],"url":"\/documentation\/agorartckit\/agorartmpresencetype\/selfjoinchannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmPresenceType":{"role":"symbol","title":"AgoraRtmPresenceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmPresenceType"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmPresenceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmPresenceType"}],"url":"\/documentation\/agorartckit\/agorartmpresencetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmPresenceTypeSelfJoinChannel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceTypeSelfJoinChannel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmPresenceTypeSelfJoinChannel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType~1selfJoinChannel\/title","value":"AgoraRtmPresenceTypeSelfJoinChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType~1selfJoinChannel\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceTypeSelfJoinChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType\/title","value":"AgoraRtmPresenceType"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmPresenceType\/fragments","value":[{"kind":"identifier","text":"AgoraRtmPresenceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}