{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"h265ForStream"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoravideocodectypeforstream\/h265forstream"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoravideocodectypeforstream\/h265forstream"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecTypeForStream\/h265ForStream","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"2: H.265."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"h265ForStream"}],"title":"AgoraVideoCodecTypeForStream.h265ForStream","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraVideoCodecTypeForStream@AgoraVideoCodecTypeH265ForStream","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraVideoCodecTypeH265ForStream"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecTypeForStream"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoCodecTypeForStream":{"role":"symbol","title":"AgoraVideoCodecTypeForStream","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraVideoCodecTypeForStream"}],"abstract":[{"type":"text","text":"The codec type of the output video."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecTypeForStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoCodecTypeForStream"}],"url":"\/documentation\/agorartckit\/agoravideocodectypeforstream"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraVideoCodecTypeForStream/h265ForStream":{"role":"symbol","title":"AgoraVideoCodecTypeForStream.h265ForStream","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"h265ForStream"}],"abstract":[{"type":"text","text":"2: H.265."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraVideoCodecTypeForStream\/h265ForStream","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraVideoCodecTypeH265ForStream"}],"url":"\/documentation\/agorartckit\/agoravideocodectypeforstream\/h265forstream"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraVideoCodecTypeH265ForStream"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraVideoCodecTypeH265ForStream"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraVideoCodecTypeH265ForStream"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecTypeForStream\/title","value":"AgoraVideoCodecTypeForStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecTypeForStream\/fragments","value":[{"kind":"identifier","text":"AgoraVideoCodecTypeForStream"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecTypeForStream~1h265ForStream\/title","value":"AgoraVideoCodecTypeH265ForStream"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraVideoCodecTypeForStream~1h265ForStream\/fragments","value":[{"kind":"identifier","text":"AgoraVideoCodecTypeH265ForStream"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}