{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTriggerTranscode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult","preciseIdentifier":"c:@E@AgoraH265TranscodeResult","text":"AgoraH265TranscodeResult"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorah265transcoderdelegate\/ontriggertranscode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorah265transcoderdelegate\/ontriggertranscode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onTriggerTranscode(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onTriggerTranscode:"}],"role":"symbol","title":"onTriggerTranscode(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTriggerTranscode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscodeResult","preciseIdentifier":"c:@E@AgoraH265TranscodeResult"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)AgoraH265TranscoderDelegate(im)onTriggerTranscode:","required":true,"modules":[{"name":"AgoraRtcKit"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscodeResult":{"role":"symbol","title":"AgoraH265TranscodeResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}],"url":"\/documentation\/agorartckit\/agorah265transcoderesult"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderDelegate":{"role":"symbol","title":"AgoraH265TranscoderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}],"url":"\/documentation\/agorartckit\/agorah265transcoderdelegate"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraH265TranscoderDelegate/onTriggerTranscode(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onTriggerTranscode:"}],"role":"symbol","title":"onTriggerTranscode(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTriggerTranscode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraH265TranscodeResult","preciseIdentifier":"c:@E@AgoraH265TranscodeResult"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscoderDelegate\/onTriggerTranscode(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/agorartckit\/agorah265transcoderdelegate\/ontriggertranscode(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onTriggerTranscode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTriggerTranscode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onTriggerTranscode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraH265TranscodeResult","preciseIdentifier":"c:@E@AgoraH265TranscodeResult","text":"AgoraH265TranscodeResult"},{"kind":"text","text":") "},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/title","value":"AgoraH265TranscodeResult"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscodeResult\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscodeResult"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate\/title","value":"AgoraH265TranscoderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate\/fragments","value":[{"kind":"identifier","text":"AgoraH265TranscoderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onTriggerTranscode(_:)\/title","value":"onTriggerTranscode:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraH265TranscoderDelegate~1onTriggerTranscode(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTriggerTranscode:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}