{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"excellent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoranetworkquality\/excellent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoranetworkquality\/excellent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/excellent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: The network quality is excellent."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"excellent"}],"title":"AgoraNetworkQuality.excellent","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraNetworkQuality@AgoraNetworkQualityExcellent","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityExcellent"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality/excellent":{"role":"symbol","title":"AgoraNetworkQuality.excellent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"excellent"}],"abstract":[{"type":"text","text":"1: The network quality is excellent."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality\/excellent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQualityExcellent"}],"url":"\/documentation\/agorartckit\/agoranetworkquality\/excellent"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraNetworkQuality":{"role":"symbol","title":"AgoraNetworkQuality","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraNetworkQuality"}],"abstract":[{"type":"text","text":"Network quality types."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraNetworkQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraNetworkQuality"}],"url":"\/documentation\/agorartckit\/agoranetworkquality"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraNetworkQualityExcellent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityExcellent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraNetworkQualityExcellent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1excellent\/title","value":"AgoraNetworkQualityExcellent"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality~1excellent\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQualityExcellent"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality\/title","value":"AgoraNetworkQuality"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraNetworkQuality\/fragments","value":[{"kind":"identifier","text":"AgoraNetworkQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}