{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopMicrophoneRecording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraleavechanneloptions\/stopmicrophonerecording"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraleavechanneloptions\/stopmicrophonerecording"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopMicrophoneRecording","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether to stop microphone recording when a user leaves the channel. YES:"},{"type":"text","text":" "},{"type":"text","text":"(Default) Stop microphone recording.NO: Do not stop microphone recording."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopMicrophoneRecording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"stopMicrophoneRecording","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraLeaveChannelOptions(py)stopMicrophoneRecording","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"stopMicrophoneRecording"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLeaveChannelOptions/stopMicrophoneRecording":{"role":"symbol","title":"stopMicrophoneRecording","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopMicrophoneRecording"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether to stop microphone recording when a user leaves the channel. YES:"},{"type":"text","text":" "},{"type":"text","text":"(Default) Stop microphone recording.NO: Do not stop microphone recording."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions\/stopMicrophoneRecording","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopMicrophoneRecording"}],"url":"\/documentation\/agorartckit\/agoraleavechanneloptions\/stopmicrophonerecording"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLeaveChannelOptions":{"role":"symbol","title":"AgoraLeaveChannelOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"abstract":[{"type":"text","text":"The options for leaving a channel."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLeaveChannelOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}],"url":"\/documentation\/agorartckit\/agoraleavechanneloptions"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"stopMicrophoneRecording"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"stopMicrophoneRecording"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopMicrophoneRecording"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopMicrophoneRecording\/title","value":"stopMicrophoneRecording"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions~1stopMicrophoneRecording\/fragments","value":[{"kind":"identifier","text":"stopMicrophoneRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions\/title","value":"AgoraLeaveChannelOptions"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLeaveChannelOptions\/fragments","value":[{"kind":"identifier","text":"AgoraLeaveChannelOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}