{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRemotePositionEx"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/removeremotepositionex(_:connection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/removeremotepositionex(_:connection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePositionEx(_:connection:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRemotePositionEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"removeRemotePositionEx(_:connection:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraLocalSpatialAudioKit(im)removeRemotePositionEx:connection:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"removeRemotePositionEx:connection:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/removeRemotePositionEx(_:connection:)":{"role":"symbol","title":"removeRemotePositionEx(_:connection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeRemotePositionEx"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/removeRemotePositionEx(_:connection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeRemotePositionEx:connection:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/removeremotepositionex(_:connection:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit":{"role":"symbol","title":"AgoraLocalSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtcConnection":{"role":"symbol","title":"AgoraRtcConnection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtcConnection"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtcConnection"}],"url":"\/documentation\/agorartckit\/agorartcconnection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeRemotePositionEx:connection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeRemotePositionEx:connection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeRemotePositionEx:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"connection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtcConnection","preciseIdentifier":"c:objc(cs)AgoraRtcConnection","text":"AgoraRtcConnection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"connection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1removeRemotePositionEx(_:connection:)\/title","value":"removeRemotePositionEx:connection:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1removeRemotePositionEx(_:connection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeRemotePositionEx:connection:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/title","value":"AgoraLocalSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/title","value":"AgoraRtcConnection"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtcConnection\/fragments","value":[{"kind":"identifier","text":"AgoraRtcConnection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}