{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteAudioAttenuation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"attenuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forceSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"attenuation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For the user’s sound attenuation coefficient, the"},{"type":"text","text":" "},{"type":"text","text":"value range is [0,1]. The values are as follows:0: Broadcast mode, where the"},{"type":"text","text":" "},{"type":"text","text":"volume and timbre are not attenuated with distance, and the volume and timbre"},{"type":"text","text":" "},{"type":"text","text":"heard by local users do not change regardless of distance.(0,0.5): Weak"},{"type":"text","text":" "},{"type":"text","text":"attenuation mode, that is, the volume and timbre are only weakly attenuated"},{"type":"text","text":" "},{"type":"text","text":"during the propagation process, and the sound can travel farther than the"},{"type":"text","text":" "},{"type":"text","text":"real environment.0.5: (Default) simulates the attenuation of the volume in"},{"type":"text","text":" "},{"type":"text","text":"the real environment; the effect is equivalent to not setting the"},{"type":"text","text":" "},{"type":"text","text":"speaker_attenuation parameter.(0.5,1]: Strong attenuation mode, that is, the"},{"type":"text","text":" "},{"type":"text","text":"volume and timbre attenuate rapidly during the propagation process."}]}]},{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID. This parameter must be the same as the user ID"},{"type":"text","text":" "},{"type":"text","text":"passed in when the user joined the channel."}]}]},{"name":"forceSet","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to force the user’s sound attenuation"},{"type":"text","text":" "},{"type":"text","text":"effect:YES: Force attenuation to set the sound attenuation of the user. At"},{"type":"text","text":" "},{"type":"text","text":"this time, the attenuation coefficient of the sound insulation area set in"},{"type":"text","text":" "},{"type":"text","text":"the audioAttenuation of the AgoraSpatialAudioZone does not take effect for"},{"type":"text","text":" "},{"type":"text","text":"the user.If the sound source and listener are inside and outside the sound"},{"type":"text","text":" "},{"type":"text","text":"isolation area, the sound attenuation effect is determined by the"},{"type":"text","text":" "},{"type":"text","text":"audioAttenuation in AgoraSpatialAudioZone.If the sound source and the"},{"type":"text","text":" "},{"type":"text","text":"listener are in the same sound insulation area or outside the same sound"},{"type":"text","text":" "},{"type":"text","text":"insulation area, the sound attenuation effect is determined by attenuation in"},{"type":"text","text":" "},{"type":"text","text":"this method.NO: Do not force attenuation to set the user’s sound attenuation"},{"type":"text","text":" "},{"type":"text","text":"effect, as shown in the following two cases."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/setremoteaudioattenuation(_:userid:forceset:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/setremoteaudioattenuation(_:userid:forceset:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/setRemoteAudioAttenuation(_:userId:forceSet:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the sound attenuation effect for the specified user."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteAudioAttenuation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forceSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setRemoteAudioAttenuation(_:userId:forceSet:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraLocalSpatialAudioKit(im)setRemoteAudioAttenuation:userId:forceSet:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setRemoteAudioAttenuation:userId:forceSet:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/setRemoteAudioAttenuation(_:userId:forceSet:)":{"role":"symbol","title":"setRemoteAudioAttenuation(_:userId:forceSet:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRemoteAudioAttenuation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forceSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the sound attenuation effect for the specified user."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/setRemoteAudioAttenuation(_:userId:forceSet:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRemoteAudioAttenuation:userId:forceSet:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/setremoteaudioattenuation(_:userid:forceset:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit":{"role":"symbol","title":"AgoraLocalSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setRemoteAudioAttenuation:userId:forceSet:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteAudioAttenuation:userId:forceSet:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRemoteAudioAttenuation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"attenuation"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceSet:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"forceSet"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1setRemoteAudioAttenuation(_:userId:forceSet:)\/title","value":"setRemoteAudioAttenuation:userId:forceSet:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1setRemoteAudioAttenuation(_:userId:forceSet:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setRemoteAudioAttenuation:userId:forceSet:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/title","value":"AgoraLocalSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}