{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedLocalSpatialAudio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioConfig","preciseIdentifier":"c:objc(cs)AgoraLocalSpatialAudioConfig","text":"AgoraLocalSpatialAudioConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of AgoraLocalSpatialAudioKit. See"},{"type":"text","text":" "},{"type":"text","text":"AgoraLocalSpatialAudioConfig ."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/sharedlocalspatialaudio(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/sharedlocalspatialaudio(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/sharedLocalSpatialAudio(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes AgoraLocalSpatialAudioKit ."},{"type":"text","text":" "},{"type":"text","text":"Before calling other methods of the AgoraLocalSpatialAudioKit class, you need"},{"type":"text","text":" "},{"type":"text","text":"to call this method to initialize AgoraLocalSpatialAudioKit.The SDK supports"},{"type":"text","text":" "},{"type":"text","text":"creating only one AgoraLocalSpatialAudioKit instance for an app."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedLocalSpatialAudio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLocalSpatialAudioConfig","preciseIdentifier":"c:objc(cs)AgoraLocalSpatialAudioConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"sharedLocalSpatialAudio(with:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraLocalSpatialAudioKit(cm)sharedLocalSpatialAudioWithConfig:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"sharedLocalSpatialAudioWithConfig:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/sharedLocalSpatialAudio(with:)":{"role":"symbol","title":"sharedLocalSpatialAudio(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedLocalSpatialAudio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraLocalSpatialAudioConfig","preciseIdentifier":"c:objc(cs)AgoraLocalSpatialAudioConfig"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Initializes AgoraLocalSpatialAudioKit ."},{"type":"text","text":" "},{"type":"text","text":"Before calling other methods of the AgoraLocalSpatialAudioKit class, you need"},{"type":"text","text":" "},{"type":"text","text":"to call this method to initialize AgoraLocalSpatialAudioKit.The SDK supports"},{"type":"text","text":" "},{"type":"text","text":"creating only one AgoraLocalSpatialAudioKit instance for an app."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/sharedLocalSpatialAudio(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedLocalSpatialAudioWithConfig:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/sharedlocalspatialaudio(with:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioConfig":{"role":"symbol","title":"AgoraLocalSpatialAudioConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioConfig"}],"abstract":[{"type":"text","text":"The configuration of AgoraLocalSpatialAudioKit ."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioConfig"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudioconfig"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit":{"role":"symbol","title":"AgoraLocalSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"sharedLocalSpatialAudioWithConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedLocalSpatialAudioWithConfig:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"sharedLocalSpatialAudioWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioConfig","preciseIdentifier":"c:objc(cs)AgoraLocalSpatialAudioConfig","text":"AgoraLocalSpatialAudioConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1sharedLocalSpatialAudio(with:)\/title","value":"sharedLocalSpatialAudioWithConfig:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1sharedLocalSpatialAudio(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedLocalSpatialAudioWithConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioConfig\/title","value":"AgoraLocalSpatialAudioConfig"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioConfig\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/title","value":"AgoraLocalSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}