{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRemotePosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positionInfo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"posInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRemoteVoicePositionInfo","preciseIdentifier":"c:objc(cs)AgoraRemoteVoicePositionInfo","text":"AgoraRemoteVoicePositionInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"uid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user ID. This parameter must be the same as the user ID passed in when the user joined the channel."}]}]},{"name":"posInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The spatial position of the remote user. See AgoraRemoteVoicePositionInfo."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After successfully calling this method, the SDK calculates the spatial audio parameters based on the relative position of the local and remote user. Call this method after joinChannelByToken [2\/4] ."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/updateremoteposition(_:positioninfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoralocalspatialaudiokit\/updateremoteposition(_:positioninfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePosition(_:positionInfo:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates the spatial position of the specified remote user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRemotePosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRemoteVoicePositionInfo","preciseIdentifier":"c:objc(cs)AgoraRemoteVoicePositionInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"updateRemotePosition(_:positionInfo:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraLocalSpatialAudioKit(im)updateRemotePosition:positionInfo:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateRemotePosition:positionInfo:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit":{"role":"symbol","title":"AgoraLocalSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"abstract":[],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraLocalSpatialAudioKit/updateRemotePosition(_:positionInfo:)":{"role":"symbol","title":"updateRemotePosition(_:positionInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRemotePosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRemoteVoicePositionInfo","preciseIdentifier":"c:objc(cs)AgoraRemoteVoicePositionInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the spatial position of the specified remote user."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraLocalSpatialAudioKit\/updateRemotePosition(_:positionInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateRemotePosition:positionInfo:"}],"url":"\/documentation\/agorartckit\/agoralocalspatialaudiokit\/updateremoteposition(_:positioninfo:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRemoteVoicePositionInfo":{"role":"symbol","title":"AgoraRemoteVoicePositionInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRemoteVoicePositionInfo"}],"abstract":[{"type":"text","text":"The spatial position of the remote user or the media player."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRemoteVoicePositionInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRemoteVoicePositionInfo"}],"url":"\/documentation\/agorartckit\/agoraremotevoicepositioninfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateRemotePosition:positionInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRemotePosition:positionInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateRemotePosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRemoteVoicePositionInfo","preciseIdentifier":"c:objc(cs)AgoraRemoteVoicePositionInfo","text":"AgoraRemoteVoicePositionInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"posInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/title","value":"AgoraLocalSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraLocalSpatialAudioKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1updateRemotePosition(_:positionInfo:)\/title","value":"updateRemotePosition:positionInfo:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraLocalSpatialAudioKit~1updateRemotePosition(_:positionInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateRemotePosition:positionInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRemoteVoicePositionInfo\/title","value":"AgoraRemoteVoicePositionInfo"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRemoteVoicePositionInfo\/fragments","value":[{"kind":"identifier","text":"AgoraRemoteVoicePositionInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}