{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"-1: The default audio route."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"title":"AgoraAudioOutputRouting.default","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioOutputRouting@AgoraAudioOutputRoutingDefault","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingDefault"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting/default":{"role":"symbol","title":"AgoraAudioOutputRouting.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[{"type":"text","text":"-1: The default audio route."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingDefault"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting\/default"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting":{"role":"symbol","title":"AgoraAudioOutputRouting","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"abstract":[{"type":"text","text":"The type of the audio route."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioOutputRoutingDefault"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingDefault"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioOutputRoutingDefault"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1default\/title","value":"AgoraAudioOutputRoutingDefault"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1default\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/title","value":"AgoraAudioOutputRouting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}