{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"earpiece"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/earpiece"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/earpiece"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/earpiece","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1: The audio route is an earpiece."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"earpiece"}],"title":"AgoraAudioOutputRouting.earpiece","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioOutputRouting@AgoraAudioOutputRoutingEarpiece","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingEarpiece"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting/earpiece":{"role":"symbol","title":"AgoraAudioOutputRouting.earpiece","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"earpiece"}],"abstract":[{"type":"text","text":"1: The audio route is an earpiece."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/earpiece","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingEarpiece"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting\/earpiece"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting":{"role":"symbol","title":"AgoraAudioOutputRouting","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"abstract":[{"type":"text","text":"The type of the audio route."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioOutputRoutingEarpiece"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingEarpiece"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioOutputRoutingEarpiece"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1earpiece\/title","value":"AgoraAudioOutputRoutingEarpiece"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1earpiece\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingEarpiece"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/title","value":"AgoraAudioOutputRouting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}