{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loudspeaker"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/loudspeaker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/loudspeaker"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/loudspeaker","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"4: The audio route is an external speaker."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loudspeaker"}],"title":"AgoraAudioOutputRouting.loudspeaker","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioOutputRouting@AgoraAudioOutputRoutingLoudspeaker","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingLoudspeaker"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting/loudspeaker":{"role":"symbol","title":"AgoraAudioOutputRouting.loudspeaker","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loudspeaker"}],"abstract":[{"type":"text","text":"4: The audio route is an external speaker."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/loudspeaker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingLoudspeaker"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting\/loudspeaker"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting":{"role":"symbol","title":"AgoraAudioOutputRouting","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"abstract":[{"type":"text","text":"The type of the audio route."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioOutputRoutingLoudspeaker"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingLoudspeaker"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioOutputRoutingLoudspeaker"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1loudspeaker\/title","value":"AgoraAudioOutputRoutingLoudspeaker"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1loudspeaker\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingLoudspeaker"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/title","value":"AgoraAudioOutputRouting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}