{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerphone"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/speakerphone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraaudiooutputrouting\/speakerphone"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/speakerphone","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"3: The audio route is the speaker that comes with the device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerphone"}],"title":"AgoraAudioOutputRouting.speakerphone","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraAudioOutputRouting@AgoraAudioOutputRoutingSpeakerphone","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingSpeakerphone"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting/speakerphone":{"role":"symbol","title":"AgoraAudioOutputRouting.speakerphone","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerphone"}],"abstract":[{"type":"text","text":"3: The audio route is the speaker that comes with the device."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting\/speakerphone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRoutingSpeakerphone"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting\/speakerphone"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraAudioOutputRouting":{"role":"symbol","title":"AgoraAudioOutputRouting","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"abstract":[{"type":"text","text":"The type of the audio route."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraAudioOutputRouting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}],"url":"\/documentation\/agorartckit\/agoraaudiooutputrouting"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraAudioOutputRoutingSpeakerphone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingSpeakerphone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraAudioOutputRoutingSpeakerphone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1speakerphone\/title","value":"AgoraAudioOutputRoutingSpeakerphone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting~1speakerphone\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRoutingSpeakerphone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/title","value":"AgoraAudioOutputRouting"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraAudioOutputRouting\/fragments","value":[{"kind":"identifier","text":"AgoraAudioOutputRouting"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}