{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindToOwner"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamlifecycle\/bindtoowner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamlifecycle\/bindtoowner"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle\/bindToOwner","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Bind to the owner of the RTMP stream. If the owner leaves the channel, the CDN live streaming stops immediately."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindToOwner"}],"title":"AgoraRtmpStreamLifeCycle.bindToOwner","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamLifeCycle@AgoraRtmpStreamLifeCycleBindToOwner","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToOwner"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamLifeCycle/bindToOwner":{"role":"symbol","title":"AgoraRtmpStreamLifeCycle.bindToOwner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindToOwner"}],"abstract":[{"type":"text","text":"Bind to the owner of the RTMP stream. If the owner leaves the channel, the CDN live streaming stops immediately."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle\/bindToOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToOwner"}],"url":"\/documentation\/agorartckit\/agorartmpstreamlifecycle\/bindtoowner"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamLifeCycle":{"role":"symbol","title":"AgoraRtmpStreamLifeCycle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}],"abstract":[{"type":"text","text":"Lifecycle of the CDN live video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}],"url":"\/documentation\/agorartckit\/agorartmpstreamlifecycle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamLifeCycleBindToOwner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToOwner"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToOwner"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle~1bindToOwner\/title","value":"AgoraRtmpStreamLifeCycleBindToOwner"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle~1bindToOwner\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToOwner"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle\/title","value":"AgoraRtmpStreamLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}