{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindToChannel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorartmpstreamlifecycle\/bindtochannel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorartmpstreamlifecycle\/bindtochannel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle\/bindToChannel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Bind to the channel lifecycle. If all hosts leave the channel, the CDN live streaming stops after 30 seconds."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindToChannel"}],"title":"AgoraRtmpStreamLifeCycle.bindToChannel","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@AgoraRtmpStreamLifeCycle@AgoraRtmpStreamLifeCycleBindToChannel","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToChannel"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamLifeCycle/bindToChannel":{"role":"symbol","title":"AgoraRtmpStreamLifeCycle.bindToChannel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindToChannel"}],"abstract":[{"type":"text","text":"Bind to the channel lifecycle. If all hosts leave the channel, the CDN live streaming stops after 30 seconds."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle\/bindToChannel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToChannel"}],"url":"\/documentation\/agorartckit\/agorartmpstreamlifecycle\/bindtochannel"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraRtmpStreamLifeCycle":{"role":"symbol","title":"AgoraRtmpStreamLifeCycle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}],"abstract":[{"type":"text","text":"Lifecycle of the CDN live video stream."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraRtmpStreamLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}],"url":"\/documentation\/agorartckit\/agorartmpstreamlifecycle"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AgoraRtmpStreamLifeCycleBindToChannel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToChannel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToChannel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle~1bindToChannel\/title","value":"AgoraRtmpStreamLifeCycleBindToChannel"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle~1bindToChannel\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycleBindToChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle\/title","value":"AgoraRtmpStreamLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraRtmpStreamLifeCycle\/fragments","value":[{"kind":"identifier","text":"AgoraRtmpStreamLifeCycle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}