{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_azimuth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_azimuth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_azimuth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_azimuth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The azimuth angle of the remote user or media player relative to the local"},{"type":"text","text":" "},{"type":"text","text":"user. The value range is [0,360], and the unit is degrees, The values are as"},{"type":"text","text":" "},{"type":"text","text":"follows:0: (Default) 0 degrees, which means directly in front on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.90: 90 degrees, which means directly to the left on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.180: 180 degrees, which means directly behind on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.270: 270 degrees, which means directly to the right on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.360: 360 degrees, which means directly in front on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_azimuth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"speaker_azimuth","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSpatialAudioParams(py)speaker_azimuth","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"speaker_azimuth"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams/speaker_azimuth":{"role":"symbol","title":"speaker_azimuth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_azimuth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The azimuth angle of the remote user or media player relative to the local"},{"type":"text","text":" "},{"type":"text","text":"user. The value range is [0,360], and the unit is degrees, The values are as"},{"type":"text","text":" "},{"type":"text","text":"follows:0: (Default) 0 degrees, which means directly in front on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.90: 90 degrees, which means directly to the left on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.180: 180 degrees, which means directly behind on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.270: 270 degrees, which means directly to the right on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane.360: 360 degrees, which means directly in front on the"},{"type":"text","text":" "},{"type":"text","text":"horizontal plane."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_azimuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speaker_azimuth"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_azimuth"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams":{"role":"symbol","title":"AgoraSpatialAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"abstract":[{"type":"text","text":"The spatial audio parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"speaker_azimuth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"speaker_azimuth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_azimuth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_azimuth\/title","value":"speaker_azimuth"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_azimuth\/fragments","value":[{"kind":"identifier","text":"speaker_azimuth"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/title","value":"AgoraSpatialAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}