{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_orientation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_orientation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_orientation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The orientation of the remote user or media player relative to the local"},{"type":"text","text":" "},{"type":"text","text":"user. The value range is [0,180], and the unit is degrees, The values are as"},{"type":"text","text":" "},{"type":"text","text":"follows:0: (Default) 0 degrees, which means that the sound source and"},{"type":"text","text":" "},{"type":"text","text":"listener face the same direction.180: 180 degrees, which means that the sound"},{"type":"text","text":" "},{"type":"text","text":"source and listener face each other."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"speaker_orientation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSpatialAudioParams(py)speaker_orientation","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"speaker_orientation"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams":{"role":"symbol","title":"AgoraSpatialAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"abstract":[{"type":"text","text":"The spatial audio parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams/speaker_orientation":{"role":"symbol","title":"speaker_orientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The orientation of the remote user or media player relative to the local"},{"type":"text","text":" "},{"type":"text","text":"user. The value range is [0,180], and the unit is degrees, The values are as"},{"type":"text","text":" "},{"type":"text","text":"follows:0: (Default) 0 degrees, which means that the sound source and"},{"type":"text","text":" "},{"type":"text","text":"listener face the same direction.180: 180 degrees, which means that the sound"},{"type":"text","text":" "},{"type":"text","text":"source and listener face each other."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_orientation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speaker_orientation"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_orientation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"speaker_orientation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"speaker_orientation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_orientation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/title","value":"AgoraSpatialAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_orientation\/title","value":"speaker_orientation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_orientation\/fragments","value":[{"kind":"identifier","text":"speaker_orientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}