{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_attenuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_attenuation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_attenuation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_attenuation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The sound attenuation coefficient of the remote user or media player. The"},{"type":"text","text":" "},{"type":"text","text":"value range is [0,1]. The values are as follows:0: Broadcast mode, where the"},{"type":"text","text":" "},{"type":"text","text":"volume and timbre are not attenuated with distance, and the volume and timbre"},{"type":"text","text":" "},{"type":"text","text":"heard by local users do not change regardless of distance.(0,0.5): Weak"},{"type":"text","text":" "},{"type":"text","text":"attenuation mode, where the volume and timbre only have a weak attenuation"},{"type":"text","text":" "},{"type":"text","text":"during the propagation, and the sound can travel farther than that in a real"},{"type":"text","text":" "},{"type":"text","text":"environment. enable_air_absorb needs to be enabled at the same time. 0.5:"},{"type":"text","text":" "},{"type":"text","text":"(Default) Simulates the attenuation of the volume in the real environment;"},{"type":"text","text":" "},{"type":"text","text":"the effect is equivalent to not setting the speaker_attenuation"},{"type":"text","text":" "},{"type":"text","text":"parameter.(0.5,1]: Strong attenuation mode, where volume and timbre attenuate"},{"type":"text","text":" "},{"type":"text","text":"rapidly during the propagation. enable_air_absorb needs to be enabled at the"},{"type":"text","text":" "},{"type":"text","text":"same time."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_attenuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"speaker_attenuation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSpatialAudioParams(py)speaker_attenuation","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"speaker_attenuation"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams/speaker_attenuation":{"role":"symbol","title":"speaker_attenuation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_attenuation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The sound attenuation coefficient of the remote user or media player. The"},{"type":"text","text":" "},{"type":"text","text":"value range is [0,1]. The values are as follows:0: Broadcast mode, where the"},{"type":"text","text":" "},{"type":"text","text":"volume and timbre are not attenuated with distance, and the volume and timbre"},{"type":"text","text":" "},{"type":"text","text":"heard by local users do not change regardless of distance.(0,0.5): Weak"},{"type":"text","text":" "},{"type":"text","text":"attenuation mode, where the volume and timbre only have a weak attenuation"},{"type":"text","text":" "},{"type":"text","text":"during the propagation, and the sound can travel farther than that in a real"},{"type":"text","text":" "},{"type":"text","text":"environment. enable_air_absorb needs to be enabled at the same time. 0.5:"},{"type":"text","text":" "},{"type":"text","text":"(Default) Simulates the attenuation of the volume in the real environment;"},{"type":"text","text":" "},{"type":"text","text":"the effect is equivalent to not setting the speaker_attenuation"},{"type":"text","text":" "},{"type":"text","text":"parameter.(0.5,1]: Strong attenuation mode, where volume and timbre attenuate"},{"type":"text","text":" "},{"type":"text","text":"rapidly during the propagation. enable_air_absorb needs to be enabled at the"},{"type":"text","text":" "},{"type":"text","text":"same time."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_attenuation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speaker_attenuation"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_attenuation"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams":{"role":"symbol","title":"AgoraSpatialAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"abstract":[{"type":"text","text":"The spatial audio parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"speaker_attenuation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"speaker_attenuation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_attenuation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_attenuation\/title","value":"speaker_attenuation"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_attenuation\/fragments","value":[{"kind":"identifier","text":"speaker_attenuation"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/title","value":"AgoraSpatialAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}