{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_distance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_distance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_distance","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The distance of the remote user or media player relative to the local user."},{"type":"text","text":" "},{"type":"text","text":"The value range is [1,50], and the unit is meters. The default value is 1"},{"type":"text","text":" "},{"type":"text","text":"meter."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"speaker_distance","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)AgoraSpatialAudioParams(py)speaker_distance","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"speaker_distance"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams":{"role":"symbol","title":"AgoraSpatialAudioParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"abstract":[{"type":"text","text":"The spatial audio parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioParams/speaker_distance":{"role":"symbol","title":"speaker_distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance of the remote user or media player relative to the local user."},{"type":"text","text":" "},{"type":"text","text":"The value range is [1,50], and the unit is meters. The default value is 1"},{"type":"text","text":" "},{"type":"text","text":"meter."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioParams\/speaker_distance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"speaker_distance"}],"url":"\/documentation\/agorartckit\/agoraspatialaudioparams\/speaker_distance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"speaker_distance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"speaker_distance"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker_distance"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/title","value":"AgoraSpatialAudioParams"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioParams"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_distance\/title","value":"speaker_distance"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioParams~1speaker_distance\/fragments","value":[{"kind":"identifier","text":"speaker_distance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}