{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteAudioStreams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mute","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to stop subscribing to the audio streams of all"},{"type":"text","text":" "},{"type":"text","text":"remote users:YES: Stop subscribing to the audio streams of all remote"},{"type":"text","text":" "},{"type":"text","text":"users.NO: Subscribe to the audio streams of all remote users."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/muteallremoteaudiostreams(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/muteallremoteaudiostreams(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteAllRemoteAudioStreams(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio streams of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the local user stops or resumes"},{"type":"text","text":" "},{"type":"text","text":"subscribing to the audio streams of all remote users, including all"},{"type":"text","text":" "},{"type":"text","text":"subsequent users.Call this method after joinChannelByToken [2\/4] .When using"},{"type":"text","text":" "},{"type":"text","text":"the spatial audio effect, if you need to set whether to stop subscribing to"},{"type":"text","text":" "},{"type":"text","text":"the audio streams of all remote users, Agora recommends calling this method"},{"type":"text","text":" "},{"type":"text","text":"instead of the muteAllRemoteAudioStreams method in AgoraRtcEngineKit .After"},{"type":"text","text":" "},{"type":"text","text":"calling this method, you need to call updateSelfPosition and"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition to update the spatial location of the local user and the"},{"type":"text","text":" "},{"type":"text","text":"remote user; otherwise, the settings in this method do not take effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteAudioStreams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"muteAllRemoteAudioStreams(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraBaseSpatialAudioKit(im)muteAllRemoteAudioStreams:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit":{"role":"symbol","title":"AgoraBaseSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"abstract":[{"type":"text","text":"This class contains some of the APIs in the AgoraLocalSpatialAudioKit class."},{"type":"text","text":" "},{"type":"text","text":"The AgoraLocalSpatialAudioKit class inherits from AgoraBaseSpatialAudioKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/muteAllRemoteAudioStreams(_:)":{"role":"symbol","title":"muteAllRemoteAudioStreams(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteAllRemoteAudioStreams"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Stops or resumes subscribing to the audio streams of all remote users."},{"type":"text","text":" "},{"type":"text","text":"After successfully calling this method, the local user stops or resumes"},{"type":"text","text":" "},{"type":"text","text":"subscribing to the audio streams of all remote users, including all"},{"type":"text","text":" "},{"type":"text","text":"subsequent users.Call this method after joinChannelByToken [2\/4] .When using"},{"type":"text","text":" "},{"type":"text","text":"the spatial audio effect, if you need to set whether to stop subscribing to"},{"type":"text","text":" "},{"type":"text","text":"the audio streams of all remote users, Agora recommends calling this method"},{"type":"text","text":" "},{"type":"text","text":"instead of the muteAllRemoteAudioStreams method in AgoraRtcEngineKit .After"},{"type":"text","text":" "},{"type":"text","text":"calling this method, you need to call updateSelfPosition and"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition to update the spatial location of the local user and the"},{"type":"text","text":" "},{"type":"text","text":"remote user; otherwise, the settings in this method do not take effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/muteAllRemoteAudioStreams(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/muteallremoteaudiostreams(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"muteAllRemoteAudioStreams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"muteAllRemoteAudioStreams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mute"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/title","value":"AgoraBaseSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteAllRemoteAudioStreams(_:)\/title","value":"muteAllRemoteAudioStreams:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1muteAllRemoteAudioStreams(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteAllRemoteAudioStreams:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}