{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxAudioRecvCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"maxCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]},{"kind":"parameters","parameters":[{"name":"maxCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum number of streams that a user can receive within a specified audio reception range. The value of this parameter should be ≤ 16, and the default value is 10."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the number of receivable streams exceeds the set value, the local user receives the maxCount streams that are closest to the local user."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/setmaxaudiorecvcount(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/setmaxaudiorecvcount(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setMaxAudioRecvCount(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the maximum number of streams that a user can receive in a specified audio reception range."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxAudioRecvCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setMaxAudioRecvCount(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraBaseSpatialAudioKit(im)setMaxAudioRecvCount:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setMaxAudioRecvCount:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/setMaxAudioRecvCount(_:)":{"role":"symbol","title":"setMaxAudioRecvCount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxAudioRecvCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the maximum number of streams that a user can receive in a specified audio reception range."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setMaxAudioRecvCount(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMaxAudioRecvCount:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/setmaxaudiorecvcount(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit":{"role":"symbol","title":"AgoraBaseSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"abstract":[{"type":"text","text":"This class contains some of the APIs in the AgoraLocalSpatialAudioKit class."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setMaxAudioRecvCount:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMaxAudioRecvCount:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMaxAudioRecvCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"maxCount"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setMaxAudioRecvCount(_:)\/title","value":"setMaxAudioRecvCount:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setMaxAudioRecvCount(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMaxAudioRecvCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/title","value":"AgoraBaseSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}