{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setZones"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"zones"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioZone","text":"AgoraSpatialAudioZone"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"zones","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sound insulation area settings. See AgoraSpatialAudioZone."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/setzones(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/setzones(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setZones(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the sound insulation area."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1In virtual interactive scenarios, you can use this method to set"},{"type":"text","text":" "},{"type":"text","text":"the sound insulation area and sound attenuation coefficient. When the sound"},{"type":"text","text":" "},{"type":"text","text":"source (which can be the user or the media player) and the listener belong to"},{"type":"text","text":" "},{"type":"text","text":"the inside and outside of the sound insulation area, they can experience the"},{"type":"text","text":" "},{"type":"text","text":"attenuation effect of sound similar to the real environment when it"},{"type":"text","text":" "},{"type":"text","text":"encounters a building partition.When the sound source and the listener belong"},{"type":"text","text":" "},{"type":"text","text":"to the inside and outside of the sound insulation area, the sound attenuation"},{"type":"text","text":" "},{"type":"text","text":"effect is determined by the sound attenuation coefficient in"},{"type":"text","text":" "},{"type":"text","text":"AgoraSpatialAudioZone .If the user or media player is in the same sound"},{"type":"text","text":" "},{"type":"text","text":"insulation area, it is not affected by AgoraSpatialAudioZone, and the sound"},{"type":"text","text":" "},{"type":"text","text":"attenuation effect is determined by the attenuation parameter in"},{"type":"text","text":" "},{"type":"text","text":"setPlayerAttenuation or setRemoteAudioAttenuation. If you do not call"},{"type":"text","text":" "},{"type":"text","text":"setPlayerAttenuation or setRemoteAudioAttenuation, the default sound"},{"type":"text","text":" "},{"type":"text","text":"attenuation coefficient of the SDK is 0.5, which simulates the attenuation of"},{"type":"text","text":" "},{"type":"text","text":"the sound in the real environment.If the sound source and the receiver belong"},{"type":"text","text":" "},{"type":"text","text":"to two sound insulation areas, the receiver cannot hear the sound source.If"},{"type":"text","text":" "},{"type":"text","text":"this method is called multiple times, the last sound insulation area set"},{"type":"text","text":" "},{"type":"text","text":"takes effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setZones"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraSpatialAudioZone","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioZone"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"setZones(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraBaseSpatialAudioKit(im)setZones:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"setZones:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/setZones(_:)":{"role":"symbol","title":"setZones(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setZones"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AgoraSpatialAudioZone","preciseIdentifier":"c:objc(cs)AgoraSpatialAudioZone"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Sets the sound insulation area."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1In virtual interactive scenarios, you can use this method to set"},{"type":"text","text":" "},{"type":"text","text":"the sound insulation area and sound attenuation coefficient. When the sound"},{"type":"text","text":" "},{"type":"text","text":"source (which can be the user or the media player) and the listener belong to"},{"type":"text","text":" "},{"type":"text","text":"the inside and outside of the sound insulation area, they can experience the"},{"type":"text","text":" "},{"type":"text","text":"attenuation effect of sound similar to the real environment when it"},{"type":"text","text":" "},{"type":"text","text":"encounters a building partition.When the sound source and the listener belong"},{"type":"text","text":" "},{"type":"text","text":"to the inside and outside of the sound insulation area, the sound attenuation"},{"type":"text","text":" "},{"type":"text","text":"effect is determined by the sound attenuation coefficient in"},{"type":"text","text":" "},{"type":"text","text":"AgoraSpatialAudioZone .If the user or media player is in the same sound"},{"type":"text","text":" "},{"type":"text","text":"insulation area, it is not affected by AgoraSpatialAudioZone, and the sound"},{"type":"text","text":" "},{"type":"text","text":"attenuation effect is determined by the attenuation parameter in"},{"type":"text","text":" "},{"type":"text","text":"setPlayerAttenuation or setRemoteAudioAttenuation. If you do not call"},{"type":"text","text":" "},{"type":"text","text":"setPlayerAttenuation or setRemoteAudioAttenuation, the default sound"},{"type":"text","text":" "},{"type":"text","text":"attenuation coefficient of the SDK is 0.5, which simulates the attenuation of"},{"type":"text","text":" "},{"type":"text","text":"the sound in the real environment.If the sound source and the receiver belong"},{"type":"text","text":" "},{"type":"text","text":"to two sound insulation areas, the receiver cannot hear the sound source.If"},{"type":"text","text":" "},{"type":"text","text":"this method is called multiple times, the last sound insulation area set"},{"type":"text","text":" "},{"type":"text","text":"takes effect."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/setZones(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setZones:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/setzones(_:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraSpatialAudioZone":{"role":"symbol","title":"AgoraSpatialAudioZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraSpatialAudioZone"}],"abstract":[{"type":"text","text":"Sound insulation area settings."},{"type":"text","text":" "},{"type":"text","text":"Sincev4.0.1"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraSpatialAudioZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraSpatialAudioZone"}],"url":"\/documentation\/agorartckit\/agoraspatialaudiozone"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit":{"role":"symbol","title":"AgoraBaseSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"abstract":[{"type":"text","text":"This class contains some of the APIs in the AgoraLocalSpatialAudioKit class."},{"type":"text","text":" "},{"type":"text","text":"The AgoraLocalSpatialAudioKit class inherits from AgoraBaseSpatialAudioKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setZones:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setZones:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"setZones:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<AgoraSpatialAudioZone *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zones"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setZones(_:)\/title","value":"setZones:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1setZones(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setZones:"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone\/title","value":"AgoraSpatialAudioZone"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraSpatialAudioZone\/fragments","value":[{"kind":"identifier","text":"AgoraSpatialAudioZone"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/title","value":"AgoraBaseSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}