{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSelfPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"position"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisForward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisUp"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"position","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The coordinates in the world coordinate system. This"},{"type":"text","text":" "},{"type":"text","text":"parameter is an array of length 3, and the three values represent the front,"},{"type":"text","text":" "},{"type":"text","text":"right, and top coordinates in turn."}]}]},{"name":"axisForward","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unit vector of the x axis in the coordinate"},{"type":"text","text":" "},{"type":"text","text":"system. This parameter is an array of length 3, and the three values"},{"type":"text","text":" "},{"type":"text","text":"represent the front, right, and top coordinates in turn."}]}]},{"name":"axisRight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unit vector of the y axis in the coordinate"},{"type":"text","text":" "},{"type":"text","text":"system. This parameter is an array of length 3, and the three values"},{"type":"text","text":" "},{"type":"text","text":"represent the front, right, and top coordinates in turn."}]}]},{"name":"axisUp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unit vector of the z axis in the coordinate system."},{"type":"text","text":" "},{"type":"text","text":"This parameter is an array of length 3, and the three values represent the"},{"type":"text","text":" "},{"type":"text","text":"front, right, and top coordinates in turn."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"0: Success. < 0: Failure."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/updateselfposition(_:axisforward:axisright:axisup:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/agorartckit\/agorabasespatialaudiokit\/updateselfposition(_:axisforward:axisright:axisup:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPosition(_:axisForward:axisRight:axisUp:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Updates the spatial position of the local user."},{"type":"text","text":" "},{"type":"text","text":"Under the AgoraLocalSpatialAudioKit class, this method needs to be used with"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition . The SDK calculates the relative position between the"},{"type":"text","text":" "},{"type":"text","text":"local and remote users according to this method and the parameter settings in"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition, and then calculates the user’s spatial audio effect"},{"type":"text","text":" "},{"type":"text","text":"parameters."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSelfPosition"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisForward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisUp"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"updateSelfPosition(_:axisForward:axisRight:axisUp:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AgoraBaseSpatialAudioKit(im)updateSelfPosition:axisForward:axisRight:axisUp:","modules":[{"name":"AgoraRtcKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateSelfPosition:axisForward:axisRight:axisUp:"}]},"hierarchy":{"paths":[["doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit"]]},"references":{"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit":{"role":"symbol","title":"AgoraBaseSpatialAudioKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"abstract":[{"type":"text","text":"This class contains some of the APIs in the AgoraLocalSpatialAudioKit class."},{"type":"text","text":" "},{"type":"text","text":"The AgoraLocalSpatialAudioKit class inherits from AgoraBaseSpatialAudioKit."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit"},"doc://AgoraRtcKit/documentation/AgoraRtcKit/AgoraBaseSpatialAudioKit/updateSelfPosition(_:axisForward:axisRight:axisUp:)":{"role":"symbol","title":"updateSelfPosition(_:axisForward:axisRight:axisUp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSelfPosition"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisForward"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisRight"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"axisUp"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Updates the spatial position of the local user."},{"type":"text","text":" "},{"type":"text","text":"Under the AgoraLocalSpatialAudioKit class, this method needs to be used with"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition . The SDK calculates the relative position between the"},{"type":"text","text":" "},{"type":"text","text":"local and remote users according to this method and the parameter settings in"},{"type":"text","text":" "},{"type":"text","text":"updateRemotePosition, and then calculates the user’s spatial audio effect"},{"type":"text","text":" "},{"type":"text","text":"parameters."}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit\/AgoraBaseSpatialAudioKit\/updateSelfPosition(_:axisForward:axisRight:axisUp:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateSelfPosition:axisForward:axisRight:axisUp:"}],"url":"\/documentation\/agorartckit\/agorabasespatialaudiokit\/updateselfposition(_:axisforward:axisright:axisup:)"},"doc://AgoraRtcKit/documentation/AgoraRtcKit":{"role":"collection","title":"AgoraRtcKit","abstract":[{"type":"text","text":"Summary"}],"identifier":"doc:\/\/AgoraRtcKit\/documentation\/AgoraRtcKit","kind":"symbol","type":"topic","url":"\/documentation\/agorartckit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateSelfPosition:axisForward:axisRight:axisUp:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSelfPosition:axisForward:axisRight:axisUp:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateSelfPosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"position"},{"kind":"text","text":" "},{"kind":"identifier","text":"axisForward:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"axisForward"},{"kind":"text","text":" "},{"kind":"identifier","text":"axisRight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"axisRight"},{"kind":"text","text":" "},{"kind":"identifier","text":"axisUp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"axisUp"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/title","value":"AgoraBaseSpatialAudioKit"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit\/fragments","value":[{"kind":"identifier","text":"AgoraBaseSpatialAudioKit"}]},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updateSelfPosition(_:axisForward:axisRight:axisUp:)\/title","value":"updateSelfPosition:axisForward:axisRight:axisUp:"},{"op":"replace","path":"\/references\/doc:~1~1AgoraRtcKit~1documentation~1AgoraRtcKit~1AgoraBaseSpatialAudioKit~1updateSelfPosition(_:axisForward:axisRight:axisUp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSelfPosition:axisForward:axisRight:axisUp:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}